### ISSUE TITLE
Stock caffe integration

### ISSUE THREAD

**Issue by jmozah** [NVIDIA/DIGITS#10]
I dont know where to put this... ( i dont find a mailing list for DIGITS yet?)
it would be good if digits is made compatible with the stock Caffe.. 
Is there anything specific in NVIDIA caffe?

./zahoor

**Comment by moconnor725** [comment]
The challenge is that Caffe is a moving target and is managed by the BVLC.  This is why we maintain our own fork of caffe, http://github.com/NVIDIA/caffe, which always works with DIGITS.  We do try hard to keep our caffe fork up to date with the BVLC master but sometimes there is a bit of drift.  

From your error message, it sounds like the python interface has changed on the caffe side and we haven't caught up yet.
