### ISSUE TITLE
WebInstall one_time.sh uninstalls CUDA (& NVIDIA driver)!

### ISSUE THREAD

**Issue by johnmellor** [NVIDIA/DIGITS#101]
The [WebInstall instructions](https://github.com/NVIDIA/DIGITS/blob/v1.0/docs/WebInstall.md) tell you to run a script called `one_time.sh` which runs the following command:

```bash
sudo apt-get install libatlas-base-dev libatlas-dev libboost-all-dev libopencv-dev libprotobuf-dev libgoogle-glog-dev libgflags-dev libhdf5-dev libleveldb-dev liblmdb-dev libsnappy-dev  -y -q
```

But running this uninstalled CUDA (without prompting, due to the `-y -q`)!

This is because `libboost-all-dev` lists `libhwloc-plugins` as a recommended package (and Ubuntu installs recommended packages by default). But `libhwloc-plugins` in turn requires `ocl-icd-libopencl1`, which conflicts with `nvidia-libopencl1-343`, which is required by various CUDA packages.

See https://bugs.launchpad.net/ubuntu/+source/ocl-icd/+bug/1247736 and https://bugs.launchpad.net/ubuntu/+source/nvidia-cuda-toolkit/+bug/1311975.

Hence running `./one_time.sh` caused the following packages to be removed: `cuda cuda-6-5 cuda-drivers cuda-runtime-6-5 nvidia-libopencl1-343`.

And the next time I ran `sudo apt-get autoremove --purge`, since `cuda` had been removed to resolve the conflict, it also removed my NVIDIA driver, amongst other packages:
```
The following packages will be REMOVED
  cuda-command-line-tools-6-5* cuda-core-6-5* cuda-cublas-6-5*
  cuda-cublas-dev-6-5* cuda-cudart-6-5* cuda-cudart-dev-6-5* cuda-cufft-6-5*
  cuda-cufft-dev-6-5* cuda-curand-6-5* cuda-curand-dev-6-5* cuda-cusparse-6-5*
  cuda-cusparse-dev-6-5* cuda-documentation-6-5* cuda-driver-dev-6-5*
  cuda-license-6-5* cuda-misc-headers-6-5* cuda-npp-6-5* cuda-npp-dev-6-5*
  cuda-samples-6-5* cuda-toolkit-6-5* cuda-visual-tools-6-5* freeglut3*
  freeglut3-dev* libxmu-dev* libxmu-headers* linux-headers-3.13.0-44*
  linux-headers-3.13.0-44-generic* linux-image-3.13.0-44-generic*
  linux-image-extra-3.13.0-44-generic* linux-signed-image-3.13.0-44-generic*
  nvidia-343-dev* nvidia-modprobe*
```

## Proposed solution

Changing `run_once.sh` to install `libboost-all-dev` with `--no-install-recommends` solves the conflict (since `libhwloc-plugins` and hence `ocl-icd-libopencl1` will not be installed). Specifically, `run_once.sh` should run the following commands:
```bash
sudo apt-get install --no-install-recommends libboost-all-dev  -y -q
sudo apt-get install libatlas-base-dev libatlas-dev libopencv-dev libprotobuf-dev libgoogle-glog-dev libgflags-dev libhdf5-dev libleveldb-dev liblmdb-dev libsnappy-dev  -y -q
```

DIGITS seems to work fine without `libhwloc-plugins` and `ocl-icd-libopencl1`.

## Additional info

I noticed later on that the [WebInstall instructions](https://github.com/NVIDIA/DIGITS/blob/v1.0/docs/WebInstall.md) say that "CUDA driver of version 346 or later" is required, and I only have 343. But 343 is the latest version available when you download https://developer.nvidia.com/cuda-downloads-geforce-gtx9xx (I have a GTX 970) and install it [as instructed](http://developer.download.nvidia.com/compute/cuda/6_5/rel/docs2/CUDA_Getting_Started_Linux.pdf):

```bash
$ sudo dpkg -i cuda-repo-ubuntu1404-6-5-prod_6.5-19_amd64.deb
$ sudo apt-get update
$ sudo apt-get install cuda
$ echo 'export PATH=/usr/local/cuda-6.5/bin:$PATH' >> ~/.profile
$ echo 'export LD_LIBRARY_PATH=/usr/local/cuda-6.5/lib64:$LD_LIBRARY_PATH' >> ~/.profile
```

**Comment by lukeyeager** [comment]
Thanks for the great bug report, and sorry for the trouble! I'll test this and get the issue fixed for the next release.

**Comment by lukeyeager** [comment]
That seems to work, thanks again!

>  the WebInstall instructions say that "CUDA driver of version 346 or later" is required

You're right, 343 should be sufficient for the 1.0 installer since it comes with CUDA 6.5. That's a documentation bug. The next version of the installer will come with CUDA 7.0 and you **will** need to have 346 or higher installed.

**Comment by tjdevWorks** [comment]
I am trying to install caffe on 16.04 Ubuntu (with cuda 8.0 and cudnn 6.0 installed) for setting up NVIDIA DIGITS but when is run the command:

`sudo apt-get install --no-install-recommends libboost-all-dev  -y -q`

It gives me this error:
The following packages have unmet dependencies:
 libboost-all-dev : Depends: libboost-date-time-dev but it is not going to be installed
                    Depends: libboost-filesystem-dev but it is not going to be installed
                    Depends: libboost-graph-dev but it is not going to be installed
                    Depends: libboost-graph-parallel-dev but it is not going to be installed
                    Depends: libboost-iostreams-dev but it is not going to be installed
                    Depends: libboost-log-dev but it is not going to be installed
                    Depends: libboost-mpi-dev but it is not going to be installed
                    Depends: libboost-mpi-python-dev but it is not going to be installed
                    Depends: libboost-program-options-dev but it is not going to be installed
                    Depends: libboost-regex-dev but it is not going to be installed
                    Depends: libboost-serialization-dev but it is not going to be installed
                    Depends: libboost-system-dev but it is not going to be installed
                    Depends: libboost-thread-dev but it is not going to be installed
                    Depends: libboost-wave-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
