### ISSUE TITLE
"Error : you do not have read access to folder" in DIGITS 4.0

### ISSUE THREAD

**Issue by youngwanLEE** [NVIDIA/DIGITS#1013]
When I make a new dataset, I faced this error. 

"ERROR : you do not have read access to folder /home/youngwan/caffe/data/food_train_added"

However, actually there is the folder in exactly location.

the weird thing is that till yesterday I made a new dataset normally with exactly same way.

**Comment by gheinrich** [comment]
Hello, this [doc](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/docs/UbuntuInstall.md#permissions) might be relevant to your problem.

**Comment by youngwanLEE** [comment]
@gheinrich thanks for reply. I have a question.

In "the entire chain of directories from / to your data must be readable by www-data",

what is mean 'www-data' ?? i can't understand that sentence.

**Comment by gheinrich** [comment]
`www-data` is a username on your system. The doc states that the user must be able to read your data. This implies that the data files must be readable by this user and also all the parent folders up to `/` must be readable and executable by this user.

**Comment by youngwanLEE** [comment]
@gheinrich oh I see. Thank you

I have a one more question. Today I just tried to use the same user name 'youngwan' which is my pc username and I could make LMDB file on yesterday. 

How to permit or authorize the DIGITS to access the folder ??

**Comment by gheinrich** [comment]
I don't know what happened on your machine between yesterday and today but if you're using deb packages then the data must be accessible by user `www-data`. If you're running the server manually then the data must be accessible by the user the started the server.

**Comment by youngwanLEE** [comment]
@gheinrich  Thanks for your reply. 

Is there any re-install DIGITS manual or documentation ?

**Comment by gheinrich** [comment]
If anything is missing from [there](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/docs/UbuntuInstall.md) let us know. The paragraph on access permissions looks pretty clear to me.

**Comment by youngwanLEE** [comment]
@gheinrich I don't realize why this problem happened.

The DIGITS 4.0 was installed by apt-get update & apt-get install digits(Deb package installations)

And I usually open DIGITS in "http://localhost/"

I just followed the manual... :( 

Then, I can't find your remove and re-install DIGITS instruction in your link.

So I just apt-get update && apt-get install digits again. But command window showed that there is no any upgraded message.

**Comment by gheinrich** [comment]
This isn't specific to DIGITS. Refer to the [apt-get manual](http://linux.die.net/man/8/apt-get). You may use the `remove` flag to remove packages. Not sure what you are trying to do though. Re-installing DIGITS won't change the fact that your data must be readable by `www-data`.

**Comment by youngwanLEE** [comment]
@gheinrich You mean if I installed and played digits by Deb package, I could access the dataset by www-data. Yes I did. I installed and played digits by Deb package and could play 'localhost'. But I faced that problem.

**Comment by gheinrich** [comment]
You can verify two things:

1. `namei -l /home/youngwan/caffe/data/food_train_added` and make sure `www-data` has the right permissions on the whole chain leading up to your image files
2. have a look at this [post](https://github.com/NVIDIA/DIGITS/issues/778#issuecomment-234181154).
