### ISSUE TITLE
Greyed out delete-group button is clickable.

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#1014]
See title.

![image](https://cloud.githubusercontent.com/assets/7721540/18050494/33a2aeea-6def-11e6-8045-db1fdc661567.png)
![image](https://cloud.githubusercontent.com/assets/7721540/18050498/364d616c-6def-11e6-93de-8dd76637d7cc.png)

- [ ] Disable button
- [ ] Put whitespace after the word 'selected'
- [ ] Specify 'related files'

What do the 'related files' encompass?
I guess for deleting a dataset that means deleting all models.
When deleting models, does that then remove pretrained models?

**Comment by gheinrich** [comment]
Well spotted Tim!

When a job is deleted the corresponding job directory is deleted. An error is dropped if you attempt to delete a dataset that has models associated to it. If a model is created from a pre-trained model then deleting the job does not delete the pre-trained model.

**Comment by TimZaman** [comment]
Ah, I see. In that case i think the second warning line is redundant, or change it to say it cannot be reverted/un-done. Grouping is really handy though. If I had to whine I'd say the (location of the) 'Use grouping' checkbox hurts my Feng shui.

**Comment by lukeyeager** [comment]
Closed by https://github.com/NVIDIA/DIGITS/pull/1049.
