### ISSUE TITLE
memory issue while following tutorial on object detection

### ISSUE THREAD

**Issue by JVR32** [NVIDIA/DIGITS#1018]
Hello,

I'm following the example in [https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection].
I use the graphics card : **NVIDIA GeForce GTX970** -> 4096 MB.

In the document, I read : 

> NOTE: this instance of DetectNet requires at least 12GB of GPU memory. If you have less memory on your GPU[s], you may want to decrease the batch size. On a 4GB card, you can set the batch size to 2 and the batch accumulation to 5, for an effective batch of 10, and that should fit on your card.

So, since I have a GPU with 4GB, I used the settings as mentioned (batch size = 2 ; accum. = 5). But it still runs out of memory. A few seconds after starting, digits is stopped with following error message : 

![error](https://cloud.githubusercontent.com/assets/19925967/18090465/29f23b3c-6ec5-11e6-9300-94a517798274.jpg)

I tried some other settings (e.g. batch size = 1 ; accum. = 4), but it always get stuck.
Any suggestions?

Regards.

**Comment by gheinrich** [comment]
Hello, how did you establish that you had a GPU memory issue? Did you check `caffe_output.log` from the model page? In particular, can you make sure you have installed Python OpenCV bindings (`sudo apt-get install python-opencv`)

**Comment by JVR32** [comment]
I thought it had to be a memory issue because of the 'memory required ...' in the error message. I'll check the log, and check the Python OpenCV bindings ...

**Comment by JVR32** [comment]
You were right!
In the log file I noticed : 

> ImportError: No module named cv2

Installing OpenCV in Python fixed the problem.

Thank you so much!
