### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by Dahandla** [NVIDIA/DIGITS#1026]
The DIGITS server runs as www-data, so keep in mind that prebuilt LMDB datasets used for generic models need to be readable by the www-data user. In particular, the entire chain of directories from / to your data must be readable by www-data.

when creating a new classification dataset, I enter an existing path but it says: 

Training images folder

```
folder does not exist
```

Hello, I am just getting started with Ubuntu and Digits , I am completely new to this tech , so please keep that in mind if you answer:

could someone please explain to a new user what are the steps to get my data set to read or what location they need to be in

I am running it on localhost/

thank you

**Comment by lukeyeager** [comment]
Here's one way to do it:

```sh
# create a new top-level directory
sudo mkdir /data

# make yourself the owner of the new directory
sudo chown `id -u`:`id -g` /data

# move the data that you care about into this new directory
mv my-data /data/

# make the entire directory readable by everyone (including `www-data`)
chmod -R +r /data
```

**Comment by komms** [comment]
In my case, as I'm using the container. I linked the dataset folder on the host with the a folder on the docker using -v tag. 
**docker run --runtime=nvidia -d -v /data/digits:/data  -p 5000:5000 nvidia/digits**
