### ISSUE TITLE
Custom Object Detection Model Failed

### ISSUE THREAD

**Issue by skyzhao3q** [NVIDIA/DIGITS#1029]
# I want to make a object detection(signA detection) model using the "DetectNet".
## 1. Prepare train data and val data.
image(size: 1920 * 1080 )
label (for example: 
signA 0 0 0 1136 351 1264 351 1136 479 1264 479 0 0 0 0 0 0 0 
signB 0 0 0 1327 235 1455 235 1327 363 1455 363 0 0 0 0 0 0 0)
the size of bbox is : 128 * 128

## 2. Create new object Detection Dataset with

+ Pad image: 1920 , 1080

+ Custom classe:  dontcare,signA

the others are left by default.
And the dataset created successfully.
## 3. Create new object detection model with the "DetectNet"
I changed some parameters because the size of image is different withe images in the tutorial.
mine: 1920 * 1080
tutorial: 1248 * 384
so I changed these values in the "DetectNet" definition.

+ 1248 -> 1920
+ 384 -> 1080
+ 352 -> 1048

Finally I got some error like these when training the model.

> ERROR: Check failed: bottom[i]->shape() == bottom[0]->shape()
Creating layer coverage/sig
Creating Layer coverage/sig
coverage/sig <- cvg/classifier
coverage/sig -> coverage
Setting up coverage/sig
Top shape: 1 1 67 120 (8040)
Memory required for data: 3015697088
Creating layer bbox/regressor
Creating Layer bbox/regressor
bbox/regressor <- pool5/drop_s1_pool5/drop_s1_0_split_1
bbox/regressor -> bboxes
Setting up bbox/regressor
Top shape: 1 4 67 120 (32160)
Memory required for data: 3015825728
Creating layer bbox_mask
Creating Layer bbox_mask
bbox_mask <- bboxes
bbox_mask <- coverage-block
bbox_mask -> bboxes-masked
Check failed: bottom[i]->shape() == bottom[0]->shape()
        
## What is wrong ? Or How can I create a custom object detection model?

thank you.

**Comment by skyzhao3q** [comment]
@lukeyeager thank you

**Comment by lukeyeager** [comment]
Please contribute to that thread if you have further questions.

**Comment by fdesmedt** [comment]
@skyzhao3q   Did you find out how to solve this issue? I am currently having the same issue, having the same train of thoughs, and seem not be able to solve it. The comments of #980 where not able to help me so far

**Comment by Ali-Maher** [comment]
@skyzhao3q , I just checked your data set format , I think you should to change the Bounding box representation in annotation files ( 4 points) . to be (X_min Y_min X_max Y_max ) 2 points only . you can refer to this figure:
![figure5-768x93](https://cloud.githubusercontent.com/assets/23374006/20336804/eeba054c-ac07-11e6-8f9e-11b7888a4f5f.png)

**Comment by skyzhao3q** [comment]
@fdesmedt I haven't solve this issue so far. In other  words I can't make a custom class model successfully.However I actually made a pedestrian model using kitti-data.You can see details here
https://github.com/skyzhao3q/NvidiaDigitsObjDetect

**Comment by skyzhao3q** [comment]
@Ali-Maher Thank you for your advice. I found this mistake later and corrected it. But it seems that the problem is more than this.

**Comment by yunjiezh** [comment]
@skyzhao3q have you solved the problem? I'm trying the same thing

**Comment by TheMikeyR** [comment]
I'm in the same boat, having issues with 1920x1080 images
