### ISSUE TITLE
Disabling "Minimum box size" in object detection datasets

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/DIGITS#1030]
When creating an "object detection dataset", the field "Minimum box size (in pixels) for validation set" doesn't allow the value 0. Although the tool-tip indicates that 0 is used to disable the threshold.

**Comment by gheinrich** [comment]
Thanks for the feedback. I have a candidate fix on #1031 - if you wish to help test the fix that would be much appreciated.

**Comment by sherifshehata** [comment]
Thank you for your fix. I tried it and it works.
