### ISSUE TITLE
Inspect database after training

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DIGITS#1032]
It's suggestion for enhancement.

It will be good if after network is trained we can apply it to train or val data to see what samples are the hardest and maybe remove them from DB if they are noise\outliers\mistakes.

**Comment by gheinrich** [comment]
Hello, for classification networks you can provide the `train.txt` or `val.txt` files from your dataset job directory in `Test a list of images`. Then you get a confusion matrix like [there](https://github.com/NVIDIA/DIGITS/tree/digits-4.0/examples/text-classification#verification) and you can review all individual predictions to find out which ones are incorrect.

**Comment by mrgloom** [comment]
Ok, I understand.
But there is no option to sort predictions by confidence and visually inspect images it will be a good option for data cleaning or understanding weak sides of classifier.
