### ISSUE TITLE
Classification task related questions

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DIGITS#1033]
1. Where lmdb databases are stored? Can I change directory?
2. Where model snaphots are stored? Can I change directory?
3. Can I avoid creation of lmdb database and run training and prediction directly on .jpg images?
4. Can NVIDIA DIGITS work with custom caffe branches? For example if I would like to test classification task with [Spartial Pyramid Pooling layer](https://github.com/ShaoqingRen/SPP_net), how to test if this branch compatible with NVIDIA DIGITS?

**Comment by gheinrich** [comment]
Hello,

> Where lmdb databases are stored? Can I change directory?
> Where model snaphots are stored? Can I change directory?

These are stored in the job directory. You can find the location of the job directory on the job page. All jobs are stored within the same top-level job folder. The location of the top-level job folder can be changed by editing the DIGITS configuration - [details](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/UbuntuInstall.md#configuration) 

> Can I avoid creation of lmdb database and run training and prediction directly on .jpg images?

No, for image classification, we support only HDF5 and LMDB data storage.

> Can NVIDIA DIGITS work with custom caffe branches? For example if I would like to test classification task with Spartial Pyramid Pooling layer, how to test if this branch compatible with NVIDIA DIGITS?

DIGITS 4.0 works with the master branch of the BVLC fork and with the caffe-0.15 branch of the NVIDIA fork. You can try other branches at your own risk. You can try running the automatic tests in `/digits-test` to sanity check your installation.
