### ISSUE TITLE
How to do data augmentation on the fly?

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DIGITS#1034]
Is it possible to do data augmentation on the fly with DIGITS?
 If not maybe some special Caffe layer can be used? like here https://github.com/kevinlin311tw/caffe-augmentation

**Comment by gheinrich** [comment]
Hello,

Caffe's `Data` layer supports data augmentation in the form or random cropping and random flipping. If you're looking for more elaborate data augmentation you can insert a custom layer. For example [DetectNet](https://github.com/NVIDIA/caffe/tree/caffe-0.15/examples/kitti)  performs on-the-fly data augmentation with the `DetectNetTransformation` layer (this layer is specific for object detection - not re-usable for general purpose data augmentation).

**Comment by gheinrich** [comment]
I forgot to say (how could I!) that if you're using Torch then we support a pretty elaborate set of data transformations directly in DIGITS UI. See @TimZaman 's PR #777

**Comment by TimZaman** [comment]
Yeah I should do a short doc/helper/"?" on the augmentation some time.

There was a great layer in Caffe at one point adapted from work at Princeton. It was called COMPACT_DATA, and the layer was like, you get the idea ([link](https://github.com/ChenglongChen/caffe-windows)):
```py
transform_param {
    mean_file: "path-to-image-mean"
    mirror: true
    crop_size: 32
    multiscale: true
    debug_display: false  
    smooth_filtering: false
    jpeg_compression: false
    contrast_adjustment: false
    min_scaling_factor: 0.8
    max_scaling_factor: 1.2
    angle_interval: 45
    max_shearing_ratio: 0.1
    max_perspective_ratio: 0.1
    warp_fillval: 255
  }
```
Sadly this didn't come close to a PR in Caffe. I have tried wrapping this up in a PR myself but the implementation of Princeton is 2 years old and I would effectively have to do _everything_ over again. So currently Torch is your best bet.
If you _do_ want to stick with Caffe, cook yourself a custom python layer, which DIGITS supports:
https://github.com/NVIDIA/DIGITS/blob/master/digits/templates/models/python_layer_explanation.html . That should work, right @gheinrich ?

**Comment by gheinrich** [comment]
> If you do want to stick with Caffe, cook yourself a custom python layer, which DIGITS supports

Sure, Python layers are ideal for quick experiments, if you're not too concerned about perf.

**Comment by lukeyeager** [comment]
It looks like your question has been answered. Please open a new issue for any follow-up questions.
