### ISSUE TITLE
Are standard networks pretrained?

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DIGITS#1036]
Are standard networks shipped with DIGITS pretrained?
If not, how can I load pretrained on ImageNet weights of AlexNet?

**Comment by gheinrich** [comment]
Hello, standard networks in DIGITS are not pre-trained. You can find an ILSVRC2012 pre-trained Alexnet from e.g. [Caffe's model zoo](https://github.com/BVLC/caffe/tree/rc3/models/bvlc_alexnet). Also have a look at the [fine-tuning guide](https://github.com/NVIDIA/DIGITS/tree/v4.0.0/examples/fine-tuning).
