### ISSUE TITLE
Feature suggestion: different resize values for train and val

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/DIGITS#1042]
I suggest that you allow the user to set different resize values for training and validation in object detection dataset creation.

**Comment by gheinrich** [comment]
Hello, can you explain how you would use this? In general in machine learning, the recommendation is to draw training and validation examples from the same distribution so it sounds unusual to have different image sizes for those.

**Comment by sherifshehata** [comment]
one possible usage is if the training set is not full images. 

I agree that it is reasonable to have the same size for training and testing, and After some thinking i believe the current features could be used to handle different cases
