### ISSUE TITLE
custom class mappings #Object-Detection 

### ISSUE THREAD

**Issue by skyzhao3q** [NVIDIA/DIGITS#1046]
I am trying to train my own DetectNet from custom dataset. But the class of object is not contained in the default class mapping. Types are something like these as below:
> signf1 0 0 0 1540 80 1668 208 0 0 0 0 0 0 0
> signa1 0 0 0 447 306 575 434 0 0 0 0 0 0 0
> signb1 0 0 0 1734 112 1862 240 0 0 0 0 0 0 0
> signb2 0 0 0 472 11 600 139 0 0 0 0 0 0 0
> signg 0 0 0 634 53 762 181 0 0 0 0 0 0 0
 
The **`signa1`** is the object to be detected. I think the `**Custom classes**` should be set as 
`**dontcare,signa1**` when training my custom dataset.
Is this right? How could I handle these custom classes ?

**Comment by gheinrich** [comment]
Yes. Did you see this [doc](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/digits/extensions/data/objectDetection/README.md#custom-class-mappings)?

**Comment by skyzhao3q** [comment]
@gheinrich Yes, I have read that. But I am not sure my understanding is right or not.
