### ISSUE TITLE
Validation images with no objects

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/DIGITS#1054]
Hello,
I was trying to create a validation object detection dataset which contains images with no objects. First i tried to create it using empty label files, but digits gave me the error ""Label key 0000 not found in label folder".

I handled this issue by adding a "dummy" label for these images. But i think this is not the best solution.

**Comment by gheinrich** [comment]
Hello, what would be a better solution? It seems reasonable to me to expect one label file per image. You can have empty label files.

**Comment by sherifshehata** [comment]
I agree it is reasonable to have a label file per image. But the case is that i provide empty label files and it gives the error "Label key 0000 not found in label folder".

**Comment by sherifshehata** [comment]
To make it work i added the following dummy line in each label file:
"dummy 0.0 0 0.0 0 0 1 1 0.0 0.0 0.0 0.0 0.0 0.0 0.0"

Using empty label files didn't work

**Comment by gheinrich** [comment]
Thanks for letting us know- this needs fixing indeed!

**Comment by sherifshehata** [comment]
Glad to be of help. And thank you for your continuous and prompt support.
