### ISSUE TITLE
Classification script example.py broken?

### ISSUE THREAD

**Issue by achaiah** [NVIDIA/DIGITS#1055]
I tried to use the [example.py](https://github.com/NVIDIA/DIGITS/blob/master/examples/classification/example.py) script to classify images but it seems that the script is broken.  I'm getting 5 results that are static no matter the input image, each listing 1.0000% as their confidence level.

Has anyone recently looked at it to see if it needs tweaking?

**Comment by lukeyeager** [comment]
Seems to be working for me:
```
$ ./use_archive.py 20161031-100930-8396_epoch_30.0.tar.gz ~/Desktop/lena.jpg 
Extracting tarfile ...
Unknown file: solver.prototxt
Unknown file: train_val.prototxt
Unknown file: info.json
Unknown file: original.prototxt
Processed 1/1 images in 0.004512 seconds ...
---------------- Prediction for /home/lyeager/Desktop/lena.jpg -----------------
 96.5435% - "8"
  2.9436% - "2"
  0.3707% - "0"
  0.0728% - "4"
  0.0539% - "3"

Script took 0.750832 seconds.
```
Did you figure it out from your end?

**Comment by achaiah** [comment]
Hmm I'll try again in a few. You seem to be using a different script. Previously I tried calling example.py directly with the parameters it requires and it generated bad results.

**Comment by achaiah** [comment]
Just gave it a shot and the script seems to be unable to find caffe. I'm running DIGITS 5.0RC and the training + recognition works fine using the web interface but not using the script :(

Traceback (most recent call last):
  File "./use_archive.py", line 15, in <module>
    from example import classify
  File "/scratch/ai/frameworks/digits/examples/classification/example.py", line 20, in <module>
    import caffe  # noqa
ImportError: No module named caffe

**Comment by lukeyeager** [comment]
Just set your PYTHONPATH appropriately:
```sh
export PYTHONPATH=$CAFFE_ROOT/python:$PYTHONPATH
```
DIGITS does this for you automatically ([here](https://github.com/NVIDIA/DIGITS/blob/v5.0.0-rc.1/digits/config/caffe.py#L34)), but you're not running inside of DIGITS for this example.

**Comment by achaiah** [comment]
Ah, great, didn't know which env variable was needed here.  Thanks, that did the trick!

**Comment by achaiah** [comment]
Oh quick question... I have a fairly large model so while recognition takes 0.1s the whole script takes 15s.  Any way to preload the model into memory so it doesn't incur the overhead?

**Comment by gheinrich** [comment]
There is an example on this project: https://github.com/NVIDIA/gpu-rest-engine

**Comment by achaiah** [comment]
Perfect, thanks!
