### ISSUE TITLE
DetectNet: ERROR: error code 1

### ISSUE THREAD

**Issue by StevenSama** [NVIDIA/DIGITS#1056]
the caffe output log:
[caffe_output.txt](https://github.com/NVIDIA/DIGITS/files/466727/caffe_output.txt)
train the detectnet use kitti dataset
-----------------------
dataset desc:
KITTI

Done 10:46:30 AM

DB backend: lmdb
Create train_db DB
Entry Count: 6373
Feature shape (3, 384, 1248)
Label shape (1, 25, 16)
Create val_db DB
Entry Count: 1108
Feature shape (3, 384, 1248)
Label shape (1, 19, 16)
----------------
train error:
Memory required for data: 3824638080
Creating layer bbox_loss
Creating Layer bbox_loss
bbox_loss <- bboxes-obj-masked-norm
bbox_loss <- bbox-obj-label-norm
bbox_loss -> loss_bbox
Setting up bbox_loss
Top shape: (1)
with loss weight 2
Memory required for data: 3824638084
Creating layer coverage_loss
Creating Layer coverage_loss
coverage_loss <- coverage_coverage/sig_0_split_0
coverage_loss <- coverage-label_slice-label_4_split_0
coverage_loss -> loss_coverage
Setting up coverage_loss
Top shape: (1)
with loss weight 1
Memory required for data: 3824638088
Creating layer cluster

GPU: nvidia m40x4
python-opencv was installed sucessfully

network desc
https://raw.githubusercontent.com/NVIDIA/caffe/caffe-0.15/examples/kitti/detectnet_network.prototxt

**Comment by gheinrich** [comment]
The `caffe_output.log` would be more useful than the full dump of your model description. Can you check you have Python bindings for OpenCV installed (`apt-get install python-opencv`)?

**Comment by StevenSama** [comment]
python-opencv was installed sucessfully

**Comment by StevenSama** [comment]
[caffe_output.txt](https://github.com/NVIDIA/DIGITS/files/466726/caffe_output.txt)

**Comment by lukeyeager** [comment]
@StevenSama here are the relevant lines at the end of your Caffe log:
```
I0912 15:26:10.511989  4682 layer_factory.hpp:77] Creating layer cluster
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/caffe/layers/detectnet/clustering.py", line 3, in <module>
import cv2 as cv
ImportError: libnppc.so.7.5: cannot open shared object file: No such file or directory
```
Looks like your build of OpenCV is trying to find NPP. My guess is that you build OpenCV from source (why?) and you haven't set `LD_LIBRARY_PATH` in such a way that OpenCV can find your NPP DSO's.

**Comment by athmanal** [comment]
Hi,I am having the same issue here.could you please let me know hoe to correct this issue? what should the LD_LIBRARY_PATH be and how can I reinstall python-opencv??

**Comment by lukeyeager** [comment]
These are the instructions we recommend for building Caffe:
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildCaffe.md

If you have multiple versions of OpenCV installed, that's going to be really tricky to untangle. If you want a clean system, you may want to look into using the nvidia-docker DIGITS image:
https://github.com/NVIDIA/nvidia-docker/wiki/DIGITS

**Comment by StevenSama** [comment]
/usr/local/cuda/lib64/libnppc.so.7.5 install from nvidia cuda 7.5 will fix it.

**Comment by StevenSama** [comment]
@lukeyeager thanks a lot!
