### ISSUE TITLE
Error code -9 when creating a custom object detection dataset

### ISSUE THREAD

**Issue by DarylWM** [NVIDIA/DIGITS#1057]
Hello.

I'm attempting to create a custom data set but get "ERROR: error code -9". I haven't found an explanation for it. The create_train_db_db.log contains this; no mention of the error:

```
WARNING: log_file config option not found - no log file is being saved
2016-09-10 23:23:27 [INFO ] Created features db for stage train_db in train_db/features
```
Does anybody know what this error means?

Thanks,
Daryl.

**Comment by lukeyeager** [comment]
This SO post seems relevant:
http://stackoverflow.com/a/18529453/2404152

**Comment by DarylWM** [comment]
Indeed - thanks.
