### ISSUE TITLE
Upload Text File has no Way of Specifying Path on Local System

### ISSUE THREAD

**Issue by cancan101** [NVIDIA/DIGITS#106]
The text file with all of the images is stored on the machine running DIGITS as opposed to the machine my browser is running on.
![image](https://cloud.githubusercontent.com/assets/51059/7625597/a389fc2e-f9c7-11e4-9926-d2a11c56bda0.png)

**Comment by lukeyeager** [comment]
Are you saying the instructions should be made clearer, or are you asking for new functionality?

You can't just provide a local filesystem folder without a bunch of client-side javascript uploading the images - DIGITS obviously doesn't have access to pull files from a client machine.

Without adding new features to DIGITS, you have three options:

1. Copy the images to the machine that is running DIGITS manually.
2. Mount the client-side image folder on your DIGITS server so that DIGITS can reach them on it's local filesystem.
3. Make the images accessible through apache or nginx and provide a textfile of URLs instead of filesystem paths.

Any suggestions on how to improve the labels and tooltips to make this functionality more clear?

**Comment by cancan101** [comment]
I am saying this is the opposite problem.

All of my data is already on the machine running DIGITS so why does the text file (with files and labels) have to be on the _client_ (browser) machine.

**Comment by lukeyeager** [comment]
Oh, it doesn't have to be. DIGITS is going to look for the files locally. Did you try it already?

**Comment by cancan101** [comment]
How do I specify to DIGITS to use a local text file? the "choose file" selector wants a file on my client computer.

**Comment by lukeyeager** [comment]
Oh now I see what you're getting at. DIGITS expects the textfile to be on the client machine and the images to be on the server. I can see how that's weird.

Uh, for now you can just copy the textfile to your client and upload it through the form.

How would you suggest making changes moving forward? DIGITS is going to have to figure out how to transfer data between machines for #108, and we might as well start moving that way now.

**Comment by cancan101** [comment]
Maybe add an additional input option like:
![image](https://cloud.githubusercontent.com/assets/51059/7637193/2470dd86-fa3a-11e4-9586-e54e7110c971.png)

The same issue applies to the labels txt folder as well.

**Comment by lukeyeager** [comment]
Yeah, that would work. It would be really nice if there was an autocomplete feature for inputting paths to local files. That's obviously a security concern, but DIGITS isn't really built for security for now anyway.

**Comment by sbodenstein** [comment]
Any update on this? Its really inconvenient when dealing huge training sets. For example, I'm doing some training where the text file of path names to the training images is over 700mb. The path names are automatically created on the host machine. Having to download to client then upload back to host is seriously annoying.

**Comment by lukeyeager** [comment]
@sbodenstein, thanks for bumping this. I'll knock this a little higher in the TODO queue. 

Can you create your images with the folder structure that DIGITS expects? That would let you simply enter the path to a folder once and do away with the textfiles entirely.

https://github.com/NVIDIA/DIGITS/blob/v2.0.0-rc2/docs/ImageFolderFormat.md

**Comment by sbodenstein** [comment]
A common use case is something like this: you have the entire ImageNet dataset, and you want to train a classifier on a subset of this. It would be highly annoying to have to reshape your directory structure to put the images in your required format.

**Comment by lukeyeager** [comment]
I solved that problem with symlinks:
https://github.com/NVIDIA/DIGITS/blob/v2.0.0-rc2/docs/ImageFolderFormat.md#example-use-case---imagenet-subset

Feel free to use that hack if you like, but it's not a reasonable long-term solution.
