### ISSUE TITLE
am I running out of gpu memory?

### ISSUE THREAD

**Issue by lasandcris** [NVIDIA/DIGITS#1065]
Hi,

I'm not sure what this error is pointing to but i'm getting the following error (this is my error log):

Top shape: (1)
with loss weight 1
Memory required for data: 229963956
Creating layer accuracy
Creating Layer accuracy
accuracy <- score_score_0_split_1
accuracy <- label_label_0_split_1
accuracy -> accuracy
Setting up accuracy
Top shape: (1)
Memory required for data: 229963960
accuracy does not need backward computation.
loss needs backward computation.
score_score_0_split needs backward computation.
score needs backward computation.
upscore needs backward computation.
score_fr needs backward computation.
drop7 needs backward computation.
relu7 needs backward computation.
fc7 needs bac*** Check failure stack trace: ***

Thanks for helping out.
laszlo

**Comment by gheinrich** [comment]
Hi, can you post the whole `caffe_output.log`? There might be a clue in there.

**Comment by lasandcris** [comment]
[caffe_output.txt](https://github.com/NVIDIA/DIGITS/files/472715/caffe_output.txt)

there is also something I just noticed. I can't preview the db I just made - so it might be to do with that.

**Comment by gheinrich** [comment]
Are you using Windows? Did you follow these [instructions](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildDigitsWindows.md)? Can you give more context (the dataset your are training on, the network you are using, etc.)?

cc @IsaacYangSLA

**Comment by lasandcris** [comment]
i'm replicating the semantic segmentation example with my own dataset. everything is the same as in the example - which works using the example dataset - but not using mine. I made sure that the sizes of images for both features and labels match and have the same name (not ext). the labels are 1 channel png images. 

Strangely, as I mentioned, the db appears corrupt for some strange reason. I can't view the actual db data. not for training/val or for feature/label. my image shapes are: 

train_db DB
Feature shape  
(3L, 375L, 500L) 
Label shape  
(1L, 375L, 500L) 

val_db DB
Feature shape  
(3L, 281L, 500L) 
Label shape  
(1L, 281L, 500L) 

and yes, its windows built.

**Comment by lasandcris** [comment]
sorry, got mixed up with the other dataset with the shapes, these are mine:

Feature shape for stage train_db: (3L, 480L, 640L)
Label shape for stage train_db: (1L, 480L, 640L)
Feature shape for stage val_db: (3L, 478L, 640L)
Label shape for stage val_db: (1L, 478L, 640L)

**Comment by lasandcris** [comment]
One more thing:

I'm using the Coco dataset images for training. I used their json to parse out the segmentation for each image and wrote out my own png labels for all 85 categories. I wrote the labels as 8U1C and left the jpg images for features as they were (24bit). if you want i'll send you some example images.

**Comment by gheinrich** [comment]
Hi @lasandcris your data shapes look correct. Unfortunately the error you get is a bit cryptic and doesn't tell us much. It would help if you can find a way to get a more explicit error. I found it that FCN-Alexnet works well on a variety of datasets and with different image sizes. Can you let us know which version of Caffe/CuDNN you are using? Note that Windows is not officially supported and it might be hard for us to help further.

**Comment by lasandcris** [comment]
Hi @gheinrich , I'm using v0.15 branch of caffe with DetectNet which I ported to windows (Cuda8, without CuDNN - I'm working on it to fix this). There wasn't any problem with it - its happily working with the dataset using the example. 

I did some more tests yesterday and the only difference I can narrow it down to is that the VOC dataset is using paletted images as labels and the one I created is a grayscale 1 channel. I know this shouldn't cause problems but I'm having problems even creating the database. There is no error from caffe/digits but its not possible to view the images once the database is created, which makes me think that it must to do with the images themselves. 

If you want to test the dataset out yourself I'm happy to send you the entire dataset or a sample from it, this is my email: lrikker@hotmail.com.

thanks,
laszlo

**Comment by lasandcris** [comment]
Had some more time and done some further tests. It seems that grayscale label databases end up corrupt and am unable to use them for training. It looks as you can only use paletted image labels at the moment (not sure why - I haven't looked into that). 

Saying that, I was unable to generate useful platted images from the labels I have. I used PIL - but the only time it worked was when I didn't use any flags at conversion but that gave a really compressed range of values. Using the Adaptive flag gave a full range of values but that didn't work during creating the DB and digits returned a Value Error (all label images must use the same palette). Can you guys recommend a treid and tested conversion?

thanks

**Comment by gheinrich** [comment]
Hello, for the labels I recommend you use a lossless format like PNG. You can provide:
- grayscale (8-bit, single-channel) images,
- palette (8-bit, single-channel) images,
- RGB (8-bit, triple-channel) images, in which case you need to provide the class-to-color mappings through a separate text file.

If you have ImageMagic installed you can use the `identify` command to check that your images have the expected format.

It is very important to have contiguous values in the resulting image. For example if you have 3 classes the only pixel values in your image should be 0,1,2 (possibly 255 too if you want to use it as a `dontcare` - see this [directive](https://github.com/NVIDIA/DIGITS/blob/c88d568491c4ea3f6c0eb308cdd999b5a0a10d8e/examples/semantic-segmentation/fcn_alexnet.prototxt#L322))

In your case you seem to be willing grayscale images so you may use mode `L` when converting your images:
`
img = img.convert('L')
img.save('img.png')
`

**Comment by lasandcris** [comment]
_"It is very important to have contiguous values in the resulting image. For example if you have 3 classes the only pixel values in your image should be 0,1,2"__

this is what I didn't do!! So, this must be the problem - I did the whole imageMagick/python/c++ options to convert the labels in different ways, I think I exhausted all possibilities ;)

i'll give it a go now. thanks.
are you guys coming to gtc?

**Comment by gheinrich** [comment]
Sure, I'll be at GTC EU in Amsterdam. I'd be glad to talk to you then.

**Comment by lasandcris** [comment]
awesome - we'll meet then - got a list of questions to ask :0

**Comment by lasandcris** [comment]
Its working! - the ordering of pixel values of classes was the problem. you see, before I've taken real care making sure I had an even spread between classes ranging from 0-255 - what a mistake! of course it makes sense only assigning the number of classes as label values.
thanks,
laszlo

**Comment by gheinrich** [comment]
Thanks for the feedback and if you have fun examples to share I'd be glad to see them!
