### ISSUE TITLE
Using DetectNet model from python?

### ISSUE THREAD

**Issue by hudvin** [NVIDIA/DIGITS#1078]
Can you provide please any examples on how to use detecnet model from python code?

**Comment by gheinrich** [comment]
Hello, you can use the [classification script](https://github.com/NVIDIA/DIGITS/tree/digits-4.0/examples/classification) as an example. Note the DetectNet performs mean subtraction in the network so you don't have to do it in your script.

**Comment by varunvv** [comment]
@gheinrich 

I  tried to use the modified classification scrip to detect objects using a model trained by DetectNet.
I could get correct result through DIGITS interface but not able to get the same result using classification script. Can you give some more details about the modifications in classification script.

**Comment by thaiat** [comment]
same issue for me, struggling to figure out how to run the object detection in python with the downoaded model. I took a look at the classification script but i can t understand how to adapt it to detection

**Comment by RSly** [comment]
Hi,
I also tried the forward pass in python without much success.
I get this error:
blob.cpp:113] Check failed: data_

here is some part of the code
-------------
net = caffe.Net(model_def,      # defines the structure of the model
                model_weights,  # contains the trained weights
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
transformer.set_transpose('data', (2,0,1))  # move image channels to outermost dimension
transformer.set_raw_scale('data', 255)      # rescale from [0, 1] to [0, 255]
transformer.set_channel_swap('data', (2,1,0))  # swap channels from RGB to BGR

_, channels, height, width = transformer.inputs['data']
image = caffe.io.load_image(img_path)
image = scipy.misc.imresize(image, (height, width), 'bilinear')

net.blobs['data'].data[...] = transformer.preprocess('data', image)
output = net.forward()

--------------------

any suggestion?

**Comment by varunvv** [comment]
Use below steps instead of 
"transformer.preprocess('data', image)"

[assuming batch size is 1]

image = image.transpose(2,0,1)
#Please do necessary resizing 
net.blobs['data'].data[0] = image
start = time.time()
output = net.forward()
end = time.time()

This change helped me.

**Comment by RSly** [comment]
Thanks @varunvv I followed your suggestion but the problem remains

It is interesting to see that it works fine with a 1 class detectnet, my problem arises with the 2class detect net.

@gheinrich any idea why this _data problem could happen with the 2class detectnet?

**Comment by gheinrich** [comment]
It's a bit puzzling since the 1-class and 2-class detectnets take the same input.

**Comment by RSly** [comment]
@gheinrich Yes, I am also surprised. could you reproduce the same error?

**Comment by ShervinAr** [comment]
@thaiat  Hi, could you manage to run the python code to perform inference for DetectNet?

**Comment by ShervinAr** [comment]
@hudvin Hi, did you figure out which parts of the classification example should be modified to perform inference using DetectNet?

**Comment by ShervinAr** [comment]
@gheinrich  could you please provide more details on exactly which parts of the classification example python code should be modified to perform detection using a trained DetectNet model?

**Comment by lukeyeager** [comment]
Please see https://github.com/NVIDIA/DIGITS/issues/1404.
