### ISSUE TITLE
No GPU option in digits-devserver

### ISSUE THREAD

**Issue by araml** [NVIDIA/DIGITS#1085]
I've followed the build instructions https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md but when I try to classify from digits-devserver I don't have any GPU to select, for example these gpu options dont appear [https://github.com/NVIDIA/DIGITS/raw/master/docs/images/new-model-bottom-half.jpg](url) . Now the .py device_query in digits/digits/ returns 
```
     ./device_query.py 
      No devices found.
```
While caffe's device_query returns the correct gpu I have.

Also the CPU_ONLY flag was NOT selected while building caffe.

**Comment by lukeyeager** [comment]
I suspect that DIGITS may not be able to find `libcudart.so` on standard paths. Have you set up your environment in one of these ways?
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/InstallCuda.md#environment

**Comment by araml** [comment]
@lukeyeager Thanks its using GPU now. Shouldn't NVIDIA's CUDA Toolkit Installer set these paths? (Cuda 8.0).

**Comment by lukeyeager** [comment]
> Shouldn't NVIDIA's CUDA Toolkit Installer set these paths?

I think so, yeah. Did you install with a deb package or the runfile?

**Comment by araml** [comment]
@lukeyeager Used the runfile because the .deb installed drivers that were not working with opencv's CUDA functions.

**Comment by lukeyeager** [comment]
Read carefully through this guide:
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/InstallCuda.md

It won't take you nearly as long as it would to read through the big boy guide:
http://docs.nvidia.com/cuda/cuda-installation-guide-linux

I personally always use deb packages to install CUDA (install `cuda-toolkit-7-5` instead of `cuda`) and runfiles to install the driver.

**Comment by shab07** [comment]
@lukeyeager ./device_query.py lists down the GPU devices. This works fine
when I launch ./digits-devserver, digits is up on local host.
and further more I have generated the dataset and ready to start the training. But I get This error
[ERROR] Train Caffe Model task failed with error code -6
and digits says memory required.
GPU devices menu is missing.
KIndly guide
