### ISSUE TITLE
dpnn module required error

### ISSUE THREAD

**Issue by gonzalolc** [NVIDIA/DIGITS#1087]
Hello

I've just reinstalled all torch packages for running the text-classification example.
I already did `luarocks install dpnn`
and I get the following error:

ERROR: /usr/share/lua/5.1/trepl/init.lua:384: .../share/digits/digits/jobs/20160919-102150-25c4/model.lua:1: dpnn module required: luarocks install dpnn

My luarocks list:
luarocks list
Warning: Failed loading manifest for /home/gonzalo/.luarocks/lib/luarocks/rocks: /home/gonzalo/.luarocks/lib/luarocks/rocks/manifest: No such file or directory

Installed rocks:
----------------

argcheck
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

cudnn
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

cunn
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

cutorch
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

cwrap
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

dok
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

dpnn
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

env
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

gnuplot
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

graph
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

hdf5
   0-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

image
   1.1.alpha-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

lightningmdb
   0.9.18.2-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

lpeg
   1.0.0-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

lua-cjson
   2.1devel-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

lua-pb
   scm-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

luaffi
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

luafilesystem
   1.6.3-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

moses
   1.4.0-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

nccl
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

nn
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

nngraph
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

nnx
   0.1-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

optim
   1.0.5-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

paths
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

penlight
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

qtlua
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

qttorch
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

struct
   1.4-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

sundown
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

sys
   1.1-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

tds
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

threads
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

torch
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

totem
   0-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

trepl
   scm-1 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

xlua
   1.0-0 (installed) - /home/gonzalo/torch/install/lib/luarocks/rocks

I also tried restarting the digits server.
How can I solve this?

**Comment by gheinrich** [comment]
Hello, you still seem to have a system install (`/usr/share/lua`). That shouldn't be the case if you followed the Torch (source) install instructions. Maybe you need to un-install the `torch7-nv` package? Otherwise, can you seek help on https://github.com/Element-Research/dpnn?

**Comment by gonzalolc** [comment]
Yes I have a system install (under /usr/share/lua). Should be under /usr/local right?
How do I do that? sorry for my noobery! I installed torch from http://torch.ch/docs/getting-started.html
instructions
Thanks

**Comment by gheinrich** [comment]
Hi, I don't think you're supposed to have any `lua` stuff in `/usr/` if you're doing the source install. Maybe your system install is a remnant of a previous installation of `torch7-nv` deb package. Can you uninstall that package in that case?

**Comment by gonzalolc** [comment]
ok I uninstalled torch7-nv... but this disables the usage of torch in digits.

**Comment by gonzalolc** [comment]
for some reason it was searching the dpnn package under /usr/lib/luarocks and as I din't sudo when installing dpnn, it installed in ~/torch... directory
I just `sudo luarocks install dpnn` and it started working

Thanks for your help
