### ISSUE TITLE
Pills Called Images

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#1098]
We could rename the pills that say 'Images' to their line above it, because they are not necessarily images anymore. Also it'd be cleaner.

![image](https://cloud.githubusercontent.com/assets/7721540/18682285/4a7cfc9c-7f74-11e6-8181-a38b490d2e70.png)

![image](https://cloud.githubusercontent.com/assets/7721540/18682292/58e38c1a-7f74-11e6-89f5-b7ca9366ae4f.png)

**Comment by gheinrich** [comment]
`Images` is not static: it is coming from the category [there](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/views.py#L88). If you define a new category then a new pill will show such as in the [text classification](https://github.com/NVIDIA/DIGITS/pull/1025) workflow:
![img](https://cloud.githubusercontent.com/assets/3889770/18686323/d27b263a-7f7b-11e6-8bc9-403445aa00dc.png)

**Comment by TimZaman** [comment]
Oh wow.. I didn't even see i didn't have the categories enabled.
