### ISSUE TITLE
ERROR: 'ascii' codec can't decode byte 0xd8 in position 55: ordinal not in range(128)

### ISSUE THREAD

**Issue by StevenSama** [NVIDIA/DIGITS#1100]
create dataset error:
**dataset info:**
Image Dimensions
256x256 (Width x Height)
Image Type
Color
Resize Transformation
Fill
DB Backend
lmdb
Image Encoding
png
DB Compression
none
----------------------
Traceback (most recent call last):
  File "/data/digits/digits/scheduler.py", line 507, in run_task
    resources -- the resources allocated for this task
  File "/data/digits/digits/task.py", line 220, in run
    for line in utils.nonblocking_readlines(p.stdout):
  File "/data/digits/digits/utils/__init__.py", line 66, in nonblocking_readlines
    yield buf[:(n+1)].decode(enc)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 55: ordinal not in range(128)

**Comment by gheinrich** [comment]
Hi @StevenSama this error is probably due to the fact that your system locale is UTF8 and you have unicode in your file names. Can you check this post and see if this helps in your particular case: https://github.com/NVIDIA/DIGITS/issues/353#issuecomment-147445084

**Comment by StevenSama** [comment]
thanks @gheinrich ifound that change the Resize Transformation to Squash no error happen in the same dataset,

**Comment by StevenSama** [comment]
it helps,thanks @gheinrich
