### ISSUE TITLE
Subtracting dataset mean in deploy [Object detection]

### ISSUE THREAD

**Issue by sherifshehata** [NVIDIA/DIGITS#1104]
Hello,
In detectnet, the mean value (127) is subtracted using the data transformation layer. I decided to disable this mean subtraction and work with the dataset mean, by using the "Subtract Mean" feature during training job creation. I noticed that the generated prototxt files contain mean subtraction in "train_val.prototxt", but not in "deploy.prototxt"

I also noticed that the generated "deploy.prototxt" is using old "data input" format.

**Comment by gheinrich** [comment]
During inference the mean is subtracted during pre-processing in the [Caffe transformer](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/model/tasks/caffe_train.py#L1391-L1395). Do you still think there is an issue here?

**Comment by sherifshehata** [comment]
Thanks for clarification.
