### ISSUE TITLE
A valid Caffe installation was not found on your system. Use the envvar CAFFE_ROOT to indicate a valid installation.

### ISSUE THREAD

**Issue by Jmx5200** [NVIDIA/DIGITS#1107]
### # this is the error information, my caffe is in /home/mx/caffe/
A valid Caffe installation was not found on your system.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "./digits-devserver", line 8, in <module>
    import digits.config
  File "/home/mx/digits/digits/config/__init__.py", line 7, in <module>
    from . import caffe
  File "/home/mx/digits/digits/config/caffe.py", line 227, in <module>
    executable, version, flavor = load_from_path()
  File "/home/mx/digits/digits/config/caffe.py", line 51, in load_from_path
    raise ValueError('Caffe executable not found in PATH')
ValueError: Caffe executable not found in PATH

**Comment by gheinrich** [comment]
Hello, with #1091 merged now you need to use environment variables to configure DIGITS. The environment variables are listed [there](https://github.com/NVIDIA/DIGITS/blob/e615f4ec79de27187c7d389ffac92e263f059631/docs/Configuration.md). In your case you need to set the `CAFFE_ROOT` variable: `export CAFFE_ROOT=/home/mx/caffe/`.

**Comment by Jmx5200** [comment]
Thanks very much ,but every time I use digits,I must input CAFFE_ROOT=/home/mx/caffe/ in terminal,  
maybe I should write the environment variables into a file, how to do it?

**Comment by lukeyeager** [comment]
```sh
# These instructions are for bash
$ echo $SHELL
/bin/bash

# Check the current value of your envvar
$ echo $CAFFE_ROOT

# Add the envvar to ~/.profile so it will load automatically when you login
$ echo "export CAFFE_ROOT=/home/username/caffe/" >> ~/.profile

# Load the new configuration
$ source ~/.profile

# Check the new envvar value
$ echo $CAFFE_ROOT
/home/username/caffe/
```

If you need more help or if you use a different shell, you can probably find what you need via Google. Setting environment variables is a good skill to learn.

**Comment by drcrook1** [comment]
I am having the same problem, however I have completed these steps and I have CAFFE_ROOT pointing to the correct place. https://github.com/NVIDIA/DIGITS/issues/1390

**Comment by lukeyeager** [comment]
Did you install with a deb package? If so, please follow these instructions for changing the configuration:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md#troubleshooting

**Comment by keryar** [comment]
In my case, when I try to set a CAFFE_ROOT value, it says my path is not valid for some reason.
And CAFFE_ROOT is empty.  I installed my caffe through aptitude dependencies of CUDA, and I need to upgrade it to 0.16v in order to fix a GPU memory error.

**Comment by eric8730** [comment]
I have installed all of the prerequisites. I have the CAFFE_ROOT in /home/user/caffe which is a path.
| _ / | | / |
| |) | | ( || | | | _
|/__|__| || |___/ 6.1.1

A valid Caffe installation was not found on your system.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"main", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/mikulis/digits/digits/main.py", line 70, in
main()
File "/home/mikulis/digits/digits/main.py", line 53, in main
import digits.config
File "digits/config/init.py", line 7, in
from . import ( # noqa
File "digits/config/caffe.py", line 230, in
executable, version, flavor = load_from_path()
File "digits/config/caffe.py", line 54, in load_from_path
raise ValueError('Caffe executable not found in PATH')
ValueError: Caffe executable not found in PATH

thank you so much,
eric
