### ISSUE TITLE
Segmentation Inference - 'module' object has no attribute 'pyplot'

### ISSUE THREAD

**Issue by uschmelmer** [NVIDIA/DIGITS#1117]
Hi,
when i want to infer a segmentation image and choose colormap from dataset, i get the following error:
```
 AttributeError

'module' object has no attribute 'pyplot'
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/udo/programs/digits/digits/webapp.py", line 72, in decorated
    return f(_args, *_kwargs)
  File "/home/udo/programs/digits/digits/model/images/generic/views.py", line 394, in infer_one
    outputs)
  File "/home/udo/programs/digits/digits/model/images/generic/views.py", line 794, in get_inference_visualizations
    extension = extension_class(dataset, **extension_form.data)
  File "/home/udo/programs/digits/digits/extensions/view/imageSegmentation/view.py", line 44, in **init**
    cmap = mpl.colors.ListedColormap(palette)
AttributeError: 'module' object has no attribute `'pyplot'
```
matplotlib seems installed.
Best Regards,
Udo

**Comment by gheinrich** [comment]
Can you try adding this in `digits/extensions/view/imageSegmentation/view.py`?

```python
import matplotlib as mpl
+ import matplotlib.pyplot 
```

In theory we should have to do this though it's working for me without this line, possibly because another package I have is doing this `import matplotlib.pyplot` import implicitly.

**Comment by uschmelmer** [comment]
Hi,
i think i tried it, but i was late at night... 
But i will double check, when i return from work.
Thanks,
Udo

**Comment by uschmelmer** [comment]
Hi,
double checked it. Adding "import matplotlib.pyplot" did not solve the problem.
Best Regards,
Udo

**Comment by uschmelmer** [comment]
So adding import matplotlib.pyplot AND rebooting the machine did the trick for me.
Maybe some process wasn't properly closed..

**Comment by kertansul** [comment]
@gheinrich as suggested 
by adding `RUN mkdir -p ~/.config/matplotlib && echo "backend:agg" > ~/.config/matplotlib/matplotlibrc` in the dockerfile works ! THANKS !

**Comment by jerome0121** [comment]
I have this problem too.
I follow semantic-segmentation step by step, until i created the dataset and clicking the Explore DB, the page show the Error like:
![default](https://cloud.githubusercontent.com/assets/29109888/26660443/c246278c-46aa-11e7-9427-de7f69b77011.PNG)
Same problem when i choose colormap from dataset.
I use the latest digits docker. and i can't find the dockerfile...
