### ISSUE TITLE
object-detection models use in TX1

### ISSUE THREAD

**Issue by FaceOP** [NVIDIA/DIGITS#1132]
Hello every one.
I am a new hand for digits!
Hope some can help me to solve this stupid question!!

I am train a object-detection models with
https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection
this guide and I successfull to detection a Frame
And the result is correct(same answer with guide)

I try to run it at TX1.
But it Irrational to use digits run the same way,Because of TX1's space only 14GB, and it's efficacy is vesy low.
So, I download the models(successfull one ) and put it into TX1,
And....
How can I go next?
How to use this models?
I only know use digits to  detection image ,but  how use this models?
I know caffe has a classification.cpp to use models.
Does object-detection has the similar way to use models?
Thank everyone!

**Comment by MacroHongJian** [comment]
i have the same question too. here U can install digits on tx1. https://github.com/dusty-nv/jetson-inference and i just done at here https://github.com/dusty-nv/jetson-inference/blob/master/docs/building-nvcaffe.md to install nv-caffe but i don't known how to use the model

**Comment by FaceOP** [comment]
I find something to use the download model.
And you can use [dusty-nv](https://github.com/dusty-nv/jetson-inference)
You can use it "detectnet-console" 
And put your own create model to replace the source original model.

**Comment by lukeyeager** [comment]
See https://github.com/NVIDIA/DIGITS/issues/1404 for information about using Python for inference on DetectNet models.

If you want to use C++ for inference instead of Python, check the diff in that gist I posted. It should give you enough information to alter Caffe's `examples/cpp_classification/classification.cpp` on your own.

**Comment by ChenhuiZhao** [comment]
that's a good question, thanks for you guys share your experience!
