### ISSUE TITLE
Binary Segmentation Model on Torch - No mean image

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#1133]
Hmm I don't seem to have a mean.jpg image when I am going through:
https://github.com/nvidia/DIGITS/tree/master/examples/binary-segmentation#using-torch7
My dir looks like:
![image](https://cloud.githubusercontent.com/assets/7721540/19022771/026c9f28-88e0-11e6-82c5-9a54f6cd192f.png)
And I get a _no mean image_ error on tensorflow. How does torch handle a mean image subtraction type being set but no image available? This might be a source of the problem getting the segmentation to converge nicely on torch.

**Comment by TimZaman** [comment]
cc @gheinrich

**Comment by gheinrich** [comment]
Don't you see a `mean.binaryproto` on your screenshot? :-)

**Comment by TimZaman** [comment]
Does Torch support that?

**Comment by gheinrich** [comment]
We could read the `.binaryproto` from the Lua wrappers however the current implementation converts the proto file to an image file in the [Python wrapper for Torch](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/digits/model/tasks/torch_train.py#L111-L133).

**Comment by TimZaman** [comment]
Oh wow that's not very transparant.
So I'll move tf's mean file reader to binaryproto then to circumvent the
whole mean/jpg/png etc thing.
