### ISSUE TITLE
Extracting used classes from trained model?

### ISSUE THREAD

**Issue by JVR32** [NVIDIA/DIGITS#1135]
Hello,

I created an object detection dataset with custom classes : **dontcare,110**, and later on, I used this dataset to train an object detection model.

When using _inference.py_, I have to provide the _model id_.

I know I trained a model for detecting objects of class _110_, but I guess -somehow- it must also be possible to get the used detection class (other than _dontcare_) by accessing a parameter or calling a function in _inference.py_ ?

So, my question is : suppose I wouldn't know the object class that was targeted in an object detection model ... is it possible to discover it in _inference.py_ ?

**Comment by gheinrich** [comment]
Hello, after that [line](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/tools/inference.py#L54) you can access the custom classes with `dataset.extension_userdata['custom_classes']`

**Comment by JVR32** [comment]
That's what I was looking for. Thank you!
