### ISSUE TITLE
UnicodeDecodeError occurred while submiting dataset creation

### ISSUE THREAD

**Issue by c2h2** [NVIDIA/DIGITS#114]
lastest DIGITS installed, following the tutorial: https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md, try to create a dataset.

python throws an error:

UnicodeDecodeError
'ascii' codec can't decode byte 0xe4 in position 9: ordinal not in range(128)

**Comment by c2h2** [comment]
fixed by exporting env:

    export LC_ALL="en_US.utf8"

**Comment by lukeyeager** [comment]
Thanks for reporting this! Where did you find the `LC_ALL` variable? Does it affect how python interprets unicode? I'm assuming you were probably trying to use chinese characters in the name of your dataset, is that correct? Can you post the test string you were using that caused the issue?

**Comment by c2h2** [comment]
I used purely English chars, but i guess somehow ubuntu has no preset LC_ALL. I have put it into my .bashrc file. thanks

**Comment by lukeyeager** [comment]
I'll close this issue as there doesn't appear to be an issue with DIGITS.

**Comment by makman7** [comment]
This because of space in the image path
