### ISSUE TITLE
Digits in CPU Mode

### ISSUE THREAD

**Issue by skyzhao3q** [NVIDIA/DIGITS#1145]
When I run Digits in cpu mode to do the tutorial of kitti-data, I got this Error Message below:

ERROR: Check failed: error == cudaSuccess (29 vs. 0) driver shutting down

It seems the model has been trained and it worked too.

What does the Error Message mean ?

PS: cuda-version is 8.0

**Comment by lukeyeager** [comment]
I think it's a Caffe bug - something in a destructor somewhere. Feel free to open a bug over at `NVIDIA/caffe` if it's a problem.
