### ISSUE TITLE
/usr/bin/python: No module named digits

### ISSUE THREAD

**Issue by naive231** [NVIDIA/DIGITS#1146]
I install DIGITS ok, but when I want to download mnist data from python, it returns that message:

```
igsrd@naivechou/~/project/toyshop/deep_learning/digits>python -m digits.download_data mnist ~/mnist
/usr/bin/python: No module named digits
```

Why?

**Comment by sschoenefeld** [comment]
I assume you installed Digits 4.0 (e.g. from the repository). In this case please use the instructions for downloading the datasets from the 4.0 branch:

https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/StandardDatasets.md

$ python tools/download_data/main.py mnist ~/mnist

Regards,
Stefan

**Comment by naive231** [comment]
You said changing arguments of python:

`python tools/download_data/main.py mnist ~/mnist`

This is a relative path, where is my root path?

**Comment by naive231** [comment]
I get it:
```
cd /usr/share/digits
ython tools/download_data/main.py mnist ~/mnist
```

**Comment by TimZaman** [comment]
Yes you call it from the digits root. Funny, I had the same problem today. I had an old version of DIGITS and was reading the newer Readme 👍
