### ISSUE TITLE
Explore database failed with "TypeError object of type 'NoneType' has no len()"

### ISSUE THREAD

**Issue by korabelnikov** [NVIDIA/DIGITS#1147]
![image](https://cloud.githubusercontent.com/assets/3808833/19159905/098cca54-8bff-11e6-9c90-06d7979e16bd.png)

![image](https://cloud.githubusercontent.com/assets/3808833/19159923/1a54805c-8bff-11e6-8035-2036dec58429.png)

develop

task is segmentation. all images are good.  database is also good.

**Comment by lukeyeager** [comment]
That's a problem. Can you run DIGITS in debug mode (`digits-devserver -d`) so that we can see which line of code is throwing the error?

**Comment by gheinrich** [comment]
@korabelnikov are you using grayscale labels (not palette)? I think there's a problem with these that I need to fix.

**Comment by korabelnikov** [comment]
@gheinrich yes

**Comment by gheinrich** [comment]
That should be fixed with #1177 thanks.
