### ISSUE TITLE
Classify many, uploads all images to ram?

### ISSUE THREAD

**Issue by Tutufa** [NVIDIA/DIGITS#115]
Hi, Im trying to modify classify many to get scores for test data. I can get csv with scores (for medium size datasets), but if size of input file is too big (~400k images) digits crashes, and prompts to the terminal 'Killed'.  I think its because ram and swap are exhausted. It would be nice to process big files in chunks automatically. Or there is a solution for this problem? I do uncomment some lines to use GPU mode during classifications, it makes it run much faster.

**Comment by lukeyeager** [comment]
You're right, I currently read all images before classifying. It simplifies the code a bit, but it's not really necessary.

This is basically the same issue as #70. DIGITS hasn't been designed for heavy-duty classification. I'll try and clean up the classify many path a bit, but I'm also going to post an example python script that you can start with and that will let you do whatever you want with the results.

**Comment by Tutufa** [comment]
@lukeyeager yep, thanks! I dont understand why you call processing files through nn using digits a heavy - duty (-: I think its kind of natural thing and getting scores fast without wiring to the snapshots is very cool and desired feature, I think. Filter visualization would be ubercool too.

**Comment by lukeyeager** [comment]
> I dont understand why you call processing files through nn using digits a heavy duty

Fair enough. I guess what I'm saying is that at some point, if you want to classify thousands and millions of images quickly, you shouldn't be using python, and thus shouldn't be using the DIGITS classification tools. You should be doing something with C++ (This example would be helpful to have - https://github.com/BVLC/caffe/issues/2487).

But, I can still get something decent working in DIGITS for those who don't want to set up something secondary.

> Filter visualization would be ubercool too.

DIGITS already has it for "Classify One" - are you saying you want to see it for "Classify Many" as well?

**Comment by Tutufa** [comment]
Yeah, probably u are right.  About filters, classify one is pretty cool. I thought that it would be cool to choose blob and visualize filters (like conv layer 3, show all filters) on a separate page, just to look how learned features look like. On classify one filters are small, but its pretty cool to look whether some features has been spotted by nn or not. @lukeyeager

**Comment by tmquan** [comment]
@lukeyeager : It would be nice if you can give us an example show how to use a trained network to classify a particular image in python script, so that we can write our own to perform a heavy-duty classification. 
Ref: http://nbviewer.ipython.org/github/BVLC/caffe/blob/master/examples/classification.ipynb 

Since the categories from digits are different from actual numbered categories in manual folder, it is a bit hard to use in caffe only.

**Comment by lukeyeager** [comment]
@tmquan great idea, I had been considering doing that for a while.

Issue added here: https://github.com/NVIDIA/DIGITS/issues/147.

**Comment by lukeyeager** [comment]
You can now implement this easily yourself by altering the example provided to close #147 in ad5980cf4360bebb30a830df3384adc3de1ca393 at https://github.com/NVIDIA/DIGITS/tree/master/examples/classification.

I'll open a new issue for using RAM efficiently while classifying many images in DIGITS.
