### ISSUE TITLE
incorrect cpu utilization value

### ISSUE THREAD

**Issue by korabelnikov** [NVIDIA/DIGITS#1168]
![image](https://cloud.githubusercontent.com/assets/3808833/19409988/c4f92d84-92f1-11e6-9943-6589fad6fe39.png)

digits 4.1 dev

**Comment by lukeyeager** [comment]
Do you have a corresponding `top` screenshot that proves the value is incorrect? CPU utilization > 100% is perfectly normal - you might be utilizing more than one core.

**Comment by korabelnikov** [comment]
I'm new in linux. if it's normal then OK. Just percentage > 100 looks strange and uninformative.
![image](https://cloud.githubusercontent.com/assets/3808833/19622716/6f60b4b6-98c1-11e6-8442-4c5f798ea773.png)

**Comment by lukeyeager** [comment]
I agree - the convention is a little non-intuitive. If you have 24 cores, then your max utilization is 2400%.

**Comment by korabelnikov** [comment]
@lukeyeager maybe divide the value by number of cores?
`nproc`

**Comment by lukeyeager** [comment]
Thanks for the feedback. For now I think we'll stick with the linux convention since this is expected behavior for people familiar with linux (https://github.com/NVIDIA/DIGITS/pull/800#issue-157498755, https://github.com/NVIDIA/DIGITS/issues/254#issuecomment-168777520, etc.).
