### ISSUE TITLE
Compiling cpp code for inference using a manually written makefile

### ISSUE THREAD

**Issue by szm2015** [NVIDIA/DIGITS#1170]
Hi everyone,

I'm trying to write a code in cpp to perform detection with detectnet. I have no problem with the code when I place it in tools/ and perform cmake .. and make, the code is compiled and it works. but what I'm actually trying to do is to compile the code with my own makefile. but when I do this, running the code results in a seg fault (which occurs after the simplest codes like setting caffe mode).

I have tested my makefile with bvlc caffe and it works (with a classification model) but here ...

here is my makefile:

`CXX=gcc

CFLAGS = -fPIC -Wall -Wno-sign-compare -Wno-uninitialized -O3 -DNDEBUG

INCLUDE = -I. -I/usr/local/cuda/include -I/home/gpuserver/Moosavi/DIGITS/nv-caffe/include/ -I/home/gpuserver/Moosavi/DIGITS/nv-caffe/src/ -isystem /usr/local/cuda-8.0/include -isystem /usr/include/opencv -isystem /usr/include/atlas -isystem /usr/include/python2.7 -isystem /usr/include/x86_64-linux-gnu/python2.7 -isystem /usr/lib/python2.7/dist-packages/numpy/core/include -I/home/gpuserver/Moosavi/DIGITS/nv-caffe/include -I/home/gpuserver/Moosavi/DIGITS/nv-caffe/build -I/home/gpuserver/Moosavi/DIGITS/nv-caffe/3rdparty

LDFLAGS = -L/usr/local/lib -L/usr/local/cuda/lib64 -L/usr/local/cuda/lib -lcudart -lcublas -lcurand -lglog -lgflags -lprotobuf -lleveldb -lsnappy -llmdb -lboost_system -lhdf5_hl -lhdf5 -lm -lopencv_core -lopencv_highgui -lopencv_imgproc -lboost_thread -lstdc++ -lcblas -latlas -L/home/gpuserver/Moosavi/DIGITS/nv-caffe/build/lib/ -lcaffe-nv /home/gpuserver/Moosavi/DIGITS/nv-caffe/build/lib/libcaffe-nv.so.0.15.13 /home/gpuserver/Moosavi/DIGITS/nv-caffe/build/lib/libproto.a -rdynamic /home/gpuserver/Moosavi/DIGITS/nv-caffe/build/lib/libcaffe-nv.so.0.15.13 -Wl,-rpath,/home/gpuserver/Moosavi/DIGITS/nv-caffe/build/lib:/usr/local/cuda-8.0/lib64:::::::: 

SRC = Detection.cpp

OBJS = $(SRC:.c=.o)
EXE = Detection

all:  $(SRC) $(EXE)

clean:
    rm -f _.o
    rm -f $(EXE)
    find ./ -name \_.o  -delete

$(EXE): $(OBJS)
    $(CXX) $(OBJS) $(INCLUDE) $(LDFLAGS) -o $@

.cpp.o:
    $(CXX) $(CFLAGS) $< -o $@
`

I have tried to add all the files used by cmake to compile my code. 
by the way I'm using nvidia caffe 0.15.13, cuda 8.0 and cudnn 5.1.5 on a gtx 1080 gpu.
Thanks for taking the time and reading this! and I appreciate any help greatly!

**Comment by lukeyeager** [comment]
I bet you're missing some crucial build flags. See explanation here: https://github.com/BVLC/caffe/pull/3311#issuecomment-155863722

**Comment by flx42** [comment]
@lukeyeager is right, you need at least [this flag](https://github.com/NVIDIA/gpu-rest-engine/blob/master/inference/classification.cpp#L6)
```

**Comment by flx42** [comment]
Also, look here: https://github.com/NVIDIA/caffe/issues/30#issuecomment-152357416

**Comment by szm2015** [comment]
@flx42 thank you, adding #define USE_CUDNN 1 did the trick!
