### ISSUE TITLE
torch classify many task failed with error code -11

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#1173]
Torch jobs on TravisCI have been failing for a while now (>1 week, <2 weeks):

https://travis-ci.org/NVIDIA/DIGITS/jobs/167788079
https://travis-ci.org/lukeyeager/DIGITS/jobs/167736840
https://travis-ci.org/lukeyeager/DIGITS/jobs/167736180

Things all the test failures have in common:
1. Framework is Torch
2. Test class is `*LeNet*`
   - These are the only tests which use a "real" network (i.e. one with convolution layers)
3. Test name is `*classify_many*` or `*top_n*`
   - These are the only tests which do inference on multiple inputs
4. They all fail with this message: `torch classify many task failed with error code -11`
   - In Python, when a script returns a negative error code, it means the script was killed with a signal. [Signal 11 means](http://man7.org/linux/man-pages/man7/signal.7.html) "SIGSEGV Invalid memory reference".

**Comment by lukeyeager** [comment]
Trying to find the offending change is difficult. Here's what has changed in the last two weeks:

https://github.com/torch/distro/compare/5c7c762518374422873dff5a2da834704f0658db...bd5e664194953539e928546e987c615a481a8eee
https://github.com/torch/nn/compare/c40e59edd2ddfdec166d3557cceaf25898bba52c...a8e63f2da3d3d84a7e1eed917572901a9ffba5d9
https://github.com/torch/torch7/compare/b1ce165d049ec54b38c728d227352f8d2f0d526d...4f7843e8be8de37d0474e9d4a529261b147e8a8e

What's worse is I can't reproduce it locally yet.

@soumith does the numbered list above make you think of any potential breaking changes that may have gone into Torch recently?

**Comment by soumith** [comment]
the bug seems to be around not able to load libcudnn.so

i'm digging into it a bit, but i wonder if anything wrt deploying cudnn onto these build boxes has changed recently

**Comment by lukeyeager** [comment]
I think these messages are just warnings:
```
Failed to load cudnn backend (is libcudnn.so in your library path?)
Failed to load cunn backend (is CUDA installed?)
Falling back to legacy nn backend
```
Thanks for taking a look! I was just hoping you'd think of something off the top of your head - I wasn't asking you to actually dig into it.

**Comment by soumith** [comment]
@lukeyeager i could prob think of the offending change if i knew what the error message that is emmitted from the torch side. Looks like that isn't being logged right now?

**Comment by lukeyeager** [comment]
No, not right now. Once I figure out how to reproduce it, I'll post back here.

**Comment by gheinrich** [comment]
Since it's a segmentation fault there is probably no error message from Torch. I'll see if I can isolate the particular line of code that is causing the crash.

**Comment by gheinrich** [comment]
Hi @soumith it seems like setting the number of threads to 1 (`torch.setnumthreads(1)`) as in #1179 - as opposed to the default `8` - "solves" this issue. Are you aware of any concurrency issues when running convolutions on CPU-only systems? Thanks for your offer to help by the way!

**Comment by gheinrich** [comment]
Thanks for the pointer Soumith. We're installing `libopenblas-dev` package with `apt` so it is impractical for us to rebuild OpenBLAS. However doing `export OPENBLAS_MAIN_FREE=1` at run-time also seems to address the issue. Cheers!

**Comment by lukeyeager** [comment]
Thanks for investigating @gheinrich!

**Comment by lukeyeager** [comment]
It looks like #1179 may not have fixed this entirely.
https://travis-ci.org/lukeyeager/DIGITS/builds/169015952

**Comment by lukeyeager** [comment]
Hmm... 

Torch [installs](https://github.com/torch/distro/blob/4f5ad0ff2c/install-deps#L25) OpenBLAS to it's default location of `/opt/OpenBLAS` ([this line](https://github.com/torch/distro/blob/4f5ad0ff2c/install.sh#L41) tells torch where to find it).

We [cache](https://github.com/NVIDIA/DIGITS/blob/435948676e/.travis.yml#L76) the torch build in DIGITS, but not the OpenBLAS build. Since ToT OpenBLAS has the same SONAME as the version installed with deb packages on 14.04, Torch loads the library just fine.

But it's possible that running a build of torch that was built for ToT OpenBLAS is unable to use the old version that comes on 14.04, and that's why we're seeing memory corruption issues.

Need to rewrite some stuff tomorrow to test this theory...
