### ISSUE TITLE
Interpretation of 'Visualizations and statistics'

### ISSUE THREAD

**Issue by JVR32** [NVIDIA/DIGITS#1176]
Hello,

I trained an object detector.
Let's have a look at the last graphs of  'visualizations and statistics' for a successful detection : 

![visu_ok](https://cloud.githubusercontent.com/assets/19925967/19476612/5a2b3768-953a-11e6-9306-167de2062be6.jpg)

Three objects were found, at the right position. Perfect detection.

Now, let's do the same for a failed detection : 

![visu](https://cloud.githubusercontent.com/assets/19925967/19476661/a91847d0-953a-11e6-9f87-4cbddfc918df.jpg)

In the CVG/classifier-graph, there is a clear detection of an object. It is also at the right location (there is an object in the image that has to be detected).  It's also visible in "coverage".  But somehow, it disappears later on, with the result 'no bounding boxes detected', although it is an object that should be detected.

What might be the reason for that, and is there something I can do so that the object would be detected?

Regards.

**Comment by lukeyeager** [comment]
That detection is being filtered out because of some default thresholds in your network (see [default parameters](https://github.com/NVIDIA/caffe/blob/v0.15.13/examples/kitti/detectnet_network.prototxt#L2504) and [their [lack of] documentation](https://github.com/NVIDIA/caffe/blob/v0.15.13/python/caffe/layers/detectnet/clustering.py#L107-L115).

You can just edit the `deploy.prototxt` file on disk and try again with different thresholds.

**Comment by JVR32** [comment]
Changing 'gridbox_rect_threshold' from '3' into '2' was an improvement. Thanks Luke.

**Comment by lukeyeager** [comment]
No problem. Does that answer your question for now? If so, you can close this.

**Comment by Anjan369** [comment]
@lukeyeager @JVR32 
when I tried this with multi class object detection for 3 class , even though for each class the b-boxlist is showing the values but the rectangle in the object is displaying only for the last class, if I give only class 1 & class 2 Image, b-box list is showing but the rectangle are not drawn, but if I give class 3 image only the bounding box is drawn,
can you help me out in this?
