### ISSUE TITLE
Torch test image "stops" training

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#118]
If you classify an image while a torch model is still training, DIGITS marks the job as "Done", even though the training is still going on in the background.

**Comment by Sravan2j** [comment]
@lukeyeager : I fixed the issue. Could you please check it once. Please let me know if you face any issues. If everything looks good, please close the issue. Thanks for your time and help.

**Comment by lukeyeager** [comment]
LGTM, thanks!
