### ISSUE TITLE
ImportError: No module named caffe.layers.detectnet.clustering

### ISSUE THREAD

**Issue by szm2015** [NVIDIA/DIGITS#1181]
Hi everyone, 

As the title suggests I'm getting the following error when I try to run my inference code for detectnet:
      ImportError: No module named caffe.layers.detectnet.clustering
      terminate called after throwing an instance of 'boost::python::error_already_set'

The error resolves when I copy the exe file to caffe root and execute it there, but remains otherwise.
I have added caffe_root/python to my PYTHONPATH and PATH and running the command:
      python -c "import caffe; print caffe.__file__"
gives me this path:
      /home/gpuserver/Moosavi/DIGITS/nv-caffe/python/caffe/init.pyc

which is the right one.

I'm using nvidia caffe version 0.15.13, and the inference code is written in cpp.

**Comment by lukeyeager** [comment]
Can you post the actual log of the error?

Also, just a thought, is the entry in your PYTHONPATH that contains caffe relative or absolute?

**Comment by szm2015** [comment]
sorry but I don't know what you mean by actual log of error, when I run the code it only gives me the two lines I said and then the program crashes.
I have added caffe to my PYTHONPATH by adding the following line to ~/.bashrc:

     export PYTHONPATH="${PYTHONPATH}:/home/gpuserver/Moosavi/DIGITS/nv-caffe/python

(if that's what you mean)

**Comment by lukeyeager** [comment]
As an example:
```sh
$ ls /not-a-directory
ls: cannot access '/not-a-directory': No such file or directory
```

**Comment by szm2015** [comment]
I'm sorry but I don't understand what this has to do with my question :(

**Comment by lukeyeager** [comment]
Please just post the command you tried to run, and the output that you got (including the error message).

**Comment by szm2015** [comment]
OK, I think the problem is with my IDE, 
This is what I'm doing: 

I write the code in Qt and compile it, when I run it there (by pushing the run button!) I get this message:
ImportError: No module named caffe.layers.detectnet.clustering
terminate called after throwing an instance of 'boost::python::error_already_set'
The program has unexpectedly finished.

but when I open a terminal in my project folder and run the exe by ./EXEname, everything is okey, I haven't tried this before, I just copied the exe to caffe root. but now I see that the problem only occurs when I try to run it from my IDE, though I don't understand why it is like this.

**Comment by lukeyeager** [comment]
Then this is probably a generic IDE configuration issue and not related to Caffe specifically.

**Comment by alpop** [comment]
I had same problem while in IDE (Spyder): ImportError: No module named layers.detectnet.clustering 
It was OK from terminal, too.
It turned out that I had multiple python installations and multiple python caffe modules.
I resolved the issue by removing the offending one with 'conda uninstall caffe
