### ISSUE TITLE
Is it possible to train from two data source and  NOT select a dataset for an object classification model? [caffe]

### ISSUE THREAD

**Issue by enoonIT** [NVIDIA/DIGITS#1183]
I'm trying to use a network which loads data from two separate lmdbs so i'd like to specify those directly in the prototxt, ex:

```
layer {
  name: "data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: false
    crop_size: 227
    mean_file: "data/ilsvrc12/imagenet_mean.binaryproto"
  }
  data_param {
    source: "/home/enoon/libs/DIGITS/digits/jobs/20161007-155515-46ca/train_db"
    batch_size: 50
    backend: LMDB
  }
}
```

But Digits forces you to select a database at model creation. Is there a way around this?

[EDIT]
I tried to launch the training just the same and I got:

> ERROR: cannot specify two train data layers

**Comment by gheinrich** [comment]
Sorry there is no way around this in the classification path as DIGITS needs many things from the dataset (mean, class labels, number of classes, number of samples, etc.). You can however create a generic dataset (select "new dataset>images>other" on the homepage) from your existing LMDBs.

**Comment by enoonIT** [comment]
Ok, thanks for the feedback.
