### ISSUE TITLE
train object detection network on jetson with error code -9

### ISSUE THREAD

**Issue by MacroHongJian** [NVIDIA/DIGITS#1184]
when i tran on jetson TX1 follow by [this](https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection). I got an error but i don't know how to solve it.
below is the output
Top shape: 2 192 48 156 (2875392)
Memory required for data: 403695488
Creating layer inception_3a/1x1
Creating Layer inception_3a/1x1
inception_3a/1x1 <- pool2/3x3_s2_pool2/3x3_s2_0_split_0
inception_3a/1x1 -> inception_3a/1x1
Setting up inception_3a/1x1
Top shape: 2 64 48 156 (958464)
Memory required for data: 407529344
Creating layer inception_3a/relu_1x1
Creating Layer inception_3a/relu_1x1
inception_3a/relu_1x1 <- inception_3a/1x1
inception_3a/relu_1x1 -> inception_3a/1x1 (in-place)
Setting up inception_3a/relu_1x1
Top shape: 2 64 48 156 (958464)
Memory required for data: 411363200
Creating layer inception_3a/3x3_reduce
Creating Layer inception_3a/3x3_reduce
inception_3a/3x3_reduce <- pool2/3x3_s2_pool2/3x3_s2_0_split_1
inception_3a/3x3_reduce -> inception_3a/3x3_reduce

**Comment by gheinrich** [comment]
Hello, `-9` is the code for the SIGKILL signal. This means the program was killed, possibly because it requested too much memory. Training DetectNet on Jetson might be a challenge... can't you use a full-size computer for training?

**Comment by MacroHongJian** [comment]
Thanks, I just want that i can show the object-dection on a portable mechine. So its a useless job. ^_^

**Comment by phansel** [comment]
The DIGITS readme states: 

`NOTE: this instance of DetectNet requires at least 12GB of GPU memory. If you have less memory on your GPU[s], you may want to decrease the batch size. On a 4GB card, you can set the batch size to 2 and the batch accumulation to 5, for an effective batch of 10, and that should fit on your card.`

Did you change the batch size?
