### ISSUE TITLE
Creating Database - Can't find Images

### ISSUE THREAD

**Issue by snuffysasa** [NVIDIA/DIGITS#1189]
I am trying to create a new object detection database. Every time I get an error like 

ERROR: Exception: LoadImageError: "/home/vsi/Desktop/DIGITS/examples/object-detection/kitti-data/train/images/002567.png" not found

The image does exist at that path, along with the rest of the images.  I made sure that the images do exist at the path. Why can't Digits find the images?

I attached log file.
[create_train_db_db(3).txt](https://github.com/NVIDIA/DIGITS/files/540100/create_train_db_db.3.txt)

**Comment by lukeyeager** [comment]
> The DIGITS server runs as www-data, so keep in mind that prebuilt LMDB datasets used for generic models need to be readable by the www-data user. In particular, the entire chain of directories from / to your data must be readable by www-data.
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md#permissions

^ Does that answer your question?
