### ISSUE TITLE
no sunnybrook plugin in Deb packages 14.04

### ISSUE THREAD

**Issue by imrael202** [NVIDIA/DIGITS#1193]
Hello 
i can't add sunnybrook plugin to digits
Digits installed from Deb packages ubuntu 14.04

**Comment by gheinrich** [comment]
Hello, plug-ins are a new feature in DIGITS 5.0. Deb packages haven't been released for 5.0 yet but you can get it from source [there](https://github.com/NVIDIA/DIGITS/tree/digits-5.0).

**Comment by gheinrich** [comment]
Please close if your issue is solved.

**Comment by imrael202** [comment]
thanks!
