### ISSUE TITLE
Filter difference between classification and other dataset

### ISSUE THREAD

**Issue by LucMioulet** [NVIDIA/DIGITS#1194]
Not sure it is an issue, but there is something that is bugging me about the filters generated when using a "classification dataset" or an "other dataset".
Task 1 : create a classification dataset from 3 channel images using the digits interface. Learn from this with any standard network, get good classification accuracy. View a filter on an example. You get usually nice smooth filters on your first convolution.

Task 2 : create an "other dataset" re-using the dataset generated from Task 1. Learn from this using the same architecture, get good classification accuracy. View a filter on an example. You get noise.

I am learning from the same dataset, with the same architecture with close to identical end-results. And yet the filters have nothing in common. This is kind of annoying as I would like to understand what my network is learning. Any ideas how to solve this problem ?

**Comment by gheinrich** [comment]
Sorry I know this doesn't help but I too would expect filters to look similar. Have you been able to double check?

**Comment by gheinrich** [comment]
This would be better addressed on https://groups.google.com/forum/#!forum/digits-users
