### ISSUE TITLE
Can not set caffe path manually as before?

### ISSUE THREAD

**Issue by JulyUp** [NVIDIA/DIGITS#1199]
Hello, I try the new digits-5.0. When I run the command ' ././digits-devserver', it shows error
```
A valid Caffe installation was not found on your system.
Use the envvar CAFFE_ROOT to indicate a valid installation.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/congleng/work/digitssss/digits/digits/__main__.py", line 66, in <module>
    main()
  File "/home/congleng/work/digitssss/digits/digits/__main__.py", line 49, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import caffe
  File "digits/config/caffe.py", line 229, in <module>
    executable, version, flavor = load_from_path()
  File "digits/config/caffe.py", line 51, in load_from_path
    raise ValueError('Caffe executable not found in PATH')
ValueError: Caffe executable not found in PATH
```
Can it not set caffe path manually as digits-4.0?

**Comment by gheinrich** [comment]
Hello, does this give a hint:

`
A valid Caffe installation was not found on your system. Use the envvar CAFFE_ROOT to indicate a valid installation.
`

The configuration is now specified through environment variables only. Refer to the new [5.0 configuration doc](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/Configuration.md).

**Comment by gheinrich** [comment]
@lukeyeager is this likely an inconsistency between the Caffe executable and Python bindings?

**Comment by lukeyeager** [comment]
@michaelholm-ce why are you running `digits-devserver` with `sudo`? That shouldn't be necessary in most cases.

Also, when you use `sudo`, you discard all your environment variables - including `CAFFE_ROOT`.

**Comment by michaelholm-ce** [comment]
Well, that explains it.  I have permission denied without sudo.

**Comment by lukeyeager** [comment]
```sh
$ man sudo
...
     -E, --preserve-env
                 Indicates to the security policy that the user wishes to preserve their existing
                 environment variables.  The security policy may return an error if the user does
                 not have permission to preserve the environment.
```

**Comment by michaelholm-ce** [comment]
Changed owner of DIGITS to my username, and now the correct caffe version is found.  Thank you, @lukeyeager.

**Comment by lukeyeager** [comment]
@JulyUp please close this issue if you are satisfied.

**Comment by JulyUp** [comment]
@gheinrich @lukeyeager Thankyou. Another doubt,When I do `./digits-devserver`and use 'Use Text FIles' in module 'New Image Classification Dataset', how can I upload my local image set and create a new dataset in another windows or ubuntu machine? I tried and failed. It seems digits can not find the image.

**Comment by gheinrich** [comment]
Last question is unrelated to this issue -> closing. @JulyUp please post your question on the DIGITS users list.

**Comment by AzmHmd** [comment]
when I do echo $CAFFE_ROOT, the result is empty. why?

**Comment by lukeyeager** [comment]
@AzmHmd please read up on environment variables in general:
http://askubuntu.com/q/58814/336440
http://stackoverflow.com/q/234742/2404152
etc.
