### ISSUE TITLE
Quality in inference intermediate results

### ISSUE THREAD

**Issue by pansk** [NVIDIA/DIGITS#1200]
While testing autoencoders for image processing, I noticed that some typical artifacts of JPEG compression were appearing in the results.
I couldn't find an option to fix this, what I did is modify the embed_image_html to produce PNGs by default. Here's the diff:

```
@@ -300,7 +300,7 @@ def embed_image_html(image):
     fmt = image.format
     if not fmt:
         # default to JPEG
-        fmt = 'jpeg'
+        fmt = 'png'
     else:
         fmt = fmt.lower()

```

I add here request for image processing: could you put a flag somewhere in the infer_one to show results as an image instead of as an array? And (if this last flag is selected) an option to avoid renormalization of the image?

**Comment by gheinrich** [comment]
Hi @pansk if the output of your network is an image then why don't you use the "image output" visualization method ([example](https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/binary-segmentation#verification))?

**Comment by pansk** [comment]
Sorry, I completely missed the feature. If that's also producing PNGs by default that's perfect.

**Comment by pansk** [comment]
Ok, I have to reopen this issue after checking the new version.
Apparently, the "image output" visualization method is still compressing the result as JPEG (lossy) rather than PNG (lossless). If you're designing an image processing algorithm (e.g. a DAE), you really want lossless compression.
