### ISSUE TITLE
Plans for a multiclass DetectNet anytime soon?

### ISSUE THREAD

**Issue by rtrahms** [NVIDIA/DIGITS#1210]
Hi all -

I have been looking at the DetectNet example, and am attempting to train it on my own datasets.  I discovered that, while multiple classes can exist in the labels (either in the KITTI dataset or my own dataset), DetectNet can only detect one class of object.  Bummer. 
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/digits/extensions/data/objectDetection/README.md#custom-class-mappings
This makes DetectNet (in its current form) not practical for a lot of applications.  I am interested in plans to evolve DetectNet to train on multiple classes like those defined in the label files.

Thanks!
Rob

**Comment by gheinrich** [comment]
Hello, DetectNet supports multi-class object detection - an example was merged on https://github.com/NVIDIA/caffe/pull/157. Warning: this isn't and out-of-the-box solution - this is for advanced users who are willing to spend time adjusting parameters to address their specific use case - there is no guarantee that it will work at all on your data. DIGITS has full support for multi-class object detection during visualization.

**Comment by rtrahms** [comment]
Thanks for the quick response!  I will take a look at this.
Rob
