### ISSUE TITLE
Customize previous network: local variable 'python_layer' referenced before assignment

### ISSUE THREAD

**Issue by dbolkensteyn** [NVIDIA/DIGITS#1215]
I'm following the fine-tuning tutorial here:
https://github.com/NVIDIA/DIGITS/blob/master/examples/fine-tuning/README.md

When I click "Customize" next to my previous LeNet MNIST network, I'm getting this error:
```
500: INTERNAL SERVER ERROR
UnboundLocalError
local variable 'python_layer' referenced before assignment
```

Note that I've left the field above `Python Layers: Server-side file` empty, and that I did select my dataset first.

I'm running DIGITS 5.1:
```
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.1-dev
```

**Comment by lukeyeager** [comment]
Should be fixed by https://github.com/NVIDIA/DIGITS/pull/1202.
