### ISSUE TITLE
Large GPU memory consumption in loading model with nvcaffe+cuDNN

### ISSUE THREAD

**Issue by szm2015** [NVIDIA/DIGITS#1217]
Hi everyone!

I have encountered a weird problem! (at least that's what I think!) I have built nvidia caffe 0.15.13 with cuDNN ver. 5.1.5 and CUDA 8.0 on a GTX 1080 GPU. when I run a detectnet model (with a cpp inference code I have written) at first (when the model is being loaded) about 7 or 8 GB of memory is consumed and then it reduces to about 400 MB while processing each image.

As I was testing on another system without cuDNN and without this problem, I built caffe without cuDNN and the problem resolved, meaning that it consumes less that a 100 MB while loading the model and like before about 400 MB while processing each image. so I assume that the problem is with cuDNN (as everything else is completely the same, caffe version, CUDA, hardware, everything!!!)

Why does this occur? and is there a way to solve it? (to have cuDNN and resolve this issue as well)

Note that I don't have an elegant method to compute memory consumption and I just use watch -n0 nvidia-smi to see how much memory is being used at each stage, if there is such a method (a code a function anything) to show how much memory each part of code uses, I would be grateful to know it!

Thank you.

**Comment by lukeyeager** [comment]
Sorry, I'm not sure what the problem is. The cuDNN convolution algorithms take more memory than the naive convolution algorithms Caffe uses when cuDNN isn't present. That's part of why they're so much faster.

Also, this is not really related to DIGITS. If you think something is wrong, please open a bug at NVIDIA/caffe.

**Comment by szm2015** [comment]
OK thank you I didn't know this fact about cuDNN, and it seems that I can't use it for my application (as it consumes nearly all of memory available at first)

**Comment by lukeyeager** [comment]
Caffe+cuDNN assumes that it can use all memory available in the GPU, but it shouldn't ever use MORE memory than is available on the GPU.

**Comment by szm2015** [comment]
No it doesn't use more than that, it's just that I want to run some programs simultaneously and in this case when one program uses this much of memory (even for a short period of time) the other ones crash,

**Comment by szm2015** [comment]
As you said cuDNN+Caffe uses all the "available" memory so I was able to run my codes (with a delay to pass the pick) with cuDNN. Thank you for your help.
