### ISSUE TITLE
Torch outputs displayed in different order

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#122]
Caffe outputs (1) `loss (train)`, (2) `accuracy (val)`, (3) `loss (val)` in the graph.

Torch outputs (1) `loss (train)`, (2) `loss (val)`, (3) `accuracy (val)`.

The ordering is arbitrary (and in fact I think the Torch ordering might make more sense), but the upshot of this is that the accuracy line is yellow for caffe and green for torch. That's confusing. Let's just make torch match caffe's behavior.

**Comment by Sravan2j** [comment]
@lukeyeager: fixed the issue. Please test it once and close issue if fix looks good. Thanks for your time.

**Comment by lukeyeager** [comment]
Looks good, thanks!

In the future, you can break up these three bugfixes into separate commits so it's more clear what you did to address each issue. No big deal though.
