### ISSUE TITLE
Support for .ppm images

### ISSUE THREAD

**Issue by GiuliaP** [NVIDIA/DIGITS#123]
Hi,

would it be possible to add to DIGITS the possibility of creating a dataset of images in the .ppm format?
I've read that at present .jpg, .png and .bmp are supported.

Thank you,
Giulia

**Comment by lukeyeager** [comment]
@GiuliaP sure, PPM looks pretty straightforward. I'll get to it when I can.

**Comment by GiuliaP** [comment]
Thank you!!
