### ISSUE TITLE
C++ for DIGITS trained classification network

### ISSUE THREAD

**Issue by harewei** [NVIDIA/DIGITS#1231]
Hello
Is there a way to use c++ to perform classification for networks trained with DIGITS?
I know there's a python script in the example, but I could not find any c++ related instructions anywhere.

I did take a look at caffe's own c++ classification code
[](https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp)
but will this work with for digits as well?

**Comment by lukeyeager** [comment]
> but will this work with for digits as well?

DIGITS gives you a `deploy.prototxt` and a `.caffemodel` which together are sufficient to run inference on a Caffe model (with the possible addition of a `mean.binaryproto` and `labels.txt`). So it's not really a question of whether it "works with digits" or not - DIGITS won't be involved at all.

This is probably going to be your best reference for C++ classification with Caffe models:
https://github.com/BVLC/caffe/tree/master/examples/cpp_classification

**Comment by pkrush** [comment]
I would say once you’re writing C++ code you’re out of the DIGITS world. Of you course you can still use the DIGITS job directories. 

I am currently working on a fork for cpp_classification to handle batch inference (classification):
https://github.com/GemHunt/caffe/edit/master/examples/cpp_classification/

This currently works for directories and LMDBs, but needs lot of work to clean it up.
I am using this for tiny LeNet style networks. It’s inferring LMDBs at 40K plus images a second with a GTX970 GPU and a slower CPU. I am very happy with this over what the python module was doing. 
This started from simple changes to batch processing from @flx42:
https://github.com/flx42/caffe/commit/be0bff1a84c9e16fb8e8514dc559f2de5ab1a416

I find it strange that there are all these great tools to build deep learning models, but the production implementations are not documented very well, or don’t exist at all. I can see that the trail blazers are getting bored by this point. 

If you need help feel free to contact me. 
Best, Paul Krush

**Comment by flx42** [comment]
@pkrush I think it's because it's more difficult to come up with a solution for inference that would be generic enough for all use cases, especially when the Caffe library itself is not really helping you.
Images might be in different format, sizes and thus require custom preprocessing.
They may come from HTTP requests, RPC calls, local/remote storage, a database, etc.
Some use cases require batching, other uses cases are focused on latency and so they can't batch.

We have another inference example [here](https://github.com/nvidia/gpu-rest-engine), it's latency optimized and might be a good starting point, but it requires customization too.

Tensorflow has [TensorFlow Serving](https://tensorflow.github.io/serving/) by the way.

**Comment by pkrush** [comment]
Thanks for the great info @flx42 !

**Comment by harewei** [comment]
So I tried using my DIGITS trained network in caffe with
https://github.com/BVLC/caffe/tree/master/examples/cpp_classification
The code runs without any problem and is able to classify, however the classification result is sometimes very different.

The caffe c++ classification requires 6 arguments
1.the executable file, this one is obvious
2.deploy.prototxt, which I grabbed from my trained network job folder
3..caffemodel, which I grabbed the last snapshot iteration number from my trained netowrk job folder
4.mean.binaryproto, which I grabbed from my database folder
5.words.txt, which I created with the classification class names
6.the image to be classified

When I use "classify one image" in DIGITS and using the c++ program on the same .bmp file, sometimes the prediction percentage don't match up and even categorize it into two different things (and oddly enough, the percentage generated by c++ with digits network is always 0.0000 or 1.0000.  If I run the ilsvrc12 example from http://caffe.berkeleyvision.org/gathered/examples/imagenet.html it gives the output identical to the page).

**Comment by flx42** [comment]
The `cpp_classification` code is in `examples`, not `tools`. So you probably need to customize it for your own pre-processing steps.

**Comment by harewei** [comment]
Could you tell me the pre-process used by DIGITS when classifying one image?  Thank you

**Comment by gheinrich** [comment]
@harewei can you share you C++ code if it's working?

**Comment by szm2015** [comment]
Hi everyone
I've written a c++ code to perform inference using a model trained with digits. I do the preprocess in the following steps:
1- resizing the image to networks input size (by opencv default INTER_LINEAR, I have also checked other options but they make no difference).
2. converting the image to BGR
3.converting the result to float
3.subtracting mean. here I manually set the mean subtraction method to the one the nerwork uses. here is the code I use for each method (Image, pixel and none):
`void CaffeClassifier::SetMean (const std::string& mean_file, QString Mean_Method) {
    if (Mean_Method == "Image" || Mean_Method == "Pixel") {
        caffe::BlobProto blob_proto;
        ReadProtoFromBinaryFileOrDie (mean_file.c_str(), &blob_proto);

        // Convert from BlobProto to Blob<float>
        caffe::Blob<float> mean_blob;
        mean_blob.FromProto(blob_proto);
        CHECK_EQ(mean_blob.channels(), num_channels_)
             << "Number of channels of mean file doesn't match input layer.";

        if (Mean_Method == "Pixel") {
            // The format of the mean file is planar 32-bit float BGR or grayscale
            std::vector<cv::Mat> channels;
            float* data = mean_blob.mutable_cpu_data();
            for (int i = 0; i < num_channels_; ++i) {
                // Extract an individual channel
                cv::Mat channel(mean_blob.height(), mean_blob.width(), CV_32FC1, data);
                channels.push_back(channel);
                data += mean_blob.height() * mean_blob.width();
            }

            // Merge the separate channels into a single image
            cv::Mat mean;
            cv::merge(channels, mean);

            // Compute the global mean pixel value and create a mean image
            // filled with this value
            cv::Scalar channel_mean = cv::mean(mean);
            mean_ = cv::Mat (input_geometry_, mean.type(), channel_mean);
        }
        else if (Mean_Method == "Image") {
            // The format of the mean file is planar 32-bit float BGR or grayscale
            std::vector<cv::Mat> channels;
            for (int i = 0; i < num_channels_; ++i) {
                // Extract an individual channel
                cv::Mat channel(mean_blob.height(), mean_blob.width(), CV_32FC1, mean_blob.mutable_cpu_data());
                channels.push_back(channel);
            }

            // Merge the separate channels into a single image
            cv::merge(channels, mean_);
        }
    }
    else {
        // Consider no mean image
        cv::Scalar channel_mean = cv::Scalar(0,0,0);
        mean_ = cv::Mat (input_geometry_, CV_32FC3, channel_mean);
    }
}`
I don't know how to do the transpose part in cpp.

Now by doing these I get a different result from digits. I have 10 classes, in some of them the cpp code performs better and in some digits does. Note that the difference isn't much, mostly in 1,2 or 3 images in each class.

**Comment by szm2015** [comment]
Hey guys! Nobody's going to answer this?! As it's still an open issue!

I found the way digits does "fill" and other resize options, but still I've got some questoins. as far as I have figured when using "fill" one dimension is resized to input size (say 60 pixels), then should the mean image be resized to the same size? (as we're going to subtract it from out input?) and other than that should the network input be modified? because it give me the error that "Input channels are not wrapping the input layer of the network." 

Other than that I really appreciate if someone point me to the right direction as to find out how "exactly" does digits perform the preprocess pipeline (as I believe is the source of the inconsistencies)? So that I'd be able to duplicate the precedure in cpp. 

Thanks in advance!

**Comment by kraigrs** [comment]
I am trying to incorporate a model that I trained using DIGITS into my C++ application via the example given here: https://github.com/BVLC/caffe/blob/master/examples/cpp_classification/classification.cpp. I've confirmed that my model can correctly classify my images using the pre-compiled `./build/examples/cpp_classification/classification.bin`, but I'm having trouble embedding this into my own C++ application. I am able to successfully build my C++ project with the classification example above, but my program immediately crashes when it attempts to build the classifier:

```
Classifier::Classifier(const string& model_file,
                       const string& trained_file,
                       const string& mean_file,
                       const string& label_file) {
#ifdef CPU_ONLY
  Caffe::set_mode(Caffe::CPU);
#else
  Caffe::set_mode(Caffe::GPU);
#endif

  /* Load the network. */
  net_.reset(new Net<float>(model_file, TEST)); // <-- crashes here
```

It crashes my program without an error message, leaving me little information as to what actually happened. I've confirmed it's correctly setting the mode to GPU. The `model_file` specified here is the `deploy.prototxt` from the model output of DIGITS. Any help would be greatly appreciated! My only thought is that maybe my GPU think there's no enough memory to hold the network?

System information: Ubuntu 14.04, DIGITS 4.0.0, Caffe 0.15.13, CUDA 8.0, cuDNN 5, NVIDIA Quadro K1100M

**Comment by gheinrich** [comment]
Hello, there are many examples on https://github.com/dusty-nv/jetson-inference that you can use to perform inference from C++ code.

**Comment by szm2015** [comment]
Well I had the same problem and adding a #define USE_CUDNN 1 before #include <caffe/caffe.hpp> solved it.

**Comment by kraigrs** [comment]
Thank you both for your responses! After doing so, it's still crashing but at least now I'm getting the following error:
```
F0110 10:41:06.241632  7135 gpu_memory.cpp:74] Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager
```

So it's having trouble initializing my GPU?

**Comment by kraigrs** [comment]
Referencing this thread as well: https://github.com/NVIDIA/caffe/issues/213

**Comment by pkrush** [comment]
Reboot? (kill other GPU threads?) I got something like this at one point because I had other zombie GPU usage in the background and I manged to waste like 3-4 hours. Are you only calling the same code? @kraigrs  NVIDIA/caffe#213

**Comment by kraigrs** [comment]
I thought that my running DIGITS server was the issue since I only have one GPU, so I stopped that. I'll try rebooting to see if that makes a difference.

Also, in addition to the thread you cite, here are two more: https://github.com/NVIDIA/caffe/issues/196 and https://github.com/NVIDIA/caffe/pull/200

I tried this solution from https://github.com/NVIDIA/caffe/pull/200:
```
Caffe::set_mode(Caffe::GPU);
initialize_gpu_memory_scope();
```
... but it didn't work, and I get a strange error: `*** stack smashing detected ***`

FWIW I can successfully check the device:
```
Caffe::set_mode(Caffe::GPU);
int device_id = 0;
Caffe::SetDevice(device_id);
int check = Caffe::CheckDevice(device_id);
cout << "Using GPU device " << device_id << "; check = " << check << endl;
```
... which produces `Using GPU device 0; check = 1`

I'll try the reboot and get back to everyone.

**Comment by flx42** [comment]
See https://github.com/NVIDIA/caffe/issues/30

**Comment by kraigrs** [comment]
I tried this
```
#define USE_CUDNN 1
#include <caffe/caffe.hpp>
```
... and my crash error persists.

**Comment by ShervinAr** [comment]
@lukeyeager is there a similar C++ code as the one in https://github.com/BVLC/caffe/tree/master/examples/cpp_classification
for detection purposes rather than classification?

**Comment by gheinrich** [comment]
https://github.com/dusty-nv/jetson-inference

**Comment by ShervinAr** [comment]
@gheinrich  I was aware of the code provided in https://github.com/dusty-nv/jetson-inference but there seems large discrepancies between the results obtained by Digits and that of Jetson.
