### ISSUE TITLE
ERROR: error code -11 in detectnet training

### ISSUE THREAD

**Issue by amlarraz** [NVIDIA/DIGITS#1239]
Hi! I trying to train Detecnet with my own data, i can build the dataset perfectly and following [this](https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection) tutorial to train detectnet, but, in the begining of the train, give me the following error: ERROR: error code -11

My configuration is the next:

Ubuntu 16.04
Geforce GTX 1080
cuda 8.0
caffe 0.15.14
Driver nvidia: 367.57

I installed Caffe from https://github.com/BVLC/caffe and also try to install nv-caffe from https://github.com/NVIDIA/caffe.git and have both installed (nv-caffe give me an error during make runtest about 3 layers, but i think are data augmentation layers like detectnet.resize or something like this)

Any idea? thanks in advance!

**Comment by lukeyeager** [comment]
Can you give us the last few lines of your `caffe_output.log`?

**Comment by amlarraz** [comment]
I1102 23:25:37.374640 16303 layer_factory.hpp:77] Creating layer conv2/relu_3x3_reduce
I1102 23:25:37.374646 16303 net.cpp:94] Creating Layer conv2/relu_3x3_reduce
I1102 23:25:37.374649 16303 net.cpp:435] conv2/relu_3x3_reduce <- conv2/3x3_reduce
I1102 23:25:37.374652 16303 net.cpp:396] conv2/relu_3x3_reduce -> conv2/3x3_reduce (in-place)
I1102 23:25:37.374658 16303 net.cpp:144] Setting up conv2/relu_3x3_reduce
I1102 23:25:37.374661 16303 net.cpp:151] Top shape: 2 64 96 312 (3833856)
I1102 23:25:37.374662 16303 net.cpp:159] Memory required for data: 197877120
I1102 23:25:37.374665 16303 layer_factory.hpp:77] Creating layer conv2/3x3
I1102 23:25:37.374670 16303 net.cpp:94] Creating Layer conv2/3x3
I1102 23:25:37.374672 16303 net.cpp:435] conv2/3x3 <- conv2/3x3_reduce
I1102 23:25:37.374676 16303 net.cpp:409] conv2/3x3 -> conv2/3x3
*** Aborted at 1478125537 (unix time) try "date -d @1478125537" if you are using GNU date ***
PC: @     0x7f8a88ea4436 caffe::DataTransformer<>::TransformPtr()
*** SIGSEGV (@0x1026f67d110) received by PID 16303 (TID 0x7f8a27fff700) from PID 1869074704; stack trace: ***
@     0x7f8a871c74a0 (unknown)
@     0x7f8a88ea4436 caffe::DataTransformer<>::TransformPtr()
@     0x7f8a88eade2f caffe::DataTransformer<>::TransformPtrEntry()
@     0x7f8a88e429b0 boost::detail::function::void_function_obj_invoker0<>::invoke()
@     0x7f8a88e4377b ThreadPool::main_loop()
@     0x7f8a86f7d5d5 (unknown)
@     0x7f8a86d566fa start_thread
@     0x7f8a87298b5d clone
@                0x0 (unknown)

**Comment by amlarraz** [comment]
I solved it! i think i had no all dependences installed...if anybody find this helpful here is the things i did: (and install caffe & pycaffe)

- Re-Make caffe with Python layers: In your Makefile.config, make sure to have this line uncommented
WITH_PYTHON_LAYER := 1

- Install the next python packages: cython, python-opencv, easydict

and DIGITS work perfectly!
