### ISSUE TITLE
Incorrect iteration_to_epoch calculation with batch_accumulation

### ISSUE THREAD

**Issue by bachma** [NVIDIA/DIGITS#1240]
Hello,
I'm not a 100% sure, but I think the calculation of iteration_to_epoch is incorrect when using batch_accumulation. I guess this is due to the calculation of solver.max_iter since it doesn't take batch_accumulation into account.

**Comment by lukeyeager** [comment]
I'm pretty sure we're doing it right. Please elaborate on why you think what we're doing is incorrect.

**Comment by bachma** [comment]
As it is stated in https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/solver.cpp#L280-L282 the internal iter_ counter in caffe "indicates the number of times the weights have been updated."
You can also see this in https://github.com/NVIDIA/caffe/blob/caffe-0.15/src/caffe/solver.cpp#L233-L235.

Therefore, the number of samples processed during one caffe iteration should be `batch_size x iter_size` and should be taken into account in DIGITS while calculating `iteration_to_epoch`.

This is not done in https://github.com/NVIDIA/DIGITS/blob/713cb83e1f515858ba599bda199fa35e98f3f62d/digits/model/tasks/caffe_train.py#L527-L531 and https://github.com/NVIDIA/DIGITS/blob/713cb83e1f515858ba599bda199fa35e98f3f62d/digits/model/tasks/caffe_train.py#L889-L890

Please correct me if I'm wrong

**Comment by gheinrich** [comment]
What @bachma is saying makes sense. I tried training the same model without batch accumulation and with batch accumulation and it does indeed take much longer to go through the same number of "epochs" (in DIGITS speak) when using batch accumulation.

**Comment by lukeyeager** [comment]
Oh wow, great point! I'm surprised that's how Caffe counts things.

**Comment by lukeyeager** [comment]
Thanks for the report @bachma. I verified the bug with a debug Caffe build - you're exactly right.

Would you like to try out #1262 and verify the fix?
