### ISSUE TITLE
snapshot.caffemodel type is PCX image?

### ISSUE THREAD

**Issue by elirex** [NVIDIA/DIGITS#1245]
I use googlenet to train on DIGITS. I download the trained model and run on Nvidia TX1 through [jetson-inference](https://github.com/dusty-nv/jetson-inference) that response error:  
```bash
in nvinfer1::cudnn::validateConfig(nvinfer1::Network const&, nvinfer1::CudaEngineBuildContext const&) ()
   from /usr/lib/aarch64-linux-gnu/libnvinfer.so.1
```
I use another the trained model (trained by caffe, not through DIGITS) to run is OK.

I compare two models, then I discovered their file type are difference.
The model trained by DIGITS that file type is PCX image.
The mode trained by Caffe that file type is binary.

**Comment by gheinrich** [comment]
Can you elaborate on your question and whether you are having an issue at all?

**Comment by gheinrich** [comment]
No feedback => closing.
