### ISSUE TITLE
KITTI format genrator 

### ISSUE THREAD

**Issue by moh3th1** [NVIDIA/DIGITS#1248]
I have my data contain only two classes , its on Pascal VOC format (XML file).
Are there any  tool that can generate/convert to KITTI format ?

**Comment by gheinrich** [comment]
Hello, I don't know if such a tool exists. If you find or create one, please let us know, thanks!

**Comment by moh3th1** [comment]
I think I find one 
https://github.com/prabindh/euclid

**Comment by gheinrich** [comment]
Excellent, please let us know if it works well!

**Comment by ljz1995** [comment]
Are you success convert from Pascal VOC format (XML file) to KITTI format

**Comment by ljz1995** [comment]
Are you convert from Pascal VOC format (XML file) to KITTI format ?

**Comment by ljz1995** [comment]
Are you success convert from Pascal VOC format (XML file) to KITTI format ?

**Comment by kargarisaac** [comment]
is there any code to convert tracklet_labels.xml file into text files?
I have downloaded data from http://www.cvlibs.net/datasets/kitti/raw_data.php and want to convert labels to files same as labels from http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d
