### ISSUE TITLE
Reason of training images' dimensions?

### ISSUE THREAD

**Issue by ontheway16** [NVIDIA/DIGITS#1249]
I do not know about lmdb but what i am seeing in kitti dataset, there are different directories like train, val and raw etc.  I have two questions here. 

1. For custom data, I was assuming train and val directories would be enough, is it?

2. Title question,  if i have information of bounding box rectangle of an object in a photo, which will be utilized in training, why I am supplying 1248x384 training images (consumes a lot of memory) instead of directly providing much smaller bounding-box crops of the objects from the main photos? Since coordinates of objects known, this cropping work can be done programmatically, unless there is another reason for this large dimension.

**Comment by gheinrich** [comment]
Hello, please refer to this [object detection example](https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/object-detection).

Regarding your other question, the reason we need to provide full images (not just the areas where objects are located) is the network needs data to learn the difference between background and foreground.

**Comment by ontheway16** [comment]
Thank you, then is it wise to prepare 1248x384 crops from my main (very large, like 10K*25K) image each contains one object at the center?
Or,  a custom sized image which contains an object in the center, and background on four sides which is as large as objects width or height. Which one do you think is more logical for better success and faster training times? (I can prepare both options very easily)

**Comment by gheinrich** [comment]
It is generally recommended to draw your training examples from the same distribution as the examples you want to test on later. So for example if the object isn't always going to be at the center of your test images, it shouldn't be the case in your training images.

**Comment by ontheway16** [comment]
Well thanks again, These are very valuable comments for me.

**Comment by gheinrich** [comment]
Thanks. Closing.
