### ISSUE TITLE
Disable cuDNN

### ISSUE THREAD

**Issue by matiaszilli** [NVIDIA/DIGITS#1250]
Hello. How can I change the Caffe version in DIGITS?. Because my GPU does not support cuDNN and I can not run DIGITS. Other option can be run DIGITS without cuDNN but i do not know if is it possible.
PD: I am using DIGITS 4.0 and UBUNTU 14.04
Best regards.

**Comment by lukeyeager** [comment]
The deb packages we provide only work if you have a GPU compatible with cuDNN.

But if you build from source, then you can build Caffe however you like.
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildDigits.md

**Comment by matiaszilli** [comment]
Perfect. So, the enviroment variable $CAFFE_ROOT manage the Caffe Path for
DIGITS ?.
Best Regards.


2016-11-10 19:31 GMT+01:00 Luke Yeager <notifications@github.com>:

**Comment by lukeyeager** [comment]
Yup. https://github.com/NVIDIA/DIGITS/blob/v5.0.0-rc.1/digits/config/caffe.py#L224-L229

**Comment by matiaszilli** [comment]
Perfect!. Thank you so much. I will try to do it. If I get a problem, I
will tell you.
Best regards

2016-11-10 20:15 GMT+01:00 Luke Yeager <notifications@github.com>:
