### ISSUE TITLE
Setting Ignore label on RGB labeled images in Segmentation Dataset

### ISSUE THREAD

**Issue by klaimane** [NVIDIA/DIGITS#1251]
Hi,

I'm creating a segmentation dataset with RGB feature images and RGB labels.
How do I set up my classes.txt and cmap.txt if I want DIGITS to ignore a specific label (255 255 255) during training? (like VOC-Pascal)

Is it enough to add a label "ignore" and (255 255 255) in last lines of the classes .txt and cmap.txt respectively?

Thanks,
Eldad

**Comment by gheinrich** [comment]
Hello, as you correctly figured out you need to add this line to your color map text file:
```
255 255 255
```
and this line to your class names text file:
```
ignore
```

You also need to update your prototxt to tell Caffe to ignore this label. Assuming the class to ignore has ID=10 (i.e. this is the eleventh class - IDs are zero-based). Then you would add this to the `loss_param` section of your `SoftMaxWithLoss` layer *and* the `accuracy_param` section of your `Accuracy` layer:
```
ignore_label: 10
```

You would typically ignore labels for areas that mark delineations between classes, or areas where the class is undefined. As a general comment, note that background should not generally be ignored.

**Comment by klaimane** [comment]
perfect! Thanks!
