### ISSUE TITLE
Error when adding dice.py python layer to caffe alex-net

### ISSUE THREAD

**Issue by klaimane** [NVIDIA/DIGITS#1253]
Hi,

Trying to add Dice metric layer to network to manage dataset imbalance.
I followed the instructions in the medical imaging example but receive error this when training the net:

> ERROR: Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Python (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Concat, ContrastiveLoss, Convolution, Crop, Data, Deconvolution, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, Input, LRN, LSTM, LSTMUnit, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Parameter, Pooling, Power, RNN, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile, WindowData)

**from output log:**

> I1110 16:44:09.254968 172016 layer_factory.hpp:77] Creating layer dice

> F1110 16:44:09.255031 172016 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Python (known types: AbsVal, Accuracy, ArgMax, BNLL, BatchNorm, BatchReindex, Bias, Concat, ContrastiveLoss, Convolution, Crop, Data, Deconvolution, Dropout, DummyData, ELU, Eltwise, Embed, EuclideanLoss, Exp, Filter, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, Input, LRN, LSTM, LSTMUnit, Log, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Parameter, Pooling, Power, RNN, ReLU, Reduction, Reshape, SPP, Scale, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, Tile, WindowData)

> *** Check failure stack trace: ***
> @     0x7ffff1b4c9fd  google::LogMessage::Fail()
> @     0x7ffff1b4e7cc  google::LogMessage::SendToLog()
> @     0x7ffff1b4c5ec  google::LogMessage::Flush()
> @     0x7ffff1b4f0de  google::LogMessageFatal::~LogMessageFatal()
> @     0x7ffff730079f  caffe::LayerRegistry<>::CreateLayer()
> @     0x7ffff742544c  caffe::Net<>::Init()
> @     0x7ffff7427545  caffe::Net<>::Net()
> @     0x7ffff740cf3a  caffe::Solver<>::InitTrainNet()
> @     0x7ffff740e03c  caffe::Solver<>::Init()
> @     0x7ffff740e36a  caffe::Solver<>::Solver()
> @     0x7ffff7400e23  caffe::Creator_SGDSolver<>()
> @           0x410aed  caffe::SolverRegistry<>::CreateSolver()
> @           0x409ec2  train()
> @           0x40752c  main
> @     0x7fffe9ebcb15  __libc_start_main
> @           0x407d9d  (unknown)

**Comment by gheinrich** [comment]
Hello, you need to enable support for Python layers in Caffe. Did you build Caffe yourself from the top-level makefile? Our recommendation is to get Caffe from the `caffe-nv` .deb package ([instructions](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md)) or if you need to build Caffe yourself, use `cmake` to generate the makefile as explained in the [Caffe build instructions](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildCaffe.md).

**Comment by klaimane** [comment]
Thanks! I'm running on the HPC so I'll ask the admin to install it according to the instructions.

**Comment by klaimane** [comment]
After compiling caffe with python layer support and adding the dice.py layer as in the medical imaging example I get another error:

I1112 11:45:39.933650 39113 net.cpp:150] Setting up loss
I1112 11:45:39.933662 39113 net.cpp:157] Top shape: (1)
I1112 11:45:39.933665 39113 net.cpp:160]     with loss weight 1
I1112 11:45:39.933730 39113 net.cpp:165] Memory required for data: 203912492
I1112 11:45:39.933735 39113 layer_factory.hpp:77] Creating layer dice
I1112 11:45:43.071300 39113 net.cpp:100] Creating Layer dice
I1112 11:45:43.071329 39113 net.cpp:434] dice <- score_score_0_split_1
I1112 11:45:43.071341 39113 net.cpp:434] dice <- label_label_0_split_1
I1112 11:45:43.071349 39113 net.cpp:408] dice -> dice
Traceback (most recent call last):
File "/pstore/home/klaimane/.local/digits/20161112-114537-b333/digits_python_layers.py", line 17, in reshape
raise Exception("Prediction must have twice the number of elements of the input.")
Exception: Prediction must have twice the number of elements of the input.

**Comment by gheinrich** [comment]
Hello, the Dice Python layer only works (and makes sense) for binary segmentation so you need to have only two classes in your final softmax. Refer to the [medical imaging example](https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/medical-imaging#fcn-alexnet).

**Comment by klaimane** [comment]
Of course, how silly of me :-)

Are there any "dice-like" layers that support multiple classes? (in our case I think 3 would be the absolute minimum.)

I'm currently trying to compensate by painting a proportional part of the background with the ignore label, but this technique only compensates for background quantity balance and not balance of other classes.

**Comment by gheinrich** [comment]
Note that the Dice layer from the medical imaging example is just a metric to replace accuracy. It is not a loss layer so it has no impact on training. The `backward()` method needs to be implemented to use it as a loss. If you have more than 2 classes you might be interested in the `InfoGainLoss` which makes it possible to penalize some errors more strongly (e.g. predicting background instead of foreground). However the caveat is the default implementation in Caffe doesn't work with FCNs (besides, even after integrating changes to fix this, I didn't manage to get it to produce better predictions).

**Comment by klaimane** [comment]
Thanks! I guess this leaves the balancing on the dataset side?

**Comment by gheinrich** [comment]
Is class imbalance that much of an issue for you? On the medical imaging example even though the background represents 98.5% of pixels we get a Dice metric of 0.86 when using FCN-8s. I am not totally convinced by the benefits of doing class balancing in the dataset. I like it when the training dataset represents the true distribution of the data that you're likely to encounter during testing.

**Comment by klaimane** [comment]
I guess it would be relatively easy to test a balanced vs unbalanced set and comapre the results.

**Comment by gheinrich** [comment]
Sure.

I'll be closing this issue for now.
