### ISSUE TITLE
ERROR: Check failed: data_  

### ISSUE THREAD

**Issue by Ali-Maher** [NVIDIA/DIGITS#1257]
Hello 
I worked with digits 5.0, I tried the classification task wit MNIST and done without any problem , but for Detectnet after creation the (train/val)  KITTI dataset successfully , unfortunately it gives error at creating model task (Train Caffe Model task failed with error code -6).. I tried to use another dataset with the same format, but the problem still exist. any suggestion please. 

```
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.0.0-rc.1

2016-11-11 12:23:36 [INFO ] Loaded 14 jobs.
2016-11-11 12:25:18 [20161111-122516-a2ad] [WARNING] Ignoring data_param.source ...
2016-11-11 12:25:18 [20161111-122516-a2ad] [WARNING] Ignoring data_param.backend ...
2016-11-11 12:25:18 [20161111-122516-a2ad] [WARNING] Ignoring data_param.source ...
2016-11-11 12:25:18 [20161111-122516-a2ad] [WARNING] Ignoring data_param.backend ...
2016-11-11 12:25:18 [20161111-122516-a2ad] [WARNING] Ignoring data_param.source ...
2016-11-11 12:25:18 [20161111-122516-a2ad] [WARNING] Ignoring data_param.backend ...
2016-11-11 12:25:18 [20161111-122516-a2ad] [WARNING] Ignoring data_param.source ...
2016-11-11 12:25:18 [20161111-122516-a2ad] [WARNING] Ignoring data_param.backend ...
2016-11-11 12:25:18 [20161111-122516-a2ad] [DEBUG] Network sanity check - train
2016-11-11 12:25:18 [20161111-122516-a2ad] [DEBUG] Network sanity check - val
2016-11-11 12:25:18 [20161111-122516-a2ad] [DEBUG] Network sanity check - deploy
2016-11-11 12:25:18 [20161111-122516-a2ad] [INFO ] Train Caffe Model task started.
2016-11-11 12:25:18 [20161111-122516-a2ad] [INFO ] Task subprocess args: "/home/ali-maher/caffe/build/tools/caffe train --solver=/home/ali-maher/DIGITS-digits-5.0/digits/jobs/20161111-122516-a2ad/solver.prototxt --gpu=0 --weights=/home/ali-maher/ggoleNet_caffe_model/bvlc_googlenet.caffemodel"
2016-11-11 12:25:18 [20161111-122516-a2ad] [ERROR] Train Caffe Model: Check failed: data_
2016-11-11 12:25:19 [20161111-122516-a2ad] [ERROR] Train Caffe Model task failed with error code -6
```
![screenshot from 2016-11-11 11-23-48](https://cloud.githubusercontent.com/assets/23374006/20203532/09e16cba-a803-11e6-99a6-a9ee202b2b92.png)

**Comment by DarylWM** [comment]
I have the same issue. I believe it can be recreated by running the tests.

ERROR: test suite for <class 'digits.model.images.generic.test_views.TestAllInOneNetwork'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/local/lib/python2.7/dist-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/daryl/DIGITS-5.1-dev/digits/model/images/generic/test_views.py", line 242, in setUpClass
    assert cls.model_wait_completion(cls.model_id) == 'Done', 'create failed'
AssertionError: create failed
-------------------- >> begin captured logging << --------------------
digits: INFO: Job deleted.
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits: INFO: Job deleted.
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
digits.webapp: INFO: Analyze DB (Training Images) task started.
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: INFO: Task subprocess args: "/usr/bin/python2 /home/daryl/DIGITS-5.1-dev/digits/tools/analyze_db.py /tmp/tmpqCDWAP/train_images --force-same-shape"
digits.webapp: INFO: Analyze DB (Training Labels) task started.
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: INFO: Task subprocess args: "/usr/bin/python2 /home/daryl/DIGITS-5.1-dev/digits/tools/analyze_db.py /tmp/tmpqCDWAP/train_labels --force-same-shape"
digits.webapp: INFO: Analyze DB (Validation Images) task started.
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: INFO: Task subprocess args: "/usr/bin/python2 /home/daryl/DIGITS-5.1-dev/digits/tools/analyze_db.py /tmp/tmpqCDWAP/val_images --force-same-shape"
digits.webapp: INFO: Analyze DB (Validation Labels) task started.
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: INFO: Task subprocess args: "/usr/bin/python2 /home/daryl/DIGITS-5.1-dev/digits/tools/analyze_db.py /tmp/tmpqCDWAP/val_labels --force-same-shape"
digits.webapp: WARNING: Analyze DB (Training Labels) unrecognized output: WARNING: log_file config option not found - no log file is being saved
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: DEBUG: Images are 2x1x1
digits.webapp: WARNING: Analyze DB (Training Images) unrecognized output: WARNING: log_file config option not found - no log file is being saved
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: DEBUG: Images are 10x10x1
digits.webapp: INFO: Analyze DB (Training Labels) task completed.
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
digits.webapp: INFO: Analyze DB (Training Images) task completed.
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
digits.webapp: WARNING: Analyze DB (Validation Images) unrecognized output: WARNING: log_file config option not found - no log file is being saved
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: DEBUG: Images are 10x10x1
digits.webapp: WARNING: Analyze DB (Validation Labels) unrecognized output: WARNING: log_file config option not found - no log file is being saved
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: DEBUG: Images are 2x1x1
digits.webapp: INFO: Analyze DB (Validation Images) task completed.
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
digits.webapp: INFO: Analyze DB (Validation Labels) task completed.
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "task update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130500-e13e [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits: INFO: Job complete.
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130503-9977 [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
digits.webapp: DEBUG: Network sanity check - train
digits.webapp: DEBUG: Network sanity check - val
digits.webapp: DEBUG: Network sanity check - deploy
digits.webapp: INFO: Train Caffe Model task started.
socketio: INFO: emitting event "task update" to 20161111-130503-9977 [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130503-9977 [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
digits.webapp: INFO: Task subprocess args: "/home/daryl/caffe/build/tools/caffe train --solver=/tmp/tmpGa1NVm/20161111-130503-9977/solver.prototxt --gpu=0"
socketio: INFO: emitting event "task update" to 20161111-130503-9977 [/jobs]
digits.webapp: ERROR: Train Caffe Model: Check failed: data_
digits.webapp: ERROR: Train Caffe Model: Check failed: data_
digits.webapp: ERROR: Train Caffe Model: Check failed: data_
digits.webapp: ERROR: Train Caffe Model: Check failed: data_
digits.webapp: ERROR: Train Caffe Model task failed with error code -6
socketio: INFO: emitting event "task update" to 20161111-130503-9977 [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130503-9977 [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]
socketio: INFO: emitting event "server update" to job_management [/jobs]
socketio: INFO: emitting event "job update" to 20161111-130503-9977 [/jobs]
socketio: INFO: emitting event "job update" to job_management [/jobs]

**Comment by DarylWM** [comment]
I checked that my Caffe (NVcaffe) is installed and operating properly using `make runtest`, and all the tests passed.

**Comment by DarylWM** [comment]
I built NVcaffe from source, taking the head of the repo. I'll try going back to the tagged v0.15.14 release.

**Comment by DarylWM** [comment]
@Ali-Maher Building https://github.com/NVIDIA/caffe/releases/tag/v0.15.14 resolved this issue for me.

**Comment by Ali-Maher** [comment]
@DarylWM , finally start training Detectnet Now, Compiling NVCaffe V 0.15.14 also resolved this issue for me. thanks all.
