### ISSUE TITLE
Use of "truncated" parameter

### ISSUE THREAD

**Issue by ontheway16** [NVIDIA/DIGITS#1258]
I want to ask about use of "truncated".
I am planning to create several 1248x384 crops from main image but naturally, some objects will be available partially. If 30% of an object remains in the cropped image, in labels, cant decide should I add 0.30 or 0.70,

**Comment by lukeyeager** [comment]
>```
   1    truncated    Float from 0 (non-truncated) to 1 (truncated), where
                     truncated refers to the object leaving image boundaries
```
https://github.com/NVIDIA/DIGITS/tree/digits-5.0/digits/extensions/data/objectDetection#label-format
