### ISSUE TITLE
Cuda-devices

### ISSUE THREAD

**Issue by matiaszilli** [NVIDIA/DIGITS#1260]
Hi!. I train my CNN perfect, but when I try to do the image inference. I get the follow error:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1111 11:09:41.910959 14384 gpu_memory.cpp:152] Check failed: error == cudaSuccess (46 vs. 0)  all CUDA-capable devices are busy or unavailable
*** Check failure stack trace: ***
```
So, I can not understand why I can train perfect but I get error when do the inference.

Best regards

**Comment by lukeyeager** [comment]
Are all your GPUs actually busy? DIGITS is supposed to kick inference jobs to the CPU when all your GPUs are busy. What does `nvidia-smi` tell you? How about `python digits/device_query.py`?

**Comment by matiaszilli** [comment]
No, all Gpu's are not busy.

pc@Workstation:~/digits$ python digits/device_query.py
Device #0:
>>> CUDA attributes:
  name                         GeForce GTX 770
  totalGlobalMem               2094399488
  clockRate                    1110500
  major                        3
  minor                        0
>>> NVML attributes:
  Total memory                 1997 MB
  Used memory                  350 MB
  Temperature                  41 C

Device #1:
>>> CUDA attributes:
  name                         Tesla C2075
  totalGlobalMem               5558501376
  clockRate                    1147000
  major                        2
  minor                        0
>>> NVML attributes:
  Total memory                 5301 MB
  Used memory                  0 MB
  Memory utilization           0%
  GPU utilization              0%
  Temperature                  58 C

NVIDIA SMI

Workstation:~/digits$ nvidia-smi
Fri Nov 11 13:27:44 2016       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 367.57                 Driver Version: 367.57                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 770     Off  | 0000:0F:00.0     N/A |                  N/A |
| 46%   41C    P8    N/A /  N/A |    314MiB /  1997MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla C2075         Off  | 0000:42:00.0     Off |                    0 |
| 30%   58C   P12    33W /  N/A |      0MiB /  5301MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

**Comment by lukeyeager** [comment]
Oh wow, that's a pretty old Tesla card. I'm assuming you built caffe without cuDNN in order to get it to run at all?

Try excluding the old card from your list of devices and see if you still have the issue.

    export CUDA_VISIBLE_DEVICES=0

**Comment by lukeyeager** [comment]
Well you didn't really "disable" your old card - you just hid it from DIGITS. I think if you build Caffe without cuDNN support then you might be able to use the old card.

If your question has been answered, will you close the issue please?

**Comment by matiaszilli** [comment]
Perfect. Thank you so much!

2016-11-14 18:18 GMT+01:00 Luke Yeager <notifications@github.com>:
