### ISSUE TITLE
Find (ctrl+f) has broken in the 'custom network' form

### ISSUE THREAD

**Issue by korabelnikov** [NVIDIA/DIGITS#1265]
branch:master (yesterday checkout)

It'works before when I used version 4.1.

1. crtrl+f does not action now

![image](https://cloud.githubusercontent.com/assets/3808833/20249350/0ec21792-aa11-11e6-9706-77f69246d0cd.png)

**Comment by lukeyeager** [comment]
Confirmed. When I moved stuff around in #1201, I broke Ace's auto-loading feature. In #1271, I load this extension explicitly.
