### ISSUE TITLE
Error when using multi-gpu

### ISSUE THREAD

**Issue by 401qingkong** [NVIDIA/DIGITS#1269]
I have two gpus in my computer. Version Information is as follows:
DIGITS version:5.0.0-rc.1
Caffe version:0.15.7
![1](https://cloud.githubusercontent.com/assets/20376660/20260948/bda53a34-aa96-11e6-8239-08bfb7f9e16f.png)
But when I choose the two gpus, there is a problem like below:
parallel.cpp:160] USE_NCCL := 1 must be specified for multi-GPU
what do I need to configure?Thanks in advance

**Comment by gheinrich** [comment]
Hello, you could fix this by installing Caffe 0.15.13 from the [Nvidia ML repo](http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/). If you want to [build Caffe](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildCaffe.md) yourself I recommend checking out the latest version on 0.15.x branch. Before you run `cmake` to generate your makefile, make sure you install the `libnccl-dev` package from the ML repo.

**Comment by lukeyeager** [comment]
This is unrelated, but you might want to update your driver. It looks like your driver isn't able to read the name of your GPU.

**Comment by 401qingkong** [comment]
@gheinrich Hi! I try to install Caffe 0.15.13. I want to know whether there is requirement for the CUDA version. Now the version is cuda-7.0. It seems that at least cuda-7.5 is needed by libnccl-dev package.

**Comment by 401qingkong** [comment]
@lukeyeager Thank you for your reply. Indeed, I have just installed a new gpu, but it is the same as the first one,They are all TitanX. when I check the gpu version, the information is as follows:
![2](https://cloud.githubusercontent.com/assets/20376660/20305282/a9f7b8a2-ab6f-11e6-9d48-3593eaf2d003.png)
There is no concerate gpu model information It seems to have problems.
The original driver version is 346.46. So do I need to update or install another driver for the same gpu model?

**Comment by lukeyeager** [comment]
You're right - NCCL only has [official builds](https://github.com/NVIDIA/nccl/releases) for CUDA 7.5 and 8.0. You could [build nccl from source](https://github.com/NVIDIA/nccl/blob/master/README.md#build--run) if you're committed to using CUDA 7.0.

It might be simplest to just upgrade to the CUDA 8.0 toolkit and driver. It shouldn't break any existing apps you built against CUDA 7.0 because you can have both toolkits installed alongside each other.

**Comment by 401qingkong** [comment]
@gheinrich @lukeyeager In fact, I have uninstalled CUDA 7.0. Now the version is CUDA 7.5.  And the digits version also changes from DIGITS-3.0 TO DIGITS 5.0.0-rc.1. When I start the previous DIGITS, it shows that CUDA 7.0 is needed(DIGITS-3.0 depends on CUDA7.0). I want to ask if there is a method for me to load the previous digits jobs to the new version without installing CUDA7.0.?
Also, can you give me a brief key installation instructions about how to keep two CUDA toolkits under one system.

**Comment by lukeyeager** [comment]
Why do you say that DIGITS 3.0 depends on CUDA 7.0? DIGITS shouldn't really care about your CUDA version (although you do need https://github.com/NVIDIA/DIGITS/commit/9526a851916a146fcee761e03bd92e207c0371e2 to interact properly with CUDA 8.0).

And the jobs you've stored on disk certainly don't care about CUDA (although you may need to set an envvar to point out the location of your old jobs since https://github.com/NVIDIA/DIGITS/pull/1091).

**Comment by 401qingkong** [comment]
@lukeyeager  Thanks for your reply. I have checked the problem and found that  the  CAFFE_ROOT variable  is wrongly set. Now everything is ok. And I set the DIGITS_JOBS_DIR to point out the location of my old jobs, It works. However, when I set two routes in this  environment variables(the old jobs and the new jobs), just like this:
export DIGITS_JOBS_DIR=/home/chenzhineng/Downloads/DIGITS-5.0.0-rc.1/digits/jobs:/home/chenzhineng/Downloads/DIGITS-digits-3.0/digits/jobs
DIGITS failed to loads  jobs. 
![3](https://cloud.githubusercontent.com/assets/20376660/20509384/5ece3462-b0a3-11e6-88ad-7f5d1dcec6a5.png)
How to solve this? Sorry to trouble you again. Thanks

**Comment by gheinrich** [comment]
You can only have one job directory. You can merge two of them by copying the files manually.

**Comment by lukeyeager** [comment]
@401qingkong sounds like your original problem is resolved. Can we close this?

**Comment by 401qingkong** [comment]
@lukeyeager @gheinrich Yes! Thanks for your help

**Comment by mrgloom** [comment]
Is it possible to use multi GPU configuration without NCCL?
Seems it's added only in newer caffe releases?
https://github.com/BVLC/caffe/blob/master/tools/caffe.cpp#L250

**Comment by moumouyou** [comment]
Hi, @lukeyeager @gheinrich , I met an error when installing caffe with USE_NCCL := 1.

Error messages are as follows:
CXX/LD -o .build_release/tools/finetune_net.bin
CXX/LD -o .build_release/examples/siamese/convert_mnist_siamese_data.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
CXX/LD -o .build_release/examples/mnist/convert_mnist_data.bin
.build_release/tools/caffe.o：在函数‘train()’中：
caffe.cpp:(.text+0x2845)：对‘caffe::NCCL::NCCL(boost::shared_ptrcaffe::Solver<float >)’未定义的引用
caffe.cpp:(.text+0x2888)：对‘caffe::NCCL::Run(std::vector<int, std::allocator > const&, char const*)’未定义的引用
caffe.cpp:(.text+0x2890)：对‘caffe::NCCL::~NCCL()’未定义的引用
caffe.cpp:(.text+0x3232)：对‘caffe::NCCL::~NCCL()’未定义的引用
caffe.cpp:(.text+0x335b)：对‘caffe::NCCL::~NCCL()’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:627: recipe for target '.build_release/tools/caffe.bin' failed
make: *** [.build_release/tools/caffe.bin] Error 1
make: *** 正在等待未完成的任务....

My environment information is as follows:
Ubunutu 16.04
caffe 1.0.0rc5, everything is OK without nccl
cuda 8.0
cudnn 5.1
nccl 1.3.4 or 1.2.3, build from source or installed from deb pkg without error messages
gpu: nvidia gtx1080 x2
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39 Driver Version: 375.39 |
|-------------------------------+----------------------+----------------------+
| GPU Name Persistence-M| Bus-Id Disp.A | Volatile Uncorr. ECC |
| Fan Temp Perf Pwr:Usage/Cap| Memory-Usage | GPU-Util Compute M. |
|===============================+======================+======================|
| 0 GeForce GTX 1080 Off | 0000:02:00.0 Off | N/A |
| 3% 48C P8 8W / 200W | 1MiB / 8114MiB | 0% Default |
+-------------------------------+----------------------+----------------------+
| 1 GeForce GTX 1080 Off | 0000:03:00.0 On | N/A |
| 0% 48C P8 8W / 200W | 183MiB / 8110MiB | 0% Default |
+-------------------------------+----------------------+----------------------+

Could you help me? Any advice will be appreciated!
