### ISSUE TITLE
Torch needs to adjust models for each dataset

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#128]
When using Caffe, DIGITS adjusts the last layer of the network to match the number of classes in the dataset. This is pretty easy, just `layer[-1].num_output = num_classes`.

It's more complicated in Torch because the network is defined in a piece of lua source code instead of a text file. We need to find some kind of solution for this. Maybe after `main.lua` reads the model, it can edit that object and adjust the output of the last layer?

**Comment by Sravan2j** [comment]
@lukeyeager : Currently, I am changing the output of the last layer, if and only if it is "Linear" layer. For all other layers, I am displaying warning message. This function can be improved in future to support all other layers. Please test it once and close issue if fix looks good. Thanks for your time.

**Comment by lukeyeager** [comment]
Closed in #324.
