### ISSUE TITLE
Cannot create mode for Object Detection

### ISSUE THREAD

**Issue by abinlee** [NVIDIA/DIGITS#1282]
I follow the demo steps for Object Detection with KITTI but always get error while model initialized.
Here is my train environment:
GPU - Tesla P100-SXM2-16GB
Docker image from nvidia-docker - Digits 4.0.0/Caffe 0.15.13
detectnet_network.prototxt - https://github.com/NVIDIA/caffe/releases/tag/v0.15.14

The error message is :

ERROR: Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0) CURAND_STATUS_LAUNCH_FAILURE
```
Ignoring source layer loss2/loss
Ignoring source layer pool4/3x3_s2
Ignoring source layer pool4/3x3_s2_pool4/3x3_s2_0_split
Ignoring source layer pool5/7x7_s1
Ignoring source layer pool5/drop_7x7_s1
Ignoring source layer loss3/classifier
Ignoring source layer loss3/loss3
Starting Optimization
Solving
Learning Rate Policy: step
Iteration 0, Testing net (#0)
Ignoring source layer train_data
Ignoring source layer train_label
Ignoring source layer train_transform
Test net output #0: loss_bbox = 40.9217 (* 2 = 81.8434 loss)
Test net output #1: loss_coverage = 23.5318 (* 1 = 23.5318 loss)
Test net output #2: mAP = 0
Test net output #3: precision = 0
Test net output #4: recall = 0
Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE
```

Thanks,
Abin

**Comment by lukeyeager** [comment]
> The DIGITS/caffe images we provide are based on CUDA 7.5, so they can't run on Pascal boards like the 1080. Hopefully we will have deb packages for caffe and DIGITS on CUDA 8.0 soon.
@flx42 https://github.com/NVIDIA/nvidia-docker/issues/221#issuecomment-254568007

**Comment by lukeyeager** [comment]
See https://github.com/NVIDIA/caffe/issues/270 for a summary.
