### ISSUE TITLE
Inconsistent  batchsize  during training phase using DIGITS-5.0.0-rc.1

### ISSUE THREAD

**Issue by 401qingkong** [NVIDIA/DIGITS#1289]
When creating a new model, I set batch_size to be 32 in the prototxt file. However, It keeps to be the constant 16 in the training phase observed in the log file, but the test-batchsize is right in the log file. Similarily,  it changes from 64 in the train_val.prototxt  to 32 in the training phase observed in the log file. It seems that max_iter is calculated based the prototxt file. Please check the Inconsistent problem and whether the descent calculation is influenced.
The first picture is from prototxt file, the second is from the log file
![proto](https://cloud.githubusercontent.com/assets/20376660/20517875/fb9a4040-b0d7-11e6-8a11-384edc1aabb9.png)
![log2](https://cloud.githubusercontent.com/assets/20376660/20517879/ff0f24c0-b0d7-11e6-91e7-158a4a688959.png)

**Comment by slayton58** [comment]
Are you running on multiple GPUs? If so, the batch size is divided by the # GPUs you use to maintain numerical consistency. So if you specify batch_size: 64, and run on 2 GPUs, each will get batch_size: 32

**Comment by gheinrich** [comment]
@401qingkong does @slayton58 's answer address your question?
