### ISSUE TITLE
python layer axis

### ISSUE THREAD

**Issue by fschmich** [NVIDIA/DIGITS#1291]
Hi all,

I've implemented a python layer that computes class-wise accuracies to be displayed during learning instead of only the overall accuracy. Is there any setting where I can set the lines/points produced by the layer to live on the "accuracy %" scale on the right hands side? Right now it seems like they're automatically  scaled by the left hand's (loss -) scale. Any help is highly appreciated.

Best wishes,

Fabian

**Comment by gheinrich** [comment]
Hello, I think you can need to define your "top" such that the word "accuracy" is in the name: https://github.com/NVIDIA/DIGITS/blob/digits-5.0/digits/model/tasks/train.py#L540-L544

**Comment by fschmich** [comment]
Awesome, Greg, thanks for the pointer!
