### ISSUE TITLE
run Digits has mistake

### ISSUE THREAD

**Issue by TonyZihao** [NVIDIA/DIGITS#1292]
```
user@user-ProLiant-DL380-Gen9:~/digits$ ./digits-devserver
Default value for caffe_root "<PATHS>" invalid:
	caffe binary not found in PATH
==================================== Caffe =====================================
Where is caffe installed?

	Suggested values:
	(P*) [PATH/PYTHONPATH] <PATHS>
>> ~/caffe
ERROR: caffe binary not found at "/home/user/caffe"
Invalid input
>> ~/

caffe root is ok ,i dont know how to slove this proplem .
in ubuntu 14.04
```

**Comment by TonyZihao** [comment]
now i have a new problem ,like tihs
user@user-ProLiant-DL380-Gen9:~/digits$ ./digits-devserver 
Default value for caffe_root "<PATHS>" invalid:
	caffe binary not found in PATH
==================================== Caffe =====================================
Where is caffe installed?

	Suggested values:
	(P*) [PATH/PYTHONPATH] <PATHS>
>> ~/caffe
ERROR: Library at "libcaffe.so.1.0.0-rc3" does not have expected suffix "-nv". Are you using the NVIDIA/caffe fork?
Invalid input
>> 

how can i solve it ?thake you very much

**Comment by gheinrich** [comment]
Hello, have a look at Caffe [build instructions](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildCaffe.md) or install Caffe from a .deb package using the [Ubuntu install instructions](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/UbuntuInstall.md)

**Comment by TonyZihao** [comment]
what i installed caffe is BLVC,not Nvidia. is this problem? @gheinrich

**Comment by gheinrich** [comment]
Our instructions are for nv-caffe. DIGITS should work with the latest BVLC but since we don't own the BVLC project we cannot guarantee that it works.

**Comment by TonyZihao** [comment]
@gheinrich i will try to install nv-digits,think you very much !
