### ISSUE TITLE
ImportError: No module named caffe.layers.detectnet.clustering

### ISSUE THREAD

**Issue by layer19** [NVIDIA/DIGITS#1295]
I've read the issues #963 and #1181. The problem is still remains. Here's my code:

```
#include <caffe/caffe.hpp>

int main() {
    caffe::Caffe::set_mode(caffe::Caffe::CPU);

    std::shared_ptr<caffe::Net<float> > _net;
    cv::Mat                             _mean;
    cv::Size                            _input_geometry;
    int                                 _num_channels;

    _net.reset( new caffe::Net<float>( std::string( "/home/alex/ClionProjects/ext_model/deploy.prototxt" ), caffe::TEST ) );
    _net->CopyTrainedLayersFrom( std::string( "/home/alex/ClionProjects/ext_model/DetectNet.caffemodel" ) );

    caffe::Blob<float> *input_layer = _net->input_blobs()[0];
    _num_channels = input_layer->channels();

    _input_geometry = cv::Size(input_layer->width(), input_layer->height());

    const int ciNum      = 1;
    const int ciChannels = 3;
    const int ciHeight   = 640;
    const int ciWidth    = 1024;

    caffe::Blob<float> mean_blob( ciNum, ciChannels, ciHeight, ciWidth );

    std::vector<cv::Mat> channels;
    float* data = mean_blob.mutable_cpu_data();
    for( int i = 0; i < _num_channels; ++i ) {
        cv::Mat channel( mean_blob.height(), mean_blob.width(), CV_32FC1, data );
        channels.push_back( channel );
        data += mean_blob.height() * mean_blob.width();
    }

    cv::Mat mean;
    cv::merge( channels, mean );

    cv::Scalar channel_mean = cv::mean( mean );
    _mean = cv::Mat( _input_geometry, mean.type(), channel_mean );

    caffe::Blob<float> *output_layer = _net->output_blobs()[0];
}
```

This code compiles into a bin-file without a problem. But when I'm trying to run it, the program crashes with this log (see log.txt it's really long but the error I think is on bottom 2 lines: 
ImportError: No module named caffe.layers.detectnet.clustering
terminate called after throwing an instance of 'boost::python::error_already_set')
[log.txt](https://github.com/NVIDIA/DIGITS/files/613013/log.txt)

I don't think it is IDE problem, I use CLion. I get the same error when I put the binary to a caffe root and run in from there. I've setted path variables as:

```
export PATH=${CAFFE_ROOT}/bin:/home/alex/caffe-rc3/python:${PATH}
export PYTHONPATH="${PYTHONPATH}:/home/alex/caffe-rec3/python"
```

`python -c "import caffe; print caffe.__file__" `
returns the line:
` /home/alex/caffe-rc3/python/caffe/__init__.pyc`
which is correct

I've also followed the installation instructions and installed all python packages with 
`for req in $(cat requirements.txt); do pip install $req; done`

Please help me on this, what should be done to make the program work?

**Comment by gheinrich** [comment]
Are you using nv-caffe 0.15.x?

**Comment by layer19** [comment]
No. I'm using this release https://github.com/BVLC/caffe/releases

**Comment by gheinrich** [comment]
DetectNet requires nv-caffe 0.15.x. How did you manage to train a model on BVLC Caffe? If you wish to contribute a detailed guide of how to use DetectNet from a C++ program when you're done, it would be so much appreciated! Thanks in advance!

**Comment by layer19** [comment]
I used NVIDIA DIGITS from here https://github.com/NVIDIA/DIGITS to train a model, but on another computer. Maybe 0.15x was installed there. I will try to install 0.15x and see what happens. Thank you for advice. Of course, will be my pleasure to write a guide if I'll be able to get everything to work.

**Comment by layer19** [comment]
I've installed and configured nv-caffe 0.15.x. It's sad but the problem is still remains.

**Comment by gheinrich** [comment]
did you install `python-caffe-nv` package too? (dependency of `digits` package).

**Comment by layer19** [comment]
I guess no. I did all packages from `python/requirements.txt` and `python-caffe-nv` was not there. Can you please explain how `python-caffe-nv` can be installed properly?  `sudo apt-get install python-caffe-nv` does not work.

**Comment by gheinrich** [comment]
> Can you please explain how python-caffe-nv can be installed properly?

By following the [install instructions](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md). In particular:

```
ML_REPO_PKG=nvidia-machine-learning-repo-ubuntu1404_4.0-2_amd64.deb
wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/${ML_REPO_PKG} -O /tmp/${ML_REPO_PKG}
sudo dpkg -i /tmp/${ML_REPO_PKG}
rm -f /tmp/${ML_REPO_PKG}

# Download new list of packages
sudo apt-get update
```

Then you should be able to install `python-caffe-nv`.

**Comment by gheinrich** [comment]
Or did you build nv-caffe from source? In which case you need to configure DIGITS to use your custom Caffe binary ([instructions for DIGITS 5](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/Configuration.md)).

**Comment by alpop** [comment]
I had same problem, too:  ImportError: No module named layers.detectnet.clustering 
It turned out that I had multiple python installations and multiple python caffe modules. 
I resolved the issue by removing   the offending one  with 'conda uninstall caffe '

**Comment by lukeyeager** [comment]
Yeah, conda is a tempting solution but causes lots of issues. You're on your own if you deviate from our official instructions and use conda instead of pip.

I'm closing this issue as the original issue is surely solved by now. Just follow the installation instructions.
