### ISSUE TITLE
Problem of installing Sunnybrook plugin of medical imaging demonstation 

### ISSUE THREAD

**Issue by toki2015** [NVIDIA/DIGITS#1300]
I am trying the demonstrations,which were stored in examples folder of DIGITS 5.1-dev by using (nvCaffe ver 0.15.14) based on CUDA 8.0 (Nvidia Driver 367.57). The segmentation and object detection worked well, but  I met an problem of medical imaging at the beginning to install  Sunnybrook plugin by 
$ pip install -e $DIGITS_ROOT
$ pip install $DIGITS_ROOT/plugins/data/sunnybrook/
See following message, can anyone tell me why ? 

(digits) user@DeepBox:~/digits/plugins/data/sunnybrook$ pip install -e $DIGITS_HOME
Obtaining file:///home/user/digits
Requirement already satisfied: Pillow<=3.1.2,>=2.3.0 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: numpy<=1.11.0,>=1.8.1 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: scipy<=0.17.0,>=0.13.3 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: protobuf<=2.6.1,>=2.5.0 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: six<=1.10.0,>=1.5.2 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: requests<=2.9.1,>=2.2.1 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: gevent<=1.1.0,>=1.0 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: gevent-websocket==0.9.3 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: Flask==0.10.1 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: Flask-WTF<=0.12,>=0.11 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: wtforms<=2.1,>=2.0 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: Flask-SocketIO==2.6 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Collecting setuptools<=20.7.0,>=3.3 (from digits==5.1.dev0)
  Using cached setuptools-20.7.0-py2.py3-none-any.whl
Requirement already satisfied: lmdb==0.87 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: h5py<=2.6.0,>=2.2.1 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: pydot<=1.0.29,>=1.0.28 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: psutil<=3.4.2,>=1.2.1 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: matplotlib<=1.5.1,>=1.3.1 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: scikit-fmm>=0.0.9 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from digits==5.1.dev0)
Requirement already satisfied: greenlet>=0.4.9 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from gevent<=1.1.0,>=1.0->digits==5.1.dev0)
Requirement already satisfied: itsdangerous>=0.21 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from Flask==0.10.1->digits==5.1.dev0)
Requirement already satisfied: Werkzeug>=0.7 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from Flask==0.10.1->digits==5.1.dev0)
Requirement already satisfied: Jinja2>=2.4 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from Flask==0.10.1->digits==5.1.dev0)
Requirement already satisfied: python-socketio>=1.4 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from Flask-SocketIO==2.6->digits==5.1.dev0)
Requirement already satisfied: python-engineio>=0.9.2 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from Flask-SocketIO==2.6->digits==5.1.dev0)
Requirement already satisfied: pyparsing==1.5.7 in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from pydot<=1.0.29,>=1.0.28->digits==5.1.dev0)
Requirement already satisfied: cycler in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from matplotlib<=1.5.1,>=1.3.1->digits==5.1.dev0)
Requirement already satisfied: pytz in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from matplotlib<=1.5.1,>=1.3.1->digits==5.1.dev0)
Requirement already satisfied: python-dateutil in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from matplotlib<=1.5.1,>=1.3.1->digits==5.1.dev0)
Requirement already satisfied: MarkupSafe in /home/user/.virtualenvs/digits/lib/python2.7/site-packages (from Jinja2>=2.4->Flask==0.10.1->digits==5.1.dev0)
Installing collected packages: setuptools, digits
  Found existing installation: setuptools 28.8.0
Exception:
Traceback (most recent call last):
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/req/req_install.py", line 694, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/wheel.py", line 534, in unique
    for item in fn(*args, **kw):
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/wheel.py", line 553, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1472, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1468, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/home/user/.virtualenvs/digits/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/home/user/.virtualenvs/digits/lib/python2.7/site-packages/setuptools-28.8.0.dist-info/RECORD'

(digits) user@DeepBox:~/digits/plugins/data/sunnybrook$ pip install ~/digits/plugins/data/sunnybrook/
Processing /home/user/digits/plugins/data/sunnybrook
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-McwIzY-build/setup.py", line 6, in <module>
        from digits.extensions.data import GROUP as DIGITS_PLUGIN_GROUP
    ImportError: No module named digits.extensions.data
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-McwIzY-build/

**Comment by gheinrich** [comment]
Hello, the first command:
```
$ pip install -e $DIGITS_ROOT` failed with
```
failed with:
```
IOError: [Errno 2] No such file or directory: '/home/user/.virtualenvs/digits/lib/python2.7/site-packages/setuptools-28.8.0.dist-info/RECORD'`:
```
Can you check if your virtual environment is sane? In my environment this file exists.

**Comment by toki2015** [comment]
I found the fold of 
user@DeepBox:~/.virtualenvs/digits/lib/python2.7/site-packages/setuptools-28.8.0.dist-info
has a one file named  
INSTALLER

thanks

**Comment by gheinrich** [comment]
I meant "sane" as in "sanity" - please verify that everything is correct. If necessary, re-install and un-install and re-install `setuptools` or the whole virtual env.

This is what I see:
```
$ ls .../lib/python2.7/site-packages/setuptools-28.8.0.dist-info/
dependency_links.txt  DESCRIPTION.rst  entry_points.txt  INSTALLER  METADATA  metadata.json  RECORD  top_level.txt  WHEEL  zip-safe
```

**Comment by toki2015** [comment]
Thank you very much,I tried to remove the setuptools 
$ pip uninstall setuptools
and got the same error 
IOError: [Errno 2] No such file or directory: '/home/user/.virtualenvs/digits/lib/python2.7/site-packages/setuptools-28.8.0.dist-info/RECORD'
I will try another way, thank you again !

**Comment by balouji** [comment]
Hi
I have the same problem also
when I install the pip install -e $DIGITS_ROOT
Usage:   
  pip install [options] <requirement specifier> ...
  pip install [options] -r <requirements file> ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...
 have above mentioned lines 
and then this is going to happen
pip install $DIGITS_ROOT/plugins/data/sunnybrook/
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2833, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2781, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2790, in __init__
    raise RequirementParseError(str(e))
RequirementParseError: Invalid requirement, parse error at "'/plugins'"

Storing debug log for failure in /tmp/tmpm_CQsC

it would be wonderful if you could help me out

**Comment by lukeyeager** [comment]
You haven't set the `DIGITS_ROOT` environment variable.

If you're already in the root of your DIGITS installation, just remove it and use local paths.
```
pip install -e .
pip install plugins/data/sunnybrook/
```

**Comment by balouji** [comment]
thanks and how about installing the text classifier ?

**Comment by balouji** [comment]
and there is this problem also happed on 
error: could not create '/usr/local/lib/python2.7/dist-packages/dicom': Permission denied

**Comment by elliotekoch** [comment]
I'm getting the missing digits.extensions.data module too, but the uninstall/reinstall for setup tools didn't work.  Any other suggestions?

sudo pip uninstall setuptools
Cannot uninstall requirement setuptools, not installed
ekoch@bil9001.nvidia.com> sudo pip install setuptools
Collecting setuptools
  Using cached setuptools-35.0.2-py2.py3-none-any.whl
Requirement already satisfied: six>=1.6.0 in /usr/lib/python2.7/site-packages (from setuptools)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python2.7/site-packages (from setuptools)
Requirement already satisfied: packaging>=16.8 in /usr/lib/python2.7/site-packages (from setuptools)
Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging>=16.8->setuptools)
Installing collected packages: setuptools
Successfully installed setuptools-35.0.2
ekoch@bil9001.nvidia.com> sudo pip install setuptools
ekoch@bil9001.nvidia.com> sudo yum update
Loaded plugins: aliases, changelog, fastestmirror, kabi, langpacks, product-id, search-disabled-repos, subscription-manager,
              : tmprepo, verify, versionlock
This system is not registered with Subscription Management. You can use subscription-manager to register.
Loading support for Red Hat kernel ABI
Loading mirror speeds from cached hostfile
 * base: mirror.sjc02.svwh.net
 * extras: mirrors.kernel.org
 * updates: mirror.scalabledns.com
No packages marked for update
ekoch@bil9001.nvidia.com> sudo pip install $DIGITS_ROOT/plugins/data/textClassification
Processing /root/digits/plugins/data/textClassification
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-r4KnIQ-build/setup.py", line 5, in <module>
        from digits.extensions.data import GROUP as DIGITS_PLUGIN_GROUP
    ImportError: No module named digits.extensions.data
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-r4KnIQ-build/
ekoch@bil9001.nvidia.com> python -V
Python 2.7.5

**Comment by gheinrich** [comment]
Hello, did you install DIGITS too? As per the instructions:

```
$ pip install -e $DIGITS_ROOT
```

**Comment by elliotekoch** [comment]
Yes I did. It’s working fine for images on the browser, but cannot install any plugins
