### ISSUE TITLE
error with using prototxt alexnet file

### ISSUE THREAD

**Issue by Emma20102** [NVIDIA/DIGITS#1314]
i am doing calssification model using nvidia digits. i got very low accuracy and i just cut and past the alexnet.prototxt file in the custom place tring to increase the accuracy but its giving me errors.
is their any way to get ride of theses errors. how can i eddit the prototxt code to get valid result.
this is the link of the alexnet prototext file that i used.
https://raw.githubusercontent.com/BVLC/caffe/rc3/models/bvlc_alexnet/deploy.prototxt

**Comment by gheinrich** [comment]
Hello, if you click on the question mark next to "Custom network" this will show instructions to follow for creating custom network:
![image](https://cloud.githubusercontent.com/assets/3889770/20791786/08431374-b7bf-11e6-9f01-8a164ff95c1b.png)

However using the Alexnet prototxt from BVLC will probably not help improve the accuracy.
