### ISSUE TITLE
Extract the vectors of the last FC layer from digits caffe

### ISSUE THREAD

**Issue by RoroKA** [NVIDIA/DIGITS#1317]
I used Digits/Caffe to design CNN based on AlexNet. I need to get the vector of the last fully connected layer ( before performing Sofmax ) for all images I used in the training and validation. My plan is to use these vectors of the the images as an input to another Network. How can I get these vectors using caffe?

**Comment by gheinrich** [comment]
Check this recipe:
https://groups.google.com/d/msg/digits-users/HLhwy2R4G5Q/foKsFAxXAwAJ

**Comment by RoroKA** [comment]
Thank you so much
