### ISSUE TITLE
command line execution of Docker based Digits using text-classification plugins

### ISSUE THREAD

**Issue by elliotekoch** [NVIDIA/DIGITS#1318]
I'm new to workng with both Docker and Digits. Couldn't find an example of using Docker Digits to create a dataset , test etc. from command line.
Referenced Crepe article and this one.

Tried this but no luck:
sudo nvidia-docker run qlua -nographics ../ref/text-classification-model.lua -input rtda_csv/train.csv -output train.t7b
Using default tag: latest
Pulling repository docker.io/library/qlua
nvidia-docker | 2016/12/01 13:01:56 Error: image library/qlua:latest not found

text-classification-model.lua came from the text plugin page: https://github.com/NVIDIA/DIGITS/tree/ade0287f15b2ba57ebfee41fd1fb5f1645803921/examples/text-classification

Suggestions? Or can you point me to an example?
Thanks,
Elliot

**Comment by gheinrich** [comment]
Greetings @elliotekoch ! You might find this project useful:
https://github.com/kertansul/dl-docker/blob/master/Dockerfile.digits

@kertansul maintains a Dockerfile for DIGITS which points to the 5.0 pre-release.

Also make sure you review https://github.com/kertansul/dl-docker/blob/master/README.md - there are instructions there for setting up a shared volume between the host and the container (you will probably want to copy your dataset in a shared volume).

**Comment by elliotekoch** [comment]
Thanks Greg! Digesting...
