### ISSUE TITLE
Standard Datasets

### ISSUE THREAD

**Issue by ibmua** [NVIDIA/DIGITS#132]
https://github.com/NVIDIA/DIGITS/blob/master/docs/StandardDatasets.md
It seems like the developers had changed the files, so that things like
python tools/download_data/main.py cifar100 ~/data/cifar100
doesn't really work anymore.

**Comment by lukeyeager** [comment]
It works for me. What error are you getting? Did you create the `~/data` directory first? That's just an example location.
```bash
mkdir ~/data
python tools/download_data/main.py cifar100 ~/data/cifar100
```

**Comment by lukeyeager** [comment]
I'll assume that fixed your problem. If not, let me know.
