### ISSUE TITLE
explore DB images not showing in Segmentation Dataset with 8bit per pixel PNGs

### ISSUE THREAD

**Issue by klaimane** [NVIDIA/DIGITS#1322]
Segmentation Dataset created from RGB label images with cmap and single channel grayscale 8bpp images. Data set creation succeeds but when exploring the lmdb set via DIGITS label images loko fine but the feature images are all white.

Manual access of the LMDB file shows pixel values are OK inside the binary, i.e. 
```py
import caffe
import lmdb
import PIL.Image
from StringIO import StringIO
import numpy as np

def read_lmdb(lmdb_file):
    cursor = lmdb.open(lmdb_file, readonly=True).begin().cursor()
    datum = caffe.proto.caffe_pb2.Datum()
    for _, value in cursor:
        datum.ParseFromString(value)
        s = StringIO()
        s.write(datum.data)
        s.seek(0)

        yield np.array(PIL.Image.open(s)), datum.label


lmdb_dir = '.../digits/20161202-151228-8632/train_db/features'
for im, label in read_lmdb(lmdb_dir):
    print label, np.min(im), np.max(im)
```

yields:   (from print label, np.min(im), np.max(im))
...
...
0 165 255
0 48 255
0 144 255
0 16 255
0 24 255
0 10 255
0 165 255
0 173 255
0 156 255
0 20 255
0 180 255
0 18 255
0 10 255
0 22 255
0 164 255
0 97 255
0 14 255
0 107 255
0 210 255
0 150 255
...
...

The feature images were saved from a numpy array with cv2.imwrite(image_path, image) where image is a uint8 array of size (1024,1024,1)

I'm guessing something in the HTML embedding isn't going well.

**Comment by gheinrich** [comment]
Thanks for the feedbac @klaimane can you try the patch from #1325?
