### ISSUE TITLE
What command line DIGITS uses when testing a  trained object-detection-model ?

### ISSUE THREAD

**Issue by skyzhao3q** [NVIDIA/DIGITS#1329]
I am currently trying to manually test my Digits trained object-detection model.
However I don‘t know how to use the model from script .
Therefore, I would like to know the command line that DIGITS calls under the hood when detecting one image from the GUI.
Thanks

**Comment by gheinrich** [comment]
Hello, have a look at the command-line API: https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/API.md
