### ISSUE TITLE
Cannot copy param 0 weights from layer...

### ISSUE THREAD

**Issue by matiaszilli** [NVIDIA/DIGITS#1331]
I was trying to train your Caffe network. I trained it with Digits very well, but when I try to get the output with python, I get the following error:

" Cannot copy param 0 weights from layer 'bn1a'; shape mismatch.  Source param shape is 16 (16); target param shape is 1 16 1 1 (16). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer ".

To compute the output I downloaded from Digits the complete model and I modified the deploy.prototxt. I am attaching my Digits model and my deploy that I am using to get the output and this is the problematic line:
net_full_conv = caffe.Net('deploy_toOutput.prototxt',
                          'snapshot_iter_37740_adenBig64_pre.caffemodel', caffe.TEST)

Thanks in advance.
Best regards.

[deplot_toOutput.txt](https://github.com/NVIDIA/DIGITS/files/631037/deplot_toOutput.txt)
[20161204-054513-2abe_epoch_30.0.tar.gz](https://github.com/NVIDIA/DIGITS/files/631039/20161204-054513-2abe_epoch_30.0.tar.gz)

**Comment by gheinrich** [comment]
Hello, are you using the same version of Caffe to train and test the model?

**Comment by matiaszilli** [comment]
Yes, I tried to use the nvidia digits caffe to compute the forward and it
works good!. The problem was the different versions.
Thank you so much!.

2016-12-05 16:38 GMT+01:00 Greg Heinrich <notifications@github.com>:
