### ISSUE TITLE
building from source for python3 fails due to unmet requirements

### ISSUE THREAD

**Issue by achaiah** [NVIDIA/DIGITS#1334]
Trying to build DIGITS by following `DIGITS/docs/BuildDigits.md` results in an error.  The issue happens when executing `sudo pip install -r $DIGITS_ROOT/requirements.txt`

The version of pydot in the requirements.txt `pydot>=1.0.28,<=1.0.29` only exists for python2 installations.  Only versions of pydot > 1.2.0 are supported in python3. See [here](https://github.com/davidvilla/pydot/issues/4#issuecomment-265255641).

This causes the build to fail as the requirement cannot be met.

**Comment by achaiah** [comment]
Nevermind, I guess DIGITS is not designed to run in python3 :(

**Comment by lukeyeager** [comment]
See https://github.com/NVIDIA/DIGITS/issues/511.
