### ISSUE TITLE
Error Code -11 Training DetectNet on KITTI

### ISSUE THREAD

**Issue by MikepX99** [NVIDIA/DIGITS#1336]
I get this error repeatedly while trying to train DetectNet on the KITTI dataset.

```
Iteration 632 (0.410104 iter/s, 192.634s/79 iter), loss = 20.8109
Train net output #0: loss_bbox = 7.84001 (* 2 = 15.68 loss)
Train net output #1: loss_coverage = 16.201 (* 1 = 16.201 loss)
Iteration 632, lr = 0.0001
Snapshotting to binary proto file snapshot_iter_638.caffemodel
Snapshotting solver state to binary proto file snapshot_iter_638.solverstate
Iteration 638, Testing net (#0)
Ignoring source layer train_data
Ignoring source layer train_label
Ignoring source layer train_transform
```
        
![image](https://cloud.githubusercontent.com/assets/24439078/20978833/69d6a796-bc78-11e6-963e-d60a8c2ab9ac.png)

I am following this example and everything else in DIGITS seems to work just fine so I believe that it is related to opencv but am unsure of how to proceed:

 https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection

**Comment by lukeyeager** [comment]
Can you please download the Caffe log and paste the last 20 lines or so? That often gives more information about what's going wrong.

**Comment by MikepX99** [comment]
```
`I1207 11:34:31.858978  3655 solver.cpp:479] Snapshotting to binary proto file snapshot_iter_638.caffemodel
I1207 11:34:31.982125  3655 sgd_solver.cpp:273] Snapshotting solver state to binary proto file snapshot_iter_638.solverstate
I1207 11:34:32.040336  3655 solver.cpp:362] Iteration 638, Testing net (#0)
I1207 11:34:32.040355  3655 net.cpp:723] Ignoring source layer train_data
I1207 11:34:32.040359  3655 net.cpp:723] Ignoring source layer train_label
I1207 11:34:32.040360  3655 net.cpp:723] Ignoring source layer train_transform
*** Aborted at 1481128472 (unix time) try "date -d @1481128472" if you are using GNU date ***
PC: @     0x7f557a50763c cv::_InputArray::type()
*** SIGSEGV (@0x10000) received by PID 3655 (TID 0x7f5584dde800) from PID 65536; stack trace: ***
@     0x7f5582b74cb0 (unknown)
@     0x7f557a50763c cv::_InputArray::type()
@     0x7f557a438288 cv::Mat::copyTo()
@     0x7f532e4f1d83 (unknown)
@     0x7f532e59a3d2 (unknown)
@     0x7f55837bbb94 (unknown)
@     0x7f55837bbb19 (unknown)
@     0x7f55837bbb19 (unknown)
@     0x7f55837bdc3d (unknown)
@     0x7f55837bddd0 (unknown)
@     0x7f55837920a3 (unknown)
@     0x7f5583736d6d (unknown)
@     0x7f55837920a3 (unknown)
@     0x7f55838255f7 (unknown)
@     0x7f55837405d7 (unknown)
@     0x7f5384180755 caffe::PythonLayer<>::Forward_cpu()
@     0x7f558470c238 caffe::Net<>::ForwardFromTo()
@     0x7f558470c5b7 caffe::Net<>::Forward()
@     0x7f558475da7a caffe::Solver<>::Test()
@     0x7f558475e2fe caffe::Solver<>::TestAll()
@     0x7f55847608cd caffe::Solver<>::Step()
@     0x7f558476128e caffe::Solver<>::Solve()
@           0x40af86 train()
@           0x4086cc main
@     0x7f5582b5ff45 (unknown)
@           0x408e9d (unknown)
@                0x0 (unknown)`
```

**Comment by lukeyeager** [comment]
Looks like a segfault in an OpenCV call which is coming from a Python layer.

What version of OpenCV are you using?

**Comment by MikepX99** [comment]
I am not sure, how do I find out on my machine?  I am trying a complete reinstall of caffe and opencv so hopefully this will fix it.  I'll post the new results of the DetectNet training as soon as it runs.

**Comment by lukeyeager** [comment]
`dpkg -l | grep opencv` will probably work. Unless you built from source.

**Comment by MikepX99** [comment]
The last line is python-opencv 2.4.8

**Comment by lukeyeager** [comment]
That's a good sign. That means your OpenCV build is probably fine.

**Comment by MikepX99** [comment]
I just got opencv, cuda, caffe, torch, and digits reinstalled so I'm hoping that this hard purge and reinstall will fix the problem.  I'm just importing the KITTI dataset into DIGITS again so I will be running DetectNet again soon, hopefully the net will train now.

**Comment by MikepX99** [comment]
The training fails at the same point but now the error changes to Error Code 1 instead of -11.  This are the last few lines of the log.

```
I1207 14:25:54.376837  5216 solver.cpp:479] Snapshotting to binary proto file snapshot_iter_638.caffemodel
I1207 14:25:54.523226  5216 sgd_solver.cpp:273] Snapshotting solver state to binary proto file snapshot_iter_638.solverstate
I1207 14:25:54.571719  5216 solver.cpp:362] Iteration 638, Testing net (#0)
I1207 14:25:54.571735  5216 net.cpp:723] Ignoring source layer train_data
I1207 14:25:54.571738  5216 net.cpp:723] Ignoring source layer train_label
I1207 14:25:54.571740  5216 net.cpp:723] Ignoring source layer train_transform
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/travis/miniconda/conda-bld/work/opencv-3.1.0/modules/core/src/matrix.cpp, line 1879
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/travis/miniconda/conda-bld/work/opencv-3.1.0/modules/core/src/matrix.cpp, line 1879
Traceback (most recent call last):
File "/home/mike/caffe/python/caffe/layers/detectnet/clustering.py", line 133, in forward
bbox = cluster(self, data0, bottom[1].data)
File "/home/mike/caffe/python/caffe/layers/detectnet/clustering.py", line 227, in cluster
boxes_cur_image = vote_boxes(propose_boxes, propose_cvgs, mask, self)
File "/home/mike/caffe/python/caffe/layers/detectnet/clustering.py", line 193, in vote_boxes
self.gridbox_rect_eps)
cv2.error: /home/travis/miniconda/conda-bld/work/opencv-3.1.0/modules/core/src/matrix.cpp:1879: error: (-213) Unknown/unsupported array type in function type
```

**Comment by lukeyeager** [comment]
Why'd you switch to OpenCV 3.1.0?

If you're using miniconda, then you aren't following our instructions to build from source:
https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md

Let me know if you have any problem with those instructions.

**Comment by MikepX99** [comment]
I followed those instructions.  I guess I have opencv3 installed through anaconda also and opencv2 through ubuntu's package manager.  I will try uninstalling opencv3 through conda and then retrain so opencv2 is called instead.

**Comment by MikepX99** [comment]
I have completely removed anaconda and every package with it so hopefully that removes both python3.5 and opencv3 which will only leave python2.7 and opencv left on my machine.

**Comment by MikepX99** [comment]
Reinstalling everything and removing Anaconda allowed the training to make it past epoch 1 and the validation test.  Hopefully DetectNet will properly train now.

**Comment by MikepX99** [comment]
For anyone else who runs into issues with different python versions, you need to clear your PATH variable in your .bashrc and .profile files.  I needed python3 for opencv and other computer vision projects but DIGITS requires python2 so if you clear your PATH variable then you can have both versions on your machine you just have to execute the script manually by navigating to the scripts home directory.

**Comment by zhixianGuo** [comment]
@MikepX99 Hi! I have the same problem as you ! So you solved it already?

I0313 13:20:33.195091  3798 net.cpp:723] Ignoring source layer train_data
I0313 13:20:33.195098  3798 net.cpp:723] Ignoring source layer train_label
I0313 13:20:33.195104  3798 net.cpp:723] Ignoring source layer train_transform
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/dell/mycaffe/OpenCV/opencv-3.0.0/modules/core/src/matrix.cpp, line 1837
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/dell/mycaffe/OpenCV/opencv-3.0.0/modules/core/src/matrix.cpp, line 1837
Traceback (most recent call last):
File "/home/dell/gzx/caffe/python/caffe/layers/detectnet/clustering.py", line 133, in forward
bbox = cluster(self, data0, bottom[1].data)
File "/home/dell/gzx/caffe/python/caffe/layers/detectnet/clustering.py", line 227, in cluster
boxes_cur_image = vote_boxes(propose_boxes, propose_cvgs, mask, self)
File "/home/dell/gzx/caffe/python/caffe/layers/detectnet/clustering.py", line 193, in vote_boxes
self.gridbox_rect_eps)
cv2.error: /home/dell/mycaffe/OpenCV/opencv-3.0.0/modules/core/src/matrix.cpp:1837: error: (-213) Unknown/unsupported array type in function type
