### ISSUE TITLE
How to install dependencies of digits   ?

### ISSUE THREAD

**Issue by phpmind** [NVIDIA/DIGITS#1342]
qw@qw:~/Downloads$ sudo apt-get install digits
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 digits : Depends: python-caffe-nv (>= 0.13) but it is not going to be installed
          Depends: caffe-nv (>= 0.13) but it is not going to be installed
          Recommends: torch7-nv but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

How to fix this bug ??? 

Thanks

**Comment by lukeyeager** [comment]
Sorry, `apt-get` doesn't give very helpful error messages. Try using `aptitude` instead and let's see if we can get some more information.
```sh
sudo apt-get install aptitude
sudo aptitude install digits
```

**Comment by phpmind** [comment]
Hi lukeyeager, 

I manage to install . 

Thanks
