### ISSUE TITLE
how to fine tune Alexnet or GoogLenet?

### ISSUE THREAD

**Issue by forloverj** [NVIDIA/DIGITS#1343]
I want to fine tune a AlexNet. If there is an AlexNet Previous Networks? Or like caffe fine tuning with a weights file? Any help appreciate.

**Comment by gheinrich** [comment]
Hello you can download a pre-trained Alexnet (pre-trained on ILSVRC2012) on http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel and point the "Pretrained model" field of the "custom network" tab to this file when creating your model.

**Comment by forloverj** [comment]
Thank you @gheinrich. Now I have solve the problem. But I got the the error that channel does not match. I n fact ,my data set is gray channel,but the default Alexnet is three channel. Then how to make my fine tuned Alexnet work?

**Comment by gheinrich** [comment]
There are several ways to fix this (by increasing level of complexity):
- re-create your dataset as an RGB dataset
- train your own Alexnet on a grayscale ILSVRC2012
- perform net surgery on your pre-trained Alexnet model to reduce the number of input feature maps on the first convolutional layer from 3 to 1

**Comment by forloverj** [comment]
thank you very much @gheinrich.I have known how to do.
