### ISSUE TITLE
/usr/share/digits/tools/download_data/main.py not working

### ISSUE THREAD

**Issue by phpmind** [NVIDIA/DIGITS#1344]
I am new to Digit!  I installed Digit now i and need data to load. 

This script is not available -  which is stated here : https://github.com/brainstorm-ai/DIGITS/blob/bs/dev/docs/GettingStarted.md 

Use the following command to download the MNIST dataset (for Deb package installations, the script is at **/usr/share/digits/tools/download_data/main.py**):

Am i missing something ? 

Thanks

**Comment by gheinrich** [comment]
Is the doc your are reading in line with the version of DIGITS you are using? If you are using DIGITS 4.0 this is the relevant doc: https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/GettingStarted.md
