### ISSUE TITLE
how to make the classify one Image to show the gray weights and activation images in visualization and statistics.

### ISSUE THREAD

**Issue by forloverj** [NVIDIA/DIGITS#1345]
When Ｉ test a signal  gray image after trained a model , but I find the visualizations of weights ,conv activation and pool images are showed RGB images. that shouldn't be gray image?. After turn off the "Allow_heatmap"  the weights change to gray ,but others are till RGB. How is this? Thank you very much.

**Comment by gheinrich** [comment]
Hello, we are using Jet color maps to display feature maps: http://matplotlib.org/users/colormaps.html
Many people find it easier to understand than using gray scales.

**Comment by forloverj** [comment]
thanks for your help.@gheinrich.I have solved it.
