### ISSUE TITLE
Shape Mismatch

### ISSUE THREAD

**Issue by filipetrocadoferreira** [NVIDIA/DIGITS#1348]
I've trained a googlenet in digits to use only 2 channels image. After train was done , when trying to infere in a python script i get this : 
`Cannot copy param 0 weights from layer 'conv1/7x7_s2'; shape mismatch.  Source param shape is 64 1 7 7 (3136); target param shape is 64 2 7 7 (6272). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***

`

How can it be expecting a 64x1 when the train was done using 2channels image?

**Comment by gheinrich** [comment]
Are you sure you trained on 2-channel images? How did you do it?

**Comment by filipetrocadoferreira** [comment]
In deploy: 
input: "data"
input_shape {
  dim: 1
  dim: 2
  dim: 160
  dim: 160
}

During train:



    DB backend: lmdb
    Analyze DB (Training Images)
        Image Count - 117580
        Image Dimensions - 160x160x2
    Analyze DB (Training Labels)
        Image Count - 117580
        Image Dimensions - 3x1x1
    Analyze DB (Validation Images)
        Image Count - 3920
        Image Dimensions - 160x160x2
    Analyze DB (Validation Labels)
        Image Count - 3920
        Image Dimensions - 3x1x1

**Comment by gheinrich** [comment]
If I remember correctly the data settings are mostly ignored during deployment and are merely used to figure out the number of input dimensions. What really matters is the shape of the first batch you pass to the net in `forward()` - make sure this has 2-channel images.

**Comment by gheinrich** [comment]
You can check your model's `caffe_output.log` to inspect the input shape.
