### ISSUE TITLE
train_lmdb and val_lmdb  location

### ISSUE THREAD

**Issue by RoroKA** [NVIDIA/DIGITS#1349]
Hi 

Where can I find train_lmdb and val_lmdb output from digits?
The one generated by new DataSet as classification problem

Thanks

**Comment by lukeyeager** [comment]
You can find the job directory on the job page. That directory on your server will contain the LMDBs.

**Comment by RoroKA** [comment]
Thanks for your reply.
I actually searched this location and I can't find any files with LMDB extension 

or do you mean data.mdb?
is data.mdb the LMDB file?

**Comment by lukeyeager** [comment]
The directory containing `data.mdb` is the lmdb "file".

**Comment by lukeyeager** [comment]
I can't find the documentation for this, but it's discussed here: https://github.com/BVLC/caffe/pull/2384.

**Comment by RoroKA** [comment]
Thank you so much for your help

**Comment by antoniodourado** [comment]
@lukeyeager sorry for reviving this post, but you meant that the whole directory containg `data.mdb` is the lmdb file or just the `data.mdb` file? Because usually there is a `lock.mdb` there also.
Should I point `data.mdb` as my lmdb file or the whole directory as source for lmdb?
Thank you.
