### ISSUE TITLE
digits not found in apt-get

### ISSUE THREAD

**Issue by kvrd18** [NVIDIA/DIGITS#1355]
I get the following error when I run `sudo apt-get install digits` on my Ubuntu 14.04.

```bash
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package digits is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'digits' has no installation candidate
```

**Comment by kvrd18** [comment]
I tried `sudo apt-get update`. Still doesn't work.

**Comment by kvrd18** [comment]
Is there way to add digit's PPA?

**Comment by gheinrich** [comment]
Hello, please see these [install instructions](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/UbuntuInstall.md).

**Comment by kvrd18** [comment]
Hi,

I executed the following codes as given there.

```bash
# Access to CUDA packages
CUDA_REPO_PKG=cuda-repo-ubuntu1404_7.5-18_amd64.deb
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/${CUDA_REPO_PKG} -O /tmp/${CUDA_REPO_PKG}
sudo dpkg -i /tmp/${CUDA_REPO_PKG}
rm -f /tmp/${CUDA_REPO_PKG}

# Access to Machine Learning packages
ML_REPO_PKG=nvidia-machine-learning-repo-ubuntu1404_4.0-2_amd64.deb
wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/${ML_REPO_PKG} -O /tmp/${ML_REPO_PKG}
sudo dpkg -i /tmp/${ML_REPO_PKG}
rm -f /tmp/${ML_REPO_PKG}

# Download new list of packages
sudo apt-get update
```
digits is still not available from apt.

FYI, I checked for any nvidia files inside `/etc/apt/sources.list.d/` and I did not find any.

**Comment by lukeyeager** [comment]
Are you running Ubuntu 14.04?
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

Were the repo packages successfully installed on your system?
```sh
$ dpkg -l | grep 'repo-'
```

You can use our PPAs if you like, but they still require that you have access to the NVIDIA machine-learning repo in order to get Caffe, Torch, cuDNN, etc. The PPAs only provides DIGITS and it's Python dependencies: https://launchpad.net/~nvidia-digits.

**Comment by kvrd18** [comment]
Yes, I'm on the Ubuntu 14.04. For some unknown reason, the Machine Learning package was deleted from my file system. I downloaded the package from the [NVIDIA repo](http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64) and ran `sudo dpkg -i digits_4.0.0-1_amd64.deb`. Digits is available in apt again. Thank you.

**Comment by melzoghbi** [comment]
I am having the same issue, i run CentOS 7.3.1611

**Comment by lukeyeager** [comment]
@melzoghbi check the first section of the README. No packages are provided for CentOS.
