### ISSUE TITLE
DIGITS GPU ID appears to disagree with nvidia-smi

### ISSUE THREAD

**Issue by DarylWM** [NVIDIA/DIGITS#1358]
My DL machine has four GPUs. I'm training a model on two of them. In DIGITS I selected GPU 2 and 3 for training, but the GPU utilisation showing in nvidia-smi says the training is happening on GPU 0 and 1.

I'm using:
Ubuntu 16.04
NVIDIA driver 367.57
DIGITS built from source (tagged DIGITS-5.1-dev)
NVcaffe built from source (tagged 0.15.14)
GeForce GTX 1080

**Comment by lukeyeager** [comment]
This is expected behavior. `nvidia-smi` lists the GPUs in PCI order and CUDA lists by "best first".

See `CUDA_DEVICE_ORDER` here: https://docs.nvidia.com/cuda/cuda-c-programming-guide/#env-vars

http://stackoverflow.com/q/13781738/2404152
http://stackoverflow.com/q/26123252/2404152

**Comment by lukeyeager** [comment]
https://github.com/NVIDIA/nvidia-docker/issues/262#issuecomment-265672175

**Comment by DarylWM** [comment]
OK - thanks @lukeyeager
