### ISSUE TITLE
 [INFO ] Loaded 0 jobs.

### ISSUE THREAD

**Issue by 91Eric** [NVIDIA/DIGITS#1365]
I already installed cuda8.0 cudnn5.0,caffe and other dependences .And I installed digits follow the  guides  **https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md**  , all  works well.But when I run digits using    ./digits-devserver  in folder ~/digits  ,I get the information ::
2016-12-29 13:44:08 [INFO ] Loaded 0 jobs. 
Who could tell me the reason ,Thank you very much

**Comment by lukeyeager** [comment]
It's just a notification to tell you how many jobs have been loaded from your job directory. For a new installation or an empty `JOBS_DIR`, that will be 0.

**Comment by zhangyeaixuexi** [comment]
./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.0.0-rc.2

Tensorflow support disabled.
2017-09-12 11:23:31 [INFO ] Loaded 0 jobs.

**Comment by zhangyeaixuexi** [comment]
./digits-devserver
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.0.0-rc.2

Tensorflow support disabled.
2017-09-12 11:23:31 [INFO ] Loaded 0 jobs.
i met the same question,what should i do?Thank you very much
