### ISSUE TITLE
"Train" and "Val" labels creation tool to be used with DIGITS and DetectNet

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1370]
Hello,

As I realized, if we decided to use DIGITS and Caffe to **detect** objects then we can use a suitable `.caffemodel` in accompany with DetectNet. 

Anyway, it seems we have to make our Dataset in the form of KITTI (below image). 

![figure3-300x278 1](https://cloud.githubusercontent.com/assets/18719591/21646122/20a5f69c-d2aa-11e6-8bfd-a6b5e19ad9fa.png)

**is there any tool to make these labels/annotations?**

**Comment by ontheway16** [comment]
Hello, please check the following;

https://github.com/tzutalin/labelImg

Its too bad that there is no image database type of software app. In this one, after closing the current image file, you cannot retrieve former labellings.

**Comment by ontheway16** [comment]
You are right but after importing, a little work in excel may help you to convert them to Kitti format. Thats what I am doing.

**Comment by look-recognize** [comment]
https://github.com/prabindh/euclid
It's a labeling tool for KITTI format

**Comment by isaacperez** [comment]
You can use [https://github.com/tzutalin/labelImg](https://github.com/tzutalin/labelImg)  and after you can transform the output .xml file to KITTI format with this file [https://github.com/amlarraz/label-tools/blob/master/xml_to_kitty.py](https://github.com/amlarraz/label-tools/blob/master/xml_to_kitty.py)

**Comment by VanitarNordic** [comment]
Thank you all

**Comment by eleboss** [comment]
@isaacperez Thank you ! that helps me a lot.

**Comment by kargarisaac** [comment]
is there any code to convert tracklet_labels.xml file into text files?
I have downloaded data from http://www.cvlibs.net/datasets/kitti/raw_data.php and want to convert labels to files same as labels from http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d
