### ISSUE TITLE
Digits (5.1dev) and Caffe (1.0.0 rc3) Detectnet error

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1372]
Hello,

When I try to train the detectnet, I get this following error:

```
ParseError

72:3 : Message type "caffe.LayerParameter" has no field named "detectnet_groundtruth_param".
```

any idea?

**Comment by lukeyeager** [comment]
> In order to train DetectNet, NVcaffe version 0.15.1 or later is required.
https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/object-detection#detectnet

**Comment by VanitarNordic** [comment]
I am using the latest version.

**Comment by lukeyeager** [comment]
Use this: https://github.com/NVIDIA/caffe

Not this: https://github.com/BVLC/caffe

**Comment by VanitarNordic** [comment]
Thanks, it solved this issue.
