### ISSUE TITLE
Detectnet training error

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1374]
Hello,
Why I get this error? (I'm running on CPU)

**ERROR: error code 1**

```
Memory required for data: 1278351616
Creating layer bbox_loss
Creating Layer bbox_loss
bbox_loss <- bboxes-obj-masked-norm
bbox_loss <- bbox-obj-label-norm
bbox_loss -> loss_bbox
Setting up bbox_loss
Top shape: (1)
with loss weight 2
Memory required for data: 1278351620
Creating layer coverage_loss
Creating Layer coverage_loss
coverage_loss <- coverage_coverage/sig_0_split_0
coverage_loss <- coverage-label_slice-label_4_split_0
coverage_loss -> loss_coverage
Setting up coverage_loss
Top shape: (1)
with loss weight 1
Memory required for data: 1278351624
Creating layer cluster
```

This error is at the end of caffe log file:
```
import cv2 as cv
ImportError: No module named cv2
```
I have installed the opencv by these dependencies:    

```
sudo apt-get install libprotobuf-dev libleveldb-dev libsnappy-dev libopencv-dev libhdf5-serial-dev protobuf-compiler
sudo apt-get install --no-install-recommends libboost-all-dev  
```   

I should not get this error.

**Comment by VanitarNordic** [comment]
it seems it got fixed by running this command: `sudo apt-get install python-opencv`

but I keep this thread open till if the error does not persist. then I gonna close this issue myself.

**Comment by edregansolution** [comment]
Hello, I got the similar error when train models:
**"Train Caffe Model Error
    Initialized at 08:32:53 PM (1 second)
    Running at 08:32:54 PM (1 second)
    Error at 08:32:55 PM
    (Total - 2 seconds)
ERROR: error code -11
Setting up coverage_loss
Top shape: (1)
with loss weight 1
Memory required for data: 2451719688
Creating layer cluster    
"**

My Ubuntu 16.04.3 LTS (xenial)
Python: 2.7.12
OpenCV: 3.4.0-dev
Protobuf:3.5.1
Cuda Tool Kit: v9.1
CuDNN: v7.1
Caffe: caffe-0.15(nvcaffe)
My NVIDIA card: GeForce GTX 1070 (8 GB)

I am building an object detection system(vehicle), and I'm using drone images(1280X720, 1920X1080, 4096X2160).
When i create dataset, I set Pad image size as 4096(width) and 2160(height).
Also I set resize image size as 1280(width) and 720(height).

I will attach my Makefile.config, caffe log and some other files.
Currently I'm trying to install digits object recognition system with my models, but I'm failed every time over about 20 times with various errors.
I would like to get working as soon as possible.
Thank you
Ed


![screen shot 2018-01-15 at 10 56 05 am](https://user-images.githubusercontent.com/31979503/34958034-f4bb735a-f9e4-11e7-8940-a72c5c6fb4d6.png)
![screen shot 2018-01-15 at 11 10 17 am](https://user-images.githubusercontent.com/31979503/34958036-f4f0edb4-f9e4-11e7-9976-66674b1e25d5.png)

**Comment by goldservice2017** [comment]
I have similar issue with this.
Last time about 3 months ago, I could not fix this issue.
When I train models, I got various strange errors, but I could not find similar case or solution on the internet or this blog.
@lukeyeager
Would you let me know how we can resolve issue?
Thank you

**Comment by ENDISON** [comment]
> [caffe_output_log.txt](https://github.com/NVIDIA/DIGITS/files/1632766/caffe_output_log.txt)
> [Makefile.config.txt](https://github.com/NVIDIA/DIGITS/files/1632767/Makefile.config.txt)
> 
> Hello, I got the similar error when train models:
> **"Train Caffe Model Error Initialized at 08:32:53 PM (1 second) Running at 08:32:54 PM (1 second) Error at 08:32:55 PM (Total - 2 seconds) ERROR: error code -11 Setting up coverage_loss Top shape: (1) with loss weight 1 Memory required for data: 2451719688 Creating layer cluster "**
> 
> My Ubuntu 16.04.3 LTS (xenial)
> Python: 2.7.12
> OpenCV: 3.4.0-dev
> Protobuf:3.5.1
> Cuda Tool Kit: v9.1
> CuDNN: v7.1
> Caffe: caffe-0.15(nvcaffe)
> My NVIDIA card: GeForce GTX 1070 (8 GB)
> 
> I am building an object detection system(vehicle), and I'm using drone images(1280X720, 1920X1080, 4096X2160).
> When i create dataset, I set Pad image size as 4096(width) and 2160(height).
> Also I set resize image size as 1280(width) and 720(height).
> 
> I will attach my Makefile.config, caffe log and some other files.
> Currently I'm trying to install digits object recognition system with my models, but I'm failed every time over about 20 times with various errors.
> I would like to get working as soon as possible.
> Thank you
> Ed
> 
> ![screen shot 2018-01-15 at 10 56 05 am](https://user-images.githubusercontent.com/31979503/34958034-f4bb735a-f9e4-11e7-8940-a72c5c6fb4d6.png)
> ![screen shot 2018-01-15 at 11 10 17 am](https://user-images.githubusercontent.com/31979503/34958036-f4f0edb4-f9e4-11e7-9976-66674b1e25d5.png)

I have the same question. Can you give me some way to fix the problem.
Thanks you.
