### ISSUE TITLE
DIGITS and NVCaffe on a remote server ...

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1377]
Hello,

Does anybody know a place to hourly rent a GPU equipped server to be able to run DIGITS and train models?!

if Yes, how?

**Comment by gheinrich** [comment]
Hello, thanks for asking, there are options I am sure you can find them by Googling. We don't give commercial advice here so I'll close this issue.

**Comment by VanitarNordic** [comment]
Alright :-)

**Comment by dcmartin** [comment]
Ping me; there are a number of options; I am using SoftLayer bare-metal w/ 4xK80 hourly

**Comment by VanitarNordic** [comment]
I sent you an email.
