### ISSUE TITLE
detectnet_augmentation_param defenition

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1378]
Hello, The DetectNet augmentation part consists of few parameters:

```
detectnet_augmentation_param {
    crop_prob: 1.0
    shift_x: 32
    shift_y: 32
    scale_prob: 0.4
    scale_min: 0.8
    scale_max: 1.2
    flip_prob: 0.5
    rotation_prob: 0.0
    max_rotate_degree: 5.0
    hue_rotation_prob: 0.8
    hue_rotation: 30.0
    desaturation_prob: 0.8
    desaturation_max: 0.8
  }
```

What the `_prob` means in the parameters such as  `rotation_prob`? 

Probability of rotation? How it should be calculated?

**Comment by gheinrich** [comment]
Yes, `rotation_prob` is the probability of carrying out the rotation. This isn't calculated. A value of `0.0` there disables the corresponding augmentation. `0.8` would mean that about 80% of samples will be randomly rotated.
