### ISSUE TITLE
No sign of improvement after 22 epoches (DetectNet)

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1379]
Hello,

I am sure that I've done everything correctly but as you see in the picture, there is no sign of improvement after 22 epoches, why?!

![screenshot from 2017-01-07 12 13 01](https://cloud.githubusercontent.com/assets/18719591/21744856/97d522c0-d533-11e6-9c41-a5ffe8f3c1b2.png)

**Comment by aprentis** [comment]
Usually they say that more data is amost always better. 
I think your dataset is too small.

**Comment by VanitarNordic** [comment]
I think so.

**Comment by aprentis** [comment]
what kind of network do you use? 
It`s very interesting, because you have non standart image dimensions.

**Comment by VanitarNordic** [comment]
it is detectnet. I don't know what do you mean by non standard image dimensions. We can modify network image dimensions, not bounded to use the default one. if you have looked at feature shape, they are not image dimensions in the dataset.
