### ISSUE TITLE
Multi-GPU in Torch

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#138]
In Caffe, all the multi-GPU work has to be done on their side. You just pass `--gpus 0,1` as a command line argument to Caffe, and you're running on 2 GPUs like magic.

For Torch, this will require writing some non-trivial lua code for communication between the GPUs (e.g. https://github.com/torch/cutorch/issues/42#issue-43657470).

**Comment by sbodenstein** [comment]
How about using fbcunn? (https://github.com/facebook/fbcunn)
