### ISSUE TITLE
model request

### ISSUE THREAD

**Issue by ShervinAr** [NVIDIA/DIGITS#1389]
Hi all,
Can anyone who has trained a digits model for multi-class car&pedestrian detection provide the trained model?
I have already trained a single-class model for detection of cars in the kitti dataset but having difficulty training the multi-class model defined by detectnet_network-2classes.prototxt to detect cars&pedestrians jointly.

many thanks,

**Comment by lukeyeager** [comment]
We hope to post a DetectNet+KITTI model on the model store eventually (see https://github.com/NVIDIA/DIGITS/issues/1214). The licensing is tricky for KITTI - I don't have an ETA for you.
