### ISSUE TITLE
Train for Object Detection on KITTI stops

### ISSUE THREAD

**Issue by Ran-Ba** [NVIDIA/DIGITS#1393]
Hi,
Following the DIGITS Object Detection Tutorial (https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection), I'm attempting to train using the KITTI dataset.
My Digits is installed on a server with 2 Titan X 12G GPUs. I succeeded to run the MNIST classification example successfully, but not the object detection model. I created the KITTI dataset, then configured the network as described in the tutorial.
The train run seems to be starting well where GPUs utilization and memory raising (also the temperature). But after 30 sec the GPU utilization goes to zero and stays there with no progress in the training (it stays on 0% for hours). I tried changing the batch size, to use only one or both GPUs but it didn't help. No error message is given. Note that the MNIST classification training went perfectly well.

I have this in the end of the log file:
```
I0115 10:43:21.427091  6868 parallel.cpp:334] Starting Optimization
I0115 10:43:21.427496  6868 solver.cpp:304] Solving
I0115 10:43:21.427542  6868 solver.cpp:305] Learning Rate Policy: step
I0115 10:43:21.435242  6868 solver.cpp:362] Iteration 0, Testing net (#0)
I0115 10:43:21.435286  6868 net.cpp:723] Ignoring source layer train_data
I0115 10:43:21.435292  6868 net.cpp:723] Ignoring source layer train_label
I0115 10:43:21.435297  6868 net.cpp:723] Ignoring source layer train_transform
I0115 10:43:29.674814  6868 blocking_queue.cpp:50] Data layer prefetch queue empty
I0115 10:44:19.546067  6868 solver.cpp:429]     Test net output #0: loss_bbox = 18.1978 (* 2 = 36.3955 loss)
I0115 10:44:19.546175  6868 solver.cpp:429]     Test net output #1: loss_coverage = 237.471 (* 1 = 237.471 loss)
I0115 10:44:19.546180  6868 solver.cpp:429]     Test net output #2: mAP = 0
I0115 10:44:19.546185  6868 solver.cpp:429]     Test net output #3: precision = 0
I0115 10:44:19.546190  6868 solver.cpp:429]     Test net output #4: recall = 0
I0115 10:44:39.597331  6868 solver.cpp:242] Iteration 0 (0 iter/s, 78.1698s/398 iter), loss = 306.682
I0115 10:44:39.597388  6868 solver.cpp:261]     Train net output #0: loss_bbox = 7.39306 (* 2 = 14.7861 loss)
I0115 10:44:39.597419  6868 solver.cpp:261]     Train net output #1: loss_coverage = 243.089 (* 1 = 243.089 loss)
I0115 10:44:39.597443  6868 sgd_solver.cpp:106] Iteration 0, lr = 0.0001
```

I think the problem maybe related to lmdb file. I have this in the prototxt (copied from the tutorial link):
```
# Data/Input layers
name: "DetectNet"
layer {
  name: "train_data"
  type: "Data"
  top: "data"
  data_param {
    backend: LMDB
    source: "examples/kitti/kitti_train_images.lmdb"
    batch_size: 10
  }
  include: { phase: TRAIN }
}
```

I don't have such lmdb file. Should I download it or create it? Is this part of the digits/caffe installation?

Please advice.

Thanks.

**Comment by Ran-Ba** [comment]
Update: after removing the pre-trained model from the tutorial, it works. Why it doesn't work with the pre-trained model?
Also, it is very slow: estimated time is 11 days (0.02 iterations per second) for KITTI data set (about 6000 images), with batch size 10. (I'm using one GPU, memory usage is 11GB).

**Comment by lukeyeager** [comment]
Getting stuck sounds like a Caffe bug. There have been a lot of bugfixes in the `caffe-0.15` branch (https://github.com/NVIDIA/caffe/compare/v0.15.9...caffe-0.15) - can you update to the latest on that branch and try again?

**Comment by Ran-Ba** [comment]
Updated, and now it works. Thanks.
