### ISSUE TITLE
Questions about visualizations and incorrect predictions

### ISSUE THREAD

**Issue by EddisNorris** [NVIDIA/DIGITS#1396]
Hello,
I am using Digits 4 with Cuda 8.0 Caffe version 0.15.13 with video card Titan X Pascal.
I am facing a proble: after training and using "Test a single image" I am getting changed picture that is quite not similar to original one and always getting incorrect answer.
Has any one faced such problem.. or there are some issues with Digits 4 and Titan X Pascal. These cards are quite new and need to wait for Digits 5??

![screenshot from 2017-01-17 00 42 49](https://cloud.githubusercontent.com/assets/25161856/22001553/9f5ab3b2-dc4e-11e6-87ce-10166d41022e.png)

Also another problem is that I am often getting accuracy near 100% and loss validation less than 0.2. When testing single image or many images (even those that used for training) I am getting incorrect result (output stuck at first class) no matter how many images I use also no matter number of class and also no matter type of Network (AlexNet, GoogleNet or my own custom small size net for small ammount of Images 100-200 in total). 
![screenshot from 2017-01-17 00 52 29](https://cloud.githubusercontent.com/assets/25161856/22001822/22a20a62-dc50-11e6-8c3c-4a8d383406c3.png)

**Comment by lukeyeager** [comment]
1. The displayed "data" visualization is after mean subtraction. This is the pre-processed data (you can see in the statistics that the values range from [-10,102] instead of the standard [0,255] range for 8-bit images.

2. I don't see any reason to think that is a DIGITS bug. Using a network like AlexNet - which was designed to fit on 1.3 million images - to distinguish between only 200 images is likely to massively overfit your data. My first guess would be that you need more data.

**Comment by gheinrich** [comment]
Is your dataset well balanced between your two classes? How many images of each class do you have?

**Comment by EddisNorris** [comment]
Hello,

Thank you for response..
At the moment I have two classes 2397 and 1957 images. Also I am using modified Alex net with small number of neurons. 
[network.tar.gz](https://github.com/NVIDIA/DIGITS/files/717651/network.tar.gz)

Change of network size or data set size does not help I am always getting near 100% accuracy over 1 epoch or some time it starts form 100 % like over fitting (with incorrect test results):
![overfit](https://cloud.githubusercontent.com/assets/25161856/22123405/26280bf0-de94-11e6-9803-9348be00ca74.jpg)


Any way I saw some strange behaviour of dataset, this may be a reason of failure:

In "Create DB (train)" added two classes with 2397 and 1957 images. Externally I can see that in DB train is those numbers of images. But when I check Images in that database using "Explore the db" button I can see that one of class (which has less images) has a lot of images in database.. 

See pictures: "def" catgegory has 19 tabs and they are full of images.. but category "geri" has 23 tabs but only first one "0" has images second one "1" and others are empty.
![database](https://cloud.githubusercontent.com/assets/25161856/22123056/db340500-de92-11e6-984c-38792999c9f8.jpg)
![def](https://cloud.githubusercontent.com/assets/25161856/22123064/e06c8fd8-de92-11e6-8b15-f3c4cf6157e6.jpg)
![geri](https://cloud.githubusercontent.com/assets/25161856/22123066/e37a0fac-de92-11e6-8af6-0fd66bc128bd.jpg)

Also there is strange behaviour "Clasify Many" by some reason it almost always ignores one of class .. it test images form "def" Folder but takes only 5 or 6 images from "geri" Folder. I tested with those images that was used for training:
![test](https://cloud.githubusercontent.com/assets/25161856/22123656/1bd5a094-de95-11e6-99d6-c9d5c43b1a84.jpg)

**Comment by EddisNorris** [comment]
I figured out.. the problem was not even permission on all images. Sad that Digits does not show problem to access images.
Just need to set permission Others: "Read and Write" to all folders containing training images.
