### ISSUE TITLE
DIGITS Fine Tune

### ISSUE THREAD

**Issue by ToruHironaka** [NVIDIA/DIGITS#140]
I always got the error message below when I fine tune on DIGITS but, my fine tune completed without any errors. Is this DIGITS' web service error? 
```
2015-06-09 18:31:07 [20150609-183100-d196] [ERROR] Train Caffe Model: Attempting to upgrade input file specified using deprecated transformation parameters: /home/username/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
2015-06-09 18:31:07 [20150609-183100-d196] [ERROR] Train Caffe Model: Note that future Caffe releases will only support transform_param messages for transformation fields.
2015-06-09 18:31:07 [20150609-183100-d196] [ERROR] Train Caffe Model: Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/username/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
```

**Comment by lukeyeager** [comment]
It looks like you're using a .caffemodel from an older version of caffe. Where did you get the model?

**Comment by ToruHironaka** [comment]
I got the .caffemodel from the script "./scripts/download_model_binary.py models/bvlc_reference_caffenet" I tried the model from caffe-master from Github and NVIDIA (0.10.0). 
There was exactly the same message when I fine tune on my local PC. I think I can ignore this error. Do you agree with me?

Message on my local PC while fine tuning. 
E0609 19:40:10.447484  1305 upgrade_proto.cpp:609] Attempting to upgrade input file specified using deprecated transformation parameters: models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
I0609 19:40:10.447592  1305 upgrade_proto.cpp:612] Successfully upgraded file specified using deprecated data transformation parameters.
E0609 19:40:10.447613  1305 upgrade_proto.cpp:614] Note that future Caffe releases will only support transform_param messages for transformation fields.
E0609 19:40:10.447636  1305 upgrade_proto.cpp:618] Attempting to upgrade input file specified using deprecated V1LayerParameter: models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel

**Comment by lukeyeager** [comment]
Oh, sorry I didn't read your question carefully the first time. You're saying that an error is displayed even though nothing actually goes wrong. I'm seeing the same on my machine.

The problem is that caffe is mis-classifying their log messages. See the first letter in those log lines above? **E**0609 means that line is an **error**. DIGITS "helpfully" passes along those errors to the user. Those should really only be warnings, and then DIGITS wouldn't make a fuss. I'll submit a request for caffe to change the message types.

Thanks for pointing this out!

**Comment by ToruHironaka** [comment]
Thanks for your reply and confirmation, I thought it too. I ignored it while I was running caffe on my local machine but I noticed it on my server machine. This case is solved so I closed the case.
