### ISSUE TITLE
CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE

### ISSUE THREAD

**Issue by zhaohj1995** [NVIDIA/DIGITS#1400]
Hi all,

I got  the following error when running runtest with ubuntu 14.04, GTX1080 and cuda 8.
`[----------] 18 tests from RandomNumberGeneratorTest/0, where TypeParam = float
[ RUN      ] RandomNumberGeneratorTest/0.TestRngGaussian2
[       OK ] RandomNumberGeneratorTest/0.TestRngGaussian2 (0 ms)
[ RUN      ] RandomNumberGeneratorTest/0.TestRngUniform2
[       OK ] RandomNumberGeneratorTest/0.TestRngUniform2 (1 ms)
[ RUN      ] RandomNumberGeneratorTest/0.TestRngBernoulli2
[       OK ] RandomNumberGeneratorTest/0.TestRngBernoulli2 (1 ms)
[ RUN      ] RandomNumberGeneratorTest/0.TestRngGaussianGPU
F0118 23:29:34.400086 13613 math_functions.cu:408] Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE
*** Check failure stack trace: ***
    @     0x2af73c82adaa  (unknown)
    @     0x2af73c82ace4  (unknown)
    @     0x2af73c82a6e6  (unknown)
    @     0x2af73c82d687  (unknown)
    @     0x2af73e970611  caffe::caffe_gpu_rng_gaussian<>()
    @           0x750673  caffe::RandomNumberGeneratorTest_TestRngGaussianGPU_Test<>::TestBody()
    @           0x93646a  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x92bcb9  testing::Test::Run()
    @           0x92bd97  testing::TestInfo::Run()
    @           0x92bed5  testing::TestCase::Run()
    @           0x92c14d  testing::internal::UnitTestImpl::RunAllTests()
    @           0x935fea  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x92b511  testing::UnitTest::Run()
    @           0x472007  main
    @     0x2af73f82bf45  (unknown)
    @           0x479c79  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)`
What should I do ? I have update  to cuda8, but can't solve the problem.

**Comment by lukeyeager** [comment]
Another case of https://github.com/NVIDIA/caffe/issues/270?

**Comment by zhaohj1995** [comment]
@lukeyeager 
I have solved this problem.When I type`ldd ./build/tools/caffe | grep cuda`, I get
`libcudart.so.7.0 => /usr/lib/libcudart.so.7.0 (0x00007f156953f000)
libcudnn.so.5 => /usr/local/cuda-8.0/lib64/libcudnn.so.5 (0x00007f155bd05000)`
Some `*.so` of cuda7 not be removed. After I delete them, everything is fine.
Thanks!

**Comment by weikaichenusc** [comment]
@lawpda what do you mean, some *.so of cuda7 not be removed? did you delete libcudart.so.7.0? I have tried deleted liibcudart.so.7.0, then runtest will report error of cannot finding it. What did you do to resolve the issue? thanks a lot!

**Comment by lawpda** [comment]
My problem is cuda7 didn't be completely removed before I install cuda8.  So I remove some `*.so` of older version  cuda.

**Comment by weikaichenusc** [comment]
@lawpda okay, thanks!!

**Comment by heng2j** [comment]
hi @weikaichenusc,
I have the same problem as yours. How did you fix the problem? Did you purge and reinstall CUDA?

**Comment by sfarkya** [comment]
I have reinstalled cuda 8.0, I am still getting the same error. Can anyone please tell me how can I make sure that I don't have any piece of old cudas left uninstalled? @lawpdas can you help me with this?

**Comment by lawpdas** [comment]
@sfarkya You can try `ldd ./build/tools/caffe | grep cuda` in caffe's root directory.

In my computer, cuda8/cudnn5:
```
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f2c304f2000)
	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00007f2c2c1a9000)
	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00007f2c28233000)
	libcudnn.so.5 => /usr/local/cuda/lib64/libcudnn.so.5 (0x00007f2c1d96e000)
```

**Comment by zhong-xin** [comment]
@lawpdas after run `ldd ./build/tools/caffe | grep cuda` ,I get_ the following message:
`libcudart.so.9.0 => /usr/local/cuda-9.0/lib64/libcudart.so.9.0 (0x00007f0959c3f000)
libcudnn.so.7 => /usr/local/cuda-9.0/lib64/libcudnn.so.7 (0x00007f093fd84000)
`
In my computer, cuda9/cudnn7:
then,when run `sudo make runtest` in caffe's root directory,I have the same problems.
Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0)  CURAND_STATUS_LAUNCH_FAILURE

**Comment by IvyYZ** [comment]
I had solved this problem.
Uninstall nvidia-cuda-toolkit and it's dependencies
sudo apt-get remove --auto-remove nvidia-cuda-toolkit
Then, I make clean -->make all -->make test-->make runtest

**Comment by IvyYZ** [comment]
I had solved this problem.
Uninstall nvidia-cuda-toolkit and it's dependencies
sudo apt-get remove --auto-remove nvidia-cuda-toolkit
Then, I make clean -->make all -->make test-->make runtest

**Comment by tongtyr** [comment]
> @lawpdas after run `ldd ./build/tools/caffe | grep cuda` ,I get_ the following message:
> `libcudart.so.9.0 => /usr/local/cuda-9.0/lib64/libcudart.so.9.0 (0x00007f0959c3f000) libcudnn.so.7 => /usr/local/cuda-9.0/lib64/libcudnn.so.7 (0x00007f093fd84000) `
> In my computer, cuda9/cudnn7:
> then,when run `sudo make runtest` in caffe's root directory,I have the same problems.
> Check failed: status == CURAND_STATUS_SUCCESS (201 vs. 0) CURAND_STATUS_LAUNCH_FAILURE

have solved it? I met the same problem

**Comment by zhleternity** [comment]
> I had solved this problem.
> Uninstall nvidia-cuda-toolkit and it's dependencies
> sudo apt-get remove --auto-remove nvidia-cuda-toolkit
> Then, I make clean -->make all -->make test-->make runtest

Tnanks very much，it works for me.

**Comment by xiaozhouqi** [comment]
I had solved this problem.
Uninstall nvidia-cuda-toolkit and it's dependencies
sudo apt-get remove --auto-remove nvidia-cuda-toolkit
Then, I make clean -->make all -->make test-->make runtest

Thanks very much, it works for me too.
