### ISSUE TITLE
Python Inference on DetectNet

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#1404]
There have been lots of questions about this, so I decided to write a bit of code for interacting with DetectNet using Python. I just took the [standard classification example](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/examples/classification/example.py) and changed a few lines.

https://gist.github.com/lukeyeager/777087991419d98700054cade2f755e6

Usage and example output:
```
$ ./example.py snapshot_iter_19140.caffemodel deploy.prototxt 000023.png 
WARNING: No labels file provided. Results will be difficult to interpret.
Processed 1/1 images in 0.112845 seconds ...
==> Image #0
Detected object at [(523, 170), (634, 236)] with "confidence" 2.302734
Detected object at [(680, 167), (774, 236)] with "confidence" 2.197266
Detected object at [(737, 177), (879, 284)] with "confidence" 2.484375
Script took 1.154983 seconds.
```

**Comment by VanitarNordic** [comment]
Hello,

I get this error while I try to run your code:

```
Processed 1/1 images in 0.040763 seconds ...
==> Image #0
Traceback (most recent call last):
  File "detect.py", line 251, in <module>
    args['mean'], args['labels'], args['batch_size'], not args['nogpu'])
  File "detect.py", line 210, in classify
    for left, top, right, bottom, confidence in image_results:
ValueError: too many values to unpack
```

**Comment by yankailab** [comment]
@VanitarNordic 
You may have to add/recover the cluster layer into deploy.prototxt

`layer {
  name: "cluster"
  type: "Python"
  bottom: "coverage"
  bottom: "bboxes"
  top: "bbox-list"
  python_param {
    module: "caffe.layers.detectnet.clustering"
    layer: "ClusterDetections"
    param_str: "1920, 1088, 16, 0.6, 3, 0.02, 22, 1"
  }
}`

**Comment by user7077** [comment]
Hi,
I have trained detectnet with two classes and the inference in digits works fine. Now I wanted to do this in python using your script but I only get the bounding boxes for one class. Can this script be modified to yield the bounding boxes for both classes? 
I also do not understand what exactely should be included in the label file or what it's structure should be.

**Comment by alhajjabbass** [comment]
Hello, how is the confidence calculated ? Is it a confidence with maximum 3 or how exactly is it given ?
