### ISSUE TITLE
jetson-inference detectnet-camera can not using training model?

### ISSUE THREAD

**Issue by BrainyBeeLy** [NVIDIA/DIGITS#1409]
Digits training model success. https://github.com/NVIDIA/DIGITS
using : cuda8.0 , caffe, digits5;
GoogleNet model
https://github.com/dusty-nv/jetson-inference/tree/master/detectnet-camera
jetson-inference detectnet-camera can not using this model, error follow:

[GIE] attempting to open cache file vehicle/snapshot_iter_21120.caffemodel.tensorcache
[GIE] cache file not found, profiling network model
[GIE] platform has FP16 support.
[GIE] loading vehicle/deploy.prototxt vehicle/snapshot_iter_21120.caffemodel
**[GIE] failed to retrieve tensor for output 'coverage'
[GIE] failed to retrieve tensor for output 'bboxes'**
[GIE] configuring CUDA engine
[GIE] building CUDA engine
??

**Comment by lukeyeager** [comment]
> Closing as duplicate of dusty-nv/jetson-inference#31
 https://github.com/NVIDIA/DIGITS/issues/1407#issuecomment-274259578

**Comment by adithya-p** [comment]
Did you find a way to fix this? This issue has been closed even though there are no answers. No answers, but duplicate questions and the comment section ends in a loop in which one points to the other.
