### ISSUE TITLE
caffe versioning-branches

### ISSUE THREAD

**Issue by Brootux** [NVIDIA/DIGITS#141]
I would post this issue in NVIDIA/caffe but there is no way to add an issue in this repository.

Under https://github.com/NVIDIA/DIGITS/blob/master/docs/InstallCaffe.md it says i should checkout branch ```v0.11.0``` but the repository doesnt have this branch. The branch name was changed once to ```caffe-0.12``` but this branch was deleted now too.

Could you please activate issuing for NVIDIA/caffe, create a branch/tag for the current state of code and/or update the installation documentation inside NVIDA/DIGITS?

**Comment by lukeyeager** [comment]
Have you tried it? This command *does* work:

    git clone --branch v0.11.0 https://github.com/NVIDIA/caffe.git

It's just confusing that `v0.11.0` is really a **tag**, not a **branch**. Git uses those almost interchangeably. 
https://github.com/NVIDIA/caffe/tree/v0.11.0

> Could you please activate issuing for NVIDIA/caffe

[Just did](https://github.com/NVIDIA/caffe/issues). Github disables them by default when you fork a repository.

> create a branch/tag for the current state of code

Tag is already created. I'm not going to create a `caffe-0.11` branch unless I release a hotfix for version `0.11` called `0.11.1`. 

> update the installation documentation inside NVIDA/DIGITS

Which part of the docs do you think needs to be changed?

**Comment by Brootux** [comment]
Well okay, the command works now. But there was a time after removing the ```v0.11.0``` branch from repository where this command hasn´t worked, ive looked then at the repository and saw a branch ```caffe-0.12```, but since removing this branch, ive thought there is no way to get the latest stable state. Ive also accidentally looked just for Releases and not Tags on the repository-site. But its correctly listed under Tags :)

> Which part of the docs do you think needs to be changed?

Nothing this question is obsolete now.

Thank you very much.
