### ISSUE TITLE
DIGITS ERROR: Cannot use GPU in CPU-only Caffe: check mode.

### ISSUE THREAD

**Issue by mrasyid** [NVIDIA/DIGITS#1419]
Hello,

I have been trying to search what is the reason for this error:
DIGITS ERROR: Cannot use GPU in CPU-only Caffe: check mode.
in the already submitted issues,  but I could not find the solution up to now. I apologize if I missed it if it has already been solved.
Basically I was trying to do a Semantic Segmentation experiment based on this tutorial. https://github.com/NVIDIA/DIGITS/tree/master/examples/semantic-segmentation
however, I ended up having an error like this:
![caffe-error-digits](https://cloud.githubusercontent.com/assets/1209717/22357377/e4966154-e47a-11e6-94e0-5582d5c95833.png)
I have checked my caffe installation, and I believe I have built it with GPU mode, or "CPU_ONLY : OFF" in the cmake. I also have checked the Makefile.config (if it is necessary), and the "CPU_ONLY:=1" line was also commented, meaning it is in GPU mode.
![caffe-cmake-output](https://cloud.githubusercontent.com/assets/1209717/22357428/5c9d4578-e47b-11e6-9be0-5d476220bdea.png)
![caffe-build-success](https://cloud.githubusercontent.com/assets/1209717/22357431/605c9718-e47b-11e6-95c9-6bd06e62199a.png)

Since I still do not know what is the cause of this problem, I really appreciate any help and solution for this issue.
Thank you.

**Comment by lukeyeager** [comment]
Did you tell DIGITS to use this Caffe build?
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/Configuration.md

**Comment by mrasyid** [comment]
If this what you meant:
![echo_caffe_root](https://cloud.githubusercontent.com/assets/1209717/22357924/a1ca56b0-e47e-11e6-84b4-5de16f953fca.png)
I believe I did.
But now I realize that in my cmake configuration on my previous image, the CUDA dependencies is in NO status. 
How can I fix this?

**Comment by mrasyid** [comment]
Now I am doing cmake by this: cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0 ..
And the CUDA is detected now:
![cmake-caffe-cuda-found](https://cloud.githubusercontent.com/assets/1209717/22358336/9fd9a128-e481-11e6-864d-1e74abcc4cfa.png)

Now in the recompiling status.

**Comment by mrasyid** [comment]
All right. Finally the problem solved. Thank you @lukeyeager for the help and quick response :).
![digits-training-ok](https://cloud.githubusercontent.com/assets/1209717/22358393/297909c8-e482-11e6-9453-e1411e2dd807.png)
