### ISSUE TITLE
Cannot create KITTI dataset on DIGITIS webapp while following object-detection tutorial

### ISSUE THREAD

**Issue by Daniel-Orlandi** [NVIDIA/DIGITS#1420]
Hi all,
I am fairly new to caffe and DIGITS; while following the object detection tutorial (https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection), I could not create the KITTI object detection dataset in the webapp.

here is the log file with the error: [Digits.txt](https://github.com/NVIDIA/DIGITS/files/734336/Digits.txt)

I looked over the google group and github, and coudn't find a solution.
Thanks in advance.
Daniel

**Comment by gheinrich** [comment]
Hello, did you check that files like `/mnt/8210086D10086A8D/IC/Testes_DIGITS/Tutorial_Object_Detection/Dataset/kitti-data/train/labels/000000.txt` are present and readable by the account running the DIGITS daemon (user `www-data` if you installed DIGITS from deb packages)? This file must be readable, and all the folders leading to it, must be readable and executable.

**Comment by Daniel-Orlandi** [comment]
Hello @gheinrich,
Yes, the files are there but somehow even after changing folder access permissions DIGITS can,t access the files. 
After changing the data from this folder, which is in another hard drive I was able to create the dataset.
It seems to be an Issue with my ubuntu configuration, and not with DIGITS.

Thansks for your response.
