### ISSUE TITLE
training Berkeley fc8s for segmenation with digits

### ISSUE THREAD

**Issue by RSly** [NVIDIA/DIGITS#1428]
Hi,

I am trying to train berkeley fc8-s for segmentation on a 2class problem.
Here is my proto.txt
[original.prototxt.txt](https://github.com/NVIDIA/DIGITS/files/745519/original.prototxt.txt)

Up to fc7, I am using the pre-trained model from 
http://dl.caffe.berkeleyvision.org/fcn8s-heavy-pascal.caffemodel
after fc-7 and from score_fr, layer names and num_output is changed to be learned from scratch

I get an almost flat loss, anyone has tried this before?
Why this network doesnt learn, whereas the alexnet learns much better

**Comment by gheinrich** [comment]
That could be due to improper initialization of some conv/deconv layers. Go through this thread and see if you find a solution:
https://groups.google.com/d/msg/digits-users/uHwQ1VV3-Wg/yTyk_Y8FFgAJ

**Comment by RSly** [comment]
thanks, great advice!
