### ISSUE TITLE
Loaded 0 jobs

### ISSUE THREAD

**Issue by sagarax009** [NVIDIA/DIGITS#1430]
Hi 

I followed all steps given on installation page
https://github.com/NVIDIA/DIGITS/blob/756b3bc82d3d2708770e623e395beefa3e97c74f/docs/BuildDigits.md
I am using ubuntu 16.04 but I am getting above mentioned error please guide me
thanks

**Comment by lukeyeager** [comment]
That's not an error. It's telling you how many jobs have been loaded from disk. Create a dataset, restart DIGITS, and you'll see "Loaded 1 job".
