### ISSUE TITLE
Installation problem, dpkg returned error (1)

### ISSUE THREAD

**Issue by xkuttu** [NVIDIA/DIGITS#1436]
Digits installation failed with the following error,

Setting up digits (4.0.0-1) ...
start: Unknown job: nvidia-digits-server
dpkg: error processing package digits (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 digits
E: Sub-process /usr/bin/dpkg returned an error code (1)

Can anyone help me ? What is the problem here

**Comment by lukeyeager** [comment]
What OS are you running?
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

**Comment by xkuttu** [comment]
Same result for that.

I'm using Mint 17.3.
The issue got resolved when i used the "Software Manager" app to remove and reinstall digits, the installation was successful and i was able to run digits. I still don’t know the cause of that error though.

**Comment by lukeyeager** [comment]
Hmm. Maybe mint has a custom dpkg (unlikely) or uses a different init system (slightly more likely)?

Either way, glad you figured it out.
