### ISSUE TITLE
DIGITS 5 annotation format ...

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1437]
Hi,

if we decided to use some different Caffe models rather than GoogLeNet or DetectNet, still we have to use the KITTI format to make a dataset?

**Comment by lukeyeager** [comment]
If you want to create an "Object Detection" dataset in DIGITS, then you will need your labels in the KITTI format, yes. But you can extend DIGITS by writing a plugin for other data/label formats, or you can create your own LMDB's manually outside of DIGITS and upload them to DIGITS as "Other"/"Generic" datasets. Please search around on these GitHub issues and on our user group - others have had the same question.

**Comment by VanitarNordic** [comment]
Alright but if you add this feature in DIGITS 5.1, then it will make it unique. I mean supporting COCO, ImageNet and other formats either rather than KITTI

**Comment by lukeyeager** [comment]
Agreed, that would be nice. See related feature request for Pascal VOC: https://github.com/NVIDIA/DIGITS/issues/879
