### ISSUE TITLE
ERROR: Your deploy network is missing a Softmax layer! 

### ISSUE THREAD

**Issue by busrakb** [NVIDIA/DIGITS#1439]
hi,
i wanna use digits with my dataset so i looked for pretrained Network and i found vgg face recognation. i used it but i took error what i need to do i dont know.Can u help me?

Error is;

Traceback (most recent call last):
  File "digits/scheduler.py", line 508, in run_task
    task.run(resources)
  File "digits/task.py", line 188, in run
    self.before_run()
  File "digits/model/tasks/caffe_train.py", line 215, in before_run
    self.save_files_classification()
  File "digits/model/tasks/caffe_train.py", line 496, in save_files_classification
    assert found_softmax, 'Your deploy network is missing a Softmax layer! Read the documentation for custom networks and/or look at the standard networks for examples.'
AssertionError: Your deploy network is missing a Softmax layer! Read the documentation for custom networks and/or look at the standard networks for examples.

**Comment by lukeyeager** [comment]
Please see https://github.com/NVIDIA/DIGITS/issues/1192.
