### ISSUE TITLE
DIGITS Standard Networks

### ISSUE THREAD

**Issue by ToruHironaka** [NVIDIA/DIGITS#144]
Is it possible for me to add GoogleNet, RCNN, or other model to DIGITS New Image Classification Model?

**Comment by lukeyeager** [comment]
If you can get it to run in DIGITS, feel free to submit a pull request for a new standard network.

> GoogleNet

GoogleNet has been a standard network in DIGITS since https://github.com/NVIDIA/DIGITS/commit/2c305a025994813df6b052dd3c5bbf8ffda01459.

**Comment by ToruHironaka** [comment]
Thanks, I will try to do https://github.com/NVIDIA/DIGITS/commit/2c305a025994813df6b052dd3c5bbf8ffda01459
