### ISSUE TITLE
DetectNet example training results

### ISSUE THREAD

**Issue by YuryAlkevich** [NVIDIA/DIGITS#1442]
Hello,
I've trained the DetectNet according to [this](https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection) guide. A training process was executed on machine with Nvidia GTX 690 with total 4 GB (2 x 2 GB) video ram. So I set batch size to 2 and batch accumulation to 5 to avoid memory overflow. I've got the following result:

Learning history:
![screenshot_from_2017-02-07_10-07-13](https://cloud.githubusercontent.com/assets/19429998/22729274/19cab57e-edf3-11e6-834e-3ffb74941134.png)

Input image:
![000052](https://cloud.githubusercontent.com/assets/19429998/22729151/81102b34-edf2-11e6-9a19-d490c9b1660e.png)

Output:
![screenshot_from_2017-02-07_10-05-53](https://cloud.githubusercontent.com/assets/19429998/22729196/bf071c5e-edf2-11e6-82ee-8c84105c55e0.png)

That was a photo from test data set. And one can notice that there is "hot" areas from "coverage" layer but eventually the result is zero bounding boxes. A this happens with each image from data set. 
Why does this happen? Is it because of specific parameters of training process? I've tested LeNet example and it seems work well. 

Also I have a problem with failing caffe tests after build, which is similar to [this](https://github.com/NVIDIA/caffe/issues/263) problem:

[  FAILED  ] 3 tests, listed below:
[  FAILED  ] DetectNetTransformationLayerTest/1.TestAllAugmentation, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] DetectNetTransformationLayerTest/1.TestDesaturation, where TypeParam = caffe::CPUDevice<double>
[  FAILED  ] DetectNetTransformationLayerTest/1.TestHueRotation, where TypeParam = caffe::CPUDevice<double>

May be this issue causes problem in inference process?

**Comment by lukeyeager** [comment]
It sounds like you're doing everything right - sorry you're having trouble getting the model to converge. You're not along - lots of people have problems with the object detection example:
https://github.com/NVIDIA/DIGITS/labels/object-detection

> there is "hot" areas from "coverage" layer but eventually the result is zero bounding boxes. A this happens with each image from data set.
Why does this happen?

You can tweak the clustering parameters to show more bounding boxes. Here's what each parameter means:
https://github.com/NVIDIA/caffe/blob/v0.15.14/python/caffe/layers/detectnet/clustering.py#L108-L115

> Also I have a problem with failing caffe tests after build, which is similar to this problem:

The only build configuration of Caffe that we support is with the standard OpenCV packages on either Ubuntu 14.04 or 16.04. 
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildCaffe.md
