### ISSUE TITLE
CPU Utilization 100.9% when training data

### ISSUE THREAD

**Issue by mjohn123** [NVIDIA/DIGITS#1443]
Hello all, I am using newest Caffe and DIGITS versions. I trained the FCN-8s on medical imaging which follows the medical imaging example. However, I figured out that my CPU utilization always >100%. Hence, my PC looks very slow, even the GPU memory does not full utilization. How could I setting to use all GPU memory, and reduce the CPU utilization? Thanks 
```
Hardware
TITAN X (Pascal) (#0)
Memory
6.04 GB / 11.9 GB (50.8%)
GPU Utilization
99%
Temperature
77 °C
Process #4561
CPU Utilization
100.9%
Memory
1.18 GB (7.6%)
```

**Comment by ontheway16** [comment]
@mjohn123 Hello, How many CPU cores you have? Same thing happens here too, I dont think its an issue. During training, one of the cpu cores always stays at 100%, although individual peaking core changes time to time, check system monitor, you can see it. I have 4 cores, and my cpu utilization is always around 110%, means one is fully utilized, others are mostly not in use.

**Comment by mjohn123** [comment]
Ok. I see. I will close the issue
