### ISSUE TITLE
How to achieve similar result (85% Dice) in FCN-8s for medical segmentation example?

### ISSUE THREAD

**Issue by John1231983** [NVIDIA/DIGITS#1444]
Hello all, I am following the medical imaging example at [medical_example](https://github.com/NVIDIA/DIGITS/tree/master/examples/medical-imaging) I was successful to obtain 60% accuracy using `FCN-Alexnet-Sunnybrooke_with_dice-pretrained`

Now, I am working in FCN-8s with ` fcn16s-heavy-pascal.caffemodel` pretrained-weight as  [fcn-8s](https://github.com/shelhamer/fcn.berkeleyvision.org) As the expected result, the Dice metric should exceed 0.85. However, I only can get 78% accuracy.  This is my modifed FCN-8s [prototxt](https://gist.github.com/John1231983/3f8ed7aa2fae8d48ea6549c0dc85809b)

Am I wrong any step? Thank all

![screenshot from 2017-02-08 20 44 13](https://cloud.githubusercontent.com/assets/24875971/22736171/52f8e33c-ee40-11e6-8a9f-d27122a02f5d.png)

**Comment by gheinrich** [comment]
When I used FCN-8s for this task I kept the original PASCAL VOC model (that produces predictions for 21 classes) and merely added an extra conv layer with two output feature maps at the output. You might want to try doing this.

**Comment by John1231983** [comment]
@gheinrich:thank you for your suggestion. could you please share your modified prototxt file?  it will save my time

**Comment by gheinrich** [comment]
I just added these lines:
```
layer {
  name: "score_2classes"
  type: "Convolution"
  bottom: "score"
  top: "score_2classes"
  convolution_param {
    num_output: 2
    pad: 0
    kernel_size: 1
  }
}
```
And updated `loss`, `accuracy` and the Dice Python layer to use `score_2classes` as `bottom`.

**Comment by mjohn123** [comment]
Good idea with a simple modification. However, my Dice value becomes zero values.

```
#Add one more score_2classes layer
layer {
  name: "score_2classes"
  type: "Convolution"
  bottom: "score"
  top: "score_2classes"
  convolution_param {
    num_output: 2
    pad: 0
    kernel_size: 1
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "score_2classes"
  bottom: "label"
  top: "loss"
  loss_param {
    ignore_label: 255
    normalize: true
  }
  exclude {
    stage: "deploy"
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "score_2classes"
  bottom: "label"
  top: "accuracy"
  include { stage: "val" }
  accuracy_param { ignore_label: 255 }
}
# Dice coefficient
layer {
    type: 'Python'
    name: 'dice'
    bottom: 'score_2classes'
    bottom: 'label'
    top: 'dice'
    python_param {
      module: "digits_python_layers"
      layer: "Dice"
    }
    exclude { stage: "deploy" }
}
```
![screenshot from 2017-02-14 16 06 03](https://cloud.githubusercontent.com/assets/10252224/22918921/4fe4609c-f2d0-11e6-8100-97ff935b7fb1.png)

The full prototxt can find at 
https://gist.github.com/mjohn123/fc0b51d60590d528dca351e3652e22be

**Comment by m5061125** [comment]
Hi, Gheinrich, I get the 90% dice accuracy according to your suggest, thanks a lot. But I have another question, as I want to build up my own dicom database, and I want to do multi-organ segmentation. So could pls give some hints? besides I have a question regarding the data-set in this example, because the original dicom pixel is 12 bits, in general. how many bits have been used in this example, I think it is 8 bits. Am I right?

**Comment by andrew443209993** [comment]
Hi, m5061125, could you please share your modified prototxt file?

**Comment by m5061125** [comment]
layer {
  name: "data"
  type: "Data"
  top: "data"
  include {
    phase: TRAIN
  }
  data_param {
    batch_size: 4
    backend: LMDB
  }
}
layer {
  name: "label"
  type: "Data"
  top: "label"
  include {
    phase: TRAIN
  }
  data_param {
    batch_size: 4
    backend: LMDB
  }
}
layer {
  name: "data"
  type: "Data"
  top: "data"
  include {
    phase: TEST
  }
  data_param {
    batch_size: 4
    backend: LMDB
  }
}
layer {
  name: "label"
  type: "Data"
  top: "label"
  include {
    phase: TEST
  }
  data_param {
    batch_size: 4
    backend: LMDB
  }
}
layer {
  name: "conv1_1"
  type: "Convolution"
  bottom: "data"
  top: "conv1_1"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 64
    pad: 100
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu1_1"
  type: "ReLU"
  bottom: "conv1_1"
  top: "conv1_1"
}
layer {
  name: "conv1_2"
  type: "Convolution"
  bottom: "conv1_1"
  top: "conv1_2"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu1_2"
  type: "ReLU"
  bottom: "conv1_2"
  top: "conv1_2"
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1_2"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv2_1"
  type: "Convolution"
  bottom: "pool1"
  top: "conv2_1"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu2_1"
  type: "ReLU"
  bottom: "conv2_1"
  top: "conv2_1"
}
layer {
  name: "conv2_2"
  type: "Convolution"
  bottom: "conv2_1"
  top: "conv2_2"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 128
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu2_2"
  type: "ReLU"
  bottom: "conv2_2"
  top: "conv2_2"
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2_2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv3_1"
  type: "Convolution"
  bottom: "pool2"
  top: "conv3_1"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu3_1"
  type: "ReLU"
  bottom: "conv3_1"
  top: "conv3_1"
}
layer {
  name: "conv3_2"
  type: "Convolution"
  bottom: "conv3_1"
  top: "conv3_2"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu3_2"
  type: "ReLU"
  bottom: "conv3_2"
  top: "conv3_2"
}
layer {
  name: "conv3_3"
  type: "Convolution"
  bottom: "conv3_2"
  top: "conv3_3"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu3_3"
  type: "ReLU"
  bottom: "conv3_3"
  top: "conv3_3"
}
layer {
  name: "pool3"
  type: "Pooling"
  bottom: "conv3_3"
  top: "pool3"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv4_1"
  type: "Convolution"
  bottom: "pool3"
  top: "conv4_1"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu4_1"
  type: "ReLU"
  bottom: "conv4_1"
  top: "conv4_1"
}
layer {
  name: "conv4_2"
  type: "Convolution"
  bottom: "conv4_1"
  top: "conv4_2"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu4_2"
  type: "ReLU"
  bottom: "conv4_2"
  top: "conv4_2"
}
layer {
  name: "conv4_3"
  type: "Convolution"
  bottom: "conv4_2"
  top: "conv4_3"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu4_3"
  type: "ReLU"
  bottom: "conv4_3"
  top: "conv4_3"
}
layer {
  name: "pool4"
  type: "Pooling"
  bottom: "conv4_3"
  top: "pool4"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "conv5_1"
  type: "Convolution"
  bottom: "pool4"
  top: "conv5_1"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu5_1"
  type: "ReLU"
  bottom: "conv5_1"
  top: "conv5_1"
}
layer {
  name: "conv5_2"
  type: "Convolution"
  bottom: "conv5_1"
  top: "conv5_2"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu5_2"
  type: "ReLU"
  bottom: "conv5_2"
  top: "conv5_2"
}
layer {
  name: "conv5_3"
  type: "Convolution"
  bottom: "conv5_2"
  top: "conv5_3"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 512
    pad: 1
    kernel_size: 3
    stride: 1
  }
}
layer {
  name: "relu5_3"
  type: "ReLU"
  bottom: "conv5_3"
  top: "conv5_3"
}
layer {
  name: "pool5"
  type: "Pooling"
  bottom: "conv5_3"
  top: "pool5"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {
  name: "fc6"
  type: "Convolution"
  bottom: "pool5"
  top: "fc6"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 4096
    pad: 0
    kernel_size: 7
    stride: 1
  }
}
layer {
  name: "relu6"
  type: "ReLU"
  bottom: "fc6"
  top: "fc6"
}
layer {
  name: "fc7"
  type: "Convolution"
  bottom: "fc6"
  top: "fc7"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 4096
    pad: 0
    kernel_size: 1
    stride: 1
  }
}
layer {
  name: "relu7"
  type: "ReLU"
  bottom: "fc7"
  top: "fc7"
}
layer {
  name: "score_fr"
  type: "Convolution"
  bottom: "fc7"
  top: "score_fr"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 21
    pad: 0
    kernel_size: 1
  }
}
layer {
  name: "upscore2"
  type: "Deconvolution"
  bottom: "score_fr"
  top: "upscore2"
  param {
    lr_mult: 0.0
  }
  convolution_param {
    num_output: 21
    bias_term: false
    kernel_size: 4
    stride: 2
  }
}
layer {
  name: "score_pool4"
  type: "Convolution"
  bottom: "pool4"
  top: "score_pool4"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 21
    pad: 0
    kernel_size: 1
  }
}
layer {
  name: "score_pool4c"
  type: "Crop"
  bottom: "score_pool4"
  bottom: "upscore2"
  top: "score_pool4c"
  crop_param {
    axis: 2
    offset: 5
  }
}
layer {
  name: "fuse_pool4"
  type: "Eltwise"
  bottom: "upscore2"
  bottom: "score_pool4c"
  top: "fuse_pool4"
  eltwise_param {
    operation: SUM
  }
}
layer {
  name: "upscore_pool4"
  type: "Deconvolution"
  bottom: "fuse_pool4"
  top: "upscore_pool4"
  param {
    lr_mult: 0.0
  }
  convolution_param {
    num_output: 21
    bias_term: false
    kernel_size: 4
    stride: 2
  }
}
layer {
  name: "score_pool3"
  type: "Convolution"
  bottom: "pool3"
  top: "score_pool3"
  param {
    lr_mult: 1.0
    decay_mult: 1.0
  }
  param {
    lr_mult: 2.0
    decay_mult: 0.0
  }
  convolution_param {
    num_output: 21
    pad: 0
    kernel_size: 1
  }
}
layer {
  name: "score_pool3c"
  type: "Crop"
  bottom: "score_pool3"
  bottom: "upscore_pool4"
  top: "score_pool3c"
  crop_param {
    axis: 2
    offset: 9
  }
}
layer {
  name: "fuse_pool3"
  type: "Eltwise"
  bottom: "upscore_pool4"
  bottom: "score_pool3c"
  top: "fuse_pool3"
  eltwise_param {
    operation: SUM
  }
}
layer {
  name: "upscore8"
  type: "Deconvolution"
  bottom: "fuse_pool3"
  top: "upscore8"
  param {
    lr_mult: 0.0
  }
  convolution_param {
    num_output: 21
    bias_term: false
    kernel_size: 16
    stride: 8
  }
}
layer {
  name: "score"
  type: "Crop"
  bottom: "upscore8"
  bottom: "data"
  top: "score"
  crop_param {
    axis: 2
    offset: 31
  }
}
layer {
  name: "score_12classes"
  type: "Convolution"
  bottom: "score"
  top: "score_12classes"
  convolution_param {
    num_output: 2
    pad: 0
    kernel_size: 1
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "score_12classes"
  bottom: "label"
  top: "loss"
  exclude {
    stage: "deploy"
  }
  loss_param {
    ignore_label: 255
    normalize: true
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "score_12classes"
  bottom: "label"
  top: "accuracy"
  include {
    stage: "val"
  }
  accuracy_param {
    ignore_label: 255
  }
}
layer {
  name: "dice"
  type: "Python"
  bottom: "score_12classes"
  bottom: "label"
  top: "dice"
  exclude {
    stage: "deploy"
  }
  python_param {
    module: "digits_python_layers"
    layer: "Dice"
  }
}

**Comment by andrew443209993** [comment]
m5061125, Which caffe model did you use? And I want to train the model for images of random sizes(s.a. 255*255, 650*430 ect.). Could you give me some advice?

**Comment by andrew443209993** [comment]
255x255, 640x430

**Comment by m5061125** [comment]
@andrew443209993 ,one of the advantages of FCN is not sensitive with the size of the input image, so I don't know exactly what is your point.

**Comment by andrew443209993** [comment]
m5061125, ok, Which caffe model did you use?

**Comment by m5061125** [comment]
@andrew443209993 ,I use FCN8 one channel caffemodel.

**Comment by andrew443209993** [comment]
m5061125, this one? fcn8s-heavy-pascal.caffemodel

**Comment by andrew443209993** [comment]
m5061125, or one from these? http://dl.caffe.berkeleyvision.org/

**Comment by m5061125** [comment]
@andrew443209993 ,yes, you should download it first, and reshape the input channel into one using the net.surgery.

**Comment by andrew443209993** [comment]
m5061125, thanks a lot, it works well. About your question, I think dicom pixel is 16 bits. I have the same task. I have own dicom dataset, but I dont know how to prepare dataset to download into Digits(sunnybrook LV segmentation). may we discuss by e-mail?
![example](https://cloud.githubusercontent.com/assets/6755871/24181598/b2bc0fe8-0edd-11e7-8466-a82e4a18fb0b.png)

**Comment by VanitarNordic** [comment]
@m5061125 

Hello. I have downloaded the `fcn8s-heavy-pascal.caffemodel` , but I faced this issue: https://github.com/NVIDIA/DIGITS/issues/1558

Should I do something on this file before I upload it as a pre-trained model? if Yes, how?

**Comment by Hzzone** [comment]
@andrew443209993 Have you solved this problem?

**Comment by ducnghia** [comment]
@m5061125 & @andrew443209993: Could you please share something about your preparation the dicom imageset into the compatible input for DIGITS?

**Comment by Hzzone** [comment]
@ducnghia  When you try to output one dicom image(I used python pydicom), you will find it's a 2D matrix. So taking dicom images as an gray image, you will have three ways to solve this problem. First, transform them into lmdb(digits->dataset->others, you will find it)(2D matrix as gray images when you are not fine tuning). Second,  transform them into jpeg or png(not recommended). Third,  lmdb with 3D matrix as BGR images(fine tuning since alexnet or googlenet is only suitable for color images. Using python Numpy). Google to see details, or see [Bone-Age-Assessment](https://github.com/Hzzone/Bone-Age-Assessment)(no source code)

**Comment by joshua2k** [comment]
Hello all, 

For FCN_Alexnet, I had similar issue above Dice accuracy. I followed all your comments. But the Dice accuracy was only 0.45 as below. It was much lower results of example, 0.6.  I also met similar issue on FCN-8s. Even I copied prototxt from "m5061125", I used it without any modification. It gave 0.75 DICE accuracy, lower than 0.85, results from example (much lower than results from "m5061125", 0.9)  What do i wrong something?
(DIGITS version: 5.1-dev, Caffe version: 0.15.14, Caffe flavor: NVIDIA)

Thank you

Digits Version: 

![image](https://user-images.githubusercontent.com/29867104/27799482-557b9c16-5fe3-11e7-9ce6-e04f58c6d805.png)
![image](https://user-images.githubusercontent.com/29867104/27799637-ff6101c6-5fe3-11e7-9a37-da8a466c42df.png)

The used prototxt was below

layer {
  name: "data"
  type: "Data"
  top: "data"
  include {
    phase: TRAIN
  }
  data_param {
    batch_size: 1
    backend: LMDB
  }
}
layer {
  name: "label"
  type: "Data"
  top: "label"
  include {
    phase: TRAIN
  }
  data_param {
    batch_size: 1
    backend: LMDB
  }
}
layer {
  name: "data"
  type: "Data"
  top: "data"
  include {
    phase: TEST
  }
  data_param {
    batch_size: 1
    backend: LMDB
  }
}
layer {
  name: "label"
  type: "Data"
  top: "label"
  include {
    phase: TEST
  }
  data_param {
    batch_size: 1
    backend: LMDB
  }
}
layer {
  # Use Power layer in deploy phase for input scaling
  name: "shift"
  bottom: "data"
  top: "data_preprocessed"
  type: "Power"
  power_param {
    shift: -116.0
  }
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data_preprocessed"
  top: "conv1"
  convolution_param {
    num_output: 96
    pad: 100
    kernel_size: 11
    group: 1
    stride: 4
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "norm1"
  type: "LRN"
  bottom: "pool1"
  top: "norm1"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "conv2"
  type: "Convolution"
  bottom: "norm1"
  top: "conv2"
  convolution_param {
    num_output: 256
    pad: 2
    kernel_size: 5
    group: 2
    stride: 1
  }
}
layer {
  name: "relu2"
  type: "ReLU"
  bottom: "conv2"
  top: "conv2"
}
layer {
  name: "pool2"
  type: "Pooling"
  bottom: "conv2"
  top: "pool2"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "norm2"
  type: "LRN"
  bottom: "pool2"
  top: "norm2"
  lrn_param {
    local_size: 5
    alpha: 0.0001
    beta: 0.75
  }
}
layer {
  name: "conv3"
  type: "Convolution"
  bottom: "norm2"
  top: "conv3"
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    group: 1
    stride: 1
  }
}
layer {
  name: "relu3"
  type: "ReLU"
  bottom: "conv3"
  top: "conv3"
}
layer {
  name: "conv4"
  type: "Convolution"
  bottom: "conv3"
  top: "conv4"
  convolution_param {
    num_output: 384
    pad: 1
    kernel_size: 3
    group: 2
    stride: 1
  }
}
layer {
  name: "relu4"
  type: "ReLU"
  bottom: "conv4"
  top: "conv4"
}
layer {
  name: "conv5"
  type: "Convolution"
  bottom: "conv4"
  top: "conv5"
  convolution_param {
    num_output: 256
    pad: 1
    kernel_size: 3
    group: 2
    stride: 1
  }
}
layer {
  name: "relu5"
  type: "ReLU"
  bottom: "conv5"
  top: "conv5"
}
layer {
  name: "pool5"
  type: "Pooling"
  bottom: "conv5"
  top: "pool5"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
layer {
  name: "fc6"
  type: "Convolution"
  bottom: "pool5"
  top: "fc6"
  convolution_param {
    num_output: 4096
    pad: 0
    kernel_size: 6
    group: 1
    stride: 1
  }
}
layer {
  name: "relu6"
  type: "ReLU"
  bottom: "fc6"
  top: "fc6"
}
layer {
  name: "drop6"
  type: "Dropout"
  bottom: "fc6"
  top: "fc6"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "fc7"
  type: "Convolution"
  bottom: "fc6"
  top: "fc7"
  convolution_param {
    num_output: 4096
    pad: 0
    kernel_size: 1
    group: 1
    stride: 1
  }
}
layer {
  name: "relu7"
  type: "ReLU"
  bottom: "fc7"
  top: "fc7"
}
layer {
  name: "drop7"
  type: "Dropout"
  bottom: "fc7"
  top: "fc7"
  dropout_param {
    dropout_ratio: 0.5
  }
}
layer {
  name: "score_fr_2classes"
  type: "Convolution"
  bottom: "fc7"
  top: "score_fr_2classes"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 2
    pad: 0
    kernel_size: 1
  }
}
layer {
  name: "upscore_2classes"
  type: "Deconvolution"
  bottom: "score_fr_2classes"
  top: "upscore_2classes"
  param {
    lr_mult: 0
  }
  convolution_param {
    num_output: 2
    group: 2
    bias_term: false
    kernel_size: 63
    stride: 32
    weight_filler: { type: "bilinear" }
  }
}
layer {
  name: "score"
  type: "Crop"
  bottom: "upscore_2classes"
  bottom: "data"
  top: "score"
  crop_param {
    axis: 2
    offset: 18
  }
}
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "score"
  bottom: "label"
  top: "loss"
  loss_param {
    ignore_label: 255
    normalize: true
  }
  exclude {
    stage: "deploy"
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "score"
  bottom: "label"
  top: "accuracy"
  include { stage: "val" }
  accuracy_param { ignore_label: 255 }
}
layer {
    type: 'Python'
    name: 'dice'
    bottom: 'score'
    bottom: 'label'
    top: 'dice'
    python_param {
      module: "digits_python_layers"
      layer: "Dice"
    }
    exclude { stage: "deploy" }
}

**Comment by joshua2k** [comment]
Hello Greg Heinrich,

Regarding of using pretrained FCN-8s model, you suggest to merely added an extra conv layer with two output feature maps at the output. I applied to your tip to FCN-Alexnet as below. But the DICE metric was not trained as below. Is this tip only work for fcn-8s? Thanks         

....
layer {
  name: "score_fr"
  type: "Convolution"
  bottom: "fc7"
  top: "score_fr"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  convolution_param {
    num_output: 21
    pad: 0
    kernel_size: 1
  }
}
layer {
  name: "upscore"
  type: "Deconvolution"
  bottom: "score_fr"
  top: "upscore"
  param {
    lr_mult: 0
  }
  convolution_param {
    num_output: 21
    group: 21
    bias_term: false
    kernel_size: 63
    stride: 32
    weight_filler: { type: "bilinear" }
  }
}
layer {
  name: "score"
  type: "Crop"
  bottom: "upscore"
  bottom: "data"
  top: "score"
  crop_param {
    axis: 2
    offset: 18
  }
}

layer {
  name: "score_2classes"
  type: "Convolution"
  bottom: "score"
  top: "score_2classes"
  convolution_param {
    num_output: 2
    pad: 0
    kernel_size: 1
  }
}

layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "score_2classes"
  bottom: "label"
  top: "loss"
  loss_param {
    ignore_label: 255
    normalize: true
  }
  exclude {
    stage: "deploy"
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "score_2classes"
  bottom: "label"
  top: "accuracy"
  include { stage: "val" }
  accuracy_param { ignore_label: 255 }
}

# Dice coefficient
layer {
    type: 'Python'
    name: 'dice'
    bottom: 'score_2classes'
    bottom: 'label'
    top: 'dice'
    python_param {
      module: "digits_python_layers"
      layer: "Dice"
    }
    exclude { stage: "deploy" }
}

Training curve
![image](https://user-images.githubusercontent.com/29867104/27801501-6a2ce42c-5fec-11e7-893e-6a85ce1a8e67.png)

**Comment by jionie** [comment]
@joshua2k Hi, have you solved you problem? I had met a similiar problem on my own dataset and FCN-model in tensorflow, and I found that if I directly add a conv layer(1X1, input channel 21, output channel new_classes), the accuracy of this model (model0) is not good. Then I added more conv layers after that layer and used model0 as a pretrained model, which could get better performance. Maybe the weights of one conv layer are not enough to change 21 predictions to your output predictions.

fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3 = \
                _score_layer(0, fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits, 21, 1, 'fc_9_1', new_number_of_classes)

                
                fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits = \
                tf.nn.relu(fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits)
                
                fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_1 = \
                _score_layer(0, fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits, 21, 1, 'conv_1', 48)

                fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_1 = \
                tf.nn.relu(fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_1)

                fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_2 = \
                _score_layer(0, fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_1, 48, 3, 'conv_2', 48)

                fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_2 = \
                tf.nn.relu(fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_2)

                fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_3 = \
                _score_layer(0, fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_1, 48, 1, 'conv_3', new_number_of_classes)

                fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3 += \
                fused_last_layer_and_pool4_logits_and_pool_3_upsampled_by_factor_8_logits_3_3

**Comment by raj-parihar** [comment]
Some of the fcn-8s prototext don't have final softmax layer. I do see the softmaxwithloss for train.prototext but deploy.prototext somehow "magically" excludes that. Is there a reason for that?
