### ISSUE TITLE
Detectnet, Manual inference problem; labels_file not set

### ISSUE THREAD

**Issue by ontheway16** [NVIDIA/DIGITS#1445]
Hello,
I have tried the famous curl command to manually accomplish inference, but with both "_one" and "_many" routes, I am receiving to following error;

```
curl localhost:5000/models/images/classification/classify_one.json -XPOST -F job_id=20170204-213137-087f -F image_file=@/media/alp/SAMSUNG/bigdata/testbank/IMG_20160628_0032-8.png
{
  "error": {
    "message": "labels_file not set", 
    "type": "AssertionError"
  }
```
I realize it actually works for a while before throwing the error, especially in "_many" route, cpu peaks to 100%, but "_many" too, eventually ends with the above error. Any ideas? (btw, test picture is not in train-images-labels etc.. type of folder structure, its just a folder containing some images for inference tests, so no labeling etc...

Any opinions?

**Comment by gheinrich** [comment]
Hello, @jmformenti gave you the correct command on https://github.com/NVIDIA/DIGITS/issues/1412#issuecomment-276797099

**Comment by ontheway16** [comment]
@gheinrich The command kindly provided by @jmformenti  was not working, until now. It was complaining about not finding the job directory.

The contribution here in [#1440](https://github.com/NVIDIA/DIGITS/issues/1440#issuecomment-278211506) (thanks to @mjohn123) let me finally understand how to define path variables, including DIGITS_ROOT :)

Finally, inference command is working well, and redirects to a text file, as well.

Thanks a lot for this and I can finally ask for a parsing solution to convert this output to labels.txt format. Python?
Also, is this output a kind of XML formatting?
