### ISSUE TITLE
How train a model with custom LMDB files in DIGITS

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1447]
Hello,

I encounter with some models which are based on Caffe and can load in the DIGITS, but I can not train them in the DIGITS just because they do not get their input data in the DIGITS's defined separate LMDB files. 

The DIGITS creates or gets four LMDB files, one for training images, one for training labels, one for validation images and one for validation labels, but many existing models do not follow these.

For example I have a model which posses its own two parts based LMDB files, one for training and one for validation. I want to make these two LMDB files outside the DIGITS and use them to train a model inside the DIGITS afterwards.

How can I train a model in the DIGITS in such situations?

**Comment by VanitarNordic** [comment]
no idea?

**Comment by gheinrich** [comment]
Have a look at this and see if you can find an answer to your question:
https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/regression#alternative-method-manually-creating-lmdb-files

**Comment by VanitarNordic** [comment]
No, as I mentioned I have created these LMDB files before. They are two LMDB files and the model accepts these two files as input (not like 4 LMDB parts in DIGITS). 

The model's `.prototxt` file loads successfully inside DIGITS, but because the shape of the data-set is different than DIGITS default, I can not train the model.

**Comment by gheinrich** [comment]
When creating a dataset under "other" in DIGITS you can specify one LMDB for training features, optionally one LMDB for training labels. Optionally you can also provide one LMDB for validation features (and one LMDB for validation labels). So in DIGITS you have a choice of providing between 1 and 4 LMDB files.

You cannot provide 2 separate LMDBs for training features. If this is what you want to do, then DIGITS does not support this.

**Comment by VanitarNordic** [comment]
No, there is one LMDB file for training and one for validation. I gonna test your suggestion. Please do not close this thread till I post the results.

**Comment by VanitarNordic** [comment]
I got an error.

![screenshot from 2017-02-13 12-37-47](https://cloud.githubusercontent.com/assets/18719591/22877343/4bfa2c0a-f1ea-11e6-9870-1a46606f3fe7.png)

**Comment by gheinrich** [comment]
Pretty explicit error, right? You need to either set the shape in your `Datum` objects or use JPG/PNG encoding. Have a look at the LMDB creation examples.

**Comment by VanitarNordic** [comment]
The thing is that I have successfully trained the network using these LMDB files in the command line. is this a requirement if DIGITS?

**Comment by gheinrich** [comment]
Which command line are you referring to?

**Comment by VanitarNordic** [comment]
The author of the model has offered a python file, which is called from the Caffe root and trains the model.

**Comment by gheinrich** [comment]
To answer your question, DIGITS requires that you explicitly set the shape of your `Datum` objects when they are not encoded. Can we close this issue?

**Comment by VanitarNordic** [comment]
I did :-)
