### ISSUE TITLE
Inference from shell and epoch option

### ISSUE THREAD

**Issue by ontheway16** [NVIDIA/DIGITS#1457]
Hello, as far as I understand, inference from shell uses the last epoch in the given jobID. Is it possible to pass specific epoch number as a parameter for inference?

**Comment by lukeyeager** [comment]
Yep, you can pass `snapshot_epoch=2` in the form data:
https://github.com/NVIDIA/DIGITS/blob/v5.0.0/digits/model/images/classification/views.py#L365-L366

**Comment by ontheway16** [comment]
@lukeyeager thanks for this, helped me to find out dont_resize option too.
