### ISSUE TITLE
Install instructions in digits-5.0 install digits 4.

### ISSUE THREAD

**Issue by bpinaya** [NVIDIA/DIGITS#1458]
Hi there, when installing from deb packages (following instructions on the 5.0 branch) it seems to be installing Digits 4. I had to build it myself, no big trouble, but maybe that should be on the docs.
Thanks! I am loving digits so far 👍

**Comment by lukeyeager** [comment]
Yeah, it's taking us a while to get the DIGITS 5 debs out the door. Sorry for the delay!
