### ISSUE TITLE
Copy labels.txt inside the dataset

### ISSUE THREAD

**Issue by enoonIT** [NVIDIA/DIGITS#1462]
Migrating datasets, created by using text files, from one computer to another is a pain because new model jobs will fail with error:

> [ERROR] AssertionError: labels_file does not exist

Why not save the labels file inside the job folder and then use a relative path?

**Comment by lukeyeager** [comment]
Sounds like a good idea to me.

**Comment by lucbettaieb** [comment]
👍 to this
