### ISSUE TITLE
Conditions of Training/Validation images 

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1465]
Hello,

This is not an issue but a question which could be quite important. Basically for **detection** task.

1) How the **training** images should be? I mean the image should have a clear and fully visible view of the target object, or the image should be somehow tricky and target object should have some overlapping with others?

2) The same question with **validation** images, target object(s) should be clear and fully separated, or they should contain some overlapping?

This is an example about what I mean:

**Clear visible annotated image with no overlapping:**

![0113](https://cloud.githubusercontent.com/assets/18719591/23117712/420cb5b0-f766-11e6-9741-9826817225b1.jpg)

**Target object has some overlapping with other objects (those overlapped objects could be also target objects from the same class or not):**

![d](https://cloud.githubusercontent.com/assets/18719591/23117921/3e220fe4-f767-11e6-8b19-29f49611dd2a.jpg)

**Comment by lukeyeager** [comment]
This is very clearly a data science / usage question and not at all related to the development of DIGITS.

Please use the user group for this. Or any discussion group for any deep learning tool / framework / community.

https://github.com/NVIDIA/DIGITS/blob/master/README.md#get-help

**Comment by lukeyeager** [comment]
My two cents: you should probably be able to train a network that can recognize partly occluded images. Lots of objects in the KITTI dataset are partially occluded. As for picking validation images - that's up to you. If I were you, I'd pick a validation set that is similar to the types of images the trained model will be actually be seeing in production.

**Comment by VanitarNordic** [comment]
Yes, actually I was looking for your own experience as an expert.
