### ISSUE TITLE
A question about cropping data in Digits 

### ISSUE THREAD

**Issue by aohuanxuan** [NVIDIA/DIGITS#1466]
When I train a segmentation model I want to crop the data to size 321,
So I specified 321 in the Crop Size of Data Transformations,
but finally in the train_val.prototxt I get that:

layer {
  name: "data"
  type: "Data"
  top: "data"
  include {
    phase: TRAIN
  }
  transform_param {
    crop_size: 321
  }
  data_param {
    source: "/home/digits/digits/jobs/20170216-032538-3691/train_db/features"
    batch_size: 10
    backend: LMDB
  }
}
layer {
  name: "label"
  type: "Data"
  top: "label"
  include {
    phase: TRAIN
  }
  data_param {
    source: "/home/digits/digits/jobs/20170216-032538-3691/train_db/labels"
    batch_size: 10
    backend: LMDB
  }
}

we can see only the data layer is cropped, the label layer is not.
How can we crop both data and label? And because the crop is random, how can we make sure we can get the same part of image from data and label after the random crop?

**Comment by gheinrich** [comment]
Hello, Caffe does not support that kind of cropping however you can implement it with a Python layer. See the [Python layer tutorial](https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/python-layer).

**Comment by aohuanxuan** [comment]
Get it, Thank you!
