### ISSUE TITLE
Sanity Check Error with custom network model

### ISSUE THREAD

**Issue by YuryAlkevich** [NVIDIA/DIGITS#1467]
Hello, 
I'm trying to port Tiny Yolo digits for nvCaffe + Digits. Here is the partially complete model
[model.txt](https://github.com/NVIDIA/DIGITS/files/787508/model.txt)
When I try to create a job I get an error:

`ERROR: Layer 'conv1' references bottom 'input_data' at the TEST stage however this blob is not included at that stage. Please consider using an include directive to limit the scope of this layer.`

I can't understand why this happen taking into account that I set inclusions for input_data blob.

**Comment by gheinrich** [comment]
Hello, DIGITS makes assumptions on the names you give to your input layer. Have a look at the [standard alexnet](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/digits/standard-networks/caffe/alexnet.prototxt) for an example. See if renaming your `input_data` to `data` helps.

**Comment by YuryAlkevich** [comment]
Thanks, it helped!

**Comment by symepge** [comment]
Hey @YuryAlkevich, were you able to get that work? If so, can you provide some guidelines or share your code?

**Comment by symepge** [comment]
@gheinrich I have a more general question I appreciate your help with:

If an object detection model uses a label format other that KITTI (e.g., YOLO), should the dataset in DIGITS be defined with the KITTI format and the KITTI -> YOLO label conversion happen inside the network? Or can the dataset be defined with the YOLO format? Can you elaborate on this a little bit?

**Comment by gheinrich** [comment]
Sorry, what we name "KITTI dataset" in DIGITS formats the network input ground truth in a way that's very specific to our DetectNet network. If you use YOLO you will need to write a data plug-in: https://github.com/NVIDIA/DIGITS/tree/digits-6.0/examples/writing-plugins
