### ISSUE TITLE
/usr/bin/ld: cannot find -lopencv_dep_cudart

### ISSUE THREAD

**Issue by zafersn** [NVIDIA/DIGITS#1468]
hi. I m using Nvidia jetson tx1 Ubuntu 16.04. I get an error like below.

ubuntu@tegra-ubuntu:~/caffe/build$ sudo make --jobs=4
[  1%] Built target proto
[  1%] Linking CXX shared library ../../lib/libcaffe-nv.so
/usr/bin/ld: cannot find -lopencv_dep_cudart
collect2: error: ld returned 1 exit status
src/caffe/CMakeFiles/caffe.dir/build.make:31417: recipe for target 'lib/libcaffe-nv.so.0.15.14' failed
make[2]: *** [lib/libcaffe-nv.so.0.15.14] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lukeyeager** [comment]
First of all, I can't think of a reason why it would ever make sense to type `sudo make` for any project. Don't do that. See related horror story: https://github.com/BVLC/caffe/issues/2328.

Second, this looks like an OpenCV issue. Presumably you built OpenCV from source. That never seems to go well. Is there a reason you can't just install the dependencies with deb packages as we suggest in the instructions?
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildCaffe.md

**Comment by zafersn** [comment]
@lukeyeager  I didn't build opencv  related with this instructions. Because instead of doing that i preferred opencv4tegra which is coming with jetpack 2.3.1 

thank you for your interest :)

**Comment by lukeyeager** [comment]
Oh yeah. I vaguely remember OpenCV on TX1 being complicated. This is not a supported configuration for DIGITS, so we aren't going to have any instructions which can help you.

Look around on the Caffe forums - I'm sure somebody over there has figured out how to get Caffe to compile.

**Comment by alinabee** [comment]
No issues on my TX2, but my TX1 had the same problem.

I got rid of the error by adding `set(CUDA_USE_STATIC_CUDA_RUNTIME OFF)` to my CMakeLists.txt file or running in shell with: `cmake -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF`.

Then I was able to `make` and run with no issues.
