### ISSUE TITLE
Does batch accumulation consider cutom loss layers?

### ISSUE THREAD

**Issue by RSly** [NVIDIA/DIGITS#1470]
Hi,

* I would like to know more about the batch accumulation from digits, and how this treats custom loss layers.

* In particular, for the segmentation example, I see the influence of batch accumulation on the softmaxwithloss output, but it seems it does not change anything in the dice loss output values...

Is this a bug or I am missing something here?

**Comment by gheinrich** [comment]
Are you referring to the medical imaging example? There the Dice layer is a metric, not a loss.

Regarding your question: yes, batch accumulation affects all layers. Whether this affects metrics depends on many parameters. What you're seeing is not a bug.
