### ISSUE TITLE
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by zafersn** [NVIDIA/DIGITS#1472]
Hello everyone! 
When I write this comment, I got this error. I was not able to figure it out. Can anyone has the same problem ? 
Note: I used Nvidia JetsonTX1 and Ubuntu16.04

sudo pip install -r $DIGITS_ROOT/requirements.txt

In file included from ./leveldb/port/port_posix.h:50:0,
                     from ./leveldb/port/port.h:14,
                     from ./leveldb/db/filename.h:14,
                     from leveldb/db/builder.cc:7:
    ./leveldb/port/atomic_pointer.h:212:2: error: #error Please implement AtomicPointer for this platform.
     #error Please implement AtomicPointer for this platform.
      ^
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

**Comment by lukeyeager** [comment]
You'll probably have to build Caffe with LevelDB support turned off. 

As I said,

> Look around on the Caffe forums - I'm sure somebody over there has figured out how to get Caffe to compile.
https://github.com/NVIDIA/DIGITS/issues/1468#issuecomment-281736590
