### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by waholulu** [NVIDIA/DIGITS#1479]
After excute the commands in the guidance. 

```
# Access to CUDA packages
CUDA_REPO_PKG=cuda-repo-ubuntu1404_7.5-18_amd64.deb
wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/${CUDA_REPO_PKG} -O /tmp/${CUDA_REPO_PKG}
sudo dpkg -i /tmp/${CUDA_REPO_PKG}
rm -f /tmp/${CUDA_REPO_PKG}

# Access to Machine Learning packages
ML_REPO_PKG=nvidia-machine-learning-repo-ubuntu1404_4.0-2_amd64.deb
wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/${ML_REPO_PKG} -O /tmp/${ML_REPO_PKG}
sudo dpkg -i /tmp/${ML_REPO_PKG}
rm -f /tmp/${ML_REPO_PKG}

# Download new list of packages
sudo apt-get update
```

the result shows 

> 
> Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
> Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease                     
> Ign:3 http://dl.google.com/linux/chrome/deb stable InRelease                   
> Hit:4 http://dl.google.com/linux/chrome/deb stable Release                     
> Get:5 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]    
> Get:7 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]  
> Ign:8 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64  InRelease
> Ign:9 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64  InRelease
> Hit:10 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64  Release
> Hit:12 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64  Release
> Fetched 306 kB in 1s (247 kB/s)
> Reading package lists... Done
> **W: Invalid 'Date' entry in Release file /var/lib/apt/lists/developer.download.nvidia.com_compute_machine-learning_repos_ubuntu1404_x86%5f64_Release**

Then  when I execute ` sudo apt-get install digits
`
the result shows 

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  digits : Depends: python-caffe-nv (>= 0.13) but it is not going to be installed
>           Depends: caffe-nv (>= 0.13) but it is not going to be installed
>           Recommends: torch7-nv but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> 

The result of `sudo aptitude install digits` is 

> 
> _The following NEW packages will be installed:
>   caffe-nv{ab} caffe-nv-tools{ab} cuda-cublas-8-0{a} cuda-cudart-8-0{a} cuda-curand-8-0{a} cuda-cusparse-8-0{a} cuda-license-8-0{a} cython{a} digits graphicsmagick{a} 
>   gunicorn{a} gyp{a} ipython{a} libbz2-dev{a} libcaffe-nv0{ab} libcudnn5{a} libexif-dev{a} libfreeimage3{a} libglade2-0{a} libgraphicsmagick-q16-3{a} 
>   libgraphicsmagick1-dev{a} libjs-inherits{a} libjs-jquery-ui{a} libjs-node-uuid{a} libjxr0{a} liblcms2-dev{a} libnccl1{a} libopenjp2-7{a} libqt4-designer{a} 
>   libqt4-help{a} libqt4-opengl{a} libqt4-scripttools{a} libqt4-svg{a} libqt4-test{a} libqtassistantclient4{a} libqtwebkit4{a} libssl-dev{a} libssl-doc{a} libuv1{a} 
>   libuv1-dev{a} libwmf-dev{a} libxml2-dev{a} node-abbrev{a} node-ansi{a} node-ansi-color-table{a} node-archy{a} node-async{a} node-block-stream{a} 
>   node-combined-stream{a} node-cookie-jar{a} node-delayed-stream{a} node-forever-agent{a} node-form-data{a} node-fstream{a} node-fstream-ignore{a} 
>   node-github-url-from-git{a} node-glob{a} node-graceful-fs{a} node-gyp{a} node-inherits{a} node-ini{a} node-json-stringify-safe{a} node-lockfile{a} node-lru-cache{a} 
>   node-mime{a} node-minimatch{a} node-mkdirp{a} node-mute-stream{a} node-node-uuid{a} node-nopt{a} node-normalize-package-data{a} node-npmlog{a} node-once{a} 
>   node-osenv{a} node-qs{a} node-read{a} node-read-package-json{a} node-request{a} node-retry{a} node-rimraf{a} node-semver{a} node-sha{a} node-sigmund{a} node-slide{a} 
>   node-tar{a} node-tunnel-agent{a} node-underscore{a} node-which{a} nodejs{a} nodejs-dev{a} npm{a} python-blinker{a} python-caffe-nv{ab} python-cairo{a} 
>   python-cffi-backend{a} python-chardet{a} python-cryptography{a} python-cycler{a} python-dateutil{a} python-enum34{a} python-flask{a} python-flaskext.socketio{a} 
>   python-flaskext.wtf{a} python-gevent{a} python-gevent-websocket{a} python-glade2{a} python-gobject-2{a} python-greenlet{a} python-gtk2{a} python-gunicorn{a} 
>   python-h5py{a} python-idna{a} python-ipaddress{a} python-itsdangerous{a} python-jinja2{a} python-lmdb{a} python-markupsafe{a} python-matplotlib{a} 
>   python-matplotlib-data{a} python-ndg-httpsclient{a} python-opencv{a} python-openssl{a} python-pexpect{a} python-protobuf{a} python-ptyprocess{a} python-pyasn1{a} 
>   python-pydot{a} python-pyinotify{a} python-pyparsing{a} python-qt4{a} python-requests{a} python-simplegeneric{a} python-sip{a} python-six{a} python-skimage{a} 
>   python-skimage-lib{a} python-socketio{a} python-tz{a} python-urllib3{a} python-werkzeug{a} python-wtforms{a} torch7-nv{ab} 
> 0 packages upgraded, 142 newly installed, 0 to remove and 3 not upgraded.
> Need to get 225 MB of archives. After unpacking 817 MB will be used.
> The following packages have unmet dependencies:
>  libcaffe-nv0 : Depends: libboost-python1.54.0 which is a virtual package and is not provided by any available package.
>                 Depends: libboost-system1.54.0 which is a virtual package and is not provided by any available package.
>                 Depends: libboost-thread1.54.0 which is a virtual package and is not provided by any available package.
>                 Depends: libgflags2 which is a virtual package and is not provided by any available package.
>                 Depends: libgoogle-glog0 which is a virtual package and is not provided by any available package.
>                 Depends: libhdf5-7 which is a virtual package and is not provided by any available package.
>                 Depends: libleveldb1 which is a virtual package and is not provided by any available package.
>                 Depends: libopencv-core2.4 which is a virtual package and is not provided by any available package.
>                 Depends: libopencv-highgui2.4 which is a virtual package and is not provided by any available package.
>                 Depends: libopencv-imgproc2.4 which is a virtual package and is not provided by any available package.
>                 Depends: libprotobuf8 which is a virtual package and is not provided by any available package.
> 
>  python-caffe-nv : Depends: libboost-python1.54.0 which is a virtual package and is not provided by any available package.
>                    Depends: libboost-system1.54.0 which is a virtual package and is not provided by any available package.
>  Depends: libgoogle-glog0 which is a virtual package and is not provided by any available package.
>  Depends: libprotobuf8 which is a virtual package and is not provided by any available package.
> 
>  torch7-nv : Depends: libqt4-core which is a virtual package and is not provided by any available package.
>              Depends: libqt4-gui which is a virtual package and is not provided by any available package.
>              Depends: libzmq3 which is a virtual package and is not provided by any available package.
>              Depends: libhdf5-7 which is a virtual package and is not provided by any available package.
> 
>  caffe-nv : Depends: libboost-python1.54.0 which is a virtual package and is not provided by any available package.
>             Depends: libboost-system1.54.0 which is a virtual package and is not provided by any available package.
> Depends: libgflags2 which is a virtual package and is not provided by any available package.
> Depends: libgoogle-glog0 which is a virtual package and is not provided by any available package.
> 
>  caffe-nv-tools : Depends: libboost-system1.54.0 which is a virtual package and is not provided by any available package.
> Depends: libgflags2 which is a virtual package and is not provided by any available package.
> Depends: libgoogle-glog0 which is a virtual package and is not provided by any available package.
> Depends: libleveldb1 which is a virtual package and is not provided by any available package.
> Depends: libopencv-core2.4 which is a virtual package and is not provided by any available package.
> Depends: libopencv-highgui2.4 which is a virtual package and is not provided by any available package.
> Depends: libopencv-imgproc2.4 which is a virtual package and is not provided by any available package.
> Depends: libprotobuf8 which is a virtual package and is not provided by any available package.
> 
> The following actions will resolve these dependencies:
> 
>     Keep the following packages at their current version:
> 1)     caffe-nv [Not Installed]                           
> 2)     caffe-nv-tools [Not Installed]                     
> 3)     digits [Not Installed]                             
> 4)     libcaffe-nv0 [Not Installed]                       
> 5)     python-caffe-nv [Not Installed]                    
> 6)     torch7-nv [Not Installed]                          
> 
>      Leave the following dependencies unresolved:         
> 7)     caffe-nv recommends caffe-nv-tools                 
> 8)     digits recommends torch7-nv                        
> 
> 
> Accept this solution? [Y/n/q/?]_ 

HOW TO SOLVE THIS?????!!!

**Comment by lukeyeager** [comment]
Looks like you're possibly using Ubuntu 16.04? Those repos only work for Ubuntu 14.04:

> Deb packages for major releases (i.e. v3.0 and v4.0 but not v3.1) are provided for easy installation on Ubuntu 14.04.
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md

**Comment by waholulu** [comment]
Well then how to install in 16.04??? any official guide?

**Comment by waholulu** [comment]
Thank you

**Comment by LeenaShekhar** [comment]
Hi,

I am getting this issue. How did you solve it? 

The following NEW packages will be installed:
  caffe-nv{ab} caffe-nv-tools{ab} digits{b} libcaffe-nv0{ab} libcudnn5{a} libnccl1{a} nginx{a} nginx-common{a} nginx-core{a} python-blinker{a} python-caffe-nv{ab} python-engineio{a} python-flask{a} 
  python-flaskext.socketio{a} python-flaskext.wtf{a} python-gevent{a} python-gevent-websocket{a} python-greenlet{a} python-h5py{a} python-itsdangerous{a} python-lmdb{a} python-pydot{a} 
  python-pyinotify{a} python-skfmm{a} python-socketio2{a} python-werkzeug{a} python-wtforms{a} torch7-nv{a} 
0 packages upgraded, 28 newly installed, 0 to remove and 0 not upgraded.
Need to get 1,623 kB/88.9 MB of archives. After unpacking 1,101 MB will be used.
The following packages have unmet dependencies:
 caffe-nv : Depends: libboost-python1.58.0 which is a virtual package.
            Depends: libboost-system1.58.0 which is a virtual package.
            Depends: libgflags2v5 which is a virtual package.
            Depends: libgoogle-glog0v5 which is a virtual package.
            Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is installed.
 caffe-nv-tools : Depends: libboost-system1.58.0 which is a virtual package.
                  Depends: libgflags2v5 which is a virtual package.
                  Depends: libgoogle-glog0v5 which is a virtual package.
                  Depends: libleveldb1v5 which is a virtual package.
                  Depends: libopencv-core2.4v5 which is a virtual package.
                  Depends: libopencv-highgui2.4v5 which is a virtual package.
                  Depends: libopencv-imgproc2.4v5 which is a virtual package.
                  Depends: libprotobuf9v5 which is a virtual package.
                  Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is installed.
 libcaffe-nv0 : Depends: libboost-python1.58.0 which is a virtual package.
                Depends: libboost-system1.58.0 which is a virtual package.
                Depends: libboost-thread1.58.0 which is a virtual package.
                Depends: libgflags2v5 which is a virtual package.
                Depends: libgoogle-glog0v5 which is a virtual package.
                Depends: libhdf5-10 which is a virtual package.
                Depends: libleveldb1v5 which is a virtual package.
                Depends: libopencv-core2.4v5 which is a virtual package.
                Depends: libopencv-highgui2.4v5 which is a virtual package.
                Depends: libopencv-imgproc2.4v5 which is a virtual package.
                Depends: libprotobuf9v5 which is a virtual package.
                Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is installed.
 digits : Depends: python-wtforms (>= 2.0.1) but 1.0.1-1 is to be installed.
 python-caffe-nv : Depends: libboost-python1.58.0 which is a virtual package.
                   Depends: libboost-system1.58.0 which is a virtual package.
                   Depends: libgoogle-glog0v5 which is a virtual package.
                   Depends: libprotobuf9v5 which is a virtual package.
                   Depends: libstdc++6 (>= 5.2) but 4.8.4-2ubuntu1~14.04.3 is installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     caffe-nv [Not Installed]                           
2)     caffe-nv-tools [Not Installed]                     
3)     digits [Not Installed]                             
4)     libcaffe-nv0 [Not Installed]                       
5)     python-caffe-nv [Not Installed]                    

     Leave the following dependencies unresolved:         
6)     caffe-nv recommends caffe-nv-tools
