### ISSUE TITLE
adapting a "Classification" network into a "Detection" network

### ISSUE THREAD

**Issue by ShervinAr** [NVIDIA/DIGITS#1480]
Dear all,

I would like to adapt an existing network (e.g. Lenet) which is designed for the _**classification**_ task into a network which will be used for _**object detection**_ purposes (such as DetectNet). Any help on the steps to follow is greatly appreciated.
In particular, the adapted .prototxt file of Lenet for _**detection**_ is very much welcome.

many thanks,
Shervin

**Comment by rodrigoberriel** [comment]
@ShervinAr you can't do that with DIGITS. I recommend you to take a look at https://github.com/BVLC/caffe/blob/master/examples/net_surgery.ipynb and start from there. Also, the caffe-users group might be a better place to ask such things: https://groups.google.com/d/forum/caffe-users

**Comment by gheinrich** [comment]
Closing as this is not an issue in DIGITS.
