### ISSUE TITLE
Can't create segmentation dataset

### ISSUE THREAD

**Issue by waholulu** [NVIDIA/DIGITS#1482]
The digits report error about Feature shape mismatch while I'm creating  the segmentation dataset. Is there any preprocessing required for the image?  How to solve this issue?

> Job Status Error
> Initialized at 12:45:44 PM (1 second)
> Running at 12:45:45 PM (3 seconds)
> Error at 12:45:48 PM 
> (Total - 4 seconds)
> Create train_db DB Error 
> Initialized at 12:45:44 PM (1 second)
> Running at 12:45:45 PM (3 seconds)
> Error at 12:45:48 PM 
> (Total - 4 seconds)
> ERROR: Exception: ValueError: Feature shape mismatch (last:(3, 512, 683), previous:(3, 206, 300))

For the log in the terminal

> Create val_db DB Error 
> Initialized at 12:45:44 PM (1 second)
> Running at 12:45:45 PM (3 seconds)
> Error at 12:45:48 PM 
> (Total - 4 seconds)
> ERROR: Exception: ValueError: Feature shape mismatch (last:(3, 256, 256), previous:(3, 512, 683))

> 2017-02-28 12:45:45 [20170228-124544-b8b4] [INFO ] Create train_db DB task started.
> 2017-02-28 12:45:45 [20170228-124544-b8b4] [INFO ] Task subprocess args: "/usr/bin/python2 /home/chenyan/digits/digits/tools/create_generic_db.py 20170228-124544-b8b4 --stage=train_db --jobs_dir=/home/chenyan/digits/digits/jobs"
> 2017-02-28 12:45:45 [20170228-124544-b8b4] [INFO ] Create val_db DB task started.
> 2017-02-28 12:45:45 [20170228-124544-b8b4] [INFO ] Task subprocess args: "/usr/bin/python2 /home/chenyan/digits/digits/tools/create_generic_db.py 20170228-124544-b8b4 --stage=val_db --jobs_dir=/home/chenyan/digits/digits/jobs"
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: Exception in thread Thread-4:
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: Traceback (most recent call last):
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: self.run()
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 261, in run
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: % (repr(feature.shape), repr(self.feature_shape)))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: ValueError: Feature shape mismatch (last:(3, 260, 346), previous:(3, 256, 256))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: Exception in thread Thread-2:
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: Traceback (most recent call last):
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: self.run()
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 261, in run
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: % (repr(feature.shape), repr(self.feature_shape)))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: ValueError: Feature shape mismatch (last:(3, 352, 450), previous:(3, 343, 250))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: Exception in thread Thread-2:
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: Traceback (most recent call last):
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: self.run()
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 261, in run
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: % (repr(feature.shape), repr(self.feature_shape)))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: ValueError: Feature shape mismatch (last:(3, 256, 256), previous:(3, 512, 683))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [ERROR] Create train_db DB: ValueError: Feature shape mismatch (last:(3, 260, 346), previous:(3, 256, 256))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [ERROR] Create train_db DB: ValueError: Feature shape mismatch (last:(3, 352, 450), previous:(3, 343, 250))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [ERROR] Create train_db DB: ValueError: Feature shape mismatch (last:(3, 512, 683), previous:(3, 206, 300))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [ERROR] Create train_db DB: Exception: ValueError: Feature shape mismatch (last:(3, 512, 683), previous:(3, 206, 300))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: Traceback (most recent call last):
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 478, in <module>
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: args['stage']
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 443, in create_generic_db
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: force_same_shape)
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: Exception in thread Thread-5:
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: Traceback (most recent call last):
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: self.run()
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 261, in run
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: % (repr(feature.shape), repr(self.feature_shape)))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: ValueError: Feature shape mismatch (last:(3, 512, 683), previous:(3, 206, 300))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [ERROR] Create val_db DB: ValueError: Feature shape mismatch (last:(3, 256, 256), previous:(3, 512, 683))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [ERROR] Create val_db DB: Exception: ValueError: Feature shape mismatch (last:(3, 256, 256), previous:(3, 512, 683))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: Traceback (most recent call last):
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 478, in <module>
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: args['stage']
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 443, in create_generic_db
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: force_same_shape)
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 341, in create_db
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: raise Exception(err)
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create val_db DB unrecognized output: Exception: ValueError: Feature shape mismatch (last:(3, 256, 256), previous:(3, 512, 683))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: File "/home/chenyan/digits/digits/tools/create_generic_db.py", line 341, in create_db
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: raise Exception(err)
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [WARNING] Create train_db DB unrecognized output: Exception: ValueError: Feature shape mismatch (last:(3, 512, 683), previous:(3, 206, 300))
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [ERROR] Create train_db DB task failed with error code 1
> 2017-02-28 12:45:48 [20170228-124544-b8b4] [ERROR] Create val_db DB task failed with error code 1
>

**Comment by gheinrich** [comment]
You might want to set "Enforce Same Shape" to False. Set the batch size to 1 in that case. See the tutorial on:
https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/semantic-segmentation#loading-the-data-into-digits

**Comment by waholulu** [comment]
Thanks
