### ISSUE TITLE
How to use pretrained .caffe model file to do image segmentation 

### ISSUE THREAD

**Issue by waholulu** [NVIDIA/DIGITS#1483]
From example , I found a pretrained caffe model here. https://github.com/CSAILVision/sceneparsing
and I have 1 picture 
![test](https://cloud.githubusercontent.com/assets/2868000/23437018/96458600-fdda-11e6-8249-3ae09ed870db.png)
that I want to make segmentation. **How to do it?** the guides here only shows how to train a model. I just want to use it. Thanks

**Comment by gheinrich** [comment]
DIGITS is a training system. If you already have a trained model and wish to use it for inference you might be interested in this project: https://github.com/dusty-nv/jetson-inference/tree/master/segnet-console
