### ISSUE TITLE
Segmentation visualization banding

### ISSUE THREAD

**Issue by adnphllps** [NVIDIA/DIGITS#1485]
When viewing inference results with the segmentation option, many images have banding or bullseye patterns on areas of a class that should be contiguous. This has happened on multiple network designs.

Has anyone seen this happen? 

In this case the proper inference would be all red class:
![image](https://cloud.githubusercontent.com/assets/1544500/23473792/7ac38c9c-fe7f-11e6-865d-5e5f4e7140a1.png)

This is mask copied from the visualization page:
![image](https://cloud.githubusercontent.com/assets/1544500/23473946/14731a24-fe80-11e6-919c-9a3cd547b08d.png)

Another example of the mask from a different image, but over a black background. The white areas should be a contiguous block:

![screenshot from 2017-03-01 13-13-21](https://cloud.githubusercontent.com/assets/1544500/23474213/f75f1996-fe80-11e6-8d57-f71e104ed35f.png)

![image](https://cloud.githubusercontent.com/assets/1544500/23473663/08857c08-fe7f-11e6-8fb3-9918861a2a5b.png)

**Comment by gheinrich** [comment]
Thanks for the great visualizations!

@jmancewicz can you check please?

**Comment by 4575759ww** [comment]
my inference results have the same phenomenon, also don't know why. I guess it is relevant with the deconvolution layer.

**Comment by gheinrich** [comment]
I see this banding effect on the master branch but not on the release 5.0 branch: https://github.com/NVIDIA/DIGITS/tree/digits-5.0
Can everybody confirm?

**Comment by jmancewicz** [comment]
Can you send screenshots?

**Comment by jmancewicz** [comment]
Nevermind.

**Comment by jmancewicz** [comment]
I will look at this today. It looks like it's modulating. Is the data normalized?

**Comment by adnphllps** [comment]
I see it on 5.1-dev

**Comment by adnphllps** [comment]
I noticed that by adjusting the mask slider on the inference results page, the areas that should be masked begin to appear as the the mask percentage is increased.

**Comment by jmancewicz** [comment]
#1531 should fix it. It's a simple fix that will fix the banding, but simply clamps the alpha channel which is used for adjusting the tolerance in the binary segmentation.  It was wrapping every 256 pixels in distance from the isosurface.

@gheinrich, have a look?

**Comment by lukeyeager** [comment]
Fixed in https://github.com/NVIDIA/DIGITS/pull/1531 - thanks Joe!
