### ISSUE TITLE
DetectNet inference on CPU only

### ISSUE THREAD

**Issue by ShervinAr** [NVIDIA/DIGITS#1490]
Dear all,

I have trained a detectNet model using Digits and successfully performed object detection. I am wondering whether there is an easy way to bypass _**GPU**_ usage and use _only_ _**CPU**_ (in C++) in the inference stage?

**Comment by gheinrich** [comment]
DetectNet requires some custom layers from [nv-caffe](https://github.com/NVIDIA/caffe) which are not easily ported to the main Caffe fork. Released binaries for nv-caffe are compiled with built-in GPU support but you should be able to rebuild nv-caffe yourself without GPU support (`CPU_ONLY:=1` see [doc](http://caffe.berkeleyvision.org/installation.html)) if you follow these [instructions](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildCaffe.md).

**Comment by ShervinAr** [comment]
@gheinrich  many thanks
