### ISSUE TITLE
C++ code for DetectNet model inference outside Digits

### ISSUE THREAD

**Issue by ShervinAr** [NVIDIA/DIGITS#1493]
Dear all,

Is anyone aware of a sample C++ code to perform inference on a DetectNet model trained using Digits.
I am aware of the the C++ codes provided for Jetson but these seem to produce quite different results from those in the Digits environment.

**Comment by gheinrich** [comment]
It sounds like the best course of action would be for you to investigate the discrepancies.

**Comment by ShervinAr** [comment]
@gheinrich  this seems quite impossible due to poor documentation of Jetson C++ codes

**Comment by gheinrich** [comment]
This is open source software, you are welcome to look into the code and contribute better documentation.

**Comment by ShervinAr** [comment]
@gheinrich I would if at least some algorithmic reference for the code was already available or the code writers were willing to provide such an explanation!

**Comment by gheinrich** [comment]
Thanks for the feedback. I will close this issue for now since this does not report an issue in DIGITS. Discussions are welcome on the DIGITS distribution list: https://groups.google.com/forum/#!forum/digits-users
