### ISSUE TITLE
How do digits do classify?A strange problem with caffe classification

### ISSUE THREAD

**Issue by c437yuyang** [NVIDIA/DIGITS#1497]
I have encountered a strange problem,when i use DIGITS to train a model,i got a very nice train and val accuracy,and then i use classifymany function to do classification with my val dataset,it can get the almost same result with the train result. But when i use the model and deploy.prototxt file i extracted directly from digits/jobs/xxx to do classification with python interface,it gets a exactly different result.
To be thiefly,here i use the same picture to do classify one and classify use the python interface().[https://github.com/NVIDIA/DIGITS/blob/master/examples/classification/README.md](url),and here is the different result(classify one get the correct result), and i need to use the result from python classification to integrate into a project,so who can tell me how DIGITS do the classification(I am reading the DIGITS source code now,but i am not very familiar with python,so its hard for me to get the answer and i need to fix this problem as soon as i can)? thanks very much!
classify one:
[
![2017-03-08 10 03 54](https://cloud.githubusercontent.com/assets/20332942/23686791/a05b79b2-03e6-11e7-8194-97dfa0acf03a.png)
](url)
python interface:
![2017-03-08 10 07 53](https://cloud.githubusercontent.com/assets/20332942/23686922/237faee4-03e7-11e7-81a5-21b1e5fe2769.png)

**Comment by gheinrich** [comment]
It might help if you re-train your classification model using "pixel" mean subtraction instead of the default "image" mean subtraction.

**Comment by c437yuyang** [comment]
@gheinrich oh god,thank you very much！ I trained the model using "pixel" mean and then use python interface to do classification with mean.binaryproto and solved this problem,but why this would happen?
I feel very strange because when i trained the model on other dataset it would be ok when train and classify all use mean.binaryproto,this problem only occurs on this dataset.

**Comment by gheinrich** [comment]
@c437yuyang you will find answers if you browse the archives (Gtihub issues and discussions on https://groups.google.com/forum/#!forum/digits-users).

The Python classification script is doing mean pixel subtraction. Depending on the dataset, the difference between mean image and mean pixel subtraction will be more or less significant.

**Comment by c437yuyang** [comment]
@gheinrich thank you!

**Comment by NNsauce** [comment]
@gheinrich Can I use "tf.image.per_image_standardization" to make pixel mean?
