### ISSUE TITLE
[Suggestion]Add change the snapshot period item

### ISSUE THREAD

**Issue by AltenLi** [NVIDIA/DIGITS#15]
I'd like to add the textbox of snapshot_epoch for changing the snapshot period.
Or my disk is going to explode...
Would you tell me which file should I change?
(I've found the digits/model/forms.py to add the box)

**Comment by AltenLi** [comment]
i've also changed "solver.snapshot = self.snap_epochs" in "digits/model/tasks/caffe_train.py"

**Comment by AltenLi** [comment]
Also "self.snap_epochs = snap_epochs" in "digits/model/tasks/caffe_train.py" "__init__"

**Comment by lukeyeager** [comment]
Hi @AltenLi. Yes, that's a feature that I was planning on adding. It looks like you've found all the right changes to make. If you've got it working, please send a pull request and I'll get it added into the master branch!

**Comment by thatguymike** [comment]
I wonder if while we are at it, we should add an option to save the last N snapshots as well, with the default being all.

**Comment by AltenLi** [comment]
It seems worked, but I wonder...is the unit of snapshot should be epoch or
iteration

On Tue, Mar 24, 2015 at 3:38 AM, Luke Yeager <notifications@github.com>
wrote:

> Hi @AltenLi <https://github.com/AltenLi>. Yes, that's a feature that I
> was planning on adding. It looks like you've found all the right changes to
> make. If you've got it working, please send a pull request and I'll get it
> added into the master branch!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NVIDIA/DIGITS/issues/15#issuecomment-85161882>.
>



-- 
Best Regards,
------------------
李千
Qian Li
HUST
Mobile:+86-18511584115
Email: liqian115@gmail.com

**Comment by AltenLi** [comment]
@lukeyeager I've updated the func for snapshot on my fork
