### ISSUE TITLE
Difference in GPU memory usage between training with caffe or with DIGITS+caffe

### ISSUE THREAD

**Issue by MRLoghmani** [NVIDIA/DIGITS#1505]
I was trying to fine-tune a VGG_16 and I noticed that, on the same data and with the same model, running the training with DIGITS needs about 2GB of additional GPU memory with respect to the training with plain caffe (launched from terminal). 
These are the outputs I get from nvidia-smi:

CAFFE only:

![caffe_only](https://cloud.githubusercontent.com/assets/6833023/23792685/5a337176-0588-11e7-91c3-5e4fdd2afe1f.png)

DIGITS+CAFFE:

![digits](https://cloud.githubusercontent.com/assets/6833023/23792696/641afe98-0588-11e7-9f5f-c0e657f68466.png)

I also found this discussion in caffe issues (https://github.com/BVLC/caffe/issues/1242) in which people claim the VGG model takes 1.5GB, while it seems that for me, when using DIGITS, the model takes about 4GB.

Any clues on why this happens?

**Comment by gheinrich** [comment]
The memory usage in nvidia-smi should not be worried about too much here. nv-caffe tends to pre-allocate memory to achieve better efficiency. Besides, some optimizations are done at the expense of slightly higher memory consumption. Either way, this is not a DIGITS issue so I am closing it now.

**Comment by ducnghia** [comment]
Is there anyway I could run fcn8s-heavy-pascal.caffemodel on DIGITS with a dedicated GTX 780Ti (3GB memory) without out of memory error at all?
