### ISSUE TITLE
No install.sh shell script in my git clone install

### ISSUE THREAD

**Issue by machomachopadre** [NVIDIA/DIGITS#1506]
Hi,

I executed `sudo git clone https://github.com/NVIDIA/DIGITS.git` and got digits in my home folder. Every tutorial on the web says that next I need to execute ./install.sh, but I don't have such a script! Is my install broken, or am I missing something?

Thanks

**Comment by gheinrich** [comment]
Hello, our installation instructions are on https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md
