### ISSUE TITLE
GPU CUDA Unknown Error

### ISSUE THREAD

**Issue by httpswlt** [NVIDIA/DIGITS#1510]
![s d 39coiyz cepq4q e 7q](https://cloud.githubusercontent.com/assets/25114312/23937312/d51ed53a-0991-11e7-8ef3-ff31743df6a9.png)
Thank you!!!

**Comment by lukeyeager** [comment]
This doesn't seem related to DIGITS. Sounds like you killed a process in a weird way. Try rebooting? Otherwise try on StackOverflow or the NVIDIA devtalk forum or something?

**Comment by httpswlt** [comment]
Thank you for your reply.@lukeyeager
I aready rebooting. Then it's has already been solved. But I don't why.This issue has appeared several times.I always solve it by restarting the server.So I want to why.I also ask the issue to flx42.Below is his reply information.And you can see.
![c 85 jy9vnx 2ozaf rbrg](https://cloud.githubusercontent.com/assets/25114312/23978221/c073c482-0a2d-11e7-9541-4aa59dd7f569.png)

**Comment by lukeyeager** [comment]
Well I'm glad Felix agrees with me! Please post back if you figure it out!

**Comment by httpswlt** [comment]
Okay.I'll do.
