### ISSUE TITLE
Loading floating point / binary data

### ISSUE THREAD

**Issue by swigicat** [NVIDIA/DIGITS#1516]
I have two questions:

1. Is DIGITS able to load floating point data, or higher bits-per-pixel? I have images coming from a LIDAR-like device and would like to load them as they are, and not scaled down to 8bpp.
2. Is there any way to bulk-load binary data into DIGITS, i.e. one file per class, containing all the pictures at a fixed resolution? Copying half a million files to the machine I do the learning on takes a long time, and I need to to this every time there's some change in the image preprocessing (I prefer working with the current tools to preprocess data instead of doing it with layers).

Thanks!

**Comment by gheinrich** [comment]
Hello, you can check the regression tutorial on https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/regression. Then have a look at the corresponding plug-in: https://github.com/NVIDIA/DIGITS/tree/digits-5.0/plugins/data/imageGradients. You can write your own plug-in to do the data ingest. Look into the code, everything should be self explanatory.

**Comment by swigicat** [comment]
Sorry for the long update time, I'm recently trying this but doesn't seem to work. I've created a new plugin for data ingestion. I'm able to load data, but for some reason the same network that is trained with the regular dataset (loaded from folders of images) produces strange results on the data I'm loading with the plugin. I'm guessing either the data or the labels are not in the correct format, but I can't actually see what is stored in the database.

My data is stored in a very simple format - a single binary file, first the label (from 0 to num_classes-1), stored as float32, then 1024 float32's of data (from 0 to 255, 32x32 image), then the next label and image and so on.

Some snippets of the data.py file, maybe you can spot the problem:
```
    @override
    def itemize_entries(self, stage):
        if not self.userdata['is_inference_db']:
            if stage == constants.TRAIN_DB:
                entries = self.read_bin(self.train_data_file)
            elif stage == constants.VAL_DB:
                if self.val_data_file:
                    entries = self.read_bin(self.val_data_file)
                else:
                    entries = []
            else:
                entries = []
        else:
            if stage == constants.TEST_DB:
                if not bool(self.test_data_file):
                    raise ValueError("You must provide a data file")
                else:
                    entries = self.read_bin(self.test_data_file, False)
            else:
                entries = []
        return entries

    def read_bin(self, filename, shuffle=True):
        entries = []
        with open(filename, "rb") as f:
            while True:
	        label = np.fromfile(f, dtype=np.float32, count=1)
	        if len(label) == 0:
	            break

	        image = np.fromfile(f, dtype=np.float32, count=1024)
	        entries = entries + [{'class': int(label), 'image': image}]
        return entries
```

and the encode_entry function

```
    @override
    def encode_entry(self, entry):
        label = np.array([entry['class']])
	image = entry['image']
        img = image.reshape(32, 32)
        sample = img[np.newaxis, ...]

        return sample, label
```

When I'm using the same network, with the last fully connected layer dimension set to the number of classes, the learning produces this:
![image](https://user-images.githubusercontent.com/25076260/27174386-40178338-51bc-11e7-95c7-657f8837ad3d.png)
