### ISSUE TITLE
SPPLayer support

### ISSUE THREAD

**Issue by KangKyungSoo** [NVIDIA/DIGITS#152]
I want to use SPPLayer(Spatial Pyramid Pooling Layer) within DIGITS.
But, NVIDIA/caffe is not supprting it by now(BVLC/caffe is supporting it from a month ago).
Could you update NVIDIA/caffe?

Regards,

KyungSoo

**Comment by lukeyeager** [comment]
It will be included in the next release. Thanks for letting us know you are interested in using it!
