### ISSUE TITLE
Confusing size of bounding boxes on object detection tutorial page

### ISSUE THREAD

**Issue by hadi-ghnd** [NVIDIA/DIGITS#1521]
I'm trying to perform object detection on a set of aerial images.  As it's mentioned, the size of objects should be between 50x50 to 400x400 pixels. In my case, the images are too large and the objects are relatively small. I searched for a dataset with very high resolution images, but most of the objects are smaller than 50 pixels in all of the datasets I found. So when I try to perform the training, the result is always something like this:

![screenshot from 2017-03-20 21-17-01](https://cloud.githubusercontent.com/assets/24352869/24113632/aaa30054-0db2-11e7-8152-24b599a9830c.png)

However on [this](https://devblogs.nvidia.com/parallelforall/detectnet-deep-neural-network-object-detection-digits/) and [this](https://devblogs.nvidia.com/parallelforall/deep-learning-object-detection-digits/) pages, the example is about vehicle detection in aerial images (exactly my case) and it seems to be working. I noticed that the size of images used in [the tutorial](https://devblogs.nvidia.com/parallelforall/detectnet-deep-neural-network-object-detection-digits/) is **1024x512**, while the size of bounding boxes of small vehicles seem to be strangely large:

![screenshot from 2017-03-20 21-22-38](https://cloud.githubusercontent.com/assets/24352869/24113882/7bb2b158-0db3-11e7-8b22-4e853084ac14.png)

As seen in this picture, the width and height are around 300 pixels.

I would appreciate if you could explain how can I make this detection work with my datasets, or if that's not possible, help me have access to the **Krespy** dataset used in the tutorial.

**Comment by ontheway16** [comment]
Hello, how small your objects are? I have success with 20x50 30x40 30x30 etc sizes. But my samples have a greater contrast to background.

**Comment by hadi-ghnd** [comment]
Hi, my objects are almost the same size as you mentioned. Some of them are even up to 60x80 pixels. Can I ask you how did you set the sizes in **detectnet_network.prototxt** file?
Also the class names in my label files start with a capital letter (like "Vehicle"). But in creating the dataset in digits I typed all small letters (like "vehicle"). Is this ok?
thanks

**Comment by ontheway16** [comment]
I did not make anything special in prototxt other than arranging input image size. You may need to experiment with various image sizes since too large images may cause memory problems. I think in default config, detectnet can handle around 4megapixel images max. (Like a 5000x800 image) @12GB video ram.
Also dont forget to turn off data augmentation parameters (probabilities set to zero) and set both cropbboxes to false.

Finally, I think there is no difference between car and Car.
I may advise you to take a look to my Fiji plugin, specifically targets labeling of very large images.

https://alpslabel.wordpress.com/2017/03/20/alps-label-crop-tool/

**Comment by hadi-ghnd** [comment]
Thank you for the tips. So you mean I should just change the **input size image** and **data augmentation parameters** in prototxt and there is no need to change the **stride size** or the **filter sizes**.
I just have a question about resizing the images. Does it affect the size or location of bounding boxes as well? Or I shouldn't make any changes to the label files when I resize images in dataset creation on digits?
Also thanks a lot for the tool. I can really use it to crop my images of size about 5000x4000.

**Comment by hadi-ghnd** [comment]
I tried what you suggested on 2 different datasets, but unfortunately it still doesn't work. This is one of the datasets:

## images are like this:

![vedai](https://cloud.githubusercontent.com/assets/24352869/24138155/5c990ae6-0e2c-11e7-9c4a-399a1a66dc73.png)

They have a size of **1024x1024** pixels.

The labels for these pictures are like this:

> car 1.000000 0 0.0 554.000000 996.000000 607.000000 1021.000000 0.0 0.0 0.0 0.0 0.0 0.0 0.0 

## This is the customization made in "detectnet_network.prototxt" file: 

> -- all instances of **1248x348/352** changed to **1024**

> -- cropboxes all set to **false**

I have defined the classes as:

> dontcare,car
pad images: not set
resize images: 1024x1024

but it still doesn't work and the **mAP** and **recall** are always **zero**. What else should have I done in this case?

**Comment by ontheway16** [comment]
How many images and how many labeled objects total do you have in train and validation folders?

**Comment by hadi-ghnd** [comment]
I have 933 images in training folder and around 300 images in validation folder. I don't know the exact number of objects, but each image has among 1 and 15 objects.

**Comment by ontheway16** [comment]
If you have single class in label annotations I think there is no need to declare classes (dontcare, car).
Number of labels and images are good enough to train with an acceptable result.
Are you sure about integrity of label coordinates? After creating a new dataset, I am randomly checking some of the images with "labels to images" tool at above web site to be sure everything is in place.

**Comment by hadi-ghnd** [comment]
Actually I have checked the integrity of the coordinates for some of the images. I also tried the object detection on another dataset with larger objects and the same thing happened. The only dataset that digits object detection worked for me in the KITTI data. Any other dataset I tried, resulted in a constant zero for **mAP**.

**Comment by ontheway16** [comment]
I am assuming you have continued training at least 30 epochs since I encountered situations that mAP rises after 15 or 20 epochs. Above, your figure displays just 11 epochs. In zero mAP situations, I mostly found the error on custom dataset's itself. And please double check every single step in the object detection walkthrough.

**Comment by hadi-ghnd** [comment]
@ontheway16 thank you for your help. I let the training continue to 80 epochs and this is the result:

![screenshot from 2017-03-22 07-52-23](https://cloud.githubusercontent.com/assets/24352869/24180837/da5e7bfc-0ed4-11e7-8c3a-6d03cc3f5c9c.png)

I assume if you have dealt with small objects like this before. Could you tell me if there is something I can do to increase the **precision** to a better point? Because now it's very low (about 40%).
Can I change the network architecture or only **detectnet** works with digits?

**Comment by ontheway16** [comment]
Hello, from this point, the only thing I can offer is increasing the number of data. Your mAP value appears very low. As I said, I am working with small objects but my data contains clean background, I guess this increases accuracy greatly.

**Comment by hadi-ghnd** [comment]
I am going to try some data augmentation to see if it helps. Would you suggest anything to do with the detectNet structure and maybe try different types of networks, or that's not helpful?

**Comment by ontheway16** [comment]
I am afraid I cannot since I am not into deep learning, just a user of this system like you. Therefore cannot offer any model changes etc at the moment. I also tried yolov2, but against claims that yolo perform better, accuracy was higher with detectnet. Of course, your results may come out different with it, may worth to try.

**Comment by hadi-ghnd** [comment]
Thank you so much. Your suggestions helped a lot.

**Comment by sani1486** [comment]
@hadi-ghnd hi i am interested in some follow ups about your issue as i am working on similar datasets .did you manage to improve the accuracy rate ?
Thanks
