### ISSUE TITLE
Use Detectnet with Grayscale Images

### ISSUE THREAD

**Issue by user7077** [NVIDIA/DIGITS#1522]
Hello,
I am trying to detect objects in grayscale images. I managed to get everything running when I convert the images to RGB, but when I generate a Detection Dataset and use 'Channel conversion: Grayscale' I get an error in the file detectnet_transform_layer.cpp.

I have seen the following lines in this file: 
```c
// accept only three channel images:
  CHECK_EQ(bottom[0]->channels(), 3);
  // accept only equal numbers of labels and images:
  CHECK_EQ(bottom[0]->num(), bottom[1]->num());
  // resize mean image if it exists:
  if (t_param_.has_mean_file()) {
    size_t image_x = bottom[0]->width();
    size_t image_y = bottom[0]->height();
    retrieveMeanImage(Size(image_x, image_y));
  }
  // resize image output layer: (never changes /wrt input blobs)
  top[0]->Reshape(
      bottom[0]->num(),
      bottom[0]->channels(),
      g_param_.image_size_y(),
      g_param_.image_size_x());
  // resize tensor output layer: (never changes /wrt input blobs)
  Vec3i tensorDimensions = coverage_->dimensions();
  top[1]->Reshape(
      bottom[1]->num(),
      tensorDimensions(0),
      tensorDimensions(1),
      tensorDimensions(2));
```

Here it says that only three channel images are accepted. I guess that I could speed up training substantially when using grayscale images. Does anyone have experience in adapting Detectnet to work with Grayscale images? 

Thanks for your help!

**Comment by lukeyeager** [comment]
I don't think anyone at NVIDIA has tried to train DetectNet with NVcaffe on grayscale images, no. I can't think of any particular reason it should be difficult, though. Go for it! Feel free to share your work if you get it working.

**Comment by ShervinAr** [comment]
@user7077  Hello, have you figured out how to configure detectnet to work on gray scale images yet?
