### ISSUE TITLE
Problem with object detection on custom data

### ISSUE THREAD

**Issue by hadi-ghnd** [NVIDIA/DIGITS#1524]
I'm trying to perform object detection on a set of aerial images, but the result is like below:

![screenshot from 2017-03-20 21-17-01](https://cloud.githubusercontent.com/assets/24352869/24113632/aaa30054-0db2-11e7-8152-24b599a9830c.png)

However on [this](https://devblogs.nvidia.com/parallelforall/detectnet-deep-neural-network-object-detection-digits/) and [this](https://devblogs.nvidia.com/parallelforall/deep-learning-object-detection-digits/) pages, the example is about vehicle detection in aerial images (exactly my case) and it seems to be working. 
In my dataset, images are like this:

![vedai](https://cloud.githubusercontent.com/assets/24352869/24138155/5c990ae6-0e2c-11e7-9c4a-399a1a66dc73.png)

They have a size of **1024x1024** pixels.

The labels for these pictures are like this:

`car 1.000000 0 0.0 554.000000 996.000000 607.000000 1021.000000 0.0 0.0 0.0 0.0 0.0 0.0 0.0 `

This is the customization made in "detectnet_network.prototxt" file: 

all instances of **1248x348/352** changed to **1024**
cropboxes all set to **false**

I have defined the classes as:   `dontcare,car`
pad images: **not set**
resize images: **1024x1024**

but it still doesn't work and the **mAP** and **recall** are always **zero**. What else should have I done in this case?

**Comment by ontheway16** [comment]
@hadi-ghnd , try following:
On dataset preparation, under Object Detection Dataset Options;

Pad Image: 1024 x 1024
Resize: (Keep it empty, reads width and height text in it.
Minimum box size (in pixels) for validation set:  0
