### ISSUE TITLE
DIGITS 5 failed to install on Ubuntu 16.04 

### ISSUE THREAD

**Issue by aprentis** [NVIDIA/DIGITS#1532]
Hi everybody! 

I`m trying to install DIGITS 5 for CUDA 8 on Ubuntu 16.04 with TITAN X Pascal Onboard. 
Driver Version is 375.39
![screenshot from 2017-03-24 15-28-27](https://cloud.githubusercontent.com/assets/17255184/24294325/0279ec42-10a7-11e7-8c93-a11253a5774a.png)
![screenshot from 2017-03-24 15-30-15](https://cloud.githubusercontent.com/assets/17255184/24294329/05b69f2c-10a7-11e7-86a3-2d9aba6aa667.png)

i`ve followed  instructions at this page(https://developer.nvidia.com/rdp/digits-download). 

I`ve downloaded this file
nv-deep-learning-repo-ubuntu1604-ga-cuda8.0-digits5.0_1-1_amd64.deb

Then i`ve run apt-get update and got this: 

W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/_var_nv-deep-learning-repo-ga-cuda8.0-digits5.0_Release

Could you help me with this? 

This link appears to tell about similar problem. Is there any Desicion? 
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1649086

**Comment by howtocodewang** [comment]
You might ignore this warning since it won't make your installing fail.

**Comment by shanYanGuan** [comment]
you should follow this guide:https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md.
offcial instruction is adapted for ubuntu14.04.

**Comment by lukeyeager** [comment]
Yep, we're aware of the packaging snafu. It's just a warning - you can ignore it. It will be fixed for future packages.

**Comment by manacoa** [comment]
I'm having the same issue, but continuing does NOT help. Here's what I see:

```
$ sudo apt-get update
Get:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Ign:1 file:/var/cuda-repo-8-0-local-ga2  InRelease
Get:2 file:/var/nv-deep-learning-repo-ga-cuda8.0-digits5.0  InRelease
Ign:2 file:/var/nv-deep-learning-repo-ga-cuda8.0-digits5.0  InRelease
Get:3 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Get:4 file:/var/nv-deep-learning-repo-ga-cuda8.0-digits5.0  Release [574 B]
Get:3 file:/var/cuda-repo-8-0-local-ga2  Release [574 B]
Get:4 file:/var/nv-deep-learning-repo-ga-cuda8.0-digits5.0  Release [574 B]
Hit:7 http://gb.archive.ubuntu.com/ubuntu xenial InRelease                     
Hit:8 http://gb.archive.ubuntu.com/ubuntu xenial-updates InRelease             
Hit:9 http://gb.archive.ubuntu.com/ubuntu xenial-backports InRelease           
Hit:10 http://security.ubuntu.com/ubuntu xenial-security InRelease             
Reading package lists... Done                     
W: Invalid 'Date' entry in Release file /var/lib/apt/lists/_var_nv-deep-learning-repo-ga-cuda8.0-digits5.0_Release
```
then

```
sudo apt-get install DIGITS
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package DIGITS
```

Ubuntu 16.04, x86_64
CUDA 8.0 already installed
nVidia GeForce 1080Ti

Thanks

Simon

**Comment by lukeyeager** [comment]
Lower case
