### ISSUE TITLE
Failed to connect to nvidia digit

### ISSUE THREAD

**Issue by d4baggs** [NVIDIA/DIGITS#1537]
I remove digit installation by doing  sudo apt-get --purge remove digits because its failed to connect to the server. Then install it again. But it seems that the problem still occur.
When I type sudo stop nvidia-digits-server  
![image](https://cloud.githubusercontent.com/assets/26714819/24358230/176a55c2-1333-11e7-9617-efebac0dfbe8.png)

Does anyone have idea how to solve this issue??

**Comment by lukeyeager** [comment]
My bet is you probably just aren't connecting to the server properly. If DIGITS says it's running on `0.0.0.0`, that just means it's listening on all addresses. You still need to access the server using your hostname or IP address, like `http://my-machine/` or `http://12.23.34.45`, for example.

**Comment by d4baggs** [comment]
this is what I got when type ./digits-server
![image](https://cloud.githubusercontent.com/assets/26714819/24368932/f7a1c0aa-1354-11e7-89cf-42409a531a90.png)

**Comment by lukeyeager** [comment]
I see. Yet another case of somebody trying to mix `conda`, `pip` and deb packages.

Please follow our install instructions exactly. Anytime you're using `conda`, you've diverged from the instructions and you're on your own to figure it out.
