### ISSUE TITLE
image segmentation using Digits 5

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1544]
Hello,

I want to do the segmentation task, but with my own custom images and dataset. May I ask you how should I label them (what format) or what are the terms and conditions to do this?

**Comment by gheinrich** [comment]
Hello, you can format your data in PASCAL VOC format, also briefly described on https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/semantic-segmentation#downloading-and-preparing-the-pascal-voc-data.

**Comment by VanitarNordic** [comment]
@gheinrich 

You mean I should annotate them in VOC xml?, if I am right.

**Comment by gheinrich** [comment]
Please read this carefully:
https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/semantic-segmentation#downloading-and-preparing-the-pascal-voc-data

**Comment by VanitarNordic** [comment]
Okay, Thanks. Just I have another quite question and then I will close this. 
Assume we have a classification task, it is possible that the classification output offers the quantity and confidence of all the classified objects?

For example assume that our class is Apple. Then we test the classifier with an image which contains two or more apples. How the classifier gives an output like this?

apple: 98%
apple: 95%
.
.
.
and so on.
is there any possibility to this task with classifier, or I should do it with detection or segmentation?

**Comment by S4WRXTTCS** [comment]
For segmentation I would highly suggest using this labeling tool.

https://alpslabel.wordpress.com/2017/03/28/alps-image-segmentation-tool-aims/

It makes things so much easier than trying to use GIMP (or some similar program) to manually create the label files.

**Comment by gheinrich** [comment]
@VanitarNordic have a look at this article:
https://devblogs.nvidia.com/parallelforall/image-segmentation-using-digits-5/
This should hopefully clear things up.

**Comment by VanitarNordic** [comment]
@S4WRXTTCS 

Generally I don't know what should be inside the label file, I mean the formatting. It is mentioned it should be the VOC format, but I just know the VOC format in detection, not segmentation. Would you please clear me up?

**Comment by VanitarNordic** [comment]
@gheinrich 

Why you have decided to make a separation for training and validation using `prepare_pascal_voc.sh` ?

Why not do it in Digits GUI as it is adjusted to 10% for validation set as default?

![dataset-form](https://cloud.githubusercontent.com/assets/18719591/24496038/679afb4e-154c-11e7-8281-8069f596b41d.png)

**Comment by S4WRXTTCS** [comment]
@VanitarNordic 

I'm not sure if I'm really the right person to clear up any confusion.

Personally I ignore the names like PASCAL VOC format (for segmentation) or KITTI (for detection), and I just concentrate on what's expected with either segmentation or detection. 

With Segmentation I think it's important to simplify it down to a single case where you have a feature image file, and a label image file. Where the label file is a PNG 8-bit paletted image of the same size as the feature image file. If you load any of the PASCAL VOC label files you'll notice the colors used in the image equal the number of objects in the image + 2 (the ignored borders and the background).

It might help if you understand how to manually create them. 

https://groups.google.com/forum/#!topic/digits-users/4DDVZeXjfdw

**Comment by VanitarNordic** [comment]
@S4WRXTTCS 

Hello again.
I have some PNG labels, but I get error because of the PNG color values. you mentioned they must be PNG-8 bit pallet. is there any tool to make a conversion or test?

**Comment by ontheway16** [comment]
@VanitarNordic 
Hi, if you have Fiji installed, open png label file and check for image type; As following;

![palette](https://cloud.githubusercontent.com/assets/23200711/25837013/7d8db96a-348b-11e7-88c7-de06c0b1eb09.jpg)
