### ISSUE TITLE
Does it support HDF5 dataset for segmentation task?

### ISSUE THREAD

**Issue by mjohn123** [NVIDIA/DIGITS#1548]
Hello, I have a hdf5 list that store hdf5 path as follows:

```
/home/user/file1.h5
/home/user/file2.h5
...
```
The file name is filelist.txt. I want to use DIGITS for segmentation task with and my data layer is hdf5 layer as follows

```
layer {
  name: "data"
  type: "HDF5Data"
  top: "data"
  top: "label"
  hdf5_data_param {
    source: "./filelist.txt"
    batch_size: 2
    shuffle: true
  }
}
```
Can I use above layer in current DIGITS for segmentation task with caffe?

**Comment by gheinrich** [comment]
Sorry, HDF5 is only supported for classification tasks. You can write a plug-in to ingest your HDF5 data into a segmentation dataset. Have a look at some examples on https://github.com/NVIDIA/DIGITS/tree/digits-5.0/plugins/data

**Comment by mjohn123** [comment]
Thanks. So I think I will run caffe from terminal. One benefit of DIGITS that I like is that it show the graph of epoch, instead of iterations in caffe.
