### ISSUE TITLE
Train caffe mode percentage stuck at 0% and no Estimated time remaining. 

### ISSUE THREAD

**Issue by WeiyiLi** [NVIDIA/DIGITS#1556]
Hi,
I am studying using DIGITS to do semantic segmentation. I refer the example provided in https://github.com/NVIDIA/DIGITS/tree/master/examples/semantic-segmentation. After I start training, the Job Status on training page becomes like below:

![selection_005](https://cloud.githubusercontent.com/assets/6508944/24624187/dd74a8a4-185f-11e7-930f-d70312b8d813.png)

It is stuck at 0% for a while and no estimated time remaining. BTW, I am using CPU-only mode. 

Anyone has any ideas about this issue? Thanks!

**Comment by lukeyeager** [comment]
> BTW, I am using CPU-only mode.

Yep, I'd expect that to be super slow. DIGITS can't make a prediction about when the job will finish until Caffe prints out its first update. You can run `top` on the system to make sure Caffe is still running.
