### ISSUE TITLE
FCN Alexnet Semantic Segmentation training Error

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1557]
Hello,

I decided to train the FCN Alexnet on a custom dataset with two classes: background and class0
I downloaded the FCN Alexnet `.caffemodel` from here: https://github.com/shelhamer/fcn.berkeleyvision.org/tree/master/voc-fcn-alexnet
I have also used this `.prototxt` and modified it to be used for two classes and two groups (21 to 2): https://github.com/NVIDIA/DIGITS/blob/digits-5.0/examples/semantic-segmentation/fcn_alexnet.deploy.prototxt

batch size = 1

I get this error:

![screenshot from 2017-04-04 02-40-05](https://cloud.githubusercontent.com/assets/18719591/24633956/955f96ce-18e0-11e7-8bb1-8b03c8eb37a6.png)

**Comment by RSly** [comment]
@VanitarNordic you should take a look at the caffe_output.log for a better error information

**Comment by VanitarNordic** [comment]
@RSly 

I did before but it gives no clue for me, I appreciate if you have a look.

![screenshot from 2017-04-04 12-47-41](https://cloud.githubusercontent.com/assets/18719591/24647402/fea13fda-1934-11e7-913e-217a4f0cae9f.png)

This is the system information either (Ubuntu 16.04)

![screenshot from 2017-04-04 12-44-20](https://cloud.githubusercontent.com/assets/18719591/24647313/a9d8deb8-1934-11e7-9390-94cda50ae96d.png)

**Comment by VanitarNordic** [comment]
Alright, the problem was that I was using the FCN `.caffemodel` before running the net_surgery on it. Actually the FCN models at BVLC are **not** available for training directly as I was thinking.

The model trains successfully by modifying the `fcn_alexnet.prototxt` for two classes, **BUT** it does not work by modifying the `fcn_alexnet.deploy.prototxt` as it should handle better results. it drops the below error:

![screenshot from 2017-04-04 23-06-53](https://cloud.githubusercontent.com/assets/18719591/24672897/930dc430-198b-11e7-9e0c-a2f2209e3a9b.png)

**Comment by gheinrich** [comment]
It seems hardly appropriate to name your layer `score_fr_21_classes` if it's only classifying two classes, right?

**Comment by VanitarNordic** [comment]
That's right, I have modified it for two classes, but I don't understand that problem rises with just `fcn_alexnet.deploy.prototxt`.

**Comment by gheinrich** [comment]
The error states "to learn this layer's parameters from scratch rather than copying from a saved net, rename the layer". I can't see how it could be any more explicit than that... I suggest you rename the layer in the prototxt you provide to DIGITS and the error will disappear.

**Comment by VanitarNordic** [comment]
Alright, one question remains:

There are some FCN models here: https://github.com/shelhamer/fcn.berkeleyvision.org
Should I perform any specific operation on these before I could be able to use them as pre-trained model?

**Comment by gheinrich** [comment]
The pre-trained FCN-Alexnet and FCN-8s from https://github.com/shelhamer/fcn.berkeleyvision.org have already had net surgery done so I was able to use them as is. For the other ones, I can't say.

**Comment by VanitarNordic** [comment]
Thank you. by renaming and adding two missing layers to `deploy.prototxt `my issue has been solved. Thumbs up.

```
layer {
  name: "loss"
  type: "SoftmaxWithLoss"
  bottom: "score"
  bottom: "label"
  top: "loss"
  loss_param {
    ignore_label: 255
    normalize: true
  }
  exclude {
    stage: "deploy"
  }
}
layer {
  name: "accuracy"
  type: "Accuracy"
  bottom: "score"
  bottom: "label"
  top: "accuracy"
  include { stage: "val" }
  accuracy_param { ignore_label: 255 }
}
```
