### ISSUE TITLE
FCN-8s weird out of memory Error

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1558]
Hello,

I tried to use FCN-8s with a custom VOC dataset with two classes (background and class1), but it fails.
I have downloaded the `.caffemodel` from here: http://dl.caffe.berkeleyvision.org/fcn8s-heavy-pascal.caffemodel

and used the `.prototxt` file by @gheinrich in Google Group and changed the number of outputs from 12 to 2: https://groups.google.com/forum/#!topic/digits-users/0UF-xD-yGuY

and also tried to use `accuracy_param { ignore_label: 255 }` trick, but none helped. I use batch size =1
GPU is a GTX 1060 with 6G memory. dataset contains 202 training and 36 validation images.

![screenshot from 2017-04-04 03-30-32](https://cloud.githubusercontent.com/assets/18719591/24635325/017ccfc8-18e8-11e7-8b4f-6627192936c7.png)

**I reduced the number of training images from 202 to 126 but again the same error!**

![screenshot from 2017-04-04 11-56-53](https://cloud.githubusercontent.com/assets/18719591/24645608/13e934b2-192e-11e7-810e-1fa28a1b6930.png)

**Comment by VanitarNordic** [comment]
I do not have this problem with FCN Alexnet

**Comment by gheinrich** [comment]
FCN-8s requires more memory.

**Comment by VanitarNordic** [comment]
Yess, you are right, by reducing the training images resolution, finally out of memory error disappeared and started training although on edge. it is a quite heavy network.

I have some question. I appreciate if you have consider sir.

1) Which affects the memory consumption in Segmentation tasks (or maybe detection and classification), quantity of the training images or their size (resolution)?

2) I trained the dataset on FCN-8s till 22 epoches, but the Dice (val) did not move above 0.69 . What could be the reason of that?
I see that the model behaves better that AlexNet, but dice is low (maybe almost the same as AlexNet). I used your tips already such as adding this layer:
```
layer {
  name: "score_2classes"
  type: "Convolution"
  bottom: "score"
  top: "score_2classes"
  convolution_param {
    num_output: 2
    pad: 0
    kernel_size: 1
  }
} 
```

![screenshot from 2017-04-06 00-08-10](https://cloud.githubusercontent.com/assets/18719591/24723540/3a0d1a5c-1a5d-11e7-9c46-ca653504eef3.png)

**Comment by VanitarNordic** [comment]
@gheinrich 

Yes, thank you. you are right, by reducing the training images resolution, finally out of memory error disappeared and started training although it operates on edge (most of the time 97% of memory is filled). it is a quite heavy network.

I have some important questions. I appreciate if you consider them also sir.

1) Which affects the memory consumption in Segmentation tasks (or maybe detection and classification), quantity of the training images or their size (resolution)?

2) Will adding only background images increase accuracy or other parameters? 
also I realized that `dice.py` will crash by division by zero exception when I include background only images

3) Do FCN-8S or FCn-AlexNet capable of segmenting small objects if they exist inside training images(for example 20*20 object?

4) When we want to conclude the training, should we pick the result of the latest epoch (for example 30th) or the epoch which handles the best results?

**Comment by gheinrich** [comment]
Closing issue. Those questions are better asked on mailing lists.

**Comment by VanitarNordic** [comment]
@gheinrich 

Alright, I posted the question in the Google group, please have a look. 

but the crash of `dice.py` in presence of bakcground-only images could be a bug (subdivision by zero exception)
