### ISSUE TITLE
how to disable cudnn?

### ISSUE THREAD

**Issue by tangshi** [NVIDIA/DIGITS#157]
When I ran the sample (mnist), I got an error: `ERROR: Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0) CUDNN_STATUS_ARCH_MISMATCH`.

Seems like my GPU is not supported by `cudnn`,  so how to disable cudnn?

The detail message of error: 

```
mnist -> label
Setting up mnist
Opened lmdb /home/tangshi/.digits/jobs/20150624-210634-ce54/train_db
Decoding Datum
output data size: 64,1,28,28
Loading mean file from: /home/tangshi/.digits/jobs/20150624-210634-ce54/mean.binaryproto
Top shape: 64 1 28 28 (50176)
Top shape: 64 (64)
Creating layer scale
Creating Layer scale
scale <- data
scale -> scale
Setting up scale
Top shape: 64 1 28 28 (50176)
Creating layer conv1
Creating Layer conv1
conv1 <- scale
conv1 -> conv1
Setting up conv1
Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
```

**Comment by lukeyeager** [comment]
> how to disable cudnn?

Comment out [this line](https://github.com/NVIDIA/caffe/blob/v0.11.1/Makefile.config.example#L5) in Makefile.config when you build caffe.

**Comment by tangshi** [comment]
Yes, I modified the Makefile.config and rebuilt caffe, but the error appeared again.

I found that  the capability of my GPU(Geforce GTX 260) was only 1.2, and caffe recommends users to use GPU with capacity >= 3.0. Devices with capability <= 2.0 may have to reduce CUDA thread numbers and batch sizes due to hardware constraints.  I reduced them but it made no sense.

Time to upgrade my device 😂

Thank you @lukeyeager

**Comment by moconnor725** [comment]
Yeah, CUDA support <=2.0 is a challenge.  Caffe doesn't even build with support for pre-2.0 by default.  See [these lines](https://github.com/NVIDIA/caffe/blob/v0.11.1/Makefile.config.example#L22-L27)

Until your new NVIDIA GPU arrives :-), turn on CPU_ONLY by uncommenting [this line](https://github.com/NVIDIA/caffe/blob/v0.11.1/Makefile.config.example#L8)
