### ISSUE TITLE
ERROR: Top blob 'data' produced by multiple sources

### ISSUE THREAD

**Issue by Shahnawazgrewal** [NVIDIA/DIGITS#1572]
I have six channel image (2 RGB image concatenated). I want to train the model with these images using AlexNet. I packed the images into lmdb. Then I used the OTHER option for dataset and model, however I am getting the following error when I am creating the model .

```
ERROR: Top blob 'data' produced by multiple sources. 
Creating layer train-data
Creating Layer train-data
Top blob 'data' produced by multiple sources.
Opened lmdb /multimodal-with-embedding/lmdb_database/train_labels
```
I am using [standard AlexNet architecture.](https://github.com/NVIDIA/DIGITS/blob/v4.0.0-rc.3/digits/standard-networks/caffe/alexnet.prototxt)

**My understanding of the error**
I believe the AlexNet assume that the two are coming from both train and val. Can someone explain to me how to use multiple input.

**Comment by lukeyeager** [comment]
Check out this popup for an explanation of how to filter layers: https://github.com/NVIDIA/DIGITS/pull/628#issuecomment-195137527

If you can't figure it out, paste the definition of the generated data layers for your train/val network and I'll point out the issue to you.

**Comment by Shahnawazgrewal** [comment]
I read out these instructions and removed the `TRAIN `and `VAL` phase then `DIGIT` by default include all three phases i.e. `TRAIN, VAL` and `DEPLOY`. I am able to resolve the error however I didn't get the good results in terms of accuracy.
One interesting result that I obtained is that I have same accuracy value by using an AlexNet on multi input (2 images or 6 channel).  Other network consist of two identical AlexNets processing each image and then using a `conc ` layer.

**Comment by laghai** [comment]
I'm having the same problem with DIGITS 6 and it appears the layers are as per instructions. Here's the top portion of generated layers:
layer {
  name: "train-data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: true
    crop_size: 227
  }
  data_param {
    source: "/jobs/20170926-032526-f969/train_db/features"
    batch_size: 5
    backend: LMDB
  }
}
layer {
  name: "train-data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  transform_param {
    mirror: true
    crop_size: 227
  }
  data_param {
    source: "/jobs/20170926-032526-f969/train_db/labels"
    batch_size: 5
    backend: LMDB
  }
}
layer {
  name: "val-data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  transform_param {
    crop_size: 227
  }
  data_param {
    source: "/jobs/20170926-032526-f969/val_db/features"
    batch_size: 5
    backend: LMDB
  }
}
layer {
  name: "val-data"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TEST
  }
  transform_param {
    crop_size: 227
  }
  data_param {
    source: "/jobs/20170926-032526-f969/val_db/labels"
    batch_size: 5
    backend: LMDB
  }
}

**Comment by MiralPatel3011** [comment]
I want to detect road network from satellite images. i download dataset from Kaggle which was manchesett road dataset for road network detection.  I want to train the model with these images using AlexNet. My dataset successfully uploaded in DIGITS and it display datasets information as under:

Dataset
road_segmenataion1
Done 09:24:06 AM
DB backend: lmdb
Create train_db DB
Entry Count: 724
Feature shape (3, 1500, 1500)
Label shape (1, 1500, 1500)
Create val_db DB
Entry Count: 80
Feature shape (3, 1500, 1500)
Label shape (1, 1500, 1500)

But when i trained the  segmentation model in DIGITS then within 3 s it gives following error:

ERROR: Top blob 'data' produced by multiple sources. 
Creating layer train-data
Creating Layer train-data
Top blob 'data' produced by multiple sources.
Opened lmdb /jobs/20201231-092027-c6cd/train_db/labels

As i am new user and little bit information about DIGIT. So please guide me where i am wrong.

Thanking you in advance
