### ISSUE TITLE
Torch binary not found

### ISSUE THREAD

**Issue by gismo07** [NVIDIA/DIGITS#1576]
I installed digits 5.0.0, caffe and torch 7. Everything except torch is working. 
For installing torch i followed this tutorial: [Building Torch](https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildTorch.md) from the digits tutorials.

under /var/log/digits/digits.log I can see this error message:

> Default value for torch_root "<PATHS>" invalid:
	torch binary not found in PATH

I have already set the following path variables:
`export CAFFE_ROOT=~/caffe`
`export TORCH_ROOT=~/torch`

The torch executable is located under:
`~/torch/install/bin`

How can i fix this issue?

**Comment by lukeyeager** [comment]
If you're looking at a log file in `/var/log/digits/digits.log`, then you probably used a deb package to install. But if you followed the "BuildTorch" tutorial, then you're also building something from source. Why are you mixing the two?

For deb package installs, here's the info you need:
https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md#configuration

**Comment by gismo07** [comment]
Thank you for your help!
Especially the configuration page was very useful.

I followed the BuildTorch tutorial as there is mentioned: 

> These instructions are based on the official Torch instructions.

So i thought it would be better to follow this tutorial instead of the official torch guide.

But setting the `TORCH_ROOT` variable resolved the problem.
