### ISSUE TITLE
Check failed: proto.SerializeToOstream(&output) 

### ISSUE THREAD

**Issue by kjw218** [NVIDIA/DIGITS#158]
Hello, I'm newbie of vision area
I'd like to Image training on Caffe (using my data)
but when I try to run make_imagenet_mean.sh file
I got an error
would you help me kindly?
 

this is the error message
------------------------------------------------------------------------------------------------------------------
F0703 09:53:03.039291  3732 io.cpp:67] Check failed: proto.SerializeToOstream(&output) 
*** Check failure stack trace: ***
    @     0x7f114c9a6daa  (unknown)
    @     0x7f114c9a6ce4  (unknown)
    @     0x7f114c9a66e6  (unknown)
    @     0x7f114c9a9687  (unknown)
    @     0x7f114cd1248c  caffe::WriteProtoToBinaryFile()
    @           0x402088  main
    @     0x7f114bbb6ec5  (unknown)
    @           0x40240a  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)
Done.
------------------------------------------------------------------------------------------------------------------------

I refer to this.
https://github.com/BVLC/caffe/tree/master/examples/imagenet

and I modify ~/cafe/data/ilsvrc12/train.txt, val.txt, 
like this.. 

train.txt
---------------------------------
n01440764/HYIcicleM.jpg 0
n01440764/HYIcicleM1.jpg 0
n01440764/HYIcicleM2.jpg 0
n01440764/HYIcicleM3.jpg 0
n01440764/HYIcicleM4.jpg 0
n01440764/HYIcicleM5.jpg 0
...
----------------------------------------------------

val.txt
-----------------------------------------------------------
HYIcicleM.jpg 0
HYIcicleM1.jpg 0
HY4OclockB.jpg 1
HY4OclockB1.jpg 1
HY4OclockB2.jpg 1
HY4OclockB(copy)9.jpg 2
HY4OclockB(copy)10.jpg 2
...
----------------------------------------------------------

thank you!

**Comment by lukeyeager** [comment]
Duplicate of #84.

**Comment by HeddaZhu** [comment]
I have the same bug, did anyone solved it?
I saw the answer：
1. Solution is to modify src/caffe/layers/data_layer.cpp by setting options.max_open_files = 100 (or any number significantly lower than 1000)
2. your disk is full
try to see the state of your disk by "df -a"

These answers are not suitable for me.

**Comment by lukeyeager** [comment]
@HeddaZhu can you provide a list of steps to reproduce the problem? Or does it happen randomly like it does to everyone else?

**Comment by Lakung** [comment]
i've met the same problem, but i think it's your disk is full. solved the problem by preparing more free space.
