### ISSUE TITLE
Error "caffe.LayerParameter" has no field named "crop_param". for DIGITS segmentation

### ISSUE THREAD

**Issue by qians17** [NVIDIA/DIGITS#1581]
Hi 

I want to implement segmentation and SunnyBrook LV segmentation on DIGITS 5.1. However, when I try to implement the fcn_alexnet on the custom network, it will have an error listed below:
ParseError 310:3 : Message type "caffe.LayerParameter" has no field named "crop_param".

I notice that this may be an error cause by a low version of caffe. I download it from https://github.com/NVIDIA/caffe and run the command:
cp Makefile.config.example Makefile.config
make all
make test
make runtest

However, the error still remains and the caffe version displayed on DIGITS is 0.14.5. Could anyone please tell me how to fix this problem? Which step I was wrong to upgrade caffe 0.15? Is there any command for updating the caffe if DIGITS was installed before?

Thanks,
Songyue

**Comment by lukeyeager** [comment]
You'll need to reconfigure DIGITS to use the new Caffe build. For DIGITS 5 this is done with environment variables:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/Configuration.md#environment-variables

We recommend installing pre-built packages through `apt-get` or pre-built images through `docker`, especially for those who aren't very comfortable with Linux. Check the readme for details.
