### ISSUE TITLE
Train Caffe Model task failed with error code -6

### ISSUE THREAD

**Issue by Xoppop** [NVIDIA/DIGITS#1584]
Hi. 
I assembled a new system, installed CUDA 8, Digits 5.
I tried to train the model DetectNet. I got the following result:
[ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
[ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
[ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
[ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
[ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
Train Caffe Model: Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
[ERROR] Train Caffe Model task failed with error code -6

I have not found a solution to this problem, tell me what the problem may be
```
nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.51                 Driver Version: 375.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro 2000         Off  | 0000:0F:00.0      On |                  N/A |
| 30%   37C   P12    N/A /  N/A |    105MiB /   963MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0       779    G   /usr/lib/xorg/Xorg                              89MiB |
|    0       904    C   /usr/bin/python                                 14MiB |
+-----------------------------------------------------------------------------+

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

echo $LD_LIBRARY_PATH
/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/lib64
```

**Comment by lukeyeager** [comment]
Are you using cuDNN v6? https://github.com/NVIDIA/caffe/issues/306

**Comment by Xoppop** [comment]
CuDNN v5 installed
ii  libcudnn5                     5.1.10-1+cuda8.0                           amd64        cuDNN runtime libraries

**Comment by Xoppop** [comment]
CuDNN v5 installed
ii  libcudnn5                     5.1.10-1+cuda8.0                           amd64        cuDNN runtime libraries

**Comment by lukeyeager** [comment]
Ah. `Quadro 2000` is a Fermi board (compute capability 2.1). To use cuDNN, you need a GPU with at least compute capability 3.0.
https://en.wikipedia.org/wiki/CUDA#GPUs_supported
http://stackoverflow.com/a/33760325/2404152
