### ISSUE TITLE
Check failed: result == ncclSuccess (1 vs. 0)  unhandled cuda error

### ISSUE THREAD

**Issue by mrgloom** [NVIDIA/DIGITS#1586]
I try to use last caffe master (commit eeebdab16155d34ff8f5f42137da7df4d1c7eab0) build with NCCL:

Images are 32x32 3 channel, batch size is 1.
GPU: Tesla M2090

It works with single GPU, but when I use more it crashes with non informative error:  `Check failed: result == ncclSuccess (1 vs. 0)  unhandled cuda error`.

**Comment by mrgloom** [comment]
Switching to commit `2317fa19d3f5a65cb22adcbd3792ea248996744e`, before https://github.com/BVLC/caffe/commit/3ba20549b7f49a76cd023d19f781a6891b2c2122 helped, now multi gpu training work.

**Comment by vennelakanti1997** [comment]
I have faced the same error. Check if your nccl version is compatible with your cuda version(I too do not know how to check the version of nccl. But I have cuda10.0 installed and nccl which is compatible with 10.1). Try reinstalling the nccl version which is compatrible with your cuda version
