### ISSUE TITLE
How to add pycaffe after installing caffe with dpkg?

### ISSUE THREAD

**Issue by materdd** [NVIDIA/DIGITS#1588]
I installed caffe and digits about one year ago by using below command. And I'd like to use pycaffe. How
could I install pycaffe? Do I need to re-install?
```
CUDA_REPO_PKG=cuda-repo-ubuntu1404_7.5-18_amd64.deb &&
    wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/$CUDA_REPO_PKG &&
    sudo dpkg -i $CUDA_REPO_PKG

ML_REPO_PKG=nvidia-machine-learning-repo_4.0-2_amd64.deb &&
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/$ML_REPO_PKG &&
    sudo dpkg -i $ML_REPO_PKG
```

**Comment by lukeyeager** [comment]
Those commands (from [UbuntuInstall.md](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md)) don't actually install any libraries - they're just meta-packages for our repositories.

This command will tell you whether you already have the `python-caffe-nv` deb package installed or not:
```sh
$ apt-cache policy python-caffe-nv 
python-caffe-nv:
  Installed: 0.15.13-1ubuntu16.04+cuda8.0
  Candidate: 0.15.13-1ubuntu16.04+cuda8.0
  Version table:
 *** 0.15.13-1ubuntu16.04+cuda8.0 500
        500 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Packages
        100 /var/lib/dpkg/status
```
If it's not installed, you can install it with `apt-get install python-caffe-nv`.

**Comment by materdd** [comment]
Thank you for your reply.
I checked it and python-caffe-nv has already been installed. And the cause of this problem is my mistake of pyenv path. It is a careless mistake!!

![image](https://cloud.githubusercontent.com/assets/27740131/25153951/cd607138-248e-11e7-886c-e77f12cd5632.png)
