### ISSUE TITLE
python no module called caffe_pb2

### ISSUE THREAD

**Issue by gismo07** [NVIDIA/DIGITS#1595]
I started working with some custom lmdb databases and used https://github.com/NVIDIA/DIGITS/blob/digits-5.0/examples/siamese/create_db.py as a starting point. 

Unfortunately even the imports are not working out of the box.

I had to change this line:

```python
import caffe_pb2 as caffe_pb2
```

to:

```python
import caffe.proto.caffe_pb2 as caffe_pb2
```

Is this the right way, or is something wrong with my caffe installation?

**Comment by lukeyeager** [comment]
When you import `digits.config`, it should set up your path so that you can import `caffe2_pb2` directly. See this code+comment:
https://github.com/NVIDIA/DIGITS/blob/v5.0.0/digits/config/caffe.py#L128-L130
