### ISSUE TITLE
AssertionError when using VGG-net-16

### ISSUE THREAD

**Issue by jmozah** [NVIDIA/DIGITS#160]
Hi

I created a custom network and used the VGG-net-16 layers... 
Digits says "AssertionError: must specify a loss layer" and bails out...

**Comment by lukeyeager** [comment]
Do you need to upgrade your prototxt? See https://github.com/NVIDIA/DIGITS/issues/39.

**Comment by lukeyeager** [comment]
@jmozah, did you solve your problem? I'm closing this issue. Please re-open it if you have more questions.
