### ISSUE TITLE
Trying to run AlexNet or GoogLeNet with Caffe and Digits 5 cropped to 32x32 on CIFAR10 crashes with SIGFPE

### ISSUE THREAD

**Issue by jwatte** [NVIDIA/DIGITS#1606]
Using the DIGITS4 AMI on Amazon, having upgraded it to cuda 8 and digits 5 (and rebooted for good measure,) I can train the LeNet digit recognition dataset, but the CIFAR10 data set at 32x32 color fails on both the AlexNet and GoogLeNet nets. (I edit the networks and change the "crop" values to be 32)

The problem is a SIGFPE, and it happens after some number of layers have been done. There is no useful stack trace, presumably the binaries are stripped?

To reproduce, set up the machine as per above (with a Tegra K80 GPU, 64 GB of RAM, 8 cores) and download the CIFAR10 data set using the Python script and process/import it using the DIGITS web app.
Then try to create a AlexNet or GoogLeNet model, editing the crop sizes of those models to 32 and start training. (Full settings are in the log below.)

here's the caffe_output.log file:

libdc1394 error: Failed to initialize libdc1394
I0428 02:41:18.867152  2429 upgrade_proto.cpp:1044] Attempting to upgrade input file specified using deprecated 'solver_type' field (enum)': /var/lib/digits/jobs/20170428-024117-870a/solver.prototxt
I0428 02:41:18.867419  2429 upgrade_proto.cpp:1051] Successfully upgraded file specified using deprecated 'solver_type' field (enum) to 'type' field (string).
W0428 02:41:18.867427  2429 upgrade_proto.cpp:1053] Note that future Caffe releases will only support 'type' field (string) for a solver's type.
I0428 02:41:18.998275  2429 caffe.cpp:197] Using GPUs 0
I0428 02:41:18.998476  2429 caffe.cpp:202] GPU 0: Tesla K80
I0428 02:41:19.314980  2429 solver.cpp:48] Initializing solver from parameters:
test_iter: 1563
test_interval: 391
base_lr: 0.001
display: 40
max_iter: 5865
lr_policy: "step"
gamma: 0.3
weight_decay: 1e-05
stepsize: 1173
snapshot: 391
snapshot_prefix: "snapshot"
solver_mode: GPU
device_id: 0
random_seed: 123
net: "train_val.prototxt"
type: "AdaGrad"
I0428 02:41:19.315131  2429 solver.cpp:91] Creating training net from net file: train_val.prototxt
I0428 02:41:19.315707  2429 net.cpp:323] The NetState phase (0) differed from the phase (1) specified by a rule in layer val-data
I0428 02:41:19.315731  2429 net.cpp:323] The NetState phase (0) differed from the phase (1) specified by a rule in layer accuracy
I0428 02:41:19.315888  2429 net.cpp:52] Initializing net from parameters:
state {
phase: TRAIN
}
layer {
name: "train-data"
type: "Data"
top: "data"
top: "label"
include {
phase: TRAIN
}
transform_param {
mirror: true
crop_size: 32
mean_file: "/var/lib/digits/jobs/20170428-015357-2072/mean.binaryproto"
}
data_param {
source: "/var/lib/digits/jobs/20170428-015357-2072/train_db"
batch_size: 128
backend: LMDB
}
}
layer {
name: "conv1"
type: "Convolution"
bottom: "data"
top: "conv1"
param {
lr_mult: 1
decay_mult: 1
}
param {
lr_mult: 2
decay_mult: 0
}
convolution_param {
num_output: 96
kernel_size: 11
stride: 4
weight_filler {
type: "gaussian"
std: 0.01
}
bias_filler {
type: "constant"
value: 0
}
}
}
layer {
name: "relu1"
type: "ReLU"
bottom: "conv1"
top: "conv1"
}
layer {
name: "norm1"
type: "LRN"
bottom: "conv1"
top: "norm1"
lrn_param {
local_size: 5
alpha: 0.0001
beta: 0.75
}
}
layer {
name: "pool1"
type: "Pooling"
bottom: "norm1"
top: "pool1"
pooling_param {
pool: MAX
kernel_size: 3
stride: 2
}
}
layer {
name: "conv2"
type: "Convolution"
bottom: "pool1"
top: "conv2"
param {
lr_mult: 1
decay_mult: 1
}
param {
lr_mult: 2
decay_mult: 0
}
convolution_param {
num_output: 256
pad: 2
kernel_size: 5
group: 2
weight_filler {
type: "gaussian"
std: 0.01
}
bias_filler {
type: "constant"
value: 0.1
}
}
}
layer {
name: "relu2"
type: "ReLU"
bottom: "conv2"
top: "conv2"
}
layer {
name: "norm2"
type: "LRN"
bottom: "conv2"
top: "norm2"
lrn_param {
local_size: 5
alpha: 0.0001
beta: 0.75
}
}
layer {
name: "pool2"
type: "Pooling"
bottom: "norm2"
top: "pool2"
pooling_param {
pool: MAX
kernel_size: 3
stride: 2
}
}
layer {
name: "conv3"
type: "Convolution"
bottom: "pool2"
top: "conv3"
param {
lr_mult: 1
decay_mult: 1
}
param {
lr_mult: 2
decay_mult: 0
}
convolution_param {
num_output: 384
pad: 1
kernel_size: 3
weight_filler {
type: "gaussian"
std: 0.01
}
bias_filler {
type: "constant"
value: 0
}
}
}
layer {
name: "relu3"
type: "ReLU"
bottom: "conv3"
top: "conv3"
}
layer {
name: "conv4"
type: "Convolution"
bottom: "conv3"
top: "conv4"
param {
lr_mult: 1
decay_mult: 1
}
param {
lr_mult: 2
decay_mult: 0
}
convolution_param {
num_output: 384
pad: 1
kernel_size: 3
group: 2
weight_filler {
type: "gaussian"
std: 0.01
}
bias_filler {
type: "constant"
value: 0.1
}
}
}
layer {
name: "relu4"
type: "ReLU"
bottom: "conv4"
top: "conv4"
}
layer {
name: "conv5"
type: "Convolution"
bottom: "conv4"
top: "conv5"
param {
lr_mult: 1
decay_mult: 1
}
param {
lr_mult: 2
decay_mult: 0
}
convolution_param {
num_output: 256
pad: 1
kernel_size: 3
group: 2
weight_filler {
type: "gaussian"
std: 0.01
}
bias_filler {
type: "constant"
value: 0.1
}
}
}
layer {
name: "relu5"
type: "ReLU"
bottom: "conv5"
top: "conv5"
}
layer {
name: "pool5"
type: "Pooling"
bottom: "conv5"
top: "pool5"
pooling_param {
pool: MAX
kernel_size: 3
stride: 2
}
}
layer {
name: "fc6"
type: "InnerProduct"
bottom: "pool5"
top: "fc6"
param {
lr_mult: 1
decay_mult: 1
}
param {
lr_mult: 2
decay_mult: 0
}
inner_product_param {
num_output: 4096
weight_filler {
type: "gaussian"
std: 0.005
}
bias_filler {
type: "constant"
value: 0.1
}
}
}
layer {
name: "relu6"
type: "ReLU"
bottom: "fc6"
top: "fc6"
}
layer {
name: "drop6"
type: "Dropout"
bottom: "fc6"
top: "fc6"
dropout_param {
dropout_ratio: 0.5
}
}
layer {
name: "fc7"
type: "InnerProduct"
bottom: "fc6"
top: "fc7"
param {
lr_mult: 1
decay_mult: 1
}
param {
lr_mult: 2
decay_mult: 0
}
inner_product_param {
num_output: 4096
weight_filler {
type: "gaussian"
std: 0.005
}
bias_filler {
type: "constant"
value: 0.1
}
}
}
layer {
name: "relu7"
type: "ReLU"
bottom: "fc7"
top: "fc7"
}
layer {
name: "drop7"
type: "Dropout"
bottom: "fc7"
top: "fc7"
dropout_param {
dropout_ratio: 0.5
}
}
layer {
name: "fc8"
type: "InnerProduct"
bottom: "fc7"
top: "fc8"
param {
lr_mult: 1
decay_mult: 1
}
param {
lr_mult: 2
decay_mult: 0
}
inner_product_param {
num_output: 10
weight_filler {
type: "gaussian"
std: 0.01
}
bias_filler {
type: "constant"
value: 0
}
}
}
layer {
name: "loss"
type: "SoftmaxWithLoss"
bottom: "fc8"
bottom: "label"
top: "loss"
}
I0428 02:41:19.316000  2429 layer_factory.hpp:77] Creating layer train-data
I0428 02:41:19.316679  2429 net.cpp:94] Creating Layer train-data
I0428 02:41:19.316690  2429 net.cpp:409] train-data -> data
I0428 02:41:19.316707  2429 net.cpp:409] train-data -> label
I0428 02:41:19.316721  2429 data_transformer.cpp:25] Loading mean file from: /var/lib/digits/jobs/20170428-015357-2072/mean.binaryproto
I0428 02:41:19.318146  2436 db_lmdb.cpp:35] Opened lmdb /var/lib/digits/jobs/20170428-015357-2072/train_db
I0428 02:41:19.318440  2429 data_layer.cpp:76] output data size: 128,3,32,32
I0428 02:41:19.323140  2429 net.cpp:144] Setting up train-data
I0428 02:41:19.323160  2429 net.cpp:151] Top shape: 128 3 32 32 (393216)
I0428 02:41:19.323164  2429 net.cpp:151] Top shape: 128 (128)
I0428 02:41:19.323168  2429 net.cpp:159] Memory required for data: 1573376
I0428 02:41:19.323173  2429 layer_factory.hpp:77] Creating layer conv1
I0428 02:41:19.323187  2429 net.cpp:94] Creating Layer conv1
I0428 02:41:19.323191  2429 net.cpp:435] conv1 <- data
I0428 02:41:19.323202  2429 net.cpp:409] conv1 -> conv1
I0428 02:41:19.589437  2429 net.cpp:144] Setting up conv1
I0428 02:41:19.589464  2429 net.cpp:151] Top shape: 128 96 6 6 (442368)
I0428 02:41:19.589468  2429 net.cpp:159] Memory required for data: 3342848
I0428 02:41:19.589488  2429 layer_factory.hpp:77] Creating layer relu1
I0428 02:41:19.589501  2429 net.cpp:94] Creating Layer relu1
I0428 02:41:19.589507  2429 net.cpp:435] relu1 <- conv1
I0428 02:41:19.589514  2429 net.cpp:396] relu1 -> conv1 (in-place)
I0428 02:41:19.589530  2429 net.cpp:144] Setting up relu1
I0428 02:41:19.589535  2429 net.cpp:151] Top shape: 128 96 6 6 (442368)
I0428 02:41:19.589539  2429 net.cpp:159] Memory required for data: 5112320
I0428 02:41:19.589541  2429 layer_factory.hpp:77] Creating layer norm1
I0428 02:41:19.589553  2429 net.cpp:94] Creating Layer norm1
I0428 02:41:19.589557  2429 net.cpp:435] norm1 <- conv1
I0428 02:41:19.589561  2429 net.cpp:409] norm1 -> norm1
I0428 02:41:19.589650  2429 net.cpp:144] Setting up norm1
I0428 02:41:19.589684  2429 net.cpp:151] Top shape: 128 96 6 6 (442368)
I0428 02:41:19.589686  2429 net.cpp:159] Memory required for data: 6881792
I0428 02:41:19.589689  2429 layer_factory.hpp:77] Creating layer pool1
I0428 02:41:19.589701  2429 net.cpp:94] Creating Layer pool1
I0428 02:41:19.589704  2429 net.cpp:435] pool1 <- norm1
I0428 02:41:19.589709  2429 net.cpp:409] pool1 -> pool1
I0428 02:41:19.589959  2429 net.cpp:144] Setting up pool1
I0428 02:41:19.589972  2429 net.cpp:151] Top shape: 128 96 3 3 (110592)
I0428 02:41:19.589977  2429 net.cpp:159] Memory required for data: 7324160
I0428 02:41:19.589983  2429 layer_factory.hpp:77] Creating layer conv2
I0428 02:41:19.590000  2429 net.cpp:94] Creating Layer conv2
I0428 02:41:19.590006  2429 net.cpp:435] conv2 <- pool1
I0428 02:41:19.590016  2429 net.cpp:409] conv2 -> conv2
I0428 02:41:19.617810  2429 net.cpp:144] Setting up conv2
I0428 02:41:19.617821  2429 net.cpp:151] Top shape: 128 256 3 3 (294912)
I0428 02:41:19.617825  2429 net.cpp:159] Memory required for data: 8503808
I0428 02:41:19.617833  2429 layer_factory.hpp:77] Creating layer relu2
I0428 02:41:19.617839  2429 net.cpp:94] Creating Layer relu2
I0428 02:41:19.617843  2429 net.cpp:435] relu2 <- conv2
I0428 02:41:19.617847  2429 net.cpp:396] relu2 -> conv2 (in-place)
I0428 02:41:19.617856  2429 net.cpp:144] Setting up relu2
I0428 02:41:19.617859  2429 net.cpp:151] Top shape: 128 256 3 3 (294912)
I0428 02:41:19.617861  2429 net.cpp:159] Memory required for data: 9683456
I0428 02:41:19.617864  2429 layer_factory.hpp:77] Creating layer norm2
I0428 02:41:19.617871  2429 net.cpp:94] Creating Layer norm2
I0428 02:41:19.617874  2429 net.cpp:435] norm2 <- conv2
I0428 02:41:19.617880  2429 net.cpp:409] norm2 -> norm2
I0428 02:41:19.617923  2429 net.cpp:144] Setting up norm2
I0428 02:41:19.617930  2429 net.cpp:151] Top shape: 128 256 3 3 (294912)
I0428 02:41:19.617933  2429 net.cpp:159] Memory required for data: 10863104
I0428 02:41:19.617936  2429 layer_factory.hpp:77] Creating layer pool2
I0428 02:41:19.617943  2429 net.cpp:94] Creating Layer pool2
I0428 02:41:19.617945  2429 net.cpp:435] pool2 <- norm2
I0428 02:41:19.617949  2429 net.cpp:409] pool2 -> pool2
I0428 02:41:19.617980  2429 net.cpp:144] Setting up pool2
I0428 02:41:19.617985  2429 net.cpp:151] Top shape: 128 256 1 1 (32768)
I0428 02:41:19.617987  2429 net.cpp:159] Memory required for data: 10994176
I0428 02:41:19.617990  2429 layer_factory.hpp:77] Creating layer conv3
I0428 02:41:19.618000  2429 net.cpp:94] Creating Layer conv3
I0428 02:41:19.618003  2429 net.cpp:435] conv3 <- pool2
I0428 02:41:19.618008  2429 net.cpp:409] conv3 -> conv3
I0428 02:41:19.710875  2429 net.cpp:144] Setting up conv3
I0428 02:41:19.710888  2429 net.cpp:151] Top shape: 128 384 1 1 (49152)
I0428 02:41:19.710892  2429 net.cpp:159] Memory required for data: 11190784
I0428 02:41:19.710901  2429 layer_factory.hpp:77] Creating layer relu3
I0428 02:41:19.710907  2429 net.cpp:94] Creating Layer relu3
I0428 02:41:19.710911  2429 net.cpp:435] relu3 <- conv3
I0428 02:41:19.710916  2429 net.cpp:396] relu3 -> conv3 (in-place)
I0428 02:41:19.710922  2429 net.cpp:144] Setting up relu3
I0428 02:41:19.710927  2429 net.cpp:151] Top shape: 128 384 1 1 (49152)
I0428 02:41:19.710929  2429 net.cpp:159] Memory required for data: 11387392
I0428 02:41:19.710932  2429 layer_factory.hpp:77] Creating layer conv4
I0428 02:41:19.710944  2429 net.cpp:94] Creating Layer conv4
I0428 02:41:19.710947  2429 net.cpp:435] conv4 <- conv3
I0428 02:41:19.710952  2429 net.cpp:409] conv4 -> conv4
I0428 02:41:19.764622  2429 net.cpp:144] Setting up conv4
I0428 02:41:19.764634  2429 net.cpp:151] Top shape: 128 384 1 1 (49152)
I0428 02:41:19.764638  2429 net.cpp:159] Memory required for data: 11584000
I0428 02:41:19.764645  2429 layer_factory.hpp:77] Creating layer relu4
I0428 02:41:19.764652  2429 net.cpp:94] Creating Layer relu4
I0428 02:41:19.764654  2429 net.cpp:435] relu4 <- conv4
I0428 02:41:19.764662  2429 net.cpp:396] relu4 -> conv4 (in-place)
I0428 02:41:19.764668  2429 net.cpp:144] Setting up relu4
I0428 02:41:19.764688  2429 net.cpp:151] Top shape: 128 384 1 1 (49152)
I0428 02:41:19.764690  2429 net.cpp:159] Memory required for data: 11780608
I0428 02:41:19.764693  2429 layer_factory.hpp:77] Creating layer conv5
I0428 02:41:19.764703  2429 net.cpp:94] Creating Layer conv5
I0428 02:41:19.764706  2429 net.cpp:435] conv5 <- conv4
I0428 02:41:19.764711  2429 net.cpp:409] conv5 -> conv5
I0428 02:41:19.800688  2429 net.cpp:144] Setting up conv5
I0428 02:41:19.800699  2429 net.cpp:151] Top shape: 128 256 1 1 (32768)
I0428 02:41:19.800704  2429 net.cpp:159] Memory required for data: 11911680
I0428 02:41:19.800711  2429 layer_factory.hpp:77] Creating layer relu5
I0428 02:41:19.800720  2429 net.cpp:94] Creating Layer relu5
I0428 02:41:19.800724  2429 net.cpp:435] relu5 <- conv5
I0428 02:41:19.800729  2429 net.cpp:396] relu5 -> conv5 (in-place)
I0428 02:41:19.800735  2429 net.cpp:144] Setting up relu5
I0428 02:41:19.800740  2429 net.cpp:151] Top shape: 128 256 1 1 (32768)
I0428 02:41:19.800741  2429 net.cpp:159] Memory required for data: 12042752
I0428 02:41:19.800745  2429 layer_factory.hpp:77] Creating layer pool5
I0428 02:41:19.800751  2429 net.cpp:94] Creating Layer pool5
I0428 02:41:19.800755  2429 net.cpp:435] pool5 <- conv5
I0428 02:41:19.800758  2429 net.cpp:409] pool5 -> pool5
*** Aborted at 1493347279 (unix time) try "date -d @1493347279" if you are using GNU date ***
PC: @     0x7fd867e616f0 (unknown)
*** SIGFPE (@0x7fd867e616f0) received by PID 2429 (TID 0x7fd868a41a40) from PID 1743132400; stack trace: ***
@     0x7fd866415cb0 (unknown)
@     0x7fd867e616f0 (unknown)
@     0x7fd867e61b09 (unknown)
@     0x7fd867ef518c (unknown)
@     0x7fd867fa7f75 (unknown)
@     0x7fd867fa8e9a (unknown)
@     0x7fd867f8c2ba (unknown)
@     0x7fd867f8d25c (unknown)
@     0x7fd867f8d5a3 (unknown)
@     0x7fd8680057d9 (unknown)
@           0x411d0c (unknown)
@           0x40a97c (unknown)
@           0x40867c (unknown)
@     0x7fd866400f45 (unknown)
@           0x408e4d (unknown)
@                0x0 (unknown)

ubuntu@ip-172-31-27-213:~$ lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 01)
00:02.0 VGA compatible controller: Cirrus Logic GD 5446
00:1e.0 3D controller: NVIDIA Corporation GK210GL [Tesla K80] (rev a1)
00:1f.0 Unassigned class [ff80]: XenSource, Inc. Xen Platform Device (rev 01)

ubuntu@ip-172-31-27-213:~$ lsmod
Module                  Size  Used by
dm_crypt               23177  0
nvidia_uvm            631780  2
nvidia_modeset        790192  0
nvidia              12232929  35 nvidia_modeset,nvidia_uvm
serio_raw              13462  0
isofs                  39837  0
crct10dif_pclmul       14289  0
crc32_pclmul           13113  0
ghash_clmulni_intel    13302  0
aesni_intel            55624  0
aes_x86_64             17131  1 aesni_intel
lrw                    13286  1 aesni_intel
gf128mul               14951  1 lrw
glue_helper            13990  1 aesni_intel
ablk_helper            13597  1 aesni_intel
cryptd                 20359  3 ghash_clmulni_intel,aesni_intel,ablk_helper
psmouse               106692  0
floppy                 69418  0

ubuntu@ip-172-31-27-213:~$ dpkg -l | grep cuda
ii  caffe-nv                                  0.15.13-3ubuntu14.04+cuda8.0                        amd64        Fast open framework for Deep Learning
ii  caffe-nv-tools                            0.15.13-3ubuntu14.04+cuda8.0                        amd64        Fast open framework for Deep Learning (Tools)
ii  cuda                                      8.0.61-1                                            amd64        CUDA meta-package
ii  cuda-8-0                                  8.0.61-1                                            amd64        CUDA 8.0 meta-package
ii  cuda-command-line-tools-8-0               8.0.61-1                                            amd64        CUDA command-line tools
ii  cuda-core-8-0                             8.0.61-1                                            amd64        CUDA core tools
ii  cuda-cublas-8-0                           8.0.61.1-1                                          amd64        CUBLAS native runtime libraries
ii  cuda-cublas-dev-8-0                       8.0.61.1-1                                          amd64        CUBLAS native dev links, headers
ii  cuda-cudart-8-0                           8.0.61-1                                            amd64        CUDA Runtime native Libraries
ii  cuda-cudart-dev-8-0                       8.0.61-1                                            amd64        CUDA Runtime native dev links, headers
ii  cuda-cufft-8-0                            8.0.61-1                                            amd64        CUFFT native runtime libraries
ii  cuda-cufft-dev-8-0                        8.0.61-1                                            amd64        CUFFT native dev links, headers
ii  cuda-curand-8-0                           8.0.61-1                                            amd64        CURAND native runtime libraries
ii  cuda-curand-dev-8-0                       8.0.61-1                                            amd64        CURAND native dev links, headers
ii  cuda-cusolver-8-0                         8.0.61-1                                            amd64        CUDA solver native runtime libraries
ii  cuda-cusolver-dev-8-0                     8.0.61-1                                            amd64        CUDA solver native dev links, headers
ii  cuda-cusparse-8-0                         8.0.61-1                                            amd64        CUSPARSE native runtime libraries
ii  cuda-cusparse-dev-8-0                     8.0.61-1                                            amd64        CUSPARSE native dev links, headers
ii  cuda-demo-suite-8-0                       8.0.61-1                                            amd64        Demo suite for CUDA
ii  cuda-documentation-8-0                    8.0.61-1                                            amd64        CUDA documentation
ii  cuda-driver-dev-8-0                       8.0.61-1                                            amd64        CUDA Driver native dev stub library
ii  cuda-drivers                              375.51-1                                            amd64        CUDA Driver meta-package
rc  cuda-ld-conf-7-5                          1.0.0-3                                             amd64        CUDA 7.5 ld.so.conf files
ii  cuda-license-8-0                          8.0.61-1                                            amd64        CUDA licenses
ii  cuda-misc-headers-8-0                     8.0.61-1                                            amd64        CUDA miscellaneous headers
ii  cuda-npp-8-0                              8.0.61-1                                            amd64        NPP native runtime libraries
ii  cuda-npp-dev-8-0                          8.0.61-1                                            amd64        NPP native dev links, headers
ii  cuda-nvgraph-8-0                          8.0.61-1                                            amd64        NVGRAPH native runtime libraries
ii  cuda-nvgraph-dev-8-0                      8.0.61-1                                            amd64        NVGRAPH native dev links, headers
ii  cuda-nvml-dev-8-0                         8.0.61-1                                            amd64        NVML native dev links, headers
ii  cuda-nvrtc-8-0                            8.0.61-1                                            amd64        NVRTC native runtime libraries
ii  cuda-nvrtc-dev-8-0                        8.0.61-1                                            amd64        NVRTC native dev links, headers
ii  cuda-repo-ubuntu1404                      8.0.61-1                                            amd64        cuda repository configuration files
ii  cuda-runtime-8-0                          8.0.61-1                                            amd64        CUDA Runtime 8.0 meta-package
ii  cuda-samples-8-0                          8.0.61-1                                            amd64        CUDA example applications
rc  cuda-toolkit-7-5                          7.5-18                                              amd64        CUDA Toolkit 7.5 meta-package
ii  cuda-toolkit-8-0                          8.0.61-1                                            amd64        CUDA Toolkit 8.0 meta-package
rc  cuda-visual-tools-7-5                     7.5-18                                              amd64        CUDA visual tools
ii  cuda-visual-tools-8-0                     8.0.61-1                                            amd64        CUDA visual tools
ii  libcaffe-nv0                              0.15.13-3ubuntu14.04+cuda8.0                        amd64        Fast open framework for Deep Learning (Libs)
ii  libcuda1-375                              375.51-0ubuntu1                                     amd64        NVIDIA CUDA runtime library
ii  libcudnn5                                 5.1.10-1+cuda8.0                                    amd64        cuDNN runtime libraries
ii  libnccl1                                  1.2.3-1+cuda8.0                                     amd64        NVIDIA Collectives Communication Library (NCCL) Runtime
ii  python-caffe-nv                           0.15.13-3ubuntu14.04+cuda8.0                        amd64        Fast open framework for Deep Learning (Python)
ii  torch7-nv                                 0.9.99-1+cuda8.0                                    amd64        NVidia Torch Bundle (with CUDA). Made for DIGITS.

ubuntu@ip-172-31-27-213:~$ dpkg -l | grep digits
ii  digits                                    5.0.0-1                                             all          NVIDIA DIGITS webserver

ubuntu@ip-172-31-27-213:~$ ls /dev/
Display all 195 possibilities? (y or n)
autofs              loop5               ram13               tty11               tty34               tty57               ttyS20              vcs3
.blkid.tab          loop6               ram14               tty12               tty35               tty58               ttyS21              vcs4
.blkid.tab.old      loop7               ram15               tty13               tty36               tty59               ttyS22              vcs5
block/              loop-control        ram2                tty14               tty37               tty6                ttyS23              vcs6
btrfs-control       mapper/             ram3                tty15               tty38               tty60               ttyS24              vcs7
char/               mcelog              ram4                tty16               tty39               tty61               ttyS25              vcsa
console             mem                 ram5                tty17               tty4                tty62               ttyS26              vcsa1
core                net/                ram6                tty18               tty40               tty63               ttyS27              vcsa2
cpu/                network_latency     ram7                tty19               tty41               tty7                ttyS28              vcsa3
cpu_dma_latency     network_throughput  ram8                tty2                tty42               tty8                ttyS29              vcsa4
disk/               null                ram9                tty20               tty43               tty9                ttyS3               vcsa5
ecryptfs            nvidia0             random              tty21               tty44               ttyprintk           ttyS30              vcsa6
fd/                 nvidiactl           rfkill              tty22               tty45               ttyS0               ttyS31              vcsa7
full                nvidia-uvm          rtc                 tty23               tty46               ttyS1               ttyS4               vga_arbiter
fuse                nvidia-uvm-tools    rtc0                tty24               tty47               ttyS10              ttyS5               xen/
hpet                port                shm/                tty25               tty48               ttyS11              ttyS6               xvda
.initramfs/         ppp                 snapshot            tty26               tty49               ttyS12              ttyS7               xvda1
input/              psaux               snd/                tty27               tty5                ttyS13              ttyS8               xvdb
kmsg                ptmx                stderr              tty28               tty50               ttyS14              ttyS9               xvdb1
log                 pts/                stdin               tty29               tty51               ttyS15              .udev/              zero
loop0               ram0                stdout              tty3                tty52               ttyS16              uinput
loop1               ram1                tty                 tty30               tty53               ttyS17              urandom
loop2               ram10               tty0                tty31               tty54               ttyS18              vcs
loop3               ram11               tty1                tty32               tty55               ttyS19              vcs1
loop4               ram12               tty10               tty33               tty56               ttyS2               vcs2

**Comment by lukeyeager** [comment]
Closing as a duplicate.

https://github.com/NVIDIA/DIGITS/issues/291#issuecomment-139378547
https://github.com/NVIDIA/DIGITS/issues/303#issuecomment-140163897
https://github.com/NVIDIA/DIGITS/issues/918#issuecomment-234005879

**Comment by jwatte** [comment]
Thanks for the pointer!

> the convolution and pooling layers will try to reduce the spatial dimension of your data to something less than 0, resulting in a cryptic error

It would be useful to recognize this, and give a less cryptic error.

**Comment by lukeyeager** [comment]
Agreed. I never got around to submitting a PR to BVLC. Feel free to do so.
