### ISSUE TITLE
ERROR: Out of memory: failed to allocate 58080000 bytes on device 0

### ISSUE THREAD

**Issue by yorkjohn** [NVIDIA/DIGITS#1607]
I have tried the mnist project and everything works fine. Then I created another dataset with 2000 images(size 256*256). When I tried to learn the model(standard Alex), it gives me the error as shown in the title.
I am using a laptop with 8G memory, 256 SSD disk and a graphic card which is GeForce 940MX with 1GB memory.
Dont know why it cant locate 55Mb memory for me.Please Help.

**Comment by RSly** [comment]
you should monitor your gpu usage and see what process is using it

also look in the caffe.log for more details. this 55 Mb is not the total ram but it means you have already filled the ram and it cant find additional 55Mb space

**Comment by VanitarNordic** [comment]
reduce image sizes
use smaller batch size

**Comment by yorkjohn** [comment]
to VanitarNordic:
yes, u r right. I have tried reduced the image size to 128*128, it worked.
But I still dont understand why the system couldnt allocate 53Mbs for me.

**Comment by yorkjohn** [comment]
to RSly:

next time I will pay attention to other ps to see if they drain the gpu.
is caffe.log the one in jobs directory named like "caffe_output.log"?
thanks.

**Comment by yorkjohn** [comment]
It seems my 1GB memory is really too small. 
Even I decreased batch size into 1, it is still out of memory.
I can see from the Nvidia monitor the GPU usage reaches 100% soon after the job starts.

**Comment by VanitarNordic** [comment]
@yorkjohn 

you GPU has 1G memory? it is too small for deep learning tasks. I have a GPU with 6G memory and sometimes I get the same error as you get.
