### ISSUE TITLE
USE_NCCL flag installed, but not recognized 

### ISSUE THREAD

**Issue by stolam** [NVIDIA/DIGITS#1608]
Hi,

I am trying to train on DIGITS 5.1 (DetectNet) using multiple GPUs at once. I have NCCL installed in caffe, but the training fails with the following error:

`F0428 11:32:07.443701  8682 parallel.cpp:155] USE_NCCL := 1 must be specified for multi-GPU`

However, when I train only on one GPU, it is fine.

To find out the configuration I ran the cmake on caffe:
```
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   0.15.14
--   Git               :   v0.15.14-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.62)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 3.1.0)
--   lmdb              :   Yes (ver. 0.9.10)
--   LevelDB           :   Yes (ver. 1.15)
--   Snappy            :   Yes (ver. 1.1.0)
--   OpenCV            :   Yes (ver. 3.1.0)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_61
--   cuDNN             :   Yes (ver. 5.1.5)
--   NCCL              :   Yes
-- 
-- Python:
--   Interpreter       :   /home/cvuser/anaconda2/bin/python2.7 (ver. 2.7.12)
--   Libraries         :   /home/cvuser/anaconda2/lib/libpython2.7.so (ver 2.7.12)
--   NumPy             :   /home/cvuser/anaconda2/lib/python2.7/site-packages/numpy/core/include (ver 1.11.0)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
-- Install path      :   /home/cvuser/caffe/build/install
```

Afterwards I run 
`make all`
`make install`
`make runtest`

The build is OK as well as all the tests (except 3 DetectNetTransformationLayer test)
It seems to me that it should run fine (cuDNN 5, cuda 8.0, NCCL). Any idea, what I do wrong? Do I need to activate the NCCL somewhere else?

**Comment by lukeyeager** [comment]
You're probably not using that build of caffe in DIGITS.
Guide: https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/Configuration.md
Check the drop-down in the top-right to see the version of Caffe that's being used.

**Comment by stolam** [comment]
The dropdown says:
`DIGITS version:
5.1-dev
Caffe version:
0.15.14
Caffe flavor:
NVIDIA`

However, I did not set the CAFFE_ROOT. Thank you that resolved the issue.

On the other hand, the same caffe (on the same path) is called as before. So I do not quite get what is CAFFE_ROOT for. Digits call caffe even without it. I suggest it is ~/caffe by default or to enforce users to set it.
