### ISSUE TITLE
Caffe2 configuration for Nvidia Digits 5.0

### ISSUE THREAD

**Issue by PanasheC** [NVIDIA/DIGITS#1612]
I  have successfully installed Caffe2. I have changed my configuration in .bashrc for CAFFE_ROOT to CAFFE_ROOT=~/caffe2. 

When I run ./digits-test, I am getting the following error:
ERROR: Failure: ValueError (Caffe executable not found at "~/caffe2/build/tools").

**How do I configure digits to work with Caffe2 ?**

**Comment by lukeyeager** [comment]
Caffe2 is not a drop-in replacement for Caffe1. We'll respond to https://github.com/NVIDIA/DIGITS/issues/1594 if/when we start adding support for Caffe2.
