### ISSUE TITLE
Test pretrained models

### ISSUE THREAD

**Issue by DeepBernhard** [NVIDIA/DIGITS#1613]
Dear digits community.

Is there a possibility to test a pretrained model inside digits? I love the feature to test images on trained models, but is it possible to do the same on pretrained models? I would like to compare the performance on different trained models but also on pretrained models, do I have to fiddle around with some of the scripts?

Thank you so much,
Bernhard

![test-model](https://cloud.githubusercontent.com/assets/26299848/25562692/716f0fbc-2d8d-11e7-8c5e-6bf3c9da9595.png)

**Comment by WilliamJuel** [comment]
Hello, have you seen https://github.com/NVIDIA/DIGITS/tree/master/examples/classification ?

**Comment by DeepBernhard** [comment]
Hey,

Thanks for your quick answer. Looks like I have to adapt this for object-detection models. I'll take a look into it.

Thx, Bernhard

**Comment by gheinrich** [comment]
In practice, it's difficult to use just any pre-trained model in DIGITS because when the model was trained outside of DIGITS we don't know what kind of pre-processing needs to be applied to the data (e.g. resize, crop, etc.). For this reason we have decide not to allow this in DIGITS.

**Comment by DeepBernhard** [comment]
Hey Greg.

In my case I want to use the pre trained BVLC-GoogLeNet model. What I already did was to replace one of the epoch models of the refinement training with it and then ran tests on it through DIGITS. Is pretty hacky but should be a valid test, isn't it? Nothing was detected anyway on the KITTI val data.

Thx 4 your help
