### ISSUE TITLE
Suspend corrupts Digits

### ISSUE THREAD

**Issue by yorkjohn** [NVIDIA/DIGITS#1621]
Every time when Digits is used after a wake up from a suspension mode,
it gives an error: error code-6:
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0504 12:30:02.978602 2662 common.cpp:163] Check failed: error == cudaSuccess (30 vs. 0) unknown error
*** Check failure stack trace: ***
cudaRuntimeGetVersion() failed with error #30

If I try ./deviceQuery,it gives:
cudaGetDeviceCount returned 30
-> unknown error

It seams in sleep mode, the system changes into power saving mode and use intel graphic card instead.
Since after reboot, everything works fine.
Is there any way to fix it? 

Also listed:https://devtalk.nvidia.com/default/topic/1007160/linux/suspend-corrupts-digits/

**Comment by lukeyeager** [comment]
Sounds like your problem is specific to CUDA and/or our driver - not to DIGITS. I'm not going to be able to help you there. Your best bet would probably be to ask on devtalk.
