### ISSUE TITLE
Error pascal_voc_2012 lesson (semantic-segmentation)

### ISSUE THREAD

**Issue by Maxfashko** [NVIDIA/DIGITS#1622]
Hello! I began to perform a lesson on semantic segmentation by the example of https://github.com/NVIDIA/DIGITS/tree/master/examples/semantic-segmentation. I followed all the steps in the lesson, but I got the error when I tried to start training:

`norm1 needs backward computation.
pool1 needs backward computation.
relu1 needs backward computation.
conv1 needs backward computation.
shift does not need backward computation.
label_label_0_split does not need backward computation.
label does not need backward computation.
data_data_0_split does not need backward computation.
data does not need backward computation.
This network produces output accuracy
This network produces output loss
Network initialization done.
Solver scaffolding done.
Finetuning from /home/maksim/DATASETS/PASCAL-VOC-2012/example/bvlc_alexnet.caffemodel
Attempting to upgrade input file specified using deprecated transformation parameters: /home/maksim/DATASETS/PASCAL-VOC-2012/example/bvlc_alexnet.caffemodel
Successfully upgraded file specified using deprecated data transformation parameters.
Note that future Caffe releases will only support transform_param messages for transformation fields.
Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/maksim/DATASETS/PASCAL-VOC-2012/example/bvlc_alexnet.caffemodel
Successfully upgraded file specified using deprecated V1LayerParameter
Cannot copy param 0 weights from layer 'fc6'; shape mismatch.  Source param shape is 1 1 4096 9216 (37748736); target param shape is 4096 256 6 6 (37748736). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.`

**Comment by FangliangBai** [comment]
Hi @Maxfashko , I got the same error. How did you fix it?

**Comment by Maxfashko** [comment]
@FangliangBai Carefully read the manual and it turned out that I used the wrong caffemodel
