### ISSUE TITLE
NVIDIA: no NVIDIA devices found cudaRuntimeGetVersion() failed with error #30

### ISSUE THREAD

**Issue by Xoppop** [NVIDIA/DIGITS#1634]
Hello.

Caffe established the regime CPU_Only. Learning Networks passes normally. When test network publishes the following error:

NVIDIA: no NVIDIA devices found
cudaRuntimeGetVersion () failed with error # 30
IOError:
2017-05-09 21:45:50 [ERROR] InferenceError: Unable to load any image from file '' /var/lib/digits/jobs/20170509-214546-8ba5/tmpR4V8kV.txt ''
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/digits/tools/inference.py", line 293, in <module>
args [ 'resize']
File "/usr/lib/python2.7/dist-packages/digits/tools/inference.py", line 151, in infer
raise InferenceError ( "Unable to load any image from file '% s'"% repr (input_list))
digits.inference.errors.InferenceError: "Unable to load any image from file '' /var/lib/digits/jobs/20170509-214546-8ba5/tmpR4V8kV.txt ''"

**Comment by lukeyeager** [comment]
Why are you running CPU only? Do you have GPUs on your machine?

**Comment by Xoppop** [comment]
I use the CPU because cuDNN does not work with Fermi. I had to install Caffe in CPU only mode.

**Comment by lukeyeager** [comment]
Ah, that's a good reason. Looking more carefully at your log, you should ignore the CUDA error. DIGITS keeps on trucking past the error. Your error is `"Unable to load any image from file '' /var/lib/digits/jobs/20170509-214546-8ba5/tmpR4V8kV.txt ''"`. I'd check to make sure that file exists and is formatted correctly.

**Comment by Xoppop** [comment]
I use the CPU because cuDNN does not work with Fermi. I had to install Caffe in CPU only mode.

**Comment by Xoppop** [comment]
Спасибо, разобрался где была ошибка

**Comment by Xoppop** [comment]
Thanks, understood where there was an error
