### ISSUE TITLE
textClassification plug-in install error

### ISSUE THREAD

**Issue by elliotekoch** [NVIDIA/DIGITS#1640]
I verified that my digits install and the entire system is up to date...
I even did a cache clean.

 Trying to install the text plugin i get a different error but still related to digits.extensions.data
```
sudo yum update
Loaded plugins: aliases, changelog, fastestmirror, kabi, langpacks, product-id, search-disabled-repos, subscription-manager,
              : tmprepo, verify, versionlock
This system is not registered with Subscription Management. You can use subscription-manager to register.
Loading support for Red Hat kernel ABI
Loading mirror speeds from cached hostfile
 * base: linux.mirrors.es.net
 * extras: mirror.keystealth.org
 * updates: repos.lax.quadranet.com
No packages marked for update
ekoch@bil9001.nvidia.com> sudo yum install $DIGITS_ROOT
Loaded plugins: aliases, changelog, fastestmirror, kabi, langpacks, product-id, search-disabled-repos, subscription-manager,
              : tmprepo, verify, versionlock
This system is not registered with Subscription Management. You can use subscription-manager to register.
Loading support for Red Hat kernel ABI
Loading mirror speeds from cached hostfile
 * base: linux.mirrors.es.net
 * extras: mirror.keystealth.org
 * updates: repos.lax.quadranet.com
No package /root/digits available.
Error: Nothing to do

sudo pip install $DIGITS_ROOT/plugins/data/textClassification
Processing /root/digits/plugins/data/textClassification
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-nA6Eb6-build/setup.py", line 5, in <module>
        from digits.extensions.data import GROUP as DIGITS_PLUGIN_GROUP
    ImportError: No module named digits.extensions.data
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-nA6Eb6-build/
```
suggestions?  Thanks

**Comment by lukeyeager** [comment]
Uh, why would you try to run `sudo yum install $DIGITS_ROOT`? Which part of the documentation did you get that from?

**Comment by elliotekoch** [comment]
ohoh maybe i misread this comment from G... https://github.com/NVIDIA/DIGITS/issues/1300  ...

Let me go back to the install page and review that. Thanks

**Comment by elliotekoch** [comment]
This was my reference installation procedure for centos 7:
https://gist.github.com/lukeyeager/ba948f1d56e4ab407874

Found a couple of errors i should have reported. There are a few intermediate hand hacks i used to get it to go which i will report on that page...

Will come back to this with more info after i try the hacks again,,,, will advise...

thanks,
Elliot

**Comment by lukeyeager** [comment]
That gist was just to share something I took a look at once - it's certainly not to be treated as an official installation document. The only officially supported platforms at this time are Ubuntu 14.04 and 16.04. Other platforms are your own adventure.
