### ISSUE TITLE
What should I do to create a Image Classification Dataset to classify my dicom images?

### ISSUE THREAD

**Issue by Hzzone** [NVIDIA/DIGITS#1642]
When I create a new image classification dataset like 
[my pic](http://omoitwcai.bkt.clouddn.com/2017-05-17-%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-05-17%20%E4%B8%8B%E5%8D%888.19.22.png)

```ERROR: Did not find two valid categories```

But I have already classify them into different subfolder:
![](http://omoitwcai.bkt.clouddn.com/2017-05-17-%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-05-17%20%E4%B8%8B%E5%8D%888.22.40.png)

The purpose of medical-imaging example is demonstrating how to using DIGITS to train a medical image segmentation network. However I just want to classify my own dicom data.
I am a freshman to deep learning and this problem has troubled me for a long time.
I will appreciate it if someone can help me!

**Comment by lukeyeager** [comment]
DIGITS ignores image files which don't end in one of these extensions:
https://github.com/NVIDIA/DIGITS/blob/v5.0.0/digits/utils/image.py#L37
