### ISSUE TITLE
How can I fine-tune a pre-trained deep convolutional neural network model to do image classification on my own dataset?

### ISSUE THREAD

**Issue by Marianna-Be** [NVIDIA/DIGITS#1656]
Hi,
I use Digits from Nvidia and I want to know how I can fine-tune a pre-trained deep convolutional neural network model to do image classification on my own dataset.

**Comment by lukeyeager** [comment]
There's a link to this guide on the main README:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/examples/fine-tuning/README.md
