### ISSUE TITLE
Jetson TK1: NVIDIA caffe: make runtest fails

### ISSUE THREAD

**Issue by coreyt** [NVIDIA/DIGITS#166]
To get the caffe tests ```$ make runtest``` to work, two updates need to be made.  

First, in ```https://github.com/NVIDIA/caffe/blob/master/src/caffe/util/db.cpp#L8``` and replace:
```const size_t LMDB_MAP_SIZE = 1099511627776;  // 1 TB```
with
```const size_t LMDB_MAP_SIZE = 536870912;  // 2^29. fix for Jetson TK1```

Second, in '''https://github.com/NVIDIA/caffe/blob/master/examples/mnist/convert_mnist_data.cpp#L89``` replace 
```CHECK_EQ(mdb_env_set_mapsize(mdb_env, 1099511627776), MDB_SUCCESS)  // 1TB```
with 
```CHECK_EQ(mdb_env_set_mapsize(mdb_env, 536870912), MDB_SUCCESS)  // 2^29 for the Jetson / 32-bit```

**Comment by coreyt** [comment]
Since the solution is in the issue, closing.  Hopefully others will be able to search and find the answer here!

**Comment by MazenEzzeddine** [comment]
Great, thank you for providing the solution,
Still, what does the LMDB_MAP_SIZE actually represents and would its modification affect the learning process (e.g. accuracy, convergence time)?

Thanks.
