### ISSUE TITLE
Digits install on ubantu 17

### ISSUE THREAD

**Issue by Bhairav-Pardiwala** [NVIDIA/DIGITS#1664]
Hello 

How do i install digits on ubantu 17 ?

I dont think make package ,normal install method or aptitude install method works 

Regards
Bhairav

**Comment by lukeyeager** [comment]
That's right - only two of the LTS releases (14.04 and 16.04) are currently supported. But I would expect building from source will still work pretty well. And you can always use one of the Docker images. Check the readme for links to all this information.
