### ISSUE TITLE
AttributeError 'module' object has no attribute 'pyplot'

### ISSUE THREAD

**Issue by jerome0121** [NVIDIA/DIGITS#1672]
I have same problem just like #1117 . and I use the latest nvidia/digits docker.
I follow semantic-segmentation step by step, until i created the dataset and clicking the Explore DB, the page show the Error like:
![default](https://cloud.githubusercontent.com/assets/29109888/26660443/c246278c-46aa-11e7-9427-de7f69b77011.PNG)
Same problem when i choose colormap from dataset.
.

**Comment by lukeyeager** [comment]
Looks like that change is only in the `master` branch, not in `digits-5.0`:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/digits/dataset/generic/views.py
https://github.com/NVIDIA/DIGITS/blob/83254ed7a0/digits/dataset/generic/views.py#L14

**Comment by jerome0121** [comment]
It means i can't use digits docker to fix this, right? Cause i use DGX-1 to work. I think i should use docker.
I'm newbie in docker. Could you please give me some advice?

**Comment by lukeyeager** [comment]
If you're on a DGX-1, then you'll probably want to be using the DGX-1 images:
http://docs.nvidia.com/dgx/dgx-registry-user-guide/index.html
If you have any problem with one of those images, please reach out to DGX-1 support, as mentioned at the end of that document.

If you actually do need to use the DockerHub image for some reason, you might need to adjust this line and build your own image or something:
https://gitlab.com/nvidia/digits/blob/d599be1be792b2c7de4af8dad4e3e9955cb6a46f/5.0/Dockerfile#L34
You can try reaching out to Felix for help through this issue list:
https://gitlab.com/nvidia/digits/issues

**Comment by jerome0121** [comment]
I use the DGX-1 images and it works. Thanks a lot！
