### ISSUE TITLE
[FCN-8s] ERROR: error code -11

### ISSUE THREAD

**Issue by FangliangBai** [NVIDIA/DIGITS#1698]
Hi there,
I recently tried the NVIDIA DIGITS by following the tutorial [**DIGITS/examples/semantic-segmentation/**](https://github.com/NVIDIA/DIGITS/tree/master/examples/semantic-segmentation).
After that, I want to train the `FCN-8s` networks to segment a custom data that has 4 labels. So I used the `.caffemodel` and `protoxt` file given by @gheinrich on a Google forum [**Trouble in training FCN-8s in DIGITS**](https://groups.google.com/forum/#!topic/digits-users/0UF-xD-yGuY).
However, I consistently got ERROR: error code -11:
```
Top shape: 4 1 248 256 (253952)
Memory required for data: 12189696
Creating layer conv1_1
Creating Layer conv1_1
conv1_1 <- data_data_0_split_0
conv1_1 -> conv1_1
Setting up conv1_1
Top shape: 4 64 446 454 (51835904)
Memory required for data: 219533312
Creating layer relu1_1
Creating Layer relu1_1
relu1_1 <- conv1_1
relu1_1 -> conv1_1 (in-place)
Setting up relu1_1
Top shape: 4 64 446 454 (51835904)
Memory required for data: 426876928
Creating layer conv1_2
Creating Layer conv1_2
conv1_2 <- conv1_1
conv1_2 -> conv1_2
```
I read some related issue post and googled it but didn't find a situation similar to mine. Does anyone know where the problem is?

My DIGITS info is
```
DIGITS version:
5.1-dev
Caffe version:
0.15.13
Caffe flavor:
NVIDIA
```

Thanks in advance!

**Comment by VanitarNordic** [comment]
How much is your GPU memory?

**Comment by JackGan999** [comment]
I wonder how to annotate the image of custom data. Could you give me some hint?

**Comment by FangliangBai** [comment]
This issue is due to the limited GPU memory. Change the batch size down to one worked for me

**Comment by FangliangBai** [comment]
@JackGan999 Do you mean generate mask? Please give more details.
