### ISSUE TITLE
How to do the image matching?

### ISSUE THREAD

**Issue by Saneesh** [NVIDIA/DIGITS#170]
Hello,
From the documentations I came to know to identify the objects in an image we can use the cURL call.

curl 0.0.0.0:5000/models/images/classification/classify_one.json -XPOST -F job_id=20150708-124720-6d97 -F image_file=@/home/username/Downloads/test-tshirt.jpg

This will return the predictions about the objects in the image.

Now, how can I match an image with a folder contains many images and it return the image names descanting order of matching?

Regards,
Saneesh.

**Comment by lukeyeager** [comment]
> Now, how can I match an image with a folder contains many images and it return the image names descanting order of matching?

Sorry, I don't understand what you're asking. Do you just want the "classify many" tool (see [here](https://github.com/NVIDIA/DIGITS/blob/v2.0.0-preview/docs/API.md#modelsimagesclassificationclassify_manyjson))?

**Comment by Saneesh** [comment]
Sorry, I will try to make it clear.
My requirement is, when a user take a picture of a t-shirt or shoes, the system need to find the similar product image from the image list available. For ex. if a user searched for "black puma sports shoes" the system need to fetch the similar products available in the image folder so that the user can go for buy.

How can I achieve this with caffe-DIGITS?

**Comment by lukeyeager** [comment]
Oh I see. That's not a simple image classification task. I think you're going to need to do some research.

You might want to check out [this paper](http://www.cs.toronto.edu/~fritz/absps/esann-deep-final.pdf) as an example of how to solve your problem directly with autoencoders.

You could probably find a way to use the middle layers of a model trained with DIGITS to solve your problem, but it's not simple and you wouldn't be able to do it directly with DIGITS.

**Comment by lukeyeager** [comment]
#189 will provide enough generality in DIGITS to let you solve your problem in DIGITS. There won't be a standard network to solve your specific problem, though. It's still on you to figure that out.
