### ISSUE TITLE
Error code -6 : Memory required for data: xxx Creating layer cluster

### ISSUE THREAD

**Issue by tamasbalassa** [NVIDIA/DIGITS#1710]
Hey there,

as I mentioned in the title, I am getting this error message in the DIGITS ui.

Here I am attaching the caffe output: 
[caffe_output.txt](https://github.com/NVIDIA/DIGITS/files/1124204/caffe_output.txt)

I must mention that I am trying to clone a same setup that **it worked properly before**. Same dataset and same parameters.

Also, I know that the output says that I should use the 3.3.0 version of profobuf. I had the 2.6.x before, and it worked without any problem. Than I changed it to 3.3 (after when I saw first time this error) and still got the same error message, so I switched back to the original 2.6.x that DIGITS is using. Its quite frustrating. All I could guess is that the original error is not caused by the wrong version of protobuf but by something else.

Any help or ideas are appreciated and more than welcome!

**Comment by chalesguo** [comment]
In Ubuntu16.04, the version of protoc installedis 2.6. *, Which led to version conflict. To make sure your protoc version:
protoc --version
libprotoc 2.6.1
You can upgrade your protoc like:
sudo add-apt-repository ppa:maarten-fonville/protobuf
sudo apt-get update

**Comment by ethantang95** [comment]
This issue is being addressed and is in pull request review

**Comment by ethantang95** [comment]
#1749

**Comment by ethantang95** [comment]
To fix this, you need to build protobuf 3.2.x from source. Then rebuild caffe.

**Comment by tamasbalassa** [comment]
Thanks for your answer @chalesguo , I believe that could solve the problem.

However I already managed it, but reinstalling DIGITS with synaptic (I simply removed it and installed again). Now I have still the 2.6.1 version of protobuf and DIGITS works well.

**Comment by guiklink** [comment]
I got the exactly same problem and can't get to a solution either way. I have attached my log bellow:

I0410 21:09:30.708613 10995 net.cpp:159] Memory required for data: 1272062728
I0410 21:09:30.708614 10995 layer_factory.hpp:77] Creating layer cluster
[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
what():  This program requires version 3.5.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)
*** Aborted at 1523419771 (unix time) try "date -d @1523419771" if you are using GNU date ***
PC: @     0x7f6ddd101428 gsignal
*** SIGABRT (@0x3e800002af3) received by PID 10995 (TID 0x7f6ddf451b00) from PID 10995; stack trace: ***
@     0x7f6ddd1014b0 (unknown)
@     0x7f6ddd101428 gsignal
@     0x7f6ddd10302a abort
@     0x7f6ddd73b84d __gnu_cxx::__verbose_terminate_handler()
@     0x7f6ddd7396b6 (unknown)
@     0x7f6ddd739701 std::terminate()
@     0x7f6ddd739919 __cxa_throw
@     0x7f6ddc9b8647 google::protobuf::internal::LogMessage::Finish()
@     0x7f6ddc9b887d google::protobuf::internal::VerifyVersion()
@     0x7f6b02393967 protobuf_google_2fprotobuf_2fdescriptor_2eproto::InitDefaultsFileDescriptorSetImpl()
@     0x7f6ddc9b8f75 google::protobuf::GoogleOnceInitImpl()
@     0x7f6b0238da45 protobuf_google_2fprotobuf_2fdescriptor_2eproto::InitDefaultsFileDescriptorSet()
@     0x7f6b0238e5d9 protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptorsImpl()
@     0x7f6ddc9b8f75 google::protobuf::GoogleOnceInitImpl()
@     0x7f6b0238ebf5 protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors()
@     0x7f6ddf2ef6ba (unknown)
@     0x7f6ddf2ef7cb (unknown)
@     0x7f6ddf2f48e2 (unknown)
@     0x7f6ddf2ef564 (unknown)
@     0x7f6ddf2f3da9 (unknown)
@     0x7f6dc23bff09 (unknown)
@     0x7f6ddf2ef564 (unknown)
@     0x7f6dc23c0571 (unknown)
@     0x7f6dc23bffa1 dlopen
@     0x7f6dddd578cd _PyImport_GetDynLoadFunc
@     0x7f6ddddc653e _PyImport_LoadDynamicModule
@     0x7f6ddddc7380 (unknown)
@     0x7f6ddddc7648 (unknown)
@     0x7f6ddddc875b PyImport_ImportModuleLevel
@     0x7f6dddd328a8 (unknown)
@     0x7f6dddd8b263 PyObject_Call
@     0x7f6ddde61477 PyEval_CallObjectWithKeywords
