### ISSUE TITLE
How to export segmented results?

### ISSUE THREAD

**Issue by FangliangBai** [NVIDIA/DIGITS#1713]
Does any one know how to export the inference result after the test? The visualisation process is great but I also want to save the final segmentation results for later use.

**Comment by druedaplata** [comment]
I thought we would have a way to use the Api for segmentation or detection, but I think is only possible for classification, for now maybe?

**Comment by FangliangBai** [comment]
@druedaplata  Yes, I saw someone used API to export calcification results.
For now, if one must use the segmented results, one has to change the variable in `inference.py` where the output path of `hdf5 data` was defined. Then, use some tools to open the hdf5 file. I used `Matlab`.

I haven't found an easier way to export results.

**Comment by zhuozhongshuo** [comment]
@FangliangBai Hi ! I am thinking about your question, but I can not find the way to do it. Have you finish it?And could you tell me how to do at last? Thanks!
