### ISSUE TITLE
What version of protobuf is suitable for DIGITS?

### ISSUE THREAD

**Issue by Seakia** [NVIDIA/DIGITS#1718]
hello, I encounter one question. My DIGITS cannot visualize the network when I click it then it popup one window says 
 > 'google.protobuf.pyext._message.RepeatedScalarConta' object has no attribute '_values

The protobuf which I used is version 3.2.0. Some previous issues say it's about the version of protobuf, so I downgrade to version 2.6.1 of protobuf. Under this version, the NV-Caffe which is needed by DIGITS can be compiled but the original BVLC-Caffe occurred errors when “make test”. And the protobuf 3.2.0 works well for original BVLC-Caffe.

Can you give some suggests?
Thanks

**Comment by lukeyeager** [comment]
DIGITS is only tested with pb2.
* https://github.com/NVIDIA/DIGITS/blob/v5.0.0/requirements.txt#L4
* https://github.com/NVIDIA/DIGITS/blob/v5.0.0/docs/BuildCaffe.md#dependencies

**Comment by Seakia** [comment]
I solved the problem using protobuf 3.2.0
Thanks

**Comment by IvyGongoogle** [comment]
@Seakia `protobuf 3.2.0` does work for me. `protobuf 3.1.0` works.
