### ISSUE TITLE
How to batch multiple caffe trainings in DIGITS?

### ISSUE THREAD

**Issue by ToruHironaka** [NVIDIA/DIGITS#173]
Is there any way to run multiple caffe trainings sequentially in one batch file in DIGITS?

**Comment by lukeyeager** [comment]
I'm not sure what you mean by "batch file."

You can interact with DIGITS programmatically with the REST API. Does that provide what you need?
https://github.com/NVIDIA/DIGITS/blob/digits-2.0/docs/API.md

**Comment by ToruHironaka** [comment]
I like to train multiple image datasets so I need to run each dataset at one time on DIGITS manually on my browser. I like to write a program to train multiple datasets at once automatically.

**Comment by lukeyeager** [comment]
> I'd like to write a program to train multiple datasets at once automatically.

Use curl to interface with the REST API:
https://github.com/NVIDIA/DIGITS/blob/digits-2.0/docs/GettingStarted.md#using-the-rest-api
