### ISSUE TITLE
Caffe layers.

### ISSUE THREAD

**Issue by mahfuj9346449** [NVIDIA/DIGITS#1736]
I am creating a custom caffe layer. I want to put this in digits. So how can we do that ?

**Comment by ethantang95** [comment]
In the current digits 6 RC build, custom caffe layers is broken due to protobuf migration. You can use DIGITS 5 to create custom caffe layers VIA this guide: https://github.com/NVIDIA/DIGITS/tree/v5.0.0/examples/python-layer

**Comment by mahfuj9346449** [comment]
Thnx.
