### ISSUE TITLE
Caffe path

### ISSUE THREAD

**Issue by mahfuj9346449** [NVIDIA/DIGITS#1737]
I am installing digits by using the command [sudo apt-get install digits]
How to show caffe path in DIGITS ?

**Comment by lukeyeager** [comment]
The `caffe-nv` deb package is a dependency of the `digits` package. That package contains the caffe executable.
```
$ dpkg-query -L caffe-nv | grep bin/
/usr/bin/caffe
```
If you don't set the `CAFFE_ROOT` environment variable, DIGITS looks for caffe on standard paths:
https://github.com/NVIDIA/DIGITS/blob/v5.0.0/digits/config/caffe.py#L224-L229

**Comment by mahfuj9346449** [comment]
Is it possible to use other caffe version ? Because I am getting error of installing caffe-nv.

**Comment by lukeyeager** [comment]
There are many ways to install Caffe+DIGITS. Look at the README and pick whatever seems simplest to you. FWIW, that error makes it look like you're missing the NVIDIA driver.

**Comment by mahfuj9346449** [comment]
Actually I installed Digits with existing caffe  and I am following the tutorial.
https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md

can you tell the reason of that error? Thanks in advanced.

Traceback (most recent call last):
  File "digits/scheduler.py", line 512, in run_task
    task.run(resources)
  File "digits/task.py", line 189, in run
    self.before_run()
  File "digits/model/tasks/caffe_train.py", line 218, in before_run
    self.save_files_classification()
  File "digits/model/tasks/caffe_train.py", line 530, in save_files_classification
    (train_data_layer.data_param.batch_size * solver.iter_size)
AttributeError: 'SolverParameter' object has no attribute 'iter_size'

**Comment by lukeyeager** [comment]
Ok, I guess you solved your Caffe installation problem, then. I'll close this.

Looks like you built an old version of caffe which doesn't have `iter_size`.

**Comment by mahfuj9346449** [comment]
Thanks and it works.
