### ISSUE TITLE
Visualization with Caffe does not work due to protobuf incompatabilities

### ISSUE THREAD

**Issue by ethantang95** [NVIDIA/DIGITS#1738]
Issues related to migrating from protobuf 2 to protobuf 3 for tensorflow

**Comment by lukeyeager** [comment]
Other bug reports: https://github.com/NVIDIA/DIGITS/issues/591, https://github.com/NVIDIA/caffe/issues/303

Upstream fixes: https://github.com/BVLC/caffe/pull/5010, https://github.com/BVLC/caffe/pull/5477, https://github.com/BVLC/caffe/pull/5487

**Comment by ethantang95** [comment]
Fixed as of today
