### ISSUE TITLE
Can I move .digit/jobs folder to my other internal hard drive?

### ISSUE THREAD

**Issue by ToruHironaka** [NVIDIA/DIGITS#175]
Is there any way to reset .digit/job directory to my other internal hard drive? My home directory did not have many hard drive spaces.

**Comment by lukeyeager** [comment]
Sure!

1. Shut down DIGITS
2. Move the folder
3. Reconfigure DIGITS with `./digits-devserver --config` to point to the new jobs directory

**Comment by ToruHironaka** [comment]
Can I move back to my home directory again by doing the steps 1 ~ 3?

**Comment by lukeyeager** [comment]
Yes.

**Comment by fdbf** [comment]
Hi, 

I have the same need. I tried this but without success. Jobs folder remains the same. I tried also to:
- DIGITS_JOBS_FOLDER=[desired path], then export DIGITS_JOBS_FOLDER
no success

What should I do? Running DIGITS 4.0

Thanks, 

Fabio

**Comment by lukeyeager** [comment]
When using deb packages please follow these instructions for changing the configuration:
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md#troubleshooting

**Comment by shohan6** [comment]
@lukeyeager How to change Job location on Digits 5.   I've tried above methods but fails....

**Comment by gheinrich** [comment]
Hello @slayton58 please refer to these instructions for DIGITS 5.0 configuration: https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/Configuration.md

**Comment by shohan6** [comment]
Dear @gheinrich 
I could not figure out how to use the Environment variable... Suppose I want to change the Job directory to "/mnt/Programs/digits_jobs" location. How I set this values to DIGITS_JOBS_DIR? is it like following in terminal?
export DIGITS_JOBS_DIR=/mnt/Programs/digits_jobs

another question is that how to stop/start digits server in DIGITS 5

**Comment by gheinrich** [comment]
Hello, see https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/BuildDigits.md#starting-the-server
