### ISSUE TITLE
Why DIGITS inference in Semantic segmentation shows better results ... ?!

### ISSUE THREAD

**Issue by VanitarNordic** [NVIDIA/DIGITS#1750]
@gheinrich 

Hello,

These are two inferences, one from DIGITS internal inference part and another from the code which I've found. I considered everything but DIGITS results are better and finer. 
Models are exactly the same and no mistake was happened. Have you done something more in the inference part?

DIGITS's result:
![screenshot from 2017-07-27 21-08-17](https://user-images.githubusercontent.com/18719591/28681782-ebe557ac-730f-11e7-9695-f524b2927e57.png)

My result:
![0259_out](https://user-images.githubusercontent.com/18719591/28681702-9fb6af66-730f-11e7-9bf8-0bab19b81b1d.png)

```
import sys
from os import listdir
from os.path import isfile, join
import cv2
import numpy as np
from PIL import Image
import time
import caffe

caffe.set_mode_gpu()

#caffe.set_mode_cpu() # Use CPU for the calculations

print 'Reading the network and model'

NET_FILE = 'deploy.prototxt'
MODEL_FILE = 'snapshot_iter_1356.caffemodel'
net = caffe.Net(NET_FILE, MODEL_FILE, caffe.TEST)

directory = 'images/' # Path to the image sequence
files = listdir(directory)
files.sort()

image_files = [files[i] for i in range(0, files.__len__(), 1) if files[i][-3:] == 'jpg'] #Get only image files

print 'Starting processing'
total_time = 0 # To measure the average time taken
for file_name in image_files:
        print 'Processing image: ' + file_name
        im = Image.open(join(directory, file_name))
        in_ = np.array(im, dtype=np.float32) # Preprocess the image to make it similar to the training data
        in_ = in_[:,:,::-1]
        in_ -= np.array((97, 119, 145))
        in_ = in_.transpose((2,0,1))

        net.blobs['data'].reshape(1, *in_.shape) # Reshape the network according to the image size
        net.blobs['data'].data[...] = in_
        start = time.time()
        net.forward() # Run the network for the given input image
        end = time.time()
        print 'Time taken = ' + str(end - start)
        total_time += end - start

        out = net.blobs['score'].data # Extract the output
        out = out.argmax(axis=1) # Get the labels at each pixel
        out = out.transpose(1, 2, 0) # Reshape the output into an image
        out = np.tile(out, (1,3))
        out[out != 0] = 255 # 7 is the label 'car'
        out[out == 0] = 0

        out_file_name = file_name[:-4] + '_out.png'
        cv2.imwrite(out_file_name, out)

print 'Done'
print 'Average time taken = ' + str(total_time/image_files.__len__())


```

**Comment by MichalZajac** [comment]
Hi,

Could you please tell us how did you solve the problem? If you did.
I am experiencing the same problem. Maybe it could help me to.

Thank you in advance.

**Comment by VanitarNordic** [comment]
Yes, because you have fined-tuned the model, you should rename the layer in the code also to match with the fine-tuned model, otherwise if you don't do, it will use the results of the above layers.

**Comment by MichalZajac** [comment]
Actually I use C++ and I have different problem... 
![cpp](https://user-images.githubusercontent.com/2526450/32720706-a1430a8c-c864-11e7-8d75-a4cd29132580.png)
![digits](https://user-images.githubusercontent.com/2526450/32720707-a15e1fc0-c864-11e7-8334-d266ad9d634c.png)

The image from digits seems like postprocessed, but from c++ it has different shape and somewhat "blocky" result....

But thank you for sharing your solution.

**Comment by Manugoyal123** [comment]
Hi VanitarNordic,

I am new to the digits and caffe. I am facing the same issue. Can you explain in which code, layers should be renamed?

Thanks and regards,
Manu.

**Comment by VanitarNordic** [comment]
@Manugoyal123 
the layer which you have already renamed for fine tuning

**Comment by Manugoyal123** [comment]
in_ -= np.array((97, 119, 145)) 

I am sorry, but how do you calculate this value?
