### ISSUE TITLE
Error for '--config' argument

### ISSUE THREAD

**Issue by gunju** [NVIDIA/DIGITS#1754]
I am trying to configure the path for digits to updated caffe.

But, the command './digits-devserver --config' throws error stating that unrecognized argument.

The digits version is 6.0.

**Comment by gunju** [comment]
I used

**Comment by gunju** [comment]
I downloaded previous version of digits(4.0). In that there is option of '--config'. But, how to to do the same in new versions?

**Comment by lukeyeager** [comment]
Please read the release notes for DIGITS 5.0: https://github.com/NVIDIA/DIGITS/releases/tag/v5.0.0-rc.1

This was the change: https://github.com/NVIDIA/DIGITS/pull/1091

And here is the new documentation you're looking for: https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/Configuration.md
