### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version - ONLY DOCKER

### ISSUE THREAD

**Issue by gismo07** [NVIDIA/DIGITS#1769]
Right now I have two installations of Digits:

- The 'old' way installation using the ubuntu dep packages
- The new way using the provided docker image

The old installation works like expected, but if I want to train on the docker image there appears to be something wrong with the cuda support:

> Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version

`sudo nvidia-docker run --rm nvidia/cuda nvcc --version` prints: 

```
NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61 
```

And `sudo nvidia-docker run --rm nvidia/cuda nvidia-smi` prints:
```
Tue Aug  8 08:36:55 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro P5000        Off  | 0000:03:00.0      On |                  Off |
| 26%   35C    P8     8W / 180W |    416MiB / 16269MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

How can I fix this issue?

**Comment by gismo07** [comment]
Ok I found the solution right after creating the issue:
Instead of `sudo docker run -v /home/ubuntu/nvDocker/:/data/ -p 5000:5000 nvidia/digits:6.0-rc` I have to use `sudo nvidia-docker run -v /home/ubuntu/nvDocker/:/data/ -p 5000:5000 nvidia/digits:6.0-rc`

Maybe master/docs/DockerInstall.md should be updated.

**Comment by ethantang95** [comment]
Updated in PR #1767

**Comment by lidonglei** [comment]
thankyou for your resolutions! really!

**Comment by lidonglei** [comment]
Thankyou for your solutions! really!
