### ISSUE TITLE
Best way to approach building a pixel classifier

### ISSUE THREAD

**Issue by OliverColeman** [NVIDIA/DIGITS#177]
I'm currently using Caffe to build a pixel classifier (e.g. D. Ciresan et al - Mitosis Detection in Breast Cancer Histology Images using Deep Neural Networks, MICCAI 2013). I'm wondering what the best approach would be to set-up a pixel classifier in DIGITS? Has anyone done this? (I couldn't find any examples).

I'm interested in using DIGITS as it seems to have a much nicer, faster work flow. I seem to spend an awful lot of time editing text files for Caffe (want to change a parameter? Then you have to update it over several different files, same for when your database size changes, or you want to use a different db, etc), which is becoming very cumbersome and error prone.

**Comment by lukeyeager** [comment]
I'm working on an interface for "generic" neural networks right now. You'll have to upload your own prebuilt LMDB files for now, but you can use any type of Caffe network you like. That should enable you to do per-pixel segmentation with DIGITS.

Hopefully I'll have something on the `master` branch within a week or two.

**Comment by lukeyeager** [comment]
See #189.
