### ISSUE TITLE
 TypeError: init() got an unexpected keyword argument 'syntax'

### ISSUE THREAD

**Issue by danbuckler** [NVIDIA/DIGITS#178]
So I have NVIDIA-caffe-0.11.0 and DIGITS and protobuf 2.6.1 and when I run digits-devserver as soon ad I provide the path for the caffe install I get an error stack cumlinating in TypeError: init() got an unexpected keyword argument 'syntax'. I have protobuf 2.6.1 installed. protoc --version yields libprotoc 2.6.1

**Comment by lukeyeager** [comment]
Can you provide the full stacktrace?

I suspect this is some sort of library mismatch. I'm also looking at https://github.com/BVLC/caffe/issues/2092.

**Comment by danbuckler** [comment]
root@ubuntu4caffe:~/NVIDIA-caffe-0.11.0/caffe/DIGITS# ./digits-devserver
Default value for caffe_root "<PATHS>" invalid:
        caffe binary not found in PATH
==================================== Caffe =====================================
Where is caffe installed?

        Suggested values:
        (P*) [PATH/PYTHONPATH] <PATHS>
>> /root/NVIDIA-caffe-0.11.0/caffe
Using "/root/NVIDIA-caffe-0.11.0/caffe"

Traceback (most recent call last):
  File "./digits-devserver", line 42, in <module>
    config.load_config('quiet')
  File "/root/NVIDIA-caffe-0.11.0/caffe/DIGITS/digits/config/load.py", line 147, in load_config
    option.apply()
  File "/root/NVIDIA-caffe-0.11.0/caffe/DIGITS/digits/config/caffe_option.py", line 232, in apply
    import caffe
  File "/root/NVIDIA-caffe-0.11.0/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/root/NVIDIA-caffe-0.11.0/caffe/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "/root/NVIDIA-caffe-0.11.0/caffe/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/root/NVIDIA-caffe-0.11.0/caffe/python/caffe/proto/caffe_pb2.py", line 23, in <module>
    nels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01')
TypeError: __init__() got an unexpected keyword argument 'syntax'
root@ubuntu4caffe:~/NVIDIA-caffe-0.11.0/caffe/DIGITS# protoc --version
libprotoc 2.6.1
root@ubuntu4caffe:~/NVIDIA-caffe-0.11.0/caffe/DIGITS# libprotoc 2.6.1
libprotoc: command not found
root@ubuntu4caffe:~/NVIDIA-caffe-0.11.0/caffe/DIGITS#

**Comment by lukeyeager** [comment]
I've never seen that before.

Can you try upgrading to [NVIDIA/Caffe v0.12](https://github.com/NVIDIA/caffe/tree/caffe-0.12)? You may also need to upgrade to [DIGITS v2.0](https://github.com/NVIDIA/DIGITS/tree/digits-2.0) if you haven't already.

**Comment by danbuckler** [comment]
Thanks Luke - That's fixed it.

On Fri, Jul 24, 2015 at 11:40 AM, Luke Yeager <notifications@github.com>
wrote:

> I've never seen that before.
>
> Can you try upgrading to NVIDIA/Caffe v0.12
> <https://github.com/NVIDIA/caffe/tree/caffe-0.12>? You may also need to
> upgrade to DIGITS v2.0 <https://github.com/NVIDIA/DIGITS/tree/digits-2.0>
> if you haven't already.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NVIDIA/DIGITS/issues/178#issuecomment-124618970>.
>



-- 
____________________
Dan Buckler
dan.buckler@gmail.com

**Comment by dongx12** [comment]
So how do you solve this problem ? Is that the same error ? 

>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "caffe/proto/caffe_pb2.py", line 23, in <module>
    x01(\r:\x01\x30\x12\x1d\n\x10\x64\x65t_fg_threshold\x18\x36 \x01(\x02:\x03\x30.5\x12\x1d\n\x10\x64\x65t_bg_threshold\x18\x37 \x01(\x02:\x03\x30.5\x12\x1d\n\x0f\x64\x65t_fg_fraction\x18\x38 \x01(\x02:\x04\x30.25\x12\x1a\n\x0f\x64\x65t_context_pad\x18: \x01(\r:\x01\x30\x12\x1b\n\rdet_crop_mode\x18; \x01(\t:\x04warp\x12\x12\n\x07new_num\x18< \x01(\x05:\x01\x30\x12\x17\n\x0cnew_channels\x18= \x01(\x05:\x01\x30\x12\x15\n\nnew_height\x18> \x01(\x05:\x01\x30\x12\x14\n\tnew_width\x18? \x01(\x05:\x01\x30\x12\x1d\n\x0eshuffle_images\x18@ \x01(\x08:\x05\x66\x61lse\x12\x15\n\nconcat_dim\x18\x41 \x01(\r:\x01\x31\x12\x36\n\x11hdf5_output_param\x18\xe9\x07 \x01(\x0b\x32\x1a.caffe.HDF5OutputParameter\".\n\nPoolMethod\x12\x07\n\x03MAX\x10\x00\x12\x07\n\x03\x41VE\x10\x01\x12\x0e\n\nSTOCHASTIC\x10\x02\"W\n\x0ePReLUParameter\x12&\n\x06\x66iller\x18\x01 \x01(\x0b\x32\x16.caffe.FillerParameter\x12\x1d\n\x0e\x63hannel_shared\x18\x02 \x01(\x08:\x05\x66\x61lse*\x1c\n\x05Phase\x12\t\n\x05TRAIN\x10\x00\x12\x08\n\x04TEST\x10\x01')
TypeError: __init__() got an unexpected keyword argument 'syntax'
>>>

**Comment by lukeyeager** [comment]
This looks like a problem with protobuf - https://github.com/BVLC/caffe/issues/2092.

Have you installed protobuf 3.0? You may need to roll back to 2.6.

**Comment by dongx12** [comment]
Thank you Luke, I update the protobuf2.5 to protobuf2.6, and it works well~

**Comment by austingg** [comment]
I installed protobuf 3.1, and also met this problem?  Do I need to roll back to 2.6 ?

**Comment by austingg** [comment]
It works after I unify the versions of python protobuf and protoc .
