### ISSUE TITLE
Problem adding Tensorflow to DIGITS 6

### ISSUE THREAD

**Issue by MohammadMoradi** [NVIDIA/DIGITS#1789]
Hi, I have already installed tensorflow using pip install and tested it but when I run digits 6 it says that tensorflow support is disabled. Is there any variable that I should define?
 `  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.0.0-rc.1

Tensorflow support disabled.
`Thanks in advance

**Comment by ethantang95** [comment]
Nope, there are no variables to define for Tensorflow. FYI DIGITS uses Tensorflow 1.2.1 so it will use cuDNN 5 instead of 6 as Tensorflow 1.3 just came out a few days ago

**Comment by MohammadMoradi** [comment]
Thanks @ethantang95 . The problem was Tensorflow version. It should be 1.2.1. Also cuDNN 5 not 6 as you said.
