### ISSUE TITLE
Error: "Folder does not exist or is not reachable" - Permissions checked

### ISSUE THREAD

**Issue by Weihnachtswurst** [NVIDIA/DIGITS#1809]
When creating a new _Object Detection Dataset_ the following errors occur:

> train_image_folder
    Folder does not exist or is not reachable

> train_label_folder
    Folder does not exist or is not reachable

I checked the permissions - they seem to be fine as far as I can tell (note that ubuntu is not my everyday os):

    ~$ namei -o -v /digits/kitti-data/train/images/000000.png
    f: /digits/kitti-data/train/images/000000.png
    d root root     /
    d root www-data digits
    d root www-data kitti-data
    d root www-data train
    d root www-data images
    l root www-data 000000.png -> /digits/kitti-data/raw/training/image_2/000000.png
    d root root       /
    d root www-data   digits
    d root www-data   kitti-data
    d root www-data   raw
    d root www-data   training
    d root www-data   image_2
    - root www-data   000000.png

There are also no (relevant?) error messages from DIGITS:

    ~$ sudo nvidia-docker run -v /home/dnndev/digits/ -p 5000:5000 nvidia/digits:latest
    [sudo] password for dnndev: 
    libdc1394 error: Failed to initialize libdc1394
      ___ ___ ___ ___ _____ ___
     |   \_ _/ __|_ _|_   _/ __|
     | |) | | (_ || |  | | \__ \
     |___/___\___|___| |_| |___/ 5.0.0

    2017-08-31 21:51:02 [INFO ] Loaded 0 jobs.

The OS is a clean Ubuntu 16.04.3 LTS.

__Why does this error appear although www-data has access to the files & folders?__

**Comment by lukeyeager** [comment]
Try `-v /home/dnndev/digits:/home/dnndev/digits`. Also, I'm not sure if the user inside the docker container is actually `www-data` - those are instructions regarding deb packages, not docker images.

**Comment by Weihnachtswurst** [comment]
This solved the problem for me. Thank you => close.

I would be interested what diffrence `-v /home/dnndev/digits:/home/dnndev/digits` made?
