### ISSUE TITLE
Following getting started, getting Folder does not exist error

### ISSUE THREAD

**Issue by EMCP** [NVIDIA/DIGITS#1815]
I noticed this https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/GettingStarted.md script puts the datset on top of the home folder

```
$ python -m digits.download_data mnist ./mnist
Downloading url=http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz ...
Downloading url=http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz ...
Uncompressing file=train-images-idx3-ubyte.gz ...
Uncompressing file=train-labels-idx1-ubyte.gz ...
Uncompressing file=t10k-images-idx3-ubyte.gz ...
Uncompressing file=t10k-labels-idx1-ubyte.gz ...
Reading labels from ./mnist/train-labels.bin ...
Reading images from ./mnist/train-images.bin ...
Reading labels from ./mnist/test-labels.bin ...
Reading images from ./mnist/test-images.bin ...
Dataset directory is created successfully at './mnist'
Done after 18.8859930038 seconds.
$ cd mnist
$ ls
t10k-images-idx3-ubyte.gz  test             test-labels.bin  train-images.bin            train-labels.bin
t10k-labels-idx1-ubyte.gz  test-images.bin  train            train-images-idx3-ubyte.gz  train-labels-idx1-ubyte.gz
$ cd test
$ pwd
/home/emcp/Dev/temp/digits_ex/mnist/test
```

Is that a requirement?? because I elected to place it in a sub-folder, but now seeing errors upon attempts to create the dataset

![screenshot from 2017-09-07 10-07-01](https://user-images.githubusercontent.com/3691722/30152720-58dce144-93b4-11e7-8cb5-cf23e94481a4.png)

Update : for kicks i downloaded the dataset to the original path request.. same result.  Folder does not exist.  I'm going to check the permissions but it would help to know where this call in the code is so i could perhaps debug.. 

folder permissions look fine

![screenshot from 2017-09-07 10-36-06](https://user-images.githubusercontent.com/3691722/30153892-73380e7a-93b8-11e7-9c8d-effea26bd09c.png)

**Comment by lukeyeager** [comment]
Is this a deb package install? If so, read this: https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md#permissions
