### ISSUE TITLE
DIGITS 6 looks for Protobuf compiler 3.2.0 even though Caffe can run with 2.6.1

### ISSUE THREAD

**Issue by kanakiyab** [NVIDIA/DIGITS#1839]
Hi,

I recently built DIGITS on Google Cloud platform by following instructions as per [the guidelines](https://github.com/dusty-nv/jetson-inference#system-setup).

Everything worked fine during installation but when I started training a model, it shows ERROR Code -6 and model fails to train. Upon examining the log and then running `digits-test`, I found the following error. 

`[libprotobuf FATAL google/protobuf/stubs/common.cc:61] This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)`

`terminate called after throwing an instance of 'google::protobuf::FatalException'`

`what():  This program requires version 3.2.0 of the Protocol Buffer runtime library, but the installed version is 2.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "google/protobuf/descriptor.pb.cc".)`

`*** Aborted at 1506645428 (unix time) try "date -d @1506645428" if you are using GNU date ***
PC: @     0x7fda5d10b428 gsignal`

`*** SIGABRT (@0x3ea00002633) received by PID 9779 (TID 0x7fda5f433ac0) from PID 9779; stack trace: ***`

This is from the `caffe_output.log` file. The output from the test file is also similar.

Are there any steps that need to be updated in the installation steps? I think the `sudo apt-get install protobuf-compiler libprotobuf-dev` installs ver 2.6.1 by default

**Comment by ethantang95** [comment]
You have to build protobuf from source to get anything above version 3. The Deb package is version 2.6.1 still

**Comment by kanakiyab** [comment]
I agree with you based on the error message. But maybe the setup installations need to be updated for the same? That's the reason I created the issue.

Working on the Protobuf installation from the source for ver 3.2.0

**Comment by ethantang95** [comment]
The documentation does have a portion for building protobuf from source for digits 6

**Comment by kanakiyab** [comment]
I may have missed that! 

Couldn't see it on [DIGITS setup instructions](https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md) nor on [dusty-nv/jetson-inference instructions](https://github.com/dusty-nv/jetson-inference#system-setup).

What are the other places I should look for?

**Comment by kanakiyab** [comment]
Found it [here](https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildProtobuf.md). I was expecting that maybe it was mentioned in the setup steps itself (links in prev comment above). 

Building with that instructions.
