### ISSUE TITLE
Bad results in Object detection example

### ISSUE THREAD

**Issue by jbasquiat** [NVIDIA/DIGITS#1892]
I have done the object detection tutorial but the results are poor in comparation with the graph that is shown in the tutorial:

[https://github.com/NVIDIA/DIGITS/blob/master/examples/object-detection/training-loss.jpg](url)

I have done 2 training and my results are this:

https://i.imgur.com/Jm0rUUZ.png
https://i.imgur.com/CjJBXNz.png

Why do I get similar values of loss but very different accuracy? The only difference from the tutorial is that my card has 4GB of memory and I use the batch values provided by the tutorial

**Comment by gheinrich** [comment]
Hello, you need to use the left axis to read precision, recall and mAP (the right axis is for accuracy, sorry if it's confusing).

**Comment by jbasquiat** [comment]
But precision ,recall and mAP are a percentage not?

**Comment by gheinrich** [comment]
Yes, so around 50% as per your graph.

**Comment by jbasquiat** [comment]
And why that difference between the example results and my results? I use the same dataset and the same neural network
