### ISSUE TITLE
Add ability to select which GPU to run on

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#19]
When creating a model, users should be able to select which GPU they want to use. This enhancement should be designed with multi-GPU in mind, so that when caffe or torch releases multi-GPU support, DIGITS will be ready to assign multiple GPUs to a job.

**Comment by dxj19831029** [comment]
em..Will single GPU selection mode release soon? I think it's really uesfull. :)

**Comment by lukeyeager** [comment]
Closed in 0089c40
