### ISSUE TITLE
No learning when using custom object detection dataset

### ISSUE THREAD

**Issue by aqader** [NVIDIA/DIGITS#1900]
Hello all, 

I'm currently training DetectNet on a custom dataset I have (of one specific logo) and I'm having an issue. Whenever I run the training process, I always end up with a graph like this: 

<img width="1201" alt="screen shot 2017-11-30 at 8 30 41 pm" src="https://user-images.githubusercontent.com/9979256/33463824-8e27ecd6-d60d-11e7-8c0f-4bf3cd671e64.png">

I only have one class right now, using the pretrained GoogleNet model, resized the images to 256x256 and have confirmed that my KITTI generation code should work. Any ideas as to what's going on?

**Comment by symepge** [comment]
Hello @aqader! I see that you closed this issue. Did you identify the problem? I am having the same issue. I would appreciate some guidance.
