### ISSUE TITLE
AttributeError 'tuple' object has no attribute 'astype'

### ISSUE THREAD

**Issue by AdamKisgergely** [NVIDIA/DIGITS#1905]
Succefully isntalled the Nvidia digits 6.0 with caffe 0.15, CUDA 9.0 and cudNN 7.5 on Ubuntu 16.04 LTS. Tested with the lenet tutorial image classification tutorial and worked fine. After that i managed to create an own network to sematic-segmentation by this guide:

https://github.com/NVIDIA/DIGITS/tree/master/examples/semantic-segmentation

The raw data test part working as it should, i got the pictures and the diagrams, but i would like to see the final resolution of my network. But when i tried to test with visualization method & interface form segmentation(as in in guide) to get the segmentated picture it crash with the following error:

AttributeError 'tuple' object has no attribute 'astype'

Caffe show zero information about the problem, just start job, task complete and deleted.
How could i make it work?

**Comment by neel04** [comment]
I have the same problem, could you tell me how did you solve it?
