### ISSUE TITLE
DetectNet error code -6

### ISSUE THREAD

**Issue by daylanc** [NVIDIA/DIGITS#1936]
I am trying to follow the detection tutorial (https://devblogs.nvidia.com/parallelforall/deep-learning-object-detection-digits/) using KITTI data. I follow the directions but get the following error when I start to run the model:

Error: error code -6
Memory required for data: 3800242856
Creating layer cluster

I tried to search for solutions, but most of them say it could be an openCV issue or protobuf issue, but I cannot figure it out.

**Comment by earlysleepearlyup** [comment]
@daylanc hello! I met the same error with you.Did you have solve it? Could you help me? Thank you !

**Comment by AKASH2907** [comment]
@daylanc I am dealing with the same error. Could you please help me? Thank You

**Comment by earlysleepearlyup** [comment]
@AKASH2907 I solved this error! You can download the `caffe-output.log` , and then find out the error. My error is the protobuf uncompatibility problem. I finally solve this problem by installing the protobuf 3.2.0.

**Comment by AKASH2907** [comment]
@earlysleepearlyup I looked into my caffe-output.log. I was having the same problem that it was showing protobuf 2.5.0is connected not 3.2.0. However, I downloaded and installed and now due to protobuf installation from github repo, my caffe compilation is stopped at 89%.
