### ISSUE TITLE
Export model and its related files as a tar

### ISSUE THREAD

**Issue by jmozah** [NVIDIA/DIGITS#194]
Today a model and its related files like deploy.prototxt, labels.txt, mean.jpg etc have to be picked up manually from the jobs dir. especially the labels.txt and mean..jpg has to be fished from a seperate directory... it would be nice if we have a export options which exports the following
- model (best snapshot)
- deploy.prototxt
- label.txt
- mean.jpg

**Comment by lukeyeager** [comment]
There's already a button for that.

![download-button](https://cloud.githubusercontent.com/assets/687269/9091475/6199674e-3b55-11e5-82de-f271fa931bc6.jpg)

Or you can access it directly (with more compression options) by using this url:

    /models/<job_id>/download.<extension>

https://github.com/NVIDIA/DIGITS/blob/v2.0.0-rc3/docs/FlaskRoutes.md#modelsjob_iddownload
