### ISSUE TITLE
How to train to identify the color of a product?

### ISSUE THREAD

**Issue by Saneesh** [NVIDIA/DIGITS#198]
Hello,
I want to identify the color of apparels and accessories. Some of the tshirts may have multiple color like white with green colors.

How can I train this? what should be the folder structure and what are the images I have to store in those?
I have tried like this:
colors/red
colors/green
colors/black
colors/while
in the above folder structure, corresponding colored images of the products copied. if a product have multicolor same image copied in the corresponding colors. Then used AlexNet to create the models. 
for some of images it gives proper result but for some images the result is wrong.

Is this approach is fine? to get more accuracy what should I do?

**Comment by lukeyeager** [comment]
Please ask questions about general deep learning questions on the [user group](https://groups.google.com/d/forum/digits-users).

If you think of a way to improve the DIGITS documentation or to improve the UI for solving complex problems, please do open an issue with your suggestion.
