### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by bartos88** [NVIDIA/DIGITS#2]
Is there any way to set it to use CPU instead of GPU. I'm trying to explore this software from my home machine, which doesn't have an NVIDIA card. I'm getting this error:

```
Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
```

**Comment by moconnor725** [comment]
The caffé default configuration for DiGiTS is to have CUDNN on.  If you change the caffé Makefile.config to be CPU_ONLY, then DiGiTS should be able to drive caffé without a GPU.

**Comment by bartos88** [comment]
That worked. Thanks!
