### ISSUE TITLE
Latest info on setting up Spacenet building data to use with DetectNet in DIGITS

### ISSUE THREAD

**Issue by 00krishna** [NVIDIA/DIGITS#2022]
There are a couple of issues posted here about DetectNet and the the Spacenet Building Detection challenge. 

https://github.com/NVIDIA/DIGITS/issues/1011
https://github.com/NVIDIA/DIGITS/issues/980

**I was wondering if @jbarker-nvidia or anyone could point to the script for setting up the Spacenet data in DIGITS? Like is there a repository for the scripts, or any additional posts or text files that describe the process? Even a list of steps. Heck I would not mind writing up the example if someone could just help get me started. ** 

Seems like from a high level the steps were:
1. Resize the images to 1280x1280.
I think that DIGITS now has a "Resize Image" feature under the "Create Dataset" dialogue, so that should work for this step right. 

2. Convert the Spacenet GeoJson labels into the Kitti format labels. I think one of the issues below mentions a python script for this, but I was hoping someone might know where that script is located. It does not seem hard to write, but for those of us new to the LMDB format it might help to understand how the files are set up properly. 

The configuration for the model itself seems pretty straightforward with the information in the blog post (https://devblogs.nvidia.com/exploring-spacenet-dataset-using-digits/). 

Any help would really be appreciated.

**Comment by jbarker-nvidia** [comment]
@00krishna The exact pre-processing scripts we used internally are not shareable, but I can point you in the right direction for scripts that do the same thing.

There are a collection of SpaceNet challenge utilities here: https://github.com/SpaceNetChallenge/utilities

These include scripts to convert the raw geoTIFF data into other formats such as CSV.  At that point you should be able to easily convert the data to the Kitti labeling format as described here: https://github.com/NVIDIA/DIGITS/blob/digits-4.0/digits/extensions/data/objectDetection/README.md#label-format

Let me know if you hit any hurdles and I will try to help

**Comment by 00krishna** [comment]
Oh this is excellent. Thanks so much @jbarker-nvidia . I understand that you can't share the exact scripts, but your tips are invaluable. I think the only challenge was getting the data into the system. I just have some really simple questions that hopefully take very very little of your time. I tried to come up with answers as best I could, but perhaps you can let me know if I am incorrect. Some of this is just validating the assumption, haha. 

**Getting images into DIGITS/LMDB**
**Question 1. How do I converting GeoTIFF files to JPEG files?**
**Tentative Answer**: Use the `createDataSpaceNet.py` utility from the spacenet utilities directory to convert from geoTIFF format to JPEG. 

**Question 2. Can I use the 8 band images in DIGITS with DetectNet, or only the 3 band images? (Note: Part of my goal is to understand how the texture of adjacent locations affect the predictions).**
**Assumption/ Tentative Answer**: DetectNet is only designed for 3 band images, so you would need to tweak DetectNet to work with 8 band images. Also, the standard DIGITS object detection dataset creator will only take 3 bands. So to input the multiband images I would need to create my own LMDB and then import that LMDB into DIGITS. 

**Question 3. Can I use the "Resize Image" dialogue in DIGITS to resize the image to 1280x1280, as the blog post mentions? I remember in some of the github issues, you or someone was using GDAL to resize the images. So I wanted to make sure I did not lose information in the resizing, etc.**
**Tentative Answer:** ???? Not sure about the answer to this question. Posted to the user group list, but no one has responded on it yet: https://groups.google.com/forum/#!topic/digits-users/n4YtG4_GLtA

**Getting the Labels into DIGITS/LMDB** 
**Question 4. Will the conversion utility that changes GeoTIFF files to JPEG also convert the coordinates in the labels to the new JPEG coordinates?**
**Tentative Answer:** ???? I would assume that this is the case, but was not sure. I know that GeoTIFF files usually encode the Lat/Long coordinates. So when the file is changed to JPEG my assumption is that the coordinate system changes to something else, like the pixel value starting at (0,0,..). Of course I could be mistaken about the change in coordinate systems. But just wanted to confirm that the Spacenet utility will actually keep the synchronization between the coordinate locations in the Images and the coordinates in the labels.

Thanks so much for any assistance you can provide.

**Comment by jbarker-nvidia** [comment]
1. Correct you need to use a conversion utility.  In the SpaceNet utilities above it looks like they use OpenCV + GDAL.  See [here](https://github.com/SpaceNetChallenge/utilities/blob/master/python/spaceNetUtilities/dataTools.py) and [here](https://docs.opencv.org/3.0-beta/doc/tutorials/highgui/raster-gdal/raster_io_gdal.html)

2. I'm not 100% certain on this as I haven't used the latest versions of DIGITS, but it looks like you may be able to write a custom DIGITS plugin for using 8-band images as described [here](https://docs.nvidia.com/deeplearning/digits/digits-tutorial/index.html).  I believe the standard data loaders in DIGITS expect 3-band images. @gheinrich may correct me?

3. Yep - you should be able to use DIGITS to resize the images

4. I don't think there's anything JPEG or GeoTIFF specific about the coordinates unless you scale the images during the conversion, then obviously you need to scale the coordinates.

**Comment by 00krishna** [comment]
Great. I think I have all the data converted now. I am going to try and load it into DIGITS today. Thanks so much. If I get it all working, I am hoping to write a more detailed blog post about the preprocessing steps. Hopefully then you guys will get fewer questions :).
