### ISSUE TITLE
Converting Spacenet building labels into bounding boxes to comply with Kitti label standard

### ISSUE THREAD

**Issue by 00krishna** [NVIDIA/DIGITS#2026]
@jbarker-nvidia Say, I had a hopefully easy question for you. So according to the Kitti label standard, columns 5,6,7, and 8 are the coordinates of the box around some labeled item. For example:

Car 0.00 0 1.78 369.61 179.47 427.19 222.47 1.49 1.54 2.54 -7.80 1.75 26.65 1.50
Car 0.00 1 1.70 422.06 178.75 452.47 197.00 1.48 1.97 4.33 -14.70 2.00 61.51 1.47

This means that in this image there are two cars. The first car is at box coordinates [369.61 179.47 427.19 222.47], and the second car is at location [422.06 178.75 452.47 197.00]. 

Now the Spacenet geojson files give polygons surrounding the buildings instead of boxes. These boxes require more than 4 coordinates to specify them. 

**So the question was, did you have to just find the coordinates of the squares that best fit the polygons, and then use those newly computed squares as the labels?** That seems like the only way to be compliant with the standard. 

Just wanted to check and make sure I was on the right track, before spending a lot of time generating new box coordinates and labels.

**Comment by jbarker-nvidia** [comment]
Yes, I believe @allykgray used the minimum enclosing rectangle around the polygon

**Comment by 00krishna** [comment]
Excellent. Thanks.
