### ISSUE TITLE
DetectNet on DIGITS6.0, I could not run this sample using KITTY-data.

### ISSUE THREAD

**Issue by edwardcho** [NVIDIA/DIGITS#2040]
I started object detection on DIGITS6.0 using KITTY-data.
(I saw sample case on GitHub-site about object detection sample of DIGITS6.0.)

But I met this error.
"Layer's types are Ftype:FLOAT Btype:FLOAT Fmath:FLOAT Bmath:FLOAT
Importing Python module 'caffe.layers.detectnet.clustering'"

I checked the detection python folder of nvcaffe.
    .../python/caffe/layers/detectnet    => clustering.py, mean_ap.py, __init__.py

![image](https://user-images.githubusercontent.com/29569662/39506832-0a2bc50c-4e16-11e8-938e-209f14a69039.png)

![image](https://user-images.githubusercontent.com/29569662/39506750-7fd4a2ca-4e15-11e8-9fb4-cbe36be7fae4.png)

What I should do modify it for this solving??

**Comment by edwardcho** [comment]
I solved this problem. For detection process on DIGITS, need to another libraries.
  -. protobuf 3.5.0
  -. opencv

**Comment by galdalali** [comment]
Hi @edwardcho , I have extacly the same issue.
Didn't understand how exactly did you solved this?

I'm using:
opencv 3.3.1-dev 
NVCaffe 0.17.0
DIGITS 6.1.1

**Comment by edwardcho** [comment]
Hi @galdalali , 
Please check protobuf version on your system.

If protobuf version is less then 3.5, this error will occur when it start.
The protobuf version 3.5 (more than) should be installed on your system for this sample.
(Then you should re-build NVCaffe).

**Comment by mantianwuming** [comment]
Just try NVCaffe 0.15. Also I use opencv 3.4.0 but I think that opencv 3.3 is all right.

**Comment by MonkeyWithAComputer** [comment]
If you are using a dataset that has an image with more than about 600 labels it can cause this issue.

**Comment by Abhijeet-Bhilare** [comment]
@MonkeyWithAComputer How can I check if my image has more than 600 labels? Do you mean I need to check in lmdb file?
