### ISSUE TITLE
Set map_size for LMDB

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#206]
*@crohkohl, @danst18, I'm breaking the discussion in #203 out into a new issue.*

Here's the situation as I understand it. Please correct me if any of this is wrong.

`map_size` | Linux | OSX & Windows
------------ | ------------- | -------------
lower than size of dataset | LMDB runs out of memory | ?
higher than system memory | No problem | LMDB can't allocate enough memory

On Linux, you can just set it as high as you like and never see a problem. But that strategy blows up on other platforms.

> Should [map_size] be made configurable?
https://github.com/NVIDIA/DIGITS/pull/203#issuecomment-128859465

This is a sufficient but lazy solution. I would like to understand whether this can be avoided programmatically somehow before making a decision. My googling skills are failing me.

**Comment by crohkohl** [comment]
okay, my googling let to this issue: https://github.com/dw/py-lmdb/issues/85
It seams that the possible patch leads to a significant loss of speed.

However, I think a practical solution would be to parse the input data file in `create_db.py` and compute the total required size and give it a 50 mb buffer on top.

**Comment by lukeyeager** [comment]
Thanks for pointing out that issue on `py-lmdb`, that provides some good context.

> I think a practical solution would be to parse the input data file in create_db.py and compute the total required size and give it a 50 mb buffer on top.

How will you know how much data is required for each image / data point? Remember they may be encoded as PNGs or JPEGs, and they may be different resolutions as well.

**Comment by crohkohl** [comment]
> How will you know how much data is required for each image / data point? Remember they may be encoded as PNGs or JPEGs, and they may be different resolutions as well.

I think it is save to assume the non-encoded size as an upper bound which is `NumBytes=NumImages*shape[0]*shape[1]*shape[2]*sizeof(datatype)*sizeof(label)` bytes. It should be sufficiently large and much smaller than 1 TB. We can also use min(NumBytes,1TB) if we want to stick with the 1 TB.

**Comment by hyc** [comment]
If all you need is to do a bulk import, and never have to worry about adding new records later, you can just grow the file incrementally. Or you can use the windows sparse file patch and take the 10-20% performance hit.

**Comment by lukeyeager** [comment]
@hyc, thanks for joining the discussion!

The situation is actually the opposite. I'm only creating the databases in this context, and I don't need to read from them again - that's done with a different program (Caffe). So the memory-mapping isn't really helping at all. Can I open a write-only database in such a way that I don't need to provide a map_size at all?

**Comment by hyc** [comment]
No, there's no mode like that. But if you're creating a DB and know that no other thread will try to access it concurrently, you can just grow the map whenever you hit a MDB_MAP_FULL error. See the postfix LMDB driver for an example http://fossies.org/dox/postfix-2.11.6/slmdb_8c_source.html

**Comment by lukeyeager** [comment]
> just grow the map whenever you hit a MDB_MAP_FULL error

That could work. Thanks, I'll look into that!

**Comment by lukeyeager** [comment]
Frustratingly, py-lmdb doesn't expose any way to access the map_size directly.
https://github.com/dw/py-lmdb/blob/py-lmdb_0.86/lmdb/cpython.c#L1756-L1774

So it seems I have to close and re-open the environment. In my quick little test, this didn't seem to affect performance. I'm not sure what the implications are for a big dataset. Example changes here:

https://github.com/lukeyeager/DIGITS/commit/83e65f794671370d9ebc797e3a857048eea8d23d

@crohkohl, can you try this out and see what happens on Windows? I'll try it with a big dataset on my machine, too.

**Comment by hyc** [comment]
You can't use the env_info method?

**Comment by crohkohl** [comment]
@lukeyeager 
> can you try this out and see what happens on Windows? I'll try it with a big dataset on my machine, too.

In principle it works. However, I seem to get random crashes - could it be that the resizing is not thread-safe?

**Comment by lukeyeager** [comment]
> You can't use the env_info method?

It looks like that method is only for querying information.

**Comment by lukeyeager** [comment]
> I seem to get random crashes - could it be that the resizing is not thread-safe?

Thanks for the testing! That's certainly possible. See what happens if you set `write_threads` to 1.
https://github.com/lukeyeager/DIGITS/blob/83e65f7946/tools/create_db.py#L147

It seems to work on my machine, but race conditions like this can be tricky.

**Comment by dw** [comment]
@lukeyeager A `.set_mapsize` method for py-lmdb is easily implemented, I'm exploring this at present.

**Comment by crohkohl** [comment]
@lukeyeager 

> See what happens if you set write_threads to 1

Now it works perfectly - no crash anymore.

**Comment by crohkohl** [comment]
@lukeyeager 

this seems to work

at global level: `some_rlock = threading.RLock()`
and then in the `write_batch`:

```python
def write_batch(self, batch, allow_increase=True):
        """
        Write a batch to the database

        Arguments:
        batch -- an array of Datums
        """
        with some_rlock:
            keys = self.get_keys(len(batch))
            # ...
```

**Comment by lukeyeager** [comment]
@dw, thanks for chiming in! I'll keep a lookout for a new version of py-lmdb with that method. For now, I'll continue to recommend the latest version and implement this hack. If a new version goes up on PyPI, I'll recommend it in `requirements.txt` and use it.

**Comment by lukeyeager** [comment]
@crohkohl, good idea. Does that lock fix work even if `write_threads` is still set to 10?

**Comment by dw** [comment]
@lukeyeager It's uploaded already. Windows wheels will be up in about 15 minutes.

**Comment by crohkohl** [comment]
@lukeyeager yes, it still works with `write_threads` set to 10

**Comment by lukeyeager** [comment]
@crohkohl, I decided to just simplify things and go with one write thread - see https://github.com/dw/py-lmdb/issues/97#issuecomment-129967828.

I made a pull request to fix this at #209, would you mind giving it a try?

**Comment by crohkohl** [comment]
@lukeyeager, @dw  Thanks for the great efforts - it works perfectly!

**Comment by crohkohl** [comment]
Sorry I have to open that topic again but I feel that the 1 thread solution is not yet optimal.
I am currently importing a dataset with a few hundred thousand images.

With the recursive locking and multi-threading https://github.com/NVIDIA/DIGITS/issues/206#issuecomment-129656048 I get a significant speed up. The time prediction with the current implementation is approx. 18 hours vs. 12 hours for the multi-threaded import.

Could someone maybe try an imagenet import and confirm this observeration?

**Comment by lukeyeager** [comment]
Thanks for looking into it. I thought I remembered seeing similar results myself when I was testing this months ago. What do you think of this comment:

> LMDB is a single-writer design so you wouldn't see any performance gain using multiple writer threads.
https://github.com/dw/py-lmdb/issues/97#issuecomment-130018935

Maybe there's some intensive calculations in the write thread that can be moved into the read thread? I can't look into this today, but I'll check it when I get a chance.

**Comment by hyc** [comment]
What kind of data, computations, and volumes are you talking about here? For bulk loading a sequential data set, LMDB itself should be running at the full speed of the storage medium. That also assumes you're running with NOSYNC.

**Comment by crohkohl** [comment]
@hyc You are right it is running at full speed. After a clean restart of my system everything worked as expected. Sorry for the confusion!

**Comment by lukeyeager** [comment]
Great news, thanks!
