### ISSUE TITLE
Where is the "Use S3" tab for classification in Digits 6.0.0

### ISSUE THREAD

**Issue by chrishadiono** [NVIDIA/DIGITS#2078]
I wanted to follow this guide: https://github.com/NVIDIA/DIGITS/tree/master/examples/s3 to get the data from S3 into Digits. However, I do not have a "Use S3" tab when I go to create a dataset with Classification. I just have Use Image Folder and Use Text Files. Do I have to install something else to Digits to get this functionality? I did not see where this was specified if so. Thanks!

**Comment by pablogalaviz** [comment]
Any luck on that? I'm following the AWS instructions on DIGITS setup. I can't find a way to load the image from an S3 bucket. Also, is it possible to save the jobs on a separate S3 bucket? Thanks.

**Comment by chrishadiono** [comment]
turns out that Digits 6.0 doesn't have that function released yet, you can setup Digits with the master version though and that has the Use S3 functionality available. I don't know exactly what you mean for your second question, but I don't think you can.

**Comment by pablogalaviz** [comment]
For reference: 
1. Create an account on nvidia NGC.
2. Ssh into EC2 and login to docker NGC
```
$ docker login nvcr.io

Username: $oauthtoken
Password: <Your Key> 
```
3. Download the latest DIGITS image (use the command given on NGC). You may need to resize the instance root partition. 
4. Stop any digits container (ex.)
`$ docker container stop nvidia-digits`
5. Run the latest digit container (ex.) 
`$ docker run --runtime=nvidia --name digits -d -p 5000:5000 -p 6006:6006 -v ~/digits-jobs:/jobs -v ~/data:/data nvcr.io/nvidia/digits:18.07`
