### ISSUE TITLE
My dataset does not have "Explore the db" button

### ISSUE THREAD

**Issue by ArtlyStyles** [NVIDIA/DIGITS#2099]
I followed the "Train a regression network" example. After I generated the Gradient image dataset, there was a "Explorer the db" button on the DIGITS dataset page. When you clicked it, it showed all images in the dataset. 

The "Explorer the db" was also there for the MNIST dataset. 

My application is very similar to the example. So I changed the regression network image generation python script and used that to generate my own dataset for the "Other" type. However,  I do not see the "Explorer the db" button for my own dataset. So I really do not know what is inside my DB. Why did not I have the button? 

Also, is there a way to check the value inside the "label" DB?

Thanks,

**Comment by TimZaman** [comment]
Because it has a format that's not supported for exploring.
