### ISSUE TITLE
IO Error while classify one image using MNIST_LeNet model

### ISSUE THREAD

**Issue by lilacbeauty** [NVIDIA/DIGITS#2114]
Classify One Image
Owner: lilacbeauty
MNIST_LeNet Image Classification Model

Classification failed, see job log

Tensorflow support disabled.
2018-09-26 22:44:50 [ERROR] IOError:
Traceback (most recent call last):
File "/home/nvidia/DIGITS/digits/tools/inference.py", line 293, in <module>
args['resize']
File "/home/nvidia/DIGITS/digits/tools/inference.py", line 56, in infer
model = Job.load(model_dir)
File "/home/nvidia/DIGITS/digits/job.py", line 37, in load
with open(filename, 'rb') as savefile:
IOError: [Errno 2] No such file or directory: '/home/nvidia/DIGITS/digits/jobs/20180926-224358-dda9/status.pickle'

**Comment by lilacbeauty** [comment]
I checked in folder /home/nvidia/DIGITS/digits/jobs/20180926-224358-dda9/.  There is a file named status.pickle.tmp.  I changed that file's name into 'status.pickle'.  now I have another error.

"2018-09-28 18:50:52 [DEBUG] 20180926-224358-dda9 - EOFError:"

**Comment by gegeyuan** [comment]
Your question is the same as mine. have you solved it? If you solve this problem, please give me some suggestions.Thanks.

**Comment by fredriccliver** [comment]
I have same issue.
I used LeNet also, and it caused on classifying one

**Comment by gabusleon** [comment]
I have same issue. Have anyone solved it?

**Comment by FightingSock** [comment]
Getting same issue on a different model. Same behavior where job has a file status.pickle.tmp, so I get an IO error where the status.pickle file is not found.

Tensorflow support disabled.
2019-04-19 10:27:34 [ERROR] IOError:
Traceback (most recent call last):
File "/usr/local/digits/digits/tools/inference.py", line 293, in <module>
args['resize']
File "/usr/local/digits/digits/tools/inference.py", line 56, in infer
model = Job.load(model_dir)
File "/usr/local/digits/digits/job.py", line 37, in load
with open(filename, 'rb') as savefile:
IOError: [Errno 2] No such file or directory: '/usr/local/digits/digits/jobs/20190418-135227-21e0/status.pickle'

**Comment by mwehrenberg** [comment]
I am having the same exact problem. Has anyone found out how to solve it? 
I'm using DIGITS in CPU mode on Ubuntu 16.04.

**Comment by ktnguyen2** [comment]
I have this issue too with Ubuntu 16.04, Cuda 9.0, Caffe 0.15, GTX 1080

**Comment by eve76** [comment]
I found this problem too.But when i run the devserver, i found that my pyparsing version was wrong ,i reinstalled it use pip ,and it works.

**Comment by bwery** [comment]
Just to indicate that I also encountered this problem and solution for me seems to be the patch by uhfband referenced in

https://github.com/NVIDIA/DIGITS/issues/2024

**Comment by evil-potato** [comment]
I also encountered this problem，so how can i do?

**Comment by lilacbeauty** [comment]
For all:
You need to install DIGTIS strictly by its document. 

Web pages related are shown as follows:
https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildProtobuf.md
https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildCaffe.md
https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigits.md

In summary, you need to install protobuf3 firstly, then install caffe from NVIDIA, then install DIGITS.
In this order, your DIGITS will test image successfully.

**Comment by 1329844541** [comment]
no use for me
