### ISSUE TITLE
Grouping during image folder parsing for db creation

### ISSUE THREAD

**Issue by crohkohl** [NVIDIA/DIGITS#212]
I would suggest to provide the option for grouping during image folder parsing for database creation.
If I understand correctly, right now the structure is as follows:

```
/datafolder/train/[Label]/[File]
```

My suggestion would be something like:

```
/datafolder/train/[Label]/[Group]/[File]
```

This had some potential benefits:
- Samples from the same group shall not be separated in different image lists, e.g. either they are  train or val. This provides an easy mechanism to use custom augmented data and to not bias train/val datasets.
- Potentially the reduction of the number of files per folder. On some systems a huge number of files in a single folder can cause a dramatic performance hit

**Comment by lukeyeager** [comment]
Take another look at this file:
https://github.com/NVIDIA/DIGITS/blob/v2.0.0-rc3/docs/ImageFolderFormat.md

The second benefit is already provided. Maybe the first one is, too?

**Comment by crohkohl** [comment]
Thanks for that link - I hadn't found that document yet!

I think the second point is already provided. However, the first one I think yet isn't.

Imagine the following case:

    ├── images/
    │   ├── cat/
    │   │   ├── img1/
    │   │   |     └── 1_original.jpg
    │   │   |     └── 1_mirrorX.jpg
    │   │   ├── img2/
    │   │   |     └── 2_original.jpg
    │   │   |     └── 2_mirrorX.jpg

If I understand the documentation right, this structure is just flattened and then splitted into train and validation datasets. So it could happen that this split is chosen:

Training:

    │   ├── cat/
    │   │  └── img1/1_original.jpg
    │   │  └── img2/2_mirrorX.jpg

Validation:

    │   ├── cat/
    │   │  └── img1/1_mirrorX.jpg
    │   │  └── img2/2_original.jpg


That is not what you want because it mixes data that originated from the same source image in training and validation. What you would want is:

Training:

    │   ├── cat/
    │   │  └── img1/1_original.jpg
    │   │  └── img1/1_mirrorX.jpg

Validation:

    │   ├── cat/
    │   │  └── img2/2_original.jpg
    │   │  └── img2/2_mirrorX.jpg

Maybe an option if the deepest folder structure is a grouping filter or not during splitting is desirable for people using data augmentation.

**Comment by lukeyeager** [comment]
Yes, I see what you're getting at. I can see adding an option for splitting randomly by sub-folder instead of randomly by class. Do you want to take a stab at adding a `--split_by_subfolder` option [defaults to False] in the `parse_folder` tool?

https://github.com/NVIDIA/DIGITS/blob/v2.0.0-rc3/tools/parse_folder.py

**Comment by crohkohl** [comment]
Sure, I will give it a try.

**Comment by crohkohl** [comment]
Opened a pull request https://github.com/NVIDIA/DIGITS/pull/215.
