### ISSUE TITLE
Digits does not open in Docker

### ISSUE THREAD

**Issue by clydebailey** [NVIDIA/DIGITS#2132]
I tried running Digits on two separate docker files. 
1. Docker 1: nvidia/caffe
running ./digits-devserver gives:
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.1

libdc1394 error: Failed to initialize libdc1394
cudaRuntimeGetVersion() failed with error #30
Tensorflow support disabled.
2018-12-05 10:52:30 [INFO ] Loaded 0 jobs.

2. Docker 2: nvidia/digits:latest
running ./digits-devserver gives:
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.0.0

libdc1394 error: Failed to initialize libdc1394
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
cudaRuntimeGetVersion() failed with error #35
Tensorflow support disabled.
2018-12-05 10:45:53 [INFO ] Loaded 0 jobs.

@lukeyeager please help

**Comment by Robinxbnie** [comment]
This is closed while not found the solution or answer. I met the similar problem. 
`nvidia-docker run --name digits --rm -ti -p 8001:34448 nvidia/digits`
`  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.0.0

libdc1394 error: Failed to initialize libdc1394
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
2019-10-27 18:55:39 [INFO ] Loaded 0 jobs.`

While I tried "http://localhost:8000", nothing is there(I am expecting to see the digits interface shown).
Seems the libdc1394 error not neglectable here...
