### ISSUE TITLE
ImportError: No module named caffe

### ISSUE THREAD

**Issue by dbl001** [NVIDIA/DIGITS#216]
Hi,

I followed the instruction for building Digits on Ubuntu 14.04.2 LTS here:
https://github.com/NVIDIA/DIGITS/blob/master/docs/InstallCaffe.md

$ conda -version
ubuntu@ip-10-0-1-195:~/caffe$ conda -V
conda 3.16.0

ubuntu@ip-10-0-1-195:~/caffe$ anaconda -V
anaconda Command line client (version 1.0.1)
ubuntu@ip-10-0-1-195:~/caffe$ conda update anaconda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /home/ubuntu/anaconda:
#
anaconda                  2.3.0                np19py27_0  

ubuntu@ip-10-0-1-195:~/caffe$ make py
make: Nothing to be done for `py'.
ubuntu@ip-10-0-1-195:~/caffe$ make distribute
# add include
cp -r include distribute/
mkdir -p distribute/include/caffe/proto
cp .build_release/src/caffe/proto/caffe.pb.h distribute/include/caffe/proto
# add tool and example binaries
cp .build_release/tools/upgrade_net_proto_binary.bin .build_release/tools/convert_imageset.bin .build_release/tools/train_net.bin .build_release/tools/finetune_net.bin .build_release/tools/upgrade_net_proto_text.bin .build_release/tools/net_speed_benchmark.bin .build_release/tools/extract_features.bin .build_release/tools/device_query.bin .build_release/tools/test_net.bin .build_release/tools/compute_image_mean.bin .build_release/tools/caffe.bin distribute/bin
cp .build_release/examples/cifar10/convert_cifar_data.bin .build_release/examples/siamese/convert_mnist_siamese_data.bin .build_release/examples/mnist/convert_mnist_data.bin distribute/bin
# add libraries
cp .build_release/lib/libcaffe-nv.a distribute/lib
cp .build_release/lib/libcaffe-nv.so.0.12.2 distribute/lib
cd distribute/lib; rm -f libcaffe-nv.so.0; ln -s libcaffe-nv.so.0.12.2 libcaffe-nv.so.0
cd distribute/lib; rm -f libcaffe-nv.so;   ln -s libcaffe-nv.so.0 libcaffe-nv.so
# add python - it's not the standard way, indeed...
cp -r python distribute/python
ubuntu@ip-10-0-1-195:~/caffe$ ipython 
Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 17:02:03) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import caffe
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1cca3aa1f8c5> in <module>()
----> 1 import caffe

ImportError: No module named caffe

Any ideas?

**Comment by lukeyeager** [comment]
Caffe doesn't automatically add `$CAFFE_HOME/python` to your `PYTHONPATH`, which is a required step to be able to `import caffe`. See their instructions here:

http://caffe.berkeleyvision.org/installation.html#python

DIGITS sets `PYTHONPATH` for you automatically based on your DIGITS configuration. **You should be able to use this build of Caffe with DIGITS without any errors.**
https://github.com/NVIDIA/DIGITS/blob/v2.0.0-rc3/digits/config/caffe_option.py#L228-L229

Also, `make distribute` isn't necessary. It doesn't even work right, last time I checked.

**Comment by dbl001** [comment]
ubuntu@ip-10-0-1-195:~/DIGITS$ ./digits-devserver 
modprobe: ERROR: could not insert 'nvidia_346': No such device
cudaRuntimeGetVersion() failed with error #38
Did you forget to "make pycaffe"?
Traceback (most recent call last):
  File "./digits-devserver", line 42, in <module>
    config.load_config('quiet')
  File "/home/ubuntu/DIGITS/digits/config/load.py", line 147, in load_config
    option.apply()
  File "/home/ubuntu/DIGITS/digits/config/caffe_option.py", line 236, in apply
    import caffe
  File "/home/ubuntu/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/ubuntu/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: libhdf5_hl.so.9: cannot open shared object file: No such file or directory
ubuntu@ip-10-0-1-195:~/DIGITS$

**Comment by dbl001** [comment]
It appears related to this issue:

https://github.com/BVLC/caffe/issues/2720 <https://github.com/BVLC/caffe/issues/2720>

**Comment by lukeyeager** [comment]
No, I'm pretty sure it's not related. 

> ImportError: libhdf5_hl.so.9: cannot open shared object file: No such file or directory

Looks like the same issue as #205. I'm closing this issue as I think I've answered your original question.

**Comment by sarkeribrahim** [comment]
can you please tell me how you solve your this problem
(venv)ibrhaim@ibrhaim-B85M-D3H:~/digits/digits$ ./digits-server
2015-08-25 11:09:59 [5679] [INFO] Starting gunicorn 17.5
cudaRuntimeGetVersion() failed with error #38
Did you forget to "make pycaffe"?
Traceback (most recent call last):
  File "/home/ibrhaim/venv/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==17.5', 'console_scripts', 'gunicorn')()
  File "/home/ibrhaim/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 42, in run
    WSGIApplication("%(prog)s [OPTIONS] APP_MODULE").run()
  File "/home/ibrhaim/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 144, in run
    Arbiter(self).run()
  File "/home/ibrhaim/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 165, in run
    self.start()
  File "/home/ibrhaim/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 124, in start
    self.cfg.on_starting(self)
  File "gunicorn_config.py", line 9, in on_starting
    config.load_config()
  File "/home/ibrhaim/digits/digits/digits/config/load.py", line 147, in load_config
    option.apply()
  File "/home/ibrhaim/digits/digits/digits/config/caffe_option.py", line 243, in apply
    import caffe
  File "/home/ibrhaim/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/ibrhaim/caffe/python/caffe/pycaffe.py", line 14, in <module>
    import caffe.io
  File "/home/ibrhaim/caffe/python/caffe/io.py", line 2, in <module>
    import skimage.io
ImportError: No module named skimage.io

**Comment by dbl001** [comment]
Hi,

The information below suggests a different issue.
I see you are using a python 2.7 distribution (I was using Anaconda).

Is the skiimage.io package installed?
What happens if you run:

$ pip install -U scikit-image

**Comment by sarkeribrahim** [comment]
so you suggest me to install anaconda>

after run  $ pip install -U scikit-image

(venv)ibrhaim@ibrhaim-B85M-D3H:~/caffe$ pip install -U scikit-image
Requirement already up-to-date: scikit-image in /home/ibrhaim/venv/lib/python2.7/site-packages
Requirement already up-to-date: matplotlib>=1.1.0 in /home/ibrhaim/venv/lib/python2.7/site-packages (from scikit-image)
Requirement already up-to-date: six>=1.3 in /home/ibrhaim/venv/lib/python2.7/site-packages (from scikit-image)
Requirement already up-to-date: networkx>=1.8 in /home/ibrhaim/venv/lib/python2.7/site-packages (from scikit-image)
Requirement already up-to-date: pillow>=1.7.8 in /home/ibrhaim/venv/lib/python2.7/site-packages (from scikit-image)
Requirement already up-to-date: numpy>=1.6 in /home/ibrhaim/venv/lib/python2.7/site-packages (from matplotlib>=1.1.0->scikit-image)
Downloading/unpacking python-dateutil from https://pypi.python.org/packages/any/p/python-dateutil/python_dateutil-2.4.2-py2.py3-none-any.whl#md5=c817289a1d95a355cc088e2292791a77 (from matplotlib>=1.1.0->scikit-image)
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB): 188kB downloaded
Requirement already up-to-date: pytz in /home/ibrhaim/venv/lib/python2.7/site-packages (from matplotlib>=1.1.0->scikit-image)
Requirement already up-to-date: pyparsing>=1.5.6 in /home/ibrhaim/venv/lib/python2.7/site-packages (from matplotlib>=1.1.0->scikit-image)
Requirement already up-to-date: nose>=0.11.1 in /home/ibrhaim/venv/lib/python2.7/site-packages (from matplotlib>=1.1.0->scikit-image)
Requirement already up-to-date: mock in /home/ibrhaim/venv/lib/python2.7/site-packages (from matplotlib>=1.1.0->scikit-image)
Requirement already up-to-date: decorator>=3.4.0 in /home/ibrhaim/venv/lib/python2.7/site-packages (from networkx>=1.8->scikit-image)
Installing collected packages: python-dateutil
  Found existing installation: python-dateutil 1.5
    Uninstalling python-dateutil:
      Successfully uninstalled python-dateutil
Successfully installed python-dateutil
Cleaning up...

**Comment by sarkeribrahim** [comment]
thanks for replay,


*now digits run. but it seems some problems like*


(venv)ibrhaim@ibrhaim-B85M-D3H:~/digits/digits$ ./digits-server
2015-08-25 14:02:02 [8051] [INFO] Starting gunicorn 17.5
cudaRuntimeGetVersion() failed with error #38
<https://github.com/NVIDIA/DIGITS/pull/38>
2015-08-25 14:02:06 [8051] [DEBUG] Arbiter booted
2015-08-25 14:02:06 [8051] [INFO] Listening at: http://0.0.0.0:8080 (8051)
2015-08-25 14:02:06 [8051] [INFO] Using worker:
socketio.sgunicorn.GeventSocketIOWorker
2015-08-25 14:02:06 [8087] [INFO] Booting worker with pid: 8087
2015-08-25 14:29:38 [20150825-142937-d69e] [INFO ] Parse Folder (train/val)
task started.
2015-08-25 14:29:39 [20150825-142937-d69e] [WARNING] Parse Folder
(train/val) unrecognized output: cudaRuntimeGetVersion() failed with error
#38 <https://github.com/NVIDIA/DIGITS/pull/38>


<https://github.com/NVIDIA/DIGITS/pull/38>

*in is it need to configure http://0.0.0.0:8080 <http://0.0.0.0:8080>
(8051) tohttp://0.0.0.0:5000/ <http://0.0.0.0:5000/> ????*
*and i see in tutorial,after running ./digits-server , it looks like*


% ./digits-devserver

  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/


*but in my case it shows some error, *

*and when i train a dataset then it shows like...*


2015-08-25 14:29:42 [20150825-142937-d69e] [DEBUG] Total images added: 10
2015-08-25 14:29:42 [20150825-142937-d69e] [INFO ] Create DB (train) task
completed.
2015-08-25 14:29:42 [20150825-142937-d69e] [DEBUG] Total images added: 3
2015-08-25 14:29:42 [20150825-142937-d69e] [INFO ] Create DB (val) task
completed.
2015-08-25 14:29:43 [20150825-142937-d69e] [INFO ] Job complete.
2015-08-25 14:30:57 [20150825-143055-1f9f] [INFO ] Train Caffe Model task
started.
2015-08-25 14:31:48 [8051] [INFO] Handling signal: winch
2015-08-25 14:31:48 [8051] [INFO] SIGWINCH ignored. Not daemonized
2015-08-25 14:31:48 [8051] [INFO] Handling signal: winch
2015-08-25 14:31:48 [8051] [INFO] SIGWINCH ignored. Not daemonized
2015-08-25 14:31:48 [8051] [INFO] Handling signal: winch
2015-08-25 14:31:48 [8051] [INFO] SIGWINCH ignored. Not daemonized
2015-08-25 14:31:48 [8051] [INFO] Handling signal: winch
2015-08-25 14:31:48 [8051] [INFO] SIGWINCH ignored. Not daemonized
2015-08-25 14:31:48 [8051] [INFO] Handling signal: winch
2015-08-25 14:31:48 [8051] [INFO] SIGWINCH ignored. Not daemonized

If you get time please replay...

On Tue, Aug 25, 2015 at 12:08 PM, dbl <notifications@github.com> wrote:

> Hi,
>
> The information below suggests a different issue.
> I see you are using a python 2.7 distribution (I was using Anaconda).
>
> Is the skiimage.io package installed?
> What happens if you run:
>
> $ pip install -U scikit-image
>
> > On Aug 24, 2015, at 7:29 PM, ibrahim sarker <notifications@github.com>
> wrote:
> >
> > can you please tell me how you solve your this problem
> > (venv)ibrhaim@ibrhaim-B85M-D3H:~/digits/digits$ ./digits-server
> > 2015-08-25 11:09:59 [5679] [INFO] Starting gunicorn 17.5
> > cudaRuntimeGetVersion() failed with error #38 <
> https://github.com/NVIDIA/DIGITS/pull/38>
> > Did you forget to "make pycaffe"?
> > Traceback (most recent call last):
> > File "/home/ibrhaim/venv/bin/gunicorn", line 9, in
> > load_entry_point('gunicorn==17.5', 'console_scripts', 'gunicorn')()
> > File
> "/home/ibrhaim/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py",
> line 42, in run
> > WSGIApplication("%(prog)s [OPTIONS] APP_MODULE").run()
> > File
> "/home/ibrhaim/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py",
> line 144, in run
> > Arbiter(self).run()
> > File
> "/home/ibrhaim/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py",
> line 165, in run
> > self.start()
> > File
> "/home/ibrhaim/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py",
> line 124, in start
> > self.cfg.on_starting(self)
> > File "gunicorn_config.py", line 9, in on_starting
> > config.load_config()
> > File "/home/ibrhaim/digits/digits/digits/config/load.py", line 147, in
> load_config
> > option.apply()
> > File "/home/ibrhaim/digits/digits/digits/config/caffe_option.py", line
> 243, in apply
> > import caffe
> > File "/home/ibrhaim/caffe/python/caffe/init.py", line 1, in
> > from .pycaffe import Net, SGDSolver
> > File "/home/ibrhaim/caffe/python/caffe/pycaffe.py", line 14, in
> > import caffe.io
> > File "/home/ibrhaim/caffe/python/caffe/io.py", line 2, in
> > import skimage.io
> > ImportError: No module named skimage.io
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/NVIDIA/DIGITS/issues/216#issuecomment-134454115>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NVIDIA/DIGITS/issues/216#issuecomment-134461305>.
>



-- 
With  Regards,
싸커모하매드이브라힘
Mohammad Ibrahim Sarker
ROBOT VISION LAB, Room No. 407, Engineering Building No. 2-7
Division of Electronics Engineering
Chonbuk National University
664-14 1ga Duckjin-Dong Duckjin-Gu
Jeonju Jeonbuk 561-756 SOUTH KOREA

**Comment by dbl001** [comment]
Not sure about the severity.
Something in ‘GUnicorn’:

https://github.com/benoitc/gunicorn/issues/449 <https://github.com/benoitc/gunicorn/issues/449>

https://github.com/defunkt/unicorn/blob/ea730f93b20ef582128f7c664f7b57953f855a09/lib/unicorn/http_server.rb#L303 <https://github.com/defunkt/unicorn/blob/ea730f93b20ef582128f7c664f7b57953f855a09/lib/unicorn/http_server.rb#L303>

**Comment by mpkuse** [comment]
When I try to install skikit-image, here is what I get.

Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/scikit-image
Storing debug log for failure in /home/mpkusex/.pip/pip.log


Downloading/unpacking scikit-image
  Downloading scikit-image-0.12.3.tar.gz (20.7MB): 20.7MB downloaded
  Running setup.py (path:/tmp/pip_build_root/scikit-image/setup.py) egg_info for package scikit-image
    Unable to find pgen, not compiling formal grammar.
    No eggs found in /tmp/easy_install-ISPmXy/Cython-0.24/egg-dist-tmp-jfEOnt (setup script problem?)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/scikit-image/setup.py", line 146, in <module>
        **extra
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 126, in setup
        dist = setup(**new_attr)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup
        return old_setup(**new_attr)
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__
        Distribution.__init__(self, attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: cython>=0.21
    Complete output from command python setup.py egg_info:
    Unable to find pgen, not compiling formal grammar.

No eggs found in /tmp/easy_install-ISPmXy/Cython-0.24/egg-dist-tmp-jfEOnt (setup script problem?)

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/scikit-image/setup.py", line 146, in <module>

    **extra

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 126, in setup

    dist = setup(**new_attr)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup

    return old_setup(**new_attr)

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/numpy/distutils/numpy_distribution.py", line 16, in __init__

    Distribution.__init__(self, attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve

    raise DistributionNotFound(req)

pkg_resources.DistributionNotFound: cython>=0.21

----------------------------------------

**Comment by lukeyeager** [comment]
Try installing the requirements in order:
https://github.com/NVIDIA/DIGITS/blob/a0dd82f679/docs/BuildCaffe.md#python-packages

**Comment by Rahtron3030** [comment]
I did:
sudo apt-get install python-skimage
to fix this since my firewall blocks pip. Seemed to work . . .
