### ISSUE TITLE
As I tried to run ./digits-server it raises "ImportError: libboost_python.so.1.58.0: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by erogol** [NVIDIA/DIGITS#219]
The error that I got is "ImportError: libboost_python.so.1.58.0: cannot open shared object file: No such file or directory", if I run ./digits-devserver. I installed already boost-1.58 but it cannot find the relative library or something else. Also, the file libboost_python.so.1.58.0 exactly exists and in LD_LIBRARY_PATH

**Comment by lukeyeager** [comment]
That's strange. How did you install Caffe? Did you use the web installer (from https://developer.nvidia.com/digits)? Can you post the actual error that you're seeing?

**Comment by lukeyeager** [comment]
@erogol, I'll assume you figured it out. Let me know if not.
