### ISSUE TITLE
Return number of weights in each layer(while visualising)

### ISSUE THREAD

**Issue by sudeepgaddam** [NVIDIA/DIGITS#220]
While visualising network architecture, It would be better to have number of weights in each layer and also, total weights for entire network. This will quicly give an idea of the network. 

Thanks,
Sudeep.

**Comment by lukeyeager** [comment]
You mean just a simple count? Sure, that's easy to add.

**Comment by sudeepgaddam** [comment]
Thanks a lot for quick comment. This seems small work but comes handy instead of doing manual counting everytime. When can we expect this commit?

**Comment by lukeyeager** [comment]
Created PR #221.

It was a tiny bit trickier than I thought simply because I had to add the number of weights and biases to get the true number of learned parameters.
