### ISSUE TITLE
while training object detection model, what datatype digits uses internally (FP16, FP32 or FP64)?

### ISSUE THREAD

**Issue by Abhijeet-Bhilare** [NVIDIA/DIGITS#2207]

**Comment by jconwayNV** [comment]
DIGITS uses the datatype defined in the model architecture. The training of the object detection model will define the datatype used.
DIGITS supports the same datatypes as the GPU hardware and framework. Example: Nvidia Turing and Volta both support training with FP16 and that can be enabled in model architectures most easily by using automatic mixed precision: https://developer.nvidia.com/automatic-mixed-precision
