### ISSUE TITLE
[ERROR] Train Caffe Model task failed with error code -6

### ISSUE THREAD

**Issue by RaymondZXP** [NVIDIA/DIGITS#2222]
Hi, 

I am trying to follow the object detection tutorial from DIGITS with the KITTI dataset and DetectNet. However I got the following error:

2020-04-10 16:11:45 [20200410-161144-5b02] [INFO ] Task subprocess args: "/home/raymond/caffe/build/tools/caffe train --solver=/home/raymond/DIGITS-6.1.1/digits/jobs/20200410-161144-5b02/solver.prototxt --gpu=0 --weights=/home/raymond/caffe/examples/kitti/bvlc_googlenet.caffemodel"

2020-04-10 16:11:47 [20200410-161144-5b02] [ERROR] Train Caffe Model task failed with error code -6

I am using digits 6.1.1 
**And here are some other infos:**
GPU: RTX2060
Ubuntu 16.04
cuda  :10.0 

**nvidia-smi:**
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Graphics Device     Off  | 00000000:01:00.0  On |                  N/A |
| N/A   53C    P8     9W /  N/A |    656MiB /  5904MiB |     10%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1286      G   /usr/lib/xorg/Xorg                           369MiB |
|    0      2046      G   compiz                                       144MiB |
|    0      3279      G   ...AAAAAAAAAAAACAAAAAAAAAA= --shared-files   141MiB |
+-----------------------------------------------------------------------------+

**buid caffe configs are as follow :**

 ALLOW_LMDB_NOLOCK                            ON                                                                
 BLAS                                                            Atlas                                                             
 BOOST_THREAD_LIBRARY                     /usr/lib/x86_64-linux-gnu/libpthread.so                           
 BUILD_SHARED_LIBS                               ON                                                                
 BUILD_docs                                                ON                                                                
 BUILD_matlab                                             OFF                                                               
 BUILD_only_tests                                                                                   
 BUILD_python                                             ON                                                                
 BUILD_python_layer                                   ON                                                                
 CMAKE_BUILD_TYPE                                                                                   
 CMAKE_INSTALL_PREFIX                          /home/raymond/caffe/build/install                                 
 CMAKE_INSTALL_RPATH_USE_LINK_P   TRUE                                                              
 CPU_ONLY                         OFF                                                               
 CUDA_HOST_COMPILER                             /usr/bin/cc                                                       
 CUDA_TOOLKIT_ROOT_DIR                      /usr/local/cuda                                                   
 CUDA_USE_STATIC_CUDA_RUNTIME      ON                                                                
 CUDA_rt_LIBRARY                                    /usr/lib/x86_64-linux-gnu/librt.so                                
 HDF5_CXX_LIBRARY_dl                            /usr/lib/x86_64-linux-gnu/libdl.so                                
 HDF5_CXX_LIBRARY_hdf5                       /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so                  
 HDF5_CXX_LIBRARY_hdf5_cpp               /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_cpp.so              
 HDF5_CXX_LIBRARY_hdf5_hl                 /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so               
 HDF5_CXX_LIBRARY_hdf5_hl_cpp           /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl_cpp.so           
 HDF5_CXX_LIBRARY_m                           /usr/lib/x86_64-linux-gnu/libm.so                                 
 HDF5_CXX_LIBRARY_pthread                   /usr/lib/x86_64-linux-gnu/libpthread.so                           
 HDF5_CXX_LIBRARY_sz                          /usr/lib/x86_64-linux-gnu/libsz.so                                
 HDF5_CXX_LIBRARY_z                           /usr/lib/x86_64-linux-gnu/libz.so                                 
 HDF5_C_LIBRARY_dl                              /usr/lib/x86_64-linux-gnu/libdl.so                                
 HDF5_C_LIBRARY_hdf5                          /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so                  
 HDF5_C_LIBRARY_hdf5_hl                      /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so               
 HDF5_C_LIBRARY_m                              /usr/lib/x86_64-linux-gnu/libm.so                                 
 HDF5_C_LIBRARY_pthread                    /usr/lib/x86_64-linux-gnu/libpthread.so                           
 HDF5_C_LIBRARY_sz                            /usr/lib/x86_64-linux-gnu/libsz.so                                
 HDF5_C_LIBRARY_z                                /usr/lib/x86_64-linux-gnu/libz.so                                 
 NCCL_INCLUDE_DIR                                NCCL_INCLUDE_DIR-NOTFOUND                                         
 NCCL_LIBRARY                                        NCCL_LIBRARY-NOTFOUND                                             
 OpenCV_DIR                                           /usr/share/OpenCV                                                 
 USE_CUDNN                                           OFF                                                               
 USE_LEVELDB                                        ON                                                                
 USE_LMDB                                              ON  
 USE_OPENCV                                        ON                                                                
 USE_PROJECT_FOLDERS                   OFF                                                               
 python_version                                        2                                                                 

I have not found out whats wrong or a solution to this. Has anyone run into this problem before and offer a solution?

Thanks!

**Comment by cliffwoolley** [comment]
From the nvidia-smi output, it looks like your driver is too old to properly support your RTX2060 GPU; from nvidia.com/drivers I see that RTX2060 support was first picked up in the 418.xx driver series.  You might want to just go ahead up to the latest and see what happens.  Thanks!
