### ISSUE TITLE
Digits Error (code 11)

### ISSUE THREAD

**Issue by frugaldevil** [NVIDIA/DIGITS#223]
Trying to install digits on Jetson TK1 and every time I execute ./digits-test, the following output comes out:

-------------------- >> begin captured logging << --------------------
digits: DEBUG: Parse Folder (train/val) task started.
digits.webapp: INFO: Parse Folder (train/val) task started.
digits.webapp: WARNING: Parse Folder (train/val) unrecognized output: WARNING: log_file config option not found - no log file is being saved
digits.webapp: INFO: Parse Folder (train/val) task completed.
digits: DEBUG: Create DB (train) task started.
digits: DEBUG: Create DB (val) task started.
digits: DEBUG: Parse Folder (train/val) task started.
digits.webapp: INFO: Create DB (train) task started.
digits.webapp: INFO: Create DB (val) task started.
digits.webapp: INFO: Parse Folder (train/val) task started.
digits.webapp: WARNING: Create DB (train) unrecognized output: WARNING: log_file config option not found - no log file is being saved
digits.webapp: WARNING: Create DB (val) unrecognized output: WARNING: log_file config option not found - no log file is being saved
digits.webapp: WARNING: Parse Folder (train/val) unrecognized output: WARNING: log_file config option not found - no log file is being saved
digits.webapp: INFO: Parse Folder (train/val) task completed.
digits.webapp: DEBUG: Total images added: 6
digits.webapp: INFO: Create DB (val) task completed.
digits.webapp: ERROR: Create DB (train) task failed with error code -11
digits: DEBUG: Create DB (train) task started.
digits: DEBUG: Create DB (val) task started.
digits.webapp: INFO: Create DB (train) task started.
digits.webapp: INFO: Create DB (val) task started.
digits.webapp: WARNING: Create DB (train) unrecognized output: WARNING: log_file config option not found - no log file is being saved
digits.webapp: WARNING: Create DB (val) unrecognized output: WARNING: log_file config option not found - no log file is being saved
digits.webapp: DEBUG: Total images added: 6
digits.webapp: INFO: Create DB (val) task completed.
digits.webapp: ERROR: Create DB (train) task failed with error code -11
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------

Does anyone know what error code 11 stands for, Help would be appreciated.

**Comment by lukeyeager** [comment]
I don't know - sorry the error isn't more helpful. You can try running the `create_db` tool manually to see if that gives you any more information.

1. Download MNIST - https://github.com/NVIDIA/DIGITS/blob/v2.0.0-rc3/docs/StandardDatasets.md
2. Create textfiles - `./tools/parse_folder.py ~/mnist/test /tmp/labels.txt -t /tmp/train.txt`
3. Create the LMDB - `./tools/create_db.py /tmp/train.txt /tmp/train_db 28 28`

**Comment by frugaldevil** [comment]
Got it working, had to use `sudo pip install -r requirements.txt --upgrade` & `for req in $(cat python/requirements.txt); do sudo pip install $req --upgrade; done` instead for the dependencies.

But now, execution of ./digits-test is giving a new error:
```
digits.webapp: ERROR: Train Caffe Model: Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
digits.webapp: ERROR: Train Caffe Model task failed with error code -6
```

**Comment by lukeyeager** [comment]
That's odd. Which version of cuDNN do you have, and which version of Caffe? Refer to this chart:
https://github.com/NVIDIA/caffe/wiki/Versions

**Comment by frugaldevil** [comment]
Aarh! Was using version 0.12 with cuDNN v3. 

Downloaded v0.13 and realized that it requires cuda toolkit 7.0 or greater (which is not compatible with Jetson TK1). Rolling back to version 0.12 with cuDNN v1/2

**Comment by lukeyeager** [comment]
Glad you got it working!

You're running DIGITS on a TK1? How's that going?

**Comment by frugaldevil** [comment]
Yeah. Faced tones of issues, but finally its working. 

DIGITS on TK1 is running well and good. Pretty smooth I'd say (nothing in front of the GTX series), great for small datasets and learning models.
