### ISSUE TITLE
Nvidia A100 & Caffe Container 

### ISSUE THREAD

**Issue by eanmikale** [NVIDIA/DIGITS#2238]
Is there a caffe container compatible with the A100? The last version we have is 20.03 I think? And this does not work with the A100. We know model conversion is possible from tensorflow to caffe, but there have been poor results and feedback from the developer community. Thank you for your time.

**Comment by cliffwoolley** [comment]
Unfortunately no, NVIDIA Caffe support ended after 20.03.
