### ISSUE TITLE
Support HDF5

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#224]
I'm breaking the discussion about HDF5 out from #197 ...

https://github.com/BVLC/caffe/issues/2840 is a helpful summary. This is a more detailed comparison.

Are the benefits worth the effort?

## HDF5 vs. LMDB backends

 | HDF5 | LMDB
------------ | ------------- | -------------
Compression | Whole dataset | Each datum
Compression options | [GZIP, LZF](http://docs.h5py.org/en/latest/high/dataset.html#lossless-compression-filters) | [Most image formats](http://docs.opencv.org/modules/highgui/doc/reading_and_writing_images_and_video.html#Mat imread(const string& filename, int flags))

## HDF5Data vs. Data layers

 | HDF5Data | Data
------------ | ------------- | -------------
Data types | [N-D tensors](http://docs.h5py.org/en/latest/quick.html#core-concepts) | ["N<4"-D tensors](https://github.com/NVIDIA/caffe/blob/v0.12.2/src/caffe/proto/caffe.proto#L29-L31)
Transformations | [shuffle](https://github.com/NVIDIA/caffe/blob/v0.12.2/src/caffe/proto/caffe.proto#L531-L536) | [scale, mirror, crop, mean](https://github.com/NVIDIA/caffe/blob/v0.12.2/src/caffe/proto/caffe.proto#L345-L360)

## Other HDF5 pros/cons

* Pros
  * Not tied to any particular Caffe-specific format, so it would be easier to integrate with other frameworks
  * Can have many labels/blobs all in one file
  * Can use multiple files in one HDF5Data layer
* Cons
  * Doesn't have the memory-mapping optimizations that LMDB does

**Comment by lukeyeager** [comment]
Here are some size comparisons for the different compression options on two different imagesets. The LMDB match numbers match those at https://github.com/NVIDIA/DIGITS/issues/73#issuecomment-93842406.
* MNIST test imageset
  * 10,000 images
  * 28x28 grayscale
* ImageNet-like imageset
  * 2,000 images
  * 256x256 color

Backend | Compression option | MNIST size (MB) | ImageNet size (MB)
------------ | ------------- | ------------- | -------------
LMDB | Raw | 9.9 | 383
LMDB | PNG | 3.7 | 178
LMDB | JPEG (lossy) | 9.5 | **37**
HDF5 | Raw | 31 | 1500
HDF5 | LZF | 4.2 | 683
HDF5 | GZIP | **2.7** | 428

## Takeaways

* Image compression algorithms dominate generic compression algorithms on "large" images, even though HDF5 does dataset-wide compression
  * Point for LMDB
* Even uncompressed, HDF5 is very bloated compared to protobuf in LMDB
  * Point for LMDB
* LMDB wouldn't allow any compression on non-image data
  * Half point for HDF5

**Comment by lukeyeager** [comment]
Ah, nevermind about those numbers. I was saving them as `float32` instead of `uint8`. Now the sizes look more reasonable.

Backend | Compression option | MNIST size (MB) | ImageNet size (MB)
------------ | ------------- | ------------- | -------------
LMDB | Raw | 9.9 | 383 
LMDB | PNG | 3.7 | 178 
LMDB | JPEG (lossy) | 9.5 | **37**
HDF5 | Raw | 7.6 | 376 
HDF5 | LZF | 2.2 | 339 
HDF5 | GZIP | **1.7** | 299

Image compression still rocks, but HDF5 isn't bloated as I reported above. Looking into timing comparisons now ...

**Comment by sudeepgaddam** [comment]
Are you planning to work on this?? As caffe  can still be used for non-image datasets too. and HDF5 is good for storing floating point values.

**Comment by lukeyeager** [comment]
@sudeepgaddam, see #226.

I'm planning to merge HDF5 support, but keep it constrained to image data only for now (since that's easiest). But having support in place for HDF5 will make it easier to transition to non-image data whenever we can get to it.
