### ISSUE TITLE
Copied digits-2.0 folder to separate ext4 ssd, and it gave permission denied errors.

### ISSUE THREAD

**Issue by alfredox10** [NVIDIA/DIGITS#233]
I copied the digits-2.0 folder to another storage drive and now it's giving me this error: 
> bash: ./runme.sh: Permission denied

I then copied it back to it's original location inside my Downloads folder and try to run it from there again and I am now receiving this error:
> ./runme.sh: line 11: /home/alfredo/Downloads/DIGITS/digits-2.0/venv/bin/python: Permission denied

In both cases I can say that I have done some troubleshooting including taking full ownership of both folders. I ran the sudo chown -R user:user command and this did not help. I also ran the chmod command to make it executable, but nothing.

**Comment by lukeyeager** [comment]
Please use the [user group](https://groups.google.com/d/forum/digits-users) for this type of question. See [CONTRIBUTING.md](
https://github.com/NVIDIA/DIGITS/blob/master/CONTRIBUTING.md):

> **Before creating an issue on GitHub**, check to see if you should be using the [mailing list](https://groups.google.com/d/forum/digits-users) instead.
The mailing list is for questions relating to:
* Problems installing DIGITS or its dependencies
* Understanding how to use a feature in DIGITS

> Please go to https://groups.google.com/d/forum/digits-users and create a "New Question".

Or you may just want to search around on Google or StackOverflow. This is a linux issue, not a DIGITS problem.
