### ISSUE TITLE
Input must have 4 axes, corresponding to, (num, channels, height, width)

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#234]
Not sure if this is an issue or not - but i have been searching for days and cannot seem to figure it out!

Any image i try to classify individually using digits seems to run okay. However, when using the "classify many images" button, the network crashes because of the aforementioned title/bug/i dont even know what the hell it is.

Im entirely new to caffe and DIGITS, and as i said i've spent days googling this problem - and cant seem to figure it out. what is the 5th dimension on the image, and if i do actually have 5D images, how do i convert them to 4D? 

Thanks!

**Comment by lukeyeager** [comment]
You shouldn't see that error in DIGITS. What version of Caffe and DIGITS are you using? Do you see this error with a standard network? If not, can you show me the data layers of your network?

> what is the 5th dimension on the image

What do you mean by a 5th dimension? Caffe expects 4 - as you pasted in the question title.

**Comment by lukeyeager** [comment]
This bug should be fixed in #237. Please verify if you can.

**Comment by RadicoLabs** [comment]
Bugfix implemented and working. Thankyou sir!
