### ISSUE TITLE
DIGITS cudaRuntimeGetVersion() failed with error #35

### ISSUE THREAD

**Issue by yawadugyamfi** [NVIDIA/DIGITS#252]
So I am able to run DIGITS despite this error: "cudaRuntimeGetVersion() failed with error #35". What is causing this error?

**Comment by lukeyeager** [comment]
1. Is CUDA installed on your system?
2. Do you have NVIDIA GPUs in your system?

**Comment by lukeyeager** [comment]
CUDA error `#35` is this:

> **cudaErrorInsufficientDriver = 35**
This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration. Users should install an updated NVIDIA display driver to allow the application to run.
http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038

DIGITS notices the error, prints it, and keeps on going. It's just letting you know ahead of time that you're going to run into #251.

**Comment by yawadugyamfi** [comment]
I have NVIDIA GPU on my system. However, I cannot install drivers because  I am running DIGITS on a virtual drive.. I wanted to run DIGITS using CPU ONLY so I taught there was no need to use the GPU
