### ISSUE TITLE
Problem with CPU utilization while creating datasets

### ISSUE THREAD

**Issue by yakovzvi** [NVIDIA/DIGITS#254]
is there any difference in the CPU usage in digits v2.2 ?

Cuz while doing Data Pre Processing on v2.1 it did use all my 30 CPU cores and in v2.2 it uses 1 CPU core only.

so it reflects the time remaining.
 
Thank you very Much.
yanky

**Comment by lukeyeager** [comment]
What do you mean by "Data Pre Processing"? Are you seeing a difference while creating a dataset in DIGITS, or while training a network with Caffe?

It's certainly possible that this commit may have affected CPU utilization: 6003709b5e435ca45677124ff64dab8ca14fbbc6.

What do you mean by "it reflects the time remaining"? Is it running faster or slower than before?

**Comment by inovatek** [comment]
While preparing a dataset via caffe for training, I realized that the processing on Digits 2.1 it utilizes all CPU's and with v2.2 it utilizes one only.

Thank you very much !

**Comment by yakovzvi** [comment]
Thank for your fast response :-)

It happens while creating a dataset for caffe training.

And the deference is the CPU used in 2.1 it's full power and in 2.2 1 only :-(

**Comment by lukeyeager** [comment]
This seems like a bad thing. @inovatek, why are you happy with this?

Here's what I'm seeing when creating an MNIST dataset:

Mode | Max # CPUs used | Creation Time
------------ | ------------- | -------------
Multi-writer (before #245) | 2 | 3min, 5sec
Single-writer (after #245) | 1 | 6min, 24sec

On a system with 12 CPU cores, I only saw 2 being used before - not all 12.

**Comment by inovatek** [comment]
Oh sorry we did realized all 40 CPU's before our update, and right after we got down to one only.

**Comment by lukeyeager** [comment]
I can move back to a multi-writer design, but the thing that's throwing me off is this comment:

> LMDB is a single-writer design so you wouldn't see any performance gain using multiple writer threads.
https://github.com/dw/py-lmdb/issues/97#issuecomment-130018935

I'm hoping there will be some computations I can move out of the main thread and into the reader threads without needing to go back to multiple writer threads. I'll look into it some more.

**Comment by inovatek** [comment]
I really appreciate it.

**Comment by michaelholm-ce** [comment]
Hello,

Has this issue been resolved or addressed?  I'm running a large dataset creation job (~1TB) on an NVIDIA devbox.  With DIGITS version 2.0, this dataset creation made full use of all 12 available CPUs, but with DIGITS version 3.0, it is only making use of a couple CPUs.  With a large dataset creation job like this, the difference in processing time is measured in tens of hours.  Unfortunately, I'm having trouble backtracking to version 2.0.

Thank you for any help!

**Comment by lukeyeager** [comment]
Hi @michaelholm-ce, sorry for the inconvenience! I'm looking into this now to see if there's a safe fix to slip in before the final 3.0 release.

To clarify - are you saying that you were seeing a full 1200% CPU utilization in `top` before the change? Are you seeing more than 100% utilization now? In my initial tests, I'm seeing just over 100% CPU utilization both with DIGITS 2.0 and 3.0, even though multiple cores are technically getting used.

**Comment by michaelholm-ce** [comment]
Thank you, @lukeyeager. 

I seem to remember creating datasets in the past where the cpu's were cranking away at full bore (1200%) to create a set.  However, I don't trust my memory completely.

I was able to get digits-2.0 working since I wrote my post, and did some concrete comparisons:

1) Digits 2.0:  Uses all 12 cpus, for a net usage of ~700% - 800%.  There is minor variation in usage over time, but all 12 cpu usage plot lines are banded close together.

2) Digits 3.0:  Uses 6 cpus, for a net usage of ~300%.  Individual cpu usage is not banded together, and usage per cpu varies wildly.  

My machine has 6 physical cpus, with another 6 obtained via hyperthreading.

Thanks for your work.

**Comment by lukeyeager** [comment]
Thanks for the info - that helps!

I'm able to reproduce what you're seeing when using DIGITS, but not when using `tools/create_db.py` directly. When I use it directly, I get max 100% utilization for either 2.0 or 3.0. That's weird. Continuing to look into it...

**Comment by lukeyeager** [comment]
Hey @michaelholm-ce can you test out my fix at #491?

**Comment by michaelholm-ce** [comment]
Beautiful -- I'm now sailing smooth at ~1100% CPU!  Thank you, @lukeyeager.

**Comment by lukeyeager** [comment]
Excellent!
