### ISSUE TITLE
"Infer Many Images" function does not work properly for Generic Inference

### ISSUE THREAD

**Issue by andredubbel** [NVIDIA/DIGITS#255]
After playing around a bit with the new generic inference functionality I found what seems to be a bug in with the "Infer Many Images"-function; all outputs are the same:

![screenshot from 2015-09-01 15 51 55](https://cloud.githubusercontent.com/assets/14016877/9606119/cf03b5a6-50c1-11e5-8110-665b964cdda7.png)

The displayed filenames are correct, and when testing them one by using the "Infer One Image" button they output reasonable results. I'm running the latest version of master 8a3d791fdd3488d30ffa66c1eb75820908ec6d2e

**Comment by gheinrich** [comment]
Hi @andredubbel can you try this patch: https://github.com/gheinrich/DIGITS/commit/d26703a206a1bfb9c2191ad0a0fb6ee3d5aea05a
Thanks!

**Comment by andredubbel** [comment]
It got better but there's still something weird going on: 

![screenshot from 2015-09-01 17 06 51](https://cloud.githubusercontent.com/assets/14016877/9608068/cdaf110e-50cc-11e5-923c-f57201b37e6e.png)


For some reason the first and third row are the exactly the same, and the same goes for the second and forth. After that each row seems to be unique.

If I apply the 4 first images one by one the second and fourth gets the values shown in the image while the first and third get other values.

**Comment by gheinrich** [comment]
I don't see this on my test sample. Any chance you can double check? Thanks!

**Comment by descampsa** [comment]
I had a similar issue, the results of the first chunk of images is invalid because they are overwriten by the second chunk results.
Try this patch: https://github.com/descampsa/DIGITS/commit/f4a636d4bf8241abe26754cac3c993954ebc5fd1

**Comment by lukeyeager** [comment]
@gheinrich, your patch seems to solve the problem for me. Can you open a pull request with the fix?

@andredubbel, thanks for the bug report!

**Comment by lukeyeager** [comment]
Closed in #261.
