### ISSUE TITLE
Make visualization images larger

### ISSUE THREAD

**Issue by andredubbel** [NVIDIA/DIGITS#256]
The visualization of weights and activations that are displayed when inferring a single image can a bit small (at least for nets with small input images like LeNet)

Below is an example from using a LeNet-network trained on detecting green and red dots in an image:
![image](https://cloud.githubusercontent.com/assets/14016877/9607240/5cd101b2-50c8-11e5-81c9-2764359f605c.png)

In this view its hard to get any useful information out of the visualization. But if you open them up in an external viewer they actually start to make sense:
![image](https://cloud.githubusercontent.com/assets/14016877/9607360/027bfba8-50c9-11e5-8f72-16a80f68ca65.png)

It would be nice if the images were larger or could be enlarged somehow, e.g. by clicking on or by hovering above the small image.

**Comment by lukeyeager** [comment]
See #188.
