### ISSUE TITLE
Autocomplete suggestions getting cut off

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#263]
For long directory paths, you can't see the base filename.

![autocomplete-issue](https://cloud.githubusercontent.com/assets/687269/9648139/c226e334-5199-11e5-9dbc-b312ae773858.jpg)

**Comment by gheinrich** [comment]
Hi Luke, is this better with https://github.com/gheinrich/DIGITS/commit/60dc98f53e6d0b174b7d413a779130f21815d1f9? This enables scrolling horizontally when the suggestion is longer than the text field.

Alternatively, I think it is possible to register a custom formatting function that could ensure that we show only the last x characters of suggestions.

**Comment by lukeyeager** [comment]
It's better, but still not great.

I think ideally the suggestions would only be the next piece of the path, like typing `ls <TAB> <TAB>`. For example, if you provide `/home/` the suggestions would be `guest/`, `lyeager/`. And if you click on `lyeager/`, that would be appended to the current value to make `/home/lyeager/`. Is that possible?

**Comment by gheinrich** [comment]
Good idea! I will try to implement this.

**Comment by gheinrich** [comment]
I think this does what you suggested: https://github.com/gheinrich/DIGITS/tree/dev/issue_263
It doesn't append the trailing slash on directories though. This could possibly be implemented with some changes in the autocomplete route.

**Comment by lukeyeager** [comment]
Looks good to me!
