### ISSUE TITLE
Add support for more image formats

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#27]
> Is it possible to create dataset from .bmp images?

See @sersajur's comment in #7.

Currently, the only supported image types are JPEG and PNG (see [here](https://github.com/NVIDIA/DIGITS/blob/master/tools/parse_folder.py#L204) and [here](https://github.com/NVIDIA/DIGITS/blob/master/tools/parse_folder.py#L388)). I'll add support for bmp and anything else that Pillow 2.3.0 can read.

**Comment by lukeyeager** [comment]
I decided to just add `.bmp` files for now instead of

> anything else that Pillow 2.3.0 can read

The list of extensions PIL supports is relatively long and complex: https://infohost.nmt.edu/tcc/help/pubs/pil/formats.html

I'm not going to spend time testing all the different types of images if they're not needed. If somebody else wants another format added, just ask!

**Comment by Mezzano** [comment]
We would like to have the .pgm extension available, the type to add would be "PPM".

Thanks
