### ISSUE TITLE
Dataset creation stuck at 100%

### ISSUE THREAD

**Issue by ashokpant** [NVIDIA/DIGITS#270]
DIGITS v 2.2
Classification dataset creation stuck at 100% showing estimated time remaining few seconds.

**Comment by lukeyeager** [comment]
Probably a duplicate of #242. Try this:

    pip install -U lmdb

#246 should help make these errors easier to debug. When did you last pull from GitHub?

If that doesn't solve your problem, please check the create_db log (exposed in #222).

**Comment by sbhavani** [comment]
create_db log certainly helps. I commented out line 418 in create_db.py and no more dataset creation errors for me.
