### ISSUE TITLE
Add notes to Jobs

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#275]
Similar to #210, but easier. Just add a `job.notes` field that can be edited like `job.name`.

**Comment by DESHRAJ** [comment]
Hey @lukeyeager , I am interested in working on this issue. Can you tell me that does it mean to add a new attribute named 'notes' in the Job class and adding a method to get the notes for a particular job ?

**Comment by lukeyeager** [comment]
Hi @DESHRAJ, that's great thanks!

1. Add a `notes` field to the `Job` class
2. Initialize it to `None` on `Job` creation
3. When showing a job, add some kind of `Add notes` button
4. If notes exist for a job, display them somewhere sensible and show an `Edit notes` button

**Comment by lukeyeager** [comment]
Closed in #283.
