### ISSUE TITLE
models are not loaded when changing the jobs_dir

### ISSUE THREAD

**Issue by GiuliaP** [NVIDIA/DIGITS#282]
Hi,

I have started by using the default 'jobs_dir = /home/giulia/.digits/jobs'. However, now I need to change it because it's becoming too big. I have tried either to directly modify the 'jobs_dir' value in the /home/giulia/.digits/digits.cfg file or to run the server in the configuration mode (option -c) and re-configure from there the 'jobs_dir'. However, when I run digits again, it only loads the datasets, and any model is loaded. It would be a pity to loose all my models (still they are present in the folder, but not loaded by digits) as it is a lot of work. How can I do in order to load the models from the new 'jobs_dir'?

Giulia

**Comment by GiuliaP** [comment]
Also after reverting to the original folder (the default one), digits does not load the models anymore but only the datasets... Any idea?

**Comment by gheinrich** [comment]
I just tried and I can reload both the datasets and the models. This is the sequence I followed:
- stop DIGITS server
- move jobs directory
- digits-devserver -c
- point to new location of jobs directory
I was able to see all my previous datasets and models. 
Do you see the job folders corresponding to your models and do you see status.pickle files in there?
Do you see any error in the console?

**Comment by GiuliaP** [comment]
Yes, I can see all the job folders containing my models, with the status.pickle file and all the other files inside. I do not see errors in the console. I have tried again following exactly your steps but still I see only the datasets... One thing to be noted is that I am using digits 1.0 (the reason is that with digits 2.0 I have encountered another issue).

**Comment by GiuliaP** [comment]
Update: even if the datasets are loaded, they are not usable because it fails to locate the files composing them. E.g. if I try to open a dataset, I got the following error:
IOError
[Errno 2] No such file or directory: '/home/giulia/.digits/jobs/20150909-154120-c972/labels.txt' 
Because, of course, I have moved the jobs folder in '/data/digits_jobs', and it cannot find the files in the original location anymore.

**Comment by GiuliaP** [comment]
Symlinking '/home/giulia/.digits/jobs' to the new folder might have solved the problem...

**Comment by lukeyeager** [comment]
Hi @GiuliaP, you can try putting the scheduler in verbose mode. Change this line to say `verbose=True`:
https://github.com/NVIDIA/DIGITS/blob/v2.1.0/digits/scheduler.py#L85

Then see if you see any errors in the console.

**Comment by lukeyeager** [comment]
@GiuliaP, did you resolve your issue?
