### ISSUE TITLE
Bug in line 417 of tools/create_db.py 

### ISSUE THREAD

**Issue by ajsander** [NVIDIA/DIGITS#288]
Line 417 needs an "as e" to define the exception and fails if the exception is thrown.

**Comment by lukeyeager** [comment]
Thanks! Fix implemented in #290. Can you verify that it works for you?

**Comment by ajsander** [comment]
Yeah it does, thanks.

--Sent from my phone--

Aaron Sander
(612) 695-9696 (cell)

On Sep 10, 2015, at 1:49 PM, Luke Yeager <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! Fix implemented in #290<https://github.com/NVIDIA/DIGITS/pull/290>. Can you verify that it works for you?
