### ISSUE TITLE
Incorrect data labeling

### ISSUE THREAD

**Issue by johnkorn** [NVIDIA/DIGITS#289]
Hi, all!
I've created a dataset of English alphabet characters. It was automatically split into train, valid (15%) and test (10%) sets. I trained a CNN on it and got 97% accuracy on validation set.
I want to test the net on test images. For that purposes I want to use test.txt created by DIGITS.

![1](https://cloud.githubusercontent.com/assets/6063097/9794354/ef5540ba-57ea-11e5-98ef-9996a470c8de.png)

But labeling in that file is a bit strange. Here's a portion of a file:

![22](https://cloud.githubusercontent.com/assets/6063097/9794423/39c33364-57eb-11e5-8413-59623f92a040.png)

Files from folder '63' should be labeled '63' but not '0'.
When I try to classify some of those images via python, they are classified as '0' (which is correct according to the txt). When I classify them in DIGITS GUI they are correctly classified as '63'.
What am I doing wrong?

**Comment by lukeyeager** [comment]
There is a `labels.txt` file in your dataset directory which matches those numerical network outputs to a string label. In your case, I would expect the first line of `labels.txt` to be "63".

**Comment by johnkorn** [comment]
Thanks! You're absolutely right:
![3](https://cloud.githubusercontent.com/assets/6063097/9799884/1d4d088a-580a-11e5-9827-e4ddee82457f.png)
I managed to run classification correctly. But why are labels ordered that way?

**Comment by lukeyeager** [comment]
> But why are labels ordered that way?

That's just the order that `os.listdir()` returns:
https://github.com/NVIDIA/DIGITS/blob/v2.1.0/tools/parse_folder.py#L326

We could sort them. Would you like that?

**Comment by johnkorn** [comment]
That would be great! It will make my (and probably someone else's) life easier.
