### ISSUE TITLE
How to get ground Truth Labels in the Digits example Script?

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#295]
Had an idea for an enhancement, just need a starting point..

When classifying many images, you get the ground truth and the predicted truth. This is the best way to check false flagging on a mass amount of images in one go. It would be really handy if there was a script that checks if GROUND TRUTH != PREDICTED TRUTH, and then copy it to a separate folder for review and further tweaking of your DNN.

Happy to give this a crack myself, just need a way to get the ground truth in DIGITS/examples/classification/example.py, and i can go from there :)

Thankyou!

**Comment by gheinrich** [comment]
This example processes only one image without knowledge of the ground truth. If you want to process a batch of images you might want to look at https://github.com/NVIDIA/DIGITS/blob/master/digits/model/images/classification/views.py#L298. This function reads a list of image path/ground truth from a text file. The ground truth and path are extracted using this  regular expression:
```
match = re.match(r'(.*\S)\s+(\d+)$', line)
if match:
   path = match.group(1)
   ground_truth = int(match.group(2))
```

**Comment by RadicoLabs** [comment]
Yeah Thats what i mean - Im assuming thats where the "classify many" option gets its ground truth from when using the image lists?

**Comment by lukeyeager** [comment]
See #172 - I'd do it in the view.

**Comment by RadicoLabs** [comment]
Sweet, thanks Guys!
