### ISSUE TITLE
couldn't complie succee 

### ISSUE THREAD

**Issue by mingtop** [NVIDIA/DIGITS#298]
root@root-B85M-D3H:~/git/digits-2.0/caffe$ make all
CXX src/caffe/util/insert_splits.cpp
In file included from src/caffe/util/insert_splits.cpp:7:0:
./include/caffe/common.hpp:23:19: fatal error: cnmem.h: No such file or directory
compilation terminated.
make: *** [.build_debug/src/caffe/util/insert_splits.o] Error 1

-------------------------
my cuda is 6.5 
my nvidia driver is 340.
....I don't know why?

**Comment by gheinrich** [comment]
Hi @mingtop, did you install CNMeM and configure Caffe build system accordingly (as suggested on https://github.com/NVIDIA/DIGITS/blob/master/docs/InstallCaffe.md#using-cmake)?
