### ISSUE TITLE
ImportError: PyCapsule_Import could not import module "datetime"

### ISSUE THREAD

**Issue by assaad** [NVIDIA/DIGITS#299]
Hello I am trying to install and getting this message:
ImportError: PyCapsule_Import could not import module "datetime"
Thanks

**Comment by gheinrich** [comment]
Can you post the full log? Thanks!

**Comment by assaad** [comment]
When I used the virtual environment it works. Python libraries issues

**Comment by creitiv** [comment]
I'm getting the same error when running install.sh
```
Extracting MNIST images ...

Traceback (most recent call last):
  File "mnist/main.py", line 8, in <module>
    from mnist import MnistDownloader
  File "/home/kristian/Development/digits-2.0/mnist/mnist.py", line 6, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 6, in <module>
    from . import multiarray
ImportError: PyCapsule_Import could not import module "datetime"
```

**Comment by lukeyeager** [comment]
Hi @creitiv, which OS are you using?

**Comment by creitiv** [comment]
@lukeyeager 
Ubuntu 15.04
Linux desktop 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lukeyeager** [comment]
I'm not surprised that the web installer doesn't work on 15.04.

> **NOTE**: This installer includes binaries built for *Ubuntu 14.04*. The installer will not work on any other platform.
https://github.com/NVIDIA/DIGITS/blob/v2.2.1/docs/WebInstall.md#installation-instructions

Rather than trying to get the web installer to work for you, you're probably better off building NVcaffe and DIGITS from source. 15.05 isn't [officially supported](https://github.com/NVIDIA/DIGITS/tree/v2.2.1#installation) at this time, but you shouldn't have any problems.

P.S. It looks like this guy is having the same problem and he's also on 15.04. You're not alone.
https://devtalk.nvidia.com/default/topic/870026

**Comment by kadok** [comment]
Hi @creitiv ,

I using 15.04 and after many problems DIGITS works for me.

This was my way to make DIGITS run:
https://devtalk.nvidia.com/default/topic/870026/?offset=2#4693597

I've tried use virtualenv, but isn't work for me, then I used python from system.

Hope this help you.

**Comment by Max143** [comment]
Importing the multiarray numpy extension module failed. Most
likely you are trying to import a failed build of numpy.

Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
(removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
1. Check that you are using the Python you expect (you're using /usr/local/bin/python3),
and that you have no directories in your PATH or PYTHONPATH that can
interfere with the Python and numpy versions you're trying to use.

2. If (1) looks fine, you can open a new issue at
https://github.com/numpy/numpy/issues. Please include details on:
- how you installed Python
- how you installed numpy
- your operating system
- whether or not you have multiple versions of Python installed
- if you built from source, your compiler versions and ideally a build log
Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.
Original error was: PyCapsule_Import could not import module "datetime"

**Comment by SaidBenaissa** [comment]
I have the same problem Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/multiarray.py", line 13, in <module>
    from . import overrides
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: /usr/local/lib/python2.7/dist-packages/numpy/core/_multiarray_umath.so: undefined symbol: _Py_ZeroStruct

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 15, in <module>
    import numpy as np
  File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 71, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using /home/said/.virtualenvs/cv/bin/python),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: /usr/local/lib/python2.7/dist-packages/numpy/core/_multiarray_umath.so: undefined symbol: _Py_ZeroStruct
