### ISSUE TITLE
Train Caffe Model task failed with error code -6

### ISSUE THREAD

**Issue by lxduan** [NVIDIA/DIGITS#3]
I've sccessfully imported a dataset by following the [Getting Started](https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md) page. However, after I created a new model (i.e. LeNet), there is an error about training caffe model. The error message is: `[ERROR] Train Caffe Model task failed with error code -6`. May I know how to solve that?

Thank you.

**Comment by moconnor725** [comment]
Which dataset are you using?

**Comment by moconnor725** [comment]
My mistake.  I see you used the sample MNIST dataset.  Which GPU are you using?   What happens if you reduce the customize the model and reduce the batch size?

**Comment by lxduan** [comment]
I compiled Caffe with CPU only. The error happens after the lmdb file is opened I suppose:

ERROR: error code -6
```
Creating layer mnist
Creating Layer mnist
mnist -> data
mnist -> label
Setting up mnist
Opened lmdb /home/local/ANT/lixindu/.digits/jobs/20150318-143850-2ea4/train_db
```
I didn't set the batch size. So I think it should be 10 by default as in Caffe. Just now I set the batch size as 2. But I'm still having that error.

**Comment by lukeyeager** [comment]
Yeah, caffe often returns a cryptic error code. I try to parse the log file and find out what the specific error was, but it doesn't seem to have worked in your case. I just added a commit which should let you download the raw caffe output. Will you look in there and post the last 20 lines or so? You should see something like this:

> I0319 10:17:25.519026 23732 net.cpp:76] Creating Layer pool5
I0319 10:17:25.519028 23732 net.cpp:372] pool5 <- conv5
I0319 10:17:25.519034 23732 net.cpp:334] pool5 -> pool5
I0319 10:17:25.519039 23732 net.cpp:105] Setting up pool5
**F0319 10:17:25.519184 23732 cudnn.hpp:69] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM**
*** Check failure stack trace: ***
@     0x7fecf816ddaa  (unknown)
@     0x7fecf816dce4  (unknown)
@     0x7fecf816d6e6  (unknown)
@     0x7fecf8170687  (unknown)
@     0x7fecf8517ce6  caffe::CuDNNPoolingLayer<>::Reshape()
@     0x7fecf8595171  caffe::Net<>::Init()
@     0x7fecf8596b72  caffe::Net<>::Net()
@     0x7fecf8574b70  caffe::Solver<>::InitTrainNet()
@     0x7fecf8575ce3  caffe::Solver<>::Init()
@     0x7fecf8575eb6  caffe::Solver<>::Solver()
@           0x40a380  caffe::GetSolver<>()
@           0x4061d4  train()
@           0x404111  main
@     0x7fecf767fec5  (unknown)
@           0x404d26  (unknown)
@              (nil)  (unknown)

**Comment by nullterminated** [comment]
I am having a similar problem. I choose alexnet as my model and leave all settings default. I have a 970m with 3GB of memory. The output on my terminal says:

2015-03-22 14:01:32 [20150322-140130-3826] [DEBUG] Train Caffe Model task queued.
2015-03-22 14:01:32 [20150322-140130-3826] [INFO ] Train Caffe Model task started.
2015-03-22 14:01:33 [20150322-140130-3826] [DEBUG] memory required: 793 MB
2015-03-22 14:01:34 [20150322-140130-3826] [DEBUG] memory required: 793 MB
2015-03-22 14:01:47 [20150322-140130-3826] [DEBUG] Network accuracy #0: 73.4714
2015-03-22 14:01:47 [20150322-140130-3826] [ERROR] Train Caffe Model: Check failed: error == cudaSuccess (2 vs. 0)  out of memory
2015-03-22 14:01:48 [20150322-140130-3826] [ERROR] Train Caffe Model task failed with error code -6

From the caffe_output.log, I see:

I0322 14:01:34.870321  4054 solver.cpp:42] Solver scaffolding done.
I0322 14:01:34.870345  4054 solver.cpp:222] Solving
I0322 14:01:34.870350  4054 solver.cpp:223] Learning Rate Policy: step
I0322 14:01:34.870358  4054 solver.cpp:266] Iteration 0, Testing net (#0)
I0322 14:01:47.719110  4054 solver.cpp:315]     Test net output #0: accuracy = 0.734714
I0322 14:01:47.719143  4054 solver.cpp:315]     Test net output #1: loss = 1.53392 (* 1 = 1.53392 loss)
F0322 14:01:47.932499  4054 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
@     0x7fe678bebc6c  (unknown)
@     0x7fe678bebbb8  (unknown)
@     0x7fe678beb5ba  (unknown)
@     0x7fe678bee551  (unknown)
@     0x7fe67901bb4b  caffe::SyncedMemory::mutable_gpu_data()
@     0x7fe67901c893  caffe::Blob<>::mutable_gpu_diff()
@     0x7fe67904605f  caffe::CuDNNPoolingLayer<>::Backward_gpu()
@     0x7fe678f2d158  caffe::Net<>::BackwardFromTo()
@     0x7fe678f2d211  caffe::Net<>::Backward()
@     0x7fe678f49ca1  caffe::Solver<>::Step()
@     0x7fe678f4a72f  caffe::Solver<>::Solve()
@           0x40610f  train()
@           0x40412b  main
@     0x7fe6780f2ec5  (unknown)
@           0x404775  (unknown)
@              (nil)  (unknown)

**Comment by lukeyeager** [comment]
Closing this issue as I don't have enough information to help you. If you are still having a problem, please reopen this and post the relevant part of your caffe log.
