### ISSUE TITLE
MNIST training error

### ISSUE THREAD

**Issue by hbanvait** [NVIDIA/DIGITS#30]
I installed digits from github and I am trying to run mnist example.  I have opencv 3.0 on  my system but still it is giving me the following error while training the leNet model.

can you please help me resolve the issue ?

train_db
OpenCV Error: Assertion failed (k == STD_VECTOR_MAT) in getMat, file /build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp, line 918
terminate called after throwing an instance of 'cv::Exception'
what():  /build/buildd/opencv-2.3.1/modules/core/src/matrix.cpp:918: error: (-215) k == STD_VECTOR_MAT in function getMat
*** Aborted at 1427329465 (unix time) try "date -d @1427329465" if you are using GNU date ***
PC: @     0x7fb97abe00d5 (unknown)
*** SIGABRT (@0x3e800003eab) received by PID 16043 (TID 0x7fb97c798940) from PID 16043; stack trace: ***
@     0x7fb97af78cb0 (unknown)
@     0x7fb97abe00d5 (unknown)
@     0x7fb97abe383b (unknown)
@     0x7fb97b3fe16d (unknown)
@     0x7fb97b3fc1d6 (unknown)
@     0x7fb97b3fc221 (unknown)
@     0x7fb97b3fc438 (unknown)
@     0x7fb97b9e6d31 (unknown)
@     0x7fb97ba32fbc (unknown)
@     0x7fb97b6c2e68 (unknown)
@     0x7fb97c0fb569 caffe::DecodeDatumToCVMatNative()
@     0x7fb97c0fc18d caffe::DecodeDatumNative()
@     0x7fb97c0c5372 caffe::DataLayer<>::DataLayerSetUp()
@     0x7fb97c0c7c76 caffe::BaseDataLayer<>::LayerSetUp()
@     0x7fb97c0c7d79 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
@     0x7fb97c0e90e3 caffe::Net<>::Init()
@     0x7fb97c0eb671 caffe::Net<>::Net()
@     0x7fb97c128f22 caffe::Solver<>::InitTrainNet()
@     0x7fb97c129522 caffe::Solver<>::Init()
@     0x7fb97c129b45 caffe::Solver<>::Solver()
@           0x40a8e8 caffe::GetSolver<>()
@           0x4061f7 train()
@           0x40479b main
@     0x7fb97abcb76d (unknown)
@           0x404c21 (unknown)

**Comment by lukeyeager** [comment]
Are you using the webinstaller? Those binaries were built against OpenCV 2.4 (from `apt-get install libopencv-dev`), and thus they don't link correctly on your system. Did you get an error when you ran the "one_time.sh" script?

**Comment by hbanvait** [comment]
I have installed it on ubuntu 12.04 using github.  I have installed all the requirements using the 12.04 instructions mentioned on caffe installation website (http://caffe.berkeleyvision.org/install_apt.html).  So I have not run the "one_time.sh" script.  Now I did installed opencv 2.4.1  but still I am getting the same error.

**Comment by lukeyeager** [comment]
Ah. Well technically DIGITS is only [supported](https://github.com/NVIDIA/DIGITS/blob/48c274bdf26bf8ed772caa89e7edc6bce3738a01/README.md#installation) on Ubuntu 14.04 at the moment, so you may run into some other issues if you're still on 12.04. But this looks like a caffe problem, not a DIGITS problem, so I would ask on the [caffe-users forum](https://groups.google.com/forum/#!forum/caffe-users) to see if you can get any help over there.

If you do get DIGITS working on 12.04, please let me know what you had to do differently from the instructions in the README. I would be happy to extend the list of "supported" platforms if the changes are trivial.

**Comment by hbanvait** [comment]
I had conflict of versions of openCV.  I did a fresh install of OpenCV 2.4.1 and build caffe and Digits again.  Now it is working on 12.04.

**Comment by lukeyeager** [comment]
Awesome!
