### ISSUE TITLE
Digits Freezing on Model Creation

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#300]
So the image set creation runs fine and completes every task in the job, except for "Create DB (train)" 

This gets caught up with a couple of seconds to go... Any ideas?

When i cancel the test server from the command line it dumps this into the "CreateDB" Panel:

    Exception in thread Thread-7:
    Traceback (most recent call last):
    File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
    File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
    File "/home/dev/DIGITS/tools/create_db.py", line 416, in _load_thread
    image = utils.image.load_image(path)
    File "/home/dev/DIGITS/digits/utils/image.py", line 56, in load_image
    image.load()
    File "/usr/lib/python2.7/dist-packages/PIL/ImageFile.py", line 206, in load
    raise IndexError(ie)
    IndexError: string index out of range
    Traceback (most recent call last):
    File "/home/dev/DIGITS/tools/create_db.py", line 637, in <module>
    lmdb_map_size   = args['lmdb_map_size']
    File "/home/dev/DIGITS/tools/create_db.py", line 143, in create_db
    mean_files, **kwargs)
    File "/home/dev/DIGITS/tools/create_db.py", line 213, in _create_lmdb
    time.sleep(0.2)
    KeyboardInterrupt

**Comment by gheinrich** [comment]
Do you have commit 2a8fc13? This might make the error more legible. Also, are you creating the image dataset out of a folder or a list of image files?

**Comment by RadicoLabs** [comment]
Ha yeah i have that commit - That was my error a few days ago... Now im stuck here.. ;)

And im trying to create from folder

**Comment by RadicoLabs** [comment]
Not sure if Harmless warning or contributing to the error - but the console is throwing LoadImageError: IOError: image file is truncated a lot whilst iterating through training

**Comment by RadicoLabs** [comment]
Update: I ran DIGITS on an old load of images i had and it created an imageSet perfectly fine - Maybe there is something wrong with my data - Who knows... will keep posting updates

**Comment by RadicoLabs** [comment]
Update - Now it's getting stuck on Create DB (val) - My Data should be more or less perfect -Eradicated all images that werent PNG or JPG and changed the file permissions to mirror that of my old Image set.... 

Now the system still crashes... and is throwing a crap load of "IOError: image file is truncated" messages... Any ideas

**Comment by lukeyeager** [comment]
Sounds to me like your data is improperly formatted. How did you generate your images?

**Comment by RadicoLabs** [comment]
Downloaded them all using a web crawling script.... Then i ued another script to get rid of all data that wasnt jpg, or png files, and i chmodded the files to make sure they mirrored the access rights of the old set

**Comment by RadicoLabs** [comment]
Its not just crashing on one stage though - Its crashing at different stages of the imageset creation, just always when its on 99%

Do we check to see if an image is valid before loading it into the system? I could check that all my data is okay, but i have an imageset of 40K+ images, and manually checking will be hard :/

**Comment by RadicoLabs** [comment]
I think its maybe because it's throwing too many truncated files thats why its crashing

**Comment by lukeyeager** [comment]
So you're saying that adding `ImageFile.LOAD_TRUNCATED_IMAGES = True` fixes your problem? That's great! Do you want to put that into a pull request? I'd like to see a test case where this fails too, since I've never encountered this issue.
