### ISSUE TITLE
Transpose order needs to have the same number of dimensions as input

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#301]
This error (explained in the title), keeps getting thrown when using the example scripts "Example.py" and "Use_Archive.py", contained in the DIGITS directory. I think it could be a bug with the underlying caffe system, but im not sure, so i have flagged the issue on the caffe git aswell, just incase.

Anyways, here's a copy of the stack trace that gets thrown on error:

    dev@SaveHive:~/DIGITS/examples/classification$ python use_archive.py BeastNet_E200.gz 01.jpg
    Unknown file: solver.prototxt
    Unknown file: train_val.prototxt
    Traceback (most recent call last):
      File "use_archive.py", line 94, in <module>
        classify_with_archive(args['archive'], image_files, not args['nogpu'])
      File "use_archive.py", line 71, in classify_with_archive
        mean_file=mean_file, labels_file=labels_file, use_gpu=use_gpu)
      File "/home/dev/DIGITS/examples/classification/example.py", line 187, in classify
        transformer = get_transformer(deploy_file, mean_file)
      File "/home/dev/DIGITS/examples/classification/example.py", line 62, in get_transformer
        t.set_transpose('data', (2,0,1)) # transpose to (channels, height, width)
      File "/home/dev/caffe/python/caffe/io.py", line 195, in set_transpose
        raise Exception('Transpose order needs to have the same number of '
    Exception: Transpose order needs to have the same number of dimensions as the input.

Any and all help appreciated as per usual!

**Comment by RadicoLabs** [comment]
Update: Running the same script against an AlexNet model runs fine - Could this be an incompatibility problem with GoogleNet models @lukeyeager ?

**Comment by lukeyeager** [comment]
@RadicoLabs that's possible. Can you paste the first ~10 lines of `deploy.prototxt`?

**Comment by RadicoLabs** [comment]
First 10 lines of my googleNet deploy.proto - As requested!
  
    input: "data"
    input_shape {
      dim: 1
      dim: 3
      dim: 224
      dim: 224
    }
    layer {
      name: "conv1/7x7_s2"
      type: "Convolution"

**Comment by lukeyeager** [comment]
Ah, I forgot to update the example after #231. Can you verify that #311 fixes the issue for you?

**Comment by lukeyeager** [comment]
Closed in #311.

**Comment by RadicoLabs** [comment]
Can Verify this works. Thanks Luke!
