### ISSUE TITLE
Error code -11

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#304]
DIGITS is crashing and leaving me with this error in the first couple of seconds of trying to build a new AlexNet DNN:

    ERROR: error code -11
    conv1 -> conv1
    Setting up conv1
        

Any Ideas?

**Comment by RadicoLabs** [comment]
Ha, where is overlord @lukeyeager when you need him ;)??

**Comment by lukeyeager** [comment]
Hi @RadicoLabs, can you paste the last ~20 lines of the raw Caffe log?

**Comment by RadicoLabs** [comment]
Where would one find the raw caffe logs ?

**Comment by gheinrich** [comment]
On the Image Classification Model page there is a link to a file called caffe_output.log.

**Comment by RadicoLabs** [comment]
Okay well for some reason todayits deciding to work and not crashing at all... No idea what happened. Sorry about this guys! Feel free to ignore

**Comment by jhealyIDEXX** [comment]
I'm running into this same issue if anyone is available to help

**Comment by jhealyIDEXX** [comment]
I0626 18:46:41.598201  1997 layer_factory.hpp:77] Creating layer data
I0626 18:46:41.601033  1997 net.cpp:94] Creating Layer data
I0626 18:46:41.601081  1997 net.cpp:409] data -> data
I0626 18:46:41.602280  2040 db_lmdb.cpp:35] Opened lmdb /jobs/20170626-184355-84a4/train_db/features
I0626 18:46:41.612422  1997 data_layer.cpp:76] output data size: 4,3,259,438
I0626 18:46:41.631304  1997 net.cpp:144] Setting up data
I0626 18:46:41.631336  1997 net.cpp:151] Top shape: 4 3 259 438 (1361304)
I0626 18:46:41.631345  1997 net.cpp:159] Memory required for data: 5445216
I0626 18:46:41.631356  1997 layer_factory.hpp:77] Creating layer label
I0626 18:46:41.634109  1997 net.cpp:94] Creating Layer label
I0626 18:46:41.634127  1997 net.cpp:409] label -> label
I0626 18:46:41.635566  2082 db_lmdb.cpp:35] Opened lmdb /jobs/20170626-184355-84a4/train_db/labels
I0626 18:46:41.636327  1997 data_layer.cpp:76] output data size: 4,3,259,438
I0626 18:46:41.654243  1997 net.cpp:144] Setting up label
I0626 18:46:41.654275  1997 net.cpp:151] Top shape: 4 3 259 438 (1361304)
I0626 18:46:41.654283  1997 net.cpp:159] Memory required for data: 10890432
I0626 18:46:41.654290  1997 layer_factory.hpp:77] Creating layer conv1
I0626 18:46:41.654317  1997 net.cpp:94] Creating Layer conv1
I0626 18:46:41.654372  1997 net.cpp:435] conv1 <- data
I0626 18:46:41.654398  1997 net.cpp:409] conv1 -> conv1
*** Aborted at 1498502801 (unix time) try "date -d @1498502801" if you are using GNU date ***
PC: @     0x7f67389ccf73 (unknown)
*** SIGSEGV (@0x1020bf32000) received by PID 1997 (TID 0x7f66a8d81700) from PID 200482816; stack trace: ***
@     0x7f6736e2ecb0 (unknown)
@     0x7f67389ccf73 (unknown)
@     0x7f67389d6ee0 (unknown)
@     0x7f6738896bb6 (unknown)
@     0x7f673889ad19 (unknown)
@     0x7f6736beda4a (unknown)
@     0x7f67369cc184 start_thread
@     0x7f6736ef5bed (unknown)
@                0x0 (unknown)
