### ISSUE TITLE
REST API ISSUE

### ISSUE THREAD

**Issue by aaron980** [NVIDIA/DIGITS#319]
HI,

I am trying to use the classify_one Rest api for classification. I am sending the request through VB.net  HTTP WebRequest but it keeps giving me a 400 Bad Request Error and must provide image_url or image_file.

**Comment by gheinrich** [comment]
Hi @aaron980, first you need to find the appropriate job ID. For example, using `curl`:

```
$ curl localhost:5000/index.json
{
  ...
  "jobs_dir": "/fast-scratch/gheinrich/ws/digits/digits/jobs", 
  "models": [
    {
      "dataset_id": "20150901-165729-3dc0", 
      "id": "20150915-230450-2524", 
      "name": "Alexnet", 
      "status": "Done"
    }, 
  ], 
  "version": "2.3-dev"
}
```
Then you can query the classify_one URL:
```
$ curl localhost:5000/models/images/classification/classify_one.json -XPOST -F job_id=20150915-230450-2524 -F image_file=@/fast-scratch/gheinrich/ws/digits/cifar100/fine/train/chair/chaise_s_001371.png
{
  "predictions": [
    [
      "horse", 
      26.22
    ], 
    [
      "bird", 
      19.59
    ], 
    [
      "deer", 
      15.93
    ], 
    [
      "airplane", 
      14.19
    ], 
    [
      "dog", 
      12.34
    ]
  ]
}
```

I leave it to you to find out how to do that from a VB script.

**Comment by aaron980** [comment]
Thanks @gheinrich for the info..

**Comment by gheinrich** [comment]
Tentatively closing - @aaron980 please post a question on https://groups.google.com/forum/#!forum/digits-users if you need more info.
