### ISSUE TITLE
ctypes error loading libcudart library on Mac OS X

### ISSUE THREAD

**Issue by RudolphV** [NVIDIA/DIGITS#33]
Line 84 in DIGITS/digits/device_query.py

    cudart = ctypes.cdll.LoadLibrary('libcudart.so')

causes a load error on Mac OS X, given that dylib's are used.

This 

    cudart = ctypes.cdll.LoadLibrary('libcudart.dylib')

fixes it. Should probably check for the OS it's running on, or try both.

**Comment by lukeyeager** [comment]
Is that all you had to change to get it running on a Mac? Cool. Do you want to fix it yourself and open a pull request? If not, I'll get around to it eventually.

**Comment by RudolphV** [comment]
> Is that all you had to change to get it running on a Mac?

Yes, just that one line.

**Comment by lukeyeager** [comment]
Hey @RudolphV, will you verify that the fix I just pushed to the `check-platform` branch works for you? I don't have a mac to test on.

**Comment by RudolphV** [comment]
Yes, that works. Great,
