### ISSUE TITLE
No response after starting the server

### ISSUE THREAD

**Issue by yangj1e** [NVIDIA/DIGITS#337]
I got the following RuntimeWarning after starting the server by `./digits-devserver`, and then there is no response. The thread is in uninterruptible sleep state.

```
/home/ubuntu/anaconda/lib/python2.7/site-packages/setuptools-18.3.2-py2.7.egg/pkg_resources/__init__.py:203: RuntimeWarning: You have iterated over the result of pkg_resources.parse_version. This is a legacy behavior which is inconsistent with the new version class introduced in setuptools 8.0. In most cases, conversion to a tuple is unnecessary. For comparison of versions, sort the Version instances directly. If you have another use case requiring the tuple, please file a bug with the setuptools project describing that need.

Saved config to /home/ubuntu/DIGITS/digits/digits.cfg
```

**Comment by lukeyeager** [comment]
Whoops, I'm sure that has to do with #336. I'm investigating now.

What version of `setuptools` do you have, exactly?
```bash
$ pip list | grep setuptools
setuptools (7.0)
```

**Comment by lukeyeager** [comment]
When I upgrade to the latest version of `setuptools`, I get that same warning, but the server and testsuite both still work just fine.

**Comment by lukeyeager** [comment]
@yangj1e, the warning should be gone. If you still have an issue, that's something else. Let me know.

**Comment by yangj1e** [comment]
Thanks, the warning has gone. But unfortunately, I am still having trouble with the server.
I am using aws g2.2xlarge Ubuntu 14.04 and I use anaconda instead of system python. It used to work fine.

**Comment by yangj1e** [comment]
It seems that if I manually create the `digits.cfg` file, the server can start normally.

**Comment by lukeyeager** [comment]
@yangj1e, `digits-server` won't work without a valid configuration file. But `digits-devserver` should prompt you to provide any missing information. Let me know if that's not the behavior that you're seeing.
