### ISSUE TITLE
 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#353]
So i believe this could be a bug thats crashing imageset Creation 

Midway through the process, an error halts the system and throws: 
Traceback (most recent call last):
  File "/home/dev/DIGITS/digits/scheduler.py", line 454, in run_task
    task.run(resources)
  File "/home/dev/DIGITS/digits/task.py", line 213, in run
    for line in utils.nonblocking_readlines(p.stdout):
  File "/home/dev/DIGITS/digits/utils/__init__.py", line 66, in nonblocking_readlines
    yield buf[:(n+1)].decode(enc)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 80: ordinal not in range(128)

After some research i have learned that non English chars, (i.e accented or letters not in the english alphabet) could be causing this problem. I have a mass download archive of around 400K Images and a few of these have chinese chars in their names... Could this be the cause of the problem?

Thanks!

**Comment by RadicoLabs** [comment]
Not a problem with DIGITS, but it seems to only except files with ASCII compatible filenames... Make sure you sanitize all of your filenames with the information found here before processing into DIGITS: 

http://stackoverflow.com/questions/33055869/recursively-rename-files-to-ascii-standard/33056120#33056120

**Comment by lukeyeager** [comment]
Does [this SO post](http://stackoverflow.com/a/21190382/2404152) work for you?

I added this to the top of `webapp.py` (or the bottom of `config/load.py:load_config`):
```python
import sys
reload(sys)
sys.setdefaultencoding('utf8')
```
That seems to work for me, but I'm not sure how best to solve this across all of DIGITS or whether this might break something else somewhere.

**Comment by YumornZhang** [comment]
I  encounter the same question with you @RadicoLabs  , do you rename your filenames instead of chinese chars solver this problem?

**Comment by YumornZhang** [comment]
I sloved it

**Comment by fsrfsr** [comment]
And what is your solution? @YumornZhang

**Comment by YumornZhang** [comment]
rename my files，it does not allowed any chinese chars in your files.
