### ISSUE TITLE
feature extract and multi-gpu on ec2

### ISSUE THREAD

**Issue by yarin05** [NVIDIA/DIGITS#355]
Hello everybody,
1. 
i have one folder full of images from many classes. Is it possible to train model via digits without labels. or, the labels are important for the train?  the images are not place in folders that fit to thier classes (just one folder). Now, i dont care about the classification issue becuase my goal is to get the features from the hidden layer (or other layer that will give me vector which willrepresent the image). So, how its gonna be and what are my options?
2.
I have g2.2xlarge instance on ec2 but i consider to upgrade it to the bigger g2.8xlarge . This one would work properly with digits 2.0?

Much thanks,
Yarin

**Comment by gheinrich** [comment]
@yarin05 you can use DIGITS to train a model without labels (i.e. unsupervised learning). However you need to optimise your model against a loss function. You may have a look at the [auto-encoder](https://github.com/BVLC/caffe/blob/master/examples/mnist/mnist_autoencoder.prototxt) example in Caffe but I am not sure how useful that would be for the purpose of your task. Also you might find this [thread](https://groups.google.com/forum/#!topic/caffe-users/qCCK8pgSkTY) interesting, it seems like RBM support in Caffe is still work in progress.

DIGITS would be able to make good use of your g2.8xlarge as it supports multi-GPU training with Caffe.

**Comment by yarin05** [comment]
@gheinrich thanks for answering, notice that digits block you if the folder doesnt have at least 2 subdierectories. I changed my database but still much curious for this ability with digits

**Comment by gheinrich** [comment]
If you create a *classification* dataset you need at least two classes. However you can provide your own LMDB image database to DIGITS in order create a *generic* (a.k.a. other) dataset. You can use the generic dataset to do unsupervised learning.

**Comment by lukeyeager** [comment]
@yarin05 we've added several examples/walkthroughs at [/examples/](https://github.com/NVIDIA/DIGITS/tree/master/examples). Take a look and see if any of them are helpful for you.

**Comment by yarin05** [comment]
thank you very much! i already solved my case but the examples improved my
code.


2015-12-11 21:35 GMT+02:00 Luke Yeager <notifications@github.com>:
