### ISSUE TITLE
DIGITS sometimes adds too many mean_values to network definition

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#365]
Reported in #360.

> @lukeyeager
I bet what's happening is that DIGITS is adding 3 more "mean_value" values to each data layer, for a total of 6 mean values. Can you confirm that's what's happening by looking at the train_val.prototxt that DIGITS generates on the next page?

> @RadicoLabs
> Can confirm that DIGITS is appending an additional 3 mean vals:
```
  transform_param {
    mirror: false
    crop_size: 224
    mean_value: 104.0
    mean_value: 117.0
    mean_value: 123.0
    mean_value: 94.9827728271
    mean_value: 105.82069397
    mean_value: 124.092437744
  }
```

**Comment by RadicoLabs** [comment]
@lukeyeager..Following your fixes outline in [360](), I deleted the 2 sets of mean vals, and then resetup training... DIGITS nowseems to throw this error.. "ERROR: Check failed: ShapeEquals(proto) shape mismatch (reshape not set)"

Is this spawned by 365?

**Comment by RadicoLabs** [comment]
Even setting DIGITS to not subtract the mean produces the same error

**Comment by lukeyeager** [comment]
Have you tried leaving the old `mean_value` lines and telling DIGITS to not subtract the mean?

Try starting DIGITS in debug mode and see if it gives you any more information:

    ./digits-devserver --debug

**Comment by RadicoLabs** [comment]
Ahh, so i leave them there, but just leave the fields blank ?

**Comment by lukeyeager** [comment]
I guess you can try that too, but that's not what I meant.

1. Start DIGITS in debug mode
2. Go to create a new model
3. Use your train_val network with the original `mean_value` lines like `mean_value: 104.0` in there
4. Select "No" for `Subtract Mean File`

Then you'll have your original 3 `mean_value` lines, and DIGITS won't try to add any more for you.

**Comment by RadicoLabs** [comment]
Didnt you say on 360 that doing it that way (without subtracting mean) could affect the overall outcome of our training ?

**Comment by lukeyeager** [comment]
Fair point. The scheme above will still subtract the old mean. Replace `104.0, 117.0, 123.0` with `94.9827728271, 105.82069397, 124.092437744` if you like (I'm just reading off numbers from the OP).

**Comment by RadicoLabs** [comment]
Hmmm, still getting thrown ERROR: Check failed: mean_values_.size() == 1 || mean_values_.size() == datum_channels Specify either 1 mean_value or as many as channels: 3

**Comment by RadicoLabs** [comment]
Can comfirm that Fix doesnt work... Getting thrown The error
     ERROR: Check failed: ShapeEquals(proto) shape mismatch (reshape not set) 

when trying to subtract the mean val, and not subtracting the mean val. Also, when i entered the train val for googlenet, and pressed visualise, i got the error: 
    AttributeError type object 'LayerParameter' has no attribute 'LayerType'

Not sure if that might help but it could be another problem?

**Comment by RadicoLabs** [comment]
This is still throwing the Same error "ERROR: Check failed: ShapeEquals(proto) shape mismatch (reshape not set) " even after implementing your fix @jmancewicz

**Comment by lukeyeager** [comment]
Hi @RadicoLabs. @jmancewicz changed a bunch of things related to mean subtraction with #321 - can you check and see if it solved your problem? If not, please give us some steps to reproduce the issue and we'll try to get it fixed for the v3.0 release.

**Comment by jmancewicz** [comment]
The issue was that the option to use the mean value was appending values to the mean in network, and a custom network could have already defined the mean, so this was doubling the number of values.  I changed it so that use opted for no mean, that the existing values would be left alone, and that if either mean value or mean image was selected, that the all existing specifications for mean image and mean value in the custom network were are removed before the new values are added.

**Comment by lukeyeager** [comment]
@RadicoLabs can you please provide some steps to reproduce this issue so we can verify that it's fixed in the RC release before we get to the final release?

**Comment by lukeyeager** [comment]
This looks resolved to me. Closing.
