### ISSUE TITLE
Flag --nogpu not working

### ISSUE THREAD

**Issue by moiltee** [NVIDIA/DIGITS#369]
I executed this python script with and without the --nogpu flag and it seems that script
utilizes my geforce970 GPU in all the cases. The time does not vary significantly between the execution times. More probably the problem is in my environment and how has it been installed but it would be nice to get an additional information about libraries etc. that have been used during script execution via some flag.    
```
digits@digits-Z68AP-D3:~/digits/examples/classification$ ./use_archive.py --nogpu ~/Downloads/20150824-062821-1bea_epoch_30.0.tar.gz ~/Downloads/deer.jpg
Processed 1/1 images ...
Classification took 0.0046980381012 seconds.
---------------- Prediction for /home/digits/Downloads/deer.jpg ----------------
 99.9800% - "deer"
  0.0198% - "frog"
  0.0002% - "bird"
  0.0000% - "cat"
  0.0000% - "horse"

Script took 0.350121021271 seconds.
digits@digits-Z68AP-D3:~/digits/examples/classification$ ./use_archive.py ~/Downloads/20150824-062821-1bea_epoch_30.0.tar.gz ~/Downloads/deer.jpg
Processed 1/1 images ...
Classification took 0.00455904006958 seconds.
---------------- Prediction for /home/digits/Downloads/deer.jpg ----------------
 99.9800% - "deer"
  0.0198% - "frog"
  0.0002% - "bird"
  0.0000% - "cat"
  0.0000% - "horse"

Script took 0.366127967834 seconds.
```

**Comment by gheinrich** [comment]
Using a GPU to classify a single is unlikely to produce a significant speed-up (it might even be counter productive, as seems to be the case). You can use `nvidia-smi -lms 100` to monitor GPU usage while you are running the command. If 100ms is too long, try with a smaller delay.

**Comment by lukeyeager** [comment]
The `--nogpu` flag is working correctly for me. Classifying 100 images takes 7 seconds with the GPU and 36 seconds without it, and I can verify that the GPU is being utilized via `nvidia-smi`.

What may lead you astray is that when you run with `--nogpu`, some memory still gets allocated on the GPU through pycaffe. But the GPU is not used for compute.

Here's how I checked:

1) Classify 100 images instead of 1 by adding this line:
```python
  194         raise ValueError('Invalid number for channels: %s' % channels)
+ 195     image_files = image_files * 100
  196     images = [load_image(image_file, height, width, mode) for image_file in image_files]
```
2) Use `nvidia-smi` to watch for GPU utilization:

    while :; do nvidia-smi; sleep 0.1; done

**Comment by moiltee** [comment]
Measured time was  9.14003515244 seconds with --nogpu flag (i7-3770 CPU @ 3.40GHz) and without it 9.04806399345 seconds to hundred pictures, which indicates that GPU is all the time in use. On the other hand NVIDIA server settings window does not show significant GPU utilization during the tests. Nvidia-smi tool shows for both cases some memory allocations of dedicated memory. I recommend closing this error, because the problem is in my environment. I will do the installation again.

**Comment by lukeyeager** [comment]
> I recommend closing this error, because the problem is in my environment. I will do the installation again.

Ok. Feel free to re-open and/or add a comment if you run into more related issues.
