### ISSUE TITLE
Digits2.0 :CUDA and CuDNN versions?

### ISSUE THREAD

**Issue by siddharthm83** [NVIDIA/DIGITS#381]
Hi devs,
I apologize if someone already asked this but I was not able to find the answers to the below:

Prior to downloading the Digits 2.0 web installer, I was using the below
1. CUDA v 7.5
2. CuDNN v3
3. Caffe (master from https://github.com/BVLC/caffe). 

I have 2 TitanX GPUs and I realized that the main branch of Caffe does not have multi-GPU support. I found that Digits 2.0 has multi GPU support. So my question are:
1. Which CUDA and cuDNN version does Digits2.0 come with? 
2. What are the steps I need to follow to use Digits 2.0 with cuda 7.5 and cuDNN v3? 
3. Do I have to uninstall my other instance of Caffe? (I am assuming both can coexist and I can leave the older one as-is).

**Comment by lukeyeager** [comment]
> 1) Which CUDA and cuDNN version does Digits2.0 come with? 

The DIGITS 2.0 web installer comes with:
* CUDA v7.0
* [NVcaffe v0.13.1](https://github.com/NVIDIA/caffe/releases)
* [cuDNN v3](https://github.com/NVIDIA/caffe/wiki/Versions)

> 2) What are the steps I need to follow to use Digits 2.0 with cuda 7.5 and cuDNN v3? 

You can follow the instructions in the README for this project to build Caffe and connect it to DIGITS.

> 3) Do I have to uninstall my other instance of Caffe? (I am assuming both can coexist and I can leave the older one as-is).

You can have multiple instances of Caffe on your machine. Use `./digits-devserver --config` to choose which Caffe installation you'd like to use.

> the main branch of Caffe does not have multi-GPU support

Sure it does. This pull request was merged more than 2 months ago: https://github.com/BVLC/caffe/pull/2903.
