### ISSUE TITLE
ERROR: IndexError

### ISSUE THREAD

**Issue by chliu0616** [NVIDIA/DIGITS#382]
Hello!

I try to create a module to classify some object. When the training stage is finished, I want to test a single image and show visualizations.

I get an indexError: index 95 is out of bounds for axis 0 with size 95.

![image](https://cloud.githubusercontent.com/assets/15330201/10739478/9855041c-7c57-11e5-8109-96b0bee1abc1.png)

Any ideas what might be the issue here or how to further troubleshoot the problem?

Kind Regards
Liou

**Comment by lukeyeager** [comment]
What version of DIGITS do you have? I think this was fixed in #326. That hasn't been pulled into a versioned release yet - just grab the current `master` branch and see if that fixes your problem.
