### ISSUE TITLE
Error when classifying with Finetuned network

### ISSUE THREAD

**Issue by RadicoLabs** [NVIDIA/DIGITS#384]
When i try classifictation, on a batch of images using the example.py and use_archive.py, the stacktrace throws this error:
````
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format                      
caffe.NetParameter: 1:1: Invalid control characters encountered in text.
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format                                                                             
caffe.NetParameter: 1:2: Expected identifier.
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1028 04:37:06.172204 10834 upgrade_proto.cpp:928] Check failed: ReadProtoFromTextFile(param_file, param) 
Failed to parse NetParameter file: /tmp/Models/NewNet_E200.tar.gz/deploy.prototxt *** Check failure stack trace: ***
````
Trained using the [Alexnet Finetune Tutorial](http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html)

**Comment by lukeyeager** [comment]
Are you trying to read a `.binaryproto` file as a `.prototxt` file or vice versa?

P.S. What's with all the extra spaces? Just a copy+paste issue?

**Comment by RadicoLabs** [comment]
Hmm, Will try rebuilding my alexnet Model.... Is there a way to download the model to the server from digits? Insteadf of having the download window try to save it to my PC ? 

Because right now i've just manually copied all the appropriate files from the job directories, and tarred them up to make my model file, because i dont want to have to download the model to my PC, just to have to upload it back to our dev server...

And also, sorry about the spaces, copied and pasted in a rush and didnt notice, i've updated the OP..

**Comment by lukeyeager** [comment]
It looks like you're trying to read a non-textfile as a textfile. What does this do?

    head /tmp/Models/NewNet_E200.tar.gz/deploy.prototxt

What do you mean by "download the model to the server from digits"? Isn't the model already on the server? Why aren't you using the "Previous Networks" feature?

![customize-previous-networks](https://cloud.githubusercontent.com/assets/687269/10770688/d9477da4-7ca9-11e5-94bf-cbf2f5c4475e.jpg)

Choose the network and model that you want, and then click on "Customize".

**Comment by RadicoLabs** [comment]
The Head script seriously screwed with my terminal window hahaha... also when i nanoed that file, it was a load of random symbols and content... Anyways, here's the output of your head command:

<img width="945" alt="untitled" src="https://cloud.githubusercontent.com/assets/6971776/10770810/02c11926-7d39-11e5-922f-737e00f2505c.png">

And i want to download/save the .tar.gz of the model (for use with the python scripts) to the server

**Comment by lukeyeager** [comment]
Yeah ok so that's clearly not a `.prototxt` file. What are you trying to do? How did you untar the downloaded file?

    tar xvf 20150422-142638-d892_epoch_30.0.tar.gz

**Comment by RadicoLabs** [comment]
Just using the extract method in use_archive.py.... But it could be because i manually made the model by copying all of its needed files into a single directory and tarred them myself.

It might be worth pointing out that im remotely logging into the digits server, so when i attempt to download the latest epoch in the form of a tar.gz, it only lets me download the tar to my PC.

<img width="910" alt="untitled" src="https://cloud.githubusercontent.com/assets/6971776/10771397/49f27f1c-7d3c-11e5-8999-18c1fa18eec9.png">

I would like to save the tar locally (on the machine the devserver is running on), then maybe this error wont occur/... IS there a way to do this?

**Comment by lukeyeager** [comment]
Oh this is with the classification example. Sorry, I missed that in your OP.

Get the list of models:
```
$ curl localhost:5000/index.json
{
  "datasets": [
    {
      "id": "20150415-180806-1984",
      "name": "VOC png (squash)",
      "status": "Done"
    }
  ],
  "models": [
    {
      "dataset_id": "20150415-180806-1984",
      "id": "20150415-180828-cad8",
      "name": "AlexNet on png",
      "status": "Done"
    }
  ]
}
```
Download a model:
```
$ wget localhost:5000/models/20150415-180828-cad8/download -O model.tgz 
--2015-10-27 13:58:02--  http://localhost:5000/models/20150415-180828-cad8/download
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 211286521 (201M) [text/html]
Saving to: ‘model.tgz’

100%[============================================================>] 211,286,521  694MB/s   in 0.3s   

2015-10-27 13:58:11 (694 MB/s) - ‘model.tgz’ saved [211286521/211286521]
```

**Comment by swarnkarkush21** [comment]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0629 17:12:39.369413  5063 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0629 17:12:39.369442  5063 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0629 17:12:39.369459  5063 _caffe.cpp:142] Net('../try1_2/depoly.prototxt', 1, weights='../Model/try1_2/snapshot_iter_1500000.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:288] Error parsing text-format caffe.NetParameter: 10:3: Unknown enumeration value of "LOCAL" for field "type".
F0629 17:12:39.369570  5063 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: ../try1_2/depoly.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
What is solution of this problem.
