### ISSUE TITLE
Old dataset not shown when I configure to change to a new folder to store new data

### ISSUE THREAD

**Issue by antran89** [NVIDIA/DIGITS#385]
Hi 
I tried to change to new hard drive to have more spaces to store more dataset with DIGITS. 
```
digits-devserver -c
```
The previous dataset is not shown in DIGITS interface. Please solve this bug.
Thanks.

**Comment by gheinrich** [comment]
@antran89 did you move the contents of the previous job folder into the new job folder?

**Comment by antran89** [comment]
Hi @gheinrich,
My dataset is hundreds of GB, so it is very inefficient to move data.

**Comment by gheinrich** [comment]
DIGITS requires all jobs to be in the same folder. If you can't move your existing dataset to the new folder you could try creating a symbolic link. For example:
```
ln -s /path/to/new/folder/20150812-142520-8414/ /path/to/old/folder/20150812-142520-8414
```

**Comment by antran89** [comment]
@gheinrich Thank for your suggestions. If it is not so complicated to modify, please allow for multiple folders.
