### ISSUE TITLE
blocking_queue.cpp:50] Data layer prefetch queue empty with Digits 2.0

### ISSUE THREAD

**Issue by siddharthm83** [NVIDIA/DIGITS#389]
Hi, 

My system:
1. Cuda 7.5
2. CudNN V3
3. 2x Titan X's

I am transitioning from Caffe master from BVLC to Digits mainly for the ease of use. 
1. When I train the reference_caffenet model with Imagenet 1000 using Caffe master (1 Titan X), training 20 iterations take about 6sec to 6.5 seconds. 
2. I used the web installer of digits (which I believe comes with Cuda 7.0 and cudnnv3). If I start training on the same reference_caffenet model with Digits (1 Titan X), training 20 iterations takes about double the time (13 to 14 seconds). I also notice a lot of log messages like the one below:

`18:29:17.241222 11321 blocking_queue.cpp:50] Data layer prefetch queue empty`

I tried recompiling NVCaffe with `USE_CNMEM := 0` and `USE_CNMEM := 1` (as that was the only difference between NVidia's Caffe and BVLC's Caffe makefiles) but there was no difference in performance. 

Any tips on how to debug this? I really want to be able to use Digits with 2 GPUs. I don't see the above problem  with the Caffe master from BVLC. 

Siddharth

**Comment by lukeyeager** [comment]
Filed at https://github.com/NVIDIA/caffe/issues/55.

**Comment by westeast** [comment]
I slove the problem by changing the batches number to 16 from 32
