### ISSUE TITLE
 [ERROR] AssertionError: must specify a SoftmaxWithLoss layer; SOFTMAX_LOSS cant

### ISSUE THREAD

**Issue by zdx3578** [NVIDIA/DIGITS#39]
when i want to run googlenet, googlenet use 

layers {
  bottom: "loss2/classifier"
  bottom: "label"
  top: "loss2/loss1"
  name: "loss2/loss"
  type: SOFTMAX_LOSS
  loss_weight: 0.3

not SoftmaxWithLoss layer,

here error:
2015-03-28 12:29:48 [20150328-122946-19fd] [DEBUG] Train Caffe Model task queued.
2015-03-28 12:29:48 [20150328-122946-19fd] [ERROR] AssertionError: must specify a SoftmaxWithLoss layer ;

**Comment by zdx3578** [comment]
i  use custom network  , use binary caffemodel;

**Comment by zdx3578** [comment]
can use caffe train_val.prototxt ??

**Comment by lukeyeager** [comment]
You're using a GoogLeNet network definition that was targeted for an older version of caffe (see BVLC/caffe#1694). Use the `upgrade_net_proto_text` tool that comes with caffe to upgrade it before uploading it to DIGITS. Also, GoogLeNet isn't going to work for you right now anyway (see #11).
