### ISSUE TITLE
MNIST classify many with more than 16 items shows incorrect predicitions

### ISSUE THREAD

**Issue by elezar** [NVIDIA/DIGITS#391]
After completing the MNIST tutorial, I tried to use the "Classify Many" functionality passing in the ```test.txt``` file as a file list. I noticed that the first item in the file:
```
/root/data/mnist/test/7/00000.png 7
```
Showed 9 as the top prediction. When classifying the image on its own, it was correctly classified as a 7. Looking down the list of classifications, I noted that the 17th item (and the following items):
```
/root/data/mnist/test/9/00016.png
```
was being classified correctly, and all preceding items were shown as incorrect.

Diving a little further, I created a new file:
```
head -N test.txt > sample.txt
```
ran "Classify Many" on ```sample.txt``` and noted the following.

* For ```N < 17``` the output of "Classify Many" is correct for all images in the list.
* For ```N = 16 + i; i = 1, 2, 3, ..., 16``` the predictions for the first ```i``` items in the list are incorrect (they show the predictions for item ```N``` instead of ```i```)
* For ```i > 16``` only the first 16 images remain incorrect, and show the predictions as in the previous point.

For reference, I am using the CPU-only Docker image: https://hub.docker.com/r/kaixhin/digits/

(I see that this uses https://github.com/NVIDIA/caffe/tree/caffe-0.12 and not the latest branch, but I have not yet investigated this further).

**Comment by gheinrich** [comment]
@elezar I think this was fixed with https://github.com/NVIDIA/DIGITS/pull/361. The fix doesn't appear to be in your image.

**Comment by elezar** [comment]
Thanks. I will try with an updated image.

**Comment by elezar** [comment]
Testing with the latest build of the Docker image (pulled from Docker Hub) does not show this behavior. Thanks.
