### ISSUE TITLE
Travis builds failing

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#398]
./scripts/travis/travis_install.sh: line 67: conda: command not found

That's coming from [this line](https://github.com/NVIDIA/caffe/blob/v0.13.2/scripts/travis/travis_install.sh#L67) in NVcaffe, which is called from [this line](https://github.com/NVIDIA/DIGITS/blob/b07b425b5b9ae5405c8e25df57f5c2de421b9b8b/scripts/travis/install-caffe.sh#L23) in DIGITS.

I suspect that this miniconda script has changed its default location.

    http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh

**Comment by jhprinz** [comment]
Same problem here. Apparently the default install path has changed from `~/miniconda` to `~/miniconda2`

Hope this helps.

**Comment by lukeyeager** [comment]
Yep, good call! We just fixed it in https://github.com/NVIDIA/caffe/pull/67, hopefully that solves the problem ...
