### ISSUE TITLE
Option to auto-remove failed jobs

### ISSUE THREAD

**Issue by singarajus** [NVIDIA/DIGITS#399]
When a job fails, the job logs from the disk is not deleted. It would nice to have a clean job button as well.

**Comment by lukeyeager** [comment]
I'm not sure what you mean. There are "Delete job" buttons on the home page and on the job page. What else are you looking for?

![delete-job-1](https://cloud.githubusercontent.com/assets/687269/11004192/ae4a62e6-846b-11e5-99df-07882872fe6b.jpg)

![delete-job-2](https://cloud.githubusercontent.com/assets/687269/11004198/b1c46f5c-846b-11e5-84d2-ebbc611ea3c3.jpg)

**Comment by singarajus** [comment]
Thanks, I wanted the default behavior to be clean the job logs after job finishes. There may be others who might want to tweak the network. If there is an auto clean method, I can setup multiple jobs without worrying about disk being used up.

Hope that helps.

**Comment by lukeyeager** [comment]
Hmm, that's the opposite of what I usually want. I usually want all information possible to tell me what went wrong. Thanks for explaining, I'll mark this as a feature request.

**Comment by singarajus** [comment]
I do want the debug logs to be available. However, the folder within which the job data is stored grows quite large. Does Digits create the images again? Is there a possibility of compression?

**Comment by lukeyeager** [comment]
On second thought, we're not going to do this. Closing.

> However, the folder within which the job data is stored grows quite large. Does Digits create the images again? Is there a possibility of compression?

Try storing JPEGs in your LMDBs instead of PNGs. Your datasets should take up much less space.

![encoding-options](https://cloud.githubusercontent.com/assets/687269/11753406/ca378dd6-9ff9-11e5-96a0-d0ed9ace4b9d.jpg)

Also, you may be interested in #405.
