### ISSUE TITLE
Status of dataset and trained model "Aborted"

### ISSUE THREAD

**Issue by bartos88** [NVIDIA/DIGITS#4]
I followed the getting started guide and created a dataset for the mnist_10k images and sucessfully trained the default lenet. After stopping the server and starting it up again the status for my dataset and trained model changes to "Aborted".

**Comment by lukeyeager** [comment]
To be clear - both your dataset and model jobs completed before you restarted the server?

If so, that's a bug that I've noticed on another machine, but not on mine. Thanks for reporting this issue, I'll look into it and get back to you.

**Comment by bartos88** [comment]
Yes that's correct. They both completed. Thanks for looking into it

**Comment by lukeyeager** [comment]
Hey @bartos88, can you verify that the latest commit fixed the issue for you?

**Comment by bartos88** [comment]
I just used the DIGIT installer. If I can get it to compile from the source I'll verify it for you. Will installing DIGITS from source give me any problems if I already have it installed using the easy installer?

**Comment by bartos88** [comment]
It looks like the issue is fixed for me!

**Comment by lukeyeager** [comment]
Awesome! Thanks for reporting it.
