### ISSUE TITLE
Digits UI with Authentication

### ISSUE THREAD

**Issue by gautamsingaraju** [NVIDIA/DIGITS#407]
I run Digits on an EC2 instance. When I set long running jobs, I would like to have some mechanism of authentication to the UI. It could be as simple as username and password being read from the disk to integration with LDAP.

This is a feature request for some basic WebUI authentication.

**Comment by lukeyeager** [comment]
We're planning to do #201 first. Will that be enough for a start?

Once we add authentication to the server, there is a certain amount of security that would be expected. Currently, we're treating security as a non-issue. So this probably won't happen soon.

**Comment by singarajus** [comment]
Thanks, makes sense. I have "constrained" the access to a few IP addresses using firewalls.

**Comment by lukeyeager** [comment]
@singarajus I've opened a PR for basic login functionality at #463.

**Comment by singarajus** [comment]
Thanks, Luke!

**Comment by lucbettaieb** [comment]
Bump!

My campus' network forward everything, so if I run a DIGITS server on my computer, theoretically anybody could access it if they had the hostname.  Any way I can make the server password protected?

**Comment by lucbettaieb** [comment]
:+1: This would be great

**Comment by elezar** [comment]
Some form of authentication/login would be really useful.

**Comment by croninstephen** [comment]
I'd love to see that feature too. My machine is on a university network and I don't want people to jsut be poking around.
