### ISSUE TITLE
Any plan to distributed DIGITS?

### ISSUE THREAD

**Issue by dccho** [NVIDIA/DIGITS#412]
I'm really happy to use DIGITS in multi-GPU system. It reduce training time almost 20 times.
However, it still needs almost one day to train little bit big network.
Do you have any plan to release distributed DIGITS?
If a dataset is big enough (such as Imagenet or Places DB), data parallelism is suitable solution for DIGITS.
Hope to release it ASAP.

**Comment by lukeyeager** [comment]
Do you want one training job on multiple nodes? See https://github.com/BVLC/caffe/pull/3252

Do you want to schedule single-node training jobs on multiple nodes? See https://github.com/NVIDIA/DIGITS/issues/108.
