### ISSUE TITLE
Repository in UbuntuInstall.md is dead

### ISSUE THREAD

**Issue by sun9700** [NVIDIA/DIGITS#427]
Both Repository for ubuntu deb install returns a 404 error:

--2015-11-21 10:12:31--  http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/nvidia-machine-learning-repo_4.0-1_amd64.deb
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 104.254.123.42, 104.254.123.43
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|104.254.123.42|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-11-21 10:12:32 ERROR 404: Not Found.

**Comment by gheinrich** [comment]
@sun9700, sorry docs have been updated in preparation for the upcoming DIGITS 3 release but the Nvidia repository isn't released yet. In the meantime, can you refer to this version of the  [README](https://github.com/NVIDIA/DIGITS/blob/9edc2adb79a539e5c89de19f527a2648521052c3/README.md)? Alternatively, you may install DIGITS and its dependencies from source.

**Comment by sun9700** [comment]
Thanks for your hardwork, we are expecting the ver3 deb

**Comment by lukeyeager** [comment]
Yeah, sorry about that. I meant to stage all the new documentation on the `digits-3.0` branch without updating the `master` branch.

Will let you know when the repo goes live.

**Comment by lukeyeager** [comment]
Re-opening this so maybe people can find it more easily.

**Comment by lukeyeager** [comment]
The deb packages are now accessible via the commands on this page:

https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/UbuntuInstall.md

**NOTE: these are still RC (release candidate) packages.** Please let us know if you find any issues with usage or installation and we will do our best to address them before the final 3.0 release.

Sorry for the confusion! Now that we've worked out some issues with our distribution pipeline, the next release should [hopefully] be much smoother.

/cc @jas0n1ee (#433) @kureta (#435) @alexeykurov (#451) @cognizac (#466)

**Comment by jas0n1ee** [comment]
👍
