### ISSUE TITLE
cannot import name DataRequired

### ISSUE THREAD

**Issue by sysint64** [NVIDIA/DIGITS#428]
In new Flask-WTF DataRequired renamed to Required.
If You get some error, just add to `/usr/lib/python2.7/dist-packages/wtforms/validators.py` line at end file:
`DataRequired = Required`
Fix commit: https://github.com/sysint64/DIGITS/commit/c8e93adf56b9e28cf6770f6b23ad4a52eacfb67e

**Comment by sun9700** [comment]
use the latest version of flask from pip, purge the apt-get verison.

**Comment by sysint64** [comment]
thanks that did the trick!
