### ISSUE TITLE
Folder does not exist

### ISSUE THREAD

**Issue by mavericklam** [NVIDIA/DIGITS#429]
HI! I am using the DIGITS but when I enter my path to my folder always show this:
Folder does not exist

I am using a MAC and this is the path I enter:
/Users/muname/Downloads/cohn-kanade-images/test/S122/001

**Comment by lukeyeager** [comment]
Note that the folder should be a folder on the **server**, not on your local machine.

**Comment by xhuvom** [comment]
I'm facing the same problem on Ubuntu 16.04 running Digits devserver via docker. 

when I enter my path to my folder always show this:
Folder does not exist

Although I set the folder permission to all and configured it for local sharing. 

What could be the problem??

**Comment by lukeyeager** [comment]
Make sure the entire chain from `/` to your folder is read-able by the user running your server.

> The DIGITS server runs as www-data, so keep in mind that prebuilt LMDB datasets used for generic models need to be readable by the www-data user. In particular, the entire chain of directories from / to your data must be readable by www-data.
https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md#permissions

**Comment by xhuvom** [comment]
DIGITS running from nvidia-docker gives "ERROR: Check failed:" for AlexNet model with CUDA 8.0, cuDNN 5.1

see issue [#221](https://github.com/NVIDIA/nvidia-docker/issues/221)

**Comment by lukeyeager** [comment]
I expect that both of your issues have to do with configuring and running docker, rather than with DIGITS or Caffe. Hopefully the @NVIDIA/nvidia-docker team can help you out.
