### ISSUE TITLE
How to reduce Disk Size of a model?

### ISSUE THREAD

**Issue by RaniemAR** [NVIDIA/DIGITS#432]
Hello guys..

I wonder what are the things to alter in order to get smaller model disk size!!
I tried applying dimension reduction on images and Layer reduction for shallow problems or problems that didn't seem to need a very deep network but when I am comparing results after each change it doesn't seem to be working for me !!
What do you advice..?

My Appreciation ..

**Comment by RaniemAR** [comment]
Seems to be related to the number of epochs as well..
I updated the number of filters in each layer and the size was reduced dramatically ..!! 
but if the accuracy is hitting a good percentage in early epochs can I get rid of redundant epochs!! and can I even consider them as redundant!!
Thanks for your patient reading my queries, I am new to deep learning and trying to understand this..

**Comment by gheinrich** [comment]
@RaniemAR the things that take the most disk space in a DIGITS model are the snapshots. By default DIGITS saves one snapshot after each epoch but during model creation you can change the default value to save them less often by increasing the `snapshot interval`. You can also try and reduce the size of each snapshot by reducing the number of parameters. The fully connected layers are typically where >90% of parameters are stored in a convolutional network so you might want to make them thinner.

**Comment by RaniemAR** [comment]
Thank you very much :)
Now I see why reducing the epochs is reducing the size..
I appreciate your help..
