### ISSUE TITLE
Nvidia Machine Learning Repository URL gives 404

### ISSUE THREAD

**Issue by kureta** [NVIDIA/DIGITS#435]
In the file UbuntuInstall.md the command for installing Nvidia ML repo fails. If I try to go to the full address on my browser it gives 404. If I try to go to http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/ it redirects to an accessdenied/file not found page.

**Comment by lukeyeager** [comment]
Another duplicate of https://github.com/NVIDIA/DIGITS/issues/427.

**Comment by kureta** [comment]
Sorry. I have searched for this subject but couldn't find anything. I saw that you have re-opened the original issue. Sorry for causing trouble. Thanks for the quick response.

**Comment by lukeyeager** [comment]
It's no problem. Sorry for the curt response, it's a busy day!
