### ISSUE TITLE
Different results when model exported to caffe

### ISSUE THREAD

**Issue by cicero19** [NVIDIA/DIGITS#436]
This may not be a definite issue with DIGITS. When exporting a model and loading it into caffe (python web demo) my results appear to differ from the model trained in DIGITS. Additionally, I don't get percentages as output from caffe like I do in DIGITS (they are decimals instead). Has anyone had this issue? I suspect it is an issue with the caffe web demo.

Regarding the mean file, this is the script I run to generate it from the binaryproto

import caffe
import numpy as np
import sys

blob = caffe.proto.caffe_pb2.BlobProto()
data = open( 'models/mean.binaryproto' , 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )
print arr.shape
arr = np.reshape(arr, (3,256,256))
print arr.shape
np.save('models/mean.npy', arr)

**Comment by cicero19** [comment]
I am quite certain this has to do with the mean file. I did the reshape operation because this line:

arr = np.array( caffe.io.blobproto_to_array(blob) )

gives me an array with shape (1, 3, 256, 256). The reshape allows it to run but I don't think it is maintaining the correct mean file. Any insights here?

**Comment by gheinrich** [comment]
@cicero19 this excerpt shows how to convert a `.binaryproto` to `.jpg`. Binaryproto files store images in BGR format, perhaps your script expects RGB format? I am not familiar with the Caffe web demo but on this line it seems to be doing a channel swap:
https://github.com/BVLC/caffe/blob/master/examples/web_demo/app.py#L129
This leads me to believe it's expecting RGB data.

**Comment by cicero19** [comment]
Thanks but No luck.

I am wondering, does the resize mode used at training time in DIGITS have any impact? Presumably the mean file would be different if say a squash method versus a crop or fill method were used. I don't see any parameters for this in the Caffe classifier so at training i'm not sure how it is handling input parameter differences. 

I am getting some negative values for predictions and some above 1.0 (ie. 3.2, 0.85, -0.24, -0.69, -1.3).

**Comment by gheinrich** [comment]
Those predictions are softmax scores. To turn them into probabilities you need to take the exponent of each value and divide it by the sum of the exponents (see [this](https://en.wikipedia.org/wiki/Softmax_function)). For example (and assuming the scores after Top-5 are very small):
```
>>> import math
>>> import numpy
>>> scores=numpy.array([3.2, 0.85, -0.24, -0.69, -1.3])
>>> top_score = numpy.exp(scores[0])/sum(numpy.exp(scores))
>>> print(top_score)
0.862821561535
```
Caffe expects inputs to have the right size, that is why the concept of a fill method is absent in Caffe. We need it in DIGITS when creating a dataset because images may not have the right aspect ratio.

**Comment by cicero19** [comment]
Ok thanks. 

The issue of accuracy and discrepant results when classifying the same image in DIGITS classifier and Caffe is still occurring.  

I've got oversampling on, raw-scale set to 255. Altering the channel swap doesn't make a drastic change. Are there any other variable that need to be considered?

**Comment by cicero19** [comment]
Does DIGITS get percentages from the softmax using the same function you specified above?

**Comment by gheinrich** [comment]
If you're using a `SoftMaxWithLoss` layer then Caffe should automatically perform the math for you and you should get normalized probabilities (see parameters/bottom paragraph on  [SoftmaxWithLoss](http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1SoftmaxWithLossLayer.html#details). DIGITS uses that type of layer for classification therefore the scores it gets are probabilities and no further processing is required.
Why don't you check the classification [example](https://github.com/gheinrich/DIGITS/tree/master/examples/classification)? This shows how to classify a DIGITS-trained model using a standalone Python app.

**Comment by cicero19** [comment]
Thanks. I'm using GoogLeNet architecture. Thats a nice example script. I will use it going forward instead and build a web app to interface with it.
