### ISSUE TITLE
fast-rcnn and faster-rcnn training 

### ISSUE THREAD

**Issue by b0unc3** [NVIDIA/DIGITS#438]
Hi,

is it possible to fine-tune fast/faster-rcnn models on digits?
Thanks.

**Comment by lukeyeager** [comment]
I haven't done it before. Do you have an implementation for Caffe or Torch already that you'd like to use?

**Comment by b0unc3** [comment]
I've been able to train a model using fast-rcnn (with the caffe-fast-rcnn implementation), but I would like to use digits to simplify and automate the training phase.

**Comment by lukeyeager** [comment]
DIGITS requires NVIDIA's fork of Caffe, which was last synced with BVLC/caffe on 09/29/2015 (https://github.com/NVIDIA/caffe/releases).

It looks like `caffe-fast-rcnn` is a different fork of caffe - so DIGITS will reject it.

If Caffe commits to a versioning scheme (https://github.com/BVLC/caffe/pull/3311) which denotes a standardized API, DIGITS will be able to accept a much broader range of Caffe builds - possibly including the `caffe-fast-rcnn` fork.

Alternatively, if the code you need gets merged into BVLC's fork, then it will get picked up in NVIDIA's fork for our next update.

**Comment by mbufi** [comment]
Hi there, revisiting this. Is there a tutorial or at least some steps to get FasterRCNN working with digits? I have yet to see anything that covers beyond detectron.
