### ISSUE TITLE
Fusing digits and caffe

### ISSUE THREAD

**Issue by findorion** [NVIDIA/DIGITS#442]
Hello,

I've been using digits for few months now, and I was  wondering if, once I trained my model with the digits interface, I could use my new "digits" model on new data directly through caffe ?

The purpose would be to  launch it on one command line instead of using the interface, and having a little more controle  too :)

Best regards.

**Comment by gheinrich** [comment]
@findorion there is an example [there](https://github.com/NVIDIA/DIGITS/tree/master/examples/regression) that shows how to use a model trained in DIGITS to classify images from a standalone Python app (which interacts with Caffe through Caffe's Python bindings).

You can also use DIGITS [REST API](https://github.com/NVIDIA/DIGITS/blob/master/docs/API.md) to programmatically perform classification or inference on a DIGITS model.

**Comment by findorion** [comment]
Hello @gheinrich 

Thank you for your fast answer, i'm checking the links above, hopping they're my solution.

Best regards

**Comment by findorion** [comment]
Actually i'm not sure that's what i was looking for.
This example shows more how to build the dataset in command line and then
test the "test.png" image through the interface.
My idea was more the opposit, creating the dataset and training it through
digits, and then using a command line or a python script to send images to
caffe, and then getting the result straigt through caffe.

The Api is another idea, thanks for pointing it out !

Regards,

2015-11-30 16:42 GMT+01:00 Greg Heinrich <notifications@github.com>:

**Comment by gheinrich** [comment]
My apologies, I sent the link to the wrong page. This [page](https://github.com/NVIDIA/DIGITS/tree/master/examples/classification) show how to do classification from Python.

**Comment by findorion** [comment]
Perfect man, thank you for your time and your answers !

2015-11-30 17:25 GMT+01:00 Greg Heinrich <notifications@github.com>:
