### ISSUE TITLE
Error messages displays wrong environment variable names

### ISSUE THREAD

**Issue by mohamed-ezz** [NVIDIA/DIGITS#445]
I've been trying to setup Caffe and DIGITS, for DIGITS I cloned the repo and just ran the server
``./digits-server``
(the instructions for installing digits via apt-get has a broken link and so does not work, see #427)

I got this error from `./digits-server`
``Default value for caffe_root "<PATHS>" invalid:
	Library at "not" does not have expected suffix "-nv". Are you using the NVIDIA/caffe fork?``

I concluded that I need to set `caffe_root`, then spent a significant time making sure caffe_root is set correctly, which failed all the way. Until I checked the source and found that the environment variable being read is `CAFFE_ROOT`, not `caffe_root`.

**Comment by lukeyeager** [comment]
Sorry for the inconvenience! The suggested way to fix your configuration is to use the development server.
```sh
./digits-devserver --config
```
> If you get any errors about an invalid configuration, use the development server first to set your configuration.
https://github.com/NVIDIA/DIGITS/blob/digits-2.0/README.md#production-mode
https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/BuildDigits.md#production-mode

The `CAFFE_HOME` envvar is documented here:
> Set an environment variable so DIGITS knows where Caffe is installed (optional):
    % export CAFFE_HOME=${HOME}/caffe
https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/BuildCaffe.md#download-source
https://github.com/NVIDIA/DIGITS/blob/digits-2.0/docs/InstallCaffe.md#grab-the-source
