### ISSUE TITLE
Validation uses just single CPU thread

### ISSUE THREAD

**Issue by SchranzDampf** [NVIDIA/DIGITS#446]
Hi,
is there any change to run validation step on multiple threads supplying the GPU with data?
During validation just one core (of 8 logical ones) is at 100% and GPU utilization is between 30-40% on a single GTX980.
During training two cores are at 100% and GPU is fully utilized.
As i have lots of validation data, this step consumes a lot of time.

**Comment by lukeyeager** [comment]
If you build Caffe with OpenBLAS instead of ATLAS, I think you'll see better performance.
```sh
# Install the library
sudo apt-get install libopenblas-dev
# Configure your build to use it
cmake .. -DBLAS=Open
```
If that doesn't work, I'll refer you to the [NVIDIA/caffe issues list](https://github.com/NVIDIA/caffe/issues) for follow-up questions.
