### ISSUE TITLE
The NVIDIA branch of caffe does not past make runtest under openSuSE

### ISSUE THREAD

**Issue by michael-george-hart** [NVIDIA/DIGITS#45]
I have been successful in building doing "make runtest" for master branch of caffe. 

I was unsuccessful in getting DIGITS to work properly with it 

Then I became hopeful when I found issues #12 "500: Internal server error , expect blob.data.ndim == 4" and followed to the the instructions letter in getting and buildng the NVIDIA branch of caffe from github ..... it compiles, however "make runtest" consistently fails on a number of different type of testing...
examples cited above:

Cuda number of devices: 2
Current device id: 0
Note: Randomizing tests' orders with a seed of 79470 .
[==========] Running 1068 tests from 198 test cases.
[----------] Global test environment set-up.
[----------] 1 test from HDF5DataLayerTest/3, where TypeParam = caffe::DoubleGPU
[ RUN      ] HDF5DataLayerTest/3.TestRead
F0404 11:38:19.559420 18678 hdf5_data_layer.cpp:89] Failed to open source file: 
*** Check failure stack trace: ***
    @     0x7f7c006a322d  (unknown)
    @     0x7f7c006a4ffc  (unknown)
    @     0x7f7c006a2e1c  (unknown)
    @     0x7f7c006a590e  (unknown)
    @     0x7f7c01057d01  caffe::HDF5DataLayer<>::LayerSetUp()
    @           0x92482a  caffe::Layer<>::SetUp()
    @           0x92706f  caffe::HDF5DataLayerTest_TestRead_Test<>::TestBody()
    @           0x989a33  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9800a7  testing::Test::Run()
    @           0x98014e  testing::TestInfo::Run()
    @           0x980255  testing::TestCase::Run()
    @           0x982f88  testing::internal::UnitTestImpl::RunAllTests()
    @           0x983227  testing::UnitTest::Run()
    @           0x686e6a  main
    @     0x7f7bf6b07b05  __libc_start_main
    @           0x689b32  (unknown)
/bin/sh: line 1: 18678 Aborted                 /home/XMan/Documents/digits-1.0/caffe/build/test/test.testbin --gtest_shuffle
src/caffe/test/CMakeFiles/runtest.dir/build.make:49: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 134
CMakeFiles/Makefile2:273: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:281: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
Makefile:216: recipe for target 'runtest' failed
make: *** [runtest] Error 2

[----------] 5 tests from MemoryDataLayerTest/0, where TypeParam = caffe::FloatCPU
[ RUN      ] MemoryDataLayerTest/0.TestForward
*** Aborted at 1428163234 (unix time) try "date -d @1428163234" if you are using GNU date ***
PC: @     0x7f533fb267d0 caffe::caffe_rng_gaussian<>()
*** SIGSEGV (@0x5850000) received by PID 21890 (TID 0x7f53402af7c0) from PID 92602368; stack trace: ***
    @     0x7f533555a200 (unknown)
    @     0x7f533fb267d0 caffe::caffe_rng_gaussian<>()
    @           0x699b89 caffe::GaussianFiller<>::Fill()
    @           0x6e04d5 caffe::MemoryDataLayerTest<>::SetUp()
    @           0x989a33 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x980040 testing::Test::Run()
    @           0x98014e testing::TestInfo::Run()
    @           0x980255 testing::TestCase::Run()
    @           0x982f88 testing::internal::UnitTestImpl::RunAllTests()
    @           0x983227 testing::UnitTest::Run()
    @           0x686e6a main
    @     0x7f5335546b05 __libc_start_main
    @           0x689b32 (unknown)
/bin/sh: line 1: 21890 Segmentation fault      /home/XMan/Documents/digits-1.0/caffe/build/test/test.testbin --gtest_shuffle
src/caffe/test/CMakeFiles/runtest.dir/build.make:49: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 139
CMakeFiles/Makefile2:273: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CMakeFiles/Makefile2:281: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/rule' failed
make[1]: *** [src/caffe/test/CMakeFiles/runtest.dir/rule] Error 2
M

Cuda number of devices: 2
Current device id: 0
Note: Randomizing tests' orders with a seed of 42443 .
[==========] Running 1068 tests from 198 test cases.
[----------] Global test environment set-up.
[----------] 4 tests from NetUpgradeTest
[ RUN      ] NetUpgradeTest.TestImageNet
*** Aborted at 1428163262 (unix time) try "date -d @1428163262" if you are using GNU date ***
PC: @     0x7f258eca0f18 (unknown)
*** SIGSEGV (@0x7fff00000000) received by PID 21933 (TID 0x7f25990ac7c0) from PID 0; stack trace: ***
    @     0x7f258e357200 (unknown)
    @     0x7f258eca0f18 (unknown)
    @           0x68a25c caffe::NetUpgradeTest_TestImageNet_Test::TestBody()
    @           0x989a33 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9800a7 testing::Test::Run()
    @           0x98014e testing::TestInfo::Run()
    @           0x980255 testing::TestCase::Run()
    @           0x982f88 testing::internal::UnitTestImpl::RunAllTests()
    @           0x983227 testing::UnitTest::Run()
    @           0x686e6a main
    @     0x7f258e343b05 __libc_start_main
    @           0x689b32 (unknown)
/bin/sh: line 1: 21933 Segmentation fault      /home/XMan/Documents/digits-1.0/caffe/build/test/test.testbin --gtest_shuffle
src/caffe/test/CMakeFiles/runtest.dir/build.make:49: recipe for target 'src/caffe/test/CMakeFiles/runtest' failed
make[3]: *** [src/caffe/test/CMakeFiles/runtest] Error 139
CMakeFiles/Makefile2:273: recipe for target 'src/caffe/test/CMakeFiles/runtest.dir/all' failed
make[2]: *** [src/caffe/test/CMakeFiles/runtest.dir/all] Error 2
CM

**Comment by michael-george-hart** [comment]
Found the problem.... I had assumed that the "make runtest" was isolated from references that exist in my openSuSE 13.2 system to caffe master branch of github build....
I just did a W.A.G. and remove all paths to the caffe master build and eventhing is working now... everything from https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md is now working

The take away here is you cannot have to version of caffe in your path....

Thanks again for the good work ;)

**Comment by lukeyeager** [comment]
Yes, a bunch of people are having trouble with multiple versions of caffe installed. I'm looking into creating a git submodule within DIGITS for caffe so that I can more tightly control which files are getting included at runtime. I'll get back to you on that.

Thanks for sharing your experience, and I'm glad you got it working!

**Comment by eliethesaiyan** [comment]
@michael-george-hart ,it seems i have the same problem,i would appreciate if you could give more details on how you solved it...what file did you change,i also don't know what a W.A.G is ...thank you very much
