### ISSUE TITLE
Error 404 while downloading nvidia-machine-learning-repo_4.0-1_amd64.deb 

### ISSUE THREAD

**Issue by alexeykurov** [NVIDIA/DIGITS#451]
ML_REPO_PKG=nvidia-machine-learning-repo_4.0-1_amd64.deb &&
    wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/$ML_REPO_PKG &&
    sudo dpkg -i $ML_REPO_PKG

When running this command from https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md I got 404 error. It seems that link is broken.

**Comment by lukeyeager** [comment]
Duplicate of #427.
