### ISSUE TITLE
Error code 11 - OpenCV 3

### ISSUE THREAD

**Issue by gaozunqi** [NVIDIA/DIGITS#455]
I opened the 'caffe_output.log' file :
```
I1206 11:35:49.397322 15596 layer_factory.hpp:75] Creating layer mnist
I1206 11:35:49.397788 15596 net.cpp:99] Creating Layer mnist
I1206 11:35:49.397819 15596 net.cpp:409] mnist -> data
I1206 11:35:49.397852 15596 net.cpp:409] mnist -> label
I1206 11:35:49.397867 15596 net.cpp:131] Setting up mnist
I1206 11:35:49.400709 15600 db.cpp:34] Opened lmdb /home/go/digits/digits/jobs/20151206-110901-1a8c/train_db
*** Aborted at 1449372949 (unix time) try "date -d @1449372949" if you are using GNU date ***
PC: @     0x7f368c26e8ec (unknown)
*** SIGSEGV (@0x81030001) received by PID 15596 (TID 0x7f36949fba40) from PID 18446744071579041793; stack trace: ***
@     0x7f36931b82f0 (unknown)
@     0x7f368c26e8ec (unknown)
@     0x7f369435994b caffe::DecodeDatumToCVMatNative()
@     0x7f369435ac7e caffe::DecodeDatumNative()
@     0x7f36942f7515 caffe::DataLayer<>::DataLayerSetUp()
@     0x7f36942a6f12 caffe::BaseDataLayer<>::LayerSetUp()
@     0x7f36942a6f93 caffe::BasePrefetchingDataLayer<>::LayerSetUp()
@     0x7f369428b371 caffe::Net<>::Init()
@     0x7f369428c695 caffe::Net<>::Net()
@     0x7f369437f4bc caffe::Solver<>::InitTrainNet()
@     0x7f3694380737 caffe::Solver<>::Init()
@     0x7f3694380996 caffe::Solver<>::Solver()
@           0x4114f0 caffe::GetSolver<>()
@           0x407dc6 train()
@           0x4052db main
@     0x7f36931a3a40 (unknown)
@           0x4059a9 _start
@                0x0 (unknown)
```

**Comment by lukeyeager** [comment]
Hmm, maybe you have an image in your database that OpenCV can't read? How was your dataset created? Look at `backend`, `dataset` and `encoding` here:

    http://localhost:5000/datasets/20151206-110901-1a8c.json

Also, what version of OpenCV do you have?

**Comment by gaozunqi** [comment]
@lukeyeager 
thanks for your answer. My OpenCV version is 3.00 . This error occurs when I run the demo samples.
firstly,I use the "main.py" in "digits/tools/downloads_data" to download the mnist dataset: 
sudo ./main.py -c mnist ~/digits/data/mnist
then I create the dataset by digits and it's sucess.
but when I train the dataset in digits and use the Lenet, the "error 11"occurs.

I opened the "http://localhost:5000/datasets/20151206-110901-1a8c.json" website,it says:
{
  "error": {
    "description": "Job not found",
    "message": "404: Not Found",
    "type": "NotFound"
  }
}

I don't know why

**Comment by gaozunqi** [comment]
@lukeyeager 
thanks for your answer. My OpenCV version is 3.00 . This error occurs when I run the demo samples.
firstly,I use the "main.py" in "digits/tools/downloads_data" to download the mnist dataset: 
sudo ./main.py -c mnist ~/digits/data/mnist
then I create the dataset by digits and it's sucess.
but when I train the dataset in digits and use the Lenet, the "error 11"occurs.

I opened the "http://localhost:5000/datasets/20151206-110901-1a8c.json" website,it says:
{
  "error": {
    "description": "Job not found",
    "message": "404: Not Found",
    "type": "NotFound"
  }
}

I don't know why

**Comment by gaozunqi** [comment]
hi,I found the problem:
the DecodeDatumToCVMatNative function is used for decodeing images such as jpgs.  When I create the dataset with none encode methode, I can train the models sucessful,But when I create the dataset by png or jpeg, the training process error .
Is something wrong with my opencv (3.0.0-rc1)? or something else?

**Comment by lukeyeager** [comment]
This is almost certainly an issue with OpenCV 3.0. The Caffe build instructions say to install the `libopencv-dev` package on Ubuntu 14.04, which installs OpenCV 2.4.

https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/BuildCaffe.md#install-dependencies

I'd try the caffe user groups for questions about OpenCV 3.0:

https://groups.google.com/d/forum/digits-users
https://github.com/BVLC/caffe/issues

**Comment by lukeyeager** [comment]
Any luck?

**Comment by gaozunqi** [comment]
@lukeyeager Thank you very much! These two days I have no time to do opencv , and I still using the BMP format to store the image to make the digits work. And I think if I use the opencv 2.8,the problem mast be sorvled. (-:   Now I close this issue, and thank u !

**Comment by gaozunqi** [comment]
@lukeyeager Thank you very much! These two days I have no time to do opencv , and I still using the BMP format to store the image to make the digits work. And I think if I use the opencv 2.8,the problem mast be sorvled. (-:   Now I close this issue, and thank u !
