### ISSUE TITLE
Repo Errors for v3.0

### ISSUE THREAD

**Issue by cognizac** [NVIDIA/DIGITS#466]
When trying to install the repos as directed in the Digits v3.0 instructions I get the following message after installing the repos and doing apt-get update

Get:4 http://developer.download.nvidia.com  InRelease [252 B]                  
22% [4 InRelease gpgv 252 B] [Waiting for headers] [3 InRelease 14.3 kB/64.4 kBSplitting up /var/lib/apt/lists/partial/developer.download.nvidia.com_compute_macIgn http://developer.download.nvidia.com  InRelease                            d
E: GPG error: http://developer.download.nvidia.com  InRelease: Clearsigned file isn't valid, got 'NODATA' (does the network require authentication?)

How can I fix this?

**Comment by cognizac** [comment]
Sorry just saw your message

**Comment by lukeyeager** [comment]
It's alright, this is actually a different error from #427. We're aware of it and working to resolve it now. Should be fixed soon...

**Comment by cognizac** [comment]
Thanks for the quick reply! :+1:
