### ISSUE TITLE
How to associate job folders with jobs?

### ISSUE THREAD

**Issue by GiuliaP** [NVIDIA/DIGITS#467]
Hi,

I have many jobs and now I need to use the .caffemodel files stored inside job folders to extract features outside DIGITS. The problem is that the names of job folders are not interpretable and I do not know how to associate the folder with the job, whose name is displayed only inside DIGITS. 
Conversely, inside DIGITS I can only see the folder's name if I display datasets, but not models. 
For models, I need to download the .caffemodel to be able to see the name of the job's folder associated with that job. Therefore, at present the only solution I can imagine is to download each .caffemodel manually from inside DIGITS and then annotate on paper the association between the job and the folder's name. Is there any automatic way? 

Thank you!!!
Giulia

**Comment by lukeyeager** [comment]
The job_id is in the url of the page you're looking at, like `/models/$JOB_ID` So just do this to get to the right folder:
```sh
cd $JOBS_DIR/$JOB_ID/
```

I'll add the job folder to the models page - that has bothered me as well.

**Comment by GiuliaP** [comment]
I'm sorry, I didn't notice the job_id in the url of the page.

Ok thank you! In this way indeed it will be fast to see the job folder from the page.
Is there any way to know the job name by looking at the job folder, if e.g. DIGITS is not running?

Thank you again,
Giulia

**Comment by lukeyeager** [comment]
> Is there any way to know the job name by looking at the job folder, if e.g. DIGITS is not running?

No, sorry. It's very convenient to have unique job_id's without requiring that job names be unique.

All the information is contained in the `status.pickle` file, but it's not really intended to be viewed. A command like this might be helpful in a pinch:
```sh
grep "'_name'" jobs/*/status.pickle -A2
```

**Comment by GiuliaP** [comment]
Ok! Thank you very much for your prompt answer!

Giulia

**Comment by lukeyeager** [comment]
@GiuliaP see https://github.com/NVIDIA/DIGITS/pull/469.
