### ISSUE TITLE
Flask-WTF>=0.11 in xubuntu 14.04?

### ISSUE THREAD

**Issue by mnmoustafa** [NVIDIA/DIGITS#48]
Everything goes fine when installing the requirements.txt by pip install, except `Flask-WTF>=0.11`, where I receive this output:
```
Downloading/unpacking Flask-WTF>=0.11
  Downloading Flask_WTF-0.11-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1259, in prepare_files
    )[0]
IndexError: list index out of range
```
I suspect the reason is that the python-flaskext.wtf package in ubuntu 14.04 repository is version 0.6 not 0.11.
When I start the `digits-devserver` it gives me this output:
```
 ___  _  ___ _ _____ ___
 |   \(_)/ __(_)_   _/ __|
 | |) | | (_ | | | | \__ \
 |___/|_|\___|_| |_| |___/

Traceback (most recent call last):
  File "./digits-devserver", line 40, in <module>
    from digits.webapp import app, socketio, scheduler
  File "/home/mmoustafa/digits/digits/webapp.py", line 29, in <module>
    import digits.views
  File "/home/mmoustafa/digits/digits/views.py", line 14, in <module>
    import dataset.views
  File "/home/mmoustafa/digits/digits/dataset/views.py", line 6, in <module>
    import images.views
  File "/home/mmoustafa/digits/digits/dataset/images/views.py", line 9, in <module>
    import classification.views
  File "/home/mmoustafa/digits/digits/dataset/images/classification/views.py", line 12, in <module>
    from forms import ImageClassificationDatasetForm
  File "/home/mmoustafa/digits/digits/dataset/images/classification/forms.py", line 7, in <module>
    from wtforms.validators import ValidationError, StopValidation, Optional, DataRequired, NumberRange, AnyOf
ImportError: cannot import name DataRequired
```
How to fix this?
Thanks,

**Comment by lukeyeager** [comment]
I have seen this error before:

> ImportError: cannot import name DataRequired

And I fixed it by running `pip install --upgrade Flask-WTF`. I'm not sure why that's not working for you.

A little googling makes me suspect that you have an older version of `pip` and/or `distribute` installed?

**Comment by mnmoustafa** [comment]
I think I have the latest versions of packages. Here are some diagnostics:
```
$ apt-cache policy python-pip
python-pip:
  Installed: 1.5.4-1
  Candidate: 1.5.4-1
  Version table:
 *** 1.5.4-1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/status
```
and
```
$ apt-cache policy python-setuptools
python-setuptools:
  Installed: 3.3-1ubuntu1
  Candidate: 3.3-1ubuntu1
  Version table:
 *** 3.3-1ubuntu1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```
but I am not sure why flast-wtf latest version is 0.6 not 0.11? (I have the latest apt-get update)
```
$ apt-cache policy python-flaskext.wtf
python-flaskext.wtf:
  Installed: 0.6-1
  Candidate: 0.6-1
  Version table:
 *** 0.6-1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/status
```
Thanks,

**Comment by lukeyeager** [comment]
I'm running a virtualenv on my machine, which allows me to "overwrite" the system level package (v0.6) with the latest (v0.11) in my local directory. If you whack your package that was installed with apt-get,  pip should be able to do its thing. Try this:

    sudo apt-get purge python-flaskext.wtf
    pip install --upgrade Flask-WTF

For reference, here are the versions that come with apt-get:

    % pip list | grep -i wtf
    Flask-WTF (0.6)
    WTForms (1.0.1)

And here is what pip gives me:

    % pip list | grep -i wtf
    Flask-WTF (0.11)
    WTForms (2.0.2)

**Comment by mnmoustafa** [comment]
I purged the existing flaskext.wtf package and
```
$sudo pip install --upgrade Flask-WTF                                                       
Downloading/unpacking Flask-WTF
  Downloading Flask_WTF-0.11-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1259, in prepare_files
    )[0]
IndexError: list index out of range

Storing debug log for failure in /tmp/tmpte0BRy
```
flask-wtf is not installed/upgraded for some reason.. now my pip gives me:
```
pip list | grep -i wtf
wtf (0.1)
WTForms (1.0.1)
```

**Comment by lukeyeager** [comment]
Have you tried [this](http://stackoverflow.com/a/26882153/2404152)?

**Comment by mnmoustafa** [comment]
This is it. Updating pip and distribute solved the problem. Thank you lukeyeager.

**Comment by afshindn** [comment]
on one of my machines, I'm getting the following error while running ./digits-devserver. I thought this might be related to this post. Any idea how to fix it?

Traceback (most recent call last):
  File "./digits-devserver", line 31, in <module>
    from digits import config
  File "/media/data/common/digits4/digits/config/__init__.py", line 7, in <module>
    from .current_config import config_value
  File "/media/data/common/digits4/digits/config/current_config.py", line 4, in <module>
    from .caffe_option import CaffeOption
  File "/media/data/common/digits4/digits/config/caffe_option.py", line 14, in <module>
    from digits.utils import parse_version
  File "/media/data/common/digits4/digits/utils/__init__.py", line 158, in <module>
    from . import constants, image, time_filters, errors, forms, routing, auth
  File "/media/data/common/digits4/digits/utils/forms.py", line 8, in <module>
    from wtforms.compat import string_types
ImportError: No module named compat


Here is the version of Flask and wtforms that I have installed. 
Flask-WTF (0.12)
WTForms (2.1)

Thanks

**Comment by gheinrich** [comment]
It is strange, the `compat` module has been in `WTForms` for a long time. Is it possible that you have several versions of `WTForms` on your system? Maybe check the contents of the `wtforms` package in your Python `site-packages`...

**Comment by afshindn** [comment]
this is all the files I have in dist-packages for wtforms. And I believe this is the only version I have installed. 

compat.py   ext      form.pyc  __init__.py   meta.py   utils.pyc       widgets
compat.pyc  fields   i18n.py   __init__.pyc  meta.pyc  validators.py
csrf        form.py  i18n.pyc  locale        utils.py  validators.pyc

**Comment by lukeyeager** [comment]
Try this just to be sure:
```sh
$ python -c 'import wtforms;print wtforms.__file__;print wtforms.__version__'
/usr/lib/python2.7/dist-packages/wtforms/__init__.pyc
2.1
```

**Comment by afshindn** [comment]
@lukeyeager and @gheinrich 

Your guess was right. I had two versions on the wtforms. One in "/usr/local/lib/python2.7/dist-packages" and one in "/usr/lib/python2.7/dist-packages". Pip installed the 2.1 version under /usr/local/lib while python was using the version 1.0.1 for /usr/lib/.  

I had to purge the old one and the problem is solved now. Thanks
