### ISSUE TITLE
Problems with changing job_dir

### ISSUE THREAD

**Issue by XueDx** [NVIDIA/DIGITS#482]
I install digits following https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md
In this way, digits would be installed in "/usr/share/digits" and use the "/usr/share/digits/digits/jobs" as default job_dir.
I can't afford so much disk space here and want to use another hard disk.
I try to change job_dir by "sudo python -m digits.config.edit -v". I edit all files (INSTANCE | USER | SYSTEM) and restart digits, but job_dir is still the default one. 
Furthermore, I "mkdir" my own jon dir, "chown" for "www-data" and then use "ln -s" to create a link to ”/usr/share/digits/digits/jobs“. It works well on digits 2.0, but come out an error on digits 3.0 rc1
>
Error: No valid default value found for configuration option "jobs_dir"

**Comment by loweew** [comment]
I also could not get digits to recognize the jobs_dir change in the config files using sudo service nvidia-digits-server restart. What did work for me was manually starting ./digits-server from /usr/share/digits/ 
Now the correct jobs_dir is recognized.

**Comment by lukeyeager** [comment]
My guess is that there's still a permissions issue somewhere:

> The DIGITS server runs as www-data, so keep in mind that prebuilt LMDB datasets used for generic models need to be readable by the www-data user.
https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/UbuntuInstall.md#permissions

Is there nothing helpful in the logs? Did either of you find a work-around in the last week that lets you continue to use the deb packaging?

**Comment by lukeyeager** [comment]
Try changing the `exec` line in `/etc/init/nvidia-digits-server.conf` to this:
```sh
# WAS: exec gunicorn --config /usr/share/digits/gunicorn_config.py digits.webapp:app 2>>/var/log/digits/digits.log

# Redirect both stdout and stderr to the log file
# Use stdbuf to force line buffering
exec stdbuf -oL -eL \
    gunicorn --config gunicorn_config.py digits.webapp:app \
    >>/var/log/digits/digits.log 2>&1
```

**Comment by spmallick** [comment]
I ran into the same problem, but making the new jobs directory read/writable by www-data fixed it.

**Comment by XueDx** [comment]
@spmallick I tried it, but there was something wrong.
@lukeyeager I find something  helpful in the log:
>
2016-01-19 18:12:29 [3761] [INFO] Starting gunicorn 17.5
Default value for jobs_dir "/media/imagelab/Data_Job_A/data/jobs-3" invalid:
	Parent directory does not exist
2016-01-19 18:12:30 [3761] [DEBUG] Arbiter booted
2016-01-19 18:12:30 [3761] [INFO] Listening at: http://0.0.0.0:34448 (3761)
2016-01-19 18:12:30 [3761] [INFO] Using worker: socketio.sgunicorn.GeventSocketIOWorker
2016-01-19 18:12:30 [3822] [INFO] Booting worker with pid: 3822

/media/imagelab/Data_Job_A/data/jobs-3 is my new job_dir and I have changed the permissions by
```
sudo chown -R www-data jobs-3/
```

**Comment by lukeyeager** [comment]
@XueDx make sure that `www-data` can read all of the parent directories:
```
/media/
/media/imagelab/
/media/imagelab/Data_Job_A/
/media/imagelab/Data_Job_A/data/
```

**Comment by XueDx** [comment]
@lukeyeager It seems to be the problem of `/media`, I fail to change the permissions of it. I mount my disk to `/home/[user]` and it works now. Thanks.

**Comment by lukeyeager** [comment]
Glad to hear it!

**Comment by mongoose54** [comment]
@lukeyeager I am having some similar problem with docker version of DIGITS:

`nvidia-docker run --name digits -d -p 5000:5000 -p 6008:6008 -v /nfs-raid/digits-jobs/:/jobs  nvidia/digits:6.0` 

My `/nfs-raid/digits-jobs/` is my old digits jobs at my nfs-raid. 
`/nfs-raid/digits-jobs/`  is `www-data` user:

`drwxr-xr-x 899 www-data root  36864 Dec  7 21:39 digits-jobs`


However I get the following error:

```

   ___ ___ ___ ___ _____ ___
  |   \_ _/ __|_ _|_   _/ __|
  | |) | | (_ || |  | | \__ \
  |___/___\___|___| |_| |___/ 6.0.0
 
 "/jobs" is not a valid value for jobs_dir.
 Set the envvar DIGITS_JOBS_DIR to fix your configuration.
     main()
   File "/usr/local/lib/python2.7/dist-packages/digits/__main__.py", line 53, in main
     import digits.config
   File "/usr/local/lib/python2.7/dist-packages/digits/config/__init__.py", line 7, in <module>
     from . import (  # noqa
   File "/usr/local/lib/python2.7/dist-packages/digits/config/jobs_dir.py", line 25, in <module>
     raise IOError('Permission denied: "%s"' % value)
 IOError: Permission denied: "/jobs"
```

**Comment by langelog** [comment]
If anyone has still a problem with this, you can force the change by moving all current jobs to the new directory, delete the original jobs directory and symlink the new directory as the old jobs directory. In other words:

```sh
NEW_JOBS_DIR="/Storage/DeepJobs"
OLD_JOBS_DIR="/opt/digits/digits/jobs"
cp -r $OLD_JOBS_DIR/* $NEW_JOBS_DIR
rm -rf $OLD_JOBS_DIR
ln -s $NEW_JOBS_DIR $OLD_JOBS_DIR
```

This is really stupid, but it is a fast workaround. 
Hope it helps
