### ISSUE TITLE
GPU usage for model training validation phase.

### ISSUE THREAD

**Issue by michaelholm-ce** [NVIDIA/DIGITS#493]
My issue is regarding the GPU usage for the validation phase of a model training job in DIGITS.  Suppose I train a model using 4 GPUs.  At the end of each training epoch is a relatively shorter validation phase.  Does DIGITS make use of one of the GPUs to execute this validation phase, or is this entirely executed by the CPUs (I can't tell for sure by the logs)?  If not, can validation be executed via GPU (similar to model testing in GPU mode)? 

Also, can a change be made to DIGITS to make use of 4 GPUs in parallel for validation and testing tasks?

Thank you!

**Comment by lukeyeager** [comment]
Multi-GPU is not enabled for the validation phase (but single-GPU is). This is a Caffe limitation. As I understand it, there isn't any particular reason why it couldn't be done, it just requires some work that nobody has done yet. When/if `BVLC/caffe` adds multi-GPU for the validation phase, we'll pull it into `NVIDIA/caffe` for the next release - that's our general workflow.

**Comment by michaelholm-ce** [comment]
Thank you for the explanation, @lukeyeager.

Just to confirm what I'm seeing on my end, is it typical that for the GPU that is selected for validation, its utilization is substantially lower on the validation phase as compared to the training phase?

**Comment by lukeyeager** [comment]
That's not what I'm seeing. My first GPU is 99% utilized and my second is 0% utilized during validation. I'm using a TitanZ (it's a Kepler Gemini board).

**Comment by michaelholm-ce** [comment]
Two thoughts in response:

1) Your metrics indicate that you are using no GPU capability for the validation phase, which seems in conflict with your earlier statement "Multi-GPU is not enabled for the validation phase (but single-GPU is)".  Any thoughts on this?

2) Most of my GPUs go from 60-80% utilization during the training phase (per GPU) down to 0% during the validation phase.  The single GPU that seems to be doing validation goes from ~40-60% utilization during the training phase down to ~10% during validation.  This is the general behavior even when I run on a single GPU.  Is there a possible improvement to increase GPU utilization during training or validation (other than waiting for caffe to introduce multi-GPU validation)?

**Comment by lukeyeager** [comment]
1. Why do you say that? One of my two GPUs is fully utilized during validation.

2. You may want to look into changing your [validation batch size](https://github.com/NVIDIA/DIGITS/blob/v3.0.0-rc.3/digits/standard-networks/caffe/alexnet.prototxt#L29-L31), if you haven't already.

**Comment by michaelholm-ce** [comment]
I apologize, @lukeyeager.  I misread your earlier utilization comment (my error).  I'll try changing validation batch size to try matching the ideal performance you are seeing.  Thanks for the tip.

**Comment by lukeyeager** [comment]
No problem, hope that helps!

**Comment by RobertBiehl** [comment]
Could you elaborate why and how you should change the validation batch size?
