### ISSUE TITLE
No modifications allowed

### ISSUE THREAD

**Issue by koepsell** [NVIDIA/DIGITS#5]
The included LICENSE.pdf file states "If the SOFTWARE is provided in source form, Licensee may not modify or create derivative works of the SOFTWARE."  How can developers work with this git repo?

**Comment by moconnor725** [comment]
My mistake.  That license file was for the installer.  This is now been corrected.  DIGITS is released under the BSD license.

**Comment by koepsell** [comment]
Great, thank you!  I thought that this must have been a mistake.
