### ISSUE TITLE
Specifiy the image list with partial paths + root folder in "Classify many"

### ISSUE THREAD

**Issue by GiuliaP** [NVIDIA/DIGITS#504]
In the "Classify many" option, would it be possible to add the possibility of specifying the image list as a .txt containing partial paths, instead of full paths, and the common root folder separately, as it is already possible to do when creating the dataset?

Thanks,
Giulia

**Comment by gheinrich** [comment]
This sounds like a reasonable request. @lukeyeager do you agree?

**Comment by lukeyeager** [comment]
Sure, sounds good to me. I don't have time to do it right now, but I'll keep this on the TODOs. Or I'd be happy to review a PR from the community!
