### ISSUE TITLE
How to setup cnmem usage 

### ISSUE THREAD

**Issue by thilina27** [NVIDIA/DIGITS#518]
Hi

Im trying out Digits in my local PC. It has only 1GB VRAM. 

most CNN i tried show error that low memory in my VGA.

In theano i can set up Cnmem with .theanorc file like this

[lib]
cnmem=.5

How can i set up it in Digits ? 

Thanks

**Comment by thilina27** [comment]
I think this wont fix my issue , right ? 

I think i need to upgrade my gpu

**Comment by lukeyeager** [comment]
The simplest solution is to upgrade your GPU, as you said.

But you ought to be able to run smaller networks like LeNet with a small card. Are you not able to?

**Comment by thilina27** [comment]
I was able to run LeNet and Alexnet ( alex net wtith small image size ) I think there best thing to do is upgrade my VGA. Thanks for the response.
