### ISSUE TITLE
OSI approved license?

### ISSUE THREAD

**Issue by abdulmuneer** [NVIDIA/DIGITS#521]
Hi,
Would it possible for you guys to provide an OSI approved license to DIGITS application? It will help improve the adoption and contribution as the finer details of those licenses are well known. 
Also, it is easier to specify such a license in setup.py classifiers :)

**Comment by lukeyeager** [comment]
[We have](https://github.com/NVIDIA/DIGITS/blob/master/LICENSE) a 3-clause BSD license. It looks like that falls under the [OSI approved licenses list](https://opensource.org/licenses/alphabetical). What license issue are you referring to?

**Comment by abdulmuneer** [comment]
Thank you for the clarification. What confused me was that the name of license was not mentioned (like 'released under BSD License' etc.), but that's okay.
