### ISSUE TITLE
Error when pressing Visualize LR if Step Size given with decimal point

### ISSUE THREAD

**Issue by mfernezir** [NVIDIA/DIGITS#532]
While creating a new model from an old one with clone model, DIGITS (Version 3.1-dev) sets the Step Size format on its own to decimal (e.g. from 5 to 5.0). This then throws an error when Visualize LR is pressed. If corrected back to pure integer value, the error goes away.  

500: INTERNAL SERVER ERROR
ValueError
invalid literal for int() with base 10: '5.0'

**Comment by gheinrich** [comment]
Thanks for the bug report, I have pushed a change which should fix this (#534)

**Comment by lukeyeager** [comment]
Nice bug report @mfernezir, thanks!
