### ISSUE TITLE
ERROR: Cuda version must be >= 6.5

### ISSUE THREAD

**Issue by amiltonwong** [NVIDIA/DIGITS#54]
Dear all,

I came across "ERROR: Cuda version must be >= 6.5" after following the install guide.

root@milton-Desktop:~/digits# ./digits-devserver 
  ___  _  ___ _ _____ ___
 |   \(_)/ __(_)_   _/ __|
 | |) | | (_ | | | | \__ \
 |___/|_|\___|_| |_| |___/

ERROR: Cuda version must be >= 6.5
Couldn't import dot_parser, loading of dot files will not be possible.
 * Running on http://0.0.0.0:5000/

===================================================================

I had upgraded CUDA into 7.0 version and checked it by tools "deviceQuery" as follows:

root@milton-Desktop:/usr/local/cuda/samples/1_Utilities/deviceQuery# ./deviceQuery 
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX TITAN"
  CUDA Driver Version / Runtime Version          7.0 / 7.0
  CUDA Capability Major/Minor version number:    3.5
  Total amount of global memory:                 6143 MBytes (6441730048 bytes)
  (14) Multiprocessors, (192) CUDA Cores/MP:     2688 CUDA Cores
  GPU Max Clock rate:                            876 MHz (0.88 GHz)
  Memory Clock rate:                             3004 Mhz
  Memory Bus Width:                              384-bit
  L2 Cache Size:                                 1572864 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.0, CUDA Runtime Version = 7.0, NumDevs = 1, Device0 = GeForce GTX TITAN
Result = PASS
root@milton-Desktop:/usr/local/cuda/samples/1_Utilities/deviceQuery# 

====================================================

It seems that "digits" cannot recognize my updated CUDA version. Could someone suggest me how to fix it?

(My system is ubuntu 12.04, 64 bit)

Thanks in advance~
Milton

**Comment by lukeyeager** [comment]
DIGITS loads "libcudart.so" from your system. You probably need to update your `LD_LIBRARY_PATH` to include `/usr/local/cuda-7.0` instead of `/usr/local/cuda-6.0` (or whatever you had before) or change your symlink at `/usr/local/cuda` to point to `/usr/local/cuda-7.0`.

FYI, you can also use the device query in digits at `digits/device_query.py` to make sure that the correct version of CUDA is being loaded.

**Comment by amiltonwong** [comment]
@lukeyeager ,
You're
But now I come across another error as follows : Couldn't import dot_parser

====================================================

root@milton-Desktop:~/digits# ./digits-devserver   ___  _  ___ _ _____ ___
 |   \(_)/ __(_)_   _/ __|
 | |) | | (_ | | | | \__ \
 |___/|_|\___|_| |_| |___/

Couldn't import dot_parser, loading of dot files will not be possible.
 * Running on http://0.0.0.0:5000/

====================================================

I had used digits/device_query.py to test current CUDA being used:

root@milton-Desktop:~/digits/digits# python device_query.pyDevice #0: GeForce GTX TITAN
                totalGlobalMem 6441730048
             sharedMemPerBlock 49152
                  regsPerBlock 65536
                      warpSize 32
                      memPitch 2147483647
            maxThreadsPerBlock 1024
                     clockRate 875500
                 totalConstMem 65536
                         major 3
                         minor 5
              textureAlignment 512
         texturePitchAlignment 32
                 deviceOverlap 1
           multiProcessorCount 14
      kernelExecTimeoutEnabled 1
                    integrated 0
              canMapHostMemory 1
                   computeMode 0
                  maxTexture1D 65536
            maxTexture1DMipmap 16384
            maxTexture1DLinear 134217728
             maxTextureCubemap 16384
                  maxSurface1D 65536
             maxSurfaceCubemap 32768
              surfaceAlignment 512
             concurrentKernels 1
                    ECCEnabled 0
                      pciBusID 1
                   pciDeviceID 0
                   pciDomainID 0
                     tccDriver 0
              asyncEngineCount 1
             unifiedAddressing 1
               memoryClockRate 3004000
                memoryBusWidth 384
                   l2CacheSize 1572864
   maxThreadsPerMultiProcessor 2048
     streamPrioritiesSupported 0
        globalL1CacheSupported 0
         localL1CacheSupported 1
    sharedMemPerMultiprocessor 49152
         regsPerMultiprocessor 65536
           managedMemSupported 1
               isMultiGpuBoard 0
          multiGpuBoardGroupID 0

====================================================

Could you suggest me how to fix the "Couldn't import dot_parser" issue?

Thanks!

**Comment by amiltonwong** [comment]
I finally fix that issue by following this thread:
http://stackoverflow.com/questions/15951748/pydot-and-graphviz-error-couldnt-import-dot-parser-loading-of-dot-files-will

=====================================================

pip uninstall pyparsing
pip install -Iv https://pypi.python.org/packages/source/p/pyparsing/pyparsing-1.5.7.tar.gz#md5=9be0fcdcc595199c646ab317c1d9a709
pip install pydot

=====================================================
