### ISSUE TITLE
Ubuntu deb installation

### ISSUE THREAD

**Issue by jas0n1ee** [NVIDIA/DIGITS#540]
I follow the instruction in [here](https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md) to install to digit caffe torch.

When I using torch to run some program, this following error shown up:
```
/usr/local/bin/luajit: /usr/local/share/lua/5.1/trepl/init.lua:383: module 'loadcaffe' not found:No LuaRocks module found for loadcaffe
	no field package.preload['loadcaffe']
	no file '/home/bfomitchev/.luarocks/share/lua/5.1/loadcaffe.lua'
	no file '/home/bfomitchev/.luarocks/share/lua/5.1/loadcaffe/init.lua'
	no file '/usr/local/share/lua/5.1/loadcaffe.lua'
	no file '/usr/local/share/lua/5.1/loadcaffe/init.lua'
	no file './loadcaffe.lua'
	no file '/usr/local/share/luajit-2.1.0-beta1/loadcaffe.lua'
	no file '/home/jisli/.luarocks/share/lua/5.1/loadcaffe.lua'
	no file '/home/jisli/.luarocks/share/lua/5.1/loadcaffe/init.lua'
	no file '/home/bfomitchev/.luarocks/lib/lua/5.1/loadcaffe.so'
	no file '/usr/local/lib/lua/5.1/loadcaffe.so'
	no file './loadcaffe.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/jisli/.luarocks/lib/lua/5.1/loadcaffe.so'
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/trepl/init.lua:383: in function 'require'
	neural_style.lua:6: in main chunk
	[C]: in function 'dofile'
	/usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```

While `jisli` is me, `bfomitchev` seems to be some nvidia employee. I'm still finding the reason that why torch will crash and I will rebuild it from source code, but it's interesting to see someone's name in an error msg :)

**Comment by borisfom** [comment]
Hi Jason,

You are right – I am this employee ☺
My home dir was left in the .deb package due to imperfect .db build – it’s completely benign though (unless you have some evil user under same id).
Your problem is probably exactly as reported : the program you run failed to load loadcaffe module.
Do you have loadcaffe Lua module installed in one of the trees listed below ?

Best,
-Boris.

**Comment by gheinrich** [comment]
Hi @jas0n1ee can you be more specific on:
> When I using torch to run *some program*

What is the program you are using? DIGITS does not use `loadcaffe` module.

**Comment by jas0n1ee** [comment]
@gheinrich I have solve the problem with installing `loadcaffe` module. For most purpose of this, I'm just curious about who is the guy `bfomitchev`. Apology if there is any disturbing.
