### ISSUE TITLE
Issue with lightningmdb luarocks package

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#544]
> It looks like all LMDB/Torch tests are failing with a SEGFAULT (HDF5 tests pass). This seems to be a regression in the current version of the lightningmdb wrapper on Luarocks registry. The latest version of Github is working. I have filed an issue on shmul/lightningmdb#10.
@gheinrich https://github.com/NVIDIA/DIGITS/pull/541#issuecomment-175047706

Assuming they don't get this fixed immediately, how can we fix this from our end?

**Comment by lukeyeager** [comment]
I'm attempting to fix it with https://github.com/lukeyeager/DIGITS/commit/772c444bbbc880bd85e026a608c9d6f4c1e56425. Let's see how the TravisCI build goes ...

**Comment by lukeyeager** [comment]
[My build](https://travis-ci.org/lukeyeager/DIGITS/builds/104959237) passed. Looks like [yours](https://travis-ci.org/gheinrich/DIGITS/builds/104963236) did too (except for the timeout failure). So it looks like either upgrading or downgrading will work, as you guessed.

In general, I would lean towards downgrading and fixing our requirements to known good versions. But I guess we're already building bleeding-edge for all of our Torch components already. So let's go with your version, since it updates the documentation as well.

BTW, is there no parallel to a `pip` requirements.txt file for `luarocks`?

**Comment by gheinrich** [comment]
Thanks. I don't mind either way. I have opened PR #545 if you still want to take mine.

I don't know of a `luarocks` equivalent to `pip -r requirements.txt`. That could be done with a script?

**Comment by lukeyeager** [comment]
> Some were indeed broken, but as far as I know, 0.9.17.4-1 solves them all. I uploaded it to the main luarocks site a couple of days ago and it is listed there now.
@shmul https://github.com/shmul/lightningmdb/issues/10#issuecomment-177136607

Should we switch back to using the luarocks website now? Both are "bleeding-edge" options, but maybe waiting for them to be posted on the main luarocks site is a tiny bit less "bleeding-edge"?

**Comment by borisfom** [comment]
I agree we should switch, for the next package,
