### ISSUE TITLE
Error when use "Step Down (arbitrary steps)" in learning rate policy

### ISSUE THREAD

**Issue by 201power** [NVIDIA/DIGITS#547]
When I use "Step Down" (arbitrary steps) policy in the learinng rate,  set to "6,50", the digits generated error: 
ValueError: could not convert string to float: ,

**Comment by lukeyeager** [comment]
Which version of DIGITS are you using? This was fixed in https://github.com/NVIDIA/DIGITS/pull/534.
```
$ ./digits-devserver --version
3.2-dev

$ git describe
v3.1.0-12-ga95b89e
```

**Comment by 201power** [comment]
I use:

$ ./digits-devserver --version
3.2-dev

$ git describe
v3.1.0-7-g07a4697

**Comment by lukeyeager** [comment]
Oh, you used a comma. Use a period.

**Comment by 201power** [comment]
Can I input two step values? Means step down at 6%, and then step down again at 50%. 
I tried "6.50" it does not work.

**Comment by lukeyeager** [comment]
Aha, now I see what you're saying! Sorry, I should have read your OP more carefully. That does look like a bug. Hang on a minute ...

**Comment by lukeyeager** [comment]
Wow you found a bug that was present in the **initial commit** for this repository. Apparently nobody has ever used this feature before - hah!

Thanks for the bug report. Fix is at https://github.com/NVIDIA/DIGITS/pull/549 - I'll merge when the TravisCI build passes.

**Comment by gheinrich** [comment]
If it's any comfort, it has never worked for Torch either :-)
