### ISSUE TITLE
Is it possible to have a standalone solution

### ISSUE THREAD

**Issue by StevenLOL** [NVIDIA/DIGITS#55]
Is it possible to have a standalone solution? 

So that I don't need to install those dependencies, last time I spend one day to install Caffe and only managed to install it on 2/3 of my computers due to OS (ubuntu 12.04/12.10/14.04)  and dependency (boost,opencv,gcc,cuda,hdf5) issues.

I have disk space, and I have hardware, so I don't mind even if a standalone package is 10GB or more.

**Comment by lukeyeager** [comment]
The web installer that you can download from https://developer.nvidia.com/digits is a standalone solution, but it is only for Ubuntu 14.04. A platform-independent standalone solution is not possible - even many of the required python packages have to get compiled on installation and wouldn't work on another system.

**Comment by Kaixhin** [comment]
If you're able to use Docker then I have a standalone CPU-only DIGITS image available at https://registry.hub.docker.com/u/kaixhin/digits/. Instructions are included in the readme.

Obviously this is quite slow - if I am able to redistribute the cuDNN archive with my Docker images then I would be able to create one with CUDA and cuDNN.

**Comment by lukeyeager** [comment]
Nice work, @Kaixhin! I had started down that path of creating a Dockerfile for DIGITS, but I got sidetracked with other things.

**Comment by Kaixhin** [comment]
Thanks @lukeyeager, it wasn't very difficult with your clearly documented instructions. Given the license for cuDNN is there any way it can be included in a Docker image? Not only would it let me build the optimal DIGITS image, but also plenty of other deep learning libraries.

**Comment by lukeyeager** [comment]
cuDNN is currently only available to registered developers. If the license or distribution strategy changes, I'll be sure to let you know.

**Comment by Kaixhin** [comment]
Thanks for the clarification. Nevertheless Docker seems like a decent standalone solution considering VMs would require GPUs with virtualisation capabilities. The only issue is providing different CUDA/driver versions, and I haven't been able to think of a good solution so far.

**Comment by StevenLOL** [comment]
Thanks @Kaixhin , glade to know docker.

**Comment by StevenLOL** [comment]
Thanks all.

**Comment by Kaixhin** [comment]
@StevenLOL does the Docker container meet your requirements? If so @lukeyeager perhaps it is worth documenting on the readme or elsewhere?

**Comment by MiguelGarciaCalderon** [comment]
Hi @Kaixhin can you tell how to open digits homepage?

**Comment by Kaixhin** [comment]
@MiguelGarciaCalderon Sorry looks like there was a problem with `digits-server`, but `digits-devserver` seems to be working fine. I've updated the Dockerfiles and rebuilt/tested `kaixhin/digits` successfully. Rebuilding `kaixhin/cuda-digits` now so those should be ready within a few hours.

**Comment by lukeyeager** [comment]
@MiguelGarciaCalderon @Kaixhin @StevenLOL 
There is now an official Docker solution from NVIDIA which includes prebuilt images for DIGITS:
https://github.com/NVIDIA/nvidia-docker/wiki/DIGITS

**Comment by MiguelGarciaCalderon** [comment]
Thank you I m going to use it
