### ISSUE TITLE
RMSPROP, ADADELTA & ADAM solver support

### ISSUE THREAD

**Issue by mfernezir** [NVIDIA/DIGITS#555]
Hello,

could you add support for additional solvers that are present in NVIDIA's  0.14 Caffe branch? Namely, RMSPROP, ADADELTA and ADAM:
https://github.com/NVIDIA/caffe/blob/caffe-0.14/src/caffe/proto/caffe.proto#L213

**Comment by lukeyeager** [comment]
@mfernezir I created a pull request to add these solvers: https://github.com/NVIDIA/DIGITS/pull/564

Can you test them out? All I did was make sure that there weren't any errors when I selected the new solvers. It would be nice to have somebody try to actually train a model with these solvers and report back on whether we can do anything more in DIGITS to help make these alternate solvers easier to use correctly.

**Comment by mfernezir** [comment]
@lukeyeager cool! :) I've just run a quick test on MNIST, all new solvers are working fine. I will also try using them on datasets I'm currently working with.

Disclaimer: I'm using v0.14.0-rc.1 Caffe with CuDNN 3 and CUDA 7.5. I haven't moved to newer 0.14 versions of Caffe since there is a newly introduced bug that breaks CuDNN 3: https://github.com/NVIDIA/caffe/issues/85
As for CuDNN 4 and 0.14.0-rc.3, there was also some bug that I reported so I haven't tried using it further. https://github.com/NVIDIA/caffe/issues/98

Regarding DIGITS usability enhancements, it would be good to have an option to manually edit solver.prototxt before the training starts. Alternative option would be to allow changing all solver parameters by using DIGITS interface, but note there are some new ones for these new solvers besides momentum. https://github.com/NVIDIA/caffe/blob/caffe-0.14/src/caffe/proto/caffe.proto#L221:L229

In the long run, it may be more easier to have a separate button to actually start training after clicking "create model" so that the user could manually inspect and edit solver.prototxt if desired.

**Comment by 201power** [comment]
For the adaDelta and adaGrade solver, how should I set the learning rate? Fixed?

Since adaDelta/adaGrade have adaptive learning rate, does it only need an initial learning rate?
In my case, adaDelta / adaGrade does not work as well as SGD.
