### ISSUE TITLE
requirements for webinstall ubuntu 14.04 (grpahViz, cuDNN)

### ISSUE THREAD

**Issue by scharfy** [NVIDIA/DIGITS#56]
I have been working through a successful web-install on clean ubuntu 14.04

The requirements only stated to have driver 346 - so I haven't downloaded cuDNN or graphviz

When I attempt to visualize a network (visualize button ) when building a model 

![image](https://cloud.githubusercontent.com/assets/7809322/7074866/58d24962-dec3-11e4-8944-ca976de446b9.png)

I return this error
![image](https://cloud.githubusercontent.com/assets/7809322/7074876/729ef818-dec3-11e4-93a3-d4ba37f44dc7.png)

Do i need to get graphviz and cuDNN on my own?

Thanks and my apologies if this is the wrong place for this question.  Great work

**Comment by openzeka** [comment]
I am getting same warning.

**Comment by lukeyeager** [comment]
Ah, it looks like we left out a line in the "one_time.sh" script. I'll make sure that's fixed for the next packaged version. Thanks for reporting it!

For now, if you want to use the visualization tool, you can manually run this command:

    sudo apt-get install graphviz
