### ISSUE TITLE
Internal server error when expecting integer number of epochs but receiving a float instead (3.2 dev)

### ISSUE THREAD

**Issue by mfernezir** [NVIDIA/DIGITS#570]
Steps to reproduce the bug:

New Image Classification Model -> Previous Networks -> select some previous network and pretrained model -> click Customize

If you select a previous model with fractional epoch naming (e.g. Epoch#2.75) and click 'Customize', there is an error:

500: INTERNAL SERVER ERROR

ValueError
invalid literal for int() with base 10: '2.75'

If the selected epoch naming is not fractional (e.g. Epoch#3) then there is no interface error after clicking Customize.

**Comment by lukeyeager** [comment]
Thanks for the excellent bug report! Fix is at #571.
