### ISSUE TITLE
Incorrect name in siamese network definition

### ISSUE THREAD

**Issue by danst18** [NVIDIA/DIGITS#574]
I believe [this parameter](https://github.com/NVIDIA/DIGITS/blob/master/examples/siamese/mnist_siamese_train_test.prototxt#L279) should be called `ip2_b` to share the weights with the [left side of the network](https://github.com/NVIDIA/DIGITS/blob/master/examples/siamese/mnist_siamese_train_test.prototxt#L132).

**Comment by gheinrich** [comment]
Well spotted, thanks!

**Comment by gheinrich** [comment]
I have pushed #575 to fix this.
