### ISSUE TITLE
How to extract the feature vector？

### ISSUE THREAD

**Issue by ybguo1** [NVIDIA/DIGITS#577]
For example, I have some images and I want to extract the feature in the first fully connection layers. Could you tell what should I do?

**Comment by gheinrich** [comment]
If you tick the box `Show visualizations and statistics` above `Test One` or `Classify One` buttons then DIGITS will show a visualization of the weights and activations for each layer. Is that enough or are you asking for the raw data?

**Comment by ybguo1** [comment]
Thank you. I have solved this problem by caffe and matlab.

**Comment by Noor59007** [comment]
@gheinrich i want the raw data in each layer can i?

**Comment by gheinrich** [comment]
@Noor59007 there is currently no way to retrieve the raw data from DIGITS UI. The raw data are captured [there](https://github.com/NVIDIA/DIGITS/blob/master/digits/model/tasks/caffe_train.py#L1061) (Caffe) and [there](https://github.com/NVIDIA/DIGITS/blob/master/digits/model/tasks/torch_train.py#L687) (Torch) and later stored in a temporary HDF5 file [there](https://github.com/NVIDIA/DIGITS/blob/master/tools/inference.py#L198-L214). There is currently no way to retrieve the data from DIGITS UI. Feel free to file a new issue if you feel this is needed.

**Comment by d1993b** [comment]
@gheinrich I am a beginner use DIGITS with Caffe.
I want to captured raw data in each layer. 
Could you tell me how to do in your link?
Thank you.

**Comment by gheinrich** [comment]
Hello, you might want to look at this for an example: https://groups.google.com/d/msg/digits-users/HLhwy2R4G5Q/foKsFAxXAwAJ

**Comment by d1993b** [comment]
@gheinrich 
Thank you very much for your help.
I will read the discussion in the group.
Thank you.
