### ISSUE TITLE
Problems with relative server paths

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#593]
*Reported by @gheinrich at https://github.com/NVIDIA/DIGITS/pull/586#discussion_r53694262*

When selecting files for upload, the file auto-completion is relative to the CWD of the DIGITS server (i.e. `~/digits` or `/usr/share/digits`). But when the files are actually used, they are relative to the jobs directory (since the subprocess CWD [is altered](https://github.com/NVIDIA/DIGITS/blob/v3.0.0/digits/task.py#L206)).

We should probably just disallow relative paths in general.

**Comment by Lucaszw** [comment]
Fixed by: #773

**Comment by Lucaszw** [comment]
resolved by #773
