### ISSUE TITLE
Test Many issue

### ISSUE THREAD

**Issue by danst18** [NVIDIA/DIGITS#599]
The *Test Many* feature is not working properly for me when using generic inference.

It seems that I can't test more images than the batch size that I used for training. For example, if I use a batch size of 16 in the siamese network example from the docs and I try to test more than 16 images this is what I get:

![screenshot from 2016-02-24 15 21 38](https://cloud.githubusercontent.com/assets/6713977/13290418/67495d10-db0b-11e5-9fad-2aa35bdc0434.png)

The result for the first four images is not correct. As you can see in the screenshot below, when I remove the last ten images the result for the first four images is correct.

![screenshot from 2016-02-24 15 22 40](https://cloud.githubusercontent.com/assets/6713977/13290421/69a960f0-db0b-11e5-848b-7966ece6e7f4.png)

**Comment by gheinrich** [comment]
Hi @danst18 are you using CuDNN 4.0.7?

```
$ dpkg -s libcudnn4
Package: libcudnn4
Status: install ok installed
Priority: optional
Section: multiverse/libs
Installed-Size: 60054
Maintainer: cudatools <cudatools@nvidia.com>
Architecture: amd64
Source: cudnn
Version: 4.0.7
```

**Comment by danst18** [comment]
Hi @gheinrich, the command doesn't find libcudnn4, probably because I manually placed the files in the cuda folders. However:
```
% ls /usr/local/cuda/lib64/*cudnn* -1
/usr/local/cuda/lib64/libcudnn.so
/usr/local/cuda/lib64/libcudnn.so.4
/usr/local/cuda/lib64/libcudnn.so.4.0.7
/usr/local/cuda/lib64/libcudnn_static.a
```

**Comment by lukeyeager** [comment]
Ok, that rules out one possibility. What version of DIGITS are you using?

```
$ ./digits-devserver --version
3.3-dev
```

**Comment by danst18** [comment]
I was on 3.2-dev. I just updated to 3.3-dev and the problem persists.

**Comment by lukeyeager** [comment]
I see it too ...

**Comment by lukeyeager** [comment]
@danst18 can you try out #603?

**Comment by danst18** [comment]
@lukeyeager Sorry for my late reply. I just tried this and works fine :+1:
