### ISSUE TITLE
runme.sh error "ImportError: No module named datetime"

### ISSUE THREAD

**Issue by Jiakui** [NVIDIA/DIGITS#6]
./runme.sh gives an error that datatime module could not be found. But I checked with "python -c "from datetime import datetime, date"", no error was given.

What's could be the reason?

Thanks!

./runme.sh
  ___  _  ___ _ _____ ___
 |   \(_)/ __(_)_   _/ __|
 | |) | | (_ | | | | \__ \
 |___/|_|\___|_| |_| |___/

Traceback (most recent call last):
  File "digits/digits-devserver", line 40, in <module>
    from digits.webapp import app, socketio, scheduler
  File "/home/iranyu/DeepLearning/digits-1.0/digits/digits/webapp.py", line 6, in <module>
    from flask import Flask
  File "/home/iranyu/DeepLearning/digits-1.0/python-env/lib/python2.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/home/iranyu/DeepLearning/digits-1.0/python-env/lib/python2.7/site-packages/werkzeug/__init__.py", line 154, in <module>
    __import__('werkzeug.exceptions')
  File "/home/iranyu/DeepLearning/digits-1.0/python-env/lib/python2.7/site-packages/werkzeug/exceptions.py", line 67, in <module>
    from werkzeug._internal import _get_environ
  File "/home/iranyu/DeepLearning/digits-1.0/python-env/lib/python2.7/site-packages/werkzeug/_internal.py", line 15, in <module>
    from datetime import datetime, date
ImportError: No module named datetime

**Comment by lukeyeager** [comment]
Hi Jiaku, are you running Ubuntu 14.04? A little googling led me to [this page](http://stackoverflow.com/questions/26031160/importerror-no-module-named-datetime) which makes me suspect that you may have a ubuntu version issue. The web installer has binaries built specifically for Ubuntu 14.04 x64, so you would run into other problems even if you fixed your python packages (if indeed you are running another OS).

**Comment by Jiakui** [comment]
I am running Ubuntu 14.10 x64, right now I am using the downloaded binaries.

Is it possible to build the binary from scratch? That might eliminate the problem.

Thanks!

**Comment by lukeyeager** [comment]
Sure you can, just follow the instructions in the [README](https://github.com/NVIDIA/DIGITS/blob/master/README.md).

**Comment by lukeyeager** [comment]
Were you able to build from scratch? Did you ever figure out what was causing your error?

**Comment by Jiakui** [comment]
Yes, I built from scratch on Ubuntu 14.10 and it is able to run. I haven't checked the source of error for downloaded binary.

Thanks!

**Comment by lukeyeager** [comment]
Alright, then I'll close this issue.

If anyone else runs into this problem, please let me know and I'll look into it more. I suspect it has something to do with the virtualenv setup for the web installer.
