### ISSUE TITLE
Digits For Audio datasets

### ISSUE THREAD

**Issue by simplybarca** [NVIDIA/DIGITS#607]
I would like to ask if Digits supports audio datasets. if so where we can start.?

**Comment by gheinrich** [comment]
Hello, for the moment DIGITS only works with image data. Can you have a look at https://github.com/NVIDIA/DIGITS/issues/197 and provide information on what you're looking for and how you think this feature could be implemented? That will help us come up with the best solution for everyone.

I am closing this bug. Thanks for the feedback!
