### ISSUE TITLE
New "classify many images" feature

### ISSUE THREAD

**Issue by michael-george-hart** [NVIDIA/DIGITS#61]
I am not really sure how to classify this issue..... so hopefully no one reading reading this thinks it a silly thing to post.
First let me state I am new to DIGITS/CAFFE however, bought into the sales pitch about easy of use...
So training was easy... Had images with dimension between 512x512 to 4096x4096.... squashed the images to make them all fit into 256x256....
The system trained and am ready to classify my test images ....

   I was under the impression using "Test several images"  would at least display the predicted categories of all the data in "val.txt" file... What I got was a screen full of images from the various layers for what seem to be all 5 categories of images --to me a rather useless things to have from my trained network.

My question is, and it would be a nice feature to have in DIGITS, is how to I take my well trained network and predict the categories without now searching through a lot of CAFFE documentation and examples to get prediction of associated categories of my test images.

Not being a CAFFE/DIGIT expert I assume I am going to have to SQUASH all my test image before my trained network can test them.... where do I find the code that squashed the images during training?

**Comment by lukeyeager** [comment]
You're right - "Test several images" is not an intuitive or well-documented feature. But it is a helpful one. Let me explain what the current testing features are then propose a new feature that you seem to be expecting:

**Test one image** - rename to "Classify One Image"?
Takes one image and classifies it. It displays the top 5 category predictions for this image, and also displays the weights and activations for the network.

**Test several images** - rename to "Top N Predictions"?
Takes a list of images and classifies all of them. Then it takes the top N images (9 by default) by confidence for each category and displays those. The top left image for each category is the network's most confident guess. If your network is well behaved and you upload a large enough sample, all of the images shown will be under the correct category.

**Classify Many Images** - *new*
Takes a list of images and classifies all of them. Displays the top 5 category predictions for all images in a big table.

> Not being a CAFFE/DIGIT expert I assume I am going to have to SQUASH all my test image before my trained network can test them

Certainly not. But you do have to upload each one manually at the moment. I think the "Classify Many Images" feature would get you what you want - right?

In general, DIGITS is not a deployment solution; it's a training system. The output of DIGITS is a trained model which you then take and plug into some other software which consumes the model.

**Comment by michael-george-hart** [comment]
"....output of DIGITS is a trained model which you then take and plug into some other software which consumes the model..."
Of course I did not expect it to be a production system .... but my entire buy in to DIGITS was seeing the "Test one Image" and seeing the relative association of categories and then thinking that the "Test several Images" ( having seen a demo) was a generalization of that "Test on image".

Could you point me to where the code "Test one Image" is in DIGITS so I may look at how it works and perhaps generalize it to produce outputs for an arbitrary number of images. I am fairly confident that would be more useful to a great many people who do not want to get into the gritty details of integrating a trained network into some other software model..... They would only want the image names and their associations to the categories... 

Most people I feel would simply want their model to produce prediction of category association along with the image names for arbitrary number of images ... even if it was not as pretty as what you currently have now for "Test several images" and see images .... especially if you have several thousand images; I would rather have the file name to those images displayed rather the images themselves

Thanks for the clarification...

**Comment by lukeyeager** [comment]
> Could you point me to where the code "Test one Image" is in DIGITS so I may look at how it works and perhaps generalize it to produce outputs for an arbitrary number of images. 

Sure thing. It would require:

* Adding a new button to the [template](https://github.com/NVIDIA/DIGITS/blob/ecd751630bafe86e8409d743135f4ebf0319f8fa/digits/templates/models/images/classification/show.html#L315-L322)
* Adding a new route to the [view](https://github.com/NVIDIA/DIGITS/blob/ecd751630bafe86e8409d743135f4ebf0319f8fa/digits/model/images/classification/views.py#L207-L208)
* And possibly some changes to [this function](https://github.com/NVIDIA/DIGITS/blob/ecd751630bafe86e8409d743135f4ebf0319f8fa/digits/templates/models/images/classification/show.html#L315-L322), but it may already be general enough for what you want to do.

And if you don't get to it, I can add this feature sometime next week because you're right: 
> that would be more useful to a great many people

**Comment by michael-george-hart** [comment]
This weekend, and perhaps, a good part of next week, is going to be a super busy for me.... 

Unfortunately I committed myself to using Caffe for a current project because of some misunderstanding about DIGITS (see prior messages) ... so now I have to figure how to integrate my trained DIGITS/CAFFE network into some code (PYTHON/C++) to get the images file names and their relative belonging to each classification  --anyone already have to code to do this? 

Anyway, I have been looking for a open-source project to become apart of; I guess this will be the one if you don't mine me joining.... I have been making my money being a "PYTHON EXPERT" :D ;) for the past four plus years even though C++ (twenty plus years) is my language of choice along with some CUDA for about (two to three years now)....

Looking forward in working on this project and thanks for the hints... hopefully what I need to know to complete my project will not take me too long so I can get working on your hints....

**Comment by michael-george-hart** [comment]
My complements on your code... very clean and easy to understand... it show your experience in being a clear communicator :)
Hopefully I will have a solution shortly...
I just grabbed a download of latest digit master. I tried running it on a system that have a fully functional version of digits I download about 2015-04-01. I got and unexpected error and did not seem want to correct itself even after I typed in SYS.  This "/usr/local/caffe/bin" is the correct location for caffe..  

~/DIGITS-master> ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Invalid config option for "caffe_root": ldd: ./caffe: No such file or directory
Welcome to the DIGITS config module.

Guessed "/usr/local/caffe/bin" from CAFFE_HOME
ERROR: Does not contain the caffe binary
Where is caffe installed?
        (enter "SYS" if installed system-wide)
        [default is SYS]
(q to quit) >>>

**Comment by michael-george-hart** [comment]
Here is my minor contribution to DIGITS which I believe would be more useful to a great many people. ---question; is the code using the GPU when it processing test images? In my case it seem to have a good amount of time getting the results.
 
Hopefully you can make it pretty and add a nice interface for it ... I would think that you would give the options to produce with or without the graphics -- in my code I commented out all the graphic producing stuff.

After These two line of code
    if scores is None:
        return 'An error occured while processing the images', 500

I added the following several lines of code: 
    pPath = "/home/XMan/Downloads/lables.csv"
    with open(pPath, "w") as f:
      f.writelines(str(labels));

    with open(pPath, 'w') as f:
      for index, score in enumerate(scores):
        line = '"' + paths[index] + '",'

        for i,prob in enumerate(score):
          line += "{0:.16f}".format(prob)
          if i != len(score) - 1:
            line += ','
        line += '\n'
        f.write(line)    

 Should we ever meet; I owe you a beer or a lunch ... this was quick and dirty but thanks to you and showing me where to look I have some results to submit for my project.... I was caught off-guard how much of a pain it was to get these results using the C++ Caffe ... there was nothing consistent I could find in the various blogs that was usefully to get to this point in such a short time using your hints......

**Comment by lukeyeager** [comment]
@michael-george-hart, I just added this feature and renamed some of the buttons per your suggestion.

> Hopefully you can make it pretty and add a nice interface for it

I wouldn't call my implementation pretty and nice. In fact, it's intentionally frill-free to make it easier to copy-paste the output into excel if that's what you want to do. I'm way past due for a general UI upgrade. When I get around to that, I'll find a way to display the results in a more pleasing manner.

**Comment by michael-george-hart** [comment]
Looking forward in grabbing this from the DIGITS master download this weekend... 
The changes that you recommended earlier are working for me right now.... 
Thanks for your efforts. I definitely want to have a look at the new stuff....

**Comment by Tutufa** [comment]
Guys, can you help me to do same thins? Id like to use trained model, and classify ~ 50k of images. As far as I understand there is no way to get .csv file with probabilities and names, only pop-up with most probable classes (button - Classifiy mane images) or most probable image to class (button Top N per category). @michael-george-hart has written code which does what I need (I think), where should I put it? @lukeyeager

**Comment by Tutufa** [comment]
And I have weird problem: I know how to make model through pycaffe (in ipython for example), and use net.Classifier, but probabilities I get in digits interface and ones using net.Classifier are different (fir the same image).

**Comment by lukeyeager** [comment]
> probabilities I get in digits interface and ones using net.Classifier are different (for the same image)

Can you share the script that you're using? Are you using the .caffemodel (and other files in the tarfile download) that DIGITS outputs?

Compare it with what DIGITS does in [this function](https://github.com/NVIDIA/DIGITS/blob/v1.1.0/digits/model/tasks/caffe_train.py#L629-L647). I expect that we are doing the data preprocessing differently. If you can show me that DIGITS is doing it wrong, that is definitely something that needs to be fixed.

**Comment by Tutufa** [comment]
I managed to output csv file, by modifying function image_classification_model_classify_many() in views.py

just add this right after scores calculated

```python
# create csv files and write names and probs there
    dump_csv = open('/home/ubuntu/results.csv', 'w')
    dump_csv.write('Path\tProbabilities')
    for i,j in zip(paths, scores):
        newline = i + '\t' + str(j) + '\n'
        dump_csv.write(newline)
    dump_csv.close()
```

Yes I think preprocessing is the cause, also. Nevertheless I know how to get csv now. I wish I knew html to create a button, and help with this feature.... Maybe later this summer, when all projects are done. Thanks @lukeyeager !

**Comment by djebm2** [comment]
@lukeyeager What command do Classify One/Many Image call behind the scene ?

**Comment by lukeyeager** [comment]
> What command do Classify One/Many Image call behind the scene ?

What is it that you want to know? You can jump through the code yourself if you like. Do you need a pointer to get started?

Start here: https://github.com/NVIDIA/DIGITS/blob/v3.2.0/digits/model/images/classification/views.py#L250-L305

You'll end up here:
https://github.com/NVIDIA/DIGITS/blob/v3.2.0/digits/model/tasks/caffe_train.py#L1065-L1104
