### ISSUE TITLE
 IndexError: Show visualizations and statistics

### ISSUE THREAD

**Issue by tofighi** [NVIDIA/DIGITS#618]
DIGITS: Version 3.0.0 via apt-get

After training, I tried to classify one image and  selecting "Show visualizations and statistics". Without " Show visualizations and statistics" it works, but when I try to use this option, I receive the following error:
```
IndexError
only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/digits/digits/model/images/classification/views.py", line 291, in image_classification_model_classify_one
    predictions, visualizations = job.train_task().infer_one(image, snapshot_epoch=epoch, layers=layers)
  File "/usr/share/digits/digits/model/tasks/caffe_train.py", line 1018, in infer_one
    layers=layers,
  File "/usr/share/digits/digits/model/tasks/caffe_train.py", line 1065, in classify_one
    visualizations = self.get_layer_visualizations(net, layers)
  File "/usr/share/digits/digits/model/tasks/caffe_train.py", line 1172, in get_layer_visualizations
    allow_heatmap = bool(top != 'data'))
  File "/usr/share/digits/digits/utils/image.py", line 366, in get_layer_vis_square
    vis = upscale(vis, ratio)
  File "/usr/share/digits/digits/utils/image.py", line 102, in upscale
    out[y,x] = image[math.floor(y/ratio), math.floor(x/ratio)]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by gheinrich** [comment]
Hi @tofighi, do you get this error for any network you train or just a particular one?
The error is a bit puzzling... are you able to modify the code? I'd be curious to know the output of those lines just before that [line](https://github.com/NVIDIA/DIGITS/blob/digits-3.0/digits/utils/image.py#L102)
```
print out.shape
print image.shape
print x,y
print ratio
print math.floor(y/ratio), math.floor(x/ratio)
```

**Comment by tofighi** [comment]
Hi @gheinrich , I'm able to change the code, but not sure how to do that. It gives me error for all networks I trained. I had  Version 3.0.0 RC and it works before, but after upgrading to Version 3.0.0 it gives me this error.

**Comment by lukeyeager** [comment]
> I had Version 3.0.0 RC and it works before, but after upgrading to Version 3.0.0 it gives me this error.

Nothing changed in the code that would cause this error:
https://github.com/NVIDIA/DIGITS/compare/v3.0.0-rc.3...v3.0.0

Just a guess, but did you upgrade `numpy` at some point? Here's the version that I have:
```
$ python -c 'import numpy; print numpy.__version__, numpy.__file__'
1.8.2 /usr/lib/python2.7/dist-packages/numpy/__init__.pyc
```

**Comment by tofighi** [comment]
Thank you all.
I found the issue. It was because of the version on Nympy which was 1.11.0b1. I downgraded it to 1.10.4 and now it is working without any problems.
Best

**Comment by lukeyeager** [comment]
Weird. 1.11 breaks backwards compatibility? Hopefully it's just a bug, since you were running what looks like a beta version.

Glad to hear you sorted it out!
