### ISSUE TITLE
Bug in create_db.py: Method disregards image size input arguments

### ISSUE THREAD

**Issue by andredubbel** [NVIDIA/DIGITS#626]
The method create_lmdbs in DIGITS/examples/siamese/create_db.py takes image_height and image_width as input.

If not given they are set to a default 'IMAGE_SIZE' value. After that the variables are never used again. Instead the shape is set by the first image in the file list. I think this will break if you supply a list of images of different sizes?

It feels like the idea here was to be able to set an image size and that images would be resized to this size before being added to the database.

**Comment by gheinrich** [comment]
Indeed I only tested this with images from the MNIST dataset and didn't implement image resizing. We could remove those unused parameters. Would that be OK or are you willing to see an example of how we could resize images at the same time, like [this](https://github.com/NVIDIA/DIGITS/blob/master/tools/inference.py#L95-L99)?

**Comment by andredubbel** [comment]
Either is fine by me, I just figured you had intended to add that functionality and forgotten about it.

If you remove the parameters maybe the example should state somewhere that the scripts expects images to be of the same size?
