### ISSUE TITLE
cuda installation error

### ISSUE THREAD

**Issue by kklw** [NVIDIA/DIGITS#635]
Hi. My OS is ubuntu 14.04LTS, gpu: nvidia gtx950m. I downloaded cuda-repo-ubuntu1404-7-5-local_7.5-18_amd64.deb from https://developer.nvidia.com/cuda-downloads . I tried the following:

$sudo dpkg -i cuda-repo-ubuntu1404-7-5-local_7.5-18_amd64.deb`
$sudo apt-get update`
$ sudo apt-get install cuda
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> You might want to run 'apt-get -f install' to correct these:
> The following packages have unmet dependencies:
>  cuda : Depends: cuda-7-5 (= 7.5-18) but it is not going to be installed
>  libcudnn4-doc : Depends: libcudnn4-dev but it is not going to be installed
> E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

$ sudo apt-get -f install libcudnn4-dev

> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> You might want to run 'apt-get -f install' to correct these:
> The following packages have unmet dependencies:
>  libcudnn4-dev : Depends: libcudnn4 but it is not going to be installed
> E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

How can i resolve this error? Thanks.

**Comment by gheinrich** [comment]
Did you try the suggested `apt-get -f install` (with no package)?

**Comment by lukeyeager** [comment]
It looks like you might have tried to install `libcudnn4-doc` at some point without having access to `libcudnn4-dev`. Just get rid of that package now, until you have all your other packages set up correctly.

    sudo apt-get remove libcudnn4-doc

Read these instructions carefully - they should have all the info you need to get up and running:
https://github.com/NVIDIA/DIGITS/blob/master/docs/UbuntuInstall.md
https://github.com/NVIDIA/DIGITS/blob/master/docs/InstallCuda.md

**Comment by kklw** [comment]
Thanks @gheinrich, @lukeyeager . Other than using the nvidia installation guide, I had to set the path permanently by referring to this: [http://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux](set path). I had to update gedit as there is a bug on the older version. I ended up installing geany.  After downloading the samples, I ran `make -rpath `instead.

**Comment by gheinrich** [comment]
This [doc](https://github.com/NVIDIA/DIGITS/blob/master/docs/InstallCuda.md#environment) shows three different ways of setting up the library path.

Besides, regarding the `nvidia-uvm` issue the appropriate package should be automatically installed if you followed the CUDA install instructions (because `cuda-drivers` depends on this package).
