### ISSUE TITLE
Aligning Nvidia DIGITS and OpenCV DNN together 

### ISSUE THREAD

**Issue by djebm2** [NVIDIA/DIGITS#639]
I have successfully trained a model with Digits using GoogleNet. I have tried to classify some new images using the Digits GUI and it seems to work fair enough.

However, when testing the model with OpenCV DNN module [1], I get mediocre results. Therefore, I would like to have access to the script/program initiating the forward pass on digits when hitting the _classify one _button.

I am thinking that this issue could be a great opportunity to build a new functionality for people who want to train their networks on digits and run them afterwards on OpenCV.  

[1] My program is based upon the following opencv [sample](http://docs.opencv.org/3.1.0/d5/de7/tutorial_dnn_googlenet.html#gsc.tab=0). It support GoogleNet.

**Comment by TimZaman** [comment]
Dead link? Are you working with caffe or torch?

**Comment by djebm2** [comment]
Link updated. The framework I use is caffe.

**Comment by gheinrich** [comment]
Caffe inference in DIGITS is done from this [method](https://github.com/NVIDIA/DIGITS/blob/v3.3.0/digits/model/tasks/caffe_train.py#L1184-L1234). If you are willing to replicate your DIGITS results from another program that is the function you need to port. Does that answer the question?

**Comment by djebm2** [comment]
Yes, thank you.
