### ISSUE TITLE
visualize the CNN network

### ISSUE THREAD

**Issue by dxj19831029** [NVIDIA/DIGITS#64]
see this tool? 
'''
http://people.csail.mit.edu/torralba/research/drawCNN/drawNet.html
'''
I think this looks really nice and useful, It shows all the connections of activation between each layer, and also the activation area.

 Any plan for this?

**Comment by michael-george-hart** [comment]
They nice to look at... until you actually have to do some real work with them .... then it becomes a nightmare; such is my experience... do your homework before you commit to a tool

**Comment by lukeyeager** [comment]
> http://people.csail.mit.edu/torralba/research/drawCNN/drawNet.html

Wow, that *is* pretty.

> Any plan for this?

Not currently. Higher on the visualization priority list is a backprojection of the network that tells you which part of an image contributed most strongly to the predicted class. I don't have any example pages to show you right now, but hopefully I'll have something soon!
