### ISSUE TITLE
Torch tool test.lua cannot be called inside own directory.

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#641]
If test.lua (tools/torch/test.lua) is called (manually) from within tools/torch/ you will get the following error:
```
tim@test:~/INSTALL/NVIDIA/DIGITS/tools/torch$ th test.lua 
/usr/bin/luajit: test.lua:19: attempt to concatenate a nil value
stack traceback:
	test.lua:19: in main chunk
	[C]: in function 'dofile'
	/usr/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
```
solution is calling test.lua from elsewhere.

**Comment by gheinrich** [comment]
Thanks for the feedback! Actually the statement that fails can be removed, it is redundant with these [lines](https://github.com/NVIDIA/DIGITS/blob/master/tools/torch/test.lua#L11-L14).
