### ISSUE TITLE
How should I use the DIGITS to gpu model?

### ISSUE THREAD

**Issue by gaozunqi** [NVIDIA/DIGITS#646]
I have installed Digits by the doc in "https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildCaffe.md",
but the default mode of digits is the cpu_only.
I rebuild the  caffe-nv by change the CMakeLists.txt , from the 
"[ caffe_option(CPU_ONLY  "Build Caffe without CUDA support" OFF)" to
"caffe_option(USE_CUDA  "Build Caffe without CUDA support" ON)".
But it does not works.
How should I use the DIGITS to gpu model?

**Comment by gheinrich** [comment]
Hello, are you sure CUDA is correctly installed on your system? Have a look at this [page](https://github.com/NVIDIA/DIGITS/blob/master/docs/InstallCuda.md) for instructions. After you have installed CUDA make sure it is working by calling the script under `<DIGITS>/digits/device_query.py`. This should return a list of GPUs. Then rebuild Caffe from a clean folder if necessary.

**Comment by lukeyeager** [comment]
When you do get CUDA installed on your machine correctly, you won't need to make any changes to `CMakeLists.txt`. CUDA will be detected automatically.

**Comment by gaozunqi** [comment]
yes ,you are right! @gheinrich  @lukeyeager  
I installed cuda , but have not set the Environment.
now it's ok .
thank u
