### ISSUE TITLE
how to bind digits /venv/bin/python proccess to a customized gpu,for example gpu 0

### ISSUE THREAD

**Issue by StevenSama** [NVIDIA/DIGITS#647]
help me,how to bind digits /venv/bin/python proccess to a customized gpu,for example gpu 1

**Comment by gheinrich** [comment]
I am not sure what is meant by `digits /venv/bin/python` but you can use the DIGITS configuration menu and select which GPUs you wish to use.

To edit the configuration have a look at these [instructions](https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/UbuntuInstall.md#configuration) (`.deb` install) or these [instructions](https://github.com/NVIDIA/DIGITS/blob/digits-3.0/docs/BuildDigits.md#troubleshooting) (source install).

**Comment by StevenSama** [comment]
for example,i get the info from nvidia-smi show like this,
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     13835    C   /data5/digits-2.0/venv/bin/python             1057MiB |

I wanted /data5/digits-2.0/venv/bin/python runed on GPU 1

**Comment by gheinrich** [comment]
Did my comment https://github.com/NVIDIA/DIGITS/issues/647#issuecomment-199007952 help? Are you seeing this during training or inference? Please provide more details.

**Comment by StevenSama** [comment]
i modified the caffe_train.py at the line 932 add Caffe.set_deviceid(1) and it work thx

**Comment by gheinrich** [comment]
You shouldn't have to modify the code. Either set the GPU from the config menu or select the GPU you want to use when creating the model.

**Comment by superphil0** [comment]
maybe starting the digits server with CUDA_VISIBLE_DEVICES=x digits-server
will help you? where x is the device id

**Comment by lukeyeager** [comment]
@StevenSama there is no way to bind a virtualenv to a GPU. As others have said, you can either use `CUDA_VISIBLE_DEVICES` or the built-in DIGITS mechanisms to choose your GPU.
