### ISSUE TITLE
Latest DIGITS Master cannot find Caffe .....

### ISSUE THREAD

**Issue by michael-george-hart** [NVIDIA/DIGITS#65]
I just grabbed a download of latest digit master. I tried running it on a system that have a fully functional version of digits I download about 2015-04-01. I got and unexpected error and did not seem want to correct itself even after I typed in SYS.  This "/usr/local/caffe/bin" is the correct location for caffe..  

~/DIGITS-master> ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Invalid config option for "caffe_root": ldd: ./caffe: No such file or directory
Welcome to the DIGITS config module.

Guessed "/usr/local/caffe/bin" from CAFFE_HOME
ERROR: Does not contain the caffe binary
Where is caffe installed?
        (enter "SYS" if installed system-wide)
        [default is SYS]
(q to quit) >>> SYS
ERROR: ldd: ./caffe: No such file or directory

(q to quit) >>> 

@lukeyeager : My complements on your code... very clean and easy to understand... it show your experience in being a clear communicator :)
Hopefully I can be helpful....

**Comment by lukeyeager** [comment]
Oh, are you trying to install caffe in weird places? DIGITS is pretty rigid about the caffe installation paths right now. It's looking for the binary at $CAFFE_HOME/**build/tools/**caffe, not $CAFFE_HOME/caffe. You've got to satisfy [this validation function](https://github.com/NVIDIA/DIGITS/blob/27386ed3326157de091f44468c2afcef7097fb8c/digits/config.py#L93-L124). 

So, you probably want to go down this path:
* Add `/usr/local/caffe/bin` to your `PATH`
* Add `/usr/local/caffe/python` (or wherever the caffe python module is) to your `PYTHONPATH`
* Set the `caffe_root` in DIGITS to "SYS"

**Comment by michael-george-hart** [comment]
I don't think this is a closed issue.
I started from scratch in a brand new environment and followed the instruction exactly found at this URL https://github.com/NVIDIA/DIGITS and still getting the same problem.

In my $HOME directory I have caffe and digits
export CAFFE_HOME=${HOME}/caffe
cd digits
:~> cd digits
:~/digits> ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Welcome to the DIGITS config module.

Guessed "/home/XMan/caffe" from CAFFE_HOME
ERROR: Does not contain the caffe binary
Where is caffe installed?
        (enter "SYS" if installed system-wide)
        [default is SYS]
(q to quit) >>> q

**Comment by lukeyeager** [comment]
Oh, sorry. Then what did you mean by this:

> This "/usr/local/caffe/bin" is the correct location for caffe..

Did you install caffe like [this](https://github.com/NVIDIA/DIGITS/blob/master/README.md#prerequisites)?

    % cd $HOME
    % git clone --branch v0.11.0 https://github.com/NVIDIA/caffe.git

Cloning caffe there and building it there should give you the caffe binary at 

    $HOME/caffe/build/tools/caffe

Is it there?

**Comment by michael-george-hart** [comment]
ON my machine 
$HOME/caffe/build/tools/caffe
/home/XMan/caffe/build/tools/caffe: error while loading shared libraries: libcaffe.so: cannot open shared object file: No such file or directory
So the binary is there

**Comment by michael-george-hart** [comment]
As you can see even after I set the LD_LIBRARY_PATH and the PATH directly to the binary 
I am still having issues running the latest master ---do you have any recommendation on how fix this.... 

XMan@earth:~> export LD_LIBRARY_PATH=/home/XMan/caffe/build/lib
XMan@earth:~> $HOME/caffe/build/tools/caffe                    
caffe: command line brew
usage: caffe <command> <args>

commands:
  train           train or finetune a model
  test            score a model
  device_query    show GPU diagnostic information
  time            benchmark model execution time

  Flags from /home/XMan/Documents/caffe/tools/caffe.cpp:
    -gpu (Run in GPU mode on given device ID.) type: int32 default: -1
    -iterations (The number of iterations to run.) type: int32 default: 50
    -model (The model definition protocol buffer text file..) type: string
      default: ""
    -snapshot (Optional; the snapshot solver state to resume training.)
      type: string default: ""
    -solver (The solver definition protocol buffer text file.) type: string
      default: ""
    -weights (Optional; the pretrained weights to initialize finetuning. Cannot
      be set simultaneously with snapshot.) type: string default: ""
XMan@earth:~> cd digits
XMan@earth:~/digits> ./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Welcome to the DIGITS config module.

Guessed "/home/XMan/caffe" from CAFFE_HOME
ERROR: Does not contain the caffe binary
Where is caffe installed?
        (enter "SYS" if installed system-wide)
        [default is SYS]
(q to quit) >>> SYS
ERROR: caffe binary not found

(q to quit) >>> q
XMan@earth:~/digits> export PATH=/home/XMan/caffe/build/tools/
caffe                     compute_image_mean        extract_features          net_speed_benchmark       upgrade_net_proto_binary
CMakeFiles/               convert_imageset          finetune_net              test_net                  upgrade_net_proto_text
cmake_install.cmake       device_query              Makefile                  train_net                 
XMan@earth:~/digits> export PATH=/home/XMan/caffe/build/tools:$PATH
XMan@earth:~/digits> ./digits-devserver                            
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Welcome to the DIGITS config module.

Guessed "/home/XMan/caffe" from CAFFE_HOME
ERROR: Does not contain the caffe binary
Where is caffe installed?
        (enter "SYS" if installed system-wide)
        [default is SYS]
(q to quit) >>> SYS
ERROR: ldd: ./caffe: No such file or directory

(q to quit) >>> q
XMan@earth:~/digits> ca
caffe               caller              cameratopam         case                catchsegv           
cal                 callgrind_annotate  cancel              caspol              catman              
call-browser        callgrind_control   captoinfo           cat                 
XMan@earth:~/digits> ca
caffe               caller              cameratopam         case                catchsegv           
cal                 callgrind_annotate  cancel              caspol              catman              
call-browser        callgrind_control   captoinfo           cat                 
XMan@earth:~/digits> caffe 
caffe: command line brew
usage: caffe <command> <args>

commands:
  train           train or finetune a model
  test            score a model
  device_query    show GPU diagnostic information
  time            benchmark model execution time

  Flags from /home/XMan/Documents/caffe/tools/caffe.cpp:
    -gpu (Run in GPU mode on given device ID.) type: int32 default: -1
    -iterations (The number of iterations to run.) type: int32 default: 50
    -model (The model definition protocol buffer text file..) type: string
      default: ""
    -snapshot (Optional; the snapshot solver state to resume training.)
      type: string default: ""
    -solver (The solver definition protocol buffer text file.) type: string
      default: ""
    -weights (Optional; the pretrained weights to initialize finetuning. Cannot
      be set simultaneously with snapshot.) type: string default: ""
XMan@earth:~/digits> whereis caffe
caffe: /home/XMan/caffe/build/tools/caffe

**Comment by lukeyeager** [comment]
Sorry, this is devolving a bit from the intended purpose of a GitHub issue. Would you mind reposting in the digits-users google group with a clear, concise explanation of your issue?
https://groups.google.com/d/forum/digits-users

(We'll get to the bottom of  this, I'm just trying to keep this issue list clean and related to bugs or feature requests)
