### ISSUE TITLE
Explore a previous made lmdb

### ISSUE THREAD

**Issue by engharat** [NVIDIA/DIGITS#650]
Hi,
I'm using DIGITS for classification on grayscale 16bit PNG loaded into a lmdb dataset with the image_convert caffe utility. When I created the lmdb I hadn't enabled the compression, so as far I understand the lmdb should contain the plain PNG data.
Anyway, I cannot see any "explore db" option, while it should be one of the features of DIGITS 3.

**Comment by gheinrich** [comment]
Hello, the "explore db" option is only available for classification datasets that were created using DIGITS and the LMDB backend.

Besides, there is no support for compression in LMDB as far as I know. Do you mean to say that you didn't enable *encoding* (which is  a Caffe `Datum` option)? Without encoding, the raw pixel data are stored in the LMDB. With encoding, the data are stored in either PNG or JPG format. Note that Caffe doesn't support loading 16-bit encoded data. You will have to check whether `image_convert` preserves the depth of your input images as I am not sure it does.

**Comment by engharat** [comment]
Thanks for the fast reply. Yes, as compression I mean the the png format storage sorry :) I have noticed as caffe doesn't like my 16 bit grayscale png!that is before discovering the nice lmdb dataset format ;) 
But, I had some problems as well with digits lmdb creation, it gave me an error but I should do more trials with it (hoping my 16 bit png will be supported by digits lmdb!) 
Anyway, at the end there is no support to explore db support for external lmdb, while I should not have any problem with the digit-made lmdb! Thanks, I will try soon. 
P. S. Said that there could be still problems with 16bit png on image_convert, I will open my lmdb and I will look at how data is stored, but as far as the training is going nicely and the lmdb is ten times the png files, I'm pretty confident they have been stored into 16bit raw pixel data....

**Comment by gheinrich** [comment]
Sorry, for the moment DIGITS does not support 16-bit png either. See also https://github.com/NVIDIA/DIGITS/issues/99.

I am curious to know if the depth of your images is preserved when using `image_convert` as a quick look at the code led me to believe it doesn't. When Caffe calls `cv::imread` [there](https://github.com/BVLC/caffe/blob/master/src/caffe/util/io.cpp#L78) it doesn't set the flag `CV_LOAD_IMAGE_ANYDEPTH` so I assume the data are implicitly converted to 8 bits.

**Comment by engharat** [comment]
Damn, I think you are right :/ looking at cv::imread specifications, it is clearly written that flag is not set, the data will be converted to 8 bits.
Plus, with quick& dirty calculation, ignoring the label value stored into the lmdb, for each 256x256px grayscale 16bit  stored into the lmdb i should have 2 byte * 256 * 256 = 128kbyte.
Looking at the size of my lmdb, it should be 142gb but it is actually 80 :/
So, my data is lowered down to 8 bit ahah I'm happy that it still works! :-D 
Okey, Gheinrich even if it is off-topic could you please be so kind to tell my what would happen if I modify image_convert code, putting the CV_LOAD_IMAGE_ANYDEPTH into it?:-) Would that 16bit lmdb be read and processed correctly by caffe?maybe some other code modification, or it should be changed the deep caffe structure?
Thanks again!

**Comment by gheinrich** [comment]
I don't think it will work without further hacks as `CVMatToDatum` expects 8-bit data. Ultimately, Caffe blobs are stored as 32-bit floats so as long as you're able to load your data the rest of the code should work without any further change.

**Comment by engharat** [comment]
So basically I should hack all the code about load and reading input data, looking at CVMatToDatum function and change it accordingly. I will try. 
At the same time, I should check what digits do when loading external lmdb - if it only accept it and feeds it to caffe framework I would be fine, in the other case I should change digits read functions as well.

**Comment by gheinrich** [comment]
Since there doesn't seem to be an issue in DIGITS per se, I'll close this issue.

**Comment by tfeo** [comment]
https://github.com/engharat , have you been successful in your 16-bit hacks? I curious since I am dealing with 16-bit data as well and am looking for ways to stuff 16 bit input into caffe.

**Comment by tfeo** [comment]
@engharat , have you been successful in your 16-bit hacks? I curious since I am dealing with 16-bit data as well and am looking for ways to stuff it into caffe without rescaling.

**Comment by engharat** [comment]
I haven't. I managed to build a lmdb dataset filled by 16 bit data by hand,
but then the training didn-t converged. But I did very few trials months
ago, then I switched on 8 bit data .
I suggest to build that lmdb dataset by some python functions and then
rescaling the data into -128 +128 range ( but actually with 16 bit
precision) and check if the training is converging. Then, when you are sure
that caffe is correctly digesting your data, you could try without scaling
- just my two cents.


2017-03-09 20:57 GMT+01:00 tfeo <notifications@github.com>:

**Comment by gheinrich** [comment]
There is an example using 16-bit images on https://github.com/NVIDIA/DIGITS/tree/digits-5.0/examples/medical-imaging
