### ISSUE TITLE
Editboxes: integers and doubles seperator error

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#652]
I have been ignoring this issue for a while but let's face it.
I can reproduce it like this:
- Open a new classification
- Press on the _show advanced learnign rate options_ checkbox
- Often times i immediatelly get the below error:
![image](https://cloud.githubusercontent.com/assets/7721540/13986852/e9398958-f104-11e5-9320-53259948b274.png)
The step size's default is 33.0. But, the editbox talks to the visualizer (i guess) which epects an integer, not a double.
Moreover, i have many issues that just drop the learning rate to 0 after the first epoch, but it's hard to reproduce.

**Comment by gheinrich** [comment]
Hello, what revision of DIGITS are you using? This was fixed in #534.

**Comment by gheinrich** [comment]
Closing this issue - feel free to re-open if #534 doesn't work for you.
