### ISSUE TITLE
Cannot train GoogLenet without a validation dataset.

### ISSUE THREAD

**Issue by igorbb** [NVIDIA/DIGITS#654]
This issue seems to happen with the current master-branch.
I am doing some experiments where I do not have access to a validation dataset. 
On previous digits-version I Could easily train my network on DIGITS whenever it only had the training dataset.

The network is the GoogLenet that comes with digits.
Now, if i create a LMDB though digits (text file specification), that only has training dataset I receive the following.

`CaffeTrainSanityCheckError: Layer 'conv1/7x7_s2' references bottom 'data' at the TEST stage however this blob is not included at that stage. Please consider using an include directive to limit the scope of this layer.
`

This seems related to #601 . But I could not figure out a way to fix it.
Any suggestions ?

**Comment by gheinrich** [comment]
Well spotted and thanks for the report! We shouldn't sanity check the `val` phase if there is no validation set. Can you check if #655 works for you?

**Comment by igorbb** [comment]
I can. I will do today and let you guys know. :)

**Comment by igorbb** [comment]
@gheinrich  It works well with #655 .

Should I close this issue ?

**Comment by gheinrich** [comment]
Thanks for testing! This issue will be closed automatically if #655 gets merged.
