### ISSUE TITLE
[bug] Training stopped after "Classify one"

### ISSUE THREAD

**Issue by enoonIT** [NVIDIA/DIGITS#664]
I tried to perform a "Classify One" during training of an Alexnet (on Caffe). The new page (which should show the result) remains empty, even after several minutes. The training is now stuck.

I don't usually have this issue, this is the first time it has happened to me. I had to kill the server and restart it.

**Comment by TimZaman** [comment]
I have had the same thing very often, very annoying. But for me it was solved when i built from source, with the latest versions apparently already fixing this issue. What version are you running?

**Comment by enoonIT** [comment]
I was using the source version, dowloaded on the 21st of march. I now updated to the latest version, let's see if it happen again (I hope not!)

**Comment by igorbb** [comment]
I've also noticed this on version '3.0' . Haven't had it happen with the current source of '3.3'.

**Comment by gheinrich** [comment]
I believe this was fixed with https://github.com/NVIDIA/DIGITS/pull/573. Feel free to re-open the issue if you see this again after #573.

**Comment by enoonIT** [comment]
Happened to me today, latest digits. If it matters i'm using 2 gpus
