### ISSUE TITLE
Incorrect labels generated in train.txt and val.txt? 

### ISSUE THREAD

**Issue by amruthaprasad** [NVIDIA/DIGITS#665]
When creating a new image classification dataset in DIGITS using the "Use Image Folder" option, the "?" besides "Training Images" pops a text box which reads "Indicate a folder which holds subfolders full of images. Each sub-folder should be named according to the desired label for the images that it holds..."

In my current dataset that I have, I have about 26 classes and the images are organized into sub-folders with labels from 0 to 25. I would assume that each image in the sub-folders would assume the label of the name of the "sub-folder" i.e 0 for 0; 1 for 1; ..; 25 for 25. But the train.txt and the val.txt that are generated after creating the "New Dataset" seem to have different labels? Seems like the sub-folders are being arranged as (0,1,10,11,12,...19,2,20,  ..25) with the labels (0,1,2,3,...,25)

So, what are the actual labels for the images in the sub-folders?

**Comment by gheinrich** [comment]
Hello, when DIGITS analyses your image folders, each sub-folder is associated with a class ID (i.e. a number). The class name is the name of the sub-folder. The mapping between class IDs and class names can be found in the `labels.txt` file of your job folder (this file contains the list of class names and the index of each class name is the class ID). During training, the class ID is used (the neural network expect the label to be a number, not a string like 'cat' or 'dog'). The class name is only used for visualization purpose in DIGITS when you click `classify one` or `classify many`. In your case, class names are also numbers but DIGITS sees them as strings. When your sub-folders are parsed in alphabetical order it will parse folders named '10','11',... before the folder named '2', hence the somewhat confusing labels you're seeing.

I hope this helps.

**Comment by tehoro** [comment]
If you wanted them to match, just name your sub-folders as 00, 01, 02, ... 09, 10, etc.

**Comment by amruthaprasad** [comment]
Thanks Greg/ Tehoro! That helps.
I ran into this issue while I was trying to use my own labels.txt (0,1,2,3,4,...,11,12,...25) for classification using the example.py script in python and a model generated using DIGITS.
I should be using the labels.txt that was found in the jobs directory instead of my own to get correct classification labels. Thanks!

**Comment by gheinrich** [comment]
Thanks, I am closing the issue then.
