### ISSUE TITLE
'Related Jobs' window feature

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#667]
It's too bad #137 was abandoned. It was a huge amount of half-working features that i am trying to split out and work on one by one (the which i want to add). The related jobs view is very nice to me as i can see which datasets i can throw away when they are not used, and i can jump around easily between jobs using the name dataset.
Therefore the feature request to implement this, which i have already done. i will file a pull request soon. 
<img width="1200" alt="8e24a58e-1432-11e5-9808-6acd7e63bb80" src="https://cloud.githubusercontent.com/assets/7721540/14253313/517c3cf6-fa8b-11e5-8db7-89900c04c1d0.png">

**Comment by lukeyeager** [comment]
Why close this? I agree with you - I'd like to see this feature added soon.

**Comment by TimZaman** [comment]
Ah sorry Luke. I have this feature implemented in my own fork, but i worked very fast so I didnt put it in a nice branch to make a decent pull request. Actually, this feature is the one i miss most (from my own fork) when i use the vanilla Nvidia-master branch.

**Comment by lukeyeager** [comment]
Hey @TimZaman are you working on this already? I see some commits referencing this issue. If not, @Lucaszw can do it.

**Comment by TimZaman** [comment]
It's been in our fork for ages, and I have no clue how you guy can live without it. How about the Confusion Matrix? That's just so damn important to us (also in our fork, but only for torch models): sometimes your accuracy is 90%, and only the confusion matrix will show it's just 100% biased towards a specific label (due to dataset bias).

Example: 77% accuracy in graph.. but meanwhile the confusion matrix tells me:
![image](https://cloud.githubusercontent.com/assets/7721540/15441660/6a2bc9c2-1edc-11e6-8ac1-8b0b0c89535e.png)

**Comment by lukeyeager** [comment]
> i will commit the Related Jobs next week

Cool, thanks!

> How about the Confusion Matrix?

Well we do have this: https://github.com/NVIDIA/DIGITS/pull/608.

But it looks like you're talking about something different - storing all the validation results and viewing *those* as a confusion matrix. Cool idea! I think that might be hard to do for Caffe...

**Comment by TimZaman** [comment]
Torch generally outputs the confusion matrix during validation, i set up a
simple regex that i catch and that's saved in the pickle file an updated
and sent with socketio with validation pass and voila. And i dont output
the confmat when there are more than 100 labels or it gets hefty. I didnt
dive deep in the caffe/torch implementation but i bet its similar-ish
except from the system calling and regexing.

**Comment by lukeyeager** [comment]
Whoops, forgot to close this when we merged #767. Thanks Tim. I like putting "Close #XXX" in the PR body so this gets done automatically:
https://github.com/blog/1506-closing-issues-via-pull-requests
