### ISSUE TITLE
Inference error testing a single image

### ISSUE THREAD

**Issue by pansk** [NVIDIA/DIGITS#676]
I'm trying to test a single image on a Torch network of with 3 layers (200K/200/200K, fully connected, and ReLu activations - similar to the autoencoder example).
Training works perfectly, but when try testing the network with a single image I receive this error:

InferenceError

'torch classify one task failed with error code 1'

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/digits/digits/model/images/generic/views.py", line 271, in generic_image_model_infer_one
    outputs, visualizations = job.train_task().infer_one(image, snapshot_epoch=epoch, layers=layers)
  File "/usr/share/digits/digits/model/tasks/torch_train.py", line 472, in infer_one
    layers=layers,
  File "/usr/share/digits/digits/model/tasks/torch_train.py", line 601, in classify_one
    raise digits.frameworks.errors.InferenceError(error_message)
InferenceError: 'torch classify one task failed with error code 1'

Restarting the server didn't help.

**Comment by gheinrich** [comment]
Hello Marco,
are you using DIGITS 3.0? Are you getting this error when using one of the
standard models as well or is this just related to this particular model?
You might get more information out of the DIGITS server log
(/var/log/digits). Otherwise can you post your network description so I can
try myself?
Thanks!

**Comment by pansk** [comment]
Hi Greg, 

It's 3.0, and it's a custom network, based on the auto encoder example, with just three layers but with bigger i/o (256x256x3).
I also tried commenting out {{blob}} visualization in infer_once.html but it didn't help (same error).

**Comment by pansk** [comment]
It's fixed on master, but now I can no longer run inference while training.
I'll close this and open a new ticket.
