### ISSUE TITLE
Doubts on how Caffe transform_param are applied in Digits

### ISSUE THREAD

**Issue by enoonIT** [NVIDIA/DIGITS#677]
[Latest version of Digits in use]
I'm using a default Alexnet where i changed the transform params for the data (train and test) layers, by adding:
```
transform_param {
    ...
   mean_value: 128
   scale:  0.5
}
```

Two questions:
1) the scale parameter seems to be ignored, at least during Classify One Image, where the image histogram in data activation is not changed by the scale factor. Is this normal?

2) If I click on "Subtract Mean" during the model creation, there seems no way to make the network use the mean values I manually defined in the network definition. My values are preserved only if I never click on the dropdown. If I click, there seems to be no way to tell digits to just use the network defined values. Am I missing something? Maybe an option like 'Use network defaults' would be nice.

**Comment by enoonIT** [comment]
Furthermore, even when the user defined mean value is accepted by the network (and correctly reported in train_val.prototxt) it is still ignored by the **classify one image** method.

**Comment by gheinrich** [comment]
Indeed data layers are ignored by Caffe during inference. If you wish to perform transformations on your input data you can use a `Power` layer, see this [example](https://github.com/NVIDIA/DIGITS/blob/master/digits/standard-networks/caffe/lenet.prototxt#L27-L36).

**Comment by enoonIT** [comment]
Hi, thanks for the answer.
I think this behavior is a bit confusing, as the mean values selected by drop-down at model creation is, on the contrary, applied to the inference.
So, If the mean is defined in the prototxt then it is ignored by the inference.
But if the mean is defined by the Digits gui, then it is used during inference.
Correct?

**Comment by gheinrich** [comment]
> So, If the mean is defined in the prototxt then it is ignored by the inference.

I don't think it's entirely correct. `Data` layers are used to load data from LMDB or LevelDB databases and they are not used during inference (when `input` fields are being used instead). If you were to perform your transformations in a `Power` layer then they would apply to all stages.

**Comment by enoonIT** [comment]
Ok, thanks for the clarification.
Still, If I select a specific Subtract Mean in the Data Transformations panel of the Digits GUI this will apply both to the Data layer AND to the inference.

Anyway, the safest bet seems to do all transforms in the power layer.

**Comment by gheinrich** [comment]
Thanks. It sounds like this answers your question so I'll close the issue. Feel free to post a question on https://groups.google.com/forum/#!forum/digits-users if you need any more information.
