### ISSUE TITLE
Data augmentation used by DIGITS 

### ISSUE THREAD

**Issue by vimalthilak** [NVIDIA/DIGITS#68]
Hi,

I was looking through the presentation on DIGITS where I noticed that DIGITS allows the user to add color distortion, add noise, rotate images etc. during database creation. Is this information correct or are these transformations applied on the fly within caffe? Can you point me to the piece of code where these transforms are applied either in DIGITS or caffe? Thanks

**Comment by lukeyeager** [comment]
Currently, the only thing DIGITS does is add noise to pad the image during cropping. The code for how I do that is [here](https://github.com/NVIDIA/DIGITS/blob/f2e2f3a9d600a20de46713910cfbd35375fdaff0/digits/utils/image.py#L53-L68), but you can see a live demo in DIGITS at `/datasets/images/classification/new` - click on "See Example."

See this pull request: BVLC/caffe#2252. Soon, caffe will be doing more data augmentation "on the fly." Once that PR goes in and NVIDIA/caffe gets updated to include the fix, you'll be able to do a lot more cool stuff.

**Comment by vimalthilak** [comment]
Luke,

meant to post my thanks earlier but it escaped my attention. I appreciate your quick response. I look forward to using DIGITS soon!
