### ISSUE TITLE
Subtract mean choices are switched on Digits 3.0

### ISSUE THREAD

**Issue by bnascimento** [NVIDIA/DIGITS#680]
Image choice - produces a train_val with the following data layer, notice the transformation_param:
layer {
  name: "mnist"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  **transform_param {
    mean_file: "/usr/share/digits/digits/jobs/20160412-190835-b3b8/mean.binaryproto"
  }**
  data_param {
    source: "/usr/share/digits/digits/jobs/20160412-190835-b3b8/train_db"
    batch_size: 64
    backend: LMDB
  }
}

Pixel choice gives you this data layer on train_val, once again notice the transformation param:
layer {
  name: "mnist"
  type: "Data"
  top: "data"
  top: "label"
  include {
    phase: TRAIN
  }
  **transform_param {
    mean_value: 109.589285714
    mean_value: 109.211734694
    mean_value: 117.243622449
  }**
  data_param {
    source: "/usr/share/digits/digits/jobs/20160412-190835-b3b8/train_db"
    batch_size: 64
    backend: LMDB
  }
}

This might lead to some confusion, Since pixel-wise subtraction should be pointing to complete mean.prototxt and image size subtraction should be pointing out to single value subtraction.

**Comment by gheinrich** [comment]
Can you provide a pointer to your definition of image and pixel subtraction?

What we're doing in DIGITS is explained [there](https://groups.google.com/d/msg/digits-users/FfeFp0MHQfQ/hUabaG1zCAAJ).

**Comment by bnascimento** [comment]
Ok got it, I had the impression pixel meant for pixel-wise mean values and image meant for image size mean values. 
Maybe should be considered to change the mean subtraction names for:

- None - None (is ok)
- Image - Mean image per channel
- Pixel - Single mean value per channel

To avoid more people being misled.
Thank you for your input.

**Comment by gheinrich** [comment]
Thanks for the suggestion. We will consider it. For now, I am closing this issue.
