### ISSUE TITLE
torch binary not found in PATH

### ISSUE THREAD

**Issue by Lucaszw** [NVIDIA/DIGITS#685]
When I try to generate a Dataset using the other option I receive the following error:

```
Default value for torch_root "<PATHS>" invalid:
torch binary not found in PATH
```

However my path does include torch:

```
echo $PATH 
/home/lucas/torch/install/bin:/usr/local/MATLA.......
```
```
echo $TORCH_ROOT 
/home/lucas/torch

```
Any idea what could be causing this issue?

**Comment by tehoro** [comment]
Just a guess - but you could try starting up the digits server with the --config option.   It asks for the path to torch if you do that, rather than using $PATH and other environment variables.

**Comment by Lucaszw** [comment]
Thanks was definitely helpful in speeding up debugging! It turns out that I needed to point to the **~/torch/install** folder (not ~/torch/install/bin which was in my PATH).
