### ISSUE TITLE
Cloning a vanilla Torch Model selects a vanilla Caffe Model but runs the Torch one.

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#688]
See title. You can replicate by:
Click new model. Select Torch->Alexnet.
Make the job.
Press clone.
You will see that the model selector is hovering now on Caffe->Alexnet in the Standard Network tab.
This last fact is just a UI remnant. If you would press 'Create Model' now, it will create a torch Alexnet model, although Caffe was selected!

If one were to switch to the torch alexnet standard network, and then back to the caffe alexnet standard network, one would get indeed get the Caffe one.
Seems like a straightforward UI bug.

**Comment by gheinrich** [comment]
Thanks @TimZaman I have pushed #690 which should fix this.
