### ISSUE TITLE
List format to test several images?

### ISSUE THREAD

**Issue by smewp** [NVIDIA/DIGITS#69]
I've trained a mnist_10K_model and would like to "test several images" by uploading an image list. However, after creating a val.txt file with list of filenames from the mnist_test file, I receive response "Unable to load any images from the file".  

Can you please clarify the list format requirement to get this "test several images" working?  Thank you!

**Comment by lukeyeager** [comment]
Yeah sorry about that. I really need to get around to fixing #40. My guess is that you are uploading a file that doesn't contain absolute paths to the images. Try with that and let me know if that doesn't fix it for you.

**Comment by lukeyeager** [comment]
After ac56560, you should be able to see more information about what's going wrong in the log, at least. Did you figure out your problem already?

**Comment by ljstrnadiii** [comment]
@lukeyeager 

I am trying to do inference on multiple images for a detectnet model. How should the file be formatted? is it space delimited file of full paths to the jpgs? comma separated?

It says use the val.txt file, but that is not a file used for a detectnet  model

**Comment by ljstrnadiii** [comment]
also, are there any rest examples to do inference on multiple files for detectnet?
