### ISSUE TITLE
constructing lmdb is takes really long time!

### ISSUE THREAD

**Issue by oanoelsis** [NVIDIA/DIGITS#700]
I use DIGITS with caffe. 

This is my first time with DIGITS and i just realize that constructing lmdb takes really long time than caffe's tool.

you know caffe has "convert_imageset.cpp" that construct lmdb from jpg files list. This is c++ implementation and DIGITS lmdb constructor is python implementation. 

And i have a question about why DIGITS not just use caffe's c++ lmdb constructing tool?

**Comment by gheinrich** [comment]
For the record, how much slower is the DIGITS version compared to Caffe version? (using same encoding, image size, ...).

**Comment by oanoelsis** [comment]
For me DIGITS version takes twice more than Caffe version. (I using smae encoding, image size, and same files) I checked that DIGITS version use multi-thread, and they were never fully utilized and many I/O occured. And in my knowledge that is pure python implementation. In my perspective I can't understand why use python implementation even though there already exist caffe's c++ implementation about this.

**Comment by gheinrich** [comment]
Which version of DIGITS are you using? CPU utilization was improved with https://github.com/NVIDIA/DIGITS/pull/491. Do you have this patch?

DIGITS implementation of LMDB creation is not pure Python. The heavy work is done in PIL and LMDB C libraries.

**Comment by gheinrich** [comment]
@oanoelsis were you able to try this on [DIGITS 3.3](https://github.com/NVIDIA/DIGITS/releases/tag/v3.3.0)?

**Comment by gheinrich** [comment]
No response => assumed fixed with #491 and closing
