### ISSUE TITLE
Sorting by loss

### ISSUE THREAD

**Issue by pansk** [NVIDIA/DIGITS#705]
In the model details view, sorting ascending by loss, values appear in this order:

1174.55688786
1307.10130986
2128.65663939
2232.1617981
289.524761538
297.385676324
3.12282231864E+15
310.550715772
311.165405853
312.779110293

Apparently, the sorting is happening by the string representation of the loss value.

Marco

**Comment by lukeyeager** [comment]
Thanks for the bug report. We're hoping to phase out the "Model Details" page in favor of angular.js tables in the style of https://github.com/NVIDIA/DIGITS/pull/728. We may either replace that page with a new angularized one, or we may merge some of the features from that page into the home page.

**Comment by pansk** [comment]
Apparently the "Model Details" page is gone in the last git version.

Anyway, I was just testing the new homepage and it's lovely.

If you're going to make the new "model details" page similar to that, or introduce those functions in the homepage, it's perfect! 

Can I add an item to a hypotetical (long term) wish-list? Having persistent customized reports: that could really be a useful feature.

**Comment by lukeyeager** [comment]
> Can I add an item to a hypotetical (long term) wish-list? Having persistent customized reports: that could really be a useful feature.

Sure, make a new issue and I'll mark it as an enhancement! Maybe we could just save cookies in the browser as an easy solution?

**Comment by pansk** [comment]
In the short term, sure.
In the mid term, we're about to start a project where we'll be sharing a DIGITS instance for at least part of our job. I'll be able to collect some experience data and come back to you if I realize that persistent shared reports are needed.

**Comment by jmancewicz** [comment]
I'm working on adding the output fields that were available on the models page to the front page.  These fields will be accessible from a settings dropdown. ![screen shot 2016-05-23 at 11 42 25 am](https://cloud.githubusercontent.com/assets/13259615/15480634/769f3328-20db-11e6-8bcc-229c3ce1aa6b.png) and will be persistent in each browser.

![screen shot 2016-05-23 at 11 41 00 am](https://cloud.githubusercontent.com/assets/13259615/15480620/672a8226-20db-11e6-9bdc-b23156f568ed.png)

**Comment by jmancewicz** [comment]
In the table, integers are sorts as integers, strings as strings and floats as floats.

**Comment by pansk** [comment]
I verified the sorting, sorting works correctly in both tabs, for every currently available column in the tables. I leave the ticket open for the column selector that will act as replacement for the "Model Detail" page. Thank you for your great UI job, Joe!

**Comment by lukeyeager** [comment]
Closed by https://github.com/NVIDIA/DIGITS/pull/790.
