### ISSUE TITLE
Dataset information not shown when cloning a model

### ISSUE THREAD

**Issue by flx42** [NVIDIA/DIGITS#711]
When creating a new model and selecting a dataset:
![digits2](https://cloud.githubusercontent.com/assets/3645581/14861912/13cdf5c6-0c64-11e6-8117-6d9bf9341c5a.png)

When cloning a model:
![digits](https://cloud.githubusercontent.com/assets/3645581/14861874/d8c55492-0c63-11e6-9c14-4b956db1c734.png)
If you only have one dataset, I don't see a way of having the information displayed.
If you have multiple datasets in the list, click on any other dataset, then back on the one you want.

**Comment by TimZaman** [comment]
While we're at this, maybe tackle some of the other minor cloning issues, of which a few have been fixed last week. 
**Problem: different label upon cloning**
Steps:
(1) Make a model job, name it "test"
(2) Change the label name, name it "test renamed"
(3) Click clone
(4) The actual cloned name will be "test", not "test renamed".

**Comment by flx42** [comment]
You mean #710? :)

**Comment by gheinrich** [comment]
Thanks for the bug report @flx42 

This should be fixed in #713
