### ISSUE TITLE
Bugs with parameter sweep

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#717]
*See https://github.com/NVIDIA/DIGITS/pull/708*

Don't have time to track them down and fix them right now:

1. If you try to create a model without specifying a batch size, then you get an error:

    ![sweep-bug-error1](https://cloud.githubusercontent.com/assets/687269/14905508/14fbd528-0d66-11e6-839a-0e3df8e15c93.jpg)

2. On the page with the error, the fields are filled in with weird values, causing problems later:

    ![sweep-bug-error2](https://cloud.githubusercontent.com/assets/687269/14905515/24da843a-0d66-11e6-9bfa-1d43299440e2.jpg)

**Comment by jmancewicz** [comment]
I had changed the data format in the form, but didn't update the MultiOptional validator.

**Comment by TimZaman** [comment]
Without reading your code, @jmancewicz for the sweep (COOL, excited to try), i decided to just see if the (?) icon would explain. So this is what happened..
**Making model**
![screenshot 2016-05-02 15 14 40](https://cloud.githubusercontent.com/assets/7721540/14955217/bba1708a-1078-11e6-8794-a6c1b13b8b49.png)
**Pressing create yields..**
![screenshot 2016-05-02 15 14 50](https://cloud.githubusercontent.com/assets/7721540/14955231/cc941514-1078-11e6-8996-a22a857ce0b3.png)
![screenshot 2016-05-02 15 14 53](https://cloud.githubusercontent.com/assets/7721540/14955232/cc969762-1078-11e6-865e-53ff4c09cfd2.png)

**Comment by TimZaman** [comment]
Also, if you don't set a batch size this will give an error. I always set it in the model so this requires a very hot albeit easy fix :).
Let me tickle a bit; strange how this ends up in master given a great pull request like this one from @groar don't make it through because of fairly minor comments;
https://github.com/NVIDIA/DIGITS/pull/330

**Comment by lukeyeager** [comment]
> strange how this ends up in master given a great pull request like this one from @groar don't make it through because of fairly minor comments: #330

For one thing, that PR had a TODO list that wasn't touched for 4 months.
