### ISSUE TITLE
Load shooting upto 514 on aws g2.xlarge

### ISSUE THREAD

**Issue by aichemzee** [NVIDIA/DIGITS#724]
I installed DIGITS on aws g2.xlarge from source. I had everything fine, trained a few models. Upto this point in time, digits was working great, I could upload image datasets, train models etc. Then I made an ami (made this public ami-c77680a7) of this instance. After a few days when I relaunched the server, something was broken. The digits (web) server was running fine, but the average load on my instance shot up to 514. I also tried creating a new dataset, but the process stays at 0% progress for hours. Same thing happens when I try to run a model. An guesses on what could cause this? I had a look at digits.log, but everything seems normal there.

I had the following processes running from digits:
![screen shot 2016-05-02 at 3 48 49 pm](https://cloud.githubusercontent.com/assets/4052278/14955345/f608536a-1096-11e6-9a79-e10697cf36cb.png)

Also sorting `top` showed this:
![screen shot 2016-05-02 at 3 49 25 pm](https://cloud.githubusercontent.com/assets/4052278/14955409/51895fcc-1097-11e6-8995-32491ab33d17.png)

The first two processes there seem to be taking an unusual amount of virtual space. How should I proceed in debugging this issue?

**Comment by TimZaman** [comment]
Isn't that virtual space just chached memory? It says 0.9% and 0.7%, does not seem like much.

**Comment by gheinrich** [comment]
@aichemzee you hinted on https://github.com/zhangxiangxiao/Crepe/issues/11#issuecomment-216240131 that you had solved this problem. Can we close this bug then? Thanks!

**Comment by aichemzee** [comment]
Closed. Thanks
