### ISSUE TITLE
  Package cuda-repo-ubuntu1404-7-0-local is not installed.

### ISSUE THREAD

**Issue by QuentinYu** [NVIDIA/DIGITS#725]
> ylk@ylk-B85-D3V-A:~/nv$ sudo dpkg -i nvidia-machine-learning-repo_4.0-2_amd64.deb 
> (Reading database ... 263699 files and directories currently installed.)
> Preparing to unpack nvidia-machine-learning-repo_4.0-2_amd64.deb ...
> Unpacking nvidia-machine-learning-repo (4.0-2) over (4.0-2) ...
> dpkg: dependency problems prevent configuration of nvidia-machine-learning-repo:
>  nvidia-machine-learning-repo depends on cuda-repo-ubuntu1404 | cuda-repo-ubuntu1404-7-0-local; however:
>   Package cuda-repo-ubuntu1404 is not installed.
>   Package cuda-repo-ubuntu1404-7-0-local is not installed.
> 
> 
> dpkg: error processing package nvidia-machine-learning-repo (--install):
>  dependency problems - leaving unconfigured
>  Errors were encountered while processing:
>   nvidia-machine-learning-repo

I did install the 7.5version and caffe had run on gpu。

**Comment by lukeyeager** [comment]
How did you install the toolkit? Did you use a runfile? You need to choose one of the debian installers in order to install DIGITS with deb packages.

**Comment by QuentinYu** [comment]
I am not sure why, but when I copy 
CUDA_REPO_PKG=cuda-repo-ubuntu1404_7.5-18_amd64.deb &&

>    wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/$CUDA_REPO_PKG &&
>     sudo dpkg -i $CUDA_REPO_PKG
> 
> ML_REPO_PKG=nvidia-machine-learning-repo_4.0-2_amd64.deb &&
>     wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/$ML_REPO_PKG &&
>     sudo dpkg -i $ML_REPO_PKG
as a .sh file .
and bash it . It seems working.
