### ISSUE TITLE
Torch error when testing a model trained with multiple GPUs

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#736]
```
digits.inference.errors.InferenceError:
  torch classify one task failed with error message -
  ...6-05-12/install/share/lua/5.1/cunn/DataParallelTable.lua:374:
  Model was serialized on 2 nGPUs, but you are running on 1 please set 
  DataParallelTable.deserializeNGPUs to ignore  serialized tower-GPU assignments
```

@gheinrich Would https://github.com/NVIDIA/DIGITS/pull/732 fix this?

**Comment by gheinrich** [comment]
Thanks for the bug report, I have updated the commit on #734 to fix this (with the new programming model we also need to set the number of GPUs when we deserialize a model when doing inference or fine-tuning).

**Comment by lukeyeager** [comment]
^ I think you meant #732?

**Comment by gheinrich** [comment]
> I think you meant #732?

Whoops. Indeed!
