### ISSUE TITLE
Model Creation UI Discussion & Tweaks

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#738]
Hi everyone. I have been working with Digits so much the past couple of months, I decided to take a step back and see how we use it, and was wondering how others actually use it.
First off, the Standard Networks are great to have a initial model up, but then we will always customize the model, and tweak the parameters a bit. This means that our focus here lies on the model.
Currently, the model with us is just messy we use it: we copy it to a (syntax highlighting) text editor, then change it, and paste it back in the textarea.
At first i changed the textarea to monospace. Then the box for the network was still very small to work in. I decided to make it bigger, and while at it, i found the 'Ace' editor with BSD licence: [https://ace.c9.io/ ](https://ace.c9.io/ )

**Is it allowed for you guys (NVIDIA Digits) to incorporate Ace?** It has a very small footprint, and has highlighing for python (caffe models) as well as torch (lua). And incorporating is around 20 LOC.

To answer my own question 'how do i use digits' i show here how i changed up the UI:

![ui_ace_caffe](https://cloud.githubusercontent.com/assets/7721540/15267339/86b28fc6-19bf-11e6-881b-fcd1f615af32.png)
![ui_with_ace](https://cloud.githubusercontent.com/assets/7721540/15267340/86b46e4a-19bf-11e6-9cdf-3bde8a3756cd.png)

**Comment by lukeyeager** [comment]
Neat! Ace looks like a pretty cool product - and it even has protobuf support? As you pointed out, there shouldn't be a problem integrating a BSD-licensed tool.

Since you've already done the integration work, do you want to make a pull request? I like the rearrangement of the page layout too. If you want to include that, keep it in a separate commit so it's easier to review.

**Comment by lukeyeager** [comment]
Looks like this is what @GitHub uses, too:
https://github.com/showcases/projects-that-power-github

**Comment by TimZaman** [comment]
Sure Luke i will _try_ to make a neat PR _tomorrow_.
