### ISSUE TITLE
ERROR: error code -8 when using Generic Image Model

### ISSUE THREAD

**Issue by Noiredd** [NVIDIA/DIGITS#740]
I am trying to perform image classification on pairs of images (two images for each test object) using a siamese kind of network. General idea was to pack RGB images into a DB of 6-channel entities, Splice them right after loading and have each column work on its own image. I wrote a custom LMDB-creation code and tried to load the database using Other dataset (Generic Image Dataset), but my model wouldn't learn at all. I thought the problem was with my database so I removed all 6-channel code and created a standard 3-channel DB to debug and it keeps giving me the -8 error. Digging deeper into the issue, I created a Generic dataset from one of my existing and working datasets (just passed training and validation DBs) and tried to run AlexNet on it (pasting its code straight from Image Classification dialog into Generic Image Model) only to get a -8 error again.
Here's what caffe_output.log keeps telling me about the problem:
```
I0516 17:04:11.596333  7650 net.cpp:109] Creating Layer fc8
I0516 17:04:11.596338  7650 net.cpp:457] fc8 <- fc7
I0516 17:04:11.596350  7650 net.cpp:414] fc8 -> fc8
*** Aborted at 1463411051 (unix time) try "date -d @1463411051" if you are using GNU date ***
PC: @     0x7fa9f25d70a0 (unknown)
*** SIGFPE (@0x7fa9f25d70a0) received by PID 7650 (TID 0x7fa9f3014a40) from PID 18446744073480794272; stack trace: ***
@     0x7fa9f0c79d40 (unknown)
@     0x7fa9f25d70a0 (unknown)
@     0x7fa9f25d73dc (unknown)
@     0x7fa9f2566bc7 (unknown)
@     0x7fa9f25f09c6 (unknown)
@     0x7fa9f25f1a95 (unknown)
@     0x7fa9f25c5d5a (unknown)
@     0x7fa9f25c6e9c (unknown)
@     0x7fa9f25c71a9 (unknown)
@           0x412675 (unknown)
@           0x40b4b6 (unknown)
@           0x4092b8 (unknown)
@     0x7fa9f0c64ec5 (unknown)
@           0x409a9b (unknown)
@                0x0 (unknown)
```
Am I doing something wrong, or is there indeed something wrong with DIGITS? I'll be happy to provide more info on the issue.

**Comment by lukeyeager** [comment]
A `SIGFPE` usually means that you're using the wrong input size, causing one of the internal layers to divide by zero.

**Comment by Noiredd** [comment]
I took a close look at the Siamese network from DIGITS examples and compared its prototxt to standard AlexNet. Turns out generic models **must** have `num_output` specified on the last layer, contrary to image classification models where DIGITS adds this on its own. I added this line to my network and learning started. (Didn't go well, but I think it's a different thing than this very issue.)
So I'm not sure if I missed something in the docs or maybe it simply isn't said anywhere, but the DIGITS error message wasn't very helpful here.

**Comment by lukeyeager** [comment]
Since https://github.com/NVIDIA/DIGITS/pull/628, DIGITS is supposed to throw an error in this scenario:

https://github.com/NVIDIA/DIGITS/blob/v3.3.0/digits/model/tasks/caffe_train.py#L1461-L1464

What version of DIGITS are you using?

**Comment by Noiredd** [comment]
The one I got from developer.nvidia.com/digits some 3 weeks ago, so 3.0.0. Wasn't even aware of a newer release... Sorry for the trouble.

**Comment by lukeyeager** [comment]
No problem.
