### ISSUE TITLE
Issues with home page angular tables

### ISSUE THREAD

**Issue by lukeyeager** [NVIDIA/DIGITS#741]
Following up on https://github.com/NVIDIA/DIGITS/pull/728, here are some bug reports / feature requests:

**Comment by lukeyeager** [comment]
BUG: When you click+drag over several entries, you can select them all at once. But if you drag too far, and your "mouse-up" action happens outside of the table, then Angular doesn't catch it. Then it stays stuck in "selection" mode.

**Comment by lukeyeager** [comment]
REQUEST: When you select a dataset (or several), can you filter to only show the models that were trained on that dataset[s]?

**Comment by lukeyeager** [comment]
REQUEST: When a job finishes, move it from the top section down into the appropriate table.

**Comment by lukeyeager** [comment]
REQUEST: update count of jobs based on filters (next to "Datasets" or "Models").

**Comment by TimZaman** [comment]
Oh man we really cannot pull this in in the current state.
There are only around 30 characters available in which one can describe his model, right? How does one distinguish between jobs that have run. At least the datasets's name should be in there, probably some more stuff regarding the settings. This is how it then looks in practice. Indeed i could shorten the dataset name, but then again, **there is too little space for naming and annotating**. My suggestion is to do away with the two column approach; maybe use tabs?

![image](https://cloud.githubusercontent.com/assets/7721540/15316641/2750b47a-1c1e-11e6-8488-590d12867dd9.png)

**Comment by enoonIT** [comment]
I agree with @TimZaman , in this current state it's impossible to distinguish between jobs.
At the very least I'd make the column width resizable on the fly by mouse dragging

**Comment by TimZaman** [comment]
Suggestion with using tabs:
![image](https://cloud.githubusercontent.com/assets/7721540/15323739/b46003d2-1c43-11e6-9d0a-9f116d4e53fa.png)

and 

![image](https://cloud.githubusercontent.com/assets/7721540/15323743/ba018748-1c43-11e6-9911-d8cda0cdd3eb.png)

In the wide way there is a lot of room to add more lovely column-metrics

**Comment by jmancewicz** [comment]
The side by side tables are very tight especially with the width restrictions from bootstrap. The non-name fields are about as small as they can be while still being readable.

I had initially had a tabbed view, but moved to the side by side to attempt to keep close to the origianal look. I can put out a tabbed version to see how that works.

**Comment by lukeyeager** [comment]
BTW, the tooltips added with https://github.com/NVIDIA/DIGITS/pull/748 help with these issues:

> There are only around 30 characters available in which one can describe his model, right? How does one distinguish between jobs that have run.

> in this current state it's impossible to distinguish between jobs

**Comment by TimZaman** [comment]
Definately the new homepage is an amazing improvement, it looks a lot cleaner and more professional. I think the tab view i just shown is not the ultimate solution, but it is a fair one. I tried putting the datasets below the models, but that made less sense and the scroll longer.
But I do feel like we should try to use more of the width, so i can include more metrics and really compare different outcomes, especially given the latest improvements in the sweep that was implemented. So lets say i do a sweep of 10 different settings; i will have no way at all of comparing them in one view. If we would have more space in the job-row table we could do that.

**Comment by enoonIT** [comment]
I'd like to suggest a couple of things:
1) the new tabbed view is nice, but I think people tend create to new models (and check them) more often than datasets - so I'd make the model tab the default one.
2) Model names for running networks are still hidden when too long. 
![screenshot from 2016-05-20 18 22 28](https://cloud.githubusercontent.com/assets/7884236/15434588/d8f86e34-1eb7-11e6-92d3-6a062f897f78.png) It seems some of the horizontal space is wasted (after Status and Progress). In the meantime it would be nice to have tooltips, but they don't seem to work on the running jobs.

**Comment by lukeyeager** [comment]
Thanks for all the fixes and updates @jmancewicz! Closing.
