### ISSUE TITLE
 Multi scale, multi crop and multi GPU training

### ISSUE THREAD

**Issue by KangKyungSoo** [NVIDIA/DIGITS#75]
Multi scale, multi crop and multi GPU training
will be needed, if you want reproducible results

Regards,

**Comment by lukeyeager** [comment]
Hi @KangKyungSoo, thanks for the feedback.

I'm not sure I understand you. When I mentioned reproducible results, I meant that numbers between two back-to-back training sessions should be equivalent. How is that related to the features you mentioned?

**Comment by KangKyungSoo** [comment]
I just mentioned reliable, steady test results.

**Comment by lukeyeager** [comment]
I think you're referring to the quality of the network. I was referring to mathematical equivalence between two training runs, regardless of the quality of the network.
