### ISSUE TITLE
Testing data db

### ISSUE THREAD

**Issue by tonytan4ever** [NVIDIA/DIGITS#755]
According to this line:
https://github.com/NVIDIA/DIGITS/blob/master/digits/dataset/images/classification/views.py#L384

It should be possible to add testing database in the gallery of image too. Is it just adding it to the GET parameter ?

**Comment by gheinrich** [comment]
Hello @tonytan4ever, exploring the test DB is supported if you created a test DB (by e.g. setting the `% for testing` field to something greater than 0):
![mnist-test-db-button](https://cloud.githubusercontent.com/assets/3889770/15365255/dac8bbf4-1d1f-11e6-923f-c02f78e52312.png)

![mnist-test-db](https://cloud.githubusercontent.com/assets/3889770/15365259/ddc66b30-1d1f-11e6-8601-9be49eb60395.png)

**Comment by tonytan4ever** [comment]
Thanks a lot. What is the url you use to generate the graph ? Can you show it to me ?

**Comment by gheinrich** [comment]
The graph is shown on the dataset page.

**Comment by gheinrich** [comment]
It doesn't seem like there is an issue there. Closing. Thanks for the feedback!
