### ISSUE TITLE
Torch HDF5 module should be lazily loaded

### ISSUE THREAD

**Issue by flx42** [NVIDIA/DIGITS#757]
I had an issue where my Torch setup had the hdf5 module installed but my environment was actually missing a few dependencies (namely `gcc` and `libhdf5-dev`). See here:
https://github.com/NVIDIA/nvidia-docker/commit/8e6ec6430ae51dea719a2776159d64f88e758619
It caused all Torch training jobs to fail immediately, even when none of my datasets were actually using HDF5 (they all used the default lmdb).

Can we load the HDF5 module only if the dataset is HDF5? Going forward, this feature will be useful when adding additional data loaders to DIGITS.

Thanks,

**Comment by gheinrich** [comment]
Thanks for the report @flx42. It will be difficult to make the HDF5 module for Torch optional as we're using HDF5 to pass data between processes in DIGITS. The network visualisations, for example, are passed between a Lua process and the inference process using HDF5.

So even if you only use LMDB datasets you still need support for HDF5 in both Python and Lua.

Admittedly, it is unfortunate that the HDF5 module requires GCC (just to pre-process the header file).

**Comment by lukeyeager** [comment]
Oh right, I keep forgetting that we require HDF5 for other things besides datasets.

Closing as will-not-fix.
