### ISSUE TITLE
Cannot start server with ./digits-devserver

### ISSUE THREAD

**Issue by joyofdata** [NVIDIA/DIGITS#77]
Hi!

(Working on Ubuntu 14.04 AMI on EC2 instance g2.2xlarge)

So I installed CUDA 7 and c/p-ed the cuDNN files there and also of course installed caffe as described - everything seems to be fine.

Now I installed DIGITS and I assume that ./digits-devserver is supposed to start a server listening to port 5000.

But accessing the service via my browser by http://[IP]:5000 is not working - seems like there is nothing listening.

Also ```sudo netstat -tapen``` does not list any process that would be listening on 5000.

Furthermore - running ./digits-devserver won't ask me or show me anything - [quote](https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md):

> NOTE: The first time DIGITS is run, you will be asked for the location of some directories. It should look something like the following: ... 

All I see is:

ubuntu@ip-172-31-15-133:~/digits$ ./digits-devserver
 
```
 ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/

Welcome to the DIGITS config module.

Where is caffe installed?
        (enter "SYS" if installed system-wide)
        [default is /home/ubuntu/caffe]
(q to quit) >>>   
```

Now what is this config module anyway? I can't find any documentation on how to interact with it. Is it of any use for troubleshooting this issue?

*Any ideas what to do or how to figure out what's the problem?*

Kind Regards

Raffael

**Comment by lukeyeager** [comment]
I assume you figured it out since you closed the issue. Any suggestions on improvements to the CLI?

**Comment by joyofdata** [comment]
Somehow I didn't get that I am supposed to respond to the question ... I interpreted the instructions as a statement. But in hindsight it seems pretty obvious.
