### ISSUE TITLE
Ubuntu deb installer has file read issues on mounted drives

### ISSUE THREAD

**Issue by mikepcw** [NVIDIA/DIGITS#778]
Now testing the deb installer route.
On a clean 14.04 image, I followed the `UbuntuInstall.md` directions exactly.

Problem occurs when I insert a secondary SATA drive containing training data. It is not accessible to the DIGITS webserver.
Two symptoms are when trying to create New Image Classification Dataset are:

1. Cannot autocomplete path beyond /media/username/...
2. Manually inputting the full path results in `Folder does not exist` error.

I've tracked this down to `parse_folder.py:320` that spawns that error.
Testing the conditional `if os.path.exists() and os.path.isdir()` in a regular python script as the user returns `TRUE`.

How should I mount external drives?

**Comment by mikepcw** [comment]
The above symptoms do not occur when I build from source.

**Comment by gheinrich** [comment]
Hi @mikepcw when using the .deb installer, DIGITS runs as a service under user `www-data` so you need to make sure your data (i.e. the images as well as all parent folders) are accessible by this user.

**Comment by mikepcw** [comment]
It does not help even when I recursively `chmod -R 777` everything from the mount point of that drive.

(for disclosure, I work for NVIDIA in Australia)
I have an email thread going with JulieB and she seems to think might have to do with the way it's mounted?
I'm not adept enough with Linux to know what the default mount settings are.
I simply plug in the external drive and it pops up in Linux, mounted under /media... can you try similar and see if it happens too?

I would think that having multiple external SATA drives is not that uncommon, particularly with large datasets.

**Comment by lukeyeager** [comment]
`www-data` needs to be able to read and execute every directory from `/` all the way to your data directory. So maybe check that `www-data` can read `/media`?
```sh
chmod a+rx /media
```

**Comment by mikepcw** [comment]
I will try that.
What about an NTFS or FAT32 formatted drive that comes from a Windows machine?

**Comment by gheinrich** [comment]
Can you review this post and see if this helps?
https://groups.google.com/d/msg/digits-users/wLQrOToE7cw/OgwnzhZwBAAJ

**Comment by mikepcw** [comment]
Does not work for some strange reason. Then it works if I copy to local drive. See screenshots.
The only difference is images are located on SATA drive (1st attempt) vs local disk (2nd attempt).
Still think it's something to do with disk mount settings.

"train_test" is just a selection of two directories extracted from the imagenet set

![screenshot from 2016-06-15 00-11-35](https://cloud.githubusercontent.com/assets/4396932/16046207/f44df04c-328e-11e6-91a2-b617ac0866a4.png)

![screenshot from 2016-06-15 00-18-09](https://cloud.githubusercontent.com/assets/4396932/16046255/2131a8a6-328f-11e6-8676-d952406b7e85.png)

**Comment by shohan6** [comment]
@mikepcw  I faced the same problem. Digits shows "Folder does not exits" when I gave a link from external drive. How to solve this problem. My local drive is only 100GB. If I cannot link the DATASET from external drive, I would not be able to work.

**Comment by mikepcw** [comment]
I fixed my NTFS drive by editing the default mount options in the Disks app.
Turn off Automatic Mount Options and add the following to the list of comma separated parameters
uid=1000,gid=1000,umask=022

022 gives wrx permissions to owner and rx permissions to all, for all files and dirs.
This fixed my issue above.

**Comment by lukeyeager** [comment]
Great news, thanks for the update!

**Comment by KittyLiou** [comment]
Thanks a lot. I tried your solution. It works!
