### ISSUE TITLE
Training gets randomly stuck without error messages

### ISSUE THREAD

**Issue by enoonIT** [NVIDIA/DIGITS#779]
I'm using the latest Digits ( 614809d481cf16c2134591f2efdfc190177899f5 ) but I've had this issue since I started using digits (a couple of months).
I'm using Caffe and the machine (Ubuntu 14.04, CUDA 7.5 and CudNN4) has two Titan X.

What happens is that sometimes the training of a network simply stops, without any kind of error message. Nominally the training is still going on (the job is Running) but the digits console doesn't update the training status for that particular job (the other job continues without issues) nor is there any update in the digits webpage. 
If I stop the job, things usually get messy and I have to reboot to make digits work again.

**Comment by lukeyeager** [comment]
That doesn't sound good. Is there anything in the raw Caffe output "caffe_output.log"?

**Comment by gheinrich** [comment]
Might be worth checking the DIGITS log too in case DIGITS is restarted throughout the training job.

Just checking: are you running `digits-devserver -d` and making changes to the code? I often get caught with this: DIGITS restarts as soon as I change the code and loses track of running jobs.

**Comment by enoonIT** [comment]
caffe ouput ends with:

> I0524 15:50:16.849248 22230 solver.cpp:243] Iteration 109000, loss = 0.331265
> I0524 15:50:16.849289 22230 solver.cpp:259]     Train net output #0: loss = 0.331265 (* 1 = 0.331265 loss)
> I0524 15:50:16.849299 22230 solver.cpp:590] Iteration 109000, lr = 0.00128056

Digits didn't stop, actually it successfully completed all remaining jobs using the other GPU.
Digits log don't add anything useful, it simply stopped reporting advancement on that job.
It is as one of the jobs simply froze and was stuck in a limbo - not aborting but not running also.

I must note that every now and then I run some feature extractions using the gpu on a python script (with Caffe) - I use a small batch size to make sure to not run out of memory. Could this be related?

**Comment by gheinrich** [comment]
This is reminiscent of https://github.com/NVIDIA/DIGITS/issues/664. Sharing a GPU between two Caffe processes yields unpredictable issues. That is the reason why we changed inference jobs in DIGITS with #573 to explicitly reserve GPUs.

**Comment by enoonIT** [comment]
If it might be of interest, I also work on another workstation, same setup (same hardware, same software) but only 1 gpu: there I never have this issue.

**Comment by enoonIT** [comment]
It happened again and this time I'm wasn't running anything else at the same time. Weird thing is that GPU utilizations still went up and down as if the training was continuing.

**Comment by lukeyeager** [comment]
Dumb question: have you tried refreshing the page? Just making sure this is more serious than a simple dropped SocketIO connection.

**Comment by enoonIT** [comment]
Yep, I also checked the digits logs and there I confirmed there weren't any new updates on the job.

**Comment by lukeyeager** [comment]
> If I stop the job, things usually get messy and I have to reboot to make digits work again.

Can you elaborate on what this means? It's hard to help without any real data or error messages. I can run this by the @NVIDIA/caffe team, but I don't really have a list of steps for them to reproduce the error.

**Comment by enoonIT** [comment]
I know this sounds vague, but it's very hard to pinpoint.
What happens is that If I stop digits, I'll will stop very slowly and If I try to relaunch it without rebooting it will usually hang.
Are there some more in depth logs I might enable?

**Comment by lukeyeager** [comment]
> Are there some more in depth logs I might enable?

Not really. I guess you could compile Caffe in debug mode and see if there's any more info:

    cmake .. -DCMAKE_BUILD_TYPE=Debug

**Comment by lukeyeager** [comment]
I don't think this is a DIGITS bug. If you have more trouble, please reach out to the NVIDIA/caffe team.
