### ISSUE TITLE
Editor doesn't show up in Edge and Chrome (Windows)

### ISSUE THREAD

**Issue by pansk** [NVIDIA/DIGITS#784]
I think this might be related to the introduction of ACE (#738)

I'm cloning the same Job using DIGITS from different browsers

Edge:

![image](https://cloud.githubusercontent.com/assets/1263535/15541269/08d4f9e2-228c-11e6-8d69-48106ac8c686.png)

Chrome:

![image](https://cloud.githubusercontent.com/assets/1263535/15541282/1f577e60-228c-11e6-8eb5-616ccee92930.png)

FireFox:

![image](https://cloud.githubusercontent.com/assets/1263535/15541302/338b32e6-228c-11e6-8df3-d764b471d5fd.png)

Internet Explorer:
![image](https://cloud.githubusercontent.com/assets/1263535/15541430/b8f92d98-228c-11e6-8b71-e954c4f520d7.png)

**Comment by lukeyeager** [comment]
Working for me on Win7 with Chrome 50

**Comment by pansk** [comment]
I had "Version 50.0.2661.102 m (64-bit)" running on Windows 10.

I just updated to "Version 51.0.2704.63 m (64-bit)", still no editor.

Updated to last version (your last three commits): still no editor.

If I can make some more tests in order to help you identify the problem, please let me know.

**Comment by IsaacYangSLA** [comment]
@pansk Can you let us know if that happened only on Torch editor?  I tried Clone Job, and selected LeNet, Customize on Edge / Windows 10 64bit.  Here is the screenshot.  You can see the editor was displayed correctly (not blank).
![image](https://cloud.githubusercontent.com/assets/5758988/15596707/71b2bf1a-237e-11e6-84ae-bd3df7bc94f0.png)

**Comment by gheinrich** [comment]
I had that problem once in Firefox too but when I hit <Shift>-<Ctrl>-R to force-reload everything it started working. I believe I had older .js scripts in my browser cache.

**Comment by pansk** [comment]
Yep, it was that.
False alarm.

**Comment by IsaacYangSLA** [comment]
@gheinrich , thanks for the clarification.  @pansk , can you also let us know if the other [issue](https://github.com/NVIDIA/DIGITS/issues/783) can be resolved with the similar approach?  Thanks.
