### ISSUE TITLE
ERROR: 'NoneType' object has no attribute 'db_name'

### ISSUE THREAD

**Issue by joyofdata** [NVIDIA/DIGITS#80]
(*UPDATED* traceback for most recent commits)

Hello!

I managed to load a data set of 1000 pictures (named it "test_data") and now attempted to train a model ("test_model") on it.

For the model I select my data set of 19 colored 256x256-sized pictures. I select "AlexNet" and keep the defaults.

After a second I get the following error message:

```
ERROR: 'NoneType' object has no attribute 'db_name'

Traceback (most recent call last):
  File "/home/ubuntu/digits/digits/scheduler.py", line 394, in task_thread
    task.run(**options)
  File "/home/ubuntu/digits/digits/task.py", line 161, in run
    self.before_run()
  File "/home/ubuntu/digits/digits/model/tasks/caffe_train.py", line 98, in before_run
    self.save_prototxt_files()
  File "/home/ubuntu/digits/digits/model/tasks/caffe_train.py", line 224, in save_prototxt_files
    val_data_layer.data_param.source = self.dataset.path(self.dataset.val_db_task().db_name)
AttributeError: 'NoneType' object has no attribute 'db_name'
```

Any ideas what might be the issue here?

Kind Regards 

Raffael

PS: The following two screenshots show the chosen settings and the error message:

![settings](http://i.imgur.com/shTxpwJ.png)

![error](http://i.imgur.com/v8Y5Uvq.png)

**Comment by joyofdata** [comment]
Ahaaaa .... apparently a validation set isn't optional ...

```
# causes trouble in caffe_train.py:224 and ...
val_data_layer.data_param.source = self.dataset.path(self.dataset.val_db_task().db_name)

# ... calls this function which returns None if no validation set is provided
def val_db_task(self):
        """
        Return the task that creates the validation set
        """
        for t in self.tasks:
            if isinstance(t, tasks.CreateDbTask) and 'val' in t.name().lower():
                return t
        return None
```

**Comment by lukeyeager** [comment]
> apparently a validation set isn't optional

No, it should be. If you're getting this error then that's a bug. I'm looking into it now...
