### ISSUE TITLE
ERROR: list index out of range

### ISSUE THREAD

**Issue by joyofdata** [NVIDIA/DIGITS#81]
(**UPDATED** for most recent version involving [commits to .../create_db.py](https://github.com/NVIDIA/DIGITS/commit/c0833a2896bf38307838280b7b018f78e91eb4c0) + I simplified the initial setup)

Hello!

I try to create a data set from about 100 JPEG files (colored. And I get this error message:

```
ERROR: list index out of range

Traceback (most recent call last):
  File "/home/ubuntu/digits/digits/scheduler.py", line 394, in task_thread
    task.run(**options)
  File "/home/ubuntu/digits/digits/task.py", line 196, in run
    if not self.process_output(line):
  File "/home/ubuntu/digits/digits/dataset/tasks/create_db.py", line 167, in process_output
    data = self.distribution_data()
  File "/home/ubuntu/digits/digits/dataset/tasks/create_db.py", line 243, in distribution_data
    titles.append(labels[int(key)])
IndexError: list index out of range
```

This is what my list looks like (I use \t to separate):

```
/home/ubuntu/data/train0_small/10_left.jpeg	1
/home/ubuntu/data/train0_small/10_right.jpeg	1
/home/ubuntu/data/train0_small/13_left.jpeg	1
/home/ubuntu/data/train0_small/13_right.jpeg	1
...
```

The images are already sized 256x256. If I reduce the images then the loading succeeds. For that purpose I also split the pictures into two sets of size 10 and size 90. Both were separately loaded successfully. But all 100 together failed.

Any ideas what might be the issue here or how to further troubleshoot the problem?

Kind Regards

Raffael

**Comment by joyofdata** [comment]
I think I found it. The tooltip for the labels file field was misleading.

https://github.com/NVIDIA/DIGITS/pull/83

**Comment by mescarra** [comment]
I had the same error, my numeric labels were in the range [1,N]. I couldn't solve it by moving the labels file 1 line down. I had to shift numeric labels to the range[0,N-1], and that solved the problem.
