### ISSUE TITLE
Difference in the Validation and Evaluation Accuracy

### ISSUE THREAD

**Issue by ashutosh3308** [NVIDIA/DIGITS#815]
I am using pre-trained GoogLeNet and then fine tuned it on my dataset for classifying 11 classes. Validation dataset seems to give the "loss3/top1" 86.5%. But when I evaluating the performance on my evaluation dataset it gives me 77% accuracy. Whatever changes I did it train_val.prototxt, I did the same changes in deploy.prototxt. Is this difference between the validation and evaluation accuracy is normal or did I do something wrong? Any suggestions?

The total number of samples in the validation dataset are 4123 and in evaluation is 4118. For each class, I have made sure that validation and evaluation dataset should contain same number of images

**Comment by gheinrich** [comment]
> whatever changes I did it train_val.prototxt, I did the same changes in deploy.prototxt

Hi @ashutosh3308 in DIGITS you don't have to (shouldn't) change `deploy.prototxt` as DIGITS creates it for you. Can you explain further how you ran your evaluation test? Did you use DIGITS for this?

**Comment by ashutosh3308** [comment]
I'm sorry. I post this question by mistake here.
