### ISSUE TITLE
How to run the high-speed real-time Classify

### ISSUE THREAD

**Issue by shinfo001** [NVIDIA/DIGITS#837]
`inference.py `the mechanism to read the image data from the Text List. 
It appears to be not suitable for real-time solutions.

A method for processing much faster, is there else?

**Comment by TimZaman** [comment]
I think DIGITS is designed as a training system, and it's not ideal for deployment.

![workflow2-624x362](https://cloud.githubusercontent.com/assets/7721540/16033117/8b552530-320a-11e6-9295-8e966e899110.png)

Ergo, what the above graphs says you should do is take the model to your production server, load in the model and do some asynchronous magic.

There's the UI and the API that both use the inference you refer to. Inference then uses the caffe and torch executables. You can use the latter directly as well; with their cli. Either Caffe or Torch can just process one image, or a list of images. Note also that when processing a list of images it does so in batches so it's more time-efficient. So much you know, I guess. There's currently no option to keep open the context or feed images I think. And that won't be trivial.
Still though, just using the API with single images I would classify as high-speed and real-time. But it could be faster indeed.

**Comment by gheinrich** [comment]
Further to @TimZaman's answer, if you are interested in a low-latency HTTP inference server you might be interested in the GPU REST Engine:
https://github.com/NVIDIA/gpu-rest-engine

If you are really after top-notch inference performance the ultimate solution is the NVIDIA GPU Inference Engine:
https://developer.nvidia.com/gpu-inference-engine

**Comment by shinfo001** [comment]
@TimZaman's graph is one of the ideal that I envision.
If Using Caffe or Torch process,They do not give the answer that exactly matches the DIGITS.

@gheinrich’s gave me a hint and challenges, I'd like to try.
