### ISSUE TITLE
Problem installing caffe for digits

### ISSUE THREAD

**Issue by sameerkhann** [NVIDIA/DIGITS#842]
I am trying to install caffe for digits with cudnn and i have been using v0.13.0. when i try to make all the following error prompts up .kindly help me to sort out this 
Linking CXX shared library ../../lib/libcaffe-nv.so
/usr/bin/ld:/usr/local/cuda/lib64/libcudnn.so: file format not recognized; treating as linker script
/usr/bin/ld:/usr/local/cuda/lib64/libcudnn.so:1: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcaffe-nv.so.0.13.0] Error 1
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
make: *** [all] Error 2

**Comment by lukeyeager** [comment]
Is there any reason you're using NVcaffe 0.13 and not 0.14? v0.14 is the current default branch:
https://github.com/NVIDIA/caffe/branches

I've never seen that error before. What operating system are you using? Are you using CMake or the raw Makefile build?

**Comment by sameerkhann** [comment]
i tried NVcaffe 0.14 also and that too with CMake. i am using ubuntu 14.04. problem comes out when i try to compile it with CUDNN :=1. Rest it compiles fine when i comment this part in Makefile.config file

i am using cudnn v4 and cuda 7.5 with all the prrequisite drivers installed

**Comment by sameerkhann** [comment]
i tried NVcaffe 0.14 also and that too with CMake. i am using ubuntu 14.04.
problem comes out when i try to compile it with CUDNN :=1. Rest it compiles
fine when i comment this part in Makefile.config file

i am using cudnn v4 and cuda 7.5 with all the prrequisite drivers installed

**Comment by lukeyeager** [comment]
It looks like you installed cuDNN strangely (probably unzipped a tarball?).

Can you try removing your manual cuDNN install and using deb packages to install instead?
https://github.com/NVIDIA/DIGITS/blob/v3.3.0/docs/UbuntuInstall.md#repository-access
https://github.com/NVIDIA/DIGITS/blob/v3.3.0/docs/BuildCaffe.md#cudnn

**Comment by sameerkhann** [comment]
when i try to install deb package for cuDNN it says  Unable to locate package libcudnn4-dev

**Comment by lukeyeager** [comment]
Read the instructions in that first link for getting access to the cudnn4-dev package.

**Comment by sameerkhann** [comment]
i did that but it  is still showing me that error
E: Unable to locate package libcudnn4-dev

**Comment by sameerkhann** [comment]
solved that issue thanks
one more thing could you please let me know how we can do semantic segmentation with DIGITS. I dont know  how to prepare train lmdb and label lmdb separately in digits.  My labels are also images

**Comment by gheinrich** [comment]
Closing this issue as it's solved. Feel free to post a question for semantic segmentation (but please review this [thread](https://groups.google.com/d/msg/digits-users/DBUBB0NKTYg/kBlsyr3hBgAJ)) first.

**Comment by sameerkhann** [comment]
HI I downloaded DIGITS from Greg Heinrich  but there is no segmentation
folder in examples so that i can use create_images.py

**Comment by gheinrich** [comment]
You need to get the code from pending PR #830 

```
$ git clone https://github.com/NVIDIA/DIGITS.git && cd DIGITS
$ git fetch origin refs/pull/830/head && git checkout FETCH_HEAD
```
