### ISSUE TITLE
DIGITS 4.0.0-rc.1.dev on docker

### ISSUE THREAD

**Issue by riless** [NVIDIA/DIGITS#848]
I used to work with DIGITS on Docker.

I've added this lines to my Dockerfile

```
RUN cd /root && git clone https://github.com/NVIDIA/DIGITS.git digits && cd digits && \
  pip install -r requirements.txt
EXPOSE 5000
EXPOSE 34448
```

Now when I run `/root/digits/digits-server` it gives me this error:
`Error: 'gunicorn_config.py' doesn't exist`

Tried this, but it changes nothing.
```
pip uninstall gunicorn==17.5
pip install gunicorn==17.5
```

When I run `/root/digits/digits-devserver`, it launches the server. But some javascript is not compiled. (same thing in other browsers)
![](http://i.imgur.com/H5kvVGE.png)

Here is the log in the browser console.

```
Security wrapper denied access to property bind on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ is being gradually removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported. ace.js:3
SyntaxError: let is a reserved identifier home_app.js:549
Error: [$injector:modulerr] http://errors.angularjs.org/1.2.23/$injector/modulerr?p0=home_app&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.23%2F%24injector%2Fnomod%3Fp0%3Dhome_app%0Ax%2F%3C%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A6%3A450%0AZc%2Fb.module%3C%2F%3C%2Fb%5Be%5D%3C%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A20%3A1%0AZc%2Fb.module%3C%2F%3C%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A20%3A1%0Ae%2F%3C%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A33%3A267%0Ar%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A7%3A288%0Ae%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A33%3A207%0Agc%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A36%3A309%0Afc%2Fc%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A18%3A170%0Afc%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A18%3A387%0AXc%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A17%3A415%0A%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fangular.min.js%3A214%3A144%0Am.Callbacks%2Fj%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fjquery-1.11.1.min.js%3A2%3A27239%0Am.Callbacks%2Fk.fireWith%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fjquery-1.11.1.min.js%3A2%3A28057%0A.ready%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fjquery-1.11.1.min.js%3A2%3A29889%0AJ%40http%3A%2F%2F0.0.0.0%3A5000%2Fstatic%2Fjs%2Fjquery-1.11.1.min.js%3A2%3A30255%0A
```

See this error in [AngularJS Error Reference](https://docs.angularjs.org/error/$injector/modulerr?p0=home_app&p1=%5B$injector:nomod%5D%20http:%2F%2Ferrors.angularjs.org%2F1.2.23%2F$injector%2Fnomod%3Fp0%3Dhome_app%0Ax%2F%3C@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:6:450%0AZc%2Fb.module%3C%2F%3C%2Fb%5Be%5D%3C@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:20:1%0AZc%2Fb.module%3C%2F%3C@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:20:1%0Ae%2F%3C@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:33:267%0Ar@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:7:288%0Ae@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:33:207%0Agc@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:36:309%0Afc%2Fc@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:18:170%0Afc@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:18:387%0AXc@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:17:415%0A@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fangular.min.js:214:144%0Am.Callbacks%2Fj@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fjquery-1.11.1.min.js:2:27239%0Am.Callbacks%2Fk.fireWith@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fjquery-1.11.1.min.js:2:28057%0A.ready@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fjquery-1.11.1.min.js:2:29889%0AJ@http:%2F%2F0.0.0.0:5000%2Fstatic%2Fjs%2Fjquery-1.11.1.min.js:2:30255%0A)

**Comment by gheinrich** [comment]
For the Javascript issue I think you just need to force-refresh your browser Window e.g. `<Shift><Ctrl>-R`

**Comment by riless** [comment]
Hard refreshed, removed browser cache, used another browser ... same thing

**Comment by gheinrich** [comment]
Did you base your Dockerfile on this [DIGITS 4.0 one](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/digits/4.0/Dockerfile)?

**Comment by riless** [comment]
No, I've made my own Dockerfile

**Comment by gheinrich** [comment]
Would you mind trying the one I linked to?

**Comment by flx42** [comment]
It's available on the Docker Hub, you don't need to build it yourself:
```
nvidia-docker run -ti [...] nvidia/digits:4.0
```

**Comment by riless** [comment]
I have no privileges to install nvidia-docker. that's why I'm building my own Dockerfile based on the versions of CUDA and cuDNN installed on my machine.

When I run (like i did for previous version of DIGITS)

`DOCKER_NVIDIA_DEVICES=`find /dev -name "nvidia*" | while read i; do echo -n "--device $i:$i "; done` && docker run -ti -p 34448:34448 $DOCKER_NVIDIA_DEVICES nvidia/digits:4.0`

There is no errors on the UI, but I cannot run any training, probably due to CUDA and cuDNN versions mismatch between my machine and those installed on the docker .

```
Train Caffe Model Error

    Initialized at 07:11:21 AM (1 second)
    Running at 07:11:23 AM (0 seconds)
    Error at 07:11:23 AM
    (Total - 1 second)

ERROR: Check failed: error == cudaSuccess (35 vs. 0) CUDA driver version is insufficient for CUDA runtime version

Creating layer train-data
Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
        
```

**Comment by flx42** [comment]
You should really install `nvidia-docker`, importing the devices is not enough, you also need the driver files.

**Comment by riless** [comment]
@gheinrich @flx42 now I used the instructions in [this Dockerfile](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/digits/4.0/Dockerfile) instead of [those I have already](https://github.com/Kaixhin/dockerfiles/blob/master/cuda-digits/cuda_v7.0/Dockerfile) it works fine.

The only Issue now, is that `digits.cfg` is ignored (I've used the same `digits.cfg` in these three directories `/etc/digits.cfg`, `$HOME/digits.cfg` and `./digits.cfg` inside my docker)

`digits.cfg` content
```
[DIGITS]
jobs_dir = /work/digits
log_file = /work/digits/digits.log
```

**Comment by riless** [comment]
# Solved 1:

Running `/root/digits/digits-server` will always give you this error:
`Error: 'gunicorn_config.py' doesn't exists`
because of [this line](https://github.com/NVIDIA/DIGITS/blob/b06dfaac0eda04ce93168b3ef2a1fed5ec31bc46/digits-server#L24)
Seems that the path of `gunicorn_config.py` here is relative to the path where you execute it.

`cd /root/digits/ && digits-server`

will work instead.

# Solved 2:

Digits is not looking anymore to /`etc/digits.cfg` and `$HOME/digits.cfg` (I was looking at [a very old issue](https://github.com/NVIDIA/DIGITS/issues/96). The only loaded file is the [instance config file](https://github.com/NVIDIA/DIGITS/blob/master/digits/config/config_file.py#L119) and it is located in `/root/digits/digits/digits.cfg ` not in `/root/digits/digits.cfg`
