### ISSUE TITLE
Job sorting is bugged

### ISSUE THREAD

**Issue by enoonIT** [NVIDIA/DIGITS#853]
Using: 99e2c46fa4babd2e278f6551c9f779e127119b77

Whenever I sort the Digits homepage, some jobs always stay at a given position.
See screenshots for example.
![2016-06-16 23_25_30-digits](https://cloud.githubusercontent.com/assets/7884236/16133723/ae0c6c6c-3419-11e6-89b8-b07fa042ee46.png)
![2016-06-16 23_25_11-digits](https://cloud.githubusercontent.com/assets/7884236/16133724/ae0e72be-3419-11e6-9132-5f188864a0bb.png)

**Comment by TimZaman** [comment]
Even after a fresh reload? I've had this but only when jobs went from _Running Jobs_ table to the _Model_ table.

**Comment by enoonIT** [comment]
Reload doesn't change anything - but switching to Firefox (I'm using Chrome) fixes it.
Probably a cache issue then.

**Comment by lukeyeager** [comment]
@jmancewicz can you look into it?

**Comment by jmancewicz** [comment]
I'm running up-to-date browsers and have had no trouble. Yesterday, I ran on Firefox 40 and an older chrome and saw this problem.  I think it may be a few changes to javascript. I will verify that browser age is the issue and change the code to run in older browsers.

In which browser and version are you seeing this broken sorting? Are there any warnings / errors in the console?

**Comment by jmancewicz** [comment]
It looks like chrome was a late adopter of some of the js1.7 features, namely the `let` keyword. I will change `let` to `var` to see if that fixes it.

**Comment by enoonIT** [comment]
> I'm running up-to-date browsers and have had no trouble. Yesterday, I ran on Firefox 40 and an older chrome and saw this problem. I think it may be a few changes to javascript. I will verify that browser age is the issue and change the code to run in older browsers.
> 
> In which browser and version are you seeing this broken sorting? Are there any warnings / errors in the console?

Chrome, both on Windows and Linux. Windows is version 51.0.2704.84 m
Linux I can't check until monday.

In console I get the following errors:
```
Uncaught TypeError: Cannot match against 'undefined' or 'null'.removePlaceholder @ content.js:463releaseElement @ content.js:517removed.forEach.el @ content.js:609(anonymous function) @ content.js:609
content.js:447 
Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null(…)addPlaceholder @ content.js:447replaceElement @ content.js:510(anonymous function) @ content.js:590resume @ content.js:20
6home_app.js:544 submitted submitted
```

**Comment by jmancewicz** [comment]
I tried with the current chrome, and I'm still seeing the issue. Changing the js `let` to `var` fixed the issue I was seeing in the old Firefox.  I'll have to keep looking into chrome.
