### ISSUE TITLE
Feature request: data augmentation torch

### ISSUE THREAD

**Issue by superphil0** [NVIDIA/DIGITS#865]
Hi, first, I am running DIGITS for the first time and I really like it, great product!

it makes visualization and database management much simpler. One thing I am missing, however, is a method to define my own data augmentation. Maybe it would be possible to add a "transformData"  hook to the model interface https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStartedTorch.md#internal-parameters

there is already a croplen variable (which seems fairly random, why only cropping?)

https://github.com/NVIDIA/DIGITS/blob/55b9656dedbdcf81a3e7def3e77c2706db3b29da/tools/torch/data.lua
maybe expose the whole preprocess function in data.lua as an optional arguement?
then it would be very easy to do augmentation similar to 
https://github.com/facebook/fb.resnet.torch/blob/master/datasets/transforms.lua

another idea is to expand the current data transformations UI (btw I love that you show the mean image)

I would submit a pull request to the data.lua, but I have no idea what that would break

**Comment by superphil0** [comment]
this is connected to https://github.com/NVIDIA/DIGITS/pull/777

**Comment by TimZaman** [comment]
Yes, #777 does everything significant augmentation you could ever need, with a neat UI that exposes it. But it's a fairly big PR so it needs to be checked thoroughly. Would you like to pull #777 in and check it out, @superphil0 ? I'm sure double checking wont hurt and possibly improve!

**Comment by superphil0** [comment]
Yes I already pulled #777 and played a bit with it. However, I am still missing some features (i.e aspect ratio augmentation) also the UI hides in which order the operations are being applied. If I could specify via a hook which transformations, in which order should be applied this would be much more generic. I don't think you will ever be able to implement all possible data augmentations and orders.

**Comment by TimZaman** [comment]
In my experience with post-processing, there's only so much you can do. The order can be changed and I can make it extremely fancy and elaborate, but there's a limit to the significance of the augmentations on your final performance. Although it's easy also to add aspect ratio augmentation, or better, full blown affine/perspective transformations; it's impact will probably not be significant enough to justify an elaborate UI. I also question the impact of the order of the transformations. Currently the order is irrelevant (rotation and scaling happen in one operation) and will therefore have no impact.

**Comment by superphil0** [comment]
I agree that adding every possible combination into the UI is not the way to go

I have made different experiences with augmentations in that it helped me reduce overfitting to some extent

However, from a potential user perspective: I want to reproduce results from a paper and my pure torch implementation in digits, it seems I have two options now fork and make a PR which exposes an interface to preprocess data in the form of a function that takes an image as input and returns an image or hardcode needed augmentation directly in the data.lua file

**Comment by TimZaman** [comment]
I see, and I have this all the time. My own forks usually gets quite messy and i do a lot of hardcoding in the data.lua file. If you just want to reproduce a paper's results it does not sound that genericly applicable so just keeping it in your own fork makes sense. If you get a really good improvement then, it might make a lot of sense to make a PR. That's what i did with #777, it worked so well I PR'ed, if it wouldn't have worked I wouldn't have PR'ed. Let me know what comes out, or if you see room for significant improvement in #777.

**Comment by superphil0** [comment]
I didn't explain well enough, I think it is the other way exposing the PreProcess method might be MORE generic than limiting the possible data augmentations to limited amount of UI possibilities.

In anyway, providing a clean way to experiment with augmentation would IMHO be better than leaving it to people who want to experiment to hack the data.lua script directly

**Comment by TimZaman** [comment]
Ah I see. I do like their approach in the file you refer to, but in practice it's not much different than in #777. And both need to be 'hacked' if you want to change the order of operations.

**Comment by lukeyeager** [comment]
Closed by https://github.com/NVIDIA/DIGITS/pull/777.
