### ISSUE TITLE
Clarify/Update the Model creation information in the Object Detection Tutorial

### ISSUE THREAD

**Issue by S4WRXTTCS** [NVIDIA/DIGITS#873]
From my interpretation of the Object Detection tutorial I'm supposed to copy and paste the entire model description for the detectnet network into the custom network box for a caffe network.

Where the model description is located at 
 https://github.com/NVIDIA/caffe/blob/caffe-0.15/examples/kitti/detectnet_network.prototxt

When I do this it doesn't match the screenshot for the description, and the visualization screenshot doesn't match either.

This might or might not be related to an error I'm getting when I try to train the model. I'm getting
"[ERROR] Train Caffe Model task failed with error code 1" right after I click create.

**Comment by maddiman** [comment]
Hi,

I'm also a bit confused by this, I have tried to remove or change what looks to be the dataset specific options in the dectectnet_network.prototxt linked but I'm kinda guessing, and so far failing.

Any guidance as to what should be changed, or a clean .prorotxt file would be greatly appreciated.

John

**Comment by S4WRXTTCS** [comment]
I'm not aware of anything in the detectnet_network.prototxt that's dataset specific. Unless there is something different about the images/labels you're using.

Have you tried using the Kitti dataset or a subset of it as a starting point? 

In my case the Model Description wasn't the root cause for the error I was getting. The root cause was I didn't have python-opencv installed, and that was causing my failure.

Copying and Pasting the detectnet_network.prototxt into the Custom network box exactly as is seems to work fine. It just doesn't match the visualization shown in the example, but I think that's because the example screenshot is out of date.

**Comment by lukeyeager** [comment]
Closed by #876
