### ISSUE TITLE
different results python <-> DIGITS

### ISSUE THREAD

**Issue by JVR32** [NVIDIA/DIGITS#874]
Hello,

I'm comparing the results in DIGITS and caffe using python ...
I trained the model using DIGITS, selecting the 'crop' option while composing the database.

This is my python code :
```

import numpy as np
import caffe
import scipy

MODEL_FILE = '...'
PRETRAINED = '...'
MEAN_FILE = '...'
LABEL_FILE = '...'

IMAGE_FILE = 'C:/.../.../orig-512_512.jpg' 
IMAGE_FILE2 = 'C:/.../.../orig-256_256.jpg' 

net = caffe.Net(MODEL_FILE, PRETRAINED, caffe.TEST)

transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})

blob = caffe.proto.caffe_pb2.BlobProto()
data = open(MEAN_FILE, 'rb' ).read()
blob.ParseFromString(data)
arr = np.array( caffe.io.blobproto_to_array(blob) )
transformer.set_mean('data', arr[0].mean(1).mean(1))

label_mapping = np.loadtxt(LABEL_FILE, str, delimiter='\t')

transformer.set_transpose('data', (2,0,1))
transformer.set_channel_swap('data', (2,1,0)) # if using RGB instead of BGR
transformer.set_raw_scale('data', 255.0)

net.blobs['data'].reshape(1,3,224,224)

img = caffe.io.load_image(IMAGE_FILE)
	
net.blobs['data'].data[...] = transformer.preprocess('data', img)

output = net.forward()
classi = output['softmax'].argmax()
print "{} {}".format(IMAGE_FILE, label_mapping[classi])
print net.blobs['softmax'].data[0].flatten()
```

When I use input images with dimensions [256 x 256], I get exactly the same results. If the input image has different dimensions (e.g. [256 x 340], [400 x 256], ...), than the result is different -> seems that it is correct in DIGITS, not in python. At first, I thought that the problem was related to cropping a different region in the input image, so I added following lines to my code :

```
img = caffe.io.load_image(IMAGE_FILE)
...
interp = 'bilinear'
if img.shape[0] != height or img.shape[1] != width:
    width_ratio = float(img.shape[1]) / width
    height_ratio = float(img.shape[0]) / height
    # resize to smallest of ratios (relatively larger image), keeping aspect ratio
    if width_ratio > height_ratio:
        resize_height = height
        resize_width = int(round(img.shape[1] / height_ratio))
    else:
        resize_width = width
        resize_height = int(round(img.shape[0] / width_ratio))
    img = scipy.misc.imresize(img, (resize_height, resize_width), interp=interp)
    # chop off ends of dimension that is still too long
    if width_ratio > height_ratio:
        start = int(round((resize_width-width)/2.0))
        img = img[:,start:start+width]
    else:
        start = int(round((resize_height-height)/2.0))
    img = img[start:start+height,:]
...
net.blobs['data'].data[...] = transformer.preprocess('data', img)
```

This didn't make any difference, still no correct classification in python.
Then I discovered that cropping isn't the problem. When I use image processing software, and double the dimensions of an [256 x 256] image to an [512 x 512] image, classification is correct in DIGITS, but not in python. So, I suppose cropping is not the problem, but resizing the image might be.

However, when I use matplotlib to visualize the resized images before calling _transformer.preprocess_, it seems to me that it looks exactly the same as the [256 x 256] image that produces a correct output. Very strange.

Anyone an idea what can be the problem?  So, using DIGITS gives me always the correct classification, but using the python-code produces only the same output if the input image has dimensions [256 x 256] ...

**Comment by JVR32** [comment]
Located the problem : 

`img = caffe.io.load_image(IMAGE_FILE)` produces pixel values in the range [0 1]. 

After rescaling the image with `img = scipy.misc.imresize(img, (resize_height, resize_width), interp=interp)` , pixel values are in the range [0 255].

So I guess -if resizing is necessary- the pixel values must divided by 255 before proceeding.

**Comment by lukeyeager** [comment]
Image data is always be `uint8` whenever DIGITS is in control (at least for now - we're also working on 16-bit data support). So all the models coming out of DIGITS are going to expect data in [0-255].
