### ISSUE TITLE
Classification example - Cannot create cuDNN handle

### ISSUE THREAD

**Issue by salehinejad** [NVIDIA/DIGITS#875]
Hi,

I'm trying to test a model I have trained on digits using the use_archive.py but get the following error:
```
++++++++++++++++++++++++
user@mypc:~/digits/examples/classification$ ./use_archive.py digits-model.tar.gz 67395.png
Unknown file: solver.prototxt
Unknown file: train_val.prototxt
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0628 16:41:50.114161 30550 common.cpp:121] Cannot create cuDNN handle. cuDNN won't be available.
F0628 16:41:50.568711 30550 cudnn_conv_layer.cu:56] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
Aborted (core dumped)
++++++++++++++++++++++++
```

I have nvidia titan cards, which should satisfy version 3:

nvidia-smi result:
```
++++++++++++++++++++++++
+------------------------------------------------------+                       
| NVIDIA-SMI 352.93     Driver Version: 352.93         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 0000:05:00.0      On |                  N/A |
| 22%   46C    P8    16W / 250W |    531MiB / 12284MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 0000:06:00.0     Off |                  N/A |
| 22%   54C    P8    17W / 250W |     23MiB / 12287MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 0000:09:00.0     Off |                  N/A |
| 51%   83C    P2   225W / 250W |   8296MiB / 12287MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1567    G   /usr/bin/X                                     223MiB |
|    0      3275    G   compiz                                         160MiB |
|    0      3711    G   ...WebRTC-EnableWebRtcEcdsa<WebRTC-EnableWeb    85MiB |
|    0      9148    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    33MiB |
|    2      3567    C   python2                                        110MiB |
|    2     28214    C   ./build/tools/caffe                           8159MiB |
+-----------------------------------------------------------------------------+

++++++++++++++++++++++++
```
I can train and test on digits server on local host like a charm. Any idea?

Thanks.

**Comment by lukeyeager** [comment]
How did you install DIGITS? With a deb package or from source?

Where are you picking up `pycaffe` from?

    python -c 'import caffe; print caffe.__file__'

**Comment by salehinejad** [comment]
Thanks for your reply.
It is installed from source. 
And here is the result of above command:
/usr/lib/python2.7/dist-packages/caffe/__init__.pyc

**Comment by lukeyeager** [comment]
It sounds like some sort of environment issue. Have you messed with environment variables like `LD_LIBRARY_PATH` or installed multiple versions of cuDNN in various places?

Also, which version of caffe are you using? `dpkg -l | grep caffe`

**Comment by salehinejad** [comment]
I have not installed the cuDNNs. but its likely that more than one be installed.
Here is my bashrc:
++++++++++++++++++++++++=
export CUDA_HOME=/usr/local/cuda-7.5
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64
PATH=${CUDA_HOME}/bin:${PATH}
export PATH
++++++++++++++++++++++++
Here is the result for dpkg -l | grep caffe:

++++++++++++++++++++++++++++++++
ii  caffe-nv                                              0.14.5-2+cuda7.5                                    amd64        Fast open framework for Deep Learning
ii  caffe-nv-tools                                        0.14.5-2+cuda7.5                                    amd64        Fast open framework for Deep Learning (Tools)
ii  libcaffe-nv0                                          0.14.5-2+cuda7.5                                    amd64        Fast open framework for Deep Learning (Libs)
ii  python-caffe-nv                                       0.14.5-2+cuda7.5                                    amd64        Fast open framework for Deep Learning (Python)
++++++++++++++++++++++++++++++++++++++++++++
It seems there are some duplicates?

**Comment by lukeyeager** [comment]
You probably don't want to install the ` libcudnn5_5.0.5-1+cuda8.0` package on your machine if you're using CUDA 7.5. It's probably not related to this issue, but you might want to fix it anyway. You're looking for the `*+cuda7.5` package.

**Comment by lukeyeager** [comment]
Oh. Then it's a duplicate of https://github.com/NVIDIA/DIGITS/issues/801#issuecomment-224331396. Probably should have seen that coming.

Glad you resolved your issue!

**Comment by salehinejad** [comment]
similar solution, different problem! Thanks again @lukeyeager

**Comment by edregansolution** [comment]
Hi lukeyeager
I have similar issue when create model based on kitti dataset for object recognition.

There are error detail:
./digits-devserver 
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 5.0.0

2017-12-28 12:39:51 [INFO ] Loaded 2 jobs.
2017-12-28 12:40:10 [20171228-124009-141e] [WARNING] Ignoring data_param.source ...
2017-12-28 12:40:10 [20171228-124009-141e] [WARNING] Ignoring data_param.backend ...
2017-12-28 12:40:10 [20171228-124009-141e] [WARNING] Ignoring data_param.source ...
2017-12-28 12:40:10 [20171228-124009-141e] [WARNING] Ignoring data_param.backend ...
2017-12-28 12:40:10 [20171228-124009-141e] [WARNING] Ignoring data_param.source ...
2017-12-28 12:40:10 [20171228-124009-141e] [WARNING] Ignoring data_param.backend ...
2017-12-28 12:40:10 [20171228-124009-141e] [WARNING] Ignoring data_param.source ...
2017-12-28 12:40:10 [20171228-124009-141e] [WARNING] Ignoring data_param.backend ...
2017-12-28 12:40:10 [20171228-124009-141e] [DEBUG] Network sanity check - train
2017-12-28 12:40:10 [20171228-124009-141e] [DEBUG] Network sanity check - val
2017-12-28 12:40:10 [20171228-124009-141e] [DEBUG] Network sanity check - deploy
2017-12-28 12:40:10 [20171228-124009-141e] [INFO ] Train Caffe Model task started.
2017-12-28 12:40:10 [20171228-124009-141e] [INFO ] Task subprocess args: "/home/ubuntu/nvcaffe/caffe/build/tools/caffe train --solver=/home/ubuntu/Digits/digits/jobs/20171228-124009-141e/solver.prototxt --gpu=0 --weights=/home/ubuntu/Digits/examples/object-detection/bvlc_googlenet.caffemodel"
2017-12-28 12:40:10 [20171228-124009-141e] [ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
2017-12-28 12:40:10 [20171228-124009-141e] [ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
2017-12-28 12:40:10 [20171228-124009-141e] [ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
2017-12-28 12:40:10 [20171228-124009-141e] [ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
2017-12-28 12:40:10 [20171228-124009-141e] [ERROR] Train Caffe Model: Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
2017-12-28 12:40:10 [20171228-124009-141e] [ERROR] Train Caffe Model: Cannot create cuDNN handle. cuDNN won't be available.
2017-12-28 12:40:11 [20171228-124009-141e] [ERROR] Train Caffe Model task failed with error code -6

My OS: Ubuntu 16.04
Cuda : 8.0
CuDNN: v5.1
Caffe: NVCaffe, 0.15
DIGITS: v5 or v6

I don't know what is the reason, and how to fix this issue.
I need to resolve this issue urgently, so I would like you guide me this shortly.
Thank you
Ed

**Comment by edregansolution** [comment]
![screenshot from 2017-12-28 13-51-49](https://user-images.githubusercontent.com/31979503/34420213-580d8ab4-ebd6-11e7-919c-ec9485a96115.png)

**Comment by edregansolution** [comment]
![screenshot from 2017-12-28 13-53-11](https://user-images.githubusercontent.com/31979503/34420232-77029afe-ebd6-11e7-83bf-6810cfe83b55.png)

**Comment by ZeroCool11000** [comment]
I think there are some problems with special layers because classification works with VCG and LeNet but not with ResNet. I am using Nvidia Digits 6.1.0 and the last version of nvidia caffe.
