### ISSUE TITLE
DIGITS 4.0 deb package not available in Ubuntu 14.04

### ISSUE THREAD

**Issue by LorenaGdL** [NVIDIA/DIGITS#878]
Ubuntu installations docs start saying the following:

> Deb packages for major releases (i.e. v3.0 and v4.0 but not v3.1) are provided for easy installation on Ubuntu 14.04

However, the deb package for version 4 is not included in the machine learning repo, just version 3 is present (and thus installed): http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64

Is there any way to install DIGITS v4.0 via deb package? If so, please update docs. Thanks in advance

**Comment by lukeyeager** [comment]
We haven't released 4.0 yet. We're still in the release candidate phase.

https://github.com/NVIDIA/DIGITS/tags

**Comment by anas-899** [comment]
> We haven't released 4.0 yet. We're still in the release candidate phase.

it seems that Digits 4.0 is Ready to be installed now, right?
