### ISSUE TITLE
./digits-server: line 26:  6588 Segmentation fault: 11  $PYTHON_EXE $GUNICORN_EXE --config gunicorn_config.py digits.webapp:app $@

### ISSUE THREAD

**Issue by helio-silva** [NVIDIA/DIGITS#884]
I was running digits 2 and 3 in my mac and then gunicorn started to abend with segmentation fault 
Any ideas?

**Comment by lukeyeager** [comment]
Do you have any more error information?

What version of gunicorn do you have?

**Comment by helio-silva** [comment]
gunicorn version 17.5
Python 2.7.11
full error message : Segmentation fault: 11  DIGITS_MODE_TEST=1 $PYTHON_EXE $NOSE_EXE --no-path-adjustment $@

**Comment by lukeyeager** [comment]
Must be some sort of OSX-specific bug.

We don't officially support OSX, and I don't even have a machine to test it out on. If you figure out the problem, please let us know what the solution was and if there's any change we can make in DIGITS to make for a smoother OSX experience.

**Comment by helio-silva** [comment]
It is the full desription from digits 2.0
2016-07-05 21:32:02 [10449] [INFO] Starting gunicorn 17.5
./digits-server: line 7: 10449 Segmentation fault: 11  $(command -v python) $(command -v gunicorn) --config gunicorn_config.py digits.webapp:app $@

**Comment by helio-silva** [comment]
I was trying to setup digits to show it in the Developers conference tomorrow.
Maybe I can do it using docker with ubuntu 14:04

**Comment by lukeyeager** [comment]
By far the simplest solution is `nvidia-docker`:
https://github.com/NVIDIA/nvidia-docker/wiki/DIGITS

**Comment by helio-silva** [comment]
SOLVED!
Sometimes you change your python environment white homebrew. In this case your have to compile CAFFE again and check links to python in the makefile.config
In OSX Virtualbox is necessary to use docker, so the vm will see the graphics adapter and GPU's if virtualbox is able to do it.
Instaled all containers but I'm unable to compile Nvidia-docker on OSX

**Comment by lukeyeager** [comment]
Glad you solved it, and thanks for the explanation!
