### ISSUE TITLE
ValueError: invalid literal for int() with base 10: in utils.py

### ISSUE THREAD

**Issue by AchyutaAich** [NVIDIA/DIGITS#885]
In the file DIGITS/digits/extensions/data/objectDetection/utils.py line 185,
it has gt.occlusion = int(row[2])

Since row[2] is a string type, it causes the error : ValueError: invalid literal for int() with base 10:

Hence we should first convert it to float and then to int type :)

**Comment by gheinrich** [comment]
Hi @AchyutaAich, occlusion is not supposed to be a float. As per the KITTI doc (reproduced [there](https://github.com/NVIDIA/DIGITS/tree/digits-4.0/digits/extensions/data/objectDetection#label-format)):

```
#Values    Name      Description
----------------------------------------------------------------------------
...
   1    occluded     Integer (0,1,2,3) indicating occlusion state:
                     0 = fully visible, 1 = partly occluded
                     2 = largely occluded, 3 = unknown
```

**Comment by AchyutaAich** [comment]
Yes, even I am stating that first it should be made float due to python demands, then make it cast to int type

**Comment by gheinrich** [comment]
Can you elaborate? I don't understand. Why would we need to convert to `float` since the string represents an `int`?

```python
>>> int("0")
0
```

**Comment by AchyutaAich** [comment]
What is your version of python ?

**Comment by gheinrich** [comment]
Please read my first comment.

**Comment by AchyutaAich** [comment]
Fine .. can you provide me a link to sample format of label.

**Comment by gheinrich** [comment]
See this [doc](https://github.com/NVIDIA/DIGITS/tree/digits-4.0/examples/object-detection#downloading-and-preparing-the-kitti-data)
