### ISSUE TITLE
ParseError Message type "caffe.LayerParameter" has no field named "input_param"

### ISSUE THREAD

**Issue by AchyutaAich** [NVIDIA/DIGITS#886]
Following the steps mentioned in https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection

After pasting the detectnet model description from https://github.com/NVIDIA/caffe/tree/caffe-0.15/examples/kitti to the text area, it gives the error : "caffe.LayerParameter" has no field named "input_param"

**Comment by lukeyeager** [comment]
Did you follow this step?

> In order to train DetectNet, NVcaffe version 0.15.1 or later is required.

**Comment by gheinrich** [comment]
The same error was seen by a user who posted this [message])https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/digits-users/iBRTu3F_k-M) on DIGITS Users. The solution was to re-install the system though it might have been enough to un-install the previous instance of nv-caffe.

**Comment by LorenaGdL** [comment]
I also run into this issue yesterday. I solved it by updating to version 0.15.5 of NVcaffe, but I realized that entry point of the caffe git points to version 0.14, and that was indeed the orig problem (a simple git clone gets an "old" version). So I have a question: why is the entry point behind latest branch/tag? Are you following any special convention? Any insights would be appreciated, just to know the way you work and update things

Thanks in advance

**Comment by lukeyeager** [comment]
> I solved it by updating to version 0.15.5 of NVcaffe, but I realized that entry point of the caffe git points to version 0.14, and that was indeed the orig problem (a simple git clone gets an "old" version). So I have a question: why is the entry point behind latest branch/tag? Are you following any special convention?

That's right - `caffe-0.14` is still the default branch:
https://github.com/NVIDIA/caffe/branches

Technically the 0.15 branch is still in the "release candidate" phase, as is the 4.0 branch of DIGITS. It's just a little less obvious because Caffe uses simple tags like `v0.15.8` whereas DIGITS uses complex tags like `v4.0.0-rc.3`.

Once we release NVcaffe 0.15 (at the same time as DIGITS 4.0), we'll change the default branch. Sorry for the confusion!

**Comment by skyzhao3q** [comment]
to LorenaGdl

could you tell me how to update caffe0.14 to version 0.15.5 of NVcaffe ?

thanks

**Comment by gheinrich** [comment]
Follow those [instructions](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/docs/BuildCaffe.md) and append `-b caffe-0.15` to the `git clone` command line:
`git clone https://github.com/NVIDIA/caffe.git $CAFFE_HOME -b caffe-0.15`

Then point DIGITS to your new `$CAFFE_HOME` folder by editing the configuration ([doc](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/docs/BuildDigits.md#troubleshooting))

**Comment by skyzhao3q** [comment]
to gheinrich
Thank you for your answer.

I have checked out branch caffe-0.15 and switch to it. then build it without any problems.

Although DIGITS point to my $CAFFE_HOME (~/caffe), I found out that on the DIGITS Site
the caffe version is still 0.14.5 from the info menu.

What do I need to do?

**Comment by gheinrich** [comment]
Did you do:
> Then point DIGITS to your new `$CAFFE_HOME` folder by editing the configuration ([doc](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/docs/BuildDigits.md#troubleshooting))

(and restart the server)

**Comment by skyzhao3q** [comment]
Yes, I have set the path to ~/caffe where is the path of the source by the command
./digits-devserver --config
and then restart the server, but did not work .

**Comment by gheinrich** [comment]
Are you sure you're using the right DIGITS port (`localhost:5000` for `digits-devserver`)?
Can you show the console log of your DIGITS Caffe path configuration?

**Comment by skyzhao3q** [comment]
chou@chou-dl:~/digits$ ./digits-devserver --config
================================ Jobs Directory ================================
Where would you like to store job data?

        Suggested values:
        (D*) [default] /home/chou/digits/digits/jobs
>>
Using "/home/chou/digits/digits/jobs"

===================================== GPUs =====================================
Attached devices:
Device #0:
        Name                 GeForce GTX 960
        Compute capability   5.2
        Memory               2.0 GB
        Multiprocessors      8


Input the IDs of the devices you would like to use, separated by commas, in order of pref   erence.

        Suggested values:
        (D*) [default] 0
        (N)  [none]    <NONE>
>>
Using "0"

=================================== Log File ===================================
Where do you want the log files to be stored?

        Suggested values:
        (D*) [default] /home/chou/digits/digits/digits.log
        (N)  [none]    <NONE>
>>
Using "/home/chou/digits/digits/digits.log"

=============================== Data extensions ================================
Available extensions:
        ID='image-gradients' Title='Gradients'
        ID='image-processing' Title='Processing'
        ID='image-object-detection' Title='Object Detection'

Input the IDs of the extensions you would like to use, separated by commas.

        Suggested values:
        (D*) [default] image-processing,image-object-detection
        (A)  [all]     image-gradients,image-processing,image-object-detection
        (N)  [none]    <NONE>
>>
Using "image-processing,image-object-detection"

=============================== View extensions ================================
Available extensions:
        ID='image-bounding-boxes' Title='Bounding boxes'
        ID='image-gradients' Title='Gradients'
        ID='image-image-output' Title='Image output'
        ID='all-raw-data' Title='Raw Data'

Input the IDs of the extensions you would like to use, separated by commas.

        Suggested values:
        (D*) [default] image-bounding-boxes,image-image-output,all-raw-data
        (A)  [all]     image-bounding-boxes,image-gradients,image-image-output,all-raw-da   ta
        (N)  [none]    <NONE>
>>
Using "image-bounding-boxes,image-image-output,all-raw-data"

==================================== Caffe =====================================
Where is caffe installed?

        Suggested values:
        (H*) [CAFFE_HOME]      /home/chou/caffe
        (P)  [PATH/PYTHONPATH] <PATHS>
>> /home/chou/caffe
Using "/home/chou/caffe"

==================================== Torch =====================================
Where is torch installed?

        Suggested values:
        (P*) [PATH/TORCHPATH] <PATHS>
        (N)  [none]           <NONE>
>>
Using "<PATHS>"
ERROR: torch binary not found in PATH
Using ""

Saved config to /home/chou/digits/digits/digits.cfg
Couldn't import dot_parser, loading of dot files will not be possible.
2016-08-05 17:27:30 [INFO ] Loaded 2 jobs.
  ___ ___ ___ ___ _____ ___
 |   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 4.1-dev

 * Running on http://0.0.0.0:5000/
192.168.111.111 - - [2016-08-05 17:27:45] "GET / HTTP/1.1" 200 30721 0.053494
192.168.111.111 - - [2016-08-05 17:27:45] "GET /static/css/bootstrap-theme.min.css?ver=64   e0d1248a74f911327fafbb8dc5eec7 HTTP/1.1" 200 19148 0.001906
192.168.111.111 - - [2016-08-05 17:27:45] "GET /static/css/style.css?ver=64e0d1248a74f911   327fafbb8dc5eec7 HTTP/1.1" 200 2150 0.002577
192.168.111.111 - - [2016-08-05 17:27:45] "GET /static/css/c3.min.css?ver=64e0d1248a74f91   1327fafbb8dc5eec7 HTTP/1.1" 200 2258 0.000650
192.168.111.111 - - [2016-08-05 17:27:45] "GET /static/fonts/glyphicons-halflings-regular   .woff HTTP/1.1" 200 23608 0.002359
192.168.111.111 - - [2016-08-05 17:27:45] "GET /completed_jobs.json HTTP/1.1" 200 4900 0.   004320

**Comment by gheinrich** [comment]
That looks OK... what does `/home/chou/caffe/build/tools/caffe --version` say?

**Comment by skyzhao3q** [comment]
oh, no, that is still 
caffe version 0.14.5
but why ? I did checkout the 0.15
chou@chou-dl:~/caffe$ git branch
  caffe-0.14
* caffe-0.15
  remotes/origin/caffe-0.16
chou@chou-dl:~/caffe$

**Comment by gheinrich** [comment]
Did you rebuild everything after you switched to `caffe-0.15`?

**Comment by skyzhao3q** [comment]
yes, I remove the build folder and run the command below 
mkdir build
cd build
cmake ..
make --jobs=4

**Comment by gheinrich** [comment]
How does that compare with what you see:
```sh
$ git describe
v0.15.9
$ git log --oneline
94c600c Mark 0.15.9
```

**Comment by skyzhao3q** [comment]
I got v0.14.5-3-g38651f2.
then I clone the source again of branch 0.15 ,and it worked now.
Thank you very much. And sorry of wasting your time for such mistake.
