### ISSUE TITLE
failure to install webinstaller on Ubuntu 14.04, 346.59 opensource nvidia driver for GTX 680

### ISSUE THREAD

**Issue by justinvictor** [NVIDIA/DIGITS#89]
Hi,

I'm a newbie to Linux and have been trying for a long time to get the webinstaller up. I followed the installation instructions, but the program did not detect any gpu on my machine. And then, as i was following the training example and got to the training part, there was this error: "ERROR: Check failed: error == cudaSuccess (30 vs. 0) unknown error". 

Can anyone help regarding this? Thanks!

Best Regards,
Justin

**Comment by lukeyeager** [comment]
So you're using an opensource driver? But you were able to build caffe with CUDA support? That's weird, do you even have CUDA installed? I recommend using the [Nvidia drivers](http://www.nvidia.com/Download/index.aspx?lang=en-us).

Also, in the future you should post this type of issue on our google group: https://groups.google.com/d/forum/digits-users

**Comment by moconnor725** [comment]
The caffe that is bundled in the web installer is set up to use GPUs.  I would suggest finding out why the GPU is not detected.  Fallback would be to build caffe with CPU_ONLY on and drop that in to the web installer directory.

**Comment by justinvictor** [comment]
Thanks Luke and Moconnor! the culprit is the opensource driver from xorg-edgers. I installed the proprietary drivers and things are ok now. (the driver installation process is horrible though)

**Comment by fanser** [comment]
@moconnor725 Could you tell me how to build caffe with CPU_ONLY in web installer? I don't find the caffe file using web installer.thanks

**Comment by justinvictor** [comment]
hi i am sorry but i am no longer working on this this and have lost familiarity. however i remembered that i had problems due to GPU, and not CPU.



Sent by Outlook for Android






On Sun, Jan 3, 2016 at 7:11 PM -0800, "fanser" <notifications@github.com> wrote:





@moconnor725 Could you tell me how to build caffe with CPU_ONLY in web installer? I don't find the caffe file using web installer.thanks

---

**Comment by fanser** [comment]
@justinvictor Thank for your answer. My computer graphic card don't support CUDA, so i try the CUP-ONLY model and didn't install it. Now i don't know how to solve it. Hope someone come help me.
thanks again!
