### ISSUE TITLE
learning rate for adaDelta and adaGrade

### ISSUE THREAD

**Issue by 201power** [NVIDIA/DIGITS#893]
For the adaDelta and adaGrade solver, how should I set the learning rate? Fixed?

Since adaDelta/adaGrade have adaptive learning rate, does it only need an initial learning rate?
In my case, adaDelta / adaGrade does not work as well as SGD.

**Comment by gheinrich** [comment]
Hello, the learning rate is expected to be the same between `SGD` and `ADAGRAD`. The difference is in the weight update formula. Have a look at this [page](http://caffe.berkeleyvision.org/tutorial/solver.html) for more information.

**Comment by TimZaman** [comment]
Hmm interesting point; and nice link @gheinrich: the link/doc says the gradient gets multiplied by that learning rate (!), whereas the adaptive solvers shouldn't need such a thing according to the paper. http://arxiv.org/pdf/1212.5701.pdf . If you want to stick to the vanilla implementation, set the learning rate on 1.0 and policy on fixed.
Reading up on this, I have found someone saying that changing the policy to anything other than fixed might through off the accumulated statistics ([source](https://groups.google.com/forum/#!topic/caffe-users/up28yZmmx7I)).. And now we find us going down the rabbit hole.
Maybe the lr_policy can be toggled to `fixed` when an adaptive optimizer has been selected?

**Comment by gheinrich** [comment]
Thanks for the inspiring comment @TimZaman. I'll be closing this issue for now.
