### ISSUE TITLE
Cannot Enter Localhost 

### ISSUE THREAD

**Issue by dineshgit** [NVIDIA/DIGITS#905]
Hello,

I have a CUDA Gpu machine capable and I have tried all the steps mentioned on the post to install NVidia driver, Cuda driver and Digits step by step. However, despite having positive installation results on Terminal, I cannot enter http://localhost/ at all from my Firefox browser.

I'm running Ubuntu 14.04 from USB.

What could the issue be ? Could someone kindly help ?

*I wasn't able to use the "apt-get" method of installing the files, instead I used "aptitude" command to complete them.

**Comment by lukeyeager** [comment]
> I wasn't able to use the "apt-get" method of installing the files, instead I used "aptitude" command to complete them.

That sounds suspicious. Did you ignore some errors when using `aptitude`?

> I'm running Ubuntu 14.04 from USB.

I can't think of any reason why that would be a problem, but I've never tried it myself nor heard of anyone else doing so.

**Comment by IsaacYangSLA** [comment]
@dineshgit, can you find your log file?  Usually it's in /var/log (or /var/log/nginx).  It helps us a lot if you can provide some info from the log files.  Thanks.

**Comment by dineshgit** [comment]
Hi all,

Thank you all for the support. I couldn't find the nginx file so I have zipped my entire /var/log file and attached it here. I hope this will be helpful to find out a solution. 

[log.tar.gz](https://github.com/NVIDIA/DIGITS/files/363823/log.tar.gz)

**Comment by IsaacYangSLA** [comment]
It seemed your nginx was not running.  Can you check if your port 34448 is listening to incoming traffic?  Also, try http://localhost:34448 to see if DIGITS page shows up.

**Comment by dineshgit** [comment]
Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx.

This is the message I get now when I try accessing Localhost. Is there any problems yet?

**Comment by dineshgit** [comment]
Hello,

Another update - I got the below error when trying to install DIGITS:

dinesh@dinesh-VirtualBox:~$ sudo apt-get install digits
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 digits : Depends: python-caffe-nv (>= 0.13) but it is not going to be installed
          Depends: caffe-nv (>= 0.13) but it is not going to be installed
          Recommends: torch7-nv but it is not going to be installed

Could this indicate that I'm missing some packages ?

**Comment by lukeyeager** [comment]
`apt-get` gives the worst error messages. Can you try using `aptitude` instead? That should tell you what the problem is.
```sh
$ sudo apt-get install aptitude
$ sudo aptitude install digits
```

**Comment by dineshgit** [comment]
Hi,

I got Digit interface running on Localhost finally. But I also realise that Ubuntu is now becoming an issue. Each time I login, I'm going through an endless Login loop. I have tried many many solutions including the one shown below:

chown username:username .Xauthority

but to no success at all. I've even tried switching between lightdm and gdm.
Is there a solution to this issue ?

**Comment by fillan** [comment]
Hi dineshgit, can you share how you resolved this issue? thanks.

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 digits : Depends: python-caffe-nv (>= 0.13) but it is not going to be installed
          Depends: caffe-nv (>= 0.13) but it is not going to be installed
          Recommends: torch7-nv but it is not going to be installed

**Comment by lukeyeager** [comment]
@fillan can you try using `aptitude` to see if you get a better error message? (https://github.com/NVIDIA/DIGITS/issues/905#issuecomment-233413088)

**Comment by K-Wu** [comment]
I'm running into the same problem as @dineshgit and @fillan , `aptitude` cannot solve the problem. This is what I get after retrying `aptitude`.

```
The following NEW packages will be installed:
  caffe-nv{ab} caffe-nv-tools{a} cython{a} digits graphicsmagick{a}
  gunicorn{a} libao-common{a} libao4{a} libbz2-dev{a} libcaffe-nv0{ab}
  libcudnn5{a} libdsdp-5.8gf{a} libexif-dev{a} libfreeimage3{a}
  libglpk36{a} libgraphicsmagick1-dev{a} libgraphicsmagick3{a}
  liblcms2-dev{a} liblz4-1{a} libmad0{a} libnccl1{ab} libopencore-amrnb0{a}
  libopencore-amrwb0{a} libraw9{a} libsox-fmt-all{a} libsox-fmt-alsa{a}
  libsox-fmt-ao{a} libsox-fmt-base{a} libsox-fmt-mp3{a} libsox-fmt-oss{a}
  libsox-fmt-pulse{a} libsox2{a} libtwolame0{a} libwmf-dev{a}
  python-blinker{a} python-bs4{a} python-caffe-nv{ab} python-cvxopt{a}
  python-flask{a} python-flaskext.socketio{a} python-flaskext.wtf{a}
  python-gevent{a} python-gevent-websocket{a} python-gflags{a}
  python-greenlet{a} python-h5py{a} python-itsdangerous{a} python-joblib{a}
  python-leveldb{a} python-lmdb{a} python-networkx{a} python-numexpr{a}
  python-openpyxl{a} python-pandas{a} python-pandas-lib{a} python-patsy{a}
  python-protobuf{a} python-pydot{a} python-pyinotify{a} python-skimage{a}
  python-skimage-lib{a} python-sklearn{a} python-sklearn-lib{a}
  python-socketio{a} python-statsmodels{a} python-statsmodels-lib{a}
  python-tables{a} python-tables-data{a} python-tables-lib{a}
  python-werkzeug{a} python-wtforms{a} python-yaml{a} sox{a} torch7-nv{ab}
0 packages upgraded, 74 newly installed, 0 to remove and 126 not upgraded.
Need to get 28.5 MB/93.4 MB of archives. After unpacking 571 MB will be used.
The following packages have unmet dependencies:
 torch7-nv : Depends: cuda-cublas-8-0 which is a virtual package.
             Depends: cuda-cudart-8-0 which is a virtual package.
             Depends: cuda-cusparse-8-0 which is a virtual package.
             Depends: cuda-curand-8-0 which is a virtual package.
             Depends: cuda-license-8-0 which is a virtual package.
 caffe-nv : Depends: cuda-cudart-8-0 which is a virtual package.
 libcaffe-nv0 : Depends: cuda-cublas-8-0 which is a virtual package.
                Depends: cuda-cudart-8-0 which is a virtual package.
                Depends: cuda-curand-8-0 which is a virtual package.
 python-caffe-nv : Depends: cuda-cudart-8-0 which is a virtual package.
 libnccl1 : Depends: cuda-cudart-8-0 which is a virtual package.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     caffe-nv [Not Installed]
2)     caffe-nv-tools [Not Installed]
3)     digits [Not Installed]
4)     libcaffe-nv0 [Not Installed]
5)     libnccl1 [Not Installed]
6)     python-caffe-nv [Not Installed]
7)     torch7-nv [Not Installed]

     Leave the following dependencies unresolved:
8)     digits recommends torch7-nv


Accept this solution? [Y/n/q/?] y
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 126 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

**Comment by lukeyeager** [comment]
Using `aptitude` usually won't solve the problem for you, but it does give better error messages. See this?
```
The following packages have unmet dependencies:
 torch7-nv : Depends: cuda-cublas-8-0 which is a virtual package.
             Depends: cuda-cudart-8-0 which is a virtual package.
             Depends: cuda-cusparse-8-0 which is a virtual package.
             Depends: cuda-curand-8-0 which is a virtual package.
             Depends: cuda-license-8-0 which is a virtual package.
 caffe-nv : Depends: cuda-cudart-8-0 which is a virtual package.
 libcaffe-nv0 : Depends: cuda-cublas-8-0 which is a virtual package.
                Depends: cuda-cudart-8-0 which is a virtual package.
                Depends: cuda-curand-8-0 which is a virtual package.
 python-caffe-nv : Depends: cuda-cudart-8-0 which is a virtual package.
 libnccl1 : Depends: cuda-cudart-8-0 which is a virtual package.
```

Looks to me like you didn't follow [these instructions](https://github.com/NVIDIA/DIGITS/blob/digits-5.0/docs/UbuntuInstall.md#prerequisites) to get access to the cuda repo. If you've set up your repository access properly, you should have access to `cuda-cudart-8-0`.
```sh
$ apt-cache policy cuda-cudart-8-0
cuda-cudart-8-0:
  Installed: 8.0.44-1
  Candidate: 8.0.44-1
  Version table:
 *** 8.0.44-1 500
        500 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Packages
        100 /var/lib/dpkg/status
```
