### ISSUE TITLE
Classify_one strange failure 

### ISSUE THREAD

**Issue by engharat** [NVIDIA/DIGITS#907]
Hi guys,
I changed from nvcaffe 015 to nvcaffe016, cuda 7.5 to cuda 8.0, and drivers from 354 to 362 (the one linked with cuda 8.0), cudnn 4 to 5.
I got a bunch of problems, so I reverted back to nvcaffe 015 (15.7) cuda 7.5, still keeping the 362 driver and the cudnn 5.
The problem is that I get this strange error when doing classify_one with DIGITS:
`Error code -6
F0714 21:28:53.351652 15904 gpu_memory.cpp:68] Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager`
the problem happens when I run the classify_one on a training network. It seems like it cannot allocate memory if still used by the training (but plenty of GPU RAM available)
any idea?

**Comment by lukeyeager** [comment]
Submitted to NVIDIA/caffe repo: https://github.com/NVIDIA/caffe/issues/196
