### ISSUE TITLE
Wrong Caffe version parsed for OS-X

### ISSUE THREAD

**Issue by TimZaman** [NVIDIA/DIGITS#914]
See title. I bet there's a reason for this line that hardcodes the caffe version for mac to `0.11.0` 
https://github.com/NVIDIA/DIGITS/blob/master/digits/config/caffe_option.py#L158 . 
I just removed L157-L159 and everything seems fine:
![image](https://cloud.githubusercontent.com/assets/7721540/16893350/e7759f64-4ae9-11e6-9ed7-6dc04fa532a8.png)

**Comment by IsaacYangSLA** [comment]
@TimZaman , thanks for pointing that out.  I might forget to remove that, or maybe I keep it for other reason.  Let me find out.

**Comment by IsaacYangSLA** [comment]
@TimZaman , can you help check what happens if your Caffe in Darwin does not have version info?  We would like DIGITS to tell users to upgrade their Caffe when no version info is available.  Thanks.

**Comment by TimZaman** [comment]
Yes give me an hour

**Comment by TimZaman** [comment]
@IsaacYangSLA I made a mini PR for this Mac issue, since you said you're a BSD man.

**Comment by IsaacYangSLA** [comment]
@TimZaman , thanks.  I will comment on the PR.
