### ISSUE TITLE
Object Detection Tutorial

### ISSUE THREAD

**Issue by cicero19** [NVIDIA/DIGITS#915]
Not really an issue per se, rather a clarification for the object detection example. Wondering if you could be more explicit with what dataset was used for the example as the KITTI website has many datasets (perhaps a URL would help). 

Also, what is meant by KITTI format for the label text file?

**Comment by gheinrich** [comment]
Hi @cicero19 in case you were looking at the `master` branch I hope you'll find the doc clearer on https://github.com/NVIDIA/DIGITS/tree/v4.0.0-rc.3/examples/object-detection and https://github.com/NVIDIA/DIGITS/blob/v4.0.0-rc.3/digits/extensions/data/objectDetection/README.md

**Comment by gheinrich** [comment]
No feedback => closing.
