### ISSUE TITLE
No 'Object Detection' option in create dataset

### ISSUE THREAD

**Issue by mistiansen** [NVIDIA/DIGITS#917]
I don't see an 'Object Detection' option when I try to create a new dataset. I installed less than a week ago. Is there a specific version needed for detection? 

Thanks

**Comment by mistiansen** [comment]
Sorry, I see that it's a version 4.0 feature. 4.0 was recently released for members of the Developer Program, but I don't see the option to get it anywhere. Does anyone have any pointers here?

**Comment by gheinrich** [comment]
Sorry, while we are preparing .deb packages for 4.0 you'll have to download DIGITS 4.0 from source from [there](https://github.com/NVIDIA/DIGITS/tree/v4.0.0).
