### ISSUE TITLE
Caffe Error: Error code -8 SIGFPE

### ISSUE THREAD

**Issue by DenissePerez** [NVIDIA/DIGITS#918]
Hello, I'm running a design I've ran before for other datasets, but now with this one it stops after 2 seconds and says error code -8 and there's no description about it, this is what it shows:
```
Top shape: 60 256 1 1 (15360)
Memory required for data: 54228720
Creating layer conv7
Creating Layer conv7
conv7 <- conv6
conv7 -> conv7
Setting up conv7
Top shape: 60 224 1 1 (13440)
Memory required for data: 54282480
Creating layer relu7C
Creating Layer relu7C
relu7C <- conv7
relu7C -> conv7 (in-place)
Setting up relu7C
Top shape: 60 224 1 1 (13440)
Memory required for data: 54336240
Creating layer pool8
Creating Layer pool8
pool8 <- conv7
pool8 -> pool8
```
What do you think it could be, or I could do? Thanks in advance! :)

**Comment by lukeyeager** [comment]
Can you look at the last few lines of the raw Caffe output log? The messages you posted above aren't helpful.

**Comment by DenissePerez** [comment]
I0720 09:55:31.020292 17294 net.cpp:160] Top shape: 50 256 1 1 (12800)
I0720 09:55:31.020297 17294 net.cpp:168] Memory required for data: 45101000
I0720 09:55:31.020303 17294 layer_factory.hpp:76] Creating layer pool8
I0720 09:55:31.020316 17294 net.cpp:109] Creating Layer pool8
I0720 09:55:31.020323 17294 net.cpp:457] pool8 <- conv8
I0720 09:55:31.020333 17294 net.cpp:414] pool8 -> pool8
*** Aborted at 1469026531 (unix time) try "date -d @1469026531" if you are using GNU date ***
PC: @     0x7fa18e47960e caffe::Blob<>::Reshape()
*** SIGFPE (@0x7fa18e47960e) received by PID 17294 (TID 0x7fa18ec9ca00) from PID 18446744071801640462; stack trace: ***
@     0x7fa184dec180 (unknown)
@     0x7fa18e47960e caffe::Blob<>::Reshape()
@     0x7fa18e4799da caffe::Blob<>::Reshape()
@     0x7fa18e3fe084 caffe::PoolingLayer<>::Reshape()
@     0x7fa18e49ed3b caffe::Net<>::Init()
@     0x7fa18e4a04d8 caffe::Net<>::Net()
@     0x7fa18e3975e2 caffe::Solver<>::InitTrainNet()
@     0x7fa18e3988f2 caffe::Solver<>::Init()
@     0x7fa18e398c19 caffe::Solver<>::Solver()
@           0x411a65 caffe::GetSolver<>()
@           0x4090d0 train()
@           0x406968 main
@     0x7fa184dd8b45 (unknown)
@           0x407118 (unknown)

**Comment by lukeyeager** [comment]
I've seen a `SIGFPE` before when trying to use a network on smaller images than it was designed for. AlexNet and GoogLeNet are designed for 256x256 images. If you go smaller than ~100x100, you'll get this type of error.

**Comment by DenissePerez** [comment]
Ah, ok. Thank you very much!
