### ISSUE TITLE
Any fine-tuned detectNet model for download?

### ISSUE THREAD

**Issue by hengck23** [NVIDIA/DIGITS#924]
This is a question. The link https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection shows how to fine-tuned googlenet for kitt car detection. Is there a link for me to download the fine-tuned model? (not the pretrained imageNet one). I would like to straight away port to TX1 to see the results.

**Comment by gheinrich** [comment]
Hello @hengck23 we cannot provide models trained on KITTI data without proper scrutiny if the licensing implications of doing so. Can you not train a model yourself?

**Comment by hengck23** [comment]
@gheinrich
Thanks. After I put to TX1, i will let you know the results.

**Comment by gheinrich** [comment]
Thanks, I will close this issue then.
