### ISSUE TITLE
Can't select adam solver

### ISSUE THREAD

**Issue by Nernas** [NVIDIA/DIGITS#934]
Hi, Guys.

I use digits 4.0 and nvcaffe 0.15 version on windows.
I can't object detection example. because I can't select adam solver.
also RMSPROP and ADADELTA too.

Thoes three solvers support only Torch?

**Comment by gheinrich** [comment]
Hello,
SGD, NESTEROV, ADAGRAD, RMSPROP, ADADELTA and ADAM solvers are only enabled if DIGITS correctly recognizes (NVIDIA) Caffe as being version at least version 0.14, [see code](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/frameworks/caffe_framework.py#L37-L40).

Can you let us know which version/flavour of Caffe are reported in the Info menu (top right corner of the main page)? As a workaround you might want to edit the code to forcibly enable the missing solvers.

**Comment by Nernas** [comment]
@gheinrich Oh, sorry. nvcaffe is nvidia caffe 0.15 version. All build is complete and no errors.
nvidia caffe 0.15 version is not stable?

**Comment by lukeyeager** [comment]
> Can you let us know which version/flavour of Caffe are reported in the Info menu (top right corner of the main page)?

Please just give us this info. It's possibly a bug with version-parsing on Windows (#769).

**Comment by IsaacYangSLA** [comment]
@Nernas , can you try caffe -version in your command prompt?  Also, on the upper right corner of the web page, there is a 'info' menu.  Can you tell us what you see in that menu?  We would like to see if your caffe reports correct version so DIGITS can enable those solvers.

**Comment by Nernas** [comment]
@lukeyeager, @IsaacYangSLA

Sorry for late comment.
I was solve this problem yet.

Windows caffe and nvidia caffe have save problem that caffe -version make wrong message.
'caffe say caffe version CAFFE_VERSION'
then, I need to fix that problem. ( if we dont use digits, that's no problem. )
because digits say 'Your Caffe does not have version info. Please upgrade it'

I can find that problem solved to this page.
https://github.com/NVIDIA/DIGITS/issues/47

I was changed root/digits/config/caffe_option.py ln 169
version_string = line[line.find(pattern) + len(pattern)+1:].rstrip()
to version_string = '0.12.0'

my caffe build version is 0.15.3, but digits know that my caffe version is 0.12.
then, I can't select that 3 solver type.

finally, caffe_option.py ln 169 
version_string changed my nvidia caffe's version 0.15.3, then I can select all solver.
