### ISSUE TITLE
handling image sizes larger than 256 x 256

### ISSUE THREAD

**Issue by paras42** [NVIDIA/DIGITS#939]
I would like Digits to be able to handle image sizes (without squashing or cropping for example) images larger than 256 x 256.  Is that possible?

**Comment by gheinrich** [comment]
Hello, can you give a bit more context? Nowhere in DIGITS is there a limit on 256x256 images so I do not understand the question. Are you willing to use those images during training or during inference?

**Comment by paras42** [comment]
Basically I have files (images) that are larger (2544 x 3056).  I then squash them to 256 x 256 in Digits.  However, I am wondering if my classification accuracy would improve if the larger images could be used (perhaps a sliding window technique of smaller 256 x 256 portions).  These images have subtle distinctions that may be lost by squashing.  Hope this makes senses.
Any help would be much appreciated.

Sent from my iPhone

**Comment by gheinrich** [comment]
You can use larger images but it is true that if you do so, you will need not be able to use the reference Alexnet and Googlenet networks. Feel free to explore the "custom network" tab on the model creation page. There you will see hints on the small numbers of changes to make to use a custom network of yours in DIGITS.

**Comment by paras42** [comment]
Great, thanks very much for the information, that is helpful.



Sent from my iPhone

**Comment by gheinrich** [comment]
Thanks, in the meantime I am closing this issue.
