### ISSUE TITLE
Object detection file names required to be numeric

### ISSUE THREAD

**Issue by darreneng** [NVIDIA/DIGITS#940]
When creating an Object Detection dataset, it seems like DIGITS requires the file names to be numeric. When I tried to create a dataset with filenames that contained alphabetic characters, I got the error `ERROR: ValueError: invalid literal for int() with base 10: 'ba'` in the sidebar under Create train_db DB where `ba.txt` and `ba.bmp` were the names of two of my files. When I changed the filenames to include only numeric characters (eg. `00.txt` or `00.bmp`), the dataset was successfully created.

I'm not sure if this requirement actually exists or is the result of a different bug, but it would be nice if DIGITS could handle alphabetic file names or if there was at least a warning on the UI.

**Comment by gheinrich** [comment]
Thanks for the report. As hinted on this [page](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/extensions/data/objectDetection/README.md#folder-structure) we expect a numerical identifier and the error is indeed not self-explanatory at all. We might relax this constraint in the future. In the mean time, can you stick to the expected format?

**Comment by darreneng** [comment]
Thanks, I can stick to using numeric identifiers for now. I know the example names provided (`000001.png` and `2.jpg`) are exclusively numerical, but for someone just reading the page it seems like the only requirement is that the file names for the labels and images must match

**Comment by lukeyeager** [comment]
@darreneng I actually thought the same at first, too: https://github.com/NVIDIA/DIGITS/pull/909
