### ISSUE TITLE
which accuracy plot to use on googlenet?

### ISSUE THREAD

**Issue by paras42** [NVIDIA/DIGITS#942]
I believed this may have been asked before.
I am wondering if we are supposed to average all three accuracy layers, or pick the best one (e.g. pink in the graph below)?  Typically also, do people choose the epoch yielding the best accuracy, or choose the final epoch?  I read the GoogLeNet article but couldn't find out from that.

![example_googlenet](https://cloud.githubusercontent.com/assets/20483429/17256331/128aed0c-558b-11e6-9a79-401788f0cd5e.jpg)

**Comment by rmunoz12** [comment]
In response to your first question, the [reference paper](http://arxiv.org/pdf/1409.4842v1.pdf) uses loss3/classifier at test time to classify.  From Section 5:

> At inference time, these auxiliary networks [using loss1/classifier and loss2/classifier] are discarded.

**Comment by gheinrich** [comment]
And in response to the second question:

>  Typically also, do people choose the epoch yielding the best accuracy, or choose the final epoch

We typically choose the model that shows the best accuracy on the **validation set**.

**Comment by paras42** [comment]
Great that's both very helpful. 

Thanks again!

Sent from my iPhone
