### ISSUE TITLE
DIGITS 4. GTX970 accuracy grows during training, GTX1070 accuracy stay constant.

### ISSUE THREAD

**Issue by Smorodov** [NVIDIA/DIGITS#943]
I've installed gtx1070 GPU, additionally to gtx970 card. 

digits 4.1 dev, caffe 0.16, CUDA 8.0, CUDNN v5, nvidia driver 367.35, ubuntu 14.04 LTS. 

Makefile.config :
[Makefile.config.tar.gz](https://github.com/NVIDIA/DIGITS/files/391796/Makefile.config.tar.gz)

And tested them both with MNIST DS, and LeNET network configuration.

For GTX 970 training goes ok, and accuracy increases, loss reducing.
![screenshot from 2016-07-30 11 48 56](https://cloud.githubusercontent.com/assets/1816461/17269292/2ee52914-564d-11e6-8403-0f2894f95736.png)

For GTX 1070 loss and accuracy remains the same during all 30 epochs.
![screenshot from 2016-07-30 11 51 01](https://cloud.githubusercontent.com/assets/1816461/17269294/361bbcd4-564d-11e6-9a58-50aafef36afd.png)

Can you help me please ?

UPD: looks like with NCCL turned on it works.

**Comment by lukeyeager** [comment]
> caffe 0.16

You definitely shouldn't be using the 0.16 branch. That's still experimental.
https://github.com/NVIDIA/caffe/issues/194#issuecomment-231883980
https://github.com/NVIDIA/caffe/issues/187#issuecomment-236445968

> Makefile.config

I suggest you follow these instructions to configure your build with CMake:
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/docs/BuildCaffe.md#build

> UPD: looks like with NCCL turned on it works.

Are you doing multi-GPU training?

**Comment by Smorodov** [comment]
Thank you for your reply, I have 2 GPU installed in system, I tryed single GPU training first, and without NCCL , gtx1070 GPU (primary in my system) did wrong training, while gtx 970 (secondary) worked fine. 

With NCCL turned on, both cards works fine, in single- and in multi-GPU modes.

**Comment by lukeyeager** [comment]
That's pretty weird. This is definitely a Caffe bug and not a DIGITS bug. Would you mind closing this and re-filing your bug over here?
https://github.com/NVIDIA/caffe/issues/new

Especially if you can verify that v0.15 doesn't work correctly without NCCL.
