### ISSUE TITLE
Old jobs lost after DIGITS upgrade

### ISSUE THREAD

**Issue by jmozah** [NVIDIA/DIGITS#95]
I pulled the new version of DIGITS today and restarted DIGITS. Saw some logs like below

Upgrading ImageClassificationDatasetJob to version 2
Upgrading CreateDbTask to version 2
Upgrading CreateDbTask to version 3
Upgrading CreateDbTask to version 2
Upgrading CreateDbTask to version 3

and finally the jobs dont show up in DIGITS anymore... it looks as if i started clean slate...
They are present in "jobs" directory though.
Any chance of recovering them?

**Comment by lukeyeager** [comment]
Ugh, I tested that repeatedly. The upgrade path should have worked. You can try setting `scheduler.verbose=True` on [this line](https://github.com/NVIDIA/DIGITS/blob/v1.1.0/digits/scheduler.py#L30) - that may tell you that there's something simple that needs to be changed. But I fear you probably won't be able to recover your old jobs without some pretty complicated trickery.

Do you know which version of the code (which commit) you had previously, and which version you have now? Or at least a general idea? This needs to be fixed.

**Comment by jmozah** [comment]
i didnt keep a note... i deleted the old volume... i will keep a track of that from now..

**Comment by lukeyeager** [comment]
I'll test the upgrade paths again to make sure I didn't just miss something obvious, but I doubt I'll come up with anything.

It would be super helpful if you could try this out and see if you get any more information for me (no worries if you can't/won't):

1. `rm -r ~/.digits` - clean out old configuration, jobs
1. `git checkout digits-1.0`
1. `./digits-devserver`
1. Create a dataset and model like you did before. Hopefully just a simple test will do. You can get the MNIST set using `tools/download_data/main.py` if you haven't checked that out already.
1. Shut down the server
1. `git checkout v1.1.0`
1. Edit [this line](https://github.com/NVIDIA/DIGITS/blob/v1.1.0/digits/scheduler.py#L30) to say `verbose=True`
1. `./digits-devserver`
1. See if you get any detailed error messages about what went wrong.

**Comment by jmozah** [comment]
some jobs are running... i will do it once they get over...

**Comment by jmozah** [comment]
Checked this today... looks like this was because i moved the jobs directory from one mount point (/data/data/*) to another (/data/*)... 

Upgrading ImageClassificationDatasetJob to version 2
Caught AttributeError while loading job "20150428-012751-5dac":
        'CreateDbTask' object has no attribute 'encode'
Caught OSError while loading job "20150428-034856-63e5":
        [Errno 2] No such file or directory: '/data/data/.digits/jobs/20150428-034856-63e5/'
Caught OSError while loading job "20150428-035342-6a14":
        [Errno 2] No such file or directory: '/data/data/.digits/jobs/20150428-035342-6a14/'

**Comment by lukeyeager** [comment]
Oh really? Thanks for checking that. You're supposed to be able to move the folders around without getting errors, but I haven't tested it in a while. I'll look into it.

**Comment by lukeyeager** [comment]
Should be fixed now. Thanks for investigating.

**Comment by jmozah** [comment]
I pulled it today again and this happened...
The jobs are there in the directory.. but the main page is empty...

./zahoor

**Comment by lukeyeager** [comment]
Try running with the `--config` flag to make sure your jobs directory is still set to the old location.

    ./digits-devserver -c

**Comment by jmozah** [comment]
yeah.. it was using some other directory... fixed it... thanks
