### ISSUE TITLE
Object Detection and OpenCV

### ISSUE THREAD

**Issue by suhalim9** [NVIDIA/DIGITS#952]
Hi,

I am following through the tutorial of object detection. I have installed opencv and am able to import cv2 when I run it on Python script, but it errors when DIGITS's python trying to import it.

What's requirements about opencv? Or what other things would you recommend checking?

Traceback (most recent call last):
File "/home/ai2-c3p0/Documents/code/nv_caffe/python/caffe/layers/detectnet/clustering.py", line 3, in <module>
import cv2 as cv
ImportError: /home/ai2-c3p0/anaconda2/lib/python2.7/site-packages/cv2.so: undefined symbol: _ZN2cv11arrowedLineERNS_3MatENS_6Point_IiEES3_RKNS_7Scalar_IdEEiiid

Thanks,

**Comment by gheinrich** [comment]
Hi @suhalim9 I think there is a mismatch on your system between the version of OpenCV that was used to build Caffe and the version of OpenCV that was used for installing OpenCV Python bindings. You might be able to reproduce this error if you do:
```
$ export PYTHONPATH=/path/to/caffe/python
$ python
>>> import caffe
>>> import cv2
```
If I'm correct then the solution is to install the version of the OpenCV Python bindings that matches the version you used to build Caffe.
