### ISSUE TITLE
Understanding create_db.py under tools 

### ISSUE THREAD

**Issue by afshindn** [NVIDIA/DIGITS#953]
Hi, 

I'm trying to understand the lmdb creation process better. During process you can choose your encoding option(https://github.com/NVIDIA/DIGITS/blob/master/tools/create_db.py#L606-L628). Would you explain this a bit better? What is the encoding for and why you perform the channel swap in one and not in the other? I know there was some discussions in #59 but I'm still a bit confused.

**Comment by gheinrich** [comment]
Hello, when using encoded images we store a `.png` or `.jpg`-encoded image using PIL, which expects image channels in RGB order. Therefore a channel swap is not necessary at this stage. Later on when Caffe reads from the LMDB it uses OpenCV [imread](http://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#imread) to decode the images. By default OpenCV returns images Blue, Green, Red (BGR) order.

When using un-encoded images, in DIGITS we want to store data in the same way as Caffe would receive them if it were using `imread` hence the need to swap channels. I hope this clears things up a little.

**Comment by afshindn** [comment]
The answer was right on point and made things clear. Thanks.

**Comment by afshindn** [comment]
Another quick related question. While working with color spaces other than RGB (let say YCbCr), what would be the best way to create the lmdb? Do we need use the encoding or do any channel swap here?

**Comment by gheinrich** [comment]
Unless you create the LMDB yourself, DIGITS automatically converts YCbCr images to RGB. Do you really need the network to process YCbCr?

**Comment by afshindn** [comment]
I do need to experiment with different color spaces. I was gonna create the LMDB myself and I'm planning to follow the steps in create_db script. If I'm not mistaken, I shouldn't be using any encoding in my case, am I right? Order of channels also shouldn't matter in this case (as long as training and testing is consistent)?

**Comment by lukeyeager** [comment]
> Order of channels also shouldn't matter in this case (as long as training and testing is consistent)?

That's right, it's up to you. But when testing an image in DIGITS it will be converted to BGR for you. So you'll have to test the model manually, too. We're working on improving support for this sort of thing with data extensions.
