### ISSUE TITLE
caffe binary not found in PATH??

### ISSUE THREAD

**Issue by SevenGong** [NVIDIA/DIGITS#955]
When I do the "./digits-devserver",it shows:
Default value for caffe_root "<PATHS>" invalid:
	caffe binary not found in PATH
==================================== Caffe =====================================
Where is caffe installed?

	Suggested values:
	(P*) [PATH/PYTHONPATH] <PATHS>

So I input " /home/XXX/work/deeplearning-tools/caffe-master/build/tools",but it does not work,and  it shows "ERROR: caffe binary not found at "/home/XXX/work/deeplearning-tools/caffe-master/build/tools"
".       

 What should I do??

**Comment by gheinrich** [comment]
You need to provide the path to your Caffe installation without `build/tools`.

**Comment by SevenGong** [comment]
@gheinrich, hello, it works as  you said above. Thank you very much. But it shows a new error:
File "/home/congleng/work/deeplearning-tools/caffe-master/python/caffe/proto/caffe_pb2.py", line 4, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal

I have installed protobuf. Now what should I do?

**Comment by SevenGong** [comment]
@gheinrich,it works as you said.Thank you very much.But it shows a new error:
  File "/home/congleng/anaconda2/lib/python2.7/site-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.socketio


I haved installed Flask.So what should I do to solve this error?

**Comment by SevenGong** [comment]
@gheinrich  hello, the problem above has been solved. I do "pip install flask.socketio".  Thank you very much!

**Comment by gheinrich** [comment]
Hi @SevenGong preferably you should follow the [install instructions](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/docs/BuildDigits.md). You wouldn't have had to manually install `flask.socketio` if you had run the command:
```
[sudo] pip install -r $DIGITS_HOME/requirements.txt
```

**Comment by SevenGong** [comment]
@gheinrich  I  did run the command "pip install -r $DIGITS_HOME/requirements.txt" before . So I are curious when getting the error. 

And I can do "./digits-devserver",but I have a error when doing "./digits-server". The error is:
Error: class uri 'socketio.sgunicorn.GeventSocketIOWorker' invalid or not found: 

[Traceback (most recent call last):
  File "/home/XXX/anaconda2/lib/python2.7/site-packages/gunicorn/util.py", line 142, in load_class
    mod = import_module('.'.join(components))
  File "/home/XXX/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named sgunicorn

What should I solve this problem?

**Comment by SevenGong** [comment]
@gheinrich  I have install gunicorn. So how to solve the problem above?

**Comment by gheinrich** [comment]
Closing this issue since you have opened #958
