### ISSUE TITLE
ImportError: No module named flask.ext.socketio

### ISSUE THREAD

**Issue by SevenGong** [NVIDIA/DIGITS#957]
I need help.  When I do './digits-deserver'. It shows an error:
File "/home/congleng/anaconda2/lib/python2.7/site-packages/flask/exthook.py", line 87, in load_module
raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.socketio

I haved installed Flask.So what should I do to solve this error?

**Comment by gheinrich** [comment]
Reproducing my comment from the other thread here:

You should follow the [install instructions](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/docs/BuildDigits.md). You wouldn't have had to manually install `flask.socketio` if you had run the command:
```
[sudo] pip install -r $DIGITS_HOME/requirements.txt
```
