### ISSUE TITLE
ImportError: No module named layers.detectnet.clustering

### ISSUE THREAD

**Issue by Nernas** [NVIDIA/DIGITS#963]
Hi.

My system setup nvidia caffe 0.15.9 version on windows.
and I used digits 4.0.0 rc3 version for deep learning.

When I tried example object-detection, I got some error this import error message.
digits's said ERROR: error code 1

then I tried command in cmd.
Finally I know that error as from this ImportError.

Another networks dont make error message, and works fine.

How can I solve this problem?

Thanks.

**Comment by gheinrich** [comment]
Hello, make sure your `PYTHONPATH` points to the correct version of Caffe.

**Comment by IsaacYangSLA** [comment]
@Nernas , additionally, can you let us know which document you followed to build nvcaffe in Windows?  The closest document we could find is related to Windows branch of BVLC caffe.  However, that branch does not support detectnet, and its solution/project files do not copy some required files to their destination folder after build process.  You might need to check either caffe/build/x64/release/pycaffe or caffe/python directory to see if it includes detectnet python codes.

**Comment by Nernas** [comment]
@IsaacYangSLA I was referenced on https://github.com/NVIDIA/DIGITS/issues/47 and forked Microsoft too.
I was copy all file build/x64/release/pycaffe files in C:\Miniconda2\Lib\site-packages.
but in build/x64/release/pycaffe, don't exist layers folder. then I can't import layers.detectnet.clustering.

Thank you.

**Comment by IsaacYangSLA** [comment]
@Nernas: thanks for your comments.  It sounded to me you would be able to import layers.detectnet.clustering after you copied files to build/x64/release/pycaffe.  Let me know if you have any other question.

**Comment by szm2015** [comment]
Hi, I don't know whether anyone sees this or not (as it has been closed) but anyway!!! I'm facing the same problem while executing a detectnet inference outside caffe root. I have written an cpp code for inference and when I run it I get the error but when I copy the exe file to caffe root and run it there everything goes on without a problem, I have added caffe_root/python to my PATH and PYTHONPATH like this:
      export PATH=${CAFFE_ROOT}/bin:/home/gpuserver/Moosavi/DIGITS/nv-caffe/python:${PATH}
      export PYTHONPATH="${PYTHONPATH}:/home/gpuserver/Moosavi/DIGITS/nv-caffe/python"

So I don't understand what could be the problem.

**Comment by lukeyeager** [comment]
Try importing caffe and make sure it comes from the right location.

    python -c "import caffe; print caffe.__file__"

**Comment by szm2015** [comment]
I'm not sure that I follow you, but when I run the command you said in terminal, I get this:
     /home/gpuserver/Moosavi/DIGITS/nv-caffe/python/caffe/__init__.pyc
which is the right path

**Comment by lukeyeager** [comment]
Then your `PYTHONPATH` is probably right. What's the error message you're seeing? If it's different from the OP then please open a new issue.

**Comment by szm2015** [comment]
Well I think it's similar, this is the exact error I get:
   ImportError: No module named caffe.layers.detectnet.clustering
   terminate called after throwing an instance of 'boost::python::error_already_set'

As I said the error resolves when I run the exe from caffe root, but remains otherwise. also I'm using a cpp code, so should I open a new issue?

**Comment by lukeyeager** [comment]
Yes, please open a new issue and paste the exact error you're getting, along with any other information you think may be relevant.
