### ISSUE TITLE
DetectNet training error using Kitti data

### ISSUE THREAD

**Issue by gijenk** [NVIDIA/DIGITS#973]
Hello,

I keep getting the error below while trying to training on the tutorial data. Assuming something is configured incorrectly on my machine, but can't seem to locate the issue. Running Digits 4.0, nv-caffe 0.15.9, and opencv 3.0 with python. I can successfully import caffe and cv2, and verified both versions. 

![detectnet_digits](https://cloud.githubusercontent.com/assets/7070900/17653997/eed6c640-626b-11e6-8aa4-ce184a9d5735.jpg)

caffe_output.log
```
...
I0814 18:28:34.232081 35571 solver.cpp:242] Iteration 1176 (0.249317 iter/s, 196.537s/49 iter), loss = 26.7082
I0814 18:28:34.232318 35571 solver.cpp:261]     Train net output #0: loss_bbox = 6.85118 (* 2 = 13.7024 loss)
I0814 18:28:34.232347 35571 solver.cpp:261]     Train net output #1: loss_coverage = 10.3665 (* 1 = 10.3665 loss)
I0814 18:28:34.232377 35571 sgd_solver.cpp:106] Iteration 1176, lr = 1e-05
I0814 18:29:52.763432 35571 solver.cpp:479] Snapshotting to binary proto file snapshot_iter_1197.caffemodel
I0814 18:29:52.873177 35571 sgd_solver.cpp:273] Snapshotting solver state to binary proto file snapshot_iter_1197.solverstate
I0814 18:29:52.958163 35571 solver.cpp:362] Iteration 1197, Testing net (#0)
I0814 18:29:52.958199 35571 net.cpp:723] Ignoring source layer train_data
I0814 18:29:52.958205 35571 net.cpp:723] Ignoring source layer train_label
I0814 18:29:52.958209 35571 net.cpp:723] Ignoring source layer train_transform
*** Aborted at 1471224596 (unix time) try "date -d @1471224596" if you are using GNU date ***
PC: @     0x7fd82e553282 (unknown)
*** SIGSEGV (@0x7fff02010040) received by PID 35571 (TID 0x7fd83ff8aa40) from PID 33620032; stack trace: ***
@     0x7fd83d863cb0 (unknown)
@     0x7fd82e553282 (unknown)
@     0x7fd4242a6d45 pyopencv_from<>()
@     0x7fd42434a431 pyopencv_cv_groupRectangles()
@     0x7fd83e4e60d4 (unknown)
@     0x7fd83e4e6059 (unknown)
@     0x7fd83e4e6059 (unknown)
@     0x7fd83e4e754d (unknown)
@     0x7fd83e51c6d0 (unknown)
@     0x7fd83e488d43 (unknown)
@     0x7fd83e4147bd (unknown)
```
Thanks!

**Comment by lukeyeager** [comment]
Hmm, actually that looks like it might be a bug in the transform layer somewhere. Possibly some corner case that you ran into causes a segmentation fault because of an off-by-one error or something.

Unfortunately I don't know how to debug this without being able to reproduce it. Does this happen for you every time? Always when running the validation pass at epoch 3?

**Comment by gijenk** [comment]
Thanks for the reponse. Yes, this happens on every object detection run at epoch 3. Training a classification model on the same machine works fine. I'm going to try updating opencv and reinstalling everything. Will post back the results.

**Comment by IsaacYangSLA** [comment]
I am guessing the arguments to groupRectangles (line 170 of clustering.py) might be the issue.  The second and third arguments are defined in parameters of that layer, so basically they are constant.  The first argument, proposed bounding boxes, is converted to numpy array, then to list.

@gijenk , can you add some codes to check if propose_boxes is well-formatted during training on your dataset?

**Comment by gijenk** [comment]
Update - I reinstalled everything and it's working fine using kitti and my own data. The one thing I did discover was some older opencv libs (2.4) that got installed with sudo apt-get install digits. I updated these and it seems to work. 

Thanks for looking into this!

**Comment by MacroHongJian** [comment]
Is using opencv3.1 faster than opencv2.4? Two epochs took me 11h. I use gtx1070 cuda8 14.04

**Comment by mescarra** [comment]
Same issue here. Followed DIGITS DetectNet tutorial with Kitti dataset. In my case it happens during the first validation after the first epoch. I'm glad you could solve it @gijenk but I have just installed everything. Don't want to do it again, and I honestly don't think it would solve anything. What should I do?

I also see digits installed OpenCV-2.4 libraries, but I'm pretty sure it is using OpenCV-3.1 (`[sudo] python -c "import cv2; print(cv2.__version__)" both print 3.1.0-dev`. Do I want digits to use OpenCV-2.4?

`I1220 14:25:54.077791 26816 net.cpp:723] Ignoring source layer train_data
I1220 14:25:54.077798 26816 net.cpp:723] Ignoring source layer train_label
I1220 14:25:54.077803 26816 net.cpp:723] Ignoring source layer train_transform
*** Aborted at 1482254754 (unix time) try "date -d @1482254754" if you are using GNU date ***
PC: @     0x7f07d8407a02 cv::Mat::copyTo()
*** SIGSEGV (@0x7ffe02010040) received by PID 26816 (TID 0x7f07ed0679c0) from PID 33620032; stack trace: ***
@     0x7f07ea83dcb0 (unknown)
@     0x7f07d8407a02 cv::Mat::copyTo()
@     0x7f0459a160b5 pyopencv_from<>()
@     0x7f0459b50792 pyopencv_cv_groupRectangles()
@     0x7f07eb4cf0d4 (unknown)
@     0x7f07eb4cf059 (unknown)
@     0x7f07eb4cf059 (unknown)
@     0x7f07eb4d054d (unknown)
@     0x7f07eb5056d0 (unknown)
@     0x7f07eb471d43 (unknown)
@     0x7f07eb3fd7bd (unknown)
@     0x7f07eb471d43 (unknown)
@     0x7f07eb4ea577 (unknown)
@     0x7f07eb42d617 (unknown)
@     0x7f05682e8705 (unknown)
@     0x7f07ec3dd0d8 (unknown)
@     0x7f07ec3dd457 (unknown)
@     0x7f07ec3f4eba (unknown)
@     0x7f07ec3f573e (unknown)
@     0x7f07ec3f7d0d (unknown)
@     0x7f07ec3f86ce (unknown)
@           0x40af36 (unknown)
@           0x40867c (unknown)
@     0x7f07ea828f45 (unknown)
@           0x408e4d (unknown)
@                0x0 (unknown)
`

**Comment by mescarra** [comment]
Well, solution found here (website in japanese):
https://soralab.space-ichikawa.com/2016/08/digits4-error/

The problem was OpenCV's version. To solve I had to install version OpenCV-2.4 and make it the default 
version:
```
$ sudo apt-get --reinstall install python-opencv
$ python -c "import cv2; print (cv2 .__version__)" 
2.4.8
```

**Comment by sulth** [comment]
Still it is showing the python version python -c "import cv2; print(cv2.__version__)"
3.3.0
How can i solve it.My digits server is showing error.

**Comment by YoungSharp** [comment]
@ sulth you can delete make a backup of cv.py and cv.pyc and cv2.so in /usr/lib/python2.7/dist-packages and then using sudo apt-get --reinstall install python-opencv, then you may get a right python-opencv version.
my python-opencv was installed in /opt/ros/kinetic/lib/python2.7/dist-packages, so I just delete cv2.so in that directory.
Then I can get the right version of python-opencv.
