### ISSUE TITLE
Eltwise layer not detected?

### ISSUE THREAD

**Issue by mpbrigham** [NVIDIA/DIGITS#975]
Hello!

I receive the following error when declaring an Elementwise layer:

> Bad network: Not a valid NetParameter: 103:9 : Enum type "caffe.V1LayerParameter.LayerType" has no value named "Eltwise".

```
layer {
  name: "conv1-1"
  type: "Convolution"
  bottom: "data"
  top: "conv1-1"
  param { lr_mult: 1.0 }
  param { lr_mult: 2.0 }
  convolution_param {
    num_output: 32
    kernel_size: 1
    stride: 1
    pad: 0
    weight_filler { type: "xavier" }
    bias_filler { type: "constant" }
  }
}
layer {
  name: "conv1-3"
  type: "Convolution"
  bottom: "data"
  top: "conv1-3"
  param { lr_mult: 1.0 }
  param { lr_mult: 2.0 }
  convolution_param {
    num_output: 32
    kernel_size: 3
    stride: 1
    pad: 1
    weight_filler { type: "xavier" }
    bias_filler { type: "constant" }
  }
}
layers {
  name: "maxout1"
  type: "Eltwise"
  bottom: "conv1-1"
  bottom: "conv1-3"
  top: "maxout1"
  eltwise_param {
    operation  { type: "max" }
  }
}

```

If I use `type: ELTWISE` and `eltwise_param { operation:MAX }` instead, I no longer get an error, but the top "maxout1" is no available, i.e. the following layer fails:

```
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "maxout1"
  top: "relu1"
}
```
Thanks!

**Comment by lukeyeager** [comment]
Looks like you're mixing up `layer` and `layers`

**Comment by mpbrigham** [comment]
Death by cut-and-paste! Thank you for the heads-up Luke. :-)

For reference, here is the correct syntax:

```
layer {
  name: "maxout1"
  type: "Eltwise"
  bottom: "conv1-1"
  bottom: "conv1-3"
  top: "maxout1"
  eltwise_param { operation: MAX}
  }
}
```

This implements a maxout layer that outputs the maximum value pixel-wise across the convolution layers.
