### ISSUE TITLE
A more detailed introduction in some important file.

### ISSUE THREAD

**Issue by JulyUp** [NVIDIA/DIGITS#979]
These days, I try to read the source codes of digits. Though the name of some files and functions are obvious, but as I am not familiar with the web, it is difficult  to understand how web parse the web parameters and input them to torch and caffe. So I suggest a more detailed introduction about some file and functions.

**Comment by lukeyeager** [comment]
I'm happy to help answer a specific question about some aspect of the DIGITS source code.

**Comment by JulyUp** [comment]
@lukeyeager  Can you tell me when and where the funtion "task_arguments" in module "torch_train.py" is called?

**Comment by lukeyeager** [comment]
Scheduler starts the task - https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/scheduler.py#L401
Calls `task.run()` - https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/scheduler.py#L507
Task calls `task_arguments()` - https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/task.py#L187

**Comment by JulyUp** [comment]
@lukeyeager Thank you. I got it. But I do not know when and where those nets in module"standard-networks" are used?

**Comment by JulyUp** [comment]
@lukeyeager  Are just those nets in module"standard-networks" some references when we use caffe_train.py or torch_train.py to write some networks into job_dir?  I look through the related files but can not find that those nets in module"standard-networks" are callled anywhere.

**Comment by gheinrich** [comment]
All supported Deep Learning frameworks (i.e. Caffe and Torch7) implement the same interface. The interface is defined in [framework.py](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/digits/frameworks/framework.py). The Caffe version is [caffe_framework.py](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/digits/frameworks/caffe_framework.py). The Torch version is [torch_framework.py](https://github.com/NVIDIA/DIGITS/blob/digits-4.0/digits/frameworks/torch_framework.py). In this interface there is a method called `get_standard_network_desc` that all frameworks must implement. This is where we are getting the network description for the standard networks.

**Comment by JulyUp** [comment]
@gheinrich Thank you. I have read the  function "get_standard_network_desc" in  caffe_framework.py and torch_framework.py. Though we get a standard net using the function, but where the standard net will be used?      The train_val.prototxt in a new job_dir seems to be created by caffe_train.py.  Sorry, I am wondering.  Would you like to explain to me again?

**Comment by gheinrich** [comment]
Make a little effort and look for references to `get_standard_network_desc`. You will see that it's used in two places:
- [there](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/model/views.py#L50), in the `digits.models.views.customize` route, which if you look further is accessed by the classification model template [there](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/templates/models/images/classification/new.html#L378) when you click the `customize` button on a standard network,
- [there](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/model/images/classification/views.py#L160), when we create a new image classification model from one of the standard networks.

**Comment by JulyUp** [comment]
@gheinrich Thank you very much. I am very sorry that I did not see the customize botton because it is a little bit small. Now I can understand further. Thank you. Any question, I will ask you later.

**Comment by JulyUp** [comment]
@gheinrich Now I am confused that how the module will be called when we click the button 'Create' in ' New Image Classification Dataset'.  What is the process and when and where the module '/dataset/task/create_db.py' is called?

**Comment by gheinrich** [comment]
It all starts [there](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/dataset/images/classification/views.py#L278). Then follow the code.

**Comment by SevenGong** [comment]
@gheinrich  Thank you very much.
To add a function to create rec format data used by the framework 'mxnet', I modify the tools/create_db.py. I do a pull requests for this create_db.py, and you can check it. Meanwhile I modify the dataset/images/classification/forms.py as follows:

`class ImageClassificationDatasetForm(ImageDatasetForm):
    """
    Defines the form used to create a new ImageClassificationDatasetJob
    """

    backend = wtforms.SelectField('DB backend',
            choices = [
                ('lmdb', 'LMDB'),
		('rec', 'REC'),
                ('hdf5', 'HDF5'),
                ],
            default='lmdb',
            )

    def validate_backend(form, field):
        if field.data == 'lmdb':
            form.compression.data = 'none'
	elif field.data == 'rec':
            form.compression.data = 'none'
        elif field.data == 'hdf5':
            form.encoding.data = 'none'`

But the digits do not work to create a rec database.What else should I modify?

**Comment by JulyUp** [comment]
@gheinrich Can you see my pull request ?

**Comment by SevenGong** [comment]
@gheinrich  can you see my pull request?

**Comment by JulyUp** [comment]
@lukeyeager When I click the button 'create' in new image classification model, how will the digits's codes run? When and where are the function 'create()' in model/images/classification/view.py and caffe_train.py or torch_train.py in models/tasks/ called?

**Comment by JulyUp** [comment]
@gheinrich As you said, I try my best to trace the code when I click the button 'create' in module 'new image classification'. But I still do not know where the function 'scheduler/main_thread' is called. Can you tell me?
Looking forward to your response.Thank you very very much.

**Comment by gheinrich** [comment]
I am not sure which function you are referring to. Please post a link.
