### ISSUE TITLE
AdaGrad and NAG solver options in digits

### ISSUE THREAD

**Issue by Tutufa** [NVIDIA/DIGITS#98]
How to choose different solvers in digits interface. There is a lot of options for learning rate changes policy, but I cant find a way to choose AdaGrad or NAG. Can someone help me?

**Comment by lukeyeager** [comment]
Those are not supported yet, but I think it should be pretty trivial to add them.

From what I'm seeing, only SGD, Nesterov and AdaGrad are supported in caffe. Is NAG the same as Nesterov?
https://github.com/BVLC/caffe/blob/cd0eda338e59e15b833e601061a493fd975e2ee3/src/caffe/proto/caffe.proto#L179-L184

**Comment by Tutufa** [comment]
@lukeyeager yep, NAG is Nesterov. Im surprised its not in digits yet, since they are in caffe. This solvers give much faster and better results.

**Comment by lukeyeager** [comment]
> I'm surprised its not in digits yet, since they are in caffe.

It should be trivial to add, I just hadn't heard anyone ask for it yet. I'm working on #96 right now, I'll get to this soon.

If you want to beat me to it, you can add a form field [here](https://github.com/NVIDIA/DIGITS/blob/v1.1.0/digits/model/forms.py) and [here](https://github.com/NVIDIA/DIGITS/blob/v1.1.0/digits/templates/models/images/classification/new.html), then pass it along to [this function](https://github.com/NVIDIA/DIGITS/blob/v1.1.0/digits/model/tasks/caffe_train.py#L109).

**Comment by Tutufa** [comment]
@lukeyeager Im not good with html :-/ and Im a bit in a rush. Maybe later, this summer, I will try to help.
