### ISSUE TITLE
Digits 4.0 Custom Network bug

### ISSUE THREAD

**Issue by gonzalo-invesmente** [NVIDIA/DIGITS#982]
Hello
I'm trying to implement a custom network with torch but new Digits 4.0 don't display any space to write the model.

**Comment by lukeyeager** [comment]
Maybe try a hard refresh (`Ctrl` + `F5`)?

**Comment by gonzalo-invesmente** [comment]
fixed!! 
thank you!

**Comment by lukeyeager** [comment]
You're welcome. Sorry for the inconvenience, but we can't really fix this for this release. 

https://github.com/NVIDIA/DIGITS/pull/904 should solve the problem going forward.
