### ISSUE TITLE
Install instructions fail on 16.04

### ISSUE THREAD

**Issue by bbrock171** [NVIDIA/DIGITS#986]
Error caused is: `Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Release  No Hash entry in Release file /var/lib/apt/lists/partial/developer.download.nvidia.com_compute_cuda_repos_ubuntu1404_x86%5f64_Release which is considered strong enough for security purposes`

This is a known issue listed [here](https://wiki.debian.org/Teams/Apt/Sha1Removal) presumably caused by the apt SHA1 removal. 

Recommended action is "Repository owners should make sure their release files and Packages files contain SHA256 or SHA512 fields. If they have Sources files, those should contain Checksums-Sha256."

**Comment by lukeyeager** [comment]
In order to run DIGITS on 16.04, you'll need to:

* Install CUDA 8.0 by downloading it from [this site](https://developer.nvidia.com/cuda-toolkit)
* Build Caffe and DIGITS from source (since we don't have deb packages for 16.04 yet)
