### ISSUE TITLE
Training DetectNet: ERROR: error code -11

### ISSUE THREAD

**Issue by thxmxx** [NVIDIA/DIGITS#995]
Following the tutorial below
https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection
I'm getting the error -11 while start training the network..

Cuda: 7.5
cuDNN: 5
Ubuntu 14.04
GeForce GTX Titan X

```
ERROR: error code -11
Memory required for data: 1274879360
Creating layer bbox_loss
Creating Layer bbox_loss
bbox_loss <- bboxes-obj-masked-norm
bbox_loss <- bbox-obj-label-norm
bbox_loss -> loss_bbox
Setting up bbox_loss
Top shape: (1)
with loss weight 2
Memory required for data: 1274879364
Creating layer coverage_loss
Creating Layer coverage_loss
coverage_loss <- coverage_coverage/sig_0_split_0
coverage_loss <- coverage-label_slice-label_4_split_0
coverage_loss -> loss_coverage
Setting up coverage_loss
Top shape: (1)
with loss weight 1
Memory required for data: 1274879368
Creating layer cluster
```

```
I0823 18:28:09.720865 17689 net.cpp:435] blramos@motodeep-Precision-WorkStation-R5500:/tmp$ tail caffe.INFO 
I0823 18:28:09.720737 17689 net.cpp:94] Creating Layer bbox-obj-norm
I0823 18:28:09.720746 17689 net.cpp:435] bbox-obj-norm <- bboxes-masked-norm
I0823 18:28:09.720757 17689 net.cpp:435] bbox-obj-norm <- obj-block_obj-block_0_split_1
I0823 18:28:09.720769 17689 net.cpp:409] bbox-obj-norm -> bboxes-obj-masked-norm
I0823 18:28:09.720815 17689 net.cpp:144] Setting up bbox-obj-norm
I0823 18:28:09.720829 17689 net.cpp:151] Top shape: 2 4 24 78 (14976)
I0823 18:28:09.720836 17689 net.cpp:159] Memory required for data: 1274879360
I0823 18:28:09.720844 17689 layer_factory.hpp:77] Creating layer bbox_loss
I0823 18:28:09.720857 17689 net.cpp:94] Creating Layer bbox_loss
I0823 18:28:09.720865 17689 net.cpp:435] blramos@motodeep-Precision-WorkStation-R5500:/tmp$ tail caffe.WARNING 
Log file created at: 2016/08/23 18:28:07
Running on machine: motodeep-Precision-WorkStation-R5500
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0823 18:28:07.588670 17689 upgrade_proto.cpp:1053] Note that future Caffe releases will only support 'type' field (string) for a solver's type.
lramos@motodeep-Precision-WorkStation-R5500:/tmp$
```

Even the caffe.INFO is broken.

Any clue?

**Comment by lukeyeager** [comment]
Those logs aren't super helpful. Do you have `python-opencv` installed?

**Comment by thxmxx** [comment]
I'm using opencv 3.1 with python-opencv

**Comment by lukeyeager** [comment]
So do you have a mismatch between your OpenCV versions? The Ubuntu `python-opencv` deb package installs v2.4:
http://packages.ubuntu.com/trusty/python-opencv

**Comment by thxmxx** [comment]
Solved. Just recompiled NVCaffe with python-opencv 2.4.

Ty :)

**Comment by sulth** [comment]
Hi ,Iam getting error on training after epoch 30:
* Aborted at 1507318546 (unix time) try "date -d @1507318546" if you are using GNU date ***
PC: @     0x7f6cb50bfb96 strlen
*** SIGSEGV (@0x7ffd00000587) received by PID 16880 (TID 0x7f6cb776eac0) from PID 1415; stack trace: ***
@     0x7f6cb506a4b0 (unknown)
@     0x7f6cb50bfb96 strlen
@     0x7f6cb5081980 (unknown)
@     0x7f6cb50824a6 _IO_vfprintf
@     0x7f6cb514ab64 __vsprintf_chk
@     0x7f6ca16fd1ec _ZN2cv6formatB5cxx11EPKcz
@     0x7f6ca16fd2ab cv::Exception::formatMessage()
@     0x7f6ba7e27921 cv::Exception::Exception()
@     0x7f6ba7e273f8 cv::error()
@     0x7f6ba7e2a450 cv::TLSDataContainer::gatherData()
@     0x7f6ba7e2cbd8 cv::utils::trace::details::TraceManager::~TraceManager()
@     0x7f6cb506eff8 (unknown)
@     0x7f6cb506f045 exit
@     0x7f6cb5055837 __libc_start_main
@           0x408dd9 _start
@                0x0 (unknown)
 I dont know how to solve this.Please help me
