### ISSUE TITLE
72:3 : Message type "caffe.LayerParameter" has no field named "detectnet_groundtruth_param"

### ISSUE THREAD

**Issue by JVR32** [NVIDIA/DIGITS#996]
Hello,

I have been using a (recent) working 'caffe'-implementation and a working 'digits'-implementation to test the classification of images (using Windows) -> did not use NVcaffe. 
No problems there.

Now I want to run some tests on object detection. I created a database, and that completed successfully. But when I load and visualize the 'detectnet_network.prototxt' in 'custom network' while training a model, I get the error -> 72:3 : Message type "caffe.LayerParameter" has no field named "detectnet_groundtruth_param".

Browsing the internet provided the following solution : 
_-> "You need the caffe-0.15 branch instead of the caffe-0.14 branch. We'll update the Windows doc shortly."_

Is there another way using a working caffe implementation? Perhaps make a few changes to the working caffe version, rather than trying to compile NVcaffe0.15 under Windows? 

Running the classification was possible using a caffe implementation and digits, not using NVcaffe. I suppose this also can be the case for object detection?

With kind regards.

**Comment by gheinrich** [comment]
> Is there another way using a working caffe implementation? Perhaps make a few changes to the working caffe version, rather than trying to compile NVcaffe0.15 under Windows?

Why are you asking?

DetectNet relies on many changes from NV-Caffe 0.15 that are not in NV-Caffe 0.14 (or the main BVLC fork of Caffe). Incorporating those changes in NV-Caffe 0.14 would defeat your purpose of using a proven version of Caffe (there are just too many of those changes). It is much safer to move on to NV-Caffe 0.15.

**Comment by JVR32** [comment]
I was asking because I already compiled the caffe version from [https://github.com/BVLC/caffe/tree/windows]. As you know, this caffe doesn't need digits. I ran some experiments with that caffe-version. After that, I 'discovered' digits, so I got digits to compare the results, and got it working with my working caffe compilation. There were no problems while testing image classification.
Now I want to run some tests on object detection, so I wanted to use digits and my caffe version. And then I got the error I mentioned. So I was hoping to fix the error, rather than -again- spend multiple hours (or days) to get NVcaffe running. I suppose getting NV-Caffe ready isn't that much work on Ubuntu, but using Windows, I think it is a different story ...

**Comment by lukeyeager** [comment]
@JVR32 see these discussions for getting DetectNet support on Windows:
https://github.com/NVIDIA/caffe/pull/199
https://github.com/Microsoft/caffe/pull/117

**Comment by IsaacYangSLA** [comment]
@JVR32, codes required for DetectNet is not inside BVLC Caffe.  In the second [link](https://github.com/Microsoft/caffe/pull/117) of Luke's comments, I mentioned a branch of Caffe that I used to run DetectNet on Windows.  You might consider trying it.

**Comment by JVR32** [comment]
@IsaacYangSLA : I did try that link, however it still doesn't work for me.

I used [https://github.com/isaacyangsla/caffe/tree/windows]. No problem there building caffe.
1 hour ago, I (again) downloaded [https://github.com/NVIDIA/DIGITS] -> master branch.

I'm able to start DIGITS, but as soon as I press 'visualize' while making a model for object detection, I get the error message. So, something must still be wrong.

Image classification works, so I suppose caffe is okay. But the object detection ... still no luck with it  :-(

**Comment by JVR32** [comment]
Note : for building caffe, I download the code from [https://github.com/isaacyangsla/caffe/tree/windows], loaded 'caffe-windows\windows\Caffe.sln' in VS2013, and did a 'rebuild all'.  Succeeded!

Did I skipped something by doing that, or should it work like that?

**Comment by JVR32** [comment]
Solved that problem. 

I forgot the following requirement : 

> -> copy folder <caffe_root>\Build\x64\Release\pycaffe\caffe under <python_root>\lib\site-packages.

I did it with the previous CAFFE-build, but I had to do it again after building the newer version since there are changes to that part.

**Comment by Bardo91** [comment]
I am having the same problem. I am using current master branch of caffe https://github.com/BVLC/caffe which is above v1.0. Why is the layer not supported there? isn't is suppose to be above v0.15?
