### ISSUE TITLE
ERROR: Check failed: 'ptr_' Must be non NULL

### ISSUE THREAD

**Issue by zheng-yan** [NVIDIA/DIGITS#999]
How could i fix this error?

This error occur when i follow this guide at Training DetectNet
https://github.com/NVIDIA/DIGITS/blob/digits-4.0/examples/object-detection/README.md

log:
Ignoring source layer loss2/relu_conv
Ignoring source layer loss2/fc
Ignoring source layer loss2/relu_fc
Ignoring source layer loss2/drop_fc
Ignoring source layer loss2/classifier
Ignoring source layer loss2/loss
Ignoring source layer pool4/3x3_s2
Ignoring source layer pool4/3x3_s2_pool4/3x3_s2_0_split
Ignoring source layer pool5/7x7_s1
Ignoring source layer pool5/drop_7x7_s1
Ignoring source layer loss3/classifier
Ignoring source layer loss3/loss3
Starting Optimization
Solving
Learning Rate Policy: step
Iteration 0, Testing net (#0)
Ignoring source layer train_data
Ignoring source layer train_label
Ignoring source layer train_transform
Check failed: 'ptr_' Must be non NULL

**Comment by gheinrich** [comment]
Hi, is this the full `caffe_output.log` file?

**Comment by zheng-yan** [comment]
I0909 15:36:20.571008 31478 caffe.cpp:231] Starting Optimization
I0909 15:36:20.571018 31478 solver.cpp:304] Solving
I0909 15:36:20.571022 31478 solver.cpp:305] Learning Rate Policy: step
I0909 15:36:20.575285 31478 solver.cpp:362] Iteration 0, Testing net (#0)
I0909 15:36:20.575297 31478 net.cpp:723] Ignoring source layer train_data
I0909 15:36:20.575302 31478 net.cpp:723] Ignoring source layer train_label
I0909 15:36:20.575306 31478 net.cpp:723] Ignoring source layer train_transform
F0909 15:36:20.734946 31478 gpu_memory.hpp:72] Check failed: 'ptr_' Must be non NULL
*** Check failure stack trace: ***
@     0x7fd033630ea4  (unknown)
@     0x7fd033630deb  (unknown)
@     0x7fd0336307bf  (unknown)
@     0x7fd033633a35  (unknown)
@     0x7fd033d96ec6  google::CheckNotNull<>()
@     0x7fd033d97c1a  caffe::CuDNNConvolutionLayer<>::Forward_gpu()
@     0x7fd033d57a32  caffe::Net<>::ForwardFromTo()
@     0x7fd033d57b57  caffe::Net<>::Forward()
@     0x7fd033d2e691  caffe::Solver<>::Test()
@     0x7fd033d2f07e  caffe::Solver<>::TestAll()
@     0x7fd033d31eb7  caffe::Solver<>::Step()
@     0x7fd033d32c09  caffe::Solver<>::Solve()
@           0x40e63f  train()
@           0x40b5dd  main
@     0x7fd032101a40  (unknown)
@           0x40bed9  _start
@              (nil)  (unknown)

**Comment by lukeyeager** [comment]
What version of caffe are you using?
```
$ build/tools/caffe -version
caffe version 0.15.13
```

**Comment by zheng-yan** [comment]
$ build/tools/caffe -version
caffe version 0.15.10

**Comment by zheng-yan** [comment]
thanks!!
use caffe version 0.15.13
it works
